### ISSUE TITLE
Does installing extensions from Store makes them check it for updates?

### ISSUE THREAD

**Issue by 9Morello** [Eloston/ungoogled-chromium#10]
I read somewhere that Chromium frequently connects to Google to check if the extensions are up to date. Does this version do that?

**Comment by Eloston** [comment]
[No, it does not](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/iridium-browser/first_run-deactivate-autoupdate-globally.patch). Also, an [infobar](https://www.chromium.org/user-experience/infobars) should show up when the browser tries to connect to Google on its own.

**Comment by 9Morello** [comment]
Thats nice, thanks for clarifying.
