### ISSUE TITLE
Hidden chrome flag to disable autoplay?

### ISSUE THREAD

**Issue by ObeseChicken** [Eloston/ungoogled-chromium#1000]
I have discovered the old autoplay policies are still usable from the command line.

--autoplay-policy=user-gesture-required is supposed to return the old autoplay behavior. Any wat to expose this in chrome://flags for users and to ensure chrome cannot take it away from us?

**Comment by Eloston** [comment]
If they removed it from `chrome://flags`, I think that means they're going to phase it out eventually or integrate it further (e.g. via `chrome://settings` or forced on). Is there a crbug tracking autoplay policies?

**Comment by ObeseChicken** [comment]
No crbug I can find:

https://www.chromium.org/audio-video/autoplay
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

They throw us under the bus and remove the option to block autoplay easily from the GUI.

The question is do you keep the flags with a patch (whenever they remove) or let chrome torture us with auto playing video. The extensions to stop it don't work very well.

I had found this in a discussion with a developer but I'm having trouble looking it up again.

**Comment by ObeseChicken** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/1593800

**Comment by Marek33** [comment]
Can we have this _issue_ reopen? It's one of the few things, which are missing in the Ungoogled, and it's very useful to me.

**Comment by networkException** [comment]
There is an optional patch available here: https://github.com/ungoogled-software/contrib/commit/6c03539300d5e7a3346db83957ad9333a4d6b914

See #1565

**Comment by Marek33** [comment]
Thanks! However, how does the patching work? Or will it be hopefully added in the new version? I have Windows 7, so I don't know if it can be recompiled, since apparently only Win10/11 can recompile the Chromium binaries.
