### ISSUE TITLE
Add HTTP referer options - only for same domain

### ISSUE THREAD

**Issue by eggplanting** [Eloston/ungoogled-chromium#1007]
Hello,

it would be great to get more control over the HTTP referer. The referer is enabled per default and readable by every website, which is a privacy issue. Disabling the referer completely via "--no-referrers" is no option, since it breaks website functionality.

The best way to handle the HTTP referer would be a new entry for chrome://flags, with an identical function to the implementation of Firefox: https://wiki.mozilla.org/Security/Referrer

**Firefox implementation**
network.http.referer.XOriginPolicy
controls whether or not to send a referrer across origins values:
0 = (default) send the referrer in all cases
1 = send a referrer only when the base domains are the same
2 = send a referrer only on same-origin

Options 1 and 2 would add a valuable addition to privacy. 0 is already the default.

**Comment by Peacock365** [comment]
I had a similar request, it‘s fixed now: 

https://github.com/Eloston/ungoogled-chromium/issues/1117

https://github.com/Eloston/ungoogled-chromium/commit/103669ffdb9467bc9456e7fb36604534982d6d62
