### ISSUE TITLE
Clean pre-complied binairies in third_party

### ISSUE THREAD

**Issue by perfect7gentleman** [Eloston/ungoogled-chromium#1013]
```
find third_party -type f \( -name '*.so' -o -name '*.o' \) -print -delete
find third_party -type f \( -name '*.la' -o -name '*.a' \) -print -delete
```

**Comment by Eloston** [comment]
Sorry, could you fill me in on the context here?

**Comment by PF4Public** [comment]
I suppose, that @perfect7gentleman refers to the fact, that downloaded chromium tarball has a lot of precompiled binaries.

I think, the question is, do they need to be removed in a "prune_binaries.py" after all the others?

Do they pose any harm?

**Comment by Eloston** [comment]
Am I overlooking something here? Why would we need this if we have `devutils/update_lists.py`?

I did a quick look through `pruning.list` and found a few hits for files matching those find commands...

**Comment by perfect7gentleman** [comment]
After pruning blobs there a lot of pre-complied binaries in 'third_party' are left. If you add them at 'pruning.list' that would great.

**Comment by Eloston** [comment]
Most of those files are empty. This command finds those that are not empty:

```sh
find third_party/ -type f \( -name '*.so' -o -name '*.o' -o -name '*.la' -o -name '*.a' \) -size +0 -print 
```

There are not many files remaining, and they all look like text files. I don't see what the problem is.

**Comment by perfect7gentleman** [comment]
Yes, you're right. I don't think that that can be of zero size.
