### ISSUE TITLE
chrome://flags#extension-mime-request-handling is broken

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#1014]
As reported in https://github.com/Eloston/ungoogled-chromium/issues/923#issuecomment-609499868

**Comment by jstkdng** [comment]
Weird, is this a windows only problem? I'm under arch with chromium version 81.0.4044.122 and that flags works normally, tested in a new profile just to be sure. I'm using my own fork of ungoogled-chromium-archlinux ofc.
Could the culprit be zlib? currently I'm not patching anything related to it in my fork (used to do it some versions ago), and just compiling with the system's zlib.

**Comment by PF4Public** [comment]
Just my 50 cents to this issue. For some reason, trying to update Cromium web store itself results in downloading the crx. Trying to update other extensions works fine.

I suppose, there must be something with downloading *.crx from outside of Google's web store…

**Comment by Eloston** [comment]
This isn't ready to be closed yet. Gonna need testers for 7d240d1fa5a54d5444fd0639d0d4894e17c891d9 in case I broke Chromium's downloading or "open file after downloading" logic.

**Comment by Eloston** [comment]
@jstkdng This isn't a Windows-only problem. I've seen this on Debian buster 81.0.4044.113. I can reproduce what @PF4Public has reported.

**Comment by Eloston** [comment]
Okay, I did some more thorough testing and I don't observe any behavioral before or after https://github.com/Eloston/ungoogled-chromium/commit/7d240d1fa5a54d5444fd0639d0d4894e17c891d9. I'm guessing Chromium Web Store's behavior is specific for itself. It seems this issue was created too hastily...

If you are on a browser with broken drag-and-drop, a way to open extensions is to open the CRX with the `file://` URL scheme. This will happen if you type one in manually in the Omnibox or you launch Chromium with a file path as an argument. I think this was mentioned somwhere before, but it isn't documented in the FAQ so I'll add it there.

Finally, the changes to this patch don't exhibit any behavioral differences and is larger than before, so I'll revert it.

**Comment by jstkdng** [comment]
I still think it is related to zlib. That has to be fixed on each platform repositories though.
