### ISSUE TITLE
Dark UI in Linux?

### ISSUE THREAD

**Issue by awsms** [Eloston/ungoogled-chromium#1016]
Hi, I just installed ungoogled-chromium on my Windows partition and I noticed the whole UI was dark by default. On both of my Linux machines (one running the appimage, the other one the package from the ppa), the whole menus are white. Is it an expected behaviour? If yes, is there a way to turn it completely dark, like on the Windows build? Or maybe this has something to do with GTK? I'm pretty lost tbh :laughing: 
![image_2020-04-24_10-13-39](https://user-images.githubusercontent.com/48278661/80291958-78160b00-8752-11ea-808d-94373c3f9d8b.png)
![Screenshot from 2020-04-26 00-13-00](https://user-images.githubusercontent.com/48278661/80291995-d216d080-8752-11ea-9f59-5c1e37286941.png)

**Comment by jstkdng** [comment]
Just use these flags when starting chromium
```
--force-dark-mode
--enable-features=WebUIDarkMode
```

**Comment by awsms** [comment]
> Just use these flags when starting chromium
> 
> ```
> --force-dark-mode
> --enable-features=WebUIDarkMode
> ```

Thank you!

**Comment by PF4Public** [comment]
@jstkdng Does #enable-force-dark work for you in 85? On my system, it inverts the content, Developer tools, but not the UI: tabs, address bar, menu are all still white.

**Comment by jstkdng** [comment]
@PF4Public 
Yeah, if you use the GTK+ theme it will depend on your current theme. Using the classic option makes everything dark regarldess of the GTK theme.

**Comment by fariszr** [comment]
why can't the browser detect the system's theme ?

**Comment by coughingmouse** [comment]
> Just use these flags when starting chromium
> 
> ```
> --force-dark-mode
> --enable-features=WebUIDarkMode
> ```

To further help mitigate the issue for those who are wondering how they can force dark mode permanently but not use Google's "Force Dark Mode for Web Contents" e.g. because honestly [Dark Reader](https://darkreader.org/) is better, I would like to quote [this post](https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/8#issuecomment-761813448):

> @pashinskikh If you're asking for a good way to do this, you'd create a file with full path `~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf` and the contents of this should be:
> ```
> --force-dark-mode
> --enable-features=WebUIDarkMode
> ```
