### ISSUE TITLE
Question: how can I verify that `ungoggled_chromium` is used, and not `chromium`

### ISSUE THREAD

**Issue by chrisdane** [Eloston/ungoogled-chromium#1017]
Hi

After successfull installation of `ungoogled_chromium` on Arch Linux (took over 10 hours!), I cannot find any `*ungoogled*` binary but only a binary called `chromium`, just as the one of the original chromium browser.

How can I verify that the new "ungoogled" version of the chromium browser is used? These specs are displayed after the installation of `ungoogled_chromium`:
```
$ chromium --version
Chromium 80.0.3987.163 Arch Linux
$ which chromium
/usr/bin/chromium
$ pacman -Qi chromium
<some info text about the `chromium` package>
$ pacman -Qi ungoogled-chromium
<exactly the same info text about the `ungoogled-chromium` package>
```

Also within the browser I cannot find anything that distinguishes `ungoogled-chromium` from the original `chromium`:
```
Chromium -> About Chromium -> Version 80.0.3987.163 (Developer Build) Arch Linux (64-bit)
```

This is rather a question, and not an issue.
 
Thanks for any answer!
Chris

**Comment by qvint** [comment]
Press F1. ungoogled-chromium will open an error page.

**Comment by chrisdane** [comment]
Thanks.

**Comment by PF4Public** [comment]
>Also within the browser I cannot find anything that distinguishes ungoogled-chromium from the original chromium:

But that's by design!
Quote from readme:

> ungoogled-chromium retains the default Chromium experience as closely as possible. Unlike other Chromium forks that have their own visions of a web browser, ungoogled-chromium is essentially a drop-in replacement for Chromium.

**Comment by chrisdane** [comment]
Thanks @PF4Public, thats totally fine. For me one little thingy like the F1 button is already enough, but this is not mentioned anywhere. I m wondering to put this in the readme or FAQs.

**Comment by PF4Public** [comment]
> I m wondering to put this in the readme or FAQs.

What exactly? Does the quote from readme not suffice?

**Comment by chrisdane** [comment]
I would like to see something like "To verify that the ungoogled version of chromium is used, pressing F1 will show the qjz9zk error page in contrast to [i dont know what] of the original chromium browser". The quote from the readme is perfect, but very general. My point is one specific way to distinguish the browsers.

**Comment by PF4Public** [comment]
Although I personally have no difficulties identifying ungoogled-chromium as I see how all the patches are applied, how all the binaries are removed during compilations, lets see, what @Eloston has to say ;)

**Comment by Eloston** [comment]
> I would like to see something like "To verify that the ungoogled version of chromium is used, pressing F1 will show the qjz9zk error page in contrast to [i dont know what] of the original chromium browser". The quote from the readme is perfect, but very general. My point is one specific way to distinguish the browsers.

There's #659 if anyone wants to dip into the code
