### ISSUE TITLE
Question: how do I use google as my search engine with autocomplete?

### ISSUE THREAD

**Issue by gsbhasin123** [Eloston/ungoogled-chromium#1025]
I know.. I know... don't use google hahaha.
I got google as a custom search engine, but autocomplete doesn't work (it does in regular chromium) - I don't know the autocomplete url. Would someone be so kind as to provide this to me?
Thanks in advance :smiley:

**Comment by likhner** [comment]
In `chrome://settings/searchEngines` create a new search engine with the following parameters:

Search engine: `Google`
Keyword: `google`
URL with %s in place of query: `https://www.google.com/search?client=chrome&q=%s`
Suggestions URL with %s in place of query: `https://www.google.com/complete/search?client=chrome&q=%s`

And save it.

After that, go to `chrome://settings/syncSetup` and turn on `Auto-complete searches and URLs`.

Done.

**Comment by gsbhasin123** [comment]
Thank you!
