### ISSUE TITLE
Question: disable automatic creation of search engines

### ISSUE THREAD

**Issue by MrChocolatine** [Eloston/ungoogled-chromium#1027]
**Is your feature request related to a problem? Please describe.**

Would it be possible to disable the automatic creation of "Other search engines" when we navigate?

We can see a list of them in the page `chrome://settings/searchEngines` (screenshot attached below).

From time to time, I always have to go there to empty this list because I don't want my browser to do this kind of things **automatically**. Especially when most of the time (maybe always actually?), and as you can see on my screenshot, their keyword is their hostname, who would want to type all of that to make a search.

**Describe the solution you'd like**

No custom search engine should be added upon navigation.

**Describe alternatives you've considered**

I don't have any alternative solutions. Maybe would it be possible to add a switch to disable this?

**Additional context**

![gh auto add](https://user-images.githubusercontent.com/47531779/81058788-0f076380-8ec7-11ea-9ff0-8964b739ed20.png)

**Comment by kramred** [comment]
Same as for Chrome/Chromium:
Open `chrome://flags/#disable-search-engine-collection` in a browser tab and set it to __Disabled__ – relaunch the browser

> __Disable search engine collection__
> Prevents search engines from being added automatically. – Mac, Windows, Linux, Chrome OS, Android

**Comment by MrChocolatine** [comment]
Oh thank you, was it already mentioned somewhere? I may have missed the information.

But still, we can do that manually okay, I glad, but would it be possible to disable this feature automatically for `ungoogled-chromium`?

**Comment by Eloston** [comment]
@MrChocolatine Yes it's documented in https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md (referenced here: https://github.com/Eloston/ungoogled-chromium#key-features). The flag is set to a default that aligns with Chrome/Chromium's default behavior.

@kramred It's actually a flag I added in 373c31ae4d5f6b26c89783d98820207a25fdd7b8.

**Comment by MrChocolatine** [comment]
Thank you very much @Eloston , I didn't dig enough into your repository, my bad.
