### ISSUE TITLE
[question] I have Ubuntu 14.04 LTS, which version should I install?

### ISSUE THREAD

**Issue by castor-troy** [Eloston/ungoogled-chromium#103]
Should I use Debian Stretch or Ubuntu Xenial ?

**Comment by Eloston** [comment]
I'm confused. Are you trying to update your system?

**Comment by tonowoe** [comment]
I think what he is asking is that that should he install the pre-built Debian Stretch or Ubuntu Xenial package for his Ubuntu system.

If you have Ubuntu, then I would assume that you want the Ubuntu Xenial pre-built package. Current available pre-built version for Ubuntu is 53.0.2785.116-1.1. So go ahead and download the [xenial_chromium_53.0.2785.116-1_amd64.deb](https://github.com/Eloston/ungoogled-chromium/releases/tag/53.0.2785.116-1.1).

**Comment by Eloston** [comment]
Oh I see. In that case @castor-troy, don't install either. Your system is too old to use any of the packages provided by ungoogled-chromium. You can try building ungoogled-chromium yourself, or wait until #65 is done.
