### ISSUE TITLE
Removing shortcuts from a new tab

### ISSUE THREAD

**Issue by rept1d** [Eloston/ungoogled-chromium#1032]
It seems it is impossible to hide those annoying shortcuts from a new tab in Ungoogled Chromium (which is not an issue in Google Chrome). I don't like it when my browser monitors most recent or frequently visited pages. Why would you remove the option to disable it?

I know the issue regarding this topic has already been created (#980) but it hasn't been solved in another way than it was suggested to use 3rd party extensions which as i think is not a real solution.

My browser version is 80.0.3987.149.

**Comment by Eloston** [comment]
> Why would you remove the option to disable it?

I don't recall removing any options like this.

> I don't like it when my browser monitors most recent or frequently visited pages.

You could always browse in incognito mode.

> it hasn't been solved in another way than it was suggested to use 3rd party extensions which as i think is not a real solution

I don't know what criteria you use to define a "real solution", but there's literally no JavaScript needed to change a new tab page. [It's just a manifest key](https://developer.chrome.com/extensions/override).

If that's not simple enough for you, you can also set an [Enterprise Policy key NewTabPageLocation](https://cloud.google.com/docs/chrome-enterprise/policies/?policy=NewTabPageLocation).

I think adding more way to configure options that are already natively supported is not a good use of our development time.

**Comment by AlexeyMarkarov** [comment]
The solution that worked for me is opening `chrome://flags` and setting `#custom-ntp` option to Enabled with value `about:blank`.

**Comment by touba-denrael** [comment]
`chrome://flags/#disable-top-sites` flag enabled should do its task [just hoping my recall from earlier experiments is valid].

>`chrome://flags/#custom-ntp` option to enabled with value `about:blank`

does also work [if one does not want to use other new tab page functions].
