### ISSUE TITLE
ubuntu 20.4 manual package install

### ISSUE THREAD

**Issue by sailfish009** [Eloston/ungoogled-chromium#1033]
Hi, currently there is no older version of libevent-2.1.6, libicu63 on ubuntu 20.4.
so i had to download and install older version of *.deb files.
Binaries for Ubuntu 19.10 (81.0.4044.129-1.eoan1) works fine in ubuntu 20.4.
but, i think this is little inconvenient for new comer. 

https://packages.ubuntu.com/eoan/amd64/libicu63/download
https://packages.ubuntu.com/eoan/libevent-2.1-6

**Comment by Eloston** [comment]
What binaries are you using? Are you having this problem with the Ubuntu Focal binaries on OBS?

**Comment by sailfish009** [comment]
@Eloston ubuntu 20.4 has newer version of libevent(2.1.11), libicu(66.1). 
so it cause package dependency problem.
if i install ungoogled with force mode, it gets runtime error,
so i downloaded older version of deb, and installed it manually, problem gone.

people who using ubuntu 20.4, 
can use ungoogled but have to install dependency pacakges manually.

> What binaries are you using?
81.0.4044.129-1.eoan1

> Are you having this problem... 
No.

**Comment by sailfish009** [comment]
i checked ungoogled binary link again.
package version updated. (81.0.4044.129 -> 81.0.4044.138 )
problem solved, thanks.
