### ISSUE TITLE
Video decode: Unavailable

### ISSUE THREAD

**Issue by Msouza91** [Eloston/ungoogled-chromium#1035]
**Describe the bug**
I am not able to activate Hardware Acceleration, although Chromium is recognizing my hardware, is it not available for Intel HD graphics?

**To Reproduce**
1. Install ungoogled-chromium from AUR no change in flags
2. Install optional video driver dependendency
3. Try to play any video
4. Processor uses 50%+ power

**Expected behavior**
Use the hardware acceleration available to lower cpu load

**Environment (please complete the following information):**
 - OS/Platform and version: Arch
 - ungoogled-chromium version: Version 81.0.4044.138 (Developer Version) Arch Linux 64 bits

**Additional context**

Here's the output of vainfo:

```
[marcos@Arch2020 ~]$ vainfo 
vainfo: VA-API version: 1.7 (libva 2.7.1) 
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.4.0 
vainfo: Supported profile and entrypoints 
      VAProfileMPEG2Simple            : VAEntrypointVLD 
      VAProfileMPEG2Simple            : VAEntrypointEncSlice 
      VAProfileMPEG2Main              : VAEntrypointVLD 
      VAProfileMPEG2Main              : VAEntrypointEncSlice 
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD 
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice 
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP 
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI 
      VAProfileH264ConstrainedBaseline: VAEntrypointStats 
      VAProfileH264Main               : VAEntrypointVLD 
      VAProfileH264Main               : VAEntrypointEncSlice 
      VAProfileH264Main               : VAEntrypointEncSliceLP 
      VAProfileH264Main               : VAEntrypointFEI 
      VAProfileH264Main               : VAEntrypointStats 
      VAProfileH264High               : VAEntrypointVLD 
      VAProfileH264High               : VAEntrypointEncSlice 
      VAProfileH264High               : VAEntrypointEncSliceLP 
      VAProfileH264High               : VAEntrypointFEI 
      VAProfileH264High               : VAEntrypointStats 
      VAProfileH264MultiviewHigh      : VAEntrypointVLD 
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice 
      VAProfileH264StereoHigh         : VAEntrypointVLD 
      VAProfileH264StereoHigh         : VAEntrypointEncSlice 
      VAProfileVC1Simple              : VAEntrypointVLD 
      VAProfileVC1Main                : VAEntrypointVLD 
      VAProfileVC1Advanced            : VAEntrypointVLD 
      VAProfileNone                   : VAEntrypointVideoProc 
      VAProfileJPEGBaseline           : VAEntrypointVLD 
      VAProfileJPEGBaseline           : VAEntrypointEncPicture 
      VAProfileVP8Version0_3          : VAEntrypointVLD 
      VAProfileVP8Version0_3          : VAEntrypointEncSlice 
      VAProfileHEVCMain               : VAEntrypointVLD 
      VAProfileHEVCMain               : VAEntrypointEncSlice 
```

pacman -Qe linux-firmware returns: linux-firmware 20200421.78c0348-1

**Comment by jstkdng** [comment]
which vaapi driver are you using i915 or iHD? also, did vaapi work before?

**Comment by kevinlekiller** [comment]
Enable chrome://flags/#ignore-gpu-blacklist ; relaunch ; go to chrome://gpu ; scroll to the bottom ; look for something like

    Video Acceleration Information
    Decode h264 baseline | 16x16 to 4096x4096 pixels
    Decode h264 main | 16x16 to 4096x4096 pixels
    Decode h264 high | 16x16 to 4096x4096 pixels
    Decode vp9 profile0 | 16x16 to 8192x8192 pixels

**Comment by Msouza91** [comment]
That solved it! Sorry to bother, didn't see this info on my troubleshooting, but thought about messing with this gpu blacklist flag, was afraid to screw something up since it takes so long to install right now. haha
