### ISSUE TITLE
Extensions (CRX) fail to install on Windows

### ISSUE THREAD

**Issue by vetonblu** [Eloston/ungoogled-chromium#1036]
Sorry if this is a duplicate...

I'm happy with ungoogled-chromium(windows), the only really annoying thing is it still cannot install CRX using the normal procedure or drag&drop when developer on or whatever flags (MIME) and such.
I always have to either use an older version and install there or use load the unpacked ones (this I really dislike).
Is there any way to do this using some "normal" way, drag&drop in developer mode or any other way which wouldn't imply hacks like those I'm using now?

Again, thank you for this, it's awesome, only if it weren't this CRX thing.

**Comment by r4sas** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/23#issuecomment-626376154

**Comment by Eloston** [comment]
Binaries posted https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/174
