### ISSUE TITLE
[minor request] default home page should show something

### ISSUE THREAD

**Issue by pirate486743186** [Eloston/ungoogled-chromium#1038]
At first start, you get greeted by a totally empty home page. That looks broken.

It should show something, anything.

**Comment by Ph0rk0z** [comment]
I love that tho.

**Comment by pwlin** [comment]
I object adding anything to home page. The current minimalist approach is the fastest way to startup the browser.

**Comment by PF4Public** [comment]
> I love that tho.

Empty one, or the proposition?

**Comment by Eloston** [comment]
This should be up to the supported platforms to configure. I don't think setting a homepage in this repo is appropriate; For example, Debian sets the homepage to debian.org.
