### ISSUE TITLE
What about a repo with ungoogled-patch applied?

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1042]
That'll be more convenient, and reproducible.

**Comment by PF4Public** [comment]
You mean the repo with the whole chromium tree and patches applied?

**Comment by playgithub** [comment]
Yes

**Comment by PF4Public** [comment]
This would require a lot of additional work in exchange for a minuscule benefit.

**Comment by playgithub** [comment]
Or the work needs to be done by each one who is going to build the project, right?

**Comment by wchen342** [comment]
The patches in current state will be reproducible too. Also I am not convinced having a separate repo will be any more convenient than using `depot_tools`. If you want to checkout the whole source tree of chromium it will take a very long time.

Besides, this is not feasible at this point anyway. There is not enough manpower to maintain such a repo, unless someone is willing to take the responsibility.

**Comment by playgithub** [comment]
> The patches in current state will be reproducible too. Also I am not convinced having a separate repo will be any more convenient than using `depot_tools`. 

`depot_tools` is the hardest to replace

> If you want to checkout the whole source tree of chromium it will take a very long time.

This is expected, after clone, update is cheap.
`branch`, even PR then is convenicnt.

> Besides, this is not feasible at this point anyway. There is not enough manpower to maintain such a repo, unless someone is willing to take the responsibility.

ok, I don't have enough experience (only compiled ungoogled-chromium once through `makepkg` on Manjaro, it takes about 5 hours. I see that when it is updated, it'll take another 5 hours). Anyway, I'll go and see if a patched repo can be a intermediate result, so that it needs only extra effort that uploads the updates of intermediate results.

It is light to only share pathes, and it's good to make patches expilit.
Compared to patches, a patched repo is more simple, no patches needed. But the problem is about dependencies that `depot_tools` tries to solve.

Anyway I should try first.

**Comment by wchen342** [comment]
@playgithub It is actually more complicated than that. There are many extra problems, for example:
* Someone need to make sure the patched repo is exact the same as the patches. 
* Different platforms have different patchsets. How to deal with them? Have a bunch of branches?
* The domain substitution is constantly changing. It will cause a huge spam in the commits.

Just to name a few problems I can think of right now.

**Comment by playgithub** [comment]
> @playgithub It is actually more complicated than that. There are many extra problems, for example:
> 
> * Someone need to make sure the patched repo is exact the same as the patches.
It's reproducible. One patch deserve one branch.

> * Different platforms have different patchsets. How to deal with them? Have a bunch of branches?
branch in git is cheap, just a hash value, 40 bytes

> * The domain substitution is constantly changing. It will cause a huge spam in the commits.
not familiar about this

> Just to name a few problems I can think of right now.
OK, it seems not so easy. But I still think it can be much more convenient while it's well engineer. I believe the engineer is not easy while not impossible, but once done, it'll be very convenient. However I think that's not what google wanna see.

**Comment by Eloston** [comment]
I also don't see how this will be more efficient. In the most efficient git-based implementation I can think of, each version of the source code tarball would be unpacked into an "upstream" branch (similar to what Debian does for orig tarballs), then another branch like "master" would have the ungoogled-chromium patches rebased on top of "upstream". Then, you'd need to shallow clone the tip of "master" to get only the files you need. Even then, this shallow clone might be larger and slower than the LZMA-compressed tar file we currently download the sourcecode in (but it depends on how small and fast all of git's packfiles are). And this is assuming that no file goes over the 128 MB git object limit that GitHub imposes (I'm pretty sure all files are smaller than 128 MB, but it's hard to say).

`depot_tools` is horribly inefficient in comparision, as the top-level chromium repo and all its subcomponents will have their VCS metadata (even if you do a shallow clone on all of the repos). The tar file we used is already full depot tools clone for Linux desktop, so unless you're developing for Android, I see no technical reason why you'd want a repo like this.

**Comment by playgithub** [comment]
Try to make it simple, for example, it you can't trust prebuilt binaries, just clone and build, for example:
```
$ git clone ungoggled-chromium-git-url
$ make win64
```

Another consideration is about building time,
With a simple repo, when updated, incremental building should work, and it's very efficient to build new binaries.
I'm not sure if incremental building works with standalone tar balls.

Last consideration, when **incremental** updating and **incremental** building work intuitively, I think more developers will be interested in building it, and keeps a newer version. While everything becomes so easy, I think some developers will try to play around the code, I think that is a very good news for ungoogled-chromium.

**Comment by Eloston** [comment]
> Try to make it simple, for example, it you can't trust prebuilt binaries, just clone and build

There are multiple platforms with different maintainers and setups. If you think a platform is difficult to build, please make an issue on that platform's repo.

> Last consideration, when incremental updating and incremental building work intuitively,

Incremental builds is something I overlooked, but all the contributors so far don't have that use-case. Since we currently track stable builds, there are usually a large number of changes between major versions. While security updates would benefit, they are not very frequent. I think that incremental builds would be more useful if you follow unstable Chromium versions and rebuild frequently.

> I'm not sure if incremental building works with standalone tar balls.

Technically you should be able to move the `out` folder from an older Chromium tree to a new one, and incremental building should figure out what needs to be re-built.

Regardless, you still should be able to apply ungoogled-chromium changes on a depot_tools checkout and still keep incremental building. It should be relatively similar to applying changes to a tarball checkout, but you will need to revert these changes before switching your checkout version. I wouldn't mind some changes to our tooling to better support this use-case.

**Comment by playgithub** [comment]
I see, my demand is to develop on ungoogled-chromium not only for privacy.
I'm wrong some way, a proper way is to develop on original chromium for non-privacy business, then patch to be ungoogled.

Thanks

**Comment by PF4Public** [comment]
`ccache` could be a viable substitution for incremental builds
