### ISSUE TITLE
Updating to Chromium 83.0.4103.61

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#1044]
## Notes for the developer

Once you claim it, it is advisable that you create a [Draft Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) for increased visibility:

![GitHub Interface for creating Draft Pull Requests](https://help.github.com/assets/images/help/pull_requests/pullrequest-send.png)

Finally, make sure to reference this issue in your PR.

Feel free to ask questions and discuss issues here along the way. Thanks!

## Notes for others

Feel free to raise issues or questions throughout the process. However, please refrain from asking ETAs unless no visible progress has been made here or on the developer's PR for a while (e.g. 2 weeks).

**Comment by jstkdng** [comment]
I'll take a look, no promises though.

**Comment by Eloston** [comment]
Done by #1047.
