### ISSUE TITLE
Using DNS over HTTPS (DoH) is Broken

### ISSUE THREAD

**Issue by karz1** [Eloston/ungoogled-chromium#1052]
Using DNS over HTTPS (DoH) is Broken
Tested via [https://1.1.1.1/help](https://1.1.1.1/help)
Version 81.0.4044.138 (Official Build) (64-bit) OSX version

**Comment by chinmaythosar** [comment]
The cloudflare tool itself is broken. I have been using a DoT client and the website still shows I am not secure. I have tried multiple DoT and DoH configurations and the only one where cloudflare website showed it was working is when I used cloudflare's own app on iOS. There is another url https://cloudflare-dns.com/help that I found on its forums but this is still the same and broken. Do not rely on it. I think the only effective way would be to monitor DoH port and traffic and inspect packets.

**Comment by Eloston** [comment]
Closing as invalid unless new evidence suggests otherwise.
