### ISSUE TITLE
How to build the binaries with Translation feature enabled

### ISSUE THREAD

**Issue by Ximodel** [Eloston/ungoogled-chromium#1053]
Hi, it may sound a little weird. I think ungoogled-chromium is a great alternative and I would like to build my own windows binaries with enabling Google Translate (which is contradictory to the principles of ungoogle-chromium). 
I tried to remove the following files and edit the series file.
patches/core/ungoogled-chromium/disable-translate.patch
patches/core/inox-patchset/0014-disable-translation-lang-fetch.patch

After building, it turns out the translation feature is still not working. 

Please help and tell me which file(s) is needed to be removed or edited. Thanks

**Comment by PF4Public** [comment]
Related to #999
