### ISSUE TITLE
Ubuntu download 404 not found on obs

### ISSUE THREAD

**Issue by sebastian-ruiz** [Eloston/ungoogled-chromium#1057]
The repository and binaries on opensuse.org give 404 not found errors, for both Ubuntu Focal and Ubuntu Bionic.

**Comment by emilianomacht** [comment]
Since yesterday, the update manager throws this:

> The repository 'http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Bionic  Release' no longer has a Release file.

**Comment by braewoods** [comment]
I tested the Bionic repository in a container. It downloads and installs so I am assuming this was a temporary service outage. These are not unheard of with OBS. If it becomes too frequent we can look into mirroring our OBS repository so it can be available elsewhere. Either way, non-issue now? I think this can be closed, @Eloston.

**Comment by Eloston** [comment]
Yeah I think this is non-issue. Closing.
