### ISSUE TITLE
Spotify Does Not Work

### ISSUE THREAD

**Issue by MrTeeXD** [Eloston/ungoogled-chromium#1061]
**Describe the bug**
So, when attempting to open spotify in the browser, it asks to enable "Allow sites to play protected content" in the Site settings under Protected Content but when enabling it, Spotify still asks for it to be enabled when it is already enabled.

**To Reproduce**
1. Go to https://www.spotify.com
2. Click on Launch Web Player
3. Enable  "Allow sites to play protected content" in the site settings under Protected Content
4. See error when Launch Web Player is clicked

**Expected behavior**
The spotify web player should open when  "Allow sites to play protected content" is enabled.

**Screenshots**
After enabling it, Spotify still shows this:
![chrome_SRRn7qqs2f](https://user-images.githubusercontent.com/37266538/83945949-24e1ae80-a80e-11ea-813f-d8b903820e53.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 1909 64bit
 - ungoogled-chromium version: Version 81.0.4044.138

**Comment by vardecab** [comment]
You'd need a Widevine DRM plugin but it is not distributed with Chromium thus this problem can't be solved.

**Comment by MrTeeXD** [comment]
Do you perhaps know where I can find this plugin?

**Comment by vardecab** [comment]
[This ](https://chromium.woolyss.com/) might help.

**Comment by Eloston** [comment]
Some instructions are being added to the FAQ for Windows: https://github.com/ungoogled-software/ungoogled-chromium-wiki/pull/9. Closing.
