### ISSUE TITLE
Ninja fails to compile ungoogled-chromium

### ISSUE THREAD

**Issue by artemixer** [Eloston/ungoogled-chromium#1064]
**Describe the bug**
During the process of compilation by ninja, I was met with this issue and have no idea what it might relate to. (see screenshot bellow)

**To Reproduce**
I currently don't have any information regarding what might be causing the error 

**Expected behavior**
I expect ninja to compile the files into a runnable version of ungoogled-chromium

**Screenshots**
https://prnt.sc/sv382e

**Environment (please complete the following information):**
Windows 10, VS 2019, compiled using python 3.8

**Comment by wchen342** [comment]
Seems like Python version problem. Try Python2?

**Comment by PF4Public** [comment]
Chromium build system relies on python 2. Althogh there are efforts on rewriting python2 code to be compatible with python3, this is not yet finished unfortunately.
Like @wchen342 suggests, try building with python2.

**Comment by artemixer** [comment]
> Seems like Python version problem. Try Python2?

Yes, I played around with python versions and that seemed to work. Thanks
