### ISSUE TITLE
Cannot install ungoogled-chromium in Linux Mint 19.3 Cinnamon : Dependency problem is not satisfiable

### ISSUE THREAD

**Issue by k3VTSjczL3** [Eloston/ungoogled-chromium#1065]
**Describe the bug**
The .deb package from OBS Production Repository fails to install

**To Reproduce**
1. Download the deb package from https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium
2. Double click the package or install with dpkg in terminal
3. Wait for reading database
```
sudo dpkg -i ungoogled-chromium_81.0.4044.138-1.bionic1_amd64.deb
[sudo] password for linuxuser:                     
Selecting previously unselected package ungoogled-chromium.
(Reading database ... 254499 files and directories currently installed.)
Preparing to unpack ungoogled-chromium_81.0.4044.138-1.bionic1_amd64.deb ...
Unpacking ungoogled-chromium (81.0.4044.138-1.bionic1) ...
dpkg: dependency problems prevent configuration of ungoogled-chromium:
 ungoogled-chromium depends on libjsoncpp1 (>= 1.7.4); however:
  Package libjsoncpp1 is not installed.
 ungoogled-chromium depends on libminizip1 (>= 1.1); however:
  Package libminizip1 is not installed.
 ungoogled-chromium depends on ungoogled-chromium-common (= 81.0.4044.138-1.bionic1); however:
  Package ungoogled-chromium-common is not installed.

dpkg: error processing package ungoogled-chromium (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23+linuxmint8) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 ungoogled-chromium
```

**Expected behavior**
ungoogled-chromium should continue install process without any dependency problem.

**Screenshots**
![ugch](https://user-images.githubusercontent.com/58479925/83976848-3dc09180-a8ec-11ea-800a-da82160ed2d0.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Linux Mint 19.3 Cinnamon
 - ungoogled-chromium version:81.0.4044.138-1.bionic1

**Additional context**

**Comment by wchen342** [comment]
@braewoods Need to update your Debian repo?

**Comment by braewoods** [comment]
Nope. This is because they tried to install via dpkg. That only works if the dependencies are already installed. They are missing some dependencies that need to be installed first. The output says as much.

**Comment by PF4Public** [comment]
Oh right, @k3VTSjczL3 you should add another apt sources entry and not install .deb manually.

**Comment by wchen342** [comment]
@braewoods Oh yes you are right. Haven't played with debian based system for a while.

**Comment by k3VTSjczL3** [comment]
> Oh right, @k3VTSjczL3 you should add another apt sources entry and not install .deb manually.

I have installed some dependencies (`libjsoncpp1` and `libminizip1`) manually but cannot install `ungoogled-chromium-commoon` . @braewoods where am I going to get these missing dependencies? Is this only for Ubuntu and Debian? My preconfigured Linux Mint repositories does not have it apparently.
```
sudo apt install ungoogled-chromium
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ungoogled-chromium : Depends: libavcodec58 (>= 7:4.2) but it is not installable
                      Depends: libavformat58 (>= 7:4.1) but it is not installable
                      Depends: libavutil56 (>= 7:4.0) but it is not installable
                      Depends: libc6 (>= 2.29) but 2.27-3ubuntu1 is to be installed
                      Depends: libevent-2.1-7 (>= 2.1.8-stable) but it is not installable
                      Depends: libfreetype6 (>= 2.10.1) but 2.8.1-2ubuntu2 is to be installed
                      Depends: libgcc-s1 (>= 4.0) but it is not installable
                      Depends: libharfbuzz0b (>= 2.2.0) but 1.7.2-1ubuntu1 is to be installed
                      Depends: libicu66 (>= 66.1-1~) but it is not installable
                      Depends: libre2-5 (>= 20160901) but it is not installable
                      Depends: libsnappy1v5 (>= 1.1.8) but 1.1.7-1 is to be installed
                      Depends: libstdc++6 (>= 9) but 8.4.0-1ubuntu1~18.04 is to be installed
                      Depends: libvpx6 (>= 1.7.0) but it is not installable
                      Depends: libx11-xcb1 (>= 2:1.6.9) but 2:1.6.4-3ubuntu0.2 is to be installed
                      Depends: libxcomposite1 (>= 1:0.4.5) but 1:0.4.4-2 is to be installed
                      Recommends: ungoogled-chromium-sandbox but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by nicolaasjan** [comment]
Read this:
https://forums.linuxmint.com/viewtopic.php?p=1816608#p1816608

You have to add the repo to your software sources:

```
echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Bionic/ /' | sudo tee /etc/apt/sources.list.d/home:ungoogled_chromium.list
sudo wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Bionic/Release.key -O "/etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc"
sudo apt update
sudo apt install ungoogled-chromium
```

Unfortunately there is no localization (yet?).

**Comment by k3VTSjczL3** [comment]
> Read this:
> https://forums.linuxmint.com/viewtopic.php?p=1816608#p1816608
> 
> You have to add the repo to your software sources:
> 
> ```
> echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Bionic/ /' | sudo tee /etc/apt/sources.list.d/home:ungoogled_chromium.list
> sudo wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Bionic/Release.key -O "/etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc"
> sudo apt update
> sudo apt install ungoogled-chromium
> ```
> 
> Unfortunately there is no localization (yet?).
> 
> I have Linux Mint 19.3 Mate and have not encountered unmet dependencies...
> This might be your problem:
> `E: Unable to correct problems, you have held broken packages.`
Ohhh silly ME. The repositories in the OBS is for Ubuntu 20.04 (aka Focal Fossa).
I should have checked the 2nd repo under it. Sorry for being dumb
Works now.
