### ISSUE TITLE
Why cannot webstore detect ungoogled-chromium exactly?

### ISSUE THREAD

**Issue by wchen342** [Eloston/ungoogled-chromium#1066]
So someone mentioned that UC cannot install extensions from webstore and I tried with vanilla UC on Windows and Arch and both of them can be recognized by webstore.

I searched through the issues here and all I can find is issues about drag&drop of crx files, like #1009, #988 and #923, but there is no explanation why exactly webstore cannot detect the browser. I have seen in [this issue](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/23) that it may have something to do with `safe browsing`, does this mean it is unfixable without enabling `safe brwosing`?

To put it simple, is it:
1. unsolvable? or
2. no one looked into this before? or
3. against the goal of the project so it is not fixed?

**Comment by PF4Public** [comment]
AFAIK it cannot download extensions from webstore as the URLs are obfuscated in source code. It can however install extensions as .crx files. This is also possible to accomplish with a custom search, which downloads extension.

**Comment by wchen342** [comment]
I think it is not about downloading? Because on the webstore page usually you will see the button `Add to Chrome` but in UC you will get `Available on Chrome` which means it is not recognized as chromium at all.

**Comment by PF4Public** [comment]
hmm. I have just tried opening webstore in ungoogled-chromium aaaand… guess what?
![image](https://user-images.githubusercontent.com/10319700/84089520-d7c13080-a9f7-11ea-91ba-659ead9bdd98.png)
Surprise! Not only it is detected as Chromium, but it does try to install an extension and succeeds!
Is something changed or my build gone bad? Is it a bug instead?
@jstkdng , please try this in Arch.
@braewoods , please try this in Debian.

**Comment by jstkdng** [comment]
![2020-06-08_18:32:15](https://user-images.githubusercontent.com/52050345/84090114-690fb300-a9b6-11ea-923b-726d7003bc10.jpg)
I'd be commiting heresy, but works on my machine™

**Comment by wchen342** [comment]
Strange, it doesn't work here. `83.0.4103.61-1` built from AUR.
![Screenshot](https://user-images.githubusercontent.com/6406743/84091424-e30a6100-a9e3-11ea-911f-f6647a5adc44.jpg)

**Comment by jstkdng** [comment]
@wchen342 are you testing on a clean profile?

**Comment by wchen342** [comment]
No, but I tested a clean installation of @braewoods' binary `81.0.4044.138-1` on `bionic` and it still doesn't work.

**Comment by jstkdng** [comment]
![2020-06-08_19:28:44](https://user-images.githubusercontent.com/52050345/84092874-4bdee280-a9be-11ea-8068-c8628059d6b6.jpg)
okay, just tried on a clean profile and I can confirm it isn't working, not even a button appears for me

**Comment by wchen342** [comment]
Interesting, now I wonder how your old profile actually made it work.

**Comment by Eloston** [comment]
It's been a while, but I believe this is because of `patches/core/ungoogled-chromium/disable-webstore-urls.patch`.

IIRC, the "Add to Chromium" button is provided by NeverDecaf's chromium-webstore extension. In regular Chromium, it would be "Add to Chrome".

Ideally we would re-enable detection in the Webstore, and use #285 to fix installations. I'd like to use #285 to re-enable extension installation because it allows us to not hardcode webstore URLs, and would enable users to install from non-Webstore sources (which is what NeverDecaf's extension does when it self-updates).

**Comment by jstkdng** [comment]
Might I add, had to reinstall Arch because of new hardware so had to configure a new profile, and for sure, the same thing happened as my previous comment, the thing is, after installing chromium-webstore, the 'Add to Chromium' button appears as expected and I'm able to install extensions normally. So yeah, works on my machine™ still stands

**Comment by wchen342** [comment]
@jstkdng Well I was asking i the case you didn't add anything, just the plain browser. The extra extension has two problems for me to include in my Android version:
* It needs to be bundled with browser and I am not sure it works the same on Android
* It will make the function dependent on a third party to update their code

So I wonder if there is a native way to solve this that only involves changes in C++ codes.

**Comment by jstkdng** [comment]
Isnt chromium webstore feature complete? only change could be is that google changes something on their part.

**Comment by wchen342** [comment]
@jstkdng What do you mean?
In the case you don't install that extension you won't get the button right?

**Comment by jstkdng** [comment]
@wchen342 
yeah, the store recognizes ungoogled chromium as if I was running android. Maybe a user-agent issue?
Also, does the `extension-mime-request-handling` flag not work under android? Then someone could install `chromium-webstore` using file:/// on the search bar.

**Comment by wchen342** [comment]
> Maybe a user-agent issue?

No. I tried desktop UA, it didn't work.

> Also, does the `extension-mime-request-handling` flag not work under android? Then someone could install `chromium-webstore` using file:/// on the search bar.

I just made that work in last version so theoretically, yes. But I think a more elegant way is I either bundle `chromium-webstore` or somehow make this works natively, which is way I'm asking here.

**Comment by jstkdng** [comment]
Hmm, if I remember correctly, chromium used to inject some extensions related to crypto I think. We could inject chromium-webstore that way, but that should be done here, and not only under `ungoogled-chromium-android`. Android should first get extension support.

**Comment by wchen342** [comment]
> Android should first get extension support.

I've already adapted that from Kiwi: [https://github.com/ungoogled-software/ungoogled-chromium-android/tree/extensions#extensions](https://github.com/ungoogled-software/ungoogled-chromium-android/tree/extensions#extensions). Someone was using the extension-support version which is why the question was raised.

> if I remember correctly, chromium used to inject some extensions related to crypto I think.

Yeah that's what I am thinking how it can be done. I just don't know how hard it is to keep `chromium-webstore` maintained between versions.

**Comment by jstkdng** [comment]
And there comes my comment, `chromium-webstore` is feature complete, at least according to NeverDecaf, can't you inject the latest working version and if something breaks, the user could disable the built in extension and install a the new one from NeverDecaf's releases until it is updated on this side.

**Comment by wchen342** [comment]
Ok I tried to install `chromium-webstore` directly from github release but it doesn't work. I think it is because there is no metadata for the crx file (no extension id, etc.), which means whoever want to use it needs to load the source code manually which is a huge hassle especially on Android 10.

Is the author @enolgor? Do you have any idea whether this can be solved?

**Comment by jstkdng** [comment]
@NeverDecaf is the developer of chromium-webstore.
I also tried to install it but no use, could be an issue on android as chromium-webstore installs without any problem.

**Comment by wchen342** [comment]
> @NeverDecaf is the developer of chromium-webstore.
> I also tried to install it but no use, could be an issue on android as chromium-webstore installs without any problem on pc.

I suppose on pc you drag-and-drop it according to `Readme`. That is not possible on Android so installing from url or load using developer mode are the only two possible ways.

**Comment by wchen342** [comment]
So I tried install `chromium-webstore` with `extension-mime-request-handling` and obviously it doesn't work even on desktop. I think the crx file lacks some critical things so that chromium does not consider it as a complete extension file at all.

**Comment by Eloston** [comment]
> So I tried install chromium-webstore with extension-mime-request-handling and obviously it doesn't work even on desktop.

If you mean you're trying to use a HTTP/HTTPS link in the Omnibar to install Chromium Web Store, then this also fails for me on desktop. Otherwise, could you clarify what you mean?

**Comment by jstkdng** [comment]
It works for me by dragging and dropping the crx into chrome://extensions or the file:/// protocol on desktop, how did you try to install @wchen342 ?

**Comment by wchen342** [comment]
> If you mean you're trying to use a HTTP/HTTPS link in the Omnibar

Yes, that's what I meant.

> It works for me by dragging and dropping the crx into chrome://extensions

As I said above, this is not possible on Android so I need the omnibar way to work.

**Comment by jstkdng** [comment]
well, I told you what worked for me on desktop.
BTW, I found this: https://stackoverflow.com/questions/50125821/standard-way-to-build-a-chrome-extension-into-chromium
We could use that to bundle chromium-webstore. Might need a few changes as it is a bit outdated.

**Comment by wchen342** [comment]
Interesting, I will try that out. Though I think if it is not too hard to get an id for `chromium-webstore` that will be an easier solution.

**Comment by jstkdng** [comment]
I'm not sure how extension signing works on chromium so can't really say anything.
If we want to bundle the crx we might need to modify the scripts in here to copy files to chromium source dir and not just patching. What do you think @Eloston ?

**Comment by wchen342** [comment]
One minor correction: `chromium-webstore` does have an id assigned, but there are some other stuff missing. Probably hash?

**Comment by Eloston** [comment]
Another solution is to embed the extension source code in place of `chrome/browser/resources/webstore_app/`

Or maybe add another extension like the numerous others in `chrome/browser/resources`, including but not limited to:

* cryptotoken
* cloud_print_app
* help_app
* settings
* network_speech_synthesis
* pdf
* media/mei_preload
* chrome_app
* feedback

Not sure what C++ code is required to make this work though; it's possible using the default_extensions mechanism described above is simpler/more robust.

> If we want to bundle the crx we might need to modify the scripts in here to copy files to chromium source dir and not just patching. What do you think @Eloston ?

No need to do that. I imagine this is an Android-specific change, so all you'd need to do in Android is copy the files (either the CRX or the extension source code) after you apply patches (and not before, because you probably don't want to accidentally apply patches to files you just copied in).

**Comment by wchen342** [comment]
It is a little more complicated than that. The way @jstkdng mentioned only works on windows (I check the gn files). I know pdf and cloud_print is considered "plugins" and is separate from extensions. I haven't found where cryptotoken is included though but that's the best bet because I remember it is in the extension page for vanilla chromium.

**Comment by jstkdng** [comment]
I didnt see any windows only stuff on that link appart from the gn check but cant that be removed altogether?

**Comment by wchen342** [comment]
The `default_extensions` target is included in `chrome/installer/mini_installer/BUILD.gn` which is used in template of `mini_installer` that is windwos specific (it generates a bunch of dll files).

**Comment by wchen342** [comment]
Strange, I cannot find `cryptotoken`. All I can find is the api itself which are C++ codes.

**Comment by Eloston** [comment]
> I haven't found where cryptotoken is included though but that's the best bet because I remember it is in the extension page for vanilla chromium.

1. A quick grep in `chrome/browser` (not likely to be in other directories due to Chromium architecture) shows that `cryptotoken/manifest.json` is referenced in `chrome/browser/browser_resources.grd`, which makes sense as all embedded resources must be referenced via [`.grd` files (i.e. GRIT files)](https://www.chromium.org/developers/tools-we-use-in-chromium/grit). The GRIT name for this manifest.json is `IDR_CRYPTOTOKEN_MANIFEST`
2. Doing a grep for `IDR_CRYPTOTOKEN_MANIFEST` in `chrome/browser` hits two locations:
  * `chrome/browser/extensions/component_loader.cc` in `ComponentLoader::AddDefaultComponentExtensionsWithBackgroundPages()`. This seems like where all the actual component extension loading is being done (at least one of them; there's another for kiosk mode).
  * `chrome/browser/extensions/component_extensions_whitelist/whitelist.cc` in function `IsComponentExtensionWhitelisted`. This function is referenced in `ComponentLoader::Add()`, so it might be a security check to prevent unauthorized components.

Hopefully my thought process here helps.

**Comment by wchen342** [comment]
Ok I figured that out and has successfully added `chromium-webstore` to Android version (not tested on desktop though). Now the button occurs if I switch to desktop site. There are still some minor problems but those are related to UI I think.

**Comment by jstkdng** [comment]
Do you have a binary for testing @wchen342 ?

**Comment by wchen342** [comment]
You mean the Android version?

**Comment by jstkdng** [comment]
yes

**Comment by wchen342** [comment]
I am still fixing the UI problem. Currently it will crash after hitting the `Add to Chromium` button.

**Comment by wchen342** [comment]
@jstkdng You want a binary that can run on your phone or in emulator? They need to be compiled to different architectures (`arm` vs `x86`).

**Comment by jstkdng** [comment]
@wchen342 I currently don't have an emulator installed, so for a phone I guess. My phone isn't arm64 btw.

**Comment by wchen342** [comment]
Ok, then I will compile an `arm` one. It will take some time though.

**Comment by jstkdng** [comment]
Thanks! Are you using your own resources or do you have some pipeline in your gitea server?

**Comment by wchen342** [comment]
I am using my own machine. My server is a very small instance with only 1 core.

Here you go: [https://www.droidware.info/fdroid/repo/ChromePublic.apk](https://www.droidware.info/fdroid/repo/ChromePublic.apk).

**Comment by jstkdng** [comment]
huh, this one is double the size of the apk in your gitea releases, weird. Did you include debug symbols?

**Comment by wchen342** [comment]
Yeah I made a debug build in case you find any other problem then you can report back the backtrace.

**Comment by jstkdng** [comment]
If I find anything I'll report back on uc-android. At least I managed to install ubo from the chrome web store, performance is really bad though.

**Comment by wchen342** [comment]
The bad performance is because of the debug build (optimizations are all disabled). BTW uBlock is not working correctly yet, I think it is related to API difference.

**Comment by wchen342** [comment]
`chromium-webstore` is now bundled with the Android Extension-support version, so I will close this for now.
