### ISSUE TITLE
Secure way to download Ungoogled Chromium on MacOS?

### ISSUE THREAD

**Issue by antois** [Eloston/ungoogled-chromium#1068]
Hi all,

I am curious about the project and decided to download it on MacOS. However, upon downloading the binaries, I saw this warning: 

> NOTE: These binaries are provided by anyone who are willing to build and submit them. Because these binaries are not necessarily reproducible, authenticity cannot be guaranteed; In other words, there is always a non-zero probability that these binaries may have been tampered with. In the unlikely event that this has happened to you, please report it in a new issue.

Does this warning relate to the download options listed below, in particular, via Homebrew on Mac? I am not sure I want to trust sensitive data to builds submitted by random people... However, it is not clear to me if Homebrew uses those builds as well.

Thanks for the reply.

**Comment by PF4Public** [comment]
This warning says, that _any_ binary is essentially "submitted by random people".

The only way of obtaining a trusted binary is by building on your own system from source.

**Comment by specter78** [comment]
@PF4Public How to build it?

**Comment by antois** [comment]
@PF4Public thank you for clarifying this! 

I would appreciate an advice for a complete novice on how to build it on MacOS from source.

**Comment by PF4Public** [comment]
I have very little experience with MacOS, but you should probably start with [Building instructions in ungoogled-software/ungoogled-chromium-macos repo](https://github.com/ungoogled-software/ungoogled-chromium-macos#building)

**Comment by Eloston** [comment]
Closing because question is answered. If you have questions about building on macOS, you should create an issue on ungoogled-chromium-macos repo.
