### ISSUE TITLE
Flash Plugin not detected on Linux

### ISSUE THREAD

**Issue by emuNAND** [Eloston/ungoogled-chromium#107]
it seems impossible to make ungoogled-chromium use the PPAPI plugin because it cannot detect it in chrome://plugins/. Packages like "adobe-flashplugin" and "nonfree-pepperflashplugin" also fail.

**Comment by Atavic** [comment]
Which distro exactly?

**Comment by emuNAND** [comment]
i am using ubuntu gnome edition, but i have also tried this on manjaro and linux mint.

**Comment by Eloston** [comment]
Are you using the pre-built binary or building it on your own? I know someone that uses the pre-built binary on Ubuntu Xenial and the Flash player package from Ubuntu works just fine.

**Comment by emuNAND** [comment]
@Eloston yes, i am using the prebuilt binary in the releases section. i tried opening an swf file in vivaldi and it worked just fine. am i doing something wrong?

**Comment by Eloston** [comment]
I don't know much about vivaldi, and I don't think it's related to this. Are you able to get Flash to work if you pass in the paths directly using the correct command-line flags?

**Comment by emuNAND** [comment]
@Eloston vivaldi is a chromium-based browser.
using the flag "--ppapi-flash-path" doesn't seem to work. is it because the package "adobe-flashplayer" is not supported by chromium?

**Comment by Eloston** [comment]
I don't know of any `adobe-flashplayer` package. You said [this one](http://packages.ubuntu.com/xenial/pepperflashplugin-nonfree) doesn't work?

**Comment by emuNAND** [comment]
@Eloston yes, that one and also [this one](https://apps.ubuntu.com/cat/applications/quantal/adobe-flashplugin/)

**Comment by Eloston** [comment]
That's strange; there might have been an Iridium patch that disabled loading system plugins? I'll have to check.

Were you still not able to get `--ppapi-flash-path` flag to work even with the pepperflash package? I think you'll also need to set the flag that specifies the version too, otherwise it won't work.

**Comment by emuNAND** [comment]
@Eloston both flags `--ppapi-flash-path` and `--ppapi-flash-version` do not work. i will try this with iridium just to make sure.

**Comment by Eloston** [comment]
When you use the flags, you're using an equal sign between them, right? e.g. `--ppapi-flash-path=/path/to/pepperflashplayer.so`

**Comment by emuNAND** [comment]
@Eloston yep. i also used an equal sign with the `--ppapi-flash-version` flag.

**Comment by Eloston** [comment]
Weird. I don't have a system to test this right now, so if someone wants to test this go ahead.

I'm also not sure what changes have been made that are breaking this. If someone wants to help out in the investigation that would be nice.

**Comment by usernamenotexist** [comment]
Flash must die. It cause security risk.

**Comment by emuNAND** [comment]
@usernamenotexist it's hard to kill something that is used for many websites. if browsers like chrome and firefox remove the ability to use flash, most of the history of the internet is inaccessible.

**Comment by Eloston** [comment]
@usernamenotexist There are a LOT more attack points than just Flash. To be honest, I would be more worried about JavaScript; it's essentially filling the role that Flash did back in the day. Both the tab processes and Flash plugin have to be sandboxed nowadays.

Though this is off-topic. Please limit this discussion to the original Flash plugin issue.

**Comment by my-password-is-password** [comment]
I don't use ungoogled-chromium but I do use  Chromium dev build 56.0.2915.0 by nik and my flash was missing too.  Once something stops working on dev builds I usually check ```chrome://flags/``` to see if I can re-enable stuff they take out and I found this, 

![cflash0](https://cloud.githubusercontent.com/assets/6408935/20188233/9a404a9c-a72c-11e6-8659-9dec79953675.png)


Go to ```chrome://flags/#prefer-html-over-flash``` and change it to ``Disabled`` and relaunch chromium.


![cflash](https://cloud.githubusercontent.com/assets/6408935/20188041/bfc3fc74-a72b-11e6-9308-5bda6292547d.png)

See if flash starts working for you.  It did for me.  I'm on Windows though, don't know if it works on Linux.

**Comment by Deltadragoon** [comment]
I can confirm that the issue exists on version 55.0.2883.87 built on Ubuntu xenial/16.04, running on LinuxMint serena/18.1 (64-bit). I've installed PPAPI correctly and the plugin is not detected by Chromium.

**Comment by Eloston** [comment]
Is this still an issue? I know someone who tried with the current version (version 57) and it crashes the browser since WebRTC is disabled. WebRTC will be enabled in the future (see #179)

**Comment by Deltadragoon** [comment]
It's an issue for myself, at least.

**Comment by Eloston** [comment]
I'm not sure what to say because using the command-line arguments to specify the pepperflash shared object file will cause the crash. Perhaps Ubuntu installs the plugin in a location that isn't picked up by ungoogled-chromium.

**Comment by Eloston** [comment]
62 is out. If this is still an issue, please respond here.
