### ISSUE TITLE
Extensions disappeared

### ISSUE THREAD

**Issue by Janaue** [Eloston/ungoogled-chromium#1074]
I tried to  add dictionaries  like I mentioned here https://github.com/Eloston/ungoogled-chromium/issues/1073
First I deleted the Bin folder to get a new one, hoping the dictionaries would be installed automatically.
Then I chose the official chrome and then putting the folder dictionary in the ungoogled version of chrome. 
After this, i went back to using the ungoogled version and Somehow I lost all my extensions and my imported passwords (I had to enable some flag for this the first time). However, the profile is still around 500MB and when I installed UBO again, it found all my settings, so I guess the extensions are still around in the profile. I still have my bookmarks showing up fine.
How do I get extensions to show in chrome?

**Comment by Janaue** [comment]
this was the options in  chrlauncher i used to make chrome truly portable
--enable-features=PasswordImport --disable-machine-id --disable-encryption

perhaps it messed with my extensions and passwords when I  switched from ungoogled to the official chrome, in order to get the official dictionaries, then went back to ungoogled.

**Comment by Janaue** [comment]
I also deleted the folder %LOCALAPPDATA%\Chromium\User Data\* while going ungoogled->official->ungoogled

**Comment by Eloston** [comment]
It's probably because switching between different Chromium variants is causing the browser to remove those settings. This is normal if the browser detects some unexpected data in its configuration files.

**Comment by Janaue** [comment]
is there a way to retrieve the list of extensions, so i can just reinstall them ?

**Comment by Janaue** [comment]
> 
> 
> It's probably because switching between different Chromium variants is causing the browser to remove those settings. This is normal if the browser detects some unexpected data in its configuration files.

is there a way to retrieve the list of extensions, so i can just reinstall them ?
