### ISSUE TITLE
Building 83.0.4103.97 on macOS

### ISSUE THREAD

**Issue by wickedwzrd** [Eloston/ungoogled-chromium#1075]
Current UG-chromium build: 80.0.3987.132
OS platform/ver: macOS Mojave 10.14.6
Building version: 83.0.4103.97

The last time I built chromium I had a few issues but it worked and I'm currently running the above version. I noticed that there is a newer version and I wanted to build it again and use that. However I've tried both cloning the repo and downloading the latest version from the releases and it fails on the ninja build.

```
thomas@mba ~/D/u/b/src (master)> ninja -C out/Default chrome chromedriver chrome_sandbox
ninja: Entering directory `out/Default'
ninja: error: unknown target 'chrome_sandbox'
```

I can attach the full log of each command if needed

**Comment by Eloston** [comment]
`chrome_sandbox` is only applicable on Linux AFAIK. The ungoogled-chromium-macos build script doesn't build the chrome_sandbox target.

**Comment by wickedwzrd** [comment]
I remember this first time I built it I used chrome_sandbox and it worked fine, but beside that I tried building with and without chromedriver and I'm still having issues.

```
thomas@mba ~/D/u/b/src (master)> ninja -C out/Default chrome chromedriver
ninja: Entering directory `out/Default'
ninja: error: '../../third_party/google_toolbox_for_mac/src/AppKit/GTMCarbonEvent.m', needed by 'obj/third_party/google_toolbox_for_mac/google_toolbox_for_mac/GTMCarbonEvent.o', missing and no known rule to make it```

**Comment by Eloston** [comment]
You might want to compare your build process with `build.sh` in ungoogled-chromium-macos. If the build process in that repo doesn't work, then we need to fix a bug.

**Comment by wickedwzrd** [comment]
Thanks and as of now the build process in ungoogled-chromium-macos is working since I noticed it downloaded these 2 files that did not download from the main repo
`google-toolbox-for-mac-v2.2.1.tar.gz`
`clang+llvm-8.0.0-x86_64-apple-darwin.tar.gz`
After inspecting the `build.sh` I only noticed 1 minor difference in the build process and still don't know why the main repo didn't download those 2 files. Also the build process is taking a considerable amount of time to build. 
The final thing I want to attempt and will comment on is if I can manually use the current branch in the main repo with the macos build process and see if that will download those 2 files plus successfully build.

**Comment by Eloston** [comment]
> still don't know why the main repo didn't download those 2 files

The ungoogled-chromium-macos repo has another downloads.ini file that specifies additional dependencies. The `clang+llvm` tar file is just as a convenience to have a pre-built compiler; you should be able to use your own compiler with no issues (provided it's newer than 8.0.0)

**Comment by wickedwzrd** [comment]
Ah I didn't notice the difference in the downloads.ini file. To update, the ungoogled-chromium-macos build took around 12h to complete and it working so far.
The second attempt I made to manually download the latest branch to replace the version in the macos branch failed during applying patches.
```
patching file third_party/blink/renderer/platform/runtime_enabled_features.json5
INFO: Applying patches from /Users/thomas/ungoogled-chromium-macos/patches
INFO: * Applying chromium-skia-harmony.patch (1/19)
patching file third_party/skia/src/ports/SkFontHost_FreeType.cpp
INFO: * Applying fix-cfi-failures-with-unbundled-libxml.patch (2/19)
patching file third_party/blink/renderer/core/xml/parser/xml_document_parser.cc
Hunk #1 succeeded at 140 (offset 2 lines).
Hunk #2 succeeded at 159 (offset 2 lines).
Hunk #3 succeeded at 212 with fuzz 2 (offset 8 lines).
Hunk #4 succeeded at 296 with fuzz 2 (offset 16 lines).
patching file third_party/blink/renderer/core/xml/xsl_style_sheet_libxslt.cc
patching file third_party/blink/renderer/core/xml/xslt_extensions.cc
patching file third_party/blink/renderer/core/xml/xslt_processor_libxslt.cc
Hunk #1 succeeded at 104 (offset 1 line).
patching file third_party/blink/renderer/core/xml/xslt_unicode_sort.cc
INFO: * Applying mojo.patch (3/19)
patching file content/shell/BUILD.gn
Hunk #1 FAILED at 298.
Hunk #2 succeeded at 365 (offset 6 lines).
1 out of 2 hunks FAILED -- saving rejects to file content/shell/BUILD.gn.rej
Traceback (most recent call last):
  File "/Users/thomas/ungoogled-chromium-macos/ungoogled-chromium/utils/patches.py", line 250, in <module>
    main()
  File "/Users/thomas/ungoogled-chromium-macos/ungoogled-chromium/utils/patches.py", line 246, in main
    args.callback(args, parser.error)
  File "/Users/thomas/ungoogled-chromium-macos/ungoogled-chromium/utils/patches.py", line 201, in _apply_callback
    patch_bin_path=patch_bin_path)
  File "/Users/thomas/ungoogled-chromium-macos/ungoogled-chromium/utils/patches.py", line 132, in apply_patches
    subprocess.run(cmd, check=True)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/Users/thomas/ungoogled-chromium-macos/patches/debian_buster/fixes/mojo.patch', '-d', '/Users/thomas/ungoogled-chromium-macos/build/src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.```

**Comment by Eloston** [comment]
That's because macOS has additional patches in order to make a successful build. These are version-specific.

**Comment by wickedwzrd** [comment]
Ok, thanks for the help.
