### ISSUE TITLE
OBS debian version of ungoogled-chromium missing 83 releases 

### ISSUE THREAD

**Issue by arthurlogilab** [Eloston/ungoogled-chromium#1084]
**Describe the bug**
Version 83 of ungoogled-chromium seems to be released but not the debian package. 

**To Reproduce**
1. Go to https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium
2. Click on Packages for Buster

**Expected behavior**

**Screenshots**
![Screenshot from 2020-06-24 09-37-08](https://user-images.githubusercontent.com/445200/85516374-69d35680-b5fe-11ea-8c57-bb7ec9e424f8.png)
![Screenshot from 2020-06-24 09-36-22](https://user-images.githubusercontent.com/445200/85516376-6b048380-b5fe-11ea-81b1-c17c81672b15.png)

**Environment (please complete the following information):**
 - OS/Platform and version: debian/ubuntu
 - ungoogled-chromium version: 81.0.4044.138-1.focal1 ungoogled-chromium_81.0.4044.138-1

**Comment by braewoods** [comment]
@Eloston Go ahead and close this. It's in progress to completion.

**Comment by Eloston** [comment]
For the record, PR is here https://github.com/ungoogled-software/ungoogled-chromium-debian/pull/151
