### ISSUE TITLE
Can't login into Google services.

### ISSUE THREAD

**Issue by altoids762** [Eloston/ungoogled-chromium#1086]
When I try logging into YouTube or any other Google product, I get the "Something went wrong", and I am unable to sign in to my Google account.

**Comment by Eloston** [comment]
I have no issues with my Google account. What version and platform are you using?

**Comment by altoids762** [comment]
> I have no issues with my Google account. What version and platform are you using?

I'm using an ungoggled chromium windows package. Windows 10, https://ungoogled-software.github.io/ungoogled-chromium-binaries/

**Comment by Eloston** [comment]
Do you have this issue on other browsers?

**Comment by altoids762** [comment]
> Do you have this issue on other browsers? e.g. regular Chromium

No, I'm able to login on Firefox and Palemoon.

**Comment by Eloston** [comment]
* Does it work if you change your user agent?
* Are you able to test ungoogled-chromium on a different platform, e.g. Linux, Android, or macOS?

**Comment by altoids762** [comment]
After re-installing I fixed the issue, thanks for the support.
