### ISSUE TITLE
Getting ERR_SSL_PROTOCOL_ERROR on localhosts websites

### ISSUE THREAD

**Issue by kgorol** [Eloston/ungoogled-chromium#1088]
**Describe the bug**
I am unable to test locally hosted web applications. With Firefox or "normal" Chrome websites such as localhost:8000 or localhost:4200 launch just fine.

**To Reproduce**
1. Start locally hosted web app such as Angular.
2. Try to open it with https://localhost:4200
3. Getting error ERR_SSL_PROTOCOL_ERROR

**Expected behavior**
Website opens.

**Environment (please complete the following information):**
 - OS/Platform and version: macOS Mojave 10.14.6
 - ungoogled-chromium version: 81.0.4044.92 (Official Build) (64-bit)

**Comment by xsmile** [comment]
ungoogled-chromium uses the HTTPS protocol by default. You will need to manually specify that your locally hosted application uses HTTP.

**Comment by kgorol** [comment]
Thanks @xsmile , is there any guide how to do that?

**Comment by xsmile** [comment]
@kgorol Access your web server via `http://localhost:4200` instead of `localhost:4200`. Otherwise ungoogled-chromium will default to HTTPS.

**Comment by kgorol** [comment]
@xsmile I've tried already to access localhost like that, but it still redirects me to https://

**Comment by PF4Public** [comment]
Then you need to check configuration of your server, it may have a self-signed certificate or absent one.

**Comment by kgorol** [comment]
The server does not need to be super complicated, for example empty initial Angular app behaves exactly the same.

**Comment by PF4Public** [comment]
Help us help you.

**Comment by xsmile** [comment]
@kgorol Does your server offer HTTPS? Can you paste the command you use to run it?

For instance, I can run a Python web server with `python3 -m http.server 4200` and connect to it via `http://localhost:4200/` without issues. This is on Arch Linux with version 83.0.4103.116 though.

If your server does support HTTPS and ungoogled-chromium does not open the page, then this is another issue.

**Comment by Eloston** [comment]
Closing because HTTPS is no longer default.
