### ISSUE TITLE
Does this work in Xubuntu 16.10 ?

### ISSUE THREAD

**Issue by castor-troy** [Eloston/ungoogled-chromium#109]
I am getting some libav-fmpeg56 error? Is this supported in Xubuntu 16.10 ?

**Comment by Eloston** [comment]
Do you have a libav-ffmpeg56 package? If not, then you'll probably need to build packages on your own system for now.

**Comment by 9Morello** [comment]
I just tested and the master branch currently builds and works on Xubuntu 16.10.

I got an error with the latest tag release (which didn't seem related to 16.10). Unfortunately I fucked up and forgot to save the log. I *think* it was something with 'print_backend_cups.cc'.

**Comment by 9Morello** [comment]
@Eloston those terms are fine by me. I don't expect to meet nearly as many errors on Ubuntu 16.10 as we normally get on OS X.

I'll provide builds for both in the next release then.

**Comment by Eloston** [comment]
@9Morello: Cool, thanks.
