### ISSUE TITLE
Different types of Chrome Duet doesn't work

### ISSUE THREAD

**Issue by nullsurfer** [Eloston/ungoogled-chromium#1090]
Currently, there are three types of Chrome Duet:

![Screenshot_20200627-182244106](https://user-images.githubusercontent.com/67369340/85920085-55fc4e80-b8a3-11ea-8f8b-544246eccdf1.jpg)

I use "Enabled Home-Search-TabSwitcher Variation" but my bottom bar becomes "Home-Search-Share". Tried changing variations, enabling and disabling, but didn't help. 

Using Ungoogled Chromium 83.0.4103.106 on OnePlus 6, Android 10.

**Comment by wchen342** [comment]
It is an upstream problem, see the discussions in [https://github.com/bromite/bromite/issues/580](https://github.com/bromite/bromite/issues/580).

**Comment by nullsurfer** [comment]
> It is an upstream problem, see the discussions in [bromite/bromite#580](https://github.com/bromite/bromite/issues/580).

Odd. It works just fine in Chrome though.

**Comment by wchen342** [comment]
It is reported that the flag is removed in Chrome v84 beta so can you try that to confirm?

**Comment by nullsurfer** [comment]
> It is reported that the flag is removed in Chrome v84 beta so can you try that to confirm?

It is removed in 84. Guess I gotta have to stretch my fingers more often

**Comment by Eloston** [comment]
Closing because it's an upstream issue.
