### ISSUE TITLE
chrome://settings/searchEngines doesn't work

### ISSUE THREAD

**Issue by nullsurfer** [Eloston/ungoogled-chromium#1091]
**Describe the bug**
chrome://settings/searchEngines brings ERR INVALID_URL. I was gonna use it to edit Suggestion URLs

**To Reproduce**
1. Go to chrome://settings/searchEngines

**Expected behavior**
A page appears that let me edit search suggestion URLs

**Environment (please complete the following information):**
 - OS/Platform and version: Android 10
 - ungoogled-chromium version: 83

**Comment by wchen342** [comment]
Android version does not have that page. The link only works on desktop versions.

**Comment by Eloston** [comment]
Closing because it works as intended.
