### ISSUE TITLE
Ungoogled Chromium 83 for macOS: when?

### ISSUE THREAD

**Issue by DutchPete** [Eloston/ungoogled-chromium#1092]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*

When wis this version coming out? The Windows version has been out 2 weeks now.

**Comment by adamabdulahi** [comment]
You can download stable builds from [here](https://chromium.woolyss.com/#mac)

**Comment by DutchPete** [comment]
@adamabdulahi Thanks, but I have UC installed via Homebrew cask.

**Comment by DutchPete** [comment]
So, when oh when will 83 for Homebrew be released??????
Please, why do I even have to beg for it?

**Comment by Eloston** [comment]
We are not associated with Homebrew. You should contact Homebrew directly.

**Comment by DutchPete** [comment]
My apologies. Homebrew is new to me, and I thought apps' devs released the relevant binaries to Homebrew.
