### ISSUE TITLE
Error code: RESULT_CODE_UNINSTALL_USER_CANCEL

### ISSUE THREAD

**Issue by gigabit2** [Eloston/ungoogled-chromium#1093]
**Describe the bug**
I am getting an error message on macOS. _Error code: RESULT_CODE_UNINSTALL_USER_CANCEL_

**To Reproduce**
1. Go to [https://www.youtube.com/](https://www.youtube.com/)
2. Choose a video
3. Error message is displayed

If the error is not displayed, try clicking through a few videos and the error will show. [This video](https://www.youtube.com/watch?v=8ntSYy1ZdEg) causes it to happen for me.

**Expected behavior**
Error message should not be displayed and page should load normally

**Screenshots**
![Screenshot 2020-07-02 at 19 02 49](https://user-images.githubusercontent.com/4457688/86394535-a7874d80-bc96-11ea-9602-18ebc29dfa26.png)

**Environment (please complete the following information):**
 - OS/Platform and version: macOS 10.15.5
 - ungoogled-chromium version: 83.0.4103.116

**Additional context**
It does not occur on Microsoft Edge (Chromium, 83.0.478.58), nor Apple Safari (13.1.1)

**Comment by elsnorrow** [comment]
Same here, also the same version (Version 83.0.4103.116 (Official Build) (64-bit)) and same OS. It happened occasionally on the previous build but now it just keeps happening. I first thought this was due to some extensions I'm using, but even after disabling them I get the same error.

Google Chrome & Safari don't seem to have the issue.

**Comment by PF4Public** [comment]
Isn't this the same as #1083 ?

**Comment by elsnorrow** [comment]
> Isn't this the same as #1083 ?

Looks like it! I will try the patch and see whether this solves the issue. Thnks for pointing it out.

**Comment by elsnorrow** [comment]
Patch of #1083 works. Just confirmed, would be good to push a new "official" release soon. This issue can be closed.
