### ISSUE TITLE
missing key issue on mint focal

### ISSUE THREAD

**Issue by RanTrycl** [Eloston/ungoogled-chromium#1095]
I apologize for my lack of technical knowledge. I'm having trouble with the keys installing this on Focal. Get the errors:
```

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 02456C79B2FD48BF
W: Failed to fetch http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 02456C79B2FD48BF

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 02456C79B2FD48BF
Executing: /tmp/apt-key-gpghome.lbukA9AdfB/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 02456C79B2FD48BF
gpg: keyserver receive failed: No data

```
Thank you for any comments.

**Comment by nicolaasjan** [comment]
There is a bug regarding to the OBS instructions.
See here:
https://github.com/linuxmint/mintsources/issues/205
(is for Linux Mint, but applies to Ubuntu as well)

See also here:
https://forums.linuxmint.com/viewtopic.php?p=1839169#p1839169

Try this:
`sudo rm -v '/etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc'`

`wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Focal/Release.key -O - | sudo apt-key add -`

`apt update`

**Comment by RanTrycl** [comment]
Of course this worked perfectly! Thank you extremely!

**Comment by nicolaasjan** [comment]
Glad I could help you.

I think this issue can be closed now?

**Comment by RanTrycl** [comment]
ah yeah, thanks. :)
