### ISSUE TITLE
Some website supporting PWA (Progressive Web Apps) doesn't suggest to install the app.

### ISSUE THREAD

**Issue by nam108** [Eloston/ungoogled-chromium#1096]
I wasn't sure where could be better place to post it, either here or google forum, but I assumed that it would be better here.
So in short I found that some websites that are supporting PWAs and suggest in the adress bar that I can install them, some of those website in ungoogled chromium they don't. In normal chrome it suggest normally. I was wondering what could be the reason and if it could be maybe worked around somehow?

Website that suggested me to install it's app - https://www.digitalpalireader.online/
Website that didn't - https://suttacentral.net/

**Environment (please complete the following information):**
 - OS/Platform and version: Win 8.1 32bit
 - ungoogled-chromium version: 80.0.3987.132

**Comment by Eloston** [comment]
Hmm it works on version 81 for Debian. Perhaps it could be an issue due to using an older version? Are you able to try a newer version?

**Comment by nam108** [comment]
No, this is the newest one compiled by someone. I didn't went into
compiling yet and won't have resources for that. I will try to keep an
eye on it tho. Thanks for the review.

**Comment by Eloston** [comment]
Closing because 84 is out for Windows.

**Comment by nam108** [comment]
> Closing because 84 is out for Windows.

Sadly my OS i 32bit, so I still have to wait in hopes someone will compile it finally :(

**Comment by r4sas** [comment]
> Sadly my OS i 32bit, so I still have to wait in hopes someone will compile it finally :(

Will be added soon: https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/188
