### ISSUE TITLE
crashes at random times

### ISSUE THREAD

**Issue by Fallast** [Eloston/ungoogled-chromium#1097]
it closes itself, crashes on random periods of times, its always unexpected.
this is what i get on my terminal when i run chromium

MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open i915 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: i915
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver
[21928:21944:0706/063701.416601:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018

and this is what i get when it crashes
[21886:21907:0706/064518.083945:FATAL:ref_counted.cc(66)] Check failed: --ref_count_ != std::numeric_limits<decltype(ref_count_)>::max(). 
#0 0x563f32d281a9 (/usr/lib/chromium/chromium+0x440a1a8)

Received signal 6
#0 0x563f32d281a9 (/usr/lib/chromium/chromium+0x440a1a8)
  r8: 0000000000000000  r9: 00007ff04dfdc070 r10: 0000000000000008 r11: 0000000000000246
 r12: 000000000000008a r13: 00007ff04dfdd340 r14: 00003930c0e24008 r15: 00007ff04dfdd338
  di: 0000000000000002  si: 00007ff04dfdc070  bp: 00007ff04dfdc2c0  bx: 00007ff04dfdc324
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007ff061b2de97  sp: 00007ff04dfdc070
  ip: 00007ff061b2de97 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Environment (please complete the following information):**
 - Linux mint 19.3
 - ungoogled-chromium version: Version 83.0.4103.116 (Developer Build) built on Ubuntu bionic/18.04, running on LinuxMint tricia/19.3 (64-bit)

**Comment by PF4Public** [comment]
could be related to #1089

**Comment by Fallast** [comment]
> could be related to #1089

i think so

**Comment by Fallast** [comment]
something i should point out is that im getting the same errors on google chrome

**Comment by Fallast** [comment]
i think i've fixed it, i basically uninstalled everything related to chromium and also google-chrome, no im not getting these mesa errors

**Comment by Fallast** [comment]
nevermind, still not fixed

**Comment by andreasmjg** [comment]
Same here, random crashes

**Comment by Fallast** [comment]
it's working for me now, i dont know if the update fixed it for me or if it was this command i tried:
sudo apt purge xserver-xorg-video-inte

**Comment by braewoods** [comment]
Latest patches from upstream should now be out in the build. This is probably going to make a real difference for most.
