### ISSUE TITLE
How to use Flash?

### ISSUE THREAD

**Issue by tristan-k** [Eloston/ungoogled-chromium#11]
There are [ways](http://www.webupd8.org/2014/05/install-fresh-player-plugin-in-ubuntu.html) to use chromium with Flash. For example via PepperFlash. Is Ungoogled Chromium compatible with PepperFlash?

**Comment by Eloston** [comment]
Yes, it is.

**Comment by KyleSanderson** [comment]
@Eloston you should put this in the readme.
