### ISSUE TITLE
Pre-installing extensions into ungoogled-chromium

### ISSUE THREAD

**Issue by blymed** [Eloston/ungoogled-chromium#1102]
**Describe the bug**
In order to pre-install extensions into a regular Chrome installation from a local .crx file, you just need to edit the registry in the path "Software\\Google\\Chrome\\Extensions" (or as set in external_registry_loader_win.cc). My current approach works for Chrome, but not for ungoogled-chromium. 

**To Reproduce**
1. Add an entry to Software\\Google\\Chrome\\Extensions with the id of your extension:
<img width="209" alt="Screen Shot 2020-07-10 at 20 29 01" src="https://user-images.githubusercontent.com/46053275/87186591-0e86b100-c2ec-11ea-8e5f-07b6b2f86cd8.png">
2. Add the following values:
<img width="343" alt="Screen Shot 2020-07-10 at 20 29 06" src="https://user-images.githubusercontent.com/46053275/87186681-32e28d80-c2ec-11ea-8cd0-e3a4bbef1cb1.png">
Obviously, both "path" and "version" should be your own custom values. 
3. Launch ungoogled-chromium and go to chome://extensions. You will not see the added extension, but if you go to the same link in Chrome you will see it. 

**Expected behavior**
The extension is expected to appear on chrome://extensions after such manipulations. 

**Environment (please complete the following information):**
 - Win 10 x64
 - ungoogled-chromium version: 80.0.3987

**Comment by xsmile** [comment]
This method works well for me with the the latest version 81.0.4044.138-1.1 from the Downloads section.

You might have blacklisted your extension by removing it manually via the chrome://extensions page instead of removing the registry key, see https://developer.chrome.com/apps/external_extensions#faq (bottom)

**Comment by artemixer** [comment]
> This method works well for me with the the latest version 81.0.4044.138-1.1 from the Downloads section.
> 
> You might have blacklisted your extension by removing it manually via the chrome://extensions page instead of removing the registry key, see https://developer.chrome.com/apps/external_extensions#faq (bottom)

I have also considered this possibility and added a whitelisting entry to counter that. 
<img width="594" alt="Screen Shot 2020-07-10 at 22 56 17" src="https://user-images.githubusercontent.com/46053275/87202489-f5d4c600-c300-11ea-8a16-8b363af0f65c.png">
Even if I delete the extension manually in Chrome, it still comes back on the next launch. Unlike for ungoogled-chromium, in which does not install at all.

**Comment by xsmile** [comment]
Your latest screenshot shows that you added the keys under HKEY_LOCAL_MACHINE. This won't work. You need to use HKEY_CURRENT_USER instead. I'm not sure if Chrome and Chromium behave differently in this case.

**Comment by artemixer** [comment]
> Your latest screenshot shows that you added the keys under HKEY_LOCAL_MACHINE. This won't work. You need to use HKEY_CURRENT_USER instead. I'm not sure if Chrome and Chromium behave differently in this case.

Really weird, but adding the keys into HKEY_CURRENT_USER did not seem to change anything. 
<img width="668" alt="Screen Shot 2020-07-11 at 08 41 56" src="https://user-images.githubusercontent.com/46053275/87218441-fc8c2900-c352-11ea-8fa8-cc9934697972.png">
P.S I am using a different profile for each test, so there is no possibility of blacklisting being the reason for this issue.

**Comment by artemixer** [comment]
For reference, here is the .crx package of the extension I am trying to install: [crx.zip](https://github.com/Eloston/ungoogled-chromium/files/4906442/crx.zip)

**Comment by xsmile** [comment]
Indeed, the extension doesn't show up with 80.0.3987.132-1 from the Downloads page.

**Comment by blymed** [comment]
So the cause is the browser version?

**Comment by blymed** [comment]
After some testing, it seems like 80.0 is simply not compatible with this method, but 81.0 works perfectly fine.
