### ISSUE TITLE
getting RESULT_CODE_UNINSTALL_USER_CANCEL while trying to load gmail or youtube

### ISSUE THREAD

**Issue by toniz4** [Eloston/ungoogled-chromium#1108]
**Describe the bug**
after updating on the latest build on the aur i got this problem, i can't load youtube videos, i disabled all extentions, cleared the cache, and user configs, used in incognito and logged on youtube, and when i'm logged into youtube i can't load the main page.
**To Reproduce**
I can't pinpoint on how to reproduce the error.

**Expected behavior**
i want o load youtube videos

**Environment (please complete the following information):**
 - OS/Platform and version: Artix linux
 - ungoogled-chromium version: Version 83.0.4103.116

![2020-07-16-182923_1366x768_scrot](https://user-images.githubusercontent.com/14265358/87724814-7593e200-c792-11ea-8d8d-f8e7a4cfc871.png)

**Comment by Zoraver** [comment]
What version of clang did you use to compile ungoogled-chromium?

**Comment by toniz4** [comment]
> What version of clang did you use to compile ungoogled-chromium?
clang version 10.0.0

**Comment by PF4Public** [comment]
Please, do a search first next time: #1093

**Comment by jstkdng** [comment]
the ffmpeg 4.3 patch was added to the v84 update. Will take a while for it to compile, once it is done I'll pr the repo. In the meantime you can get a v83 version with the patch here https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-83.0.4103.116-4-x86_64.pkg.tar.zst

**Comment by toniz4** [comment]
> Please, do a search first next time: #1093 #1083

sorry about that
