### ISSUE TITLE
Add option to enable/disable "blocked attempted request" infobar

### ISSUE THREAD

**Issue by notDavid** [Eloston/ungoogled-chromium#111]
I'm getting so much popups of "blocked attempted request" that it's starting to annoy me. I constantly have to try to hit a tiny "x" with the mouse pointer to close the banner.

Would it be possible to add some configuration option, for the popup bar to automatically disappear after x seconds, or disable it entirely?

Thanks :)

**Comment by Eloston** [comment]
Wait really? What platform and version are you running? What do you do that triggers this?

**Comment by notDavid** [comment]
OS X 10.12.1, 53.0.2785.116 (64-bit).

I don't know, i just opened Chromium for example, and immediately got a popup. Closed it, then browsed to some random website and within 15 seconds got a second popup. Another website, no popup. Went to Reddit.com clicked around a bit and another popup within 20 seconds.... etc.

http://i.imgur.com/3bsvWTS.png

**Comment by 9Morello** [comment]
Are you logged into Google?

**Comment by notDavid** [comment]
Nope (i don't even have a Google account..)

**Comment by Eloston** [comment]
So it's basically the same as #104 since the URL is the same, but it's a different platform and slightly different version. I have a feeling that they are triggered by the same common code, but I'm a bit puzzled why you have it but @9Morello and I don't have it.

I'll mark this as a bug for now as I can't say for sure this is a duplicate of #104.

**Comment by 9Morello** [comment]
Regarding the intent of the original post, it might be a good idea to implement a way to disable the notifications of blocked connection attempts. While a power user might prefer to have them on, I can see this being a problem if someone setups ungoogled-chromium for another person.

**Comment by Eloston** [comment]
@9Morello You have a good point.

**Comment by Eloston** [comment]
Due to a situation I encountered (more details in #104), I've changed #104 to capture all instances of the bug reported here, and reverted this issue back to the enhancement proposed originally.

**Comment by Eloston** [comment]
I just realized this is a duplicate of #112. Going to close this as such.
