### ISSUE TITLE
--disable-machine-id not working anymore in 84.0.4147.89

### ISSUE THREAD

**Issue by tomasz1986** [Eloston/ungoogled-chromium#1110]
Just a disclaimer - I am using the builds from https://github.com/macchrome/winchrome/releases, so there is always a possibility that something got broken in the build process. They are supposed to be a

>Standard build of Eloston's ungoogled-chromium. All patches applied apart from "Safe Browser"

though, so I am creating the issue here. Please forgive me if the error is related to that specific build rather than the original code.

Anyhow, Ungoogled Chromium 84.0.4147.89 seems not to preserve settings and extensions anymore in Windows when used between different Windows installations. Everything had worked fine previously, but after updating to 84.0.4147.89 the browser reset the settings and removed all extensions. I have also tested copying and trying to run the browser in a different Windows installation, and everything always gets reset, so it seems that the flag is not working at all.

**Comment by macchrome** [comment]
disable-machine-id works perfectly fine, particularly when the patch is applied cleanly.

I've updated the respective release.

**Comment by tomasz1986** [comment]
Thank you! The updated release no longer resets the configuration.
