### ISSUE TITLE
Use Edge Chromium to get rid of unwanted Google features

### ISSUE THREAD

**Issue by gabrossmann** [Eloston/ungoogled-chromium#1111]
Hey, just wandering if it would be possible to use Edge Chromium code to disable or remove unwanted pieces of codes that still exist in Chromium. Apparently, Edge removes or disables a lot of features of the original Chromium code. Would it be possible to use the source code and implement it in ungoogled-chromium ? Thanks

**Comment by mbakke** [comment]
I would expect Microsoft to add its own telemetry and similar.  Even if they don't today, they might tomorrow, so ungoogled-chromium would have to track both upstream Chromium changes as well as Microsofts changes.

If you have sufficient interest, you can probably adapt the ungoogled-chromium patches to apply on Edge and create a new project under the ungoogled-chromium umbrella.  But I don't see using Edge as an upstream for vanilla ungoogled-chromium as an option (does Edge even work on GNU/Linux and macOS?).

**Comment by Eloston** [comment]
Ultimately, the point of ungoogled-chromium is to be free of any web service dependencies (by default). It just so happens that Google Chrome and Chromium depend only on Google web services.

I agree with @mbakke's points, so I'll close this as wontfix. However if you decide to pursue this idea and achieve some success, I'd be curious to know.
