### ISSUE TITLE
"Managed by your organisation" showing in Chromium settings menu

### ISSUE THREAD

**Issue by barjoio** [Eloston/ungoogled-chromium#1112]
**Describe the bug**
At the bottom of the Chromium settings menu (3 dots meatball icon in the far right of the toolbar) there's an option saying "Managed by your organisation". Clicking the option takes me to "chrome://management/" where I have a Chromium settings page saying "Your administrator can change your browser setup remotely. Activity on this device may also be managed outside of Chrome. Learn more".

**To Reproduce**
1. Download ungoogled-chromium AppImage https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/
2. Mark as executable `sudo chmod +x ./ungoogled...`
3. Open the program and see in the settings menu.

**Expected behavior**
The "Managed by your organisation" option wouldn't be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/47948089/88075269-781a8100-cb70-11ea-8208-7fd129be53c9.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Solus Linux latest version
 - ungoogled-chromium version: Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by ryneeverett** [comment]
This would seem to be normal chromium behavior if there is any file in `/etc/chromium/policies/managed/`. See https://www.chromium.org/administrators/linux-quick-start.

**Comment by damascene** [comment]
I've similar issue. So is it normal?
here is a screenshot from my chrome://policy/
![image](https://user-images.githubusercontent.com/411046/101245914-1757a380-3721-11eb-9067-4dbd7ed7f3e7.png)

**Comment by samra-irshad** [comment]
same question

**Comment by gerrywastaken** [comment]
For anybody wanting to know what this is. Apparently you tried to look at your MRIs on Linux: [postinst](https://github.com/nroduit/Weasis/blob/be6e4bcb0730f3f35806b3145aa507b67940b290/weasis-distributions/script/resources/linux/postinst#L26-L30) so of course your browser is managed by your organisation, what were you expecting?
