### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by MrTeeXD** [Eloston/ungoogled-chromium#1119]
Hello there, this is just a Temporary issue but I wonder why theres no new Ungoogled Chromium Versions for Windows? I am using the Version 81.xxxx

**Comment by PF4Public** [comment]
You mean binary versions? Because nobody had compiled and submitted them.

**Comment by MrTeeXD** [comment]
Ahh understood. Closing this.

**Comment by PF4Public** [comment]
But you can always [compile it yourself](https://github.com/ungoogled-software/ungoogled-chromium-windows#building).
