### ISSUE TITLE
Allow disabling of "Blocked request to ..." infobars

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#112]
Suggested by @9Morello. Useful for non-powerusers who don't really care about this.

Should the infobar be disabled or enabled by default?

**Comment by 9Morello** [comment]
I think it should be enabled by default. I expect most users that come here would want to know if there was an attempt to phone Google. Its useful for finding bugs too.

But a little checkbox to disable it in the Settings page would do no harm. I'd use it if I was setting up ungoogled-chromium for someone else (less tech-familiar).

**Comment by Eloston** [comment]
Okay, sounds good. I'm thinking about adding a flag to `chrome://flags` to configure this since it's more of an "advanced" feature that most users don't care too much about.

**Comment by 9Morello** [comment]
Yeah, 'chrome://flags' seems better.

**Comment by Eloston** [comment]
Done.
