### ISSUE TITLE
What is the purpose of `fieldtrial_testing_like_official_build=true`?

### ISSUE THREAD

**Issue by wchen342** [Eloston/ungoogled-chromium#1121]
I have a bug in Android version that is related to this flag. What does it actually do? From the description in gn file it seems to be just some tests but somehow it causes different behavior when the flag is set to true.

**Comment by Eloston** [comment]
See https://github.com/Eloston/ungoogled-chromium/issues/580#issuecomment-441322312. But it looks like things have changed since then, what does the comment say now?

**Comment by wchen342** [comment]
The description is still the same. So from the thread it seems the definition of "tests" in this particular case is different from what I was thinking (the automated tests for coding purposes vs. user experience tests). There must be some flags in `chrome://flags` that this switch enabled, and that explains the behavior change.

**Comment by wchen342** [comment]
Ok I figured out the original issue. This can be closed now.
