### ISSUE TITLE
Is there any way to remove CryptoTokenExtension ?

### ISSUE THREAD

**Issue by TheJags** [Eloston/ungoogled-chromium#1123]
I have just installed Ungoogled Chromium for the first time on `Ubuntu MATE 20.04` from `OBS Production Project`, and the first thing I've noticed that, there are two extensions that cannot be removed.

1, CryptoTokenExtension
2, Chromium PDF Viewer

Now I'm OK with the PDF Viewer but would like to remove CryptoTokenExtension if there is a way. I've gone through the [closed issue #944](https://github.com/Eloston/ungoogled-chromium/issues/944) but didn't see any way to remove the extension.

Thanks alot.

**Comment by Eloston** [comment]
From a purely technical standpoint, yes. You can remove its files and its references from the source code and rebuild the browser.

I don't know the specifics for CryptoTokenExtension, but this is what you need to do to remove a built-in extension:

1. Remove the extension source code (JS and/or HTML) and its manifest.json
2. Remove references to the extension source code files from the GRIT (`.grd`) files
3. Remove references to the `IDR_*` constants from the C++ code that you just removed from the GRIT files above. To do this correctly, you'll need to remove the code that loads the extension during startup, and any other Chromium code that interacts with the extension (e.g. for CryptoTokenExtension, is there a 2FA browser interface that connects with it?)

Hopefully this answers your question.

**Comment by lua-rocks** [comment]
@Eloston It turns out that ungoogled-chromium comes with built-in malware by default and I have to ungoogle it myself?

**Comment by lua-rocks** [comment]
Obviously, if a person installs a browser, it means he needs a browser, not a pdf-viewer or crypto-miner. Anything not related to web browsing is malware.

**Comment by networkException** [comment]
It would be helpful to inform oneself before writing random nonsense. Cryptotoken has nothing to do with crypto currencies, its an early and deprecated api to communication with hardware tokens for multi factor authentication which is [planned to be removed in a future version](https://groups.google.com/a/chromium.org/g/blink-dev/c/xHC3AtU_65A/m/yg20tsVFBAAJ). Viewing PDFs is integrated into all major modern browsers and is a feature that users expect. Additionally malware is defined as software that causes damage to a computer by design, I don't know what drugs you need to be on to define a pdf viewer integrated into a browser codebase as that.

**Comment by codeswhite** [comment]
What this extension is for? In what situation would it be useful?
I suppose we can write a patch to remove it.

**Comment by networkException** [comment]
The extension is for using security hardware tokens as I already stated. Its basically only used by Google for Google Account login at this point and is planned to be removed (see the link above). In my install its not even listed in the extension page anymore and even if it was intended be used for tracking by Google it wouldn't work as it gets domain substituted like everything else: https://github.com/Eloston/ungoogled-chromium/issues/874#issuecomment-559604434

**Comment by lua-rocks** [comment]
It doesn't matter what the Wikipedia says. Overloading browser with unnecessary junk is a "damage" to RAM and CPU. For example, spyware is malware. Even if I don't care if a program is spying on me, I regard the very existence of such a program as malicious because it does something I didn't ask for.

**Comment by Nifury** [comment]
> I regard the very existence of such a program as malicious because it does something I didn't ask for.

That's interesting. Your operating system is also doing tons of things you didn't ask for.

**Comment by lua-rocks** [comment]
> That's interesting. Your operating system is also doing tons of things you didn't ask for.

Nope. I don't have a single useless package or service on my Arch-linux machine.

I installed each of them manually and I know exactly what they do and how much memory use, unlike the built-in plugins of this browser.

**Comment by codeswhite** [comment]
@lua-rocks
Please be polite, these people that work on this project are sacrificing their own free time for people like you and me.
The least we can do is be polite and thankful.

If something is bothering you you are always welcome to write your own patches to remove whatever parts of the program you wish.

If you are not satisfied with this project you are _welcome_ to go find yourself an alternative browser.

**Comment by lua-rocks** [comment]
@codeswhite You've got me wrong. I'm not going to insult anyone here and I'm grateful to the developers for their hard work. But I also don't veil my criticism and I express my thoughts openly, even if they seem rude to somebody, because I believe that criticism is just as useful as praise.

**Comment by lua-rocks** [comment]
When I speak ill of software, it does not mean that I speak ill of people. Software cannot be insulted. Especially since we're talking about plugins developed by Google.
