### ISSUE TITLE
[Feature request] Change the New Tab Page

### ISSUE THREAD

**Issue by Darthagnon** [Eloston/ungoogled-chromium#1125]
**Is your feature request related to a problem? Please describe.**
Last time I tried ungoogled Chromium, the new tab page was a stripped-back version of the vanilla Chrome new tab page, with nothing but a non-functional link to the Chrome Web Store, and it didn't seem to update with frequent sites, nor show anything else useful.

**Describe the solution you'd like**
Would it be possible to add a settings field to set a custom new tab page URL, similar to how [this extension](https://chrome.google.com/webstore/detail/change-new-tab/mocklpfdimiadpbgamlgehpgpodggahe) does it? or, at least, to set the default new tab page to something more useful that is still usable without Google services, e.g. ```chrome://apps```

**Describe alternatives you've considered**
There's the [Change New Tab](https://chrome.google.com/webstore/detail/change-new-tab/mocklpfdimiadpbgamlgehpgpodggahe) extension (best; recommended) and the [New Tab Redirect](https://chrome.google.com/webstore/detail/new-tab-redirect/icpgjfneehieebagbmdbhnlpiopdcmna) extension, but despite the small package size, when running, even the smallest one, Change New Tab, takes up 20MB RAM and creates a dedicated browser process. Chromium is demanding software, and the fewer extensions required, the better. I only recently realised that Chromium and related browsers do not provide a mechanism in settings to change the New Tab Page, and couldn't believe so basic an oversight had been made.

**Additional context**
```chrome://apps``` could work like a built-in speed-dial, if it was the default New Tab Page - the user can pin websites and see them as large icons, just like on a Speed Dial (one of the key selling points behind old Opera and a popular feature of Vivaldi and a plethora of extensions). There is the additional advantage that, from this native Chromium speed dial, the user can set most used pages to open in windows, as PWAs.

**Comment by wchen342** [comment]
> and it didn't seem to update with frequent sites, nor show anything else useful

Is your version not updaing visited sites? On my machine the new page will show the pages I last visited.

**Comment by Eloston** [comment]
I think https://github.com/Eloston/ungoogled-chromium/issues/1032#issuecomment-626381008 should answer your question. If there is a valid reason to make a UI change, I'd like to know. Closing as duplicate.

**Comment by Darthagnon** [comment]
> > and it didn't seem to update with frequent sites, nor show anything else useful
> 
> Is your version not updaing visited sites? On my machine the new page will show the pages I last visited.

Maybe it was a bad install when I last tried earlier this year - it wasn't updating the new tab page. I'll try again
