### ISSUE TITLE
Hide 'Current user' button next to the address bar

### ISSUE THREAD

**Issue by sgtpep** [Eloston/ungoogled-chromium#1126]
Is that possible to hide this button, that allows to sing in the Google account, for those who uses Chromium without singing it to it?

**Comment by Eloston** [comment]
It doesn't look like there's any configuration flag for it. I think the only way is to modify the source code.

**Comment by PF4Public** [comment]
@sgtpep Is this what you're asking for?
![image](https://user-images.githubusercontent.com/10319700/89892574-898b0200-dbdf-11ea-8658-748c1b5be6ad.png)
It is added by [patches/extra/ungoogled-chromium/add-flag-to-show-avatar-button.patch](../tree/master/patches/extra/ungoogled-chromium/add-flag-to-show-avatar-button.patch)

**Comment by sgtpep** [comment]
@PF4Public Exactly what I needed. Thank you so much!

**Comment by Eloston** [comment]
Huh.

**Comment by PF4Public** [comment]
Come to think of it, could we / should we probably change the name of this flag and reword its description, so that its purpose would be clearer and more obvious, for it to be easier to find? I do use this flag, which is obvious from a screenshot above, but if I didn't, I likely wouldn't be searching for an "avatar" or "button", I would have been searching for an "account", "user", "profile" etc.

**Comment by qvint** [comment]
The upstream calls it "[avatar toolbar button](https://source.chromium.org/search?q=kAvatarToolbarButton)".

**Comment by PF4Public** [comment]
And we may call it whatever we want:
https://github.com/Eloston/ungoogled-chromium/blob/4f574006aca69964995acfa0718e7097ce36c059/patches/extra/ungoogled-chromium/add-flag-to-show-avatar-button.patch#L27-L30

**Comment by Eloston** [comment]
I'd be okay with adding to the title and description. The flag name itself should remain since it's more of a technical detail.

**Comment by PF4Public** [comment]
> The flag name itself should remain since it's more of a technical detail.

Good point, some people might be already using it and changing the flag name will break this functionality for them.

I'll do a PR soon.
