### ISSUE TITLE
Windows Installer based on InnoSetup

### ISSUE THREAD

**Issue by Technologov** [Eloston/ungoogled-chromium#113]
Hello,

I have made a Chromium Windows Installer. (setup.exe)

[setup_src.zip](https://github.com/Eloston/ungoogled-chromium/files/578120/setup_src.zip)

Just rename "chrome.exe" into "chromium.exe" -- I recommend this to avoid confusion in Windows Task Manager. and put my code into .\Chromium\ Folder, then run Inno setup script compiler on my code.

Binary here - my Windows Installer:
https://www.dropbox.com/s/ski5sm2b6yxi8ud/Chromium_v53_Setup.exe?dl=0

-Alexey.E. "Technologov". 08.11.2016.

**Comment by Eloston** [comment]
Thanks for submitting this, but what are the benefits over the Windows installer system that Google provides?

**Comment by Technologov** [comment]
Today Chromium lacks Windows installer completely.
Only Google Chrome has it. So basically I decided to fill the void by creating my own installer from scratch.
I don't mind if you use someone else's installer, but we need one.

**Comment by Eloston** [comment]
Okay. I have created #115 to address the general issue here.
