### ISSUE TITLE
Remember passwords

### ISSUE THREAD

**Issue by arkomega** [Eloston/ungoogled-chromium#1133]
Hi, i have a problem when i'm using ungoogled chromium, i don't know if there is anyway to remember password when i'm logging in to like, youtube, twitch, twitter etc.. Everytime i go to twitch, youtube, the browser unlog me and i need to enter my email and my password everytime.

Isn't there a way to make the browser remember my passwords?
![image](https://user-images.githubusercontent.com/67123792/90128296-f7156a80-dd66-11ea-863d-93c2d5d1c994.png)

**Comment by PF4Public** [comment]
#1012 #803 #755 to name a few.

**Comment by arkomega** [comment]
> #1012 #803 #755 to name a few.
> 
> This needs to be explained in FAQ, I guess, I'll do a PR soon.

It worked thanks ^^
