### ISSUE TITLE
FAQ: "How to get FIDO U2F security keys to work in Google sign in?" solution no longer works

### ISSUE THREAD

**Issue by felmey** [Eloston/ungoogled-chromium#1136]
I've tried multiple times after rebooting to get the extension recommended in the FAQ but it seems to no longer work.  When clicking on the Add to Chromium button, a blank page opens and there is no request pop up to install.  I can't tell if this is a problem with the Chrome Store extension or if ungoogled chromium is handling it incorrectly though.  Regardless, it does not seem to work anymore as a solution.

FAQ link:
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-to-get-fido-u2f-security-keys-to-work-in-google-sign-in

Chome Web Store link:
https://chrome.google.com/webstore/detail/gnubbyd/beknehfpfkghjoafdifaflglpjkojoco

Environment (please complete the following information):

OS/Platform and version: Arch Linux
ungoogled-chromium version: Version 84.0.4147.105 (Official Build) Arch Linux (64-bit)

**Comment by Eloston** [comment]
I also cannot seem to download the extension. According to the Support page of the extension, one user reports that the extension is "not compatible with Chrome".

I also tried inspecting the direct link, but it seems no update URL is provided for any given `prodversion`: https://clients2.google.com/service/update2/crx?acceptformat=crx2,crx3&prodversion=84&x=id%3Dbeknehfpfkghjoafdifaflglpjkojoco%26installsource%3Dondemand%26uc

Does the U2F key not work without the extension?

**Comment by felmey** [comment]
Okay, good to know it's not just me!

I can login to other websites with my key.  So it the U2F key does work with ungoogled-chromium.  A pop up message asked me to press a button on the key.   It seems that the websites that actually ask you to press a button on the key work fine so far.  Google login simply detects if /when the key is plugged in, without and button press.

**Comment by felmey** [comment]
FYI, I just used one of my bacup methods of 2FA and registered my browser.  I will rarely have to use this feature now that the browser is registered.  Unless this is someones only means of authenticating with Google, I would rank this as a low priority issue.

**Comment by felmey** [comment]
My security key works fine authenticating with github.com.  So far it's just google with which it won't work in ungoogled-chromium.

**Comment by Eloston** [comment]
> I think it also worked in Chromium prior to installing ungoogled-chromium.

Are you saying it would no longer work in Chromium after you used the user data directory in ungoogled-chromium? If so, can you compare the user data directory between (a) when you get it working in Chromium and (b) when you try to use it in ungoogled-chromium?

**Comment by felmey** [comment]
Eloston, I had to uninstall Chromium in order for ungoogled-chromium to install on my Arch system...  they conflicted during the install.  But when I started up ungoogled-chromium it would immediately close (with a segfault if ran from terminal) until I deleted the ~/.config/chromium directory.  Once I deleted that, ungoogled-chromium started fine.

But yes, the U2F security key I'm using worked fine in Chromium.  I can reinstall Chromium and run any tests if that would help.

**Comment by Eloston** [comment]
Actually, this might be because of `patches/core/ungoogled-chromium/disable-gaia.patch`. I'm not sure if removing this patch will cause unwanted Google connections again (#104), so testers are welcome.

**Comment by securingmom** [comment]
Please explain the rational of using ungoogled chromium while persisting use of google services.

**Comment by 0xC0ncord** [comment]
> Actually, this might be because of `patches/core/ungoogled-chromium/disable-gaia.patch`. I'm not sure if removing this patch will cause unwanted Google connections again (#104), so testers are welcome.

I just tested this without the `disable-gaia.patch` and am seeing the same behavior as @felmey where I cannot log in via U2F. I'm not sure if I also need the gnubby extension to test this, but even so it seems that extension is still no longer available from the Chrome web store. Nonetheless, it seems a solution to #874 would also fix this one.

**Comment by PF4Public** [comment]
I see no reason to keeping these issues open then.

**Comment by PF4Public** [comment]
BTW @0xC0ncord Would it be useful to add contents from an environment variable (say SKIP_UC_PATCHES) into ungoogled-chromium ebuild into [ugc_unneeded](https://github.com/PF4Public/gentoo-overlay/blob/2fd023153f68d1000537dcb9642030ff1c2b37e4/www-client/ungoogled-chromium/ungoogled-chromium-94.0.4606.81-r1.ebuild#L322-L325) variable to allow for skipping patches locally?

**Comment by joesixpack** [comment]
2+ years later and its STILL an issue.

**Comment by PF4Public** [comment]
> 2+ years later and its STILL an issue.

May we have a more elaborate explanation of why is it an issue still?

**Comment by networkException** [comment]
The extension I linked to above should be removed since 104, I honestly don't know what kind of black magic is pulling here to block WebAuthn from working correctly. I'm not much of a JS reverse engineer myself and there wasn't anything immediately suspicious in the console or network tab.
