### ISSUE TITLE
Missing critical security features

### ISSUE THREAD

**Issue by BullShark** [Eloston/ungoogled-chromium#1143]
**Describe the bug**
Configuring DoH DNS over HTTPS is missing from the Windows build of ungoogled chromium.

Patch here -> https://git.droidware.info/wchen342/ungoogled-chromium-android/src/branch/master/patches/Bromite/Add-user-setting-for-DNS-over-HTTPS-DoH-custom-URL.patch

**To Reproduce**
1. Go to chrome://flags and search dns.
2. Click on DNS over HTTPS, and enable it.
3. Let the browser restart after making the change. It will ask to restart. Next go to preferences.
4. This is missing from the Windows build Version 84.0.4147.105 (Developer Build) (64-bit).

**DOH settings in ungoogled chromium running on Android**

![signal-2020-08-19-005408](https://user-images.githubusercontent.com/1526595/90601616-1b85a280-e1be-11ea-9ffd-312d684d7c9f.png)
![signal-2020-08-19-005414](https://user-images.githubusercontent.com/1526595/90601619-1d4f6600-e1be-11ea-9ac8-8cceaf42bd49.png)
![signal-2020-08-19-005403](https://user-images.githubusercontent.com/1526595/90601770-512a8b80-e1be-11ea-96e6-72eeb16b9116.png)

More info here:
https://www.bromite.org/doh

https://github.com/bromite/bromite/wiki/Enabling-DNS-over-HTTPS

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version: Windoze 10
 - ungoogled-chromium version:

**Additional context**

**Comment by HarukaMa** [comment]
From https://www.chromium.org/developers/dns-over-https, it seems this feature is still in staged rollout:

> We've enabled an experiment in Chrome 83 for a fraction of our users with the following scope.

You may need to change the source code or use Inspect to manipulate the states in JS in settings page to enable this feature at this time. I guess it is controlled by "variations" and it seems UC is not affected by that but I could be totally wrong there.

**Comment by Eloston** [comment]
Based on @HarukaMa's info, I'll let Google roll out the feature when it's ready.
