### ISSUE TITLE
Wrong auto-generated file naming when second time saving the website to single file mhtml file.

### ISSUE THREAD

**Issue by nam108** [Eloston/ungoogled-chromium#1145]
**Describe the bug**
I don't know if it's windows, or chromium but when I want to save a website as a "whole single file website", the first time it's saved as mhtml, but the next time, although it also saves the whole website to one file, the autogenerated name for the file is no longer mhtml but just html.

**Environment (please complete the following information):**
 - OS/Platform and version: win 8.1 (32 bit)
 - ungoogled-chromium version: 84.0.4147.105

**Comment by NuclearWinter** [comment]
Version 92.0.4481.0 Chromium - same bug
