### ISSUE TITLE
Create Windows installer

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#115]
People have been requesting this, so I created this issue as a response.

Ideally, the installer system that Google created should be used (if it is possible without using Google's pre-built binaries). Other installer systems must not be considered until it can be shown that Google's installer system has problems that another system solves.

I have no interest nor the time to implement this. I am open to anyone taking up this task.

**Comment by DeadSix27** [comment]
I worked on that.
Created a simple installer creating script. For authors.
But what about signing them?
Code Signing Certificates are very expensive more than 150$ /year 
I could easily self-sign them but that would still popup a warning that might scare users off.

**Comment by Eloston** [comment]
You can use GPG to sign the installer file and provide the signature file as a separate download. This makes it easier for non-Windows users to sign binaries and upload them. We should discuss the signing system in more detail on Gitter or elsewhere.

Regarding the installer, I think there are scripts and tools to create installers. I know of mini_installer, but there may be others.

**Comment by woolyss** [comment]
@Eloston : Henry updated its tool (chrlauncher) to install, update and launch ungoogled-chromium ;)
https://github.com/henrypp/chrlauncher/issues/33#issuecomment-279736691

**Comment by Eloston** [comment]
Windows installers have been introduced a few versions ago at the time of writing.
