### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by AXLR0sE** [Eloston/ungoogled-chromium#1151]
Trying to build ungoogled chromium and getting this error:

FAILED: gen/ui/gfx/x/damage_undef.h gen/ui/gfx/x/damage.h gen/ui/gfx/x/damage.cc 
python ../../ui/gfx/x/gen_xproto.py /usr/share/xcb/damage.xml gen/ui/gfx/x/damage_undef.h gen/ui/gfx/x/damage.h gen/ui/gfx/x/damage.cc
Traceback (most recent call last):
  File "../../ui/gfx/x/gen_xproto.py", line 1028, in <module>
    sys.exit(main())
  File "../../ui/gfx/x/gen_xproto.py", line 1018, in main
    import xcbgen.xtypes
ImportError: No module named xcbgen.xtypes
ninja: build stopped: subcommand failed.
=> ERROR: chromium-84.0.4147.125_1: do_build: 'ninja -C out/Release ${makejobs} chrome chromedriver mksnapshot' exited with 1
=> ERROR:   in do_build() at srcpkgs/chromium/template:272
Ive serched for this module but just cant find.
any solutions?

**Comment by mbakke** [comment]
You need a version of `xcb-proto` built with Python 2.

**Comment by Eloston** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/1151#issuecomment-680043925 is correct, closing.
