### ISSUE TITLE
Immediate crash running v84 on Ubuntu Bionic

### ISSUE THREAD

**Issue by eater** [Eloston/ungoogled-chromium#1154]
**Describe the bug**

As initially reported in #1089, since upgrading to v83, ungoogled-chromium crashes a few seconds after I launch it, whether or not I do anything in the browser window. The bug persists in 84.0.4147.135-1.bionic1. I do not see the bug in regular Chromium. 

**To Reproduce**
1. Add the [Bionic PPA](https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium#directUbuntu).
2. Run `apt install ungoogled-chromium` and install v84.0.4147.135-1.bionic1.
3. In a terminal, execute `chromium`
4. Chromium browser window opens, looking normal. After a few seconds, the window disappears. The terminal says:
```
[6230:6230:0825/185205.074797:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[6232:6275:0825/185205.405967:ERROR:url_request.cc(569)] Block URL in URLRequest: https://update.9oo91eapis.qjz9zk/service/update2/json
[6232:6275:0825/185205.406130:ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://update.9oo91eapis.qjz9zk/service/update2/json
Received signal 11 SEGV_MAPERR 000000000000
#0 0x560d261c7d49 (/usr/lib/chromium/chromium+0x44cbd48)
  r8: 00002f12f9bbbdb0  r9: 0000000000000000 r10: 0000000000000001 r11: 0000000000000000
 r12: 00007f3a833f7450 r13: 00002f12f9bbbdb0 r14: 00007f3a833f74c8 r15: 00002f12f94b5c00
  di: 0000000000000000  si: 4f285dd87b802459  bp: 00007f3a833f73c0  bx: 0000000000000000
  dx: 3fa41dc043beccd7  ax: 002f0b1dc60ef329  cx: 00007f3a833f74c8  sp: 00007f3a833f7380
  ip: 0000560d2835138d efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Expected behavior**
The browser should stay open and allow itself to be used for browsing.

**Environment (please complete the following information):**
 - OS/Platform and version: Ubuntu Bionic (18.04)
 - ungoogled-chromium version: 84.0.4147.135-1.bionic1

**Comment by braewoods** [comment]
Does it occur from a fresh profile?

**Comment by eater** [comment]
On v83, it DID occur with a fresh profile. On v84 it does NOT occur with a fresh profile. Still I'd like to solve whatever's in the profile that's triggering it now.

**Comment by gr01d** [comment]
I am using `Version 84.0.4147.135 (Developer Build) built on Debian buster/10, running on / (64-bit)`
 and it does not crash on me. 84.0.4147.135-1.buster1, maybe an OS issue?
Have you tried the AppImage version?

**Comment by eater** [comment]
The only AppImage I've found isn't compatible; it just tells me ` /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found `

**Comment by Eloston** [comment]
A backtrace would be helpful to diagnose the segfault, please install the `dbgsym` packages and launch Chromium with `chromium -g`. In GDB, use `run` to start the process, then use `bt` to get a backtrace after the process has crashed.

**Comment by eater** [comment]
Here you go. 
[gdb.txt](https://github.com/Eloston/ungoogled-chromium/files/5180095/gdb.txt)

**Comment by joubbi** [comment]
I have the exact same problem. I'm running Linux Mint 20 Ulyana.

**Comment by Eloston** [comment]
It's interesting GCM is getting triggered. Might be a bug in one of our patches.

**Comment by eater** [comment]
Can we leave this open?

**Comment by networkException** [comment]
Does the issue persist in the currently latest version?

**Comment by eater** [comment]
Yes, still the same.

**Comment by networkException** [comment]
So, [ungoogled-chromium-debian](https://github.com/ungoogled-software/ungoogled-chromium-debian) which also provides packaging for Ubuntu only has promised support for the latest LTS release. If this issue is reproducible on Ubuntu Focal or Impish please open a new issue there. Otherwise you can use a portable binary
