### ISSUE TITLE
Version 54 Update????

### ISSUE THREAD

**Issue by WackyModder84** [Eloston/ungoogled-chromium#116]
So the Chromium Browser has updated to Version 54 now.
Can we be expecting an updated release for UnGoogled under Version 54 anytime soon? =)

**Comment by Eloston** [comment]
Right now I'm waiting for inox-patchset to update to 54. Also I'm waiting for Debian to update to 54 (as this is the platform I develop on). I *might* release another update of 53 if 54 takes longer than expected.

I will close this issue once 54 is released.

**Comment by seb-m** [comment]
+1

I hit this nagging issue with version 53 https://sslmate.com/blog/post/ct_redaction_in_chrome_53

**Comment by japostoles** [comment]
+1, same here @seb-m

**Comment by Eloston** [comment]
This is bugging me too so I might skip over another release of 53.

**Comment by maciozo** [comment]
How does this happen to just Symantec certs?

**Comment by lenormf** [comment]
https://sslmate.com/blog/post/ct_redaction_in_chrome_53

**Comment by lenormf** [comment]
How are we doing on the update?

**Comment by Eloston** [comment]
Still waiting for Inox to update. Right now I'm working on #70, and then I will start working on #16 (which will solve some other issues). If inox hasn't updated by then, I may take matters into my own hands.

**Comment by VittGam** [comment]
Regarding the certificates breakage, you can find a workaround command-line flag on https://github.com/Eloston/ungoogled-chromium/issues/119#issuecomment-262473485.

**Comment by gcarq** [comment]
@Eloston I'm upgrading the inox-patchset to version 54 right now, a release can be expected tonight or tomorrow

**Comment by Eloston** [comment]
@gcarq Neat! Your change from GYP to GN should help me out too.

**Comment by gcarq** [comment]
@Eloston I'm glad you like it. Thanks for your patch to fix builds with `safe_browsing_mode=0`.

**Comment by Eloston** [comment]
Status update: a8ba2abf2a4048d8c96e639f38deddef1bcd2f40 allows building Debian stretch packages of 54 (I am using it right now). There's still quite a bit more to go; see [the 54.x.x.x milestone](https://github.com/Eloston/ungoogled-chromium/milestone/2). #104 is up next, then #41, and then the remaining platforms will follow.

**Comment by mimf** [comment]
How's the new version coming along?

**Comment by Eloston** [comment]
@mimf ungoogled-chromium is almost to version 55 now. It seems to be working well on Debian stretch. The macOS version seems to be a bit slower, screws up previously-saved website credentials, and Widevine support won't compile for it. It's also possible to build Archlinux builds (although there aren't any packages generated for it yet). And standard Linux builds (misnamed as Linux static) seem to work, as compiled on 14.04. Windows support is a WIP, and I've encountered an issue I'm not sure how to solve yet.

I'm thinking about releasing a tag version very soon, regardless of Windows support.

**Comment by mimf** [comment]
Oh, that's weird. My version is still version 53. The latest release was on the 24th of September. 

How do I go about getting the version 54? Is there a .deb installer?

**Comment by Eloston** [comment]
@mimf Sorry for not being specific enough. This is a build I made on my own machine for testing purposes, and it seems to be working well. I am in the process of preparing a new tag release.

**Comment by Eloston** [comment]
New release is out: [55.0.2883.75-1](https://github.com/Eloston/ungoogled-chromium/releases/tag/55.0.2883.75-1)

macOS build will be uploaded after I get the binaries for them. Other platforms will be uploaded in the future or in subsequent releases.

**Comment by mimf** [comment]
Thank you for the hard work! It would be cool to know the differences between all the versions. I mean, what's the difference between Driver and Sandbox?

**Comment by mimf** [comment]
I'm getting this error:

`sudo dpkg -i chromium_55.0.2883.75-1_amd64.deb 
Selecting previously unselected package chromium.
(Reading database ... 424043 files and directories currently installed.)
Preparing to unpack chromium_55.0.2883.75-1_amd64.deb ...
Unpacking chromium (55.0.2883.75-1) ...
dpkg: dependency problems prevent configuration of chromium:
 chromium depends on libavcodec57 (>= 7:3.2.1) | libavcodec-extra57 (>= 7:3.2.1); however:
  Package libavcodec57 is not installed.
  Package libavcodec-extra57 is not installed.
 chromium depends on libavformat57 (>= 7:3.2.1); however:
  Package libavformat57 is not installed.
 chromium depends on libavutil55 (>= 7:3.2.1); however:
  Package libavutil55 is not installed.
 chromium depends on libicu57 (>= 57.1-1~); however:
  Package libicu57 is not installed.
 chromium depends on libjpeg62-turbo (>= 1.3.1); however:
  Package libjpeg62-turbo is not installed.
 chromium depends on libminizip1 (>= 1.1); however:
  Package libminizip1 is not installed.
 chromium depends on libpng16-16 (>= 1.6.2-1); however:
  Package libpng16-16 is not installed.
 chromium depends on libre2-3 (>= 20160901); however:
  Package libre2-3 is not installed.
 chromium depends on libvpx4 (>= 1.6.0); however:
  Package libvpx4 is not installed.
 chromium depends on libwebp6 (>= 0.
dpkg: error processing package chromium (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 chromium
