### ISSUE TITLE
Major security issue with chrome/chromium

### ISSUE THREAD

**Issue by BullShark** [Eloston/ungoogled-chromium#1162]
https://web.archive.org/web/20190126075111/http://www.favbrowser.com/google-chrome-spyware-confirmed

Has this been disabled? Where's the patch to disable it?

**Comment by jstkdng** [comment]
That's just the omnibar autocomplete. If you chose another provider, chrome would send the same stuff to that provider.

**Comment by BullShark** [comment]
Oh ok. GNU.org made it sound worse than that.

**Comment by Ahrotahn** [comment]
So I found the link you posted on GNU's site here: http://www.gnu.org/proprietary/malware-google.html

> Google Chrome contains a key logger that sends Google every URL typed in, one key at a time.

That's a bit of a stretch.  Using that definition, Firefox and any other browser that gives you search suggestions would also need to be added to that list.  

But it's not *entirely wrong* either.  You *are* sending what you're typing to Google (or whatever provider you're using for search).   That's just the nature of how search suggestions work.  They can only be given to you by sending them what you're typing and responding with a list to suggest to you.  

Ungoogled Chromium deals with this in two ways:

* Search Suggestions are disabled by default <sup>([link to patch](https://github.com/Eloston/ungoogled-chromium/blob/df199c04ff367da59ce52a23a3f3b305dd3b00c3/patches/extra/inox-patchset/0006-modify-default-prefs.patch#L51))</sup>

* The default search provider is set to "No Search".  A custom feature for Ungoogled Chromium that essentially disables the search provider <sup>([link to patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/core/ungoogled-chromium/replace-google-search-engine-with-nosearch.patch))</sup>  

So by default what you type in the omnibar is not sent to Google and you get to decide for yourself who you trust enough to enable the search/suggestions for.

**Comment by BullShark** [comment]
Ok thanks.
