### ISSUE TITLE
Interest Check: MacOS style shortcuts in Linux as chrome flag?

### ISSUE THREAD

**Issue by hparadiz** [Eloston/ungoogled-chromium#1163]
I got this working myself. See below screenshot.

![image](https://user-images.githubusercontent.com/195216/91729517-aaa59980-eb72-11ea-8c41-20a9f1d47c50.png)

I have the patch available here though isn't yet rebased against ungoogled-chromium's most recent release.
https://gist.github.com/hparadiz/36adeb38011a5046bd1a17a0107fb493

It's rather quite crude right now and doesn't actually let you change anything in Chrome flags but it does work. Was wondering if anyone else would find this useful?

**Comment by jstkdng** [comment]
Why don't you PR this repo? https://github.com/ungoogled-software/contrib

**Comment by hparadiz** [comment]
> Why don't you PR this repo? https://github.com/ungoogled-software/contrib

I didn't want to go through the process of doing the work for a pull request if it wasn't going to get merged in the end. For myself I don't really need a setting in chrome flags but I could see other people wanting that.

Just wanted to gauge interest first.

**Comment by jstkdng** [comment]
Well yeah, at least here, you'd have to add more code to add a flag for it that is disabled by default. In the contrib repo you should be able to PR as is, it's supposed to be more lenient after all.

**Comment by Eloston** [comment]
@jstkdng is right. Just PR the patch file with some useful info at the top of the patch (e.g. what you've described in this issue). You don't need to sweat the details.

**Comment by hparadiz** [comment]
I made the PR so I'm closing this.
