### ISSUE TITLE
Not offering to save passwords

### ISSUE THREAD

**Issue by therealrobster** [Eloston/ungoogled-chromium#1167]
**Describe the bug**
I removed Chromium and installed ungoogled-chromium.  I then started using and when I'm at a site that has a password, it doesn't ask to save the password.  It doesn't show the lock icon to update either.

**To Reproduce**
1. visit page with form / password
2. enter new details and save
3. nothing is offered to save password.

**Environment (please complete the following information):**
 - OS/Platform and version:  POP_OS! 20.04
 - ungoogled-chromium version: Version 84.0.4147.135 (Developer Build) built on Ubuntu focal/20.04, running on Pop focal/20.04 (64-bit)

**Comment by Ahrotahn** [comment]
Is the toggle enabled?
Settings > Passwords > Offer to save passwords

It's off by default

**Comment by therealrobster** [comment]
aaaand I am a complete idiot!  :-)

Thank you and sorry for the trouble.

**Comment by x-N0** [comment]
Please mark this as ![imagen](https://user-images.githubusercontent.com/51316342/92300508-57906580-ef29-11ea-9924-b44ae1dbb93b.png), @therealrobster. ;-)
