### ISSUE TITLE
Remove nonfree bits of Chromium code

### ISSUE THREAD

**Issue by picsi** [Eloston/ungoogled-chromium#117]
According to https://libreplanet.org/wiki/List_of_software_that_does_not_respect_the_Free_System_Distribution_Guidelines#chromium-browser and https://bugs.chromium.org/p/chromium/issues/detail?id=28291 there are some nonfree bits of code in the browser, which should be removed.

**Comment by Eloston** [comment]
I don't know if any fork of Chromium complies with the free software guidelines. If you are using Debian or Ubuntu, I adapt all of Debian's changes to ungoogled-chromium. I've also stripped almost all of the binary blobs through source cleaner (all of the machine code is gone; some data in binary form for page distillation and international components for unicode).

Also the sources you've referenced are based on Google's Chromium repository. If you are to bring up evidence, you should do so in reference to what is being used and what is processed through ungoogled-chromium.

**Comment by 9Morello** [comment]
Sorry if I'm missing something, but doesn't ungoogled-chromium already do that essentially, as @Eloston pointed out?

I don't know if you can get Chromium to work with only free software, but it works just fine with only OSS.

**Comment by Eloston** [comment]
@9Morello ungoogled-chromium has not been trying to conform with free software guidelines. It has been removing the binaries from the source tree and using source code.

**Comment by Eloston** [comment]
Closing as wontfix since this is impractical to accomplish without rewriting larger portions of source code to use free software. There simply isn't enough manpower.
