### ISSUE TITLE
OpenBSD ports

### ISSUE THREAD

**Issue by qlcom** [Eloston/ungoogled-chromium#1173]
can you put this into openbsd ports?
It will be very helpful for us.

**Comment by wchen342** [comment]
#918

**Comment by Master0ne** [comment]
Wow, great progress. I guess someone will have to post this to an appropriate OpenBSD mailing list for approval by OpenBSD devs?

I'm sorry that I can't help, still not using OpenBSD yet and nowhere near to contribute to the project, also no knowledge about the proper process to get a port added.
