### ISSUE TITLE
Force Desktop Mode

### ISSUE THREAD

**Issue by NoobCoder-today** [Eloston/ungoogled-chromium#1174]
I want the **Force Desktop Mode on All Sites** option to be added in future versions of this browser.
 
I am an Android x86 user, who uses Bliss OS, and I want all my tabs to be in Desktop mode without enabling it on all tabs individually. 

The likes of Brave and Kiwi have done a fantastic job in adding this, and I hope for the same to come here.

Thanks!

**Comment by wchen342** [comment]
Can you transfer the issue to [ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android)?

Is this because you are using Android on a chromebook or tablet? Then this functionality makes sense.

**Comment by NoobCoder-today** [comment]
> Is it because you are using Android on a chromebook or tablet? Then this functionality makes sense and I will add it in the future.

@wchen342 Yea, I use Android x86 (or Bliss OS) on my laptop.

**Comment by Eloston** [comment]
@wchen342 Unfortunately I can't transfer issues unless they are under the same user/organization. One day I will move this repo to the ungoogled-software organization, but for now I've migrated the issue to https://github.com/ungoogled-software/ungoogled-chromium-android/issues/33
