### ISSUE TITLE
Unable to compile 64bit swapimport on Windows

### ISSUE THREAD

**Issue by DeadSix27** [Eloston/ungoogled-chromium#118]
I've used git master:

```
[main]
chromium_version = 53.0.2785.143
release_revision = 1

```
I've added: 
`builder.target_arch = CPUArch.x64`
at
```
def main():
	try:
		builder = buildlib.get_builder()
                builder.target_arch = CPUArch.x64
```
in build.py

And changed:
`build_output = pathlib.Path("out", "Release")`
to
`build_output = pathlib.Path("out", "Release_x64")`
in:
common.py
(without the addition of _x64, it complains that I'm using the wrong arch)

However, I get this error (see bottom)

Any idea how to solve this?

```
[7395/20450] LINK_EMBED ..\..\third_party\syzygy\binaries\exe\swapimport.exe
FAILED: ../../third_party/syzygy/binaries/exe/swapimport.exe
C:\_chromium\depot_tools\python276_bin\python.exe gyp-win-tool link-with-manifests environment.x64 True ..\..\third_party\syzygy\binaries\exe\swapimport.exe "C:\_chromium\depot_tools\python276_bin\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:..\..\third_party\syzygy\binaries\exe\swapimport.exe @..\..\third_party\syzygy\binaries\exe\swapimport.exe.rsp" 1 mt.exe rc.exe "obj\third_party\syzygy\syzygy\swapimport\swapimport.swapimport.exe.intermediate.manifest" obj\third_party\syzygy\syzygy\swapimport\swapimport.swapimport.exe.generated.manifest ..\..\build\win\compatibility.manifest
LibDef: Total time = 0.000s
pe_lib.lib(pe_lib.pe_utils.obj) : error LNK2001: unresolved external symbol "unsigned __int64 const pe::kDosStubSize" (?kDosStubSize@pe@@3_KB)
pe_lib.lib(pe_lib.pe_utils.obj) : error LNK2001: unresolved external symbol "unsigned char const * const pe::kDosStub" (?kDosStub@pe@@3QBEB)
..\..\third_party\syzygy\binaries\exe\swapimport.exe : fatal error LNK1120: 2 unresolved externals
Final: Total time = 1.593s
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\_chromium\depot_tools\python276_bin\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\_chromium\depot_tools\python276_bin\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:..\..\third_party\syzygy\binaries\exe\swapimport.exe @..\..\third_party\syzygy\binaries\exe\swapimport.exe.rsp ..\..\third_party\syzygy\binaries\exe\swapimport.exe.manifest.res' returned non-zero exit status 1120
[7403/20450] CXX obj\third_party\leveldatabase\src\db\leveldatabase.version_set.obj
ninja: build stopped: interrupted by user.
Traceback (most recent call last):
  File "build.py", line 60, in <module>
    exit(main())
  File "build.py", line 45, in main
    builder.build()
  File "C:\_chromium\ungoogled-chromium\buildlib\windows.py", line 67, in build
    super(WindowsBuilder, self).build()
  File "C:\_chromium\ungoogled-chromium\buildlib\common.py", line 369, in build
    self._run_ninja(self.build_output, self.build_targets)
  File "C:\_chromium\ungoogled-chromium\buildlib\common.py", line 224, in _run_ninja
    cwd=str(self._sandbox_dir))
  File "C:\_chromium\ungoogled-chromium\buildlib\windows.py", line 46, in _run_subprocess
    return super(WindowsBuilder, self)._run_subprocess(*args, **kwargs)
  File "C:\_chromium\ungoogled-chromium\buildlib\common.py", line 135, in _run_subprocess
    return _util.subprocess_run(*args, **kwargs)
  File "C:\_chromium\ungoogled-chromium\buildlib\_util.py", line 234, in subprocess_run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python35\lib\subprocess.py", line 1064, in communicate
    self.wait()
  File "C:\Python35\lib\subprocess.py", line 1275, in wait
    timeout_millis)
KeyboardInterrupt

C:\_chromium\ungoogled-chromium>
```

**Comment by Eloston** [comment]
Huh, looks like a problem with swapimport. I know upstream has made some changes for x64, so maybe they've fixed this already? I'll need to try updating it to see.

**Comment by DeadSix27** [comment]
Well there are a lot of 64bit changes in the latest commits (at the google git)

"Add the 64-bit Asan redirectors."
"Enable the IAT patcher unittests in x64."
"Add probes for x64. " 

etc.
Could possibly be a fix for this.

**Comment by Eloston** [comment]
FYI,

> I know upstream has made some changes for x64, so maybe they've fixed this already?

is equivalent to

> Well there are a lot of 64bit changes in the latest commits (at the google git)
> Could possibly be a fix for this.

Unless you're also making notes to yourself with these messages.

**Comment by DeadSix27** [comment]
Good point, wrote that after I woke up, usually I'm the one complaining when people write exactly what I already wrote in a previous post. Was about time someone does the same to me ;)

**Comment by nopjmp** [comment]
swapimport.exe is a 32bit process only. It has 32bit assembly for injecting the DOS header in the PE file. x64 builds will have to have an additional step that just compiles swapimport.exe first and then allows it to be called within the normal build process.

Unless you have another idea on how to get this to work.

**Comment by Eloston** [comment]
@nopjmp Oh huh, didn't know that. Maybe we can force swapimport to be built as a 32-bit binary despite the `target_cpu` GN flag?

Alternatively, we could just not reorder imports; I remember reading somewhere that whether any performance is gained on modern Windows versions is questionable (I'm having troubles finding the Chromium bug report where this was said).

**Comment by nopjmp** [comment]
@Eloston I'm just getting familiar with GN. We could just disable it and do some testing. I'm currently just using Google's provided binary while I straighten out the swapimport repo since the GN build files do not work.

**Comment by Eloston** [comment]
@nopjmp Yeah I didn't expect it to work. I did a hasty port without quite knowing what I was doing for certain parts.

You're a big help by doing this. Thanks.

**Comment by nopjmp** [comment]
The browser works fine without swapimport. If you are okay, we can remove it as a requirement. I don't see any purpose for this except for prevent dependency hell and other things. I'll try a 64bit build tomorrow after work.

**Comment by Eloston** [comment]
@nopjmp and I have decided to disable import reordering completely, since it would take some effort to port to GN and we're not really sure how much performance would be gained in modern Windows.

Closing as wontfix since there's no swapimport anymore.
