### ISSUE TITLE
Password Manager will not save new password since Chromium 80

### ISSUE THREAD

**Issue by raisehero** [Eloston/ungoogled-chromium#1182]
**Describe the bug**
Password manager will not save new detected password in login fields, auto filling of loaded password will still work.

**To Reproduce**
1. Go to any website login
2. Fill in any in/valid credentials
3. Try save password to password manager
4. Open password manager for current site
5. "No password saved for this site"

**Expected behavior**
Password manager should save new passwords.

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 Enterprise Version 2004 OS Build 10.0.19041.450
 - ungoogled-chromium version: 84.0.4147.135-1 built by tangalbert919

**Additional context**
**Flags**
--flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad --disable-machine-id --disable-encryption --extension-mime-request-handling=always-prompt-for-install --fingerprinting-canvas-image-data-noise --fingerprinting-canvas-measuretext-noise --fingerprinting-client-rects-noise --max-connections-per-host=15 --profile-directory=Default --enable-logging --v=1 --disable-extensions --flag-switches-end

[chrome_debug.log](https://github.com/Eloston/ungoogled-chromium/files/5212244/chrome_debug.log)

**Comment by Eloston** [comment]
What platform are you running on?

**Comment by raisehero** [comment]
For some reason I forget to attach the platform information.
 - OS/Platform and version: Windows 10 Enterprise Version 2004 OS Build 10.0.19041.450
 - ungoogled-chromium version: 84.0.4147.135-1 built by tangalbert919

**Comment by B-eT-a** [comment]
I thought ill add something too..

I have the same Problem also.. The browser doesnt even ask me if i want to save the PW...
Im using windows 10 LTSC 1809  Up to Date..

Flags of Chromium:
ChromiumCommandLine=--flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad --flag-switches-end --enable-features=WebUIDarkMode --force-dark-mode --disable-windows10-custom-titlebar 

Chromium Version:
Chromium v85.0.4183.121-r782793 - ungoogled
https://github.com/macchrome/winchrome/releases/

same with this version...
85.0.4183.102-1 
https://github.com/Eloston/ungoogled-chromium/releases


Best Regards..

**Comment by Eloston** [comment]
@raisehero That's strange. I've had problems saving passwords on Linux via GNOME Keyring, but I've never had any problems saving credentials on Windows (I'm also running Windows 10 Enterprise 2004). Unfortunately, I currently lack knowledge of Chromium's password manager to debug this issue.

@B-eT-a Are you sure you enabled "Offer to save passwords" in `chrome://settings/passwords`?

**Comment by raisehero** [comment]
The regression, and #1183 all begin after Ungoogled Chromium 80. 79 doesn't have both issues.

**Comment by B-eT-a** [comment]
@Eloston 

aye, im 100% shure that the option "Offer to save Passwords" is enabled.. 
I also double checked :)

Best Regards

**Comment by raisehero** [comment]
I've tried transplanting the "Default" profile folder (--profile-directory) to a new installation and this bug and #1183 will cease to exist.
Comparing files from both user data folder (--user-data-dir) and deleting folder and files from the old user data folder leads to the root cause of the problem.

This "Local State" [Local State.zip](https://github.com/Eloston/ungoogled-chromium/files/5420686/Local.State.zip) file inside the user data dir will cause both bugs (#1182 and #1183) to manifest. This file was created from before Chromium 80.

Compare to this "Local State" file which is created on Chromium 86.
[Local State.zip](https://github.com/Eloston/ungoogled-chromium/files/5420690/Local.State.zip)

Unfortunately this leaves the newly saved password encrypted despite --disable-machine-id --disable-encryption is passed…

**Comment by raisehero** [comment]
Closing, issue stems from a common root cause which is related to platform specific issue: ungoogled-software/ungoogled-chromium-windows#58
