### ISSUE TITLE
Websites with remember login function will always forget login session since Chromium 80 (Not related to cookies clearing every shutdown)

### ISSUE THREAD

**Issue by raisehero** [Eloston/ungoogled-chromium#1183]
**Describe the bug**
Since Chromium 80, websites with remember login function will always forget login session
Reverting to Chromium 79 will allow websites to actually remember login sessions
Sites affected: a lot, including github.com, facebook.com, twitter.com, searx preferences, duckduckgo.com preferences, whatever websites that saves login session 99% will forget it after Chromium relaunch

Clear cookies and site data when you quit Chromium is **DISABLED**

**To Reproduce**
1. Login to website
2. Close Chromium
3. Open website

**Expected behavior**
Website will remember login session.

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 Enterprise Version 2004 OS Build 10.0.19041.450
 - ungoogled-chromium version: 84.0.4147.135-1 built by tangalbert919

**Additional context**
**Flags**
--flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad --disable-machine-id --disable-encryption --extension-mime-request-handling=always-prompt-for-install --fingerprinting-canvas-image-data-noise --fingerprinting-canvas-measuretext-noise --fingerprinting-client-rects-noise --max-connections-per-host=15 --profile-directory=Default --enable-logging --v=1 --disable-extensions --flag-switches-end

Log from before chromium relaunch (login into website)
[chrome_debug-before.log](https://github.com/Eloston/ungoogled-chromium/files/5212246/chrome_debug-before.log)

Log after chromium relaunch (open website and see login session being forgotten)
[chrome_debug-after.log](https://github.com/Eloston/ungoogled-chromium/files/5212247/chrome_debug-after.log)

**Comment by toluschr** [comment]
I experience the same issue. However, it doesn't occur regularely. Just about every fifth shutdown.

**Comment by raisehero** [comment]
I've tried transplanting the "Default" profile folder (--profile-directory) to a new installation and this bug and #1183 will cease to exist.
Comparing files from both user data folder (--user-data-dir) and deleting folder and files from the old user data folder leads to the root cause of the problem.

This "Local State" [Local State.zip](https://github.com/Eloston/ungoogled-chromium/files/5420686/Local.State.zip) file inside the user data dir will cause both bugs (#1182 and #1183) to manifest. This file was created from before Chromium 80.

Compare to this "Local State" file which is created on Chromium 86.
[Local State.zip](https://github.com/Eloston/ungoogled-chromium/files/5420690/Local.State.zip)

Unfortunately this leaves newly saved cookies encrypted despite --disable-machine-id --disable-encryption is passed…

**Comment by raisehero** [comment]
Closing, issue stems from a common root cause which is related to platform specific issue: ungoogled-software/ungoogled-chromium-windows#58
