### ISSUE TITLE
Perform domain substitution before patching

### ISSUE THREAD

**Issue by Luka-Filipovic** [Eloston/ungoogled-chromium#1185]
**Is your feature request related to a problem? Please describe.**
Patches can't be reverted without reverting domain substitution process, which would reset the whole incremental build.

**Describe the solution you'd like**
Simply apply domain substitution before patches.
All patches should be updated to work on source that is already domain substituted. This could easily be automated.

**Comment by Eloston** [comment]
Why is this necessary when the domain substitution utility can revert the changes?

**Comment by Luka-Filipovic** [comment]
Correct me if I'm wrong, but here's one example to show my point.
Do a full build with all patches and domain sub after patches, and afterward decide to do a new build without some `a.patch`. That would require reverting domain sub, reverting `a.patch`, applying domain sub and starting a new build. 
By redoing domain sub, timestamps of all files in domain sub list are changed. Ninja incremental build checks only timestamps and even if files remain the same, they are complied once again, and basically that is like doing a full build instead of only a few actions affected by removal of `a.patch`.

**Comment by Eloston** [comment]
How is this issue different from #849? Does 1a0e163a1130c7b47b8a98fc387628b077320a49 address your issue?

**Comment by Luka-Filipovic** [comment]
I wasn't aware `domain_substitution.py` was modified to keep a track on timestamps, that definitely solves the problem listed. 
Nevertheless, it would be simpler to only revert patches without having to redo domain sub each time
Another advantage would be ability to fix some necessary links domsub brakes with patches. 
But it's really not something of a high priority right now.

**Comment by Eloston** [comment]
Right now, domain substitution is a pretty crude and inefficient tool. There are proposals like #1026 that are steps in the right direction, but there still needs to be more work on this tool.

Closing as duplicate since the timestamp manipulation logic solves this issue.
