### ISSUE TITLE
Pressing inspect in chrome://inspect/#devices opens an empty window

### ISSUE THREAD

**Issue by damascene** [Eloston/ungoogled-chromium#1187]
Pressing inspect in chrome://inspect/#devices opens an empty window, chrome://inspect is used for debugging. example [debugging NewPipe  ](https://github.com/TeamNewPipe/NewPipe/issues/4278#issuecomment-692256053),however it opens an empty page when I press the inspect button.

**To Reproduce**

1. Attach android phone to computer
2. Get and open an [app](https://github.com/TeamNewPipe/NewPipe/files/5204058/app-debug.zip) that supports debugging
3. Go to chrome://inspect 
4. Click on 'inspect'
5. You see empty window

**Expected behavior**
There should be a window with multiple tabs for debugging like "Network","Elements" etc..

**Screenshots**
![image](https://user-images.githubusercontent.com/411046/93302603-ef803000-f802-11ea-8f22-0d516ca40203.png)

**Environment (please complete the following information):**
Version 84.0.4147.135 (Developer Build) built on Ubuntu bionic/18.04, running on Ubuntu bionic/18.04 (64-bit) 
from the OBS

**Comment by PF4Public** [comment]
Could it be related to #1018?

**Comment by damascene** [comment]
I'm not sure. I've tested it on normal Chromium and it works.

**Comment by PF4Public** [comment]
I've tested it on my system and it is still working:
![image](https://user-images.githubusercontent.com/10319700/93353416-946f2d00-f844-11ea-8a75-9b98ef2a0698.png)

**Comment by damascene** [comment]
Any way to debug this further on my end?

**Comment by Eloston** [comment]
@damascene I'm not familiar with the underlying mechansism for Android app debugging in Chrome. Is it debugging a WebView? Do you have a link for more info?

@PF4Public In that screenshot, are you debugging a Chrome instance or the NewPipe app?

**Comment by PF4Public** [comment]
My bad, I somehow missed the fact that it was an application being debugged, not Chromium.

But that also functions well on my system with ungoogled-chromium 85:
![image](https://user-images.githubusercontent.com/10319700/93687090-af9ba000-fac3-11ea-8899-0a663065150b.png)

**Comment by Eloston** [comment]
Hmm, what are your Android and WebView versions @PF4Public and @damascene?

Also @wchen342 and @csagan5, would you guys have anything to add here?

**Comment by csagan5** [comment]
> 5\. You see empty window

Try debugging the DevTools window with...the DevTools (yes, it's possible, see https://stackoverflow.com/a/38366206).

**Comment by wchen342** [comment]
I tend to think the problem is not on the phone end. However I'm going to ask something obvious, that did you enabled usb debugging on your phone?

**Comment by PF4Public** [comment]
> I tend to think the problem is not on the phone end.

I also suspect that probably OBS release is lacking some of DevTools files. Could this be the case? Could we call @braewoods also? :)

**Comment by wchen342** [comment]
This is still happening on v91, Fedora+Android, both are ungoogled-chromium. There used to be a `inspect legacy` beside `inspect` which I used to circumvent this problem but now that link is gone.

**Comment by PF4Public** [comment]
> If you type in `devtools://devtools` manually in url bar then you will get the same blank screen with some random letters

404 for me:
![image](https://user-images.githubusercontent.com/10319700/125317749-e936e380-e341-11eb-8680-ba0c6499783b.png)

**Comment by PF4Public** [comment]
Devtools obviously need to download files which correspond to target version from `https://chrome-devtools-frontend.appspot.com/serve_rev/%s/%s.html` if versions differ significantly, which is blocked in ungoogled-chromium. 

After skipping domain substitution in `content/browser/devtools/devtools_http_handler.cc` and `chrome/browser/devtools/url_constants.cc` I can now debug applications from ungoogled-chromium just fine.


Ungoogled-chromium Android 88 is being debugged by ungoogled-chromium Linux 109:
![Unbenannt](https://user-images.githubusercontent.com/10319700/215343556-ec10d269-fede-482e-b37a-c1b15198185b.png)

Also I got localised UI :) (That's why I started digging at the first place)
![image](https://user-images.githubusercontent.com/10319700/215343688-3d48a1a3-d56e-46e9-b342-56d684d83d43.png)
