### ISSUE TITLE
Flash always disabled on Linux Mint 20

### ISSUE THREAD

**Issue by albialbi** [Eloston/ungoogled-chromium#1188]
Flash is always disabled

chrome://version/
Chromium | 84.0.4147.135 (Developer Build) built on Ubuntu focal/20.04, running on Linuxmint ulyana/20 (64-bit)
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS | Linux
JavaScript | V8 8.4.371.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Command Line | /usr/lib/chromium/chromium --show-component-extension-options --enable-gpu-rasterization --no-default-browser-check --media-router=0 --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=MeasureMemory --file-url-path-alias=/gen=/usr/lib/chromium/gen
Executable Path | /usr/lib/chromium/chromium
Profile Path | /home/me/.config/chromium/Default

Flash running on other browsers like firefox with no problem

**Comment by PF4Public** [comment]
Why do you need to run Flash? It is [deprecated](https://en.wikipedia.org/wiki/Adobe_Flash#End_of_life):

> Starting from Chrome 76 and Firefox 69, Flash is disabled by default and browsers do not even show a prompt to activate Flash content. Users who want to play Flash content need to manually set a browser to prompt for Flash content, and then during each browser session enable Flash plugin for every site individually. Furthermore, browsers show warnings about the removal of Flash entirely after December 2020. Microsoft Edge based on Chromium will follow the same plan as Google Chrome.[47]
> 
> Google Chrome will block Flash plugin as "out of date" in January 2021 and eventually remove it from the source code.[48] Also in December 2020 Flash support will be completely removed from Firefox.[49] Apple will drop Flash Player support from Safari 14 alongside the release of macOS Big Sur.[50] In a move to further reduce the number of Flash Player installations, Adobe announced plans to add a "time bomb" to Flash to prevent existing installations past End-of-Life date, to prompt users to uninstall Flash, and to remove all existing download links for Flash installers.

**Comment by albialbi** [comment]
There are still lots of games for flash.

**Comment by braewoods** [comment]
Even so with Chromium phasing it out I'm not sure what you expect us to do about it. I don't think anyone here cares enough about Flash to continue trying to support it.

**Comment by albialbi** [comment]
First question is, should it work or not?
In last "normal" chromium I used, it worked.

**Comment by jdjss** [comment]
> Flash is always disabled
> 
> chrome://version/
> Chromium | 84.0.4147.135 (Developer Build) built on Ubuntu focal/20.04, running on Linuxmint ulyana/20 (64-bit)
> Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
> OS | Linux
> JavaScript | V8 8.4.371.23
> Flash | (Disabled)
> User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
> Command Line | /usr/lib/chromium/chromium --show-component-extension-options --enable-gpu-rasterization --no-default-browser-check --media-router=0 --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=MeasureMemory --file-url-path-alias=/gen=/usr/lib/chromium/gen
> Executable Path | /usr/lib/chromium/chromium
> Profile Path | /home/me/.config/chromium/Default
> 
> Flash running on other browsers like firefox with no problem

sudo apt-get install pepperflashplugin-nonfree
sudo su
sudo sed -i -e '/Exec=\/usr\/bin\/chromium/s/$/ --ppapi-flash-path=\/usr\/lib\/pepperflashplugin-nonfree\/libpepflashplayer.so --ppapi-flash-version=32.0.0.433 /' /usr/share/applications/chromium.desktop

Launch chromium enable flash chrome://settings/content/flash

Test flash https://helpx.adobe.com/flash-player.html

**Comment by albialbi** [comment]
> sudo sed -i -e '/Exec=/usr/bin/chromium/s/$/ --ppapi-flash-path=/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so --ppapi-flash-version=32.0.0.433 /' /usr/share/applications/chromium.desktop

That works. Thanks very much!
