### ISSUE TITLE
SSL issues NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED

### ISSUE THREAD

**Issue by ipetepete** [Eloston/ungoogled-chromium#119]
Related to this: https://sslmate.com/blog/post/ct_redaction_in_chrome_53

Some sites just don't work, Amazon, is a prime example (pun intended :), several resources do not load due to the SSL cert...see attached 
![screen shot 2016-11-15 at 10 38 05 am](https://cloud.githubusercontent.com/assets/1248996/20316585/b048c5ac-ab1f-11e6-9cf0-825cac336a3e.png)

**Comment by hook54321a** [comment]
I'm having the same issue. When I try to go to https://www.greatagain.gov/ it comes up with the "Your connection is not private" page.

**Comment by Eloston** [comment]
A lot of websites are having this now. In #116, I mentioned that I will upgrade to 54 to fix this problem, so hang tight.

**Comment by ipetepete** [comment]
@hook54321a LOL, oh the irony

**Comment by biergaizi** [comment]
@ipetepete @hook54321a 

https://www.nsa.gov is affected by the same issue.

**Comment by VittGam** [comment]
You can workaround this by disabling the same FieldTrial flag that was disabled on-the-fly by Google on Google Chrome 53 using their Finch <s>remote hijacking</s> ehm, _Field Trial Testing_ server:

`--force-fieldtrials=*EnforceCTForProblematicRoots/Disabled/`

Enjoy! :)

**Comment by Eloston** [comment]
@VittGam Thanks for the tip! Do you have some documentation on field trials? I don't know about it.

**Comment by VittGam** [comment]
@Eloston No, unfortunately they're scattered all around the code, and there is no place where they're defined... It's just a key-value store that's checked when needed.

This particular one is checked here: https://chromium.googlesource.com/chromium/src/+/53.0.2785.116/net/http/transport_security_state.cc#753

While the `--force-fieldtrials` option is described here:

https://chromium.googlesource.com/chromium/src/+/53.0.2785.116/base/base_switches.cc#36

**Comment by Eloston** [comment]
@VittGam Alright, thanks.

**Comment by think3t** [comment]
@VittGam Thanks for the tip! It works!

**Comment by Eloston** [comment]
Going to close this since the new release is out. Builds for the platforms will roll out over time as they are built and bugs are worked out.

**Comment by xaviervalarino** [comment]
@VittGam Sorry to resurrect this year old topic, but how would I go about enabling `--force-fieldtrials` option from the command-line in OSX?

Running `chromium --force-fieldtrials=*EnforceCTForProblematicRoots/Disabled/` from term returns `unrecognized option` and then the usage text.
