### ISSUE TITLE
Unable to make threads on 4chan

### ISSUE THREAD

**Issue by christianitus03** [Eloston/ungoogled-chromium#1190]
**Describe the bug**
When I try to post a new thread on 4chan, I am redirected to a random thread and my thread isn't posted

**To Reproduce**
1. Go to 4chan.org
2. Try ake a new thread and post it

**Expected behavior**
A new thread is posted, and you are redirected to your thread.

**Environment (please complete the following information):**
 - OS/Platform and version: openSUSE Tumbleweed
 - ungoogled-chromium version: 83.0.4103.97_1.1 Portable Linux

**Additional context**
This happens across different operating systems, but never happened on other browsers. So I am not shadowbanned.

**Comment by Eloston** [comment]
Try checking `chrome://settings` and matching them to regular Chromium. You can also try reverting flags in `chrome://flags` to their defaults.

**Comment by christianitus** [comment]
> Try checking `chrome://settings` and matching them to regular Chromium. You can also try reverting flags in `chrome://flags` to their defaults.

Updated to portable version 85.0.4183.102-1.1, it works now with no changes.
