### ISSUE TITLE
Update Portable Linux to Latest Version

### ISSUE THREAD

**Issue by christianitus03** [Eloston/ungoogled-chromium#1191]
**Is your feature request related to a problem? Please describe.**
Portable Linux is still on 83.0.4102.97-1.1. This is almost three months old.

**Describe the solution you'd like**
Please update Portable Linux to the latest stable version.

**Comment by Eloston** [comment]
Marking as duplicate of https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/69
