### ISSUE TITLE
Remove safety check

### ISSUE THREAD

**Issue by wchen342** [Eloston/ungoogled-chromium#1196]
I just noticed there is a "safety check" in settings which I think should be disabled and removed. Not sure whether it is Arch only or Linux only though. See the screenshot:

![1](https://user-images.githubusercontent.com/6406743/94205487-ed793980-feb2-11ea-8a27-67b2b4c5180f.png)

**Comment by Ahrotahn** [comment]
Which version are you running?  [This patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/remove-uneeded-ui.patch#L118) should be removing that on 85+.  
Is it on the main settings page, or in a sub-section?

**Comment by wchen342** [comment]
It's `85.0.4183.83`. Wasn't the patch got reversed in the first version? Maybe that's why. Let me check the Arch repo.

**Comment by wchen342** [comment]
Yeah the Arch version of `.83` uses `.83-1` of the main repo which doesn't have that patch. I need to get a new version obviously. Closing.
