### ISSUE TITLE
Help with building flatpak

### ISSUE THREAD

**Issue by analotia** [Eloston/ungoogled-chromium#1197]
Hi, I'm trying to build a flatpak but currently facing troubles with : https://github.com/flathub/flathub/pull/1857

If you have any idea how to fix that I'd really appreciate it. BTW the build environment couldn't have any internet so all files must be downloaded before building. Here is my progress: https://github.com/flathub/flathub/pull/1857

**Comment by analotia** [comment]
I followed the build instructions in the wiki with some minor differences due to the constraints of the build environment

**Comment by Eloston** [comment]
Is there a reason why you're authoring your own build process instead of using ungoogled-chromium-portablelinux?

**Comment by analotia** [comment]
I thought that I would be a able to target more architectures that way

**Comment by analotia** [comment]
> Is there a reason why you're authoring your own build process instead of using ungoogled-chromium-portablelinux?

What do you mean by that?

**Comment by analotia** [comment]
Anyway I successfully built a package for `amd64` but I need help with `arm64` . On `arm64` `SOLINK` fails causing the whole build to fail and I don't know how to fix it.

**Comment by analotia** [comment]
All building problems resolved.
