### ISSUE TITLE
Google search in omnibox

### ISSUE THREAD

**Issue by iamso** [Eloston/ungoogled-chromium#120]
I understand that the purpose of this chromium version is to remove any ties to Google services, but at least make Google search in omnibox work.
When I choose Google as search engine for the omnibox and try to search something, it doesn't do anything.
So either remove the option from the settings or make it work. After all it's just passing arguments to a url.

Thanks

**Comment by Eloston** [comment]
Alright, I'll remove the option then.

**Comment by Eloston** [comment]
Implemented in b210c28d2eb8061267df97c9a3955dc1616fe1be
