### ISSUE TITLE
Option to override extension manifest and APIs

### ISSUE THREAD

**Issue by SoniEx2** [Eloston/ungoogled-chromium#1201]
**Is your feature request related to a problem? Please describe.**

Extensions may request too many permissions among other things.

**Describe the solution you'd like**

Some way to override extension manifest, and provide appropriately neutered APIs where relevant.

**Describe alternatives you've considered**

An alternative would probably be to make a "virtual machine" or "container" webextension, which can have webextensions installed into it. That sounds slow tho.

**Additional context**

**Comment by Eloston** [comment]
Why not just unpack the extension and modify the manifest manually?

**Comment by SoniEx2** [comment]
that doesn't work for dealing with the APIs. might aswell have asked "why not just write your own clone of arbitrarily many proprietary extensions".

it would also make them fail instead of being neutered.
