### ISSUE TITLE
School website breaking possibly due to removal of Google integration / services

### ISSUE THREAD

**Issue by HasanQZ** [Eloston/ungoogled-chromium#1202]
I have a website i need to be able to access for school (grades, assignments, etc.). Whenever i try to check the details of a class, the website gets stuck loading. I open up the console and see this:
![Screenshot from 2020-10-04 23-24-57](https://user-images.githubusercontent.com/59009269/95040308-e31c2400-0698-11eb-8498-142ae543adda.png)

I can not find a support contact for the website anywhere, and this problem persists between every build, and between Windows 10 and Arch Linux. This does not happen in any other browser. 

What are my options here? Should i just have a seperate browser for this specific website? If so, what are some simple, lightweight, cross-platform browsers i could use?

I would really like to use ungoogled-chromium as my main browser, but this is the only thing keeping me from switching for everything.

I apologize for my lack of information provided about the website, but i can not reveal very much because i do not want to reveal personal details.

Any help would be much appreciated.

**Comment by PF4Public** [comment]
You'd better inspect the Network tab of the Developer tools. Such issues might be ~a normal behaviour~ ordinary bugs of some websites. At least this might give some clues as to what is the real issue.

Ungoogled-chromium tries to be a drop-in replacement for chromium, this should not be happening.

**Comment by HasanQZ** [comment]
![Screenshot 2020-10-05 105449](https://user-images.githubusercontent.com/59009269/95102757-4d79a680-0723-11eb-92d5-d1948035397a.png)

After opening the network tab, this is what i see. I don't know what the read line means but that could be where the problem lies. After further inspection, i can't seem to find an element that fails to load.

I reluctantly installed Google Chrome, and the problem seems to be present. This issue appears to be on the other end. I'll see if my school can fix it. Thanks for your help

**Comment by PF4Public** [comment]
> might be ~a normal behaviour~ ordinary bugs

😉
