### ISSUE TITLE
[Android] Bitwarden not working on newer versions, but works for older ones.

### ISSUE THREAD

**Issue by nullsurfer** [Eloston/ungoogled-chromium#1203]
I updated to v85 from v83, but I noticed that it didn't update the app. It installed a new app. The newer version doesn't properly support Bitwarden. If I manually summon autofill, Bitwarden doesn't detect the site, but it only detects Ungoogled Chromium as a regular app, not a browser. It worked just fine on the older version.

**Comment by wchen342** [comment]
Can you file a bug report with them? They need to update the package names in [Android/Accessibility/AccessibilityHelpers.cs) and [Android/Autofill/AutofillHelpers.cs](https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/AutofillHelpers.cs).

**Comment by nullsurfer** [comment]
Just did https://github.com/bitwarden/mobile/issues/1118

**Comment by contribucious** [comment]
@nullsurfer @wchen342 [PR](https://github.com/bitwarden/mobile/pull/1119) done. :thumbsup:

**Comment by nullsurfer** [comment]
Merged: https://github.com/bitwarden/mobile/pull/1119. Thanks @contribucious!!!

**Comment by contribucious** [comment]
:v: :wink:
