### ISSUE TITLE
Update Debian/Ubuntu Binaries to 85.0.4183.121-1 

### ISSUE THREAD

**Issue by christianitus03** [Eloston/ungoogled-chromium#1204]
The version currently in OBS is from well over a month ago. Could we please get the latest version in OBS?

**Comment by awsms** [comment]
I'd like to see the binaries updated as well, but the people in charge of the repos have nothing to do with this git.

**Comment by PF4Public** [comment]
See the discussion in #1198

**Comment by Eloston** [comment]
Closing as duplicate of https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/178
