### ISSUE TITLE
Clearing cookies on every exit

### ISSUE THREAD

**Issue by blymed** [Eloston/ungoogled-chromium#1206]
I encountered a problem where ungoogled-chromium would clear out all of my data and cookies on exit, due to an option in settings.

<img width="696" alt="Screen Shot 2020-10-09 at 00 36 45" src="https://user-images.githubusercontent.com/46053275/95520638-07913c80-09c8-11eb-8d41-de4962b97e24.png">

This option is turned off by default in regular Chrome, but enabled by default in ungoogled-chromium. **Which file of ungooged-chromium source do I have to modify so that it is disabled by default?** I've been trying to figure this one out for a while.

**Comment by PF4Public** [comment]
You can disable it once and this setting will be persisted for that particular profile for the future.

**Comment by blymed** [comment]
> You can disable it once and this setting will be persisted for that particular profile for the future.

Yes, but given that I constantly have to create new profiles and switch to them, it is very uncomfortable to disable it every time. Plus if I miss it one time, all of the cookies are gone and that's very frustrating. That's why I am searching particularly for a way to disable it in the source code

**Comment by PF4Public** [comment]
You probably need to remove or revert [ungoogled-chromium/patches/extra/iridium-browser/prefs-only-keep-cookies-until-exit.patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/iridium-browser/prefs-only-keep-cookies-until-exit.patch)
If you're compiling it yourself, just removing this line should suffice:
https://github.com/Eloston/ungoogled-chromium/blob/e46b774c538cb8e1e249fe69e3e8d62c18f8c1b9/patches/series#L55

**Comment by blymed** [comment]
> You probably need to remove or revert [ungoogled-chromium/patches/extra/iridium-browser/prefs-only-keep-cookies-until-exit.patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/iridium-browser/prefs-only-keep-cookies-until-exit.patch)
> If you're compiling it yourself, just removing this line should suffice:
> 
> https://github.com/Eloston/ungoogled-chromium/blob/e46b774c538cb8e1e249fe69e3e8d62c18f8c1b9/patches/series#L55

Yep, that helped. Thanks
