### ISSUE TITLE
Ungoogled-chromium VS Chromium

### ISSUE THREAD

**Issue by TNTBOMBOM** [Eloston/ungoogled-chromium#1209]
Hi There,

I have read the documentation FAQ,Design,Philosophy but i havent found what exactly been disabled or enabled that makes ungoogled-chromium better in security/privacy than chromium just statements like disabling connection to google servers e.g safe browsing but i believe not all the changes there nor what are the impacts of these changes e.g like does it enhance privacy or security or both or none(precautionary change)..etc

I hope a comparison table can be made with the changes of what ungoogled-chromium done that chromium is worse at with the impacts of the changes. 

Take an idea of a comparison table e.g: 

https://www.whonix.org/wiki/Comparison_with_Others

Or Something like Brave can be nice as well: (but they didnt mention of what is the impact of doing it)

https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)#what-chromium-features-are-removed-for-privacysecurity-reasons

or Whonix trying to find some stuff might be not good with chromium: 

https://www.whonix.org/wiki/Dev/Chromium

At Whonix Anonymous project have new project focusing on security only not anonymity, So came to the discussion of which browser to use for security, It found to be that chromium[ has better security](https://madaidans-insecurities.github.io/firefox-chromium.html) features than Firefox. But the question lefts shall we use chromium or chromium forks like ungoogled-chromium or Brave. 

Brave has privacy issues by allowing and having tracking list by default. This leaving ungoogled-chromium on the eye.

ThX

**Comment by jstkdng** [comment]
I'd say nothing has been added that makes UC more secure than vanilla chromium, might be wrong though. Most of the changes are related to privacy and removing google integration with UC. Some interesting changes are improved fingerprinting blocking and the removal of secure browsing.

**Comment by Eloston** [comment]
Yep, @jstkdng's answer is basically correct. We don't have any rigorous security policies/practices in place. We disable things which *could* make the browser more secure, but that's a pretty weak statement.
