### ISSUE TITLE
Building script

### ISSUE THREAD

**Issue by numerys** [Eloston/ungoogled-chromium#1212]
The building scripts provided by Google/Chromium is a mess and so Ungoogled-Chromium is inheriting the problem.

A simple Makefile can solve any task, but due to some point I don't get, the wheel is getting always reinvented. A tiny change of the source invokes a complete recompilation. Why that? Unneccessary in my view.

I was trying to compile for Void-Linux but no success. Maybe some did so and can post the solution.

The building instructions are missing some points so far:
  - "flags.gn contains only a subset of what is needed to run the build.", ok, but please explain all flags and dependencies so anybody can put in the needed flags.
  - How not to compile to a specific platform (e.g. Debian Linux) but to the platform on which the build is compiled? Maybe this point is explained within the previous one (flags).

Regards

**Comment by PF4Public** [comment]
> A tiny change of the source invokes a complete recompilation.

Please, could you elaborate more on this?
Changing some bits in already unpacked source makes ninja to recompile only the changed files.
If you meant the rebuilding process with each new version, ccache helps here more-or-less.
It was earlier possible to [use jumbo](https://github.com/Eloston/ungoogled-chromium/issues/928) to speed up the compilation, but unfortunately, Google removed it some versions ago.

> please explain all flags and dependencies so anybody can put in the needed flags.

Ungoogled project has nothing to do with those, they are as they are defined in Chromium. [Chromium documentation](https://www.chromium.org/developers/gn-build-configuration) suggests a way to list them all: `gn args out/Release --list`. They are rather good documented there. [Quick googling](https://www.google.com/search?q=chromium%20all%20gn%20flags) is also helpful with [this page](https://gitlab.com/noencoding/OS-X-Chromium-with-proprietary-codecs/-/wikis/List-of-all-gn-arguments-for-Chromium-build). It is for Mac, but most of the flags are also applicable everywhere else.

> How not to compile to a specific platform (e.g. Debian Linux) but to the platform on which the build is compiled?

Could you please elaborate on what you are trying to achieve, what have you attempted and how/if was it unsuccessful?

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, feel free to do so.
