### ISSUE TITLE
Syntax error in patches.py on Python 3.5.2

### ISSUE THREAD

**Issue by Niek** [Eloston/ungoogled-chromium#1213]
The following line gives a syntax error on Python 3.5.2:
https://github.com/Eloston/ungoogled-chromium/blob/ab0e6780798dc5a742ffd26b330328a7997aebb3/utils/patches.py#L195
Removing the `f` in front fixed the issue for me.

**Comment by Niek** [comment]
Upgrading to Python 3.10 seem to have resolved the issue, closing.

**Comment by PF4Public** [comment]
[ungoogled-chromium/docs/developing.md#dependencies](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/developing.md#dependencies) mentions support of "Python 3.6 or newer"
@Eloston this information should probably be listed on topmost README.md somewhere, I guess?
