### ISSUE TITLE
Extension remove and similar functionality without user consent

### ISSUE THREAD

**Issue by PF4Public** [Eloston/ungoogled-chromium#1217]
Chrome is known not only auto-updating its extensions, but also removing without user consent. It could be actually beneficial for an average user by helping fight malicious extensions, but on the other hand provides Google with a means of censorship to put it mildly.

Does it have any other similar functionality? I do hope, that such functionality is absent in Chromium and/or is patched in ungoogled-chromium. @Eloston , please confirm.

**Comment by wchen342** [comment]
I digged though extension codes a little when trying to add it to Android version and at least in the part I have investigated there is no such functionality. But that was v84 so thing could have changed, as they are adding more strange stuff every day..

**Comment by Luka-Filipovic** [comment]
Extension autoupdate doesnt work in UC due to domain substitution and `disable-webstore-urls.patch`. I don't think chromium will auto disable any extension without contacting webstore, which can't be done

**Comment by Eloston** [comment]
I don't see how extensions can be removed automatically if the browser can't communicate with Google (unless explicitly configured to do so for specific cases, like translation). Closing.
