### ISSUE TITLE
Security Key not functioning for Google sign in

### ISSUE THREAD

**Issue by bcallaars** [Eloston/ungoogled-chromium#122]
When trying to sign in Google, the security key option returns an error. This is something that works fine in the vanilla Chrome. Any suggestions?

![screenshot_2016-11-24_14-18-27](https://cloud.githubusercontent.com/assets/493348/20601742/071e8702-b252-11e6-9f4a-37a5882a6d1f.png)

**Comment by Eloston** [comment]
Do you see any infobar show up when you attempt to use the security key? It would be along the lines of "Blocked request to ...". If you don't, then some patch is probably breaking this.

I don't know how 2-step is implemented on the browser-side, so any input here will be much appreciated.

**Comment by bcallaars** [comment]
If I'm not mistaken this is due to the unique way how Google Chrome access the security key. I'll see if I can investigate further, but it might be one of the patches breaking it. In my mind it was something to do with a request Google Chrome does in the background, but I'm not sure.

**Comment by Eloston** [comment]
Alright, sounds good. I'm actively working on 54 right now, but what you find in 53 will probably apply to 54.

**Comment by Eloston** [comment]
Also wanted to mention that it's possible that domain substitution is breaking something. Even though no requests are made, it can cause of domain name matching to fail. Take for example [this patch that fixes devtools](https://github.com/Eloston/ungoogled-chromium/blob/master/resources/common/patches/ungoogled-chromium/fix-bundled-devtools.patch).

**Comment by bcallaars** [comment]
Thanks for the tip, I'm going to see if I can find something out.

**Comment by bcallaars** [comment]
When I check out the Google JavaScript it's trying to execute, references are made to [this FIDO U2F extension](pfboblefjcgdjicmnffhdgionmgcdmne). Strangely enough when I install it, it works.

I can't find references of this in the vanilla Google Chrome, but I'm a 100% sure that this is what makes it tick. Do we need to change the instructions/wiki/documentation here somewhere to make the user aware of this?

**Comment by Eloston** [comment]
[I also found this extension](https://chrome.google.com/webstore/detail/gnubbyd-dev/dlfcjilkjfhdnfiecknlnddkmmiofjbg/) in `remoting/webapp/crd/js/gnubby_auth_handler.js`. If this works in regular Chrome, then either it's installing it automatically or it's in the source code somewhere but it's not working.

I could just add this to the documentation, but I'm kind of curious to know what's going on.

**Comment by bcallaars** [comment]
Ok as far as I can gather these are installed as plugins when needed, it seems odd, but at least legit.

**Comment by Eloston** [comment]
Alright then.
