### ISSUE TITLE
localstorage difficulties ?

### ISSUE THREAD

**Issue by Quetzaal** [Eloston/ungoogled-chromium#1223]
hi, thank a lot for the browser
i've just downloaded it yesterday, and i'm in phasis of learning, then i'm not sure that is a real "issue"

i built a personnal speed-dial in javascript located in my localhost
it work nicely on otter-browser and vivaldi
but there's non persistence of localstorage's datas with the Ungoogled Browser ??

i went here and there to find solution... then i come here to see if i've to work more, or its just because there's a chrome option that is not available, or something like this...

thank a lot again

**Comment by Ahrotahn** [comment]
Is `Settings > Cookies and other site data > Clear cookies and other site data when you quit Chromium` toggled on still?

**Comment by Quetzaal** [comment]
thanks a lot ahrothn, without you i don't think that i would went see there, i was hoping for something more specific abut LocalStorage...  but it's add with the cookies... then "allow all cookies", and after do a greylist for website that cookies must be erase in end of session.

**Comment by Eloston** [comment]
Looks like question is answered, closing.
