### ISSUE TITLE
Webdriver test fails

### ISSUE THREAD

**Issue by bundleman** [Eloston/ungoogled-chromium#1224]
Hi!
**Problem**
Ungoogled-chromium fails webdriver test on this page https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html, test definition here https://intoli.com/blog/not-possible-to-block-chrome-headless/ .

I didn't turn headless mode and did request with default flags.

My version ungoogled-chromium work by ubuntu bionic.
Test result https://imgbox.com/98DbReb0.

**Question**
May be there is a possibility turn webdriver ? Or you need to make changes to the source code ?

**Comment by wchen342** [comment]
I tested on my machine and it is fine. What version is your uc. and can you show `chrome://flags` and your installed extensions?

**Comment by bundleman** [comment]
> I tested on my machine and it is fine. What version is your uc. and can you show `chrome://flags` and your installed extensions?

1. You can see my uc version on this screenshot https://imgbox.com/98DbReb0.
I installed it from ubuntu repo.
2. I don't have extensions and my flags set up by default

**Comment by wchen342** [comment]
Probably because of the old version? Mine is v85.
Ubuntu/Debian version also has [some unique patches](https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/debian_sid/debian/patches/series). @braewoods should know this better.

**Comment by Eloston** [comment]
You might have better luck with the unportable variant

**Comment by bundleman** [comment]
Thanks to all!
