### ISSUE TITLE
Fingerprint Protection

### ISSUE THREAD

**Issue by specter78** [Eloston/ungoogled-chromium#1226]
**Describe the bug**
While running test on https://panopticlick.eff.org/, UC shows unique fingerprint.
Running the same test on Brave, It shows "your browser has a randomized fingerprint".

**To Reproduce**
https://panopticlick.eff.org/

**Expected behavior**
Partial to full fingerprint protection

**Environment (please complete the following information):**
 - OS/Platform and version: macOS 
 - ungoogled-chromium version: 86.0.4240.80

**Additional context**
NA

**Comment by indometacin** [comment]
Brave has a number of [defenses ](https://brave.com/privacy-updates-3)[against ](https://brave.com/privacy-updates-4/)[fingerprinting](https://support.brave.com/hc/en-us/articles/360022806212-How-do-I-use-Shields-while-browsing-) that I believe are unique additions to the Chromium base they build upon. That said, when testing (using UC 86.0.4240.183/Windows 10) against Panopticlick, I showed up unique as well. Showed up unique testing it against [https://www.amiunique.org](https://www.amiunique.org/) as well. (I'll add that I've heard of [criticisms](https://www.michaelhorowitz.com/browser.fingerprinting.php) of some of these testing sites, but I think they give you something of an idea of how much data is leaked, and is better than nothing.)

Should UC have fingerprinting defenses like Brave? Or is that out of scope for this project? If it's out of scope, perhaps we should experiment testing what extensions would suffice for countering fingerprinting (uMatrix? Other extensions? If any number of extensions would even really help?) to suggest for users? If it is within scope, what mechanism should be used for a fingerprinting defense? I'm aware of Chromium doing more [work ](https://www.chromium.org/Home/chromium-privacy/privacy-sandbox) in this [space](https://blog.chromium.org/2020/10/progress-on-privacy-sandbox-and.html)), but also see Brave [doesn't like the idea of a privacy sandbox much](https://brave.com/brave-fingerprinting-and-privacy-budgets/). Regardless of direction, I'd be happy to help if able.

**Comment by victor03303** [comment]
I would love if fingerprinting protection is implemented

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
> **Describe the bug**
> While running test on https://panopticlick.eff.org/, UC shows unique fingerprint.
> Running the same test on Brave, It shows "your browser has a randomized fingerprint".


Ofcourse brave paid them. But I really hope to see some anti fingerprint feature in ungoogled chromium

**Comment by DavidCreegan** [comment]
Yep same here. I love the browser though so I hope it gets proper fingerprint randomization. Even with all 3 flags enabled relating to that, it still says I have a unique fingerprint.

**Comment by ShawnNogi** [comment]
Yeah it seems it should be a priority for development. Maybe even more important than floc...

**Comment by TontyTon** [comment]
I think being unique on panopticlick is a good thing.
As even if 'you'(same browser) go to panopticlick twice, then each time your fingerprint is different, so your two sessions can't be linked by your browser fingerprint.

**Comment by ShawnNogi** [comment]
> I think being unique on panopticlick is a good thing.
> As even if 'you'(same browser) go to panopticlick twice, then each time your fingerprint is different, so your two sessions can't be linked by your browser fingerprint.

when i visit browser leaks as it always has the same uniqueness 
"https://browserleaks.com/canvas".

"99.74% (2090 of 793798 user agents have the same signature)"

On the other hand the brave browser always says 
"0 of 793798 user agents have the same signature"

I dont know of any evidence of brave "paying this site" as said above. from another user.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.

**Comment by eejeet** [comment]
Please Add a feature for anti-fingerprint at least for device memory and Video Driver Info, I am node js dev can anyone help me with where can set dynamically change the navigator in device memory and other

**Comment by iamkhalidbashir** [comment]
it's really neeeded
