### ISSUE TITLE
Ungoogled chromium just closes/crashes a few seconds after opening?

### ISSUE THREAD

**Issue by dominikheinz** [Eloston/ungoogled-chromium#1231]
**Describe the bug**
Ungoogled chromium just closes/crashes after a few seconds when it has been opened. No error message or anything is shown.

**To Reproduce**
Just download the latest version for windows 64bit (85.0.4183.121-1) and open it.
After like 3 to 5 seconds it just closes

**Expected behavior**
The browser should stay open and function normally

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 64-Bit
 - ungoogled-chromium version: 85.0.4183.121-1

**Additional context**
I had an old version of normal chromium installed before. I uninstalled it and installed ungoogled-chromium. 
The problem was there right after the installation. Rebooting the system and clearing cache/temp files didnt have any effect.

**Comment by wchen342** [comment]
Remove the previous profile completely?
