### ISSUE TITLE
video tutorial

### ISSUE THREAD

**Issue by lipici** [Eloston/ungoogled-chromium#1232]
Can someome make a video tutorial for building instructions for windows version ? Im tired of waiting everytime for someone or to check everyday the site to see if another version its on.

PS: https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md its too advanced for me

**Comment by Luka-Filipovic** [comment]
You should follow this [instractions](https://github.com/ungoogled-software/ungoogled-chromium-windows/blob/master/README.md#building). You just need two pythons, visual studio with necessary components and 7zip. 
Have in mind that build process needs good CPU and a lot of RAM, and it can be as long as 6 hours.
If you find it way to complicated my friendly advice is to give up on this and wait for releases.
If you get stuck on some of the steps listed, feel free to ask for help.

**Comment by AplhaSlayer1964** [comment]
Would you be able to help out? I am confused on what I am supposed to replace TAG_OR_BRANCH_HERE with for this command: "git checkout --recurse-submodules TAG_OR_BRANCH_HERE" I'm looking to compile the latest release so 89.0.4389.114-1.1 as of now. Thanks.

**Comment by AplhaSlayer1964** [comment]
Also is it possible to build ungoogle chromium from the main release or for windows can you only use the windows release versions? I know it's a dumb question but just wan to make sure.

**Comment by PF4Public** [comment]
Closing this issue in favour of #1589
