### ISSUE TITLE
Login to MS Teams crashes browser

### ISSUE THREAD

**Issue by AngryLasagna** [Eloston/ungoogled-chromium#1235]
**Describe the bug**
As soon as I login to MS Teams (Edu account), ungoogled-chromium crashes completely.

**To Reproduce**
Open browser, login to ms teams.

**Expected behavior**
Webapplication working. Browser not crashing.

**Environment (please complete the following information):**
 - Fedora 32 + rpmfusion, updates from 9.Nov.2020; Gnome Desktop with Wayland.
 - ungoogled-chromium version: Chromium 85.0.4183.102 from rpmfusion

**Additional context**
Worked previously. Stopped working about 2 days ago after an update.
    Upgrade      chromium-common-86.0.4240.111-1.fc32.x86_64 @updates
    Upgraded     chromium-common-85.0.4183.121-1.fc32.x86_64 @@System

**Comment by AngryLasagna** [comment]
I see, its the common package not matching. rpmfusion seems to be late.

**Comment by wchen342** [comment]
Which package are you using? On f33 I only have one package (CBP) and have no need for `chromium-common`.

**Comment by AngryLasagna** [comment]
Weird. Its autoinstalled on Fedora 32. I wonder if upgrading fixes. But still I have looked into the buildsystem of rpmfusion and saw that the maintainer doesnt update it anymore.
How much work is this to maintain?

**Comment by wchen342** [comment]
> Also yeah, I could just remove chromium-common without any dependency blocking...

That probably comes from previously installed normal chromium.

I don't think you can submit to other person's package in RPMFusion without permission. The author sometimes lags behind a month or so in updating but I think you can build an rpm file yourself with the right spec file.

**Comment by Eloston** [comment]
Since this is a packaging issue in a repo not owned by us, closing as invalid.
