### ISSUE TITLE
Extension settings can not be stored or updated?

### ISSUE THREAD

**Issue by se4u** [Eloston/ungoogled-chromium#124]
First of all, thank you for the ungoogled-chromium project. You are doing great work.

I use the [Redirector](https://chrome.google.com/webstore/detail/redirector/pajiegeliagebegjdhebejdlknciafen) chrome extension to automatically forward links to paid sites to my university's library proxy. This extensions saves me a few clicks and typing and my regex _(stored in original chrome)_ looks like this: 

![image](https://cloud.githubusercontent.com/assets/2301364/20610515/ed4f21e4-b268-11e6-936f-45de95bac8d2.png)

However, I am unable to save any regex in the Redirector extension's options page in the ungoogled-chromium app. I was wondering if you had any ideas/intuition about why this might be happening?

**Comment by Eloston** [comment]
I haven't worked with extensions in a while, but it could be possible that it's trying to save settings to the signed-in Google account instead of saving them locally in the browser profile. Does the developer tools page for the background page or options page say anything useful?

**Comment by se4u** [comment]
Thanks for the suggestion of looking into developer tools. It turns out that the problem was not a problem with `ungoogled-chromium` but rather the `content_security_policy` in the `manifest.json`. Somehow the following syntax for specifying the CSP is invalid (or incorrect)

    "content_security_policy": "script-src 'self' https://*.googleapis.com https://*.bootstrapcdn.com; object-src 'self'"

and because of this  `jquery` was not being loaded from `googleapis`. I was able to fix the error by just downloading `jquery` to the extension folder and loading the unpacked extension.

**Comment by Eloston** [comment]
Ah ok. Glad to hear a solution was found.
