### ISSUE TITLE
Clicking the search bar at www.carousell.sg makes the entire website blank.

### ISSUE THREAD

**Issue by raisehero** [Eloston/ungoogled-chromium#1241]
**Describe the bug**
Clicking the search bar at www.carousell.sg makes the entire website blank.

**To Reproduce**
1. open www.carousell.sg
2. Click on the search bar
3. See error

**Expected behavior**
An attached screenshot of proper behaviour in Google Chrome 86.0.4240.183:
![20201112T011510Z_2117x647_Snap_to_Sell,_Chat_to_Buy_for_FREE_on_the_Carousel_chrome_84HaWPA0l7](https://user-images.githubusercontent.com/71166028/98882670-ba712080-24c7-11eb-95c3-ad671ed3174b.png)
Portapps' Brave 1.16.68-66 did not exhibit this issue either

**Screenshots**
Search bar:
![20201112T011335Z_2089x255_Snap_to_Sell,_Chat_to_Buy_for_FREE_on_the_Carousel_chrome_jGi2xo1LDS](https://user-images.githubusercontent.com/71166028/98882723-d1177780-24c7-11eb-992a-0d3408e52f1f.png)
Blank problem:
![20201112T011731Z_2756x1920_Snap_to_Sell,_Chat_to_Buy_for_FREE_on_the_Carousel_chrome_trl18QPybV](https://user-images.githubusercontent.com/71166028/98882776-f4dabd80-24c7-11eb-99ea-4cfd5f877a8a.png)

**Environment (please complete the following information):**
- OS/Platform and version: Windows 10 Enterprise Version 2004 OS Build 10.0.19041.450
- ungoogled-chromium version: Ungoogled Chromium Windows 86.0.4240.183-1 built by tangalbert919

**Additional context**
None.

**Comment by jstkdng** [comment]
Works on my machine. Could it be just a temporary problem? as that error is a react one
![image](https://user-images.githubusercontent.com/52050345/98973928-5740b780-24e2-11eb-90cb-b39ca86e418c.png)

**Comment by wchen342** [comment]
Either Windows specific or more likely a network problem. Try test using a proxy and see whether this still happens.

**Comment by raisehero** [comment]
--fingerprinting-client-rects-noise causes this issue. removing it from command line switches fixes the issue.
