### ISSUE TITLE
icloud login page not loading

### ISSUE THREAD

**Issue by ekanshsinghal** [Eloston/ungoogled-chromium#1244]
**Describe the bug**
icloud.com login page load with an error - idmsa.apple.com refused to connect.

**To Reproduce**
1. Go to 'https://www.icloud.com/'
2. See error

**Expected behavior**
instead of the idmsa error, the login page should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/15945880/98913900-e5f00d00-24bf-11eb-8a4e-ed20ea639a77.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 20H2
 - ungoogled-chromium version: 86.0.4240.183 (Developer Build) (64-bit)

**Additional context**
I suspect the issue is because in the network tab, a request to the following URL fails with status code: 421 and error - "Missing X-APPLE-WEBAUTH-TOKEN cookie"
URL - https://setup.icloud.com/setup/ws/1/validate?clientBuildNumber=2019Project47&clientMasteringNumber=2019B35&clientId=8f85dcf4-10ab-4d2d-9677-9ecdaafa2163

**Comment by jstkdng** [comment]
Works on my machine.
![image](https://user-images.githubusercontent.com/52050345/98974166-9b33bc80-24e2-11eb-9ee6-21785ec87686.png)
Could you also show dev tools when trying to load the page, that could help.

**Comment by ekanshsinghal** [comment]
![image](https://user-images.githubusercontent.com/15945880/99072668-7884cf00-25da-11eb-871f-0b08e1f7a302.png)

![image](https://user-images.githubusercontent.com/15945880/99072255-acabc000-25d9-11eb-9644-af7cfbf55eb4.png)

Like I said previously, all other requests had 200 status.
request response - 
`configBag: {urls: {,…}, accountCreateEnabled: "true"}
accountCreateEnabled: "true"
urls: {,…}
accountAuthorizeUI: "https://idmsa.apple.com/appleauth/auth/authorize/signin?client_id=d39ba9916b7251055b22c7f910e2ea796ee65e98b2ddecea8f5dde8d9d1a815d"
accountCreate: "https://setup.icloud.com/setup/ws/1/createLiteAccount"
accountCreateUI: "https://appleid.apple.com/widget/account/?widgetKey=d39ba9916b7251055b22c7f910e2ea796ee65e98b2ddecea8f5dde8d9d1a815d#!create"
accountLogin: "https://setup.icloud.com/setup/ws/1/accountLogin"
accountLoginUI: "https://idmsa.apple.com/appleauth/auth/signin?widgetKey=d39ba9916b7251055b22c7f910e2ea796ee65e98b2ddecea8f5dde8d9d1a815d"
accountRepairUI: "https://appleid.apple.com/widget/account/?widgetKey=d39ba9916b7251055b22c7f910e2ea796ee65e98b2ddecea8f5dde8d9d1a815d#!repair"
downloadICloudTerms: "https://setup.icloud.com/setup/ws/1/downloadLiteTerms"
getICloudTerms: "https://setup.icloud.com/setup/ws/1/getTerms"
repairDone: "https://setup.icloud.com/setup/ws/1/repairDone"
vettingUrlForEmail: "https://id.apple.com/IDMSEmailVetting/vetShareEmail"
vettingUrlForPhone: "https://id.apple.com/IDMSEmailVetting/vetSharePhone"
error: "Missing X-APPLE-WEBAUTH-TOKEN cookie"
requestInfo: [{country: "IN", timeZone: "GMT+5.50", region: "DL"}]
0: {country: "IN", timeZone: "GMT+5.50", region: "DL"}
country: "IN"
region: "DL"
timeZone: "GMT+5.50"
success: false`

**Comment by ekanshsinghal** [comment]
Update it loaded fine in the incognito window. Also, initially, I thought it might be due to delugesiphon extension but after removing that still same error in the normal window.

**Comment by ekanshsinghal** [comment]
Update: It loaded fine in incognito which got me thinking if some extension was interfering with the site.
On further investigation, I found out PIA VPN extension was the issue. works fine after removing that.
