### ISSUE TITLE
Have extremely smooth scrolling disabled.

### ISSUE THREAD

**Issue by Joe23232** [Eloston/ungoogled-chromium#1251]
On Windows, with ungoogled chromium vs brave (chromium-based browser), it seems to have this rediculas smooth scrolling where when I am scrolling, it feels so slow and delayed, whereas with Brave it is quick and snappy while still smoothly scrolling. This is the exact same issue with Google Chrome and Firefox and I am not too sure why is this setting enabled by default.

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
