### ISSUE TITLE
Allow extensions to be installed from the chromestore

### ISSUE THREAD

**Issue by Joe23232** [Eloston/ungoogled-chromium#1254]
On chromium based browsers, I often times install privacy extensions, its unfortunate ungoogled-chromium does not allow this, therefore if I am using the web, my privacy is being breached even more than just using google chrome with the privacy extensions installed.

**Comment by TontyTon** [comment]
Use the extension - https://github.com/NeverDecaf/chromium-web-store
This allows you to directly download extensions from webstore.

**Comment by Joe23232** [comment]
I see, thanks mate

**Comment by securingmom** [comment]
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#downloading-the-crx-file

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
