### ISSUE TITLE
chrome.9oo91e.qjz9zk is blocked when trying to install extension

### ISSUE THREAD

**Issue by vinliao** [Eloston/ungoogled-chromium#1257]
**Describe the bug**

![Screenshot from 2020-11-19 20-02-21](https://user-images.githubusercontent.com/34117807/99670054-833fd800-2aa2-11eb-9e68-6913175e0eea.png)
![Screenshot from 2020-11-19 20-02-28](https://user-images.githubusercontent.com/34117807/99670030-7c18ca00-2aa2-11eb-8e2c-0f71e5875a15.png)

**To Reproduce**
1. download ungoogled-chromium
2. click on the link at the middle of the screen after first starting it up
3. see this error

**Expected behavior**
I want to download extensions.

**Environment (please complete the following information):**
 - OS/Platform and version: fedora 33
 - ungoogled-chromium version: Version 85.0.4183.102 (RPM Fusion Build) (64-bit)

**Additional context**
I thought the domain is blocked by my isp, but it does respond to my ping (although somewhat slow).
![Screenshot from 2020-11-19 20-06-51](https://user-images.githubusercontent.com/34117807/99670389-0a8d4b80-2aa3-11eb-9509-313361cbc501.png)

**Comment by vinliao** [comment]
This issue of installing extension has been fixed by using https://github.com/NeverDecaf/chromium-web-store.

**Comment by vicbanher** [comment]
I installed chromiun web store.crx but I can't install other extensions. The screen shows:
chrome.9oo91e.qjz9zk is blockedRequests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

Ubuntu Unity 20.04
ungoogled-chromium Version 87.0.4280.141 (Official Build) (64-bit)

How do I solve this problem. Help is appreciated
Victor
