### ISSUE TITLE
How to edit the default search engine

### ISSUE THREAD

**Issue by jafxdesign** [Eloston/ungoogled-chromium#1259]
Which file or files controls the default search engine?

I have made changes everywhere I can, still keeps showing the default search other than the one I set.

**Comment by guest271314** [comment]
To change default search engine after the build you can 

1, Navigate to chrome://settings/search
2. Click 'Manage search engines'
3. Click 'Add'
4. Set 'Search engine', 'Keyword', 'URL with %s in place of query' which should look something like <code>\<protocol\>://localhost:1234?search?=%s</code>
5. After setting the search engine click to right of the new entry where there is the three vertical dots icon when hovered the tool tip is 'More actions', select and click 'Make default'

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
