### ISSUE TITLE
manjaro AUR : set_sources_assignment_filter argument must be an empty list.

### ISSUE THREAD

**Issue by mirsella** [Eloston/ungoogled-chromium#1260]
**Describe the bug**
when building the package `ungoogled-chromium` from the AUR on update to date manjaro linux i get this error : 
```
==> Starting build()...
make: Entering directory '/home/mirsella/.cache/yay/ungoogled-chromium/src/chromium-launcher-6'
cc -o chromium -D_FORTIFY_SOURCE=2 -DLAUNCHER_VERSION=\"v6\" -DCHROMIUM_NAME=\"chromium\" -DCHROMIUM_BINARY=\"/usr/lib/chromium/chromium\" -DCHROMIUM_VENDOR="\"Manjaro Linux\"" -DPEPPER_FLASH_DIR=\"/usr/lib/PepperFlash\" -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/json-glib-1.0 -pthread -I/usr/include/libmount -I/usr/include/blkid  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now launcher.c -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
make: Leaving directory '/home/mirsella/.cache/yay/ungoogled-chromium/src/chromium-launcher-6'
  -> Configuring Chromium
ERROR at //build/config/BUILDCONFIG.gn:402:1: set_sources_assignment_filter argument must be an empty list.
set_sources_assignment_filter(sources_assignment_filter)
^------------------------------------------------------
==> ERROR: A failure occurred in build().
    Aborting...
error making: ungoogled-chromium
```

**To Reproduce**
1. `yay -S aur/ungoogled-chromium`

**Expected behavior**
the package would compile

**Screenshots**
![image](https://user-images.githubusercontent.com/45905567/99847926-25ca8a80-2b79-11eb-8506-866deec5e01a.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Linux main 5.9.8-2-MANJARO #1 SMP PREEMPT Wed Nov 18 06:38:03 UTC 2020 x86_64 GNU/Linux
 - ungoogled-chromium version: aur/ungoogled-chromium 86.0.4240.183-1

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-archlinux](https://github.com/ungoogled-software/ungoogled-chromium-archlinux)
