### ISSUE TITLE
This page is protected by browser. Dark Reader error for chrome://settings/ and https://chrome.google.com/

### ISSUE THREAD

**Issue by Toby4213** [Eloston/ungoogled-chromium#1262]
I want the browser to be in total dark mode, that includes the settings menu.
But Dark Reader says "This page is protected by browser."
Is that an issue with the browser settings? Since absolutely everything else associated to google has been removed, even to the extent to not being able to install extensions from the web store, ungoogled-chromium sould also not have the protection for such sites.
Or is the problem with Dark Reader?
![ungloogled-chromium_protecting_chrome_domains_01](https://user-images.githubusercontent.com/22265595/99890707-694cf380-2c62-11eb-827b-3914cadf721b.png)
![ungloogled-chromium_protecting_chrome_domains_02](https://user-images.githubusercontent.com/22265595/99890710-6c47e400-2c62-11eb-937e-befe07098c53.png)

**Comment by Luka-Filipovic** [comment]
```
    function canInjectScript(url) {
        if (isFirefox) {
            return (
                url &&
                !url.startsWith("about:") &&
                !url.startsWith("moz") &&
                !url.startsWith("view-source:") &&
                !url.startsWith("https://addons.mozilla.org/") &&
                !isPDF(url)
            );
        }
        if (isEdge) {
            return (
                url &&
                !url.startsWith("chrome") &&
                !url.startsWith("edge") &&
                !url.startsWith("https://chrome.google.com/webstore") &&
                !url.startsWith("https://microsoftedge.microsoft.com/addons")
            );
        }
        return (
            url &&
            !url.startsWith("chrome") &&
            !url.startsWith("https://chrome.google.com/webstore") &&
            !url.startsWith("devtools")
        );
    }
```

Seems like extension developers did it intentionally. 
Google Chrome doesn't allow extensions inject anything while on webstore url, however I'm sure that's not the case for UC.

**Comment by Ahrotahn** [comment]
Yeah, extensions aren't allowed to change built-in pages like that.  

You can get what you want by going to `chrome://flags/` and search for 'dark'.  Set `Force Dark Mode for Web Contents` to Enabled.  

Alternatively you can launch chromium with `--enable-features=WebUIDarkMode` and `--force-dark-mode`.

**Comment by hazarek** [comment]
> Yeah, extensions aren't allowed to change built-in pages like that.
> 
> You can get what you want by going to `chrome://flags/` and search for 'dark'. Set `Force Dark Mode for Web Contents` to Enabled.
> 
> Alternatively you can launch chromium with `--enable-features=WebUIDarkMode` and `--force-dark-mode`.

`Force Dark Mode for Web Contents` is a experimental feature. it makes sites look corrupted. 
`--enable-features=WebUIDarkMode` and `--force-dark-mode`. Doesn't work for https://chrome.google.com/webstore (macOS)

**Comment by Ahrotahn** [comment]
I maybe should have clarified that those flags are to make the built-in pages dark:
![about](https://user-images.githubusercontent.com/40727284/100516989-32d51400-314d-11eb-96bd-d1ec678d4b78.png)

The webstore is external and *can* be made dark by extensions but, as Luka pointed out, Dark Reader excludes the site.  You would either need to edit that extension to remove the restriction or use another one that doesn't have the limitation.  For example, I use [Dark Background and Light Text](https://chrome.google.com/webstore/detail/dark-background-and-light/cdcoopnlkdlmphjpjggdmhohkiklonkh):
![store](https://user-images.githubusercontent.com/40727284/100517041-9d864f80-314d-11eb-9935-5711979ffce6.png)

**Comment by hazarek** [comment]
my settings pages already are dark, i want dark mode only for store page without another plugin. i am using dark reader on macos

**Comment by iamMG** [comment]
> The webstore is external and _can_ be made dark by extensions but, as Luka pointed out, Dark Reader excludes the site. You would either need to edit that extension to remove the restriction

How to edit the extension as you are suggesting? Through the manifest file? How did you manage to darken the Web Sore? Can you please enlist the steps needed to reproduce this?

**Comment by Ahrotahn** [comment]
@iamMG They've since added an option to do this in Dark Reader in the new design!  
Click "Dev Tools" on the bottom right.  On the new window click the "Preview New Design" button at the bottom.  
Open Dark Reader's settings then go to "Site List".  There you can check "Enable on restricted pages".

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by veeud** [comment]
I am a "little" bit late but the easiest fix is go to [chrome://extensions/](chrome://extensions/)) and just give the extension permission to access files (toggle the option "Allow access to file URLs"). Maybe someone will see this.

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62218506/115e8708-6bf6-487b-b9b7-75ede8727645)

**Comment by veeud** [comment]
> > I am a "little" bit late but the easiest fix is go to chrome://extensions/) then go to "Details" on Dark Reader and give the extension permission to access files (toggle the option "Allow access to file URLs"). Maybe someone will see this.
> 
> Sorry but this doesn't help it to run on `https://chromewebstore.google.com/`. I have enabled the advanced setting `Enable on restricted pages`.
> 
> 

I am sorry, you are right. I did not read the issue correctly. I will delete my answer to avoid any confusion. Thanks for making me aware of it.

**Comment by tellervo99** [comment]
> @iamMG They've since added an option to do this in Dark Reader in the new design! Click "Dev Tools" on the bottom right. On the new window click the "Preview New Design" button at the bottom. Open Dark Reader's settings then go to "Site List". There you can check "Enable on restricted pages".

that shit don't work

**Comment by Ahrotahn** [comment]
> that shit don't work


https://github.com/user-attachments/assets/1e049589-6b06-4640-802a-0fc6c493d5cf

**Comment by SixelAlexiS90** [comment]
> > that shit don't work
> 
>  worksforme.mp4

Hi! I'm doing this on Firefox and it doesn't work, specifically on the extensions page and Mozilla support site:
https://addons.mozilla.org
https://support.mozilla.org

They stay white since they are both protected pages on Firefox, even by enabling the toggle on restricted pages.

**Comment by Ahrotahn** [comment]
Most browsers contain a list of domains that extensions are not allowed to operate on.  

In Firefox you can get this to work by going to `about:config` and setting `extensions.webextensions.restrictedDomains` to an empty list.  You'll also probably need to set `privacy.resistFingerprinting.block_mozAddonManager` to true.  

In Chromium-based browsers you would need to enable `chrome://flags/#extensions-on-chrome-urls`.  
This isn't needed on ungoogled-chromium because the domain substitution makes that domain not match.

**Comment by SixelAlexiS90** [comment]
> Most browsers contain a list of domains that extensions are not allowed to operate on.
> 
> In Firefox you can get this to work by going to `about:config` and setting `extensions.webextensions.restrictedDomains` to an empty list. You'll also probably need to set `privacy.resistFingerprinting.block_mozAddonManager` to true.
> 
> In Chromium-based browsers you would need to enable `chrome://flags/#extensions-on-chrome-urls`. This isn't needed on ungoogled-chromium because the domain substitution makes that domain not match.

Ok, for Firefox by emptying the "domains" list I was able to make it work on the Mozilla Support page.
For make it work on the Mozilla Addons page as well I had to put the "mozAddonManager" on true as well, so it's all good for now, thanks!

For Chrome instead, I've enabled that flag but the Google Web Store page for example is still white.

**Comment by PF4Public** [comment]
> For Chrome instead, I've enabled that flag but the Google Web Store page is still white.

Are you referring to Chrome or ungoogled-chromium?

**Comment by SixelAlexiS90** [comment]
> > For Chrome instead, I've enabled that flag but the Google Web Store page is still white.
> 
> Are you referring to Chrome or ungoogled-chromium?
Regular Chrome since Ahrotahn talked about generic Chromium-based browsers.
I'm sorry if it isn't relevant and I'll understand if this won't be talked further :)

**Comment by PF4Public** [comment]
Since it is a repository for ungoogled-chromium, we always refer to it by default. The message was that it works in ungoogled-chromium.

**Comment by hypersad** [comment]
@ChaliceChore Did you read the comments before you posted your comment? People have clarified @Ahrotahn is just giving an inappropriate solution. Enabling an experimental flag is corrupting most of modern website pages, and will bring a disaster user experience. It is just cheating users. After all, this whole thread should not be posted under the repository for ungoogled-chromium.

**Comment by Fred-Vatin** [comment]
Very frustrating. I managed to make my extensions work on restricted domain on Firefox and Edge when I was on Windows 10. Now, on Windows 11, with Edge, still impossible to make extensions work with `https://copilot.microsoft.com`, `https://chromewebstore.google.com`, `https://microsoftedge.microsoft.com` and so on. I even tested the `"runtime_allowed_hosts"` policy trick to no avail.

<img width="1177" height="388" alt="Image" src="https://github.com/user-attachments/assets/51c1ed54-aaaf-4a0b-a4a0-629c3067f881" />

**Comment by liweishu** [comment]
[Fishjar](https://github.com/fishjar/), the author of kiss-translator, pointed out that he did not limit the [chromewebstore](https://chromewebstore.google.com/).

Almost all chromium-based browsers have limitations.
