### ISSUE TITLE
Toggling off autoplay policies in chromium based browsers?

### ISSUE THREAD

**Issue by steponmepls** [Eloston/ungoogled-chromium#1263]
There's a flag in `about:config` in Firefox that, once set to false, allows media to be autoplayed in the background: `media.block-autoplay-until-in-foreground`
I had to enable this flag in Firefox to let a playlist from doing its job on a specific website playing videos one after another but I can't seem to find an equivalent flag/setting for chrome/chromium.
I've read the following documentation and tried different approaches without success:
- https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
- https://dev.chromium.org/administrators/policy-list-3#AutoplayAllowed
- https://dev.chromium.org/administrators/policy-list-3#AutoplayWhitelist

`chrome.exe --autoplay-policy=no-user-gesture-required`

The video only correctly autoplays if I re-visit the tab. This doesn't happen with iframe sources coming from youtube but it happens if the source is coming from nicovideo.jp
I thought it was some sort of script from within the iframe causing this but by simply enabling the flag mentioned above in Firefox solved the issue so I can only think this is a common policy adopted both by Frefox and chromium regarding autoplay media

Is there a way to toggle this policy off since there's no way to do so in about:flags ? Or better, is there a way to whitelist specific websites I trust?

**Comment by guest271314** [comment]
Are you trying to turn autoplay with no user gesture on or off?

**Comment by HighSchoolTeacherpng** [comment]
Would you like to tell the class how you solved this?
