### ISSUE TITLE
Other: Could we work on making detailed building from source notes?

### ISSUE THREAD

**Issue by Frick-David** [Eloston/ungoogled-chromium#1269]
Hey,

I am looking to get ungoogled chromium on my Linux install. However, my distro's team does not wish to package it. Is there anyway we could work together to make some more detailed build instructions. I can not say that I have built chromium from source. The building.md notes do say that the directions are insufficient to build ungoogled-chromium from source which is something I and probably a good few others would like to do. How hard would it be to build it from source? Is it pretty involved? Is this something we could work together on to explain the building.md section to cover building it from source from stage one to the end?

Thanks and best,
David Frick

**Comment by mbakke** [comment]
Does your distro package Chromium (the regular one)?

Once you have run the ungoogled scripts, building instructions are the same as for Chromium itself.

If you are starting from scratch, a good place to start is to look at existing Chromium build scripts.  Arch probably has the simplest one, at [~240 lines](https://github.com/archlinux/svntogit-packages/blob/packages/chromium/trunk/PKGBUILD).

A guide or wiki entry will quickly get outdated, and depends on how far you are willing to go wrt unbundling code, as well as other constraints imposed by your package manager/distro.

**Comment by Frick-David** [comment]
It does include chromium. How would I proceed from there?

**Comment by dm17** [comment]
> It does include chromium. How would I proceed from there?

Which distro? If it is Void, then I'm making progress building it here:
https://github.com/Eloston/ungoogled-chromium/issues/375

**Comment by Frick-David** [comment]
It is the void!

**Comment by Frick-David** [comment]
Probably can close this since I more or less am going to watch over #375. Thanks

**Comment by Eloston** [comment]
Closing per OP's request.

Also, if packaging benefits is not a high priority for you (notably, building against system libraries), you can always consider Portable Linux. Its build script is also pretty simple.
