### ISSUE TITLE
Hardware video decoding?

### ISSUE THREAD

**Issue by forkoz** [Eloston/ungoogled-chromium#128]
On old systems CPU decoding of video is atrocious. Chrome limits hardware decoding in linux to chrome OS. Patches have been made and I'm running the PPA version right now. With your changes and said patches this would finally be a killer browser.

Patches: http://www.kelvinblog.tk/enable-chromium-vaapi-hardware-acceleration-linux/
PPA: https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev

**Comment by Eloston** [comment]
The Debian version 53 builds have the VA-API patch. It seems to work. But for some reason in 54, they removed it. I heard it's broken according [to this](https://github.com/gcarq/inox-patchset/issues/24#issuecomment-262754875). There is also some effort in that issue report to add the VA-API patch to Inox (which this project uses patches from).

The blog post you linked is very old. I don't think it will help me that much.

If I'm understanding you correctly, what you're asking for is already implemented. If this is not the case, please let me know and I will reopen.
