### ISSUE TITLE
omnibox search suggestion not working

### ISSUE THREAD

**Issue by rik1599** [Eloston/ungoogled-chromium#1280]
**Describe the bug**
In latest version of ungoogled-chromium for Arch Linux (87.0.4280.88) the search suggestions aren't working

**To Reproduce**
1. Change search engine to Ecosia or DuckDuckGo
2. Make a research on the address bar
3. Notice that there aren't any suggestion

**Screenshots**
![image](https://user-images.githubusercontent.com/31370173/101898741-f5d93a80-3bac-11eb-9265-14489b0e8230.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Manjaro Linux KDE 20.2 with linux kernel 5.9 
 - ungoogled-chromium version: 87.0.4280.88 for Arch Linux

**Comment by Luka-Filipovic** [comment]
Do you have this settings checked on?
![image](https://user-images.githubusercontent.com/56702689/102201160-00a21100-3ec6-11eb-9268-6110b4c3a1f2.png)

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
