### ISSUE TITLE
[policy][extensions] Installations by rules are break.

### ISSUE THREAD

**Issue by K-mikaZ** [Eloston/ungoogled-chromium#1281]
**Describe the bug**
Can not install extensions programmatically.

**To Reproduce**
1. Create a json file into "/etc/chromium/policies/managed/ExtensionSettings.json"
2. add for example LocalCDN extension:
```
{
  "ExtensionSettings": {
      "njdfdhgcmkocbgbhcioffdbicglldapd": {
      "installation_mode": "normal_installed",
      "update_url":
        "https://clients2.google.com/service/update2/crx"
    }
  }
}
```
2. Open ungoogled-chromium
3. No extensions append (added).

**Expected behavior** 
I would like to be able to install some extensions programmatically.

**Environment (please complete the following information):**
 - OS/Platform and version:   Distro: `MX-19.3_ahs_x64 patito feo`  base: `Debian GNU/Linux 10 (buster)`
 - ungoogled-chromium version: `Version 84.0.4147.135 (Build de développement) built on Debian buster/10, running on Debian buster/10 (64 bits)`

**Additional context** 
Another problem appears if I have the json file and if I am using [https://github.com/NeverDecaf/chromium-web-store](https://github.com/NeverDecaf/chromium-web-store), if I have set `force_installed` instead of `normal_installed`:
I cannot install the extension, It tells me "installation blocked by administrator".

Precision, the json works with other chromium based browsers (vivaldi, chromium)

**Comment by mbakke** [comment]
I believe installing extensions using a policy requires access to the Chrome Web Store, which has been disabled in ungoogled-chromium.

You can install extensions automatically by downloading and placing them in `/usr/share/chromium` as outlined in the [FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#installing-the-crx-file).

If you install ungoogled-chromium with [GNU Guix](https://guix.gnu.org/manual/en/html_node/Installation.html) (works on any distro), there are some extensions packaged already so you can simply `guix install ungoogled-chromium ublock-origin-chromium`.  I am happy to package the LocalCDN extension if you are interested.

**Comment by K-mikaZ** [comment]
> I believe installing extensions using a policy requires access to the Chrome Web Store, which has been disabled in ungoogled-chromium.

OK, thanks for the explanation.
There is still a problem. If I set `force_installed` instead of `normal_installed`, I cannot install the extension (even with [https://github.com/NeverDecaf/chromium-web-store](https://github.com/NeverDecaf/chromium-web-store): it says "installation blocked by administrator".
But I will do with (adapt my json).

> You can install extensions automatically by downloading and placing them in `/usr/share/chromium` as outlined in the [FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#installing-the-crx-file).
> 
> If you install ungoogled-chromium with [GNU Guix](https://guix.gnu.org/manual/en/html_node/Installation.html) (works on any distro), there are some extensions packaged already so you can simply `guix install ungoogled-chromium ublock-origin-chromium`. I am happy to package the LocalCDN extension if you are interested.

I think for ungoogled-chromium I will continue to use [https://github.com/NeverDecaf/chromium-web-store](https://github.com/NeverDecaf/chromium-web-store), but thank you for your proposal.
