### ISSUE TITLE
Apple Silicon arm64 or unviersal builds

### ISSUE THREAD

**Issue by nshtg** [Eloston/ungoogled-chromium#1287]
Are you planing to compile native arm64(e) builds for the M1-Macs and/or universal binaries for x86_64 and arm64e?

**Comment by jstkdng** [comment]
It could be done from github workflows but it won't be simple.

**Comment by feep** [comment]
> does regular chromium have an arm64 mac build?

No, not as of 89.0.4381.0 build 840589 [(download link)](https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/840589/chrome-mac.zip).
