### ISSUE TITLE
ungoogled chromium won't work in flatpak (Debian)

### ISSUE THREAD

**Issue by fariszr** [Eloston/ungoogled-chromium#1288]
**Describe the bug**
i cant start ungoogled-chromium on flatpak.
it shows error:
Your Flatpak version does not support the expose-pids flag,
which means that Chromium is unable to run. This generally
happens if your distro's bubblewrap installation is setuid
instead of using user namespaces.

**To Reproduce**
1. install ungoogled chromium from flatpak

**Screenshots**
![image](https://user-images.githubusercontent.com/35614734/102468162-18ee6900-4049-11eb-85d3-3b9a748d99dd.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Debain testing/sid
 - ungoogled-chromium version: 87

**Additional context**
i have enabled user namespaces in the debian kernel but it still shows this error. (by `sudo sysctl kernel.unprivileged_userns_clone=1` and then ` sudo echo kernel.unprivileged_userns_clone = 1 | sudo tee /etc/sysctl.d/00-local-userns.conf`
even with --no-sandbox it still shows the same error.
**this issue happens with the normal chromium flatpak package too**

**Comment by n1msk** [comment]
I get this error as well.

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the Flatpak repo: [flathub/com.github.Eloston.UngoogledChromium](https://github.com/flathub/com.github.Eloston.UngoogledChromium)
