### ISSUE TITLE
re2 updates break chromium on linux

### ISSUE THREAD

**Issue by okanpe** [Eloston/ungoogled-chromium#1289]
Hi,

re2 just got an update on my distro (arch) and now chromium complains about failing to find libre2.so.8 .

"/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.8: cannot open shared object file: No such file or directory"

Looks like with this update, file is updated to libre2.so.9 . And when I symlink libre2.so.9 (or libre2.so) to .8, then it complains about an undefined symbol.

"/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: _ZN3re23RE23Arg12parse_stringEPKcmPv"

Problem persists with
87.0.4280-88
87.0.4280-66
86.0.4240.183

This happens every time re2 package gets an update but symlinking would at least allow me to use the browser before, now it simply doesn't work.

**Comment by megnu** [comment]
From what I understand, rebuilding ungoogled-chromium with the lastest re2 version is the solution.
But I would rather wait for the next release, so I did downgrade re2 and it works.

**Comment by okanpe** [comment]
Yes of course, but sometimes  it'd take over 2 weeks for a new release. I was thinking of statically linking the re2 lib, not sure if that's ok with the project

**Comment by wchen342** [comment]
I think @jstkdng's philosophy of maintaining the AUR package is to keep the PKGBUILD as close to upstream as possible, so I doubt he will make the change. Also the problem is not just with re2, it has happened with other libraries in the past.

**Comment by jstkdng** [comment]
If you want to statically link re2 just comment out this line from the PKGBUILD
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/a2e922f3d3f830c79115c5285f4ff891f10b685f/PKGBUILD#L72

**Comment by okanpe** [comment]
Thank you for the replies. I'm not really building myself with a laptop, wondered if maintainer would. But as @wchen342 pointed out, that's not happening. I'm closing this

**Comment by jstkdng** [comment]
If that happens ofc I'm rebuilding and uploading to my repo as it affects me as well.
If you aren't using my repo you should ask for a rebuild from the maintainer of the one you use.
