### ISSUE TITLE
Disable WebRTC, WebGL, WebAssembly 

### ISSUE THREAD

**Issue by trimechee** [Eloston/ungoogled-chromium#1292]
Hello, Ungooled Chromium is great and fantastic ! Ungooled Chromium is the fastest and lightest of web browsers ever : thank you very much ! plesa i have request : there are privacy and ip security concerns with WebRTC, WebAssembly can be used to spread virus malware, crypto mining currency, and  WebGL is not needed for low grazing notebooks that do not need the display 3D .....
Unfortunately Chromium does not allow to disable Webrtc, can you please add option in the parameters to disable webrtc and prevent ip leak? and an option to disable easily for beginners disable webassembly and webgl and the 3D API please ? i think it will make the browser even lighter for those who just want to use their computer to browse facebook and watch youtube and microsft word and it will keep the fan from spinning too much! thank you !

**Comment by guest271314** [comment]
I am not sure if WebRTC can be disabled. The Internet connection can be turned off.

It is possible to launch Chromium with the following flags https://peter.sh/experiments/chromium-command-line-switches/

- `--disable-webgl`
- `--disable-webgl-image-chromium`
- `--disable-webgl2`
- `--disable-zero-copy`
- `--disable-gpu`
- `--disable-zero-copy`

`WebAssembly` can only run code in the host environment. I do not know why that is problementic.

> i think it will make the browser even lighter for those who just want to use their computer to browse facebook

If a user is browsing *acebook it defetas the purpose of disabling WebRTC, as *acebook is tracking every move that is made by users on their site.

**Comment by trimechee** [comment]
Awesome bro ! This is very useful and informative ! Thank you for sharing these precious secrets!:)
 I have a question please : whait is the difference between use these Chromium Command Line and between go to chrome: // flags and type in the search field "webassembly", "webgl", "webrtc" .... and click IN "disable" on all these flags? is there a difference or is it the same thing ?

**Comment by trimechee** [comment]
Hello Guest271314, thank you very much for yot great help ! Please i have other question : I decided to discover the chromium flag in chrome :// flags and found a lot of flags that I think are unnecessary and I disabled them which made my Ungoogled Chromium even faster on my 2007 laptop and I can finally play HD video without lag thank's Allah !
and I also discoveri some good surprises and I activated these flags: Heavy Ad Intervention to protect my browser from crypto mining currency and I think it will be a good idea if Mr Eloston activates by default this essential option in Ungoogled Chromium, I also activated "litevideos" which allowed me to play HD video without lag or stutter .... but I found these flags:

CSSOM View Scroll Coordinates

Filtering scroll prediction

Threaded scrolling

Previews Allowed

Despite my research, I didn't understand what these flags are for and the usefulness and the role of these flags ans  I don't know if it is safe or is there  bug and stability issues if i disable these flags, I need to disable as many flags as possible because my old laptop dates from 2007 and the noise of the fan laptop is spoiling my life, thank you very much for your help :)

**Comment by guest271314** [comment]
> whait is the difference between use these Chromium Command Line and between go to chrome: // flags 

No difference that I am aware of. Launching with flags negates the need to set at chrome: //flags and potentially requiring relaunching for the flags to take effect.

> Despite my research, I didn't understand what these flags are for and the usefulness and the role of these flags ans I don't know if it is safe or is there bug and stability issues if i disable these flags

More research is necessary. 

I have no way to verify if a flag is "safe" or not. First we would need to agree on the definition of that term.

**Comment by trimechee** [comment]
Excellent ! Thank you very much for this info ! there is an explanation of the functionality of these flags under the name of each flag in chrome://flags but I am not a developer thas's why I hesitated to deactivate them .... but I am courageous and I decide to disable these flags and the browser behaves normally !  thank you very much for your help :)

**Comment by trimechee** [comment]
Clarification, you said "WebAssembly can only run code in the host environment. I do not know why that is problementic.", i read an article about the danger of webassembly : the dark side of webassembly, some poeple said webassembly is used fr crypto-currency mining and other malware activities : https://www.virusbulletin.com/virusbulletin/2018/10/dark-side-webassembly/

**Comment by trimechee** [comment]
@Guest271314, please i have another question and thank you for your kindness! I am considering to use in the future a light linux os in sha Allah and I read this article and to disable flags in linus, it says we have to use the terminal, it says run terminal and put :
"chromium-browser --remote-debugging-port = 9222
google-chrome --foo --bar = 2 "

I didn't understand why there is "google-chrome foo bar ...." in this command line? What's the point ? and so in linux i can't just make shortcut of Unggoled Chromium and add command line just like on windows 7 ?! to use unggoled chromium with command line flag disabled, do I have to use terminal every time ?! we couldn't make simple shortcut on the desktop just like un windows 7 ?!!

**Comment by guest271314** [comment]
> I read this article
>
> it says we have to use the terminal, it says run terminal and put :
"chromium-browser --remote-debugging-port = 9222
google-chrome --foo --bar = 2 "

chromium-browser is not google-chrome. I do not know what that command is trying to do other than remote debugging, perhaps read debugging messages from Chromium on Chrome?

There are a number of distributions and packages that may result in Chromium or Chromium binary being named differently.

> and so in linux i can't just make shortcut of Unggoled Chromium and add command line just like on windows 7 ?

Yes, you can.

**Comment by trimechee** [comment]
Great ! thank you veru much for your help :) this the article, i think remote debugging flag is an exemple : http://www.chromium.org/developers/how-tos/run-chromium-with-flags

**Comment by trimechee** [comment]
@guest271314, I have other question please : I'm afraid if I add command line to disable flags that no longer exist, it causes a stability bug, so all the command lines on this page are updated?
https://peter.sh/experiments/chromium-command-line-switches/

because chromium removes several flags regularly, by exp there is command line to disable "print preview", but when i go to chrome: // flags, i can't find the "print preview" flag, so if i add a command line for a flag that no longer exists, will that cause stability problems?

**Comment by trimechee** [comment]
And ca i make add many commad line ? how to ? for exp afrter C:\Users\pc\AppData\Local\Chromium\Application\chrome.exe, i add space --disable-webgl and i add another space 
--disable-webgl-image-chromium.....that's right please ?

**Comment by guest271314** [comment]
> will that cause stability problems?

Not that I am aware of.

> --disable-webgl and i add another space
--disable-webgl-image-chromium

Yes. Except for the `--disable-features=AudioServiceOutOfProcess,feature1` and `--enable-features=AwaitOptimization,feature1` version.

**Comment by trimechee** [comment]
Great ! Thank you very much :)

**Comment by jacob755** [comment]
i like ungoogled dev completly remove webrtc code
and about about command switch  if anyone wish to use command on windows short cut its can not be added more than a few windows put some limition on it .so you have use chrlauncher app

**Comment by Eloston** [comment]
Closing since all inquiries seem to be resolved.

**Comment by InfoTriqs** [comment]
> 

Litevideos still exist?
