### ISSUE TITLE
Randsomware pattern warning 

### ISSUE THREAD

**Issue by ChaoticHub** [Eloston/ungoogled-chromium#1296]
**Describe the bug**

**To Reproduce**
1. Go to 'Discord.com'
2. Click on 'Join any voice chat/ one on call'
3. 'Browser closes and windows pops up ransomware pattern warning

**Expected behavior**
Join calls with no issue, this issue is new starting today and happens each any every time I start a discord call / join a server voice chat, though not when simply browsing discord normally.

**Screenshots**
![Randsom](https://user-images.githubusercontent.com/35610319/102744490-ecc43800-4327-11eb-8f3f-61acda631704.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 Pro 10.0.18363
 - ungoogled-chromium version: Version 84.0.4147.105

**Additional context**
This has not been any issue for the past week of joining calls daily, though I have gotten several of these notifications only when trying to call. Also, I have had this extension since last week and no issues up to now, I am unsure if [this](https://github.com/NeverDecaf/chromium-web-store) could be causing any of my issue.

**Comment by jstkdng** [comment]
Hmm, could it be a binary that was compromised and just recently the virus started trying to do stuff? Also, that is an old chromium version, some important security updates rolled out and v84 doesn't have those updates.

**Comment by ChaoticHub** [comment]
> Hmm, could it be a binary that was compromised and just recently the virus started trying to do stuff? Also, that is an old chromium version, some important security updates rolled out and v84 doesn't have them.

Thank you, for the heads up about the version, is there any mechanism for it to update itself? Also, any chance this was just a false positive?

**Comment by ChaoticHub** [comment]
Seems to have been resolved by an update. Hopefully just a false alert
