### ISSUE TITLE
[Flatpak] Login cookies are deleted after closing ungoogled-chromium

### ISSUE THREAD

**Issue by qx-775** [Eloston/ungoogled-chromium#1298]
**Describe the bug**
After logging in and observing cookies and closing down ungoogled-chromium. We restart it and I am suddenly not logged in anymore in all of my websites (github, reddit etc).
I clearly have the setting '_Clear cookies and site data when you quit Chromium_' **disabled**.

**To Reproduce**
1. Go to reddit.com and login
2. We view in ungoogled-chromium settings 8 cookies for reddit.com and 2 cookies for www.reddit.com (these 2 say file system, local storage)
3. Close ungoogled-chromium and start it again.
4. I  am not logged in anymore in any of my accounts and for the reddit website we only see 2 cookies for www.reddit.com, the 8 other cookies are gone.

**Expected behavior**
Cookies are not deleted on shutdown

**Screenshots**

**Environment (please complete the following information):**
 - OS: POP_OS 20.04 Gnome 3.36
 - ungoogled-chromium version:  Version 87.0.4280.88 (Official Build) (64-bit) Flatpak version

**Additional context**
My theory is that flatpak does not create a persistent directory for certaing cookies, i tried giving permissions to allow all the filesystem on flatpak using the flatseal program but without any success.
Could you kindly help me prevent ungoogled-chromium from deleting cookies after shutdown of my OS or the browser. This is bad for my workflow. Thank you.

**Comment by wchen342** [comment]
It seems to be affecting normal Chromium as well: [https://github.com/Eloston/ungoogled-chromium/issues/1290](https://github.com/Eloston/ungoogled-chromium/issues/1290)

**Comment by Oymate** [comment]
The author now says it was only on flatpak

**Comment by brain0verfl0w** [comment]
Yes, just checked out. Versions from ungoogled-software are persistent, while flatpak version isn't.

**Comment by Oymate** [comment]
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-do-i-have-to-login-to-websites-every-time-i-open-ungoogled-chromium

**Comment by rany2** [comment]
Hi, I just realized that people are making flatpak issues in  https://github.com/Eloston/ungoogled-chromium. Please direct them to https://github.com/flathub/com.github.Eloston.UngoogledChromium.

Anyway this is fixed as of https://github.com/flathub/com.github.Eloston.UngoogledChromium/commit/7efded100f5523cdc7bca9a0f1d6da9de199eae4

**Comment by qx-775** [comment]
Can confirm issue is fixed! Closing.

**Comment by Oymate** [comment]
Also if you have cookie autodelete add-on, remember to whitelist site in question
