### ISSUE TITLE
[Flatpak] Can't login to websites using U2F Device Yubikey

### ISSUE THREAD

**Issue by qx-775** [Eloston/ungoogled-chromium#1299]
**Describe the bug**
I am trying to login to websites protect by my 2FA device using U2F with a yubikey 5 nano. I can login using the yubikey in firefox, so I believe this issue is flatpak related.

**To Reproduce**
1. Go to twitter.com and login using credentials
2.  A popup is correctly shown Log in with security key and the prompt follows waiting for me to touch the U2F device
3. Touch yubikey so that we login
4. Twitter shows that the yubikey was touched and the popup is removed, however I am not logged in. 
5. This happens not just for twitter, but for all other websites with U2F protection.
6. The output of the console says after touching the yubikey: 

```js
Invalid Device
(anonymous) @ u2f_security_key_verification_page.e8bdc50d983dcd2b01f126f17f742adbefac08b2.js:7
Promise.catch (async)
u2fWebAuthenticate @ u2f_security_key_verification_page.e8bdc50d983dcd2b01f126f17f742adbefac08b2.js:7
(anonymous) @ u2f_security_key_verification_page.e8bdc50d983dcd2b01f126f17f742adbefac08b2.js:7
```

**Expected behavior**
I am logged in after touching the yubikey

**Environment**
- OS: POP_OS 20.04 Gnome 3.36
- ungoogled-chromium version: Version 87.0.4280.88 (Official Build) (64-bit) Flatpak version

I am aware that the flatpak version is still in beta thus I would like to help resolve this issue
I do not know where to start, other than testing with ungoogled-chromium installing without flatpak, but I was unable to do that
since I find the docs/instructions for Ubuntu unclear on what to do step by step.
Could you kindly help me resolve this issue? 
Thank you.

**Comment by qx-775** [comment]
Leaving comments for myself and debug purposes...

Using the webbrowser LibreWolf (fork of firefox) I can use the yubikey to login if I allow `device=all` flag in flatpak.

**Comment by qx-775** [comment]
Came back to it to view the status of this functionality. It is still not implemented in flatpak :(
Closing, since it's not an ungoogled chromium issue, but a flatpak one.

**Comment by pkoch** [comment]
If it helps anybody, I was able to get the flatpak Chrome (com.google.Chrome) read my Yubikey by using Flatseal (com.github.tchx84.Flatseal) to use the global override for `device=all`.

The application specific didn't make a difference. The global made it work. :shrug:

**Comment by pkoch** [comment]
Actually, it's not a matter of the flag being app-specific or global, but rather that Chrome starts with the Yubikey plugged in.

**Comment by videoMonkey** [comment]
> Actually, it's not a matter of the flag being app-specific or global, but rather that Chrome starts with the Yubikey plugged in.

That made the difference for me also.
