### ISSUE TITLE
About canvas fingerprinting

### ISSUE THREAD

**Issue by 9Morello** [Eloston/ungoogled-chromium#13]
Well, since this is a project with privacy in mind, I think its worth posting here. Theres a pretty good add-on to manage canvas reading for Firefox called CanvasBlocker.I asked the author and he is interested in porting it to Chromium. He just needs someone familiar with how Chromium works to help him. Heres the link: https://github.com/kkapsner/CanvasBlocker/issues/65

Maybe you guys could get in touch with him, it would be cool!
Thanks for this awesome project.

**Comment by Eloston** [comment]
I did a quick search, and [this extension for Chrome](https://github.com/marspr/privacy-extension-chrome) has a method of preventing canvas fingerprinting (though I'm not sure how it compares to CanvasBlocker).

Unfortunately, I don't have enough time to work on CanvasBlocker now. I'll reconsider in the future. Thanks for showing me this extension though, it looks pretty interesting.

P.S. WebGL can be used for fingerprinting too; [Panopticlick](https://panopticlick.eff.org/) can detect WebGL fingerprints. It'll be nice if CanvasBlocker could prevent WebGL fingerprinting too.

**Comment by 9Morello** [comment]
Thanks for your attention. I already know that extension, but unfortunately its not working anymore. Having it enabled and disabling the header reading doesn't change the results: https://www.browserleaks.com/canvas
