### ISSUE TITLE
Disable top sites?

### ISSUE THREAD

**Issue by misaka00251** [Eloston/ungoogled-chromium#1304]
In `chrome://ntp-tiles-internals/`, **TOP_SITES** is enabled.

In Google Chrome, you can disable it easily, but it seems I can't disable it in ungoogled-chromium.

**Comment by Ahrotahn** [comment]
You can disable it by launching with the `--disable-top-sites` switch.  This also removes the most visited tiles.

**Comment by misaka00251** [comment]
Thank you very much!
