### ISSUE TITLE
Add Useful Command Line Switches To About Flags

### ISSUE THREAD

**Issue by v00v** [Eloston/ungoogled-chromium#1306]
Can you please add more useful "command line switches" [1] under "about:flags" ? There are many good onces that are not accessible under "about:flags". Here are few examples;

``--disable-webgl`` - Disable all versions of WebGL.
``--disable-gpu`` - Disables GPU hardware acceleration.
``--no-crash-upload`` - Prevent the crash client from uploading crash reports.
``--no-default-browser-check`` - Disables the default browser check.
``--no-pings`` - Don't send hyperlink auditing pings.

[1] https://peter.sh/experiments/chromium-command-line-switches/

**Comment by jacob755** [comment]
and plus --disable-top-sites  --enable-stale-while-revalidate --enable-offline-load-stale-cache

**Comment by PF4Public** [comment]
Those are command line switches, not flags. They should be applied locally. For example in Gentoo they [go to](https://github.com/PF4Public/gentoo-overlay/blob/ebc3beb75ae99c26de812ea68ceb07ff50c66710/www-client/ungoogled-chromium/ungoogled-chromium-94.0.4606.61-r1.ebuild#L1065-L1066) [/etc/chromium/default](https://github.com/PF4Public/gentoo-overlay/blob/master/www-client/ungoogled-chromium/files/chromium.default)
