### ISSUE TITLE
Suggestion to have the binary version in the AUR?

### ISSUE THREAD

**Issue by Joe23232** [Eloston/ungoogled-chromium#1308]
Its pretty slow to compile `ungoogled-chromium` from source. I was hoping in the near future there could be a binary version in the AUR?

**Comment by laamalif** [comment]
you can download binary package from here: https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/87.0.4280.88-1

**Comment by Joe23232** [comment]
I understand that, however it is not in the AUR. And I wanted to suggest to
have the binaries in the AUR if possible?

**Comment by wchen342** [comment]
There used to be a `-binary` package on AUR, but it was later removed by the AUR admins due to their regulations.

**Comment by Joe23232** [comment]
Interesting, what regulation was it may I know as I am curious?

**Comment by wchen342** [comment]
I didn't remember exactly but I think it is that they said a package cannot have its source as some compiled binary files and repackage them into an AUR package.

**Comment by Joe23232** [comment]
Oh that sucks mate

**Comment by Joe23232** [comment]
As a suggestion, wouldn't it be a good idea if `ungoogled-chromium` in future builds alerts the user if there is an update available?

**Comment by wchen342** [comment]
I don't think AUR has that functionality. You can either use helper scripts like `yay` or just click "Watch - Custom - Releases" for the [archlinux repo](https://github.com/ungoogled-software/ungoogled-chromium-archlinux).

**Comment by Joe23232** [comment]
I see, thanks :)

**Comment by Joe23232** [comment]
Hi @laamalif , I downloaded the binary via your suggested link [https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/87.0.4280.88-1](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/87.0.4280.88-1) However I am unable to figure out how do I launch it? I tried to click on the `*.desktop` file included in the entire folder but it brefily shows the icon and then it closes itself. I am kinda noob over here.

**Comment by vetrivln** [comment]
Did you extract the whole file? Try runnning `chromium` in the terminal. 

(Instead of downloading the compilied binary you can use an unofficial repository like [jk-aur](https://github.com/jstkdng/aur).)

**Comment by wchen342** [comment]
You are supposed to use `pacman -U ungoogled-chromium-87.0.4280.88-1-x86_64.pkg.tar.zst` to install local package.

**Comment by Joe23232** [comment]
Ah I see, thanks :)

**Comment by Joe23232** [comment]
Hey man I am having an error. After I downloaded it, I ran 

```
sudo pacman -U ungoogled-chromium-87.0.4280.88-1-x86_64.pkg.tar.zst
```
And it did install fine, but then when I ran `chromium` on terminal then i get this error:
```
/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory
```

**Comment by nutta-git** [comment]
@Joe23232 
Do you have an other chromium base browser on your system like brave?

**Comment by Joe23232** [comment]
@nutta-git 

Hey man

> Do you have an other chromium base browser on your system like brave?

I do but I prefer to use `ungoogled-chromium` as it doesn't have weird issues with a particular extension that `brave` as on Linux. Plus it keeps shoving crypto crap down my throat and I don't want any advertisement crap.

> I had the same issue, try restarting your computer;

I tried doing that, it doesn't work :(

> however, if that doesn't work try removing the other chromium based browser and see if it works.

I could try that, but I don't want to lose the configuration files ;(

**Comment by nutta-git** [comment]
@Joe23232 
configuration files in your home directory are not effected by (`pacman -Rns`).
You should be able to reinstall it back and should have all your browser data.

**Comment by Joe23232** [comment]
Ah I see, did you manage to fix this issue by the way?

**Comment by wchen342** [comment]
The is because that binary is compiled towards an old version of library in Arch. Since the binary was compiled Arch has updated their libs and you have the new ones on you computer.

Basically you need a newly compiled binary everytime this happens, and it happens quite often on Arch because they are a rolling-update system. Try [https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/87.0.4280.88-3/ungoogled-chromium-87.0.4280.88-3-x86_64.pkg.tar.zst](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/download/87.0.4280.88-3/ungoogled-chromium-87.0.4280.88-3-x86_64.pkg.tar.zst).

**Comment by nutta-git** [comment]
@Joe23232 
That's how I fixed the issue on my side.

**Comment by BachoSeven** [comment]
If you have issues building the package yourself, the packager of the archlinux build has an unofficial repo building the package [here](https://github.com/jstkdng/aur/)

**Comment by PF4Public** [comment]
Closing this issue in favour of ungoogled-software/ungoogled-chromium-archlinux#143
