### ISSUE TITLE
HTTPS Everywhere Crashes

### ISSUE THREAD

**Issue by stfnhh** [Eloston/ungoogled-chromium#1319]
Currently using the newest build of UC on an ARM Macbook Air HTTPS Everywhere crashes when I start it, doesn't produce any logs in the chrome://extensions but I was able to get this from console: https://gist.github.com/stfnhh/93828c8de989cbfee125de252b71e6fa

Any ideas?

**Comment by stfnhh** [comment]
Possibly related various other sites like beta.protonmail.com also crash with a similar error.

**Comment by kramred** [comment]
Did you compile it yourself? It says `ARM-64 (Native)` 

Maybe try the newer [.141](https://github.com/Eloston/ungoogled-chromium/tree/87.0.4280.141-1) Chromium version (macOS patches don't need updating) 

Also, updating your macOS to ≥[11.1](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_1-release-notes) might help.

**Comment by stfnhh** [comment]
@kramred Thanks for responding, I didn't compile it myself, using this build by Marmaduke https://github.com/macchrome/macstable/releases, unfortunately I can't get my build setup to work for the life of me (https://github.com/stfnhh/ungoogled-chromium-macos/runs/1674636118?check_suite_focus=true).  I've updated to 11.1 but the issue still persists.

**Comment by kramred** [comment]
Ideas:

- You could try an empty profile – backup your profile directory then delete or move it and start Chromium, install the extension again or visit a site that currently crashes the browser
- You can wait for an updated ARM64 version from @macchrome or [open an issue in their repo](https://github.com/macchrome/macstable/issues)
- For building an ARM64 version with GitHub Actions you probably will have to use the default clang/LLVM from Xcode ≥12.2 (which seems to be included in the GitHub Actions [VM](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md)); i.e [adjust the build scripts to do that](https://chromium.googlesource.com/chromium/src.git/+/master/docs/mac_arm64.md); I wanted to look into that but have not yet found the time to do so… and I saw that you've already added the flag `target_cpu="arm64"`

**Comment by stfnhh** [comment]
@kramred I was finally able to get it to compile locally on a M1 using .141 but the issue persists.  From what I can tell the problem stems from the renderer.

**Comment by SugaryHull** [comment]
> From what I can tell the problem stems from the renderer.
Have you tried forcing software rendering (and vice-versa)?

**Comment by PF4Public** [comment]
HTTPS Everywhere was removed in 7fc57bdc9404e6ede6eb60b03da5c102b0106e37. Closing.
