### ISSUE TITLE
Option / Flag to disable adding shortcuts to NTP

### ISSUE THREAD

**Issue by thisiskarsten** [Eloston/ungoogled-chromium#1323]
**Is your feature request related to a problem? Please describe.**
The blank start page provided by ungoogled chromium does not allow disabling website shortcuts in New Tab Page, like Chrome did.

Disabling flags **#ntp-repeatable-queries** or **#ntp-modules** does not work.

**Describe the solution you'd like**
I would like **an option in Settings** or a **flag** to disable this specific feature.

**Describe alternatives you've considered**
I've already considered using extensions like Momentum or Tabliss to replace the blank NTP but I don't think this is a great solution.

**Additional context**
None.

**Comment by Ahrotahn** [comment]
Launching with `--disable-top-sites` should remove them.
