### ISSUE TITLE
Zombie processes using 100% CPU after tab closed

### ISSUE THREAD

**Issue by dev-kittens** [Eloston/ungoogled-chromium#1324]
**Describe the bug**
When I close tabs, sometimes there will be "zombie processes" created with the URL of the closed tab.

**To Reproduce**
I don't have very good reproduction steps, as it happens randomly, but:
1. Close a tab.
2. Watch as a process is created with that tab name, and that it uses 100% of a CPU core.
3. I will need to `kill -9` the process to remove it. It does not respond to `SIGTERM`.

**Expected behavior**
I expect to not see any abnormal behaviour when closing a tab.

**Screenshots**
![image](https://cdn.discordapp.com/attachments/757362274796044391/798415079594393620/unknown.png)

**Environment:**
 - OS/Platform and version: Arch Linux, kernel 5.10.4-artix2-1
 - ungoogled-chromium version: Version 87.0.4280.88 (Installed from AUR)

**Comment by guest271314** [comment]
Have you disabled chrome://settings/content/backgroundSync?

**Comment by dev-kittens** [comment]
I disabled that and it's not happening anymore. Thank you!
