### ISSUE TITLE
Unicode does not displayed correctly

### ISSUE THREAD

**Issue by tmvkrpxl0** [Eloston/ungoogled-chromium#1326]
**Describe the bug**

**To Reproduce**
1. Go to 'https://lingojam.com/GlitchTextGenerator'
2. Generate any text, and most of text is squares

**Expected behavior**
I expected it to generate glitched text, but there was only squares and part of original text

**Screenshots**
![image](https://user-images.githubusercontent.com/41675181/104491797-15350e80-5616-11eb-9cc9-d42a1131b937.png)

**Environment (please complete the following information):**
 - OS/Platform and version:Linux mint 20
 - ungoogled-chromium version:84.0.4147.135

**Additional context**
I'm pretty sure this is not font issue with my pc, since it was displayed correctly on firefox

**Comment by SugaryHull** [comment]
It sounds to me like ungoogled-chromium is blocking font downloads and Firefox isn't, which is why the crazy text renders properly in the latter
