### ISSUE TITLE
Problem building version 55 in Docker container

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#133]
(Continuation of https://github.com/Eloston/ungoogled-chromium/issues/129#issuecomment-264840089)

@lenormf For some reason, `buildlib` is using the Linux static builder instead of the Debian stretch builder. You chopped off the beginning of the log, but I can see that from this line:
```
2016-12-05 08:56:05,234 - DEBUG: Appending resources/linux_static/gn_flags
```
(Notice `linux_static`. It's only used in the Linux static builder)

Is your Docker container not a normal Debian stretch installation? I'm using the `distro` Python module to detect what distribution it's running on.

You can specify the Debian stretch builder explicitely by modifying `build.py` as follows:
* Add `import buildlib.debian` below `import buildlib`
* Replace `buildlib.get_builder()` with `buildlib.debian.DebianStretchBuilder()`

**Comment by lenormf** [comment]
I hadn't realized I had hit a bug, I was just making a comment about the workaround I had to do.

The build finished, it produced a `ungoogled-chromium_55.0.2883.75-1_linuxstatic.tar.xz` archive.

As for the build container, it's a [buildpack-deps](https://github.com/docker-library/buildpack-deps/blob/11492c68d993221fd5cd4d8a980354634fc165dd/stretch/Dockerfile) official image, plus the dependencies I installed manually.

I'm building the project with the modifications you recommend -a patch would have been nice ;)- I'll let you know how that goes.

**Comment by lenormf** [comment]
The build has ended, all the packages seem to have been successfully generated (haven't tested them yet). I've also kept the full build log if needed.

**Comment by Eloston** [comment]
`distro` gives me different values for those functions even though our `os-release` file is the same. Which probably means that `distro` is using another method to detect the distribution; maybe `lsb_release`?

Could you try [the latest master version of distro.py](https://raw.githubusercontent.com/nir0s/distro/master/distro.py) and report back what you get?

FYI, here's what I get with the latest version:
```
Python 3.5.2+ (default, Nov 22 2016, 01:00:20) 
[GCC 6.2.1 20161119] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distro
>>> distro.linux_distribution()
('Debian GNU/Linux', 'testing', 'stretch')
>>> distro.info()
{'like': '', 'version': 'testing', 'codename': 'stretch', 'id': 'debian', 'version_parts': {'major': '', 'build_number': '', 'minor': ''}}
```

**Comment by lenormf** [comment]
I fixed it by installing the `lsb-release` package, even though there wasn't apparently any need for it. I reported the [bug](https://github.com/nir0s/distro/issues/152) upstream.

**Comment by lenormf** [comment]
The build finished, the proper dynamic builder has been selected and the packages were built. [Log here](https://my.mixtape.moe/ucapdg).

**Comment by Eloston** [comment]
@lenormf Good to hear. I'm marking this as invalid since it's more of a `distro` module issue.
