### ISSUE TITLE
Patreon pages are blank

### ISSUE THREAD

**Issue by davidhealey** [Eloston/ungoogled-chromium#1330]
Visiting a patreon page it loads very briefly then the whole page turns white. It doesn't happen in Firefox or Chrome.

This page for example - https://www.patreon.com/technologyconnections

**Comment by SugaryHull** [comment]
Your given example renders just fine in my Debian build of 87.0.4280.141-1.unportable1 with the default configuration

**Comment by davidhealey** [comment]
Perhaps the issue has been resolved in a newer version. I'm using the OBS build which is v84

**Comment by SugaryHull** [comment]
It's entirely possible. If possible, try testing it against a later build

**Comment by davidhealey** [comment]
That is the most recent binary available for my OS.

**Comment by SugaryHull** [comment]
What OS are you using?

**Comment by davidhealey** [comment]
Debian Buster

**Comment by SugaryHull** [comment]
You can try the binaries that I have uploaded [here](https://github.com/SugaryHull/ungoogled-chromium-binaries/releases/tag/87.0.4280.141-1.unportable1).

**Comment by davidhealey** [comment]
I get a message that installing it will break an existing package. I'll leave it for now and continue to use Firefox to access Patreon until a new version is available.

**Comment by SugaryHull** [comment]
> I get a message that installing it will break an existing package. I'll leave it for now and continue to use Firefox to access Patreon until a new version is available.

In that case, it might be good to close this issue until OBS building is resumed.

**Comment by Eloston** [comment]
> I get a message that installing it will break an existing package. I'll leave it for now and continue to use Firefox to access Patreon until a new version is available.

Make sure to install all the proper `.deb` files mentioned [in the ungoogled-chromium-debian README](https://github.com/ungoogled-software/ungoogled-chromium-debian/tree/unportable#installing)

**Comment by davidhealey** [comment]
That lead me to the appImage (didn't know it existed before!). I tried it out but I'm still getting the blank Patreon pages. I'm guessing it must be something in my config or profile. I'll experiment some more and see if I can figure out what's going on.
