### ISSUE TITLE
TouchID for Web Authentication (Mac)

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Eloston/ungoogled-chromium#1331]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't use TouchID to log into my favorite websites with ungoogled-chromium.

**Describe the solution you'd like**
Add the same TouchID API that Brave uses (and probably Chrome too).

**Describe alternatives you've considered**
Make a own API for TouchID

**Additional context**
I'm not sure if TouchID is a Google API

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-macos](https://github.com/ungoogled-software/ungoogled-chromium-macos)
