### ISSUE TITLE
Every download is marked as "This type of file can harm your computer".

### ISSUE THREAD

**Issue by rodrigodzilla** [Eloston/ungoogled-chromium#1337]
Downloading any type of file displays the "This type of file can harm your computer" message every time. It's still possible to download the file but with many files it's bothersome.
![image](https://user-images.githubusercontent.com/77561651/104831096-3428e000-5864-11eb-9f89-ae8ad2becfae.png)

**Comment by dennyamarojr** [comment]
Probably a flag is enforced that cause this message, don't know which flag it is

**Comment by ahtaarra** [comment]
I don't see this type of warning dialogue on ungoogled-hromium v87.0.4280.88-3 which I built from AUR without any own modifications (but saved a bunch of settings afterwards).

Try enabling and disabling the option for asking for file location on each download and see whether that makes any difference. Also, why not include the version number?

**Comment by blackbeardth** [comment]
facing the same issue on UC Version 87.0.4280.141

**Comment by blackbeardth** [comment]
> I don't see this type of warning dialogue on ungoogled-chromium v87.0.4280.88-3 which I built from AUR without any own modifications (but changed a bunch of settings after installing).
> 
> Try enabling and disabling the option for asking for file location on each download and see whether that makes any difference. Also, why not include the version number?

tried both but message still shows on UC Version 87.0.4280.141

**Comment by xNaCly** [comment]
> Version 87.0.4280.141 (Developer Build) (64-bit)
Same issue here: 
![image](https://user-images.githubusercontent.com/47723417/105185112-72f2ba80-5b30-11eb-946b-3f7d717507ff.png)

**Comment by rodrigodzilla** [comment]
> I don't see this type of warning dialogue on ungoogled-chromium v87.0.4280.88-3 which I built from AUR without any own modifications (but changed a bunch of settings after installing).
> 
> Try enabling and disabling the option for asking for file location on each download and see whether that makes any difference. Also, why not include the version number?

My apologies, I'm using 87.0.4280.141-1 (64-bit)

**Comment by rodrigodzilla** [comment]
> Try enabling and disabling the option for asking for file location on each download and see whether that makes any difference. 

Same issue. After selecting the destination it's still appearing on the downloads bar.

>Also, why not include the version number?

My apologies, I'm using 87.0.4280.141-1 (64-bit)

**Comment by ahtaarra** [comment]
I have used nix package manager (on my Arch Linux install on which I had previously built and installed v87.0.4280.88-3 from AUR) to install ungoogled-chromium v87.0.4280.141 but I'm unable to reproduce this warning with the same 'profile' (or 'person').

Moreover, I also tried creating a new 'person' using the latter build (and tried it once again after pressing the 'clear all' button at the chrome://flags page on another fresh 'person' even though no flags were seemingly modified) and after that file-picker was opened and I selected the destination and the filename, there was no such warning.

**Comment by Ahrotahn** [comment]
I don't encounter this on arch.  

@rodrigodzilla, @blackbeardth, @xNaCly:  What platform are you on?  Whose build are you using?  Does the same thing happen with a new chromium profile?

I'm pretty sure that this is part of the safebrowsing stuff that is removed, so something seems to have gone wrong with the build you're using.

**Comment by xNaCly** [comment]
@Ahrotahn Im on newest windows, using the newest ug build and its happening with every download.

**Comment by dennyamarojr** [comment]
This is related to Safe browsing, I'm make some research and it seems the fix is apply regedit tweak to Safe Browsing, to Chromium (that applies to ungoogle chromium too, that could fix the issue)

**Comment by rodrigodzilla** [comment]
The issue is happening on Windows 10. I'll soon try to get the latest ungoogled-chromium release on my other laptop using Manjaro and report if the issue still happens.

**Comment by rodrigodzilla** [comment]
Fedora 33, no warning appeared. Seems likely a Windows only issue.

**Comment by dennyamarojr** [comment]
For Windows users, open CMD as admin and them paste this command:
reg add "HKLM\SOFTWARE\Policies\Chromium" /v "SafeBrowsingProtectionLevel" /t REG_DWORD /d 0 /f

After that, open ungoogled chromium, and in the address bar type chrome://policy and check if the SafeBrowsingProtectionLevel looks like this screenshot

![image](https://user-images.githubusercontent.com/36896116/106001813-51ea1680-60a8-11eb-8b93-0dbe8e002ae4.png)

**Comment by J4gQBqqR** [comment]
> For Windows users, open CMD as admin and them paste this command:
> reg add "HKLM\SOFTWARE\Policies\Chromium" /v "SafeBrowsingProtectionLevel" /t REG_DWORD /d 0 /f
> 
> After that, open ungoogled chromium, and in the address bar type chrome://policy and check if the SafeBrowsingProtectionLevel looks like this screenshot
> 
> ![image](https://user-images.githubusercontent.com/36896116/106001813-51ea1680-60a8-11eb-8b93-0dbe8e002ae4.png)

Tried on Windows 10 installation, does not work.

This is prompt for download really annoying.

**Comment by notwa** [comment]
Same problem here. I'm using [this release (87.0.4280.141-1)](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/87.0.4280.141-1) on Windows 10.0.18363. I tried the cmd to add the "SafeBrowsingProtectionLevel" registry key, and while it did appear in `chrome://policy`, it did not affect the issue. I also tried backing up `%LOCALAPPDATA%\Chromium` and reinstalling, but the issue persists.

**Comment by dennyamarojr** [comment]
> > For Windows users, open CMD as admin and them paste this command:
> > reg add "HKLM\SOFTWARE\Policies\Chromium" /v "SafeBrowsingProtectionLevel" /t REG_DWORD /d 0 /f
> > After that, open ungoogled chromium, and in the address bar type chrome://policy and check if the SafeBrowsingProtectionLevel looks like this screenshot
> > ![image](https://user-images.githubusercontent.com/36896116/106001813-51ea1680-60a8-11eb-8b93-0dbe8e002ae4.png)
> 
> Tried on Windows 10 installation, does not work.
> 
> This is prompt for download really annoying.

I'm using Windows 10 and works, did you try to use the code with CMD as admin?

**Comment by dennyamarojr** [comment]
Here's some screenshots

Using the code: 
![image](https://user-images.githubusercontent.com/36896116/106141007-610eaa00-6124-11eb-82c6-1a8229b561a6.png)

After press enter:
![image](https://user-images.githubusercontent.com/36896116/106141072-7b488800-6124-11eb-864e-7c3b22192dd0.png)

My Windows 10 version and build:
![image](https://user-images.githubusercontent.com/36896116/106141191-9fa46480-6124-11eb-87d3-dfbde2b9ff9f.png)

The command: 

reg add "HKLM\SOFTWARE\Policies\Chromium" /v "SafeBrowsingProtectionLevel" /t REG_DWORD /d 0 /f

**Comment by dennyamarojr** [comment]
And here's the screenshot from the browser:

![image](https://user-images.githubusercontent.com/36896116/106141475-fc078400-6124-11eb-9f3b-c1ebe7267f69.png)

**Comment by J4gQBqqR** [comment]
> Here's some screenshots
> 
> Using the code:
> ![image](https://user-images.githubusercontent.com/36896116/106141007-610eaa00-6124-11eb-82c6-1a8229b561a6.png)
> 
> After press enter:
> ![image](https://user-images.githubusercontent.com/36896116/106141072-7b488800-6124-11eb-864e-7c3b22192dd0.png)
> 
> My Windows 10 version and build:
> ![image](https://user-images.githubusercontent.com/36896116/106141191-9fa46480-6124-11eb-87d3-dfbde2b9ff9f.png)
> 
> The command:
> 
> reg add "HKLM\SOFTWARE\Policies\Chromium" /v "SafeBrowsingProtectionLevel" /t REG_DWORD /d 0 /f

Hi, I am doing exactly the same thing, and after doing so, I can see the policy value is 0 inside of my browser. But I still see those download alerts.

**Comment by dennyamarojr** [comment]
> > Here's some screenshots
> > Using the code:
> > ![image](https://user-images.githubusercontent.com/36896116/106141007-610eaa00-6124-11eb-82c6-1a8229b561a6.png)
> > After press enter:
> > ![image](https://user-images.githubusercontent.com/36896116/106141072-7b488800-6124-11eb-864e-7c3b22192dd0.png)
> > My Windows 10 version and build:
> > ![image](https://user-images.githubusercontent.com/36896116/106141191-9fa46480-6124-11eb-87d3-dfbde2b9ff9f.png)
> > The command:
> > reg add "HKLM\SOFTWARE\Policies\Chromium" /v "SafeBrowsingProtectionLevel" /t REG_DWORD /d 0 /f
> 
> Hi, I am doing exactly the same thing, and after doing so, I can see the policy value is 0 inside of my browser. But I still see those download alerts.

Did you go to chrome://policy and them click reload policies?

**Comment by dennyamarojr** [comment]
Because here is working and no messaging, The only that I add later was specified a Secure DNS, nothing more 

here's the screenshot:

![image](https://user-images.githubusercontent.com/36896116/106141751-73d5ae80-6125-11eb-8f30-9bc2af762211.png)

**Comment by J4gQBqqR** [comment]
No, I didn't, I restarted my browser. Would that be enough?

**Comment by dennyamarojr** [comment]
> No, I didn't, I restarted my browser. Would that be enough?

I test here and it seems, need to reload the policies manually, I remove all the policies and add the command, the message still. (need update chrome://policy manually)

**Comment by dennyamarojr** [comment]
Here's the screenshot:

![image](https://user-images.githubusercontent.com/36896116/106142219-12faa600-6126-11eb-8d87-e3efd00bba4b.png)

**Comment by J4gQBqqR** [comment]
I see, I'll reload manually this morning and feedback. Thanks!

**Comment by dennyamarojr** [comment]
Ok, check here and it seems another thing is interfering, will try add the secure dns to see if fix the issue

**Comment by dennyamarojr** [comment]
> Ok, check here and it seems another thing is interfering, will try add the secure dns to see if fix the issue

After use secure dns still appearing , I will try the other settings for Safe browsing here to see if the message goes away.

**Comment by dennyamarojr** [comment]
But probably is because missing a file download_file_types.pb in C:\Users\%USERPROFILE%\AppData\Local\Chromium\User Data\FileTypePolicies

Not sure, if the file really need, but all the topics I search show for this location too.

**Comment by Ph0rk0z** [comment]
I have the same issue with the latest x64 windows build and adding the policy does nothing. Furthermore I can't seem to choose download location whether the setting is on or off.

**Comment by sharpden** [comment]
As temporary workaround one can replace in file `ungoogled-chromium-windows\build\src\components\download\internal\common\download_item_impl.cc` string `danger_type_ = danger_type;` in function `DownloadItemImpl::SetDangerType` to `danger_type_ = DOWNLOAD_DANGER_TYPE_NOT_DANGEROUS;` and then re-run build

**Comment by J4gQBqqR** [comment]
This currently cannot be resolved by end user. Not every user has the capability to build from source. I am switching back to the older version. Will wait and see if this got improved in the future.

I guess issues like this are one of the downsides that we have to bear when using third party chromium based browser. Lack of settings/preference syncing is another downside though...

**Comment by icy0007** [comment]
Hi Guys
Microsoft is making contracts with sofware companies to render pirate or copied software useless.
they sell a sever with  software for direct contact between both , microsoft &  the software company.
software to render the software of that software company is directly incorporated into Windows 10,
starting with version 20H2 , see size of the windows isos
Win10_2004_English_x64.iso	5,268,953,088	07/25/2020 13:13	-a--
Win10_20H2_English_x64.iso	6,155,782,144	10/21/2020 20:45	-a--
Win10_20H2_v2_English_x64.iso	6,221,846,528	01/30/2021 18:58	-a--
I am now going to use Windows 7, remove all remote,firewall & defender.
Look at all the updates,most of them are there to assure connection with remote
Have a look at this :
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\mpssvc\Parameters\AppCs\AppCs firewall
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Defaults\FirewallPolicy\FirewallRules
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\FirewallRules
There are more than 2000 rules in a full windows 10, this is not normal
this is to assure there is always connection to Windows servers
Windows 10 is an enormous spy machine,
Everything what is used onto your computer is traced
Now they are going to play policeman
So try Windows 7 or 8 to see if this is also the case
icy

**Comment by CodeSlinger69** [comment]
This appears to still be an issue in the 88.0.4324.150 builds.

**Comment by J4gQBqqR** [comment]
@Eloston Could you help us check if this is a valid fix to be done in the source code?

> As temporary workaround one can replace in file `ungoogled-chromium-windows\build\src\components\download\internal\common\download_item_impl.cc` string `danger_type_ = danger_type;` in function `DownloadItemImpl::SetDangerType` to `danger_type_ = DOWNLOAD_DANGER_TYPE_NOT_DANGEROUS;` and then re-run build


Windows build is having this issue for a month now.

**Comment by icy0007** [comment]
Hi Eleston
it is still happening on windows 7 & 8.1
icy

**Comment by YasirAnqa** [comment]
Still not fixed with version 88.0.4324.150. On Windows 10.

**Comment by TontyTon** [comment]
same here not fixed in v88.0.4324.150 on Windows 10.

Also, there is no safe browsing toggle in settings, maybe in chromium they made the rules like - 'dangerous unless stated otherwise'.

**Comment by CodeSlinger69** [comment]
Build 88.0.4324.182 continues to exhibit this same problem. 

87.0.4280.67 is still the latest build that works correctly.

**Comment by J4gQBqqR** [comment]
This issue has been plaguing Windows build for months, will it even get noticed by the developer?
Is this repository/project still actively maintained?

**Comment by Kroissan** [comment]
I also have the issue, 88.0.4324.182 windows 10. The registery thing doesnt do anything unfortunatly. I searched in chrome flags but didnt find anything related to download or safe browsing. The antivirus seems to be deeply implemented in chrome, tho i know nothing about chromium, just adding for notification.

**Comment by mooms06** [comment]
.

**Comment by achesnok** [comment]
Have the same issue. windows 7, Version 88.0.4324.182 (Developer Build, ungoogled-chromium) (64-bit).

**Comment by Ph0rk0z** [comment]
I tried to add SafeBrowsingEnabled to false. Chrome says "This policy is blocked". BTW on windows 8 and probably 7 the policies moved to Wow6432Node in the registry. At least the password saving works again.

**Comment by CodeSlinger69** [comment]
This appears to be fixed in 89.0.4389.90. Thanks developers!

**Comment by mooms06** [comment]
Yes, I confirm.

**Comment by rodrigodzilla** [comment]
Can confirm that the issue has been fixed, thanks for all the hard work! Closing.
