### ISSUE TITLE
Legacy Nvidia Driver 340 and Nouveau too

### ISSUE THREAD

**Issue by Ph0rk0z** [Eloston/ungoogled-chromium#1339]
Been trying to get this NV96 based card working on chromium to only limited success. Figured people here would know more about how these pieces fit.

On ubuntu 20.0.4

Using ungoogled 84 and below I can get acceleration working on nouveau but the performance is poor. Nouveau hard locks the system when using suspend, it sucks. The latest unportable v87 breaks this whether using --use-gl=egl or desktop or nothing. Chrome doesn't detect any decode-able formats under chrome://gpu and MojoVideoDecoder tries then falls back.

Using the nvidia-340 legacy driver on 84 and below results in the GPU being undetected. If --use-gl=egl is set all features come back. Unfortunately no formats are detected again and Mojo doesn't even try.

Version 87 works the same with either flag or none. No formats are detected but at least regular acceleration is.

vainfo returns all supported formats as it should. With nouveau I have a VaProfileNone, with proprietary I don't have this listed. Read that chrome requires this profile present in order to work with vaapi on the arch forums can't find any patched versions on the ubuntu side. Have yet to try the arch stack, maybe it's better?

Has anyone gotten legacy nvidia working?

**Comment by Ph0rk0z** [comment]
Arch Update:

Building https://aur.archlinux.org/packages/libva-vdpau-driver-chromium/ and using chaotic-aur ungoogled v88 leads to gpu detected and H264 Main + High getting detected. No flags used.

Unfortunately when it goes to decode MojoVideoDecoder drops off due to VDA 4 error

Guess I have to use windows or throw the machine out of one.

**Comment by PF4Public** [comment]
I hope your issue has been resolved, otherwise please let us know.
Closing this issue for now.
