### ISSUE TITLE
"Keep" and "Discard" buttons in the Downloads page (Ctrl + J) do not do anything

### ISSUE THREAD

**Issue by Ceruleous** [Eloston/ungoogled-chromium#1341]
1. Download any file to the computer. As in #1337, file will be marked unsafe.
2. Press Ctrl + J to bring up the Downloads page
3. Click "Keep" or "Discard"
4. Nothing happens, downloaded file stays as .crdownload in the file system
https://user-images.githubusercontent.com/2577042/105154376-72fcb580-5b44-11eb-880c-c00685c8a2dd.mp4

 - Windows 10 64-bit
 - ungoogled-chromium Version 87.0.4280.141

**Comment by blackbeardth** [comment]
i am facing the same issue

**Comment by blackbeardth** [comment]
can i turn it off?

**Comment by TontyTon** [comment]
Same issue on v88.0.4324.150 on Windows 10

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
