### ISSUE TITLE
Building in OS/Xcode

### ISSUE THREAD

**Issue by Sam29556** [Eloston/ungoogled-chromium#1347]
In the building instructions it says that XCode needs to be open during the build.  When I open Xcode, it asks me to choose a template for the project.  Beyond selecting "App", can someone tell me how I should configure this (Interface, Life cycle, etc.)?

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-macos](https://github.com/ungoogled-software/ungoogled-chromium-macos)
