### ISSUE TITLE
Make Ubuntu 14.04 LTS choose the static build automatically

### ISSUE THREAD

**Issue by 9Morello** [Eloston/ungoogled-chromium#135]
Currently, if you run buildlib on Ubuntu 14.04, it will attempt to build an 16.04 package. You need to edit it to make it go for the static build.

Perhaps its a good idea to make it run `install-build-deps.sh` too.

Alternatively, it could be made so the user can run `build.py` with an argument to select the static build.

**Comment by Eloston** [comment]
1341b6dc50305a603d26d71aacc94b1504127886
