### ISSUE TITLE
Problem in build in OS Big Sur

### ISSUE THREAD

**Issue by Sam29556** [Eloston/ungoogled-chromium#1350]
I've tried multiple times to build this in Big Sur, but I keep getting the following error.  Any idea what's wrong?

INFO: Path has no substitutions: tools/md_browser/base.css
+ cp /Users/myusername/ungoogled-chromium-macos/ungoogled-chromium/flags.gn /Users/myusername/ungoogled-chromium-macos/build/src/out/Default/args.gn
+ cat /Users/myusername/ungoogled-chromium-macos/flags.macos.gn
+ cd /Users/myusername/ungoogled-chromium-macos/build/src
+ ./tools/gn/bootstrap/bootstrap.py -o out/Default/gn --skip-generate-buildfiles
ninja: Entering directory `/Users/myusername/ungoogled-chromium-macos/build/src/out/Release/gn_build'
[179/192] CXX src/gn/visibility.o
../../../tools/gn/src/gn/visibility.cc:87:10: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
  return std::move(res);
         ^
../../../tools/gn/src/gn/visibility.cc:87:10: note: remove std::move call here
  return std::move(res);
         ^~~~~~~~~~   ~
1 warning generated.
[192/192] LINK gn
+ ./out/Default/gn gen out/Default --fail-on-unused-args
ERROR at //build/config/mac/mac_sdk.gni:89:19: Script returned non-zero exit code.
_mac_sdk_result = exec_script(script_name, sdk_info_args, "scope")
                  ^----------
Current dir: /Users/myusername/ungoogled-chromium-macos/build/src/out/Default/
Command: python /Users/myusername/ungoogled-chromium-macos/build/src/build/config/mac/sdk_info.py macosx
Returned 1.
stderr:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Traceback (most recent call last):
  File "/Users/myusername/ungoogled-chromium-macos/build/src/build/config/mac/sdk_info.py", line 161, in <module>
    FillXcodeVersion(settings, args.developer_dir)
  File "/Users/myusername/ungoogled-chromium-macos/build/src/build/config/mac/sdk_info.py", line 70, in FillXcodeVersion
    '-version']).decode('UTF-8').splitlines()
  File "/Users/myusername/.pyenv/versions/2.7.13/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['xcodebuild', '-version']' returned non-zero exit status 1

See //components/nacl/features.gni:9:3: whence it was imported.
  import("//build/config/mac/mac_sdk.gni")
  ^--------------------------------------
See //BUILD.gn:20:1: whence it was imported.
import("//components/nacl/features.gni")
^--------------------------------------

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-macos](https://github.com/ungoogled-software/ungoogled-chromium-macos)
