### ISSUE TITLE
Cookies are not saved

### ISSUE THREAD

**Issue by Suncatcher** [Eloston/ungoogled-chromium#1352]
**Describe the bug**

**To Reproduce**
1. Go to 'stackstorage.com' account, Github.com, whatever
2. Login into account
3. Close the browser
4. After opening your login is reset and you need log again

**Expected behavior**
It should save the session

**Screenshots**
it prompts with this weird auth popup
![image](https://user-images.githubusercontent.com/6388034/105643498-e4b46680-5e98-11eb-9e7b-7b18c6cf7bcb.png)
and if I cancel it it shows this
![Untitled](https://user-images.githubusercontent.com/6388034/105643568-45dc3a00-5e99-11eb-8a97-a5703bf592ac.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 20H2
 - ungoogled-chromium version: 87.0.4280.141 (64-bit)

**Additional context**
The same behavior I observe with Github.com, it looses the session after browser restart. What is wrong with your cookies?

**Comment by networkException** [comment]
Have you disabled `Clear cookies and site data when you quit Chromium` in `chrome://settings/cookies`? By default ungoogled-chromium has that enabled

**Comment by Suncatcher** [comment]
Yep, that's it. I didn't know this is a default setting. Sorry, I didn't read the FAQ. Though, it's a little bit weird to do this as default.

**Comment by resolritter** [comment]
Ugh... Is there a way to turn that off with a CLI switch or something? I don't want this default

I tried to search the code for `"leave"`, `"quit"`, etc to figure out which patch enables this, but couldn't. @Eloston do you happen to know where it is?

**Comment by Eloston** [comment]
@resolritter Probably this one: https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/iridium-browser/prefs-only-keep-cookies-until-exit.patch

**Comment by solarkraft** [comment]
So is it a remnant from incorporating another browser's patches?

Can this please be removed? This default is directly contrary to the stated goal of retaining the default Chromium experience as closely as possible. This is the main reason it's *not* a drop-in replacement for Chromium.

**Comment by solarkraft** [comment]
@Eloston So is it a remnant from incorporating another browser's patches?

Can this please be removed? This default is directly contrary to the stated goal of retaining the default Chromium experience as closely as possible. This is the main reason it's *not* a drop-in replacement for Chromium. I can make another issue with a bit more elaborate reasoning, but it seems to me like this would be clear enough.

**Comment by PF4Public** [comment]
> Can this please be removed?

What is the problem of changing this in profile? It would persist.

**Comment by axinux** [comment]
<img width="1720" height="910" alt="Image" src="https://github.com/user-attachments/assets/b93234a0-496a-4e11-bc92-54736b6ab82a" />

I very much apologise for opening this up again but where would that be?

**Comment by PF4Public** [comment]
@axinux The patch in question was removed in https://github.com/ungoogled-software/ungoogled-chromium/pull/2681
