### ISSUE TITLE
Add an option to completely disable chrome:// suggestions in the search bar

### ISSUE THREAD

**Issue by ungubajue90k** [Eloston/ungoogled-chromium#1356]
Hello,

I use this latest ungoogled-chromium android version
https://github.com/ungoogled-software/ungoogled-chromium-android/releases/tag/87.0.4280.141-2-extensions

If I type `a`, `c` or `ch` in the search bar immediately these suggestions appear: 

- chrome://chrome-urls/
- chrome://version/

![IMG_20210126_160418](https://user-images.githubusercontent.com/77856086/105863201-eee97880-5ff0-11eb-9055-2423f8b77e9b.jpg)
![IMG_20210126_160758](https://user-images.githubusercontent.com/77856086/105863224-f446c300-5ff0-11eb-954f-5a8c8a41052a.jpg)

Please add an option to completely disable the chrome:// suggestions in the search bar. I want to decide which search suggestions I want in the search bar.

**Comment by wchen342** [comment]
Adding to what the OP has said, I think this should be included in the base patchset since it is not an Android specific feature.

**Comment by Ahrotahn** [comment]
I recall playing with the builtin suggestions when working on the omnibox filtering patch.  
That one is treated a bit differently since it works even with suggestions turned off.  It might be something that would need to have it's own flag instead of being rolled into the existing one.  I'll experiment with it over the week as I get time.

**Comment by Luka-Filipovic** [comment]
It think [this file](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ui/webui/chrome_web_ui_controller_factory.cc;drc=aafcff480d10ea649036833cb4052f127d733143;l=485) lists of internal pages that should appear in omnibox. Try to force it to always return `nullptr`.

**Comment by Ph0rk0z** [comment]
I actually like this. Showed me all the chrome:// urls
