### ISSUE TITLE
Spellcheck dicts troubles

### ISSUE THREAD

**Issue by Suncatcher** [Eloston/ungoogled-chromium#1357]
**Describe the bug**

**To Reproduce**
1. First and very stupid problem: I cannot find Dictionaries folder nowhere in Chromium profile, but English spellcheck works. How that could be?
2. Secondly, i tried the method [from here](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-fix-the-spell-checker), but it doesn't work. The bdic is not recognized as archive.
Something changed? 

**Expected behavior**
Dicts installation as per the manual should work

**Screenshots**
![image](https://user-images.githubusercontent.com/6388034/105892758-f6be1280-601a-11eb-8e3b-a28aff69152f.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 20H2
 - ungoogled-chromium version:  87.0.4280.141 (Official Build) (64-bit)

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
