### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by greatchromez** [Eloston/ungoogled-chromium#1358]
Could a auto-updater feature for ungoogled-chromium be implemented? It would save having to manually download/install each update from github.

Ideally it would appear in chrome://settings/help/ under 'About Chromium'.

Maybe it could include an option to rollback to the previous version and the ability to pause updates?
![1](https://user-images.githubusercontent.com/75350973/105930698-e705f480-6041-11eb-809b-5296483eed5f.PNG)

**Comment by KeithIMyers** [comment]
The biggest problem I can see with that is it would need to do a call-home
to check the version which would allow a server to capture IP addresses,
Platform and a few other things that many users would like to not have.

**Comment by PF4Public** [comment]
Linux platforms usually employ some kind of package manager, therefore the need for auto-updater is limited to those platforms, which do not, Windows for example. Please file this issue with the platform repo, that you deem might benefit from auto-updater.

**Comment by Francewhoa** [comment]
For those facing this challenge with extensions, as a temporary workaround, this publication suggests two methods to manually update extensions for ungoogled-chromium at https://avoidthehack.com/manually-install-extensions-ungoogled-chromium

https://archive.ph/SAkWb

**Comment by Francewhoa** [comment]
Below, under "Resolution", is the easier way that I know of to get automatic update of ungoogled-chromium on Linux. I used it for months now. It works really well. Very stable. And more importantly, more secure.

## Challenge

About an auto-updater for ungoogled-chromium. As you probably know, the challenge is that the maintainers of ungoogled-software have chosen to focus on ungoogled-software not on an auto-updater. I support this choice. As various other independent projects are able to auto-update ungoogled-chromium. In other words, you are free to pick and choose any auto-update option to your liking. Also, in turn, I bet that the workload of each project is more realistic.

## Step Auto-Update Ungoogled-Chromium

1. Use [**this Flatpak**](https://flathub.org/apps/details/com.github.Eloston.UngoogledChromium) to install Ungoogled-Chromium
2. Use Flatpak to automatically update Ungoogled-Chromium
3. Use this [**Chromium Web Store**](https://github.com/NeverDecaf/chromium-web-store) extension to get semi-automated update for extensions

If you are not familiar with **Flatpak** or **Chromium Web Store,** the below detailed steps and screenshot might be of interest

## Detailed Steps To Auto-Update Ungoogled-Chromium

1. This first step is optional, but if you presently already have an installed Ungoogled-Chromium, I suggest to back up any valuable data. For example, but not limited to, export your bookmarks.
         
1. Install **Flatpak**. To do so, using any navigator to your liking such as Ungoogled-Chromium or [Firefox](https://mozilla.org/firefox), go to https://flatpak.org/setup/ Click on the appropriate big button for your falvour of Linux. Find your action on this setup page. If you are not familiar with basic command lines, find those [steps with screenshots to open a Terminal/Console](https://ubuntu.com/tutorials/command-line-for-beginners#3-opening-a-terminal).

1. This first step is optional. After **Flatpak** is installed, if you presently already have an installed Ungoogled-Chromium, I suggest uninstalling it now. This will reduce the risk of conflicting data and confusion. In the future, after you're done with all the steps below, you'll have only one Ungoogled-Chromium installed. Which is much easier and faster to update then two.

1. Using Terminal, execute the below command line to install the Ungoogled-Chromium from Flathub. 

          flatpak install flathub com.github.Eloston.UngoogledChromium
   
      * Notes:

         * Think of Flathub as the repository of Flatpak. Which are packages. 
            
         * The Flatpak maintainer for Ungoogled-Chromium pulls data from the original repository at https://github.com/ungoogled-software/ungoogled-chromium
         
         * Those 2 commands line comes from the bottom of this page at https://flathub.org/apps/details/com.github.Eloston.UngoogledChromium

1. Using Terminal, execute the below command line to open **Ungoogled-Chromium**.
   
          flatpak run com.github.Eloston.UngoogledChromium

      * Note:

         * Alternatively, if your Linux uses GNOME, then using GNOME click on the **Ungoogled-Chromium** icon to open it. No need to execute this command above.

1. Install **chromium-web-store** using those steps at https://avoidthehack.com/manually-install-extensions-ungoogled-chromium

1. Using **Ungoogled-Chromium**, display the **chromium-web-store** extension button in the toolbar of **Ungoogled-Chromium**. In other words, pin it.

1. Each time you open **Ungoogled-Chromium**, the extension **chromium-web-store** will automatically notify you when an update is available for an installed extension. In this screenshot below, the red square with the number one shows this.
![image](https://user-images.githubusercontent.com/119942/218345295-f8e232fa-fa2d-4d7d-aef3-92cee1185e53.png)

1. To semi-automatically update **Ungoogled-Chromium** extensions, in just 3 clicks per extension:

    1. Click on the  **chromium-web-store** extension
    2. Using the drop down menu, click on the appropriate extension to update it. The same screenshot above show this big button for the extension **uBlock Origin**.
    3. Click on the **Add extension** button. Doing so will update the extension to its newer version.

1. Done. You have successfully installed an auto-update for **Ungoogled-Chromium** and a semi auto-update for its extensions :)
