### ISSUE TITLE
Use secure DNS can't be enabled because of "managed browser"

### ISSUE THREAD

**Issue by TheSilencedOne** [Eloston/ungoogled-chromium#1359]
**Describe the bug**
This bug doesn't allow the use of "Use secure DNS"

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Privacy'
3. Scroll down to 'Use secure DNS'
4. See error this setting is disabled on managed browsers

**Expected behavior**
I expected this option to function properly
**Screenshots**
![Screenshot_20210126-212903](https://user-images.githubusercontent.com/78061111/105934117-9086bf00-601d-11eb-8cf5-0ebf2cbf3d38.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Android 7.1.2 (FireOS 6.3.1.5)
 - ungoogled-chromium version: 87.0.4280.141

**Additional context**
This issue seems to be a wide spread chromium issue as said in this Bromite issue:https://github.com/bromite/bromite/issues/832 
Except for Microsoft Edge and Vivaldi and possibility others

**Comment by wchen342** [comment]
I use DoH patch from Bromite, so I will need to wait for the fix from them.

**Comment by TheSilencedOne** [comment]
> I use DoH patch from Bromite, so I will need to wait for the fix from them.

Thanks but just so your aware that patch has been reported as not working

**Comment by sofiorrhamn-gif** [comment]
Ise kaise theek karo

**Comment by sofiorrhamn-gif** [comment]
Use secure DNS

**Comment by sofiorrhamn-gif** [comment]
Use secure DNS

**Comment by sofiorrhamn-gif** [comment]
Use secure DNS Mera block ho gaya hai kaise theek karo

**Comment by sofiorrhamn-gif** [comment]
Use secure DNS
