### ISSUE TITLE
Is Ungoogled as safe as Chromium?

### ISSUE THREAD

**Issue by DeuShades** [Eloston/ungoogled-chromium#136]
While Chromium gets new updates every 15 days or so, ungoogled has not been updated for about 3 month, which is a very long time for a browser release... I am not so savvy when it comes to browsers and thus I do not know the extend of the security issues that the smaller Chromium updates (the ones which Ungoogled does not offer) fix. Does one have to worry about those security issues? To what extend is Ungoogled less safe than Chromium?

**Comment by JamesBedwell** [comment]
I too would like to know the security implications of this.

**Comment by Eloston** [comment]
The modern web browser is much more sophisticated than web browsers were back in the day, so there are many options when it comes to attempting a hack; you have the networking stack, plugins, and JavaScript. However, most of these hacks are pretty sophisticated and/or limited, so it'll be hard to come across in daily browsing.

How safe you are also depends on how Chromium is built. In ungoogled-chromium's case, a lot of newer and/or potentially privacy-invading features are disabled, like NaCl and WebRTC, so there are fewer attack points. Chromium has these features enabled by default.

On a related note, there have been no new tags recently, but all platforms except Windows have support for version 55 in the master branch. I might tag a version before Windows support is added if it takes too long.

If you have more questions, let me know.
