### ISSUE TITLE
Problems with ungoogled-chromium 88

### ISSUE THREAD

**Issue by aeropatron** [Eloston/ungoogled-chromium#1365]
I use linux Pop!_OS Nvidia 20.10 as OS (Ubuntu).
Since I updated yesterday I have being noticing problems, basically running some streaming video parts are jumpy, like quick cuts while going on. Sound is not affected.

Also while I was resetting my github password filling the text box, github said that my browser was doing something wrong.

I only use unblock origin as add-on, I turned it off and nothing changed.
flatpak version 88.0.4324.104 (Build oficial) (64 bits)

To reproduce:
https://www.youtube.com/watch?v=uhwGD0ADSKI (At 5 min noticeable)
https://www.youtube.com/watch?v=f66VoHQbSdA (Almost since start)

Could anyone confirm if this only happening to me with this new version or it is actually a bug?

**Comment by Pelagius740** [comment]
It's happening to me too, same flatpak version as yours. I don't know if it's happening also in non-flatpak versions, since I couldn't get the H.264 codec to work with ungoogled-chromium in Fedora.

I think it has to do with the H.264 codec. What you're seeing in youtube videos is probably the automatic setting of video resolution, which is changing from VP8/9 to H.264. Try watching a few videos in dailymotion. They use -afaik- the H.264 codec in all their videos, so you should see the same problem in all of them.

**Comment by aeropatron** [comment]
Hi @Pelagius740 , I have tried three different videos at dailymotion and each one are unaffected.
I hope our investigations helps @Eloston .

**Comment by wchen342** [comment]
I'm on Fedora, non-Flatpak UC built without non-free codecs, and I cannot see the problem in the videos you posted. It is probably flatpak specific.

**Comment by Eloston** [comment]
I'm on Debian using unportable (non-free codecs and VA-API). I do not have any issues either. Since you're on a Debian-based system, you could try unportable and see if you have any issues.

**Comment by Ghebraant** [comment]
Happens to me as well after updating to latest flatpak version, on both youtube videos as well as animated gifs for example on twitter. On youtube, the problem occurs after resolution is set to 360p or above. The codecs thing seems plausible, though I noticed that on the linked video, the codec is shown as avc1 regardless of which resolution is chosen. This is on Manjaro by the way.

**Comment by Eloston** [comment]
Closing because regular Debian builds are back, and OBS is updated. You can try to give them a shot

**Comment by sith-on-mars** [comment]
Unfortunately, the Flatpak version is not updated and still have the video stuttering issue.

**Comment by aeropatron** [comment]
I think is solved, I am trying with fjust installed flatpack version Version 87.0.4280.141 (Official Build) built on Debian buster/10, running on Pop groovy/20.10 (64-bit)
