### ISSUE TITLE
Is ungooged-chromium built with the correct flags for native notifications?

### ISSUE THREAD

**Issue by bionade24** [Eloston/ungoogled-chromium#1366]
Arch Linux, swaywm, mako as notification daemon. 

Is ungooged-chromium built with the correct flags for native notifications?

_Originally posted by @bionade24 in https://github.com/Eloston/ungoogled-chromium/discussions/1348_

**Comment by tasty0tomato** [comment]
Crash when allow notifications when open some websites in the latest Windows build by woolyss.
And do not crash in chrome.

Because of personal private, cannot provide the website that do not work.

**Comment by bionade24** [comment]
It now works under Linux with Wayland.

**Comment by tasty0tomato** [comment]
Why closed?

**Comment by bionade24** [comment]
> Why closed?

Because it's fixed?

**Comment by tasty0tomato** [comment]
> It now works under Linux with Wayland.

So so sorry, see the wrong word.
