### ISSUE TITLE
Feature request: Official portable build

### ISSUE THREAD

**Issue by ilu33** [Eloston/ungoogled-chromium#1368]
I'm not sure about the right place to put this feature request. Feel free to close the wrong one.

As somebody proposed in discussions having an official portable build to take and repackage in other distros would be nice. It would really help to spread this project. There's at least one distro considering this. Taking the unofficial binaries seems not like something a distro can do as you need to trust more and completely unknown users than just @Eloston.
Building chromium is a task only major distributions can tackle. Adding ungoogled-chromium-portablelinux to OBS would be perfect. It just needs to stay portable (which means /opt, obviously).

I came to understand that the OBS is operated by @braewoods and @jstkdng. Since Eloston obviously approves this, that would be trustworthy enough, I think.

**Comment by jstkdng** [comment]
Whilst the OBS could be used to build uc-portablelinux, it isn't able to ouput a regular .zip file, only files for each distribution , .deb for debian/ubuntu or .pkg.tar.zst for arch. Distribution of the resulting binary would require some tampering in order to create a zip file.

**Comment by ilu33** [comment]
We can't modify all paths in the existing deb. Distros don't need a zip anyway - we'd be really happy with a .deb. It just needs to be /opt only.

**Comment by jlj2** [comment]
@ilu33's idea could be excellent - no need for **.zip**.  Simply use **.deb** for all distros perhaps?

1) Simply compile an OBS package to be unpackaged, say, to `/opt` in each Linux distribution (and hopefully most unix-like/BSD distributions) perhaps?
Then, write wiki instructions on how to unpackage/install, say, a universal OBS **.deb** package for most specific distributions if users insist that the same individual compile the binary:-

- Debian/Ubuntu (unportable) 64-bit
- Arch Linux
- Portable Linux 64-bit
- Portable Linux 64-bit (for musl libc)
- macOS

As users may know, a .deb package is roughly-speaking a type of archive and can be decompressed in unix-like environments.

2) Or just package the OBS as a **.tar.gz** with a simple installer that might probe the OS type (calling uname?) and would install UC to `/opt` regardless of the distro.

3) Maybe just add the AppImage version also.

4) How about creating a `/usr/bin/uc` soft link launcher to be overwritten each time to point to the latest UC version in `/opt`?  Check also that there is no unrelated 'uc' package.

5) By the way, re the **Ungoogled Chromium** name:  rebrand it as **UC** and use the `/usr/bin/uc` soft link launcher, and therefore no need to rethink any perhaps proprietary-like **Ungoogled Chromium** [branding argument anymore](https://github.com/Eloston/ungoogled-chromium/issues/759) when just calling the browser **UC**?  '**UC**' could be presented as the preferred and short version name of the _'Unconnected-Chromiumlike'_ browser with _'the previous ungoogled-chromium name having been superseded and dropped'_.
Of course, some people may miss the previous name, but they would have to recognise that this arrangement is would be to accommodate concerns that also need to be appreciated from:-
(i) an originating company involved;  and
(ii) the packager who prepares and has offered this package to those users arguably for 'free' if that is the correct term.

**Comment by jlj2** [comment]
@ilu33's idea could be excellent - no need for **.zip**.  Simply use **.deb** for all distros perhaps?

1) Simply compile an OBS package to be unpackaged, say, to `/opt` in each Linux distribution (and hopefully most unix-like/BSD distributions) perhaps?
Then, write wiki instructions on how to unpackage/install, say, a universal OBS **.deb** package for most specific distributions if users insist that the same individual compile the binary:-

- Debian/Ubuntu (unportable) 64-bit
- Arch Linux
- Portable Linux 64-bit
- Gentoo
- Redhat

Compilations would need to continue to be separate for:-
- Windows
- macOS
- Portable Linux 64-bit (for musl libc)

As users may know, a **.deb** package is roughly-speaking a type of archive and can be decompressed in unix-like environments.

2) Or just package the OBS as a **.tar.gz** with a simple installer that might probe the OS type (calling uname?) and would install UC to `/opt` regardless of the distro.

3) Maybe just add the AppImage version also.

4) How about creating a `/usr/bin/uc` soft link launcher to be overwritten each time to point to the latest UC version in `/opt`?  Check also that there is no unrelated `uc` package.

5) By the way, re the **Ungoogled Chromium** name:  rebrand it as **UC** and use the `/usr/bin/uc` soft link launcher, and therefore no need to rethink any perhaps proprietary-like **Ungoogled Chromium** [branding argument anymore](https://github.com/Eloston/ungoogled-chromium/issues/759) when just calling the browser **UC**?  '**UC**' could be presented as the preferred and short version name of the _'Unconnected-Chromiumlike'_ browser with _'the previous ungoogled-chromium name having been superseded and dropped'_.
Of course, some people may miss the previous name, but they would have to recognise that this arrangement would be to accommodate concerns that also need to be appreciated from:-
(i) an originating company involved;  and
(ii) the packager who prepares and has offered this package to those users arguably for 'free' if that is the correct term.

**Comment by jlj2** [comment]
**UC**:  '**You see** while restricting one company from seeing you'.

**Comment by jstkdng** [comment]
wow, that's a lot of proposals.
regarding 1 and 2, a portable build should be able to run wherever you extract it to, no need to create other files.
3 would be the best solution for portable but there's already a project for that
no need for 4 and 5 since it is portable, and there's already a browser called UC, could cause problems

**Comment by wchen342** [comment]
I will object using UC as an official name. It can be confused with [UC Browser](https://en.wikipedia.org/wiki/UC_Browser) which has severe [security](https://www.digit.in/news/internet/uc-browser-under-government-lens-for-leaking-user-data-to-servers-in-china-36704.html) and [privacy problems](https://citizenlab.ca/2016/08/a-tough-nut-to-crack-look-privacy-and-security-issues-with-uc-browser/) as well as being banned in India.

**Comment by ilu33** [comment]
This issue is not about the name. It's about compiling the portable code base into something that can be easily redistributed. Since almost any distribution already has a chromium version, /opt is the ideal destination. Setting up OBS to also compile the portable version in a way that can be easily repackaged would be ideal because regularly pulling the package would be easy. deb would be a good candidate. Distros with other package managers could use alien for repackaging.

Using appimage itself is not an option. Repackaging the appimage is almost certainly a pain.

**Comment by karam72** [comment]
AppImage or a portable build (which has all dependencies inside) would be really great! So we can run multiple version of ungoogled-chromium on the same OS user without install/reinstall or the root password.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
