### ISSUE TITLE
ungoogled-chromium not starting with re2 >= 1:20210201-1

### ISSUE THREAD

**Issue by tiekoetter** [Eloston/ungoogled-chromium#1371]
**Describe the bug**
ungoogled chromium won't start with re2 version >= 1:20210201-1 on Arch Linux. (/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.9: cannot open shared object file: No such file or directory)

**To Reproduce**
1. Update re2 to >=1:20210201-1 (pacman -S re2)
2. Start Chromium
3. Output: "/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.9: cannot open shared object file: No such file or directory"

**Expected behavior**
Chromium starting normally.

**Environment (please complete the following information):**
 - OS/Platform and version: GNU/Linux (Arch Linux, Kernel 5.10.11-arch1-1)
 - ungoogled-chromium version: 88.0.4324.104

**Additional context**
Temporarily fixed by downgrading re2. Recompiling should hopefully fix this as well with the new version of re2 (will update when my poor laptop is done).

1. Look for cached re2 versions (ls /var/cache/pacman/pkg | grep "re2")
2. pacman -U re2-[version].pkg.tar.zst (In my case it was "pacman -U re2-1:20201101-1-x86_64.pkg.tar.zst")
3. Chromium should now start normally.

**Comment by braewoods** [comment]
This is a distribution specific packaging problem. Shouldn't this be reported under the distribution repository or the contributor binaries repository?

**Comment by Eloston** [comment]
Yeah, this looks Arch Linux-specific. Since I can't move this issue there, please create the issue on ungoogled-chromium-archlinux instead: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues. Thanks!
