### ISSUE TITLE
Tab Discarding and Reloading issue

### ISSUE THREAD

**Issue by gerroon** [Eloston/ungoogled-chromium#1374]
Hi

I am using Flatpak 87.0.4280.141 (Official Build) (64-bit)  on Debian x64 

Since starting to use this build the tabs have been reloading with tab changes very frequently such that it is very very noticable.  I already did couple restarts and killed some bg apps. I now have over 1.4 gb free system memory (I have total 8bg on the laptop) and it still happens.

It seems like there is a  setting for this `chrome://flags/#automatic-tab-discarding` , but this is not listed in the ungoogled's flags page. 

I am wondering if there has been a real change in the recent builds regarding this setting or memory using.

https://www.chromium.org/chromium-os/chromiumos-design-docs/tab-discarding-and-reloading 

thanks

**Comment by victor03303** [comment]
In flatpak version 89.0.4389.114
can't find that optien either :/ 

Would be nice if this option would become available

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the Flatpak repo: [flathub/com.github.Eloston.UngoogledChromium](https://github.com/flathub/com.github.Eloston.UngoogledChromium)
