### ISSUE TITLE
"Play on TV" aka Chromecast button does not display on chromecast-supported sites (e.g. YouTube)

### ISSUE THREAD

**Issue by drewthor** [Eloston/ungoogled-chromium#1382]
**Describe the bug**

Cannot cast directly to chromecast (not using cast tab which provides lower bitrate and worse performance) videos on sites like youtube.com

**To Reproduce**
1. Enable flag #cast-media-route-provider
2. Go to youtube.com
3. Click on any video
4. See that chromecast icon is missing and you can't directly cast video to chromecast
5. Try and repeat this on standard chromium and you will notice the button does appear

**Expected behavior**
Direct native casting of video on sites like youtube.com 

**Screenshots**
Ungoogled-chromium:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/9273455/107132497-356a8d00-68a5-11eb-963a-968569c6eb03.png">

Chromium proper:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/9273455/107132401-57afdb00-68a4-11eb-9f43-89ec9149ec6f.png">

**Environment (please complete the following information):**
 - OS/Platform and version: macOS 11.2
 - ungoogled-chromium version: Version 88.0.4324.146 

**Additional context**
If this is a privacy issue with enabling it by default, at least provide a flag to be able to enable it. Casting without the native/direct cast functionality is an abysmal experience

**Comment by BachoSeven** [comment]
Both the issue you're having, and the proposal to have a flag to make this feature available as an opt-in have already been mentioned in https://github.com/Eloston/ungoogled-chromium/issues/1137, so feel free to close this as duplicate and comment there instead.
