### ISSUE TITLE
Question: Multi instance usage with multiple profiles at the same time

### ISSUE THREAD

**Issue by ledgeri** [Eloston/ungoogled-chromium#1384]
HI!

I would like to know if it is reachable (and how) to have a multiple isntances of ungoogled-chromium running with using multiple profiles?
My solution with firefox is currently i have 4 seperate instalment. All release version. Also i have 4 individual profile folder.
Each instalment has its own profile {but could start any profile} (one for main usage, one for listening music, one is “vanilla” and one is as a “default browser” in case something wants to open a browser [game “news” button, programs’ “update the upgrade now” buttons etc.]), and almost all has its own addon-pack, history, etc.
Any can be opened next to any other what is running… there is no unvanted crosstalk. Even all 4 can run at the same time.

Is this system/goal is reacheble with ungoogled-chromium? (My high bet is on yes, hence chromium based browsers can run next to each other, but i never thought about an “in brand” solution…)

**Comment by jacob755** [comment]
create folder called "bin" or whatever you like  extract ungoogled-chromium content to it
now create shortcut from chrome.exe in bin folder then move shortcut to parent folder of "bin"
Then right click select properties of that shortcut
in **target** box paste this
`E:\Chromium\Bin\chrome.exe --user-data-dir=..\profile1 --disable-breakpad --disable-cookie-encryption --disable-encryption --disable-machine-id`

in  **start in** box type:
`E:\Chromium\Bin`

note1 :to create new profile  just copy paste same shortcut and just change the **profile1**  in target box for different purpose.
note2: my example  are in **drive E** / **Chromium** folder then **bin** folder

**Comment by ledgeri** [comment]
Thank you!

Why those "--disable-breakpad --disable-cookie-encryption --disable-encryption --disable-machine-id" needed to be added? What happens if i do not add them?

**Comment by jacob755** [comment]
> Thank you!
> 
> Why those "--disable-breakpad --disable-cookie-encryption --disable-encryption --disable-machine-id" needed to be added? What happens if i do not add them?

this flag i used you can remove them

**Comment by ledgeri** [comment]
> 
> 
> > Thank you!
> > Why those "--disable-breakpad --disable-cookie-encryption --disable-encryption --disable-machine-id" needed to be added? What happens if i do not add them?
> 
> those are flag I used you can remove them

Ohh ok, i thought they needed specially :)

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
