### ISSUE TITLE
What Are the Incoming Connections?

### ISSUE THREAD

**Issue by arandorion** [Eloston/ungoogled-chromium#1385]
When I first launch the browser, before I even attempt to open a website, LittleSnitch reports an incoming connection. What is that incoming connection and why is it necessary?

Thank you

**Comment by NSTAdventure** [comment]
> When I first launch the browser, before I even attempt to open a website, LittleSnitch reports an incoming connection. What is that incoming connection and why is it necessary?
> 
> Thank you

Man you dind't share the ip address then from where developer can examine that?

Or is it?

**Comment by PF4Public** [comment]
Is this still an issue?

**Comment by arandorion** [comment]
I've been playing with the latest version and haven't noticed it anymore. Interestingly, when I visit some sites with Firefox, I also get attempts at incoming connections.

**Comment by PF4Public** [comment]
Thanks for getting back to us. Closing.

**Comment by networkException** [comment]
Could be that LittleSnitch gets confused with QUIC, that pulls a lot of network trickery in order to establish a connection.
