### ISSUE TITLE
Every search request.. 

### ISSUE THREAD

**Issue by bcookatpcsd** [Eloston/ungoogled-chromium#1386]
Its+just+a+business.+We+absolutely+do+not+care+about+you+and+your+deals%2C+except+getting+benefits.+If+we+do+not+do+our+work+and+liabilities+-+nobody+will+not+cooperate+with+us.+Its+not+in+our+interests.+To+check+the+ability+of+returning+files%2C+You+should+go+to+our+website.+There+you+can+decrypt+one+file+for+free.+That+is+our+guarantee.+If+you+will+not+cooperate+with+our+service+-+for+us%2C+its+does+not+matter.+But+you+will+lose+your+time+and+data%2C+cause+just+we+have+the+private+key.+In+practise+-+time+is+much+more+valuable+than+money.

My search url was changed.. 

https://www.google.com/search?q=%s

Not sure how it happened.. 

https://www.google.com/search?sxsrf=ALeKk01dD00rEVFtkruLfSIHJnhjSK8_Aw%3A1582776661179&source=hp&ei=VUFXXtisB-CpytMP3N61uAE&q=frogs&btnK=Google+Search&oq=Its+just+a+business.+We+absolutely+do+not+care+about+you+and+your+deals%2C+except+getting+benefits.+If+we+do+not+do+our+work+and+liabilities+-+nobody+will+not+cooperate+with+us.+Its+not+in+our+interests.+To+check+the+ability+of+returning+files%2C+You+should+go+to+our+website.+There+you+can+decrypt+one+file+for+free.+That+is+our+guarantee.+If+you+will+not+cooperate+with+our+service+-+for+us%2C+its+does+not+matter.+But+you+will+lose+your+time+and+data%2C+cause+just+we+have+the+private+key.+In+practise+-+time+is+much+more+valuable+than+money.&gs_l=psy-ab.3...484.484..1405...0.0..0.0.0.......0....2j1..gws-wiz.lE3FE1Vl2kE&ved=0ahUKEwiYq5TF7vDnAhXglHIEHVxvDRcQ4dUDCAg&uact=5

https://www.google.com/search?sxsrf=ALeKk01dD00rEVFtkruLfSIHJnhjSK8_Aw%3A1582776661179&source=hp&ei=VUFXXtisB-CpytMP3N61uAE&q=pojonews+amp&btnK=Google+Search&oq=Its+just+a+business.+We+absolutely+do+not+care+about+you+and+your+deals%2C+except+getting+benefits.+If+we+do+not+do+our+work+and+liabilities+-+nobody+will+not+cooperate+with+us.+Its+not+in+our+interests.+To+check+the+ability+of+returning+files%2C+You+should+go+to+our+website.+There+you+can+decrypt+one+file+for+free.+That+is+our+guarantee.+If+you+will+not+cooperate+with+our+service+-+for+us%2C+its+does+not+matter.+But+you+will+lose+your+time+and+data%2C+cause+just+we+have+the+private+key.+In+practise+-+time+is+much+more+valuable+than+money.&gs_l=psy-ab.3...484.484..1405...0.0..0.0.0.......0....2j1..gws-wiz.lE3FE1Vl2kE&ved=0ahUKEwiYq5TF7vDnAhXglHIEHVxvDRcQ4dUDCAg&uact=5

Open to suggestions and questions.. 

But I couldn't find that this happened to anyone else..

**Comment by PF4Public** [comment]
It is not clear, what your issue is exactly.
