### ISSUE TITLE
update_lists.py exclude pattern

### ISSUE THREAD

**Issue by cjbd** [Eloston/ungoogled-chromium#1389]
hello, i have chromium src git repo already, i wanted to test `update_lists.py` script by:

```sh
./devutils/update_lists.py -t /path/to/chromium/src
```
this will consume all RAM and crash, with error like this:
```
ERROR: Unhandled exception while processing .git/objects/pack/pack-5582c833efb8d8fe08cc194ce33fdf372b9e495f.pack
```
obviously, it's also scanning `.git` folders, i googled a bit, trying to exclude this folder by modifying below code in `update_lists.py`
```py
    with Pool(processes) as procpool:
        returned_data = procpool.starmap(
            compute_lists_proc,
            zip(source_tree.rglob('[!.git]*'), repeat(source_tree), repeat(search_regex)))
```
it's not working, it still uses all RAM then crashes

i'm not very familiar with `rglob`, how do i scan the source tree with exclude pattern like excluding all `.git` folders?

thank you!

**Comment by Ahrotahn** [comment]
Setting the `--processes` flag to a lower value should help with the memory issue.  By default it will spawn a process for each of your cores and this can take a lot of RAM.  

The glob exclusion looks like it should work though.

**Comment by cjbd** [comment]
@Ahrotahn , thanks for the update, but after the change, there's still the same error: `ERROR: Unhandled exception while processing .git/objects/pack/pack-5582c833efb8d8fe08cc194ce33fdf372b9e495f.pack`, i don't think the exclusion is working  
i also tried using `--process 1`, and opened system monitor, it still uses all RAM then crash with same error

**Comment by Ahrotahn** [comment]
You used `--process`, but the correct flag is <code>--process<b>es</b></code>.  

It seems the glob exclusion excludes the git directory, but not the files in it!  It might be better to change compute_lists_proc to return if the path is in the directory.  Alternatively, you could just move the directory out temporarily.  
Normally the release tarballs are used which doesn't include the git directory.  

How much RAM do you have?  I don't think you'll be able to compile chromium without at least 8GB.

**Comment by cjbd** [comment]
@Ahrotahn, thanks for the update, i have 32GB RAM

**Comment by cjbd** [comment]
this works:
```py
with Pool(processes) as procpool:
    returned_data = procpool.starmap(
        compute_lists_proc,
        zip(filter(lambda x: ".git" not in x.parts, source_tree.rglob('*')), repeat(source_tree), repeat(search_regex)))
```
