### ISSUE TITLE
When will the pre-built binaries be updated?

### ISSUE THREAD

**Issue by jgoldgh** [Eloston/ungoogled-chromium#139]
I'm still using the OSX release from September but it's got that annoying "Your connection is not private" bug on sites like amazon.com.

**Comment by Eloston** [comment]
I'm in the process of preparing for the next tag release. I will need to ask those over in #129 for the binaries.

**Comment by 9Morello** [comment]
@jgoldgh In a few hours.

**Comment by luckydonald** [comment]
yay!
