### ISSUE TITLE
Never remember history feature

### ISSUE THREAD

**Issue by distrair** [Eloston/ungoogled-chromium#1390]
I really liked one Firefox feature, when you can disable history. I want the same feature here as well. Can you add it please?

**Comment by PF4Public** [comment]
Recently the flag [clear-data-on-exit](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-clear-data-on-exit.patch) added to ungoogled-chromium. This might be what you're looking for.
