### ISSUE TITLE
Disabling machine ID locks up settings

### ISSUE THREAD

**Issue by hitagiiiiiiii** [Eloston/ungoogled-chromium#1398]
**Describe the bug**
Enabling the 'Disable machine ID' flag triggers a response from chrome which blocks the browser's settings.

**To Reproduce**
1. Go to 'chrome://flags/'
2. Scroll down to 'Disable machine ID'
3. Select 'Enabled"
4. Go to Settings
5. See error

**Screenshots**
![chrome___settings_](https://user-images.githubusercontent.com/79207599/108220441-1a9de100-710d-11eb-9ed3-9b2d1556292c.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 desktop 1903
 - ungoogled-chromium version: 88.0.4324.150

**Additional context**
Also everything downloaded is seen as suspicious by Chromium requiring you to click 'keep' after each download.

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
