### ISSUE TITLE
Upload ubuntu binaries   

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#14]
Chromium requires a powerful cpu and a huge amount of ram for its compilation  

and some users doesn't have it,  for it i suggest upload ubuntu "at least xenial" binaries,  thanks

**Comment by Eloston** [comment]
I'll start doing this for the next version of ungoogled-chromium, which will be based on a stable version of Chromium 51.

**Comment by triceratops1** [comment]
the binary is  compatible with ubuntu, but i needed modify the control file of control.tar.gz   

with this "control"    this binary works fine

https://gist.github.com/triceratops1/080b57b91333db34108db738997c06a4

**Comment by triceratops1** [comment]
if you want compatibility with ubuntu, please replaces libjpeg62-turbo with libjpeg62   


i proved it, modifying your  debs

**Comment by Eloston** [comment]
@triceratops1: I appreciate your effort, but I will not accept this. In the event that other libraries are renamed or the ABI starts to differ across distributions for the same library, your change will no longer apply. It is better to build directly on Ubuntu.

**Comment by Eloston** [comment]
Done with [51.0.2704.106-1.1](https://github.com/Eloston/ungoogled-chromium/releases/tag/51.0.2704.106-1)
