### ISSUE TITLE
macOS: Fix building with Widevine support on 55

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#141]
For some reason, Widevine support cannot be built with Chromium 55. This is the error: https://github.com/Eloston/ungoogled-chromium/issues/129#issuecomment-265023549

Any help with this will be appreciated.

**Comment by pjv** [comment]
is there a viable, manual workaround for getting this to work with the current v55 9morello.dmg?

**Comment by Eloston** [comment]
@pjv I don't think so. You could try getting the widevine files from Chrome and seeing if it will work, but I don't think the browser has the code to interface with them.

**Comment by Eitot** [comment]
Can this issue remain open, so that someone may still figure out why Widevine cannot be built?

**Comment by Eloston** [comment]
@Eitot Either they can comment here and I will re-open, or they can open a new issue report (since it probably won't be related to this error).

**Comment by 9Morello** [comment]
@Eitot The master branch works with Widevine. The user still has to copy the plugin files from Google Chrome.

**Comment by Eitot** [comment]
Does the Widevine build also fail with the regular Chromium source code? The FreeSMUG build also does not seem to have it.

**Comment by 9Morello** [comment]
@Eitot Sorry, seems like I wrote your response days ago and forgot to actually post it.
I haven't tested, nor I've read about regular Chromium building with Widevine on OS X. Its hard to test without using the same flags.
