### ISSUE TITLE
Video stutters in the Flatpak version

### ISSUE THREAD

**Issue by sith-on-mars** [Eloston/ungoogled-chromium#1412]
I'm on the latest OpenSUSE Tumbleweed. I use the Flatpak version of Ungoogled Chromium.

When I played videos, they kept stuttering. I don't have the same issue with other browsers on my device (they're non-Flatpak). Is it possible that codes shipped with the Flatpak version is buggy?

**Comment by Ghebraant** [comment]
Something is definitely wrong. On youtube, the problem occurs when the video is using AVC1 codec, and the resolution is set to above 480p. There was another report about it here: https://github.com/Eloston/ungoogled-chromium/issues?q=is%3Aissue+is%3Aclosed

**Comment by aeropatron** [comment]
Try to install last version:
https://github.com/Eloston/ungoogled-chromium/issues/1365#issuecomment-787522970

**Comment by sith-on-mars** [comment]
Problem is solved after installing the latest Flatpak version today.
