### ISSUE TITLE
[Feature Request] always incognito mode

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#1413]
I would like a always incognito mode similar to the one available in Bromite

**Additional context**
![Screenshot_20210226-121917_1](https://user-images.githubusercontent.com/78061111/109333402-6b0fef80-782d-11eb-945f-af90698ee20c.png)

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
+1

**Comment by Rekulous** [comment]
This is a neat option

**Comment by Ahrotahn** [comment]
This already exists!  Just add `--incognito` to your launch switches.

**Comment by TheSilencedOne** [comment]
> This already exists! Just add `--incognito` to your launch switches.

Not really the best work around a official implementation would be nice

**Comment by keks24** [comment]
There is a configuration file for this:
```bash
$ vi "/etc/chromium/default"
CHROMIUM_FLAGS="--incognito"
```

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
