### ISSUE TITLE
Consider taking some more patches from bromite

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#1417]
**Is your feature request related to a problem? Please describe.**
First of all, thanks to the  developers of this project for their hard work, you people are awesome.
Currently, the condition of privacy browsers on desktop platform is terrible, we have firefox advising privacy and phoning home upon opening it every time and having vulnerable sandbox
https://madaidans-insecurities.github.io/firefox-chromium.html
And speaking of chromium based browsers brave comes to mind also, but they have done questionable things in the past like injecting affiliate urls in search queries. 

**Describe the solution you'd like**
Currently ungoogled chromium has only 3 flags from bromite patches, and bromite has been doing great recently, adding anti fingerprinting features like timezone randomisation, having flag to disable WebGL completely, custom user agent support built into browser, hope you will include these patches as flags in ungoogled chromium.

**Describe alternatives you've considered**

**Additional context**

**Comment by wchen342** [comment]
See Eloston's comment [here](https://github.com/Eloston/ungoogled-chromium/discussions/1395#discussioncomment-389878).

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
