### ISSUE TITLE
Buildlib is not guessing the distro correctly on Ubuntu 16.10

### ISSUE THREAD

**Issue by 9Morello** [Eloston/ungoogled-chromium#142]
If you run the master branch in Ubuntu 16.10, it will attempt to build the static version. It seems that `dist_codename` in `__init__.py` isn't returning the actual Ubuntu version, making it go for the static build.

For example, changing lines 49 and 50 to this _does not_ make it use the XenialBuilder on Ubuntu 16.10:

```
        elif dist_id == "ubuntu" and (dist_codename == "yakkety"):
            from .debian import UbuntuXenialBuilder
```

**Comment by Eloston** [comment]
Try launching an interactive Python 3 console in the `buildlib/_external` directory and let me know the output of the following:
```
import distro
distro.info()
```

**Comment by 9Morello** [comment]
The version output was "Yakkety Yak". The version output on 16.04 was "Xenial Xerus". Using the capitalized full names fixes the issue.

**Comment by Eloston** [comment]
@9Morello Ah I see. Thanks for your input. Going to merge your PR now.
