### ISSUE TITLE
Maybe Ungoogle Chromium should have the option for an adblock like Bromite

### ISSUE THREAD

**Issue by Rekulous** [Eloston/ungoogled-chromium#1420]
I really like Bromite on Android as a browser since its a fork of Ungoogle Chromium, but there are some patches and additional features that I think should be added to Ungoogled Chromium such as an adblock which you can turn on and off. It would be a nice and convenient thing to have without configuring extensions and other stuff. The Adblock should block tracking, ads, and other nasty things on webpages.

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Well, it's not really needed as we can install ub0 and it will work better than anything

**Comment by Rekulous** [comment]
> Well, it's not really needed as we can install ub0 and it will work better than anything( android version also supports extensions)

I use uBO, but its handy to have an adblocker if you want (maybe that is bloat)

**Comment by TheSilencedOne** [comment]
Ublock Origin does work but it also makes you more easily identifiable by Ad & tracking companies

**Comment by NSTAdventure** [comment]
> Well, it's not really needed as we can install ub0 and it will work better than anything( android version also supports extensions)

The only issues as mentioned by @wchen342  extension variant discontinued why?

**Comment by wchen342** [comment]
> its a fork of Ungoogle Chromium

No it is *not*. Bromite has its own goals different from ungoogled-chromium.

> android version also supports extensions

I will no longer update the extension version. See ungoogled-software/ungoogled-chromium-android#78.

**Comment by tangalbert919** [comment]
According to the [wiki](https://github.com/bromite/bromite/wiki/AdBlocking), Bromite uses the Chromium subresource filter to do the adblocking, so this could be implemented as an enhancing feature in ungoogled-chromium.

> Well, it's not really needed as we can install ub0 and it will work better than anything( android version also supports extensions)

We could do that, but the idea is that we don't need to get extensions at all.

**Comment by NSTAdventure** [comment]
> According to the [wiki](https://github.com/bromite/bromite/wiki/AdBlocking), Bromite uses the Chromium subresource filter to do the adblocking, so this could be implemented as an enhancing feature in ungoogled-chromium.
> 
> > Well, it's not really needed as we can install ub0 and it will work better than anything( android version also supports extensions)
> 
> We could do that, but the idea is that we don't need to get extensions at all.

wait but user like me are rallying on extension i hope all ungoogled chromium developer consider this :)

Best Regards
NST_Adventure

**Comment by securingmom** [comment]
> handy to have an adblocker

To that end:

https://NextDNS.io

Apply using android's Secure DNS.

**Comment by Luka-Filipovic** [comment]
You can check https://github.com/privacyone/breeze-core, a project my friends and I are working on. It is heavily based on ungoogled-chromium. It has "built-in" ublock so you may find it interesting.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
