### ISSUE TITLE
Get rid if the annoying message  "this type of file can harm your computer Do you really want to save it ?" when downloading a file

### ISSUE THREAD

**Issue by mooms06** [Eloston/ungoogled-chromium#1423]
**Describe the bug**
Whenever I download some file, Ungoogled Chromium asks me to confirm that I want to save the file (see screenshots)
Message says "this type of file can harm your computer. Do you really want to save it ?"
It happens randomly, with pdf, swf, exe, etc...

**To Reproduce**
1. Go to http://www.landxmlproject.org/file-cabinet
2. Click on any download link on the page 
3. Choose the directory to save the file
4. Chromium will show a nag on the bottom left. 
**Expected behavior**
Chromium should download the file after asking for which folder to save it.

**Screenshots**
![image](https://user-images.githubusercontent.com/25405517/110032250-35409e80-7d38-11eb-9703-1af7ac866ca9.png)

If I go to the download manager (the button on the right on the previous image or Ctrl+J), the two buttons aren't even working:
![image](https://user-images.githubusercontent.com/25405517/110031975-e4c94100-7d37-11eb-8142-6d6615c23bbc.png)

![image](https://user-images.githubusercontent.com/25405517/110031473-3fae6880-7d37-11eb-8139-57ff7ef7eb18.png)

**Environment (please complete the following information):**
 - Widows 10 20H1
 - ungoogled-chromium_88.0.4324.182-1.1_installer-x64

**Additional context**
It also happens when updating extensions with Chrome web store extension.

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
That's a security feature, even PDFs can damage an OS like windows😂

**Comment by mooms06** [comment]
It happens on every extension...Anyway, there should be an option to disable this.

**Comment by Glubzor** [comment]
I heavily support this request. Please purely disable it. Many thanks to contributors of this project.

**Comment by tangalbert919** [comment]
I will take a look at this and see what I can do about it.

**Comment by mooms06** [comment]
It also happens with extensions as well (when updated by Chromium Web Store extension)

![image](https://user-images.githubusercontent.com/25405517/110450857-e1311380-80c3-11eb-98e2-47d50204c304.png)

**Comment by Kroissan** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/1337
You may try the registery hack.
No solution at this date, for me it happens to every download.

**Comment by mooms06** [comment]
I tried the registry key, it doesn't work.

**Comment by Ph0rk0z** [comment]
Use version 87.0.4280.67, that's the last one without this.

**Comment by securingmom** [comment]
> In that case, why not add a warning every time you open the browser in Windows 

An alert seeking Informed Consent everytime Windows is started would be preferable.

If people understood what vanilla Windows Home did to them maybe they would jump ship.   Why pay to be used by spyware?

> That's a security feature

👍 

> pdf, swf,

These can contain executable payloads.

> exe

Self evident.


>  privacy problem.

Disable security features and want privacy?  hmmmm  Seems more likely the extension per se  is the trigger.  Does this happen for you with any of these benign extensions:

.png
.jpg
.jpeg


> and see what I can do about it.

User education.

**Comment by patoniilista** [comment]
> Does this happen for you with any of these benign extensions:

.png
.jpg
.jpeg

I'm having the same issue on a spare machine running windows 10 and I can say that anything that gets downloaded ends up being flagged: .crx, .jpg, .png, .jpeg, .pdf, .docx, .txt, .webp, .psd, basically any extension.

**Comment by tangalbert919** [comment]
I have pushed a fix for this problem. New Windows builds will be released today.

**Comment by Glubzor** [comment]
Excellent ! Many thanks.

**Comment by mooms06** [comment]
Fixed in 89.0.4389.90-1.
Thank you.
