### ISSUE TITLE
Update AppImage, Flatpak, and Portable to 88.0.4324.182-1 or latest

### ISSUE THREAD

**Issue by christianitus03** [Eloston/ungoogled-chromium#1428]
Title explains it all. I tried posting this issue in the repo for Portable but got no response after two weeks. Each of these repos are still a few releases behind.

**Comment by TheEvilSkeleton** [comment]
I'm the maintainer of the Flatpak package. We're already using the latest version: https://github.com/flathub/com.github.Eloston.UngoogledChromium/blob/master/com.github.Eloston.UngoogledChromium.yaml#L176

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
