### ISSUE TITLE
Don't understand how to install extensions on Android

### ISSUE THREAD

**Issue by bege10** [Eloston/ungoogled-chromium#1430]
I have installed org.ungoogled.chromium.extensions.stable from the repository added to F-Droid.
I expected to be able to install extensions right away, but when I try to open the webstore I am redirected to https://chrome.google.com/webstore/unsupported
So I thought I had to follow this instruction: https://github.com/NeverDecaf/chromium-web-store
But when I come to install the unpacked crx I get the error toast that manifest is not a valid json.
What do I need to do to be able to add extensions?

Installed on Fairphone 3, /e/OS 0.14 (based on Android 10, LineageOS, microG).

**Comment by wchen342** [comment]
The extension version is discontinued.

If you still want to try, see [this](https://github.com/ungoogled-software/ungoogled-chromium-android/tree/88.0.4324.182-2#extensions).

**Comment by bege10** [comment]
Thank you for your answer. If I come to open the web store as desktop browser I don't see `Add to Chromium`. I tried several extensions.

**Comment by wchen342** [comment]
Are you sure you downloaded the right version?

**Comment by bege10** [comment]
It is org.ungoogled.chromium.stable Version 88.0.4324.182

**Comment by bege10** [comment]
![Screenshot_20210311-143419_Ungoogled_Chromium](https://user-images.githubusercontent.com/1184237/110795329-fef2aa00-8276-11eb-8147-bf6801f3b600.png)
![Screenshot_20210311-143238_Ungoogled_Chromium](https://user-images.githubusercontent.com/1184237/110795384-0dd95c80-8277-11eb-9193-8e03e5482290.png)

**Comment by wchen342** [comment]
Not sure what was going on, try an older version maybe?

**Comment by bege10** [comment]
That's what didn't work yesterday. Just tried it again and with the changed flag I can install extensions. Thank you very much.
Is it normal that chrome://extensions remains empty? How can I uninstall extensions?

**Comment by wchen342** [comment]
Which version? Versions older than `87.0.4280.141` doesn't have chrome://extensions correctly.

**Comment by bege10** [comment]
I mixed up the chrome-extension popup via the button at the bottom of the app menu and the manually entered chrome://extensions. The latter shows the installed extensions and also allows to uninstall them.
So at the moment everything looks as it should.
Thanks for your help.
