### ISSUE TITLE
Update ungoogled chromium

### ISSUE THREAD

**Issue by hefty-fading-culprit-epiphany-drew** [Eloston/ungoogled-chromium#1434]
**Is your feature request related to a problem? Please describe.**
5 highly vulnerabe cves were patched in chromium 89.0.4389.90

**Describe the solution you'd like**
Update to the latest chromium asap

**Describe alternatives you've considered**
Backport them? 

**Additional context**

https://chromereleases.googleblog.com/2021/03/stable-channel-update-for-desktop_12.html?m=1

**Comment by Eloston** [comment]
Done.

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
> Done.

That was fast
