### ISSUE TITLE
starting chromium gives error '/usr/lib/chromium/chromium: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory' on Artix Linux

### ISSUE THREAD

**Issue by hondamilkie** [Eloston/ungoogled-chromium#1436]
Building ungoogled-chromium-bin from the AUR gives error /usr/lib/chromium/chromium: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory,
error still occurs after updating the system

To Reproduce
1. clone ungoogled-chromium-bin from AUR
2. build with command 'makepkg -si'
3. start and get error

Expected behavior
Start with no errors

Screenshots
![a](https://user-images.githubusercontent.com/71604637/111080337-ef34c900-84f5-11eb-9925-0931f6dfe60e.png)

   Environment:
 - OS/Platform and version: Artix GNU/Linux 
 - ungoogled-chromium version: 89.0.4389.90-3

**Additional context**

**Comment by j-james** [comment]
That error occurs because the `libjsoncpp` library has been updated, but Chromium hasn't been recompiled for it.

You should also probably avoid using a binary Arch package.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
