### ISSUE TITLE
Google OAuth: Invalid parameter value for redirect_uri: Non-public domains not allowed

### ISSUE THREAD

**Issue by marcelklehr** [Eloston/ungoogled-chromium#1437]
Hi,

I'm the author of an extension that supports connecting to Google OAuth for syncing bookmarks via an encrypted file in Google Drive. Using Google OAuth in ungoogled-chromium doesn't work however, as google says:
https://user-images.githubusercontent.com/36833664/110196580-11847200-7e78-11eb-8738-a37213e14fb6.png

Is there anything I can do to make this work, or is this by design / won'tfix for you folks?

see https://github.com/floccusaddon/floccus/issues/847

**Comment by shaddybaddah** [comment]
I have this issue too. Hoping for a fix, or workaround

**Comment by PF4Public** [comment]
Closing this issue as a solution has been suggested above. Anyone coming here from outside, see also #1896.
