### ISSUE TITLE
Feature Request: Setting to reenable automatic formatting of URLs in Omnibox

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Eloston/ungoogled-chromium#1438]
I personally like how Chrome strips away the https:// and the www from the Omnibox, so I'd like to have an option to reenable it.

There are two possible ways to do this:
1. Use the normal setting from chrome (Right click -> Show full address bar), but it's enabled by default
2. Make a flag to change it back

**Comment by PF4Public** [comment]
Closing this issue in favour of #1051
