### ISSUE TITLE
Extended Stable Branch

### ISSUE THREAD

**Issue by travankor** [Eloston/ungoogled-chromium#1441]
https://www.ghacks.net/2021/03/05/google-decides-to-switch-to-a-4-week-release-cycle-for-chrome/

Chromium is somewhat difficult to rebase the patchset onto new versions, and upstream plans to speed up the release cadence. This makes it harder to keep track of potentially privacy-invasive features that ship.

It would be useful if there's support for Chromium's 8 week extended stable branch.

**Comment by PF4Public** [comment]
I believe we are coping with 4-week release cycle rather swift, as such there is no need for the Extended Stable presently.
