### ISSUE TITLE
[Android - Extension build] chrome://extension "load unpacked" option is broken

### ISSUE THREAD

**Issue by Beatz106** [Eloston/ungoogled-chromium#1442]
Universal Bypass has been used as an example (this extension is no longer available in the Google Chrome store, but it can be any that, as a requirement, needs to be downloaded directly)

**To Reproduce**
1. Go to the extension page (see URL in the address bar) and go to step 5.
![Screenshot_20210318-221210_Ungoogled_Chromium_Extensions](https://user-images.githubusercontent.com/74375581/111735612-ed466f00-8841-11eb-8188-21d78feb7e6b.png)

2. After clicking on "Load unpacked" the following menu appears in the style of "Open with" with only 2 options¹: 
![Screenshot_20210318-221847_Sistema_Android](https://user-images.githubusercontent.com/74375581/111736127-d9e7d380-8842-11eb-9253-c572a0548a2a.png)

2.1. **Procedure for the first option**

- 2.1.1. The file manager will ask for permission for the browser to have access to the current folder (obviously the folder with the content of the extension unzipped), the problem is that the change is not saved and it will ask for permission every time you want to install an extension from the file manager (this is not a system problem, it would already be reported previously)
![Screenshot_20210318-221858_Archivos](https://user-images.githubusercontent.com/74375581/111737261-e705c200-8844-11eb-9548-96aa202576e7.png)
![Screenshot_20210318-221913_Archivos](https://user-images.githubusercontent.com/74375581/111737283-f127c080-8844-11eb-8ae9-a455500bee44.png)

- 2.1.2. After granting access permission, the file manager closes, then returns to the browser with the following message:
![Screenshot_20210318-221930_Ungoogled_Chromium_Extensions](https://user-images.githubusercontent.com/74375581/111738013-3e586200-8846-11eb-980e-5670fd7ddfb1.png)

2.2 **Process for the second option**

- 2.2.1. This time the file manager is opened in another way, yes, it doesn't matter which file is selected, here the browser will crash.
![Screenshot_20210318-224705_Archivos](https://user-images.githubusercontent.com/74375581/111738505-1c131400-8847-11eb-8b81-13d5b89719b8.png)

**Expected behavior**
It should work the way Kiwi Browser does, the screenshots are in order of how the target extension was installed.
![Screenshot_20210318-225146_Sistema_Android](https://user-images.githubusercontent.com/74375581/111739015-ede20400-8847-11eb-902c-2c8b1bbadbc3.png)
![Screenshot_20210318-225224_Archivos](https://user-images.githubusercontent.com/74375581/111739031-f4707b80-8847-11eb-8410-17dfd69928b6.png)
![Screenshot_20210318-225233_Archivos](https://user-images.githubusercontent.com/74375581/111739036-fa665c80-8847-11eb-967f-f9c5f3dc1e92.png)
![Screenshot_20210318-225259_Kiwi_Browser](https://user-images.githubusercontent.com/74375581/111739054-00f4d400-8848-11eb-8548-9034553a6893.png)

**Environment (please complete the following information):**
 - OS/Platform and version: LineageOS 17, Android 10
 - ungoogled-chromium version: 88.0.4324.182

**Additional context**
¹The available options as well as the way the browser behaves with, for example, the default file manager will depend on the Android version and the ROM, especially with part 2.

**Comment by wchen342** [comment]
The extension version is discontinued.

**Comment by Beatz106** [comment]
> The extension version is discontinued.

This information must be provided by the leader / one of the project leaders, in addition, the source repository of such version should be archived

**Comment by wchen342** [comment]
I am the sole developer of the Android version of ungoogled-chromium. The repo is located at [ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android). You can browse through the commit histories if you have any doubts.

The relative patches of the extension version is archived at [wchen342/chromium-android-extension](https://github.com/wchen342/chromium-android-extension).

**Comment by Beatz106** [comment]
> I am the sole developer of the Android version of ungoogled-chromium. The repo is located at [ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android). You can browse through the commit histories if you have any doubts.
> 
> The relative patches of the extension version is archived at [wchen342/chromium-android-extension](https://github.com/wchen342/chromium-android-extension).

Okay, I'm not interested in your project. Greetings.

**Comment by wchen342** [comment]
> I'm not interested in your project

It is not *my* project. The Android repo is under [ungoogled-software](https://github.com/ungoogled-software) where `ungoogled-chromium` on different platforms are hosted, and it is recognized as part of `ungoogled-chromium` by @Eloston.

For future visitors, the project is organized loosely in a top-down, tree like manner, where the main repo hosts the core part of the patches and the different platform repos hosts platform specific stuff. Each platform-specific repo is maintained by different maintainers and they are only loosely connected to this main repo. There is no so-called "project leaders" except for Eloston who approve all pull requests to this core repo.
