### ISSUE TITLE
Automatic OS upgrade overwrites state

### ISSUE THREAD

**Issue by mkgvt** [Eloston/ungoogled-chromium#1443]
**Describe the bug**
When the OS automatically upgrades ungoogled chromium while an older version is running, the new version overwrites at least some of the state which causes things like open tabs to be forgotten.

**To Reproduce**
1. Upgrade ungoogled chromium while an older version is still running
2. Start new version and verify chrome://settings/help
        - It reports a problem with the profile. (Sorry, I didn't capture the message.)
        - It pops up "Restore pages? Chromium didn't shut down correctly." with a restart button
3. Shutdown new version
4. Shutdown old version
5. Restart (new).

The old tabs which should have been saved are gone. Only chrome://settings/help is open.

**Expected behavior**
It is expected that the tabs open in the older version should reopened in the new version.

As a workaround, the user can close the old version before upgrading manually. But the problem still remains if the versions are being upgraded by the OS.

**Environment (please complete the following information):**
 - OS/Platform and version: NixOS 64-bit 20.09.2660.da3378c4aaf, 20.09.3505.12d9950bf47
 - ungoogled-chromium version: 85.0.4183.102 (also 88.0.4324.150 88.0.4324.182 I think)

**Additional context**
This may be related to #1432. It may also be an artifact of the sync code being removed  #667.

This problem will likely happen anytime the OS upgrades automatically while an older version is running even if the ability to upgrade within ungoogled chromium is reimplemented independent of the Google API. (It may even happen for Chrome with the Google API.)

**Comment by mkgvt** [comment]
I don't know if this is related or not... Today, some tabs could not be dragged to a different window. The dragging worked but the new window didn't accept them. (This is after having upgraded to 89.0.4389.90 and verifying that all the running processes are from that version. This is trivial to do with NixOS due to the way that processes are referred to by the full path:)

```
$ ps x | awk '/chromium/{print $5}' | sort -u
/nix/store/kb29xi0wjvpxfdp5l42m9sjz9d8ml0nv-chromium-unwrapped-89.0.4389.90/libexec/chromium/chromium
```
Looking at a tree view of the running processes, there were three "base" chromium processes (chromium processes which are a child of a bash shell) each of which had a number of child chromium processes. I hypothesize that opening a new window from the desktop rather than from within an existing window caused the newly open window to have a different base process. 

I exited all three base chromium processes and restarted. (Except for two windows with their tabs, all the windows with their tabs came back up correctly. I was surprised.) Now there is only one base chromium process and all others are a child of them. Opening a new window from the the desktop must open in the base process because there is still only one base process when examined through the tree view of ps.

**Comment by mkgvt** [comment]
Sorry, I misspoke. Starting a new chromium from the desktop does not always make the window a child of an existing chromium process.

**Comment by PF4Public** [comment]
Is this still an issue?
