### ISSUE TITLE
No livestreams on YouTube.

### ISSUE THREAD

**Issue by 1Turtle** [Eloston/ungoogled-chromium#1446]
**Description of the bug**
When I try to watch a livestream in Youtube, instead of the video, I get the message **"Your browser can't play this video. _[Learn more](https://www.youtube.com/supported_browsers)_"**. _(I also can't play videos on reddit btw.)_

**To Reproduce:**
1. Go to **[YouTube](https://www.youtube.com/)**
2. Search for a livestream under the appropriate category
3. Click it

**Expected behavior**
Normally, a video or livestream would be started instead of the message.
On the other hand, videos in general already work. On twitter I can watch everything and on youtube normal videos work too.

**Screenshots**
![Screenshot-of-youtube-livestream](https://user-images.githubusercontent.com/53350357/112297284-001fd000-8c96-11eb-81a0-9026766105ac.png)

**Environment**
 - OS/Platform and version: **Fedora 33** (Workstatoin Edition)
 - ungoogled-chromium version: 89.0.4389.90 (Developer Build, ungoogled-chromium) (64-Bit)

**Comment by wchen342** [comment]
The OBS build cannot have proprietary codecs in ffmpeg. I think only some of the livestreams are affected. If you want to have all codecs you need to change `freeworld 1` in the spec file and rebuild with full source code.

**Comment by SteveGremory** [comment]
and uh, sorry to ask but how may i go about doing that? the source looks- New to me? never worked with chromium before.
Thanks in advance.

**Comment by SteveGremory** [comment]
any help?

**Comment by wchen342** [comment]
I have never tried building freeworld but you can use the original tar file from google instead of the clean one, then try either change `%gloabal freeworld 0` to 1 or just build with the new tar file.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
