### ISSUE TITLE
88.0.4324.182-1 for Windows 64-bit Crashes On Start

### ISSUE THREAD

**Issue by BrazenFox5** [Eloston/ungoogled-chromium#1447]
I installed via a installer, and it just crashed on start.

**To Reproduce**
1. Open app
2. See error

It works for like a nice 30 secs, then crashes.

https://i.imgur.com/JJRrYPY.gif

Ungoogled Chromium, 88.0.4324.182-1, installer

**Comment by Glubzor** [comment]
This has been solved in 89 version.
Use this one [https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/89.0.4389.90-1](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/89.0.4389.90-1)
Many thanks to  @tangalbert919

**Comment by BrazenFox5** [comment]
> This has been solved in 89 version.
> Use this one https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/89.0.4389.90-1
> Many thanks to @tangalbert919

Oh ok thanks.
