### ISSUE TITLE
Create Organization

### ISSUE THREAD

**Issue by nopjmp** [Eloston/ungoogled-chromium#145]
To speed up the development cycle and to give badges to contributors in the issue tracker, I propose creating a "Ungoogled" organization or another name. "Ungoogled" is fairly close to "Google" and may allow them to take down the project / group if they decided.

This way, downloads should be able to be posted by members of the organization. I haven't used organizations on GitHub personally, but I believe members have the power to make releases and upload files.

This would also allow anyone including Eloston to leave the project if they decide they do not want to do it anymore and the project can continue.

**Comment by Eloston** [comment]
Hmm, the permission control and team features look pretty enticing. I'll check this out.

**Comment by Eloston** [comment]
Update: I've created a new organization called [ungoogled-software](https://github.com/ungoogled-software). Going to try it out for binary downloads and syzygy swapimport before moving this repository over to get a better feel for how it will work.

**Comment by nopjmp** [comment]
It might also be a good idea to create an IRC channel or a channel on another messaging system. It might be able to help keep issues done and help point people to older issues that were resolved.

**Comment by Eloston** [comment]
[How about Gitter](https://gitter.im/)?

**Comment by nopjmp** [comment]
I haven't used gitter before Ive mainly used slack and discord. I'll check it out.

Sent from my android device.

-----Original Message-----

**Comment by Eloston** [comment]
[I've created a new Gitter room for ungoogled-software](https://gitter.im/ungoogled-software/Lobby). The permissions that Gitter requests are pretty nice.

**Comment by DeadSix27** [comment]
Probably should close this now.

**Comment by Eloston** [comment]
I haven't figured out how to setup the organization and how to transition everything over yet, but we can discuss this more on Gitter.

Closing for now.
