### ISSUE TITLE
Widevine instructions are incorrect 

### ISSUE THREAD

**Issue by HairyMilkshakes** [Eloston/ungoogled-chromium#1454]
On the webpage it states that the Widevine DRM contents must be extracted to the User Data in the app folder and that's incorrect: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#windows

The Widevine files (if extracted from the Google Chrome offline installer files) must be placed into Chromium -> Application -> (Current Version folder) under AppData in order to be detected by the browser.

**Comment by Eloston** [comment]
Fixed.
