### ISSUE TITLE
extensions Multi Chat - Messenger for Whatsapp cannot be used in ungoogled-chromium

### ISSUE THREAD

**Issue by candrapersada** [Eloston/ungoogled-chromium#1455]
why can't [Multi Chat - Messenger for Whatsapp](https://chrome.google.com/webstore/detail/multi-chat-messenger-for/dllplfhjknghhdneiblmkolbjappecbe) be used on ungoogled-chromium?
![image](https://user-images.githubusercontent.com/36833664/112713502-0ddc8c00-8f08-11eb-938c-b520e9ded376.png)

**Comment by jacob755** [comment]
set user agent see if its work

--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"

if above wont work allow all cookie
allow all cookie
**chrome://settings/cookies?search=cookie**

if still above wont work
enable bellow in chrome://flags/
**Storage Access API**
if still not work also enable 
**Access contexts for client-side storage**
 in a chrome://flags/

**Comment by candrapersada** [comment]
> set user agent see if its work
> 
> --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"

how to set user agent for extensions Multi Chat - Messenger for Whatsapp?

**Comment by jacob755** [comment]
> > set user agent see if its work
> > --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> 
> how to set user agent for extensions Multi Chat - Messenger for Whatsapp?
> or
use this read how use it
https://github.com/eladkarako/iniRun


> > allow all cookie
> > chrome://settings/cookies?search=cookie
> 
> how to allow cookie only for extensions Multi Chat - Messenger for Whatsapp without allow all cookie?
for cookie whitelist this maybe work maybe not otherwise i don't know
https://multi-chat.net
https://web.whatsapp.com

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
