### ISSUE TITLE
Updated from fedora 33 to fedora 34, ungoogled chromium literally won't show text

### ISSUE THREAD

**Issue by vinliao** [Eloston/ungoogled-chromium#1456]
**Describe the bug**
For whatever reason, the text in ungoogled-chromium's webpages doesn't appear

**To Reproduce**
1. Install fedora 34
2. Install ungoogled-chromium
3. Use it

**Expected behavior**
I want the text to appear.

**Screenshots**
![Screenshot from 2021-03-27 23-29-45](https://user-images.githubusercontent.com/34117807/112727712-60dd3000-8f56-11eb-8a21-baee831ec27a.png)
![Screenshot from 2021-03-27 23-30-05](https://user-images.githubusercontent.com/34117807/112727715-620e5d00-8f56-11eb-88f4-eea5cce4dfe2.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Fedora 34
 - ungoogled-chromium version: 88.0.4324.96-1.fc34

**Comment by git-bruh** [comment]
This might be the glibc 2.33 issue, you'll need a binary that's built with [this](https://github.com/archlinux/svntogit-packages/blob/packages/chromium/trunk/chromium-glibc-2.33.patch) patch. https://crbug.com/1164975

Can you check if running `chromium --no-sandbox` in a terminal fixes it ? (Don't disable the sandbox in regular usage though, just for testing)

**Comment by vinliao** [comment]
Update: using `--no-sandbox` fixes the text issue.

![Screenshot from 2021-03-28 17-29-54](https://user-images.githubusercontent.com/34117807/112749394-52d9ee80-8fec-11eb-8278-e1366ed3ce4e.png)

**Comment by wchen342** [comment]
I didn't include patches for Rawhide because OBS cannot build them. The fix shall be included once F34 is out.

**Comment by wchen342** [comment]
v90 for F34 is available from the OBS repository now.

**Comment by PF4Public** [comment]
Is this still an issue?

**Comment by wchen342** [comment]
I doubt it but let's wait for reply.
