### ISSUE TITLE
Building latest version (based on chromium-89.0.4389.90.tar.xz) fails on Arch

### ISSUE THREAD

**Issue by raxamit** [Eloston/ungoogled-chromium#1457]
Building project on Archlinux fails with following error:

"In file included from ../../media/gpu/vaapi/vaapi_utils.cc:18:
../../third_party/libva_protected_content/va_protected_content.h:136:14: error: redefinition of '_VA_TEE_EXEC_FUNCTION_ID'
typedef enum _VA_TEE_EXEC_FUNCTION_ID {
             ^
/usr/include/va/va_prot.h:405:14: note: previous definition is here
typedef enum _VA_TEE_EXEC_FUNCTION_ID {
             ^
In file included from ../../media/gpu/vaapi/vaapi_utils.cc:18:
../../third_party/libva_protected_content/va_protected_content.h:163:16: error: redefinition of '_VAEncryptionSegmentInfo'
typedef struct _VAEncryptionSegmentInfo {
               ^
/usr/include/va/va.h:2044:16: note: previous definition is here
typedef struct _VAEncryptionSegmentInfo {
               ^
In file included from ../../media/gpu/vaapi/vaapi_utils.cc:18:
../../third_party/libva_protected_content/va_protected_content.h:183:16: error: redefinition of '_VAEncryptionParameters'
typedef struct _VAEncryptionParameters {
               ^
/usr/include/va/va.h:2064:16: note: previous definition is here
typedef struct _VAEncryptionParameters {
               ^
3 errors generated.
[24786/44930] CXX obj/components/policy/core/common/internal/cloud_policy_client.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting..."

After a brief investigation I found that chromium-89.0.4389.90 defines **_VA_TEE_EXEC_FUNCTION_ID**,  **_VAEncryptionSegmentInfo** and **VAEncryptionParameters** in a file "_chromium-89.0.4389.90/third_party/libva_protected_content/va_protected_content.h_". The very same symbols are defined in **libva** library (which is listed as a dependency) header file "_va_prot.h_".
Not sure what can be done on a ungoogled-chromium side; though, it seems that this issue was fixed in the most recent version of chromium as its "_va_protected_content.h_" no longer contains these conflicting  redefinitions.

**Comment by git-bruh** [comment]
You can just get the patch file from the commit that fixed it and apply it in the PKGBUILD: https://github.com/chromium/chromium/commit/e0b362edd9b49143b89fc76c4a31dd5603b6fbd0.patch

This is due to the latest libva update.

**Comment by braewoods** [comment]
This has been addressed in the repository for Arch packaging.

**Comment by Eloston** [comment]
Closing as resolved
