### ISSUE TITLE
Enable Pin to Shelf or Creating Shortcuts

### ISSUE THREAD

**Issue by abakasam** [Eloston/ungoogled-chromium#1458]
I need to enable, chrome://flags/#enable-desktop-pwas-app-icon-shortcuts-menu, but it shows:

Not available on my platform

My computer:

Ungoogled Chromium 89.0.4389.90
Android 9
Acer Chromebook 15 (CB3-532) Build/R89-13729.56.0

Tried in order:

https://www.androidcentral.com/how-pin-apps-and-shortcuts-shelf-chromebook
https://jonnorris.work/add-websites-apps-chrome-os-shelf/
https://winaero.com/enable-pwas-app-icon-shortcut-menu-in-chrome-and-edge/

![Screenshot 2021-03-29 5 05 03 AM](https://user-images.githubusercontent.com/58202540/112822645-d546ca80-904d-11eb-9d68-d7ad6f6a8194.png)

Sam

**Comment by abakasam** [comment]
May you compile ungoogled-chromium as an APK? https://github.com/Eloston/ungoogled-chromium

I believe the issue comes from using ungoogled-chromium-android an an APK. The disabled features needed for a Chromebook. https://github.com/ungoogled-software/ungoogled-chromium-android

![Screenshot 2021-04-06 6 40 36 PM](https://user-images.githubusercontent.com/58202540/113790777-c88a3c80-9707-11eb-855a-769334fe5ce0.png)
![Screenshot 2021-04-06 6 41 37 PM](https://user-images.githubusercontent.com/58202540/113790780-c922d300-9707-11eb-9a03-6e31f0548c20.png)

Sam

**Comment by abakasam** [comment]
May someone add: Add to Home Screen or Create Shortcut . For X86 of Ungoogled Chromium...

It is missing for Chromebook.

- Android (LG Aristo 4+): https://www.mediafire.com/file/s3iorwpe6wggzp2/ChromeModernPublic_arm.apk/file
- Android (OnePlus 3): https://www.mediafire.com/file/92wc6itln1oaena/ChromeModernPublic_arm64.apk/file
- Chrome (Acer Chromebook 15): https://www.mediafire.com/file/d4vuqsmbp5skwj9/ChromeModernPublic_x86.apk/file

Click image to see better.

Sam

Android (LG Aristo 4+) | Android (OnePlus 3) | Chrome (Acer Chromebook 15)
------------ | --------------|--------------
![Aristo 4+](https://user-images.githubusercontent.com/58202540/119059476-01b7fc80-b996-11eb-8124-1bdff0d12fd0.png) | ![Screenshot_20210520-150236](https://user-images.githubusercontent.com/58202540/119059543-244a1580-b996-11eb-8c85-895f86e6818c.jpg) | ![Chrome](https://user-images.githubusercontent.com/58202540/119059567-31ff9b00-b996-11eb-8b32-8d25af68ed9e.png)

**Comment by abakasam** [comment]
Click on third image to enlarge. Is there any progress?

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android)
