### ISSUE TITLE
Shortcut settings don't save via new tab page

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#1459]
**Describe the bug**
When changing shortcut settings in chrome://new-tab-page, they don't save.

**To Reproduce**
1. Go to `chrome://new-tab-page`
2. Click on `Customize` in the bottom right
3. Click on `Shortcuts`
4. Change a setting
5. See error; setting doesn't save after exiting.

**Expected behavior**
The setting is supposed to save.

**Environment (please complete the following information):**
 - OS/Platform and version: `macOS, arm64`
 - ungoogled-chromium version: `Version 89.0.4389.90 (Official Build, ungoogled-chromium) (arm64)`

**Additional context**
This might just be a bug for the macOS arm64 version — I haven't tried it on other platforms. Likely not platform specific, but _maybe_.

**Comment by SafwanLjd** [comment]
I'm having the same problem on Windows 10 x86_64

It's annoying as hell, I hope they fix it

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
