### ISSUE TITLE
Unable to start - Couldn't mmap icu data file

### ISSUE THREAD

**Issue by buralien** [Eloston/ungoogled-chromium#1471]
**Describe the bug**
After the update of ungoogled-chromium (89.0.4389.114-1.focal1) over (84.0.4147.135-1.focal1) on Ubuntu 20.04, I am unable to start it - it stops immediatelly. The error message is:
```
[0407/164435.271519:ERROR:icu_util.cc(248)] Couldn't mmap icu data file
[0407/164435.271632:FATAL:content_main_delegate.cc(35)] Check failed: false.
#0 0x55c76e98a699 <unknown>
Aborted (core dumped)
```

**To Reproduce**
1. Start `chromium` from the command line or through a desktop shortcut
2. The process stops with the error above immediately

**Expected behavior**
Start ungoogled-chromium browser, or present a better error.

**Environment (please complete the following information):**
 - OS/Platform and version: Ubuntu 20.04 64-bit
 - ungoogled-chromium version: 89.0.4389.114-1.focal1

**Additional context**
I have been using the previous version(s) for many months before this update without any issues.

**Comment by git-bruh** [comment]
Does `/usr/lib/chromium/icudtl.dat` exist ? The error is usually related to that file.

**Comment by enjoydambience** [comment]
I am also running Ubuntu 20.04 and encountering the exact same issue.
 `/usr/lib/chromium/icudtl.dat` indeed does not exist.
 
 Will be downgrading for now

**Comment by buralien** [comment]
I confirm that `/usr/lib/chromium/icudtl.dat` does not exist on my machine either.

```
bur@pc ~> ls -1 /usr/lib/chromium/
chrome_100_percent.pak
chrome_200_percent.pak
chrome-sandbox
chromium
libEGL.so
libGLESv2.so
locales
resources.pak
snapshot_blob.bin
v8_context_snapshot.bin
```

**Comment by macbeto** [comment]
I confirm the same error with Linux Mint 20.1. I did a rollback to the previous version for now.

**Comment by nicklyk** [comment]
@macbeto How did you rollback to the previous version? 

I'm running Ubuntu 20.04

**Comment by enjoydambience** [comment]
A temporary fix can be found here: https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/218#issuecomment-814906091

**Comment by nicklyk** [comment]
Sweet! It works again.
It's throwing some errors/warning at me though. Might be unrelated..

`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[8696:8696:0407/222724.490525:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[8696:8696:0407/222725.783893:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 1 times!
[8696:8696:0407/222726.280866:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 2 times!
[8696:8696:0407/222726.288454:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 3 times!
`

**Comment by braewoods** [comment]
Problem should be resolved once the new build finishes.

**Comment by braewoods** [comment]
Please report any further issues directly in the Debian repository. I do not check this one as frequently.

**Comment by buralien** [comment]
I confirm that after installing the new build of ungoogled-chromium (89.0.4389.114-1.focal2) over (89.0.4389.114-1.focal1), this problem is resolved.
