### ISSUE TITLE
Edge in tab hover cards

### ISSUE THREAD

**Issue by fabriziobagala** [Eloston/ungoogled-chromium#1475]
**Describe the bug**
When I place the cursor over a tab, a popup appears showing me the title and address of the tab. Often this popup does not have a black border and a shadow.

**To Reproduce**
1. Place the cursor over a tab
2. See error

**Expected behavior**
The popup has both a black border and a shadow.

**Screenshots**

![image](https://user-images.githubusercontent.com/62190484/114280520-efaf7980-9a39-11eb-8aaf-710562158e2b.png)

**Environment:**
 - OS/Platform and version: **macOS Big Sur 11.2.3**
 - ungoogled-chromium version: **89.0.4389.114 (Official Build, ungoogled-chromium) (x86_64)**

**Comment by vairag22** [comment]
Both are unexpected behavior. The correct behavior should be no black border but a shadow (which gives a hovering feel).

**Comment by fabriziobagala** [comment]
> Both are unexpected behavior. The correct behavior should be no black border but a shadow (which gives a hovering feel).

I got it. Then this is a graphical issue.

**Comment by fabriziobagala** [comment]
This issue has been fixed in version 90.0.4430.72.
