### ISSUE TITLE
Is that possible to install ungoogled chromium for all users?

### ISSUE THREAD

**Issue by ivan123-ru** [Eloston/ungoogled-chromium#1478]
I use Windows build of of ungoogled chromium 89.0.4389.114.
Is there any way to install it for all users?

**Comment by osyu** [comment]
You can run the installer with the `--system-level` command-line argument to install for all users.

**Comment by ivan123-ru** [comment]
> You can run the installer with the `--system-level` command-line argument to install for all users.

Thanks!
