### ISSUE TITLE
Feature request: Jumplist on Windows

### ISSUE THREAD

**Issue by osyu** [Eloston/ungoogled-chromium#1479]
Stock Google Chrome has a jumplist for opening a new window (and incognito window):
![UpPoUDuvkz](https://user-images.githubusercontent.com/8067918/114480950-89f5f580-9bd1-11eb-9251-f3718cc2bfc2.png)

Chromium doesn't (both normal and ungoogled):
![image](https://user-images.githubusercontent.com/8067918/114481055-c45f9280-9bd1-11eb-9004-6eeba14a2642.png)

Coming from other browsers that have a jumplist like this, it'd be nice to have it here too.

**Comment by qualityrice** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/1370

**Comment by osyu** [comment]
Ah gotcha, closing as duplicate
