### ISSUE TITLE
Version 55 Update for Windows???

### ISSUE THREAD

**Issue by WackyModder84** [Eloston/ungoogled-chromium#148]
I'm glad to finally see that we got a Version 55 Update for UnGoogled.
But when can Windows Users like myself expect to see our browsers finally updated too? =)

**Comment by Eloston** [comment]
We're working this out in #147. Almost there!

**Comment by Eloston** [comment]
#147 has been merged. I am going to make builds now (x64 and x86) and upload them.

**Comment by Eloston** [comment]
Binaries are up now.
