### ISSUE TITLE
Permanently deny access to the keychain

### ISSUE THREAD

**Issue by fabriziobagala** [Eloston/ungoogled-chromium#1489]
**Describe the bug**
Whenever I open Ungoogled Chromium I always get this message requesting access to the keychain.

**To Reproduce**
1. Open Ungoogled Chromium
2. See error

**Expected behavior**
Ability to opt out of giving consent to keychain access permanently.

**Screenshots**
![image](https://user-images.githubusercontent.com/62190484/114846857-63a4a580-9ddd-11eb-9b1d-df1f22a46f15.png)

**Environment:**
 - OS/Platform and version: **macOS Big Sur 11.2.3**
 - ungoogled-chromium version: **89.0.4389.114 (Official Build, ungoogled-chromium) (x86_64)**

**Comment by Ahrotahn** [comment]
Adding `--password-store=basic` to the launch switches should remove that dialog.

**Comment by fabriziobagala** [comment]
> Adding --password-store=basic to the launch switches should remove that dialog.

Unfortunately this command does not remove the dialog

**Comment by Ahrotahn** [comment]
It seems like that might be a [mac-specific issue](https://bugs.chromium.org/p/chromium/issues/detail?id=880522).

Does adding `--use-mock-keychain` instead help?  If that doesn't work, you could also try `--disable-features=NetworkService`, but I'd recommend trying the other one first.

**Comment by fabriziobagala** [comment]
> Does adding `--use-mock-keychain` instead help?

Yes, by adding this command the dialog disappears.
