### ISSUE TITLE
AppImage 89.0.4389.114-1 ?

### ISSUE THREAD

**Issue by atuctuc** [Eloston/ungoogled-chromium#1493]
hallo,
does anyone know if the AppImage version 89.0.4389.114-1 is also available for download somewhere?

if so, could someone share a download link?
thanks; 
anan

**Comment by christianitus03** [comment]
Yeah, the portable and appimage releases are pretty neglected. Hopefully the owner sees this and updates them!

**Comment by mdedonno1337** [comment]
Some work is done on the repo (https://github.com/ungoogled-software/ungoogled-chromium-portablelinux).
Reading at the moment the doc on the https://github.com/ungoogled-software/ungoogled-chromium-binaries repository to make the PR for the appimage for the version 90.0.4430.85 (probably also the 89, we will see).

**Comment by mdedonno1337** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/243

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
