### ISSUE TITLE
Getting an error when trying to compile on Debian Stretch

### ISSUE THREAD

**Issue by 9Morello** [Eloston/ungoogled-chromium#15]
I'm getting the following error when I try to compile it in Debian Stretch.
./build_debian.sh: line 32: RUN_SOURCE_CLEANER: unbound variable

Its a clean install.

**Comment by Eloston** [comment]
Oops, I forgot to update my instructions to use a tag release instead of the HEAD.

The HEAD will not always be in a working state. You need to use a tag release.
