### ISSUE TITLE
Chromium is insanely slow to startup on Debian due to lsb_release being slow

### ISSUE THREAD

**Issue by hjri** [Eloston/ungoogled-chromium#1504]
**Describe the bug**
Trying to start ungoogled-chromium can take up to 2 minutes, because startup script calls `lsb_release` (which calls `apt-cache`) which can take a lot of time, i.e. just running plan `lsb_release` takes up **28 SECONDS** on this particular machine.

**To Reproduce**
1. be me
2. start chromium
3. wait for it
4. wait for it
5. wait for it
6. wait for it
7. wait for it
8. minute has passed and ungoogled-chromium has started

**Expected behavior**
ungoogled-chromium is about as fast to start as stock chromium

**Screenshots**
none

**Environment (please complete the following information):**
 - OS/Platform and version: Linux x64 Debian bullseye/sid
 - ungoogled-chromium version: 89.0.4389.114-1.buster1

**Additional context**
My current solution is to monkey-patch the chromium script like so:

replace
```
DIST=`printf "%s %s/%s" $(lsb_release -si) $(lsb_release -sc) $(lsb_release -sr)`
```
with
```
DIST=`printf "%s %s/%s" ASS ASS ASS`
```

**Comment by hjri** [comment]
This also makes opening links from other applications just as slow

**Comment by braewoods** [comment]
The normal delay is usually less than 300ms for this portion. I've implemented a more efficient alternative that replaces this and it will become available in the next release.

Though I have to wonder what you're doing differently that lsb_release would choke so badly. This kind of delay is magnitudes higher than typical and makes me think your system is being seriously overloaded if something like lsb_release is experiencing this much delay.

**Comment by hjri** [comment]
well, most likely it's not the `lsb_release` itself choking but rather `apt-cache` it calls, and that takes long time due to quite complex apt-pinning i have in place (so that KDE and MESA are pulled from unstable while rest of the system uses testing, yeah yeah frankendebian i know).

that's just a guess and an observation from looking at process tree while chromium boots

**Comment by braewoods** [comment]
It should be implemented in the current OBS builds. Please close this issue if your problem is resolved.

**Comment by hjri** [comment]
yeah, it opens blazingly fast now, many thanks!
