### ISSUE TITLE
Request to package `ungoogled-chromium-bin` into the AUR

### ISSUE THREAD

**Issue by paniash** [Eloston/ungoogled-chromium#1507]
**Is your feature request related to a problem? Please describe.**

The current installation instructions for installing on Arch linux involve either adding an OBS repository or an unofficial one such as chaotic-aur. A lot of Arch users install using the AUR but it doesn't contain a binary build of ungoogled-chromium.

A part of this frustration comes about when using third-party repositories as mentioned [here](https://github.com/ungoogled-software/ungoogled-chromium-archlinux) where I seem to receive a segmentation fault when installing using this medium. See [this issue](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/124) for more info.

**Describe the solution you'd like**

To package a binary of ungoogled-chromium into the AUR.

**Describe alternatives you've considered**
Installing the `ungoogled-chromium` package from the AUR but that would involve compiling it locally on my machine.

**Comment by networkException** [comment]
Hello, I'm one of the maintainers of ungoogled-chromium-archlinux. I think it would be more fitting to open this issue there. Adding a `-bin` package to the aur is definitely something I have planned to add in the future, right now however I'm still busy working on overhauling the existing build process

**Comment by paniash** [comment]
@networkException Hi! Glad to hear the future plans for the same! Thanks.

**Comment by braewoods** [comment]
We're currently faced with an issue with Arch that keeps the package from building so not much we can do at present.

**Comment by paniash** [comment]
@braewoods Is that an issue from Arch's side? But it would be really cool to see a `-bin` in the AUR. :-)

**Comment by braewoods** [comment]
It appears to be as it also impacts their official chromium package. We have no idea how they manage to succeed with building it.

**Comment by wchen342** [comment]
@Jstkdng Have you tried to submit a `-bin` package lately?

Haven't been on Arch for some time but once there was a `-bin` package on AUR but it was removed by moderators.

**Comment by jstkdng** [comment]
@wchen342 yeah, there was, and I was the maintainer. It was deleted due to security concerns or something since I used my binaries.

**Comment by paniash** [comment]
@jstkdng How do other binary packages exist then? for example, the AUR has both `brave` and `brave-bin` packages.

**Comment by jstkdng** [comment]
@paniash 
They exist because they use "official" binary distributions, be it for other distros like debian or ubuntu, or portable binaries.

When uc-bin was taken down I was using my arch binaries and repackaging the contents into another package, here's the [PKGBUILD](https://github.com/jstkdng/ungoogled-chromium-bin/blob/master/PKGBUILD) since at that point uc-portablelinux was outdated and the debian/ubuntu ones always have linking problems when something in arch gets updated.
Portablelinux is the best solution for our -bin package without breaking the rules of repackaging.

**Comment by PF4Public** [comment]
Closing in favor of the linked issue at the ungoogled-software/ungoogled-chromium-archlinux repository.
