### ISSUE TITLE
Request for an openSUSE binary or help on creating one.

### ISSUE THREAD

**Issue by Pepperspraylaugh** [Eloston/ungoogled-chromium#1509]
**Is your feature request related to a problem? Please describe.**
openSUSE lacks a binary, and seems to be incompatible with the Fedora package and/or dependencies. I used the AppImage for a bit but it doesn't seem to be acceptable for me anymore.

**Describe the solution you'd like**
A downloadable binary for openSUSE/similar replacement, or help on how I could make a binary myself.

**Describe alternatives you've considered**
I've considered dropping the UG files onto a chromium install but I really don't want to disable SUID sandboxes.

**Comment by wchen342** [comment]
I am the maintainer of Fedora package. Maybe you can start with the OpenSUSE official chromium package [on OBS here](https://build.opensuse.org/package/show/network:chromium/chromium) and modify their `spec` file to apply the patches, domain substitutions, etc.?

**Comment by danfos** [comment]
For OpenSuse the [Portable Linux 64-bit](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/) package works fine.

Just download the package, untar it somewhere and run it. For the current latest version:

```
tar xf ~/Downloads/ungoogled-chromium_90.0.4430.93-1.1_linux.tar.xz
ungoogled-chromium_90.0.4430.93-1.1_linux/chrome &
```

There a quite some OBS builds, see https://build.opensuse.org/search?search_text=ungoogled-chromium
[This one](https://build.opensuse.org/package/show/home:justkidding:arch/ungoogled-chromium) seems to be quite up-to-date.

**Comment by danfos** [comment]
There is also #1211

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
