### ISSUE TITLE
Apparently, the flatpak package uses an outdated version of openh264

### ISSUE THREAD

**Issue by wittytweezers** [Eloston/ungoogled-chromium#1512]
When I first installed UC, I ran into the jittery video problem mentioned in other issues. Apparently, it's been fixed recently. But before that, I tried several things to fix it, one of which was to install the latest branch of openh264, and remove the other one (branch 2.0). Then I noticed that whenever I updated chromium, that branch (2.0) was reinstalled. So I thought maybe that specific version was used as a dependency (I don't know much about flatpak, so I might be wrong). I've looked through the previous issues (both open and closed), and this doesn't seem to have been addressed before.

**Comment by rany2** [comment]
This should be fixed as of https://github.com/flathub/com.github.Eloston.UngoogledChromium/commit/52cc528ffa6194f2e6c725e4ce1e8103e15a9f6f in the latest flatpak UG version.
