### ISSUE TITLE
stop loading anything under chrome-search://local-ntp

### ISSUE THREAD

**Issue by jacob755** [Eloston/ungoogled-chromium#1513]
**Is your feature request related to a problem? Please describe.**

the problem is when i start browser or click + button to create new tab and pasting any url 
if i wont wait for 2 second or more title bar show chrome-search://local-ntp/local-ntp.html
and pasted url wont open. Seems many have same problem when googling
i disabled all ntp flag added --disable-top-sites but still happen
i try extension that replace new tab page but still slowdown happen

**Describe the solution you'd like**

the thing i want is flag to disable any html js css that load in background in a chrome-search://local-ntp
so pure blank white page ready o paste or browse no top site or whatever was in a new tab page. And this is a Optional so if anyone want that behavior
still have it

according to here seems html js css loding 
https://chromium.googlesource.com/experimental/chromium/src/+/d07ec0748f7e29857bf61a19e1e452aa89daa7c1/chrome/browser/resources/local_ntp

**Describe alternatives you've considered**
can be disabled by patch  for everyone?!
**Additional context**

**Comment by networkException** [comment]
I have personally never experienced that issue, does it occur when using a different user data directory (set using `--user-data-dir`, see https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#overriding-the-user-data-directory)

**Comment by jacob755** [comment]
there is a no difference

**Comment by guest271314** [comment]
Even though on first run the option is provided to customize the page, hiding "tiles" and "cards" does not work Issue 1192882: After disabling tiles and cards they still appear on chrome://newtab https://bugs.chromium.org/p/chromium/issues/detail?id=1192882 is marked as 'WontFix'

> In general, NTPs are considered an integral part of Chrome's UI. Turning off JS will break the experience and so we don't allow this. You can also not set an arbitrary page as your NTP. This is currently by design. Closing this bug as WAI.

The workaround I use is a Chrome extension, see 
Simplest extension (unpacked, non-CWS) to disable JavaScript on new tab page https://groups.google.com/a/chromium.org/g/chromium-extensions/c/aH4kwzUqGXk/m/V2b5Af_MBAAJ.

```
{
  "name": "tab",
  "version": "1.0",
  "manifest_version": 3,
  "chrome_url_overrides" : {
    "newtab": "./blank.html"
  }
}
```

blank.html

```<!doctype html><html><body></body></html>```

**Comment by jacob755** [comment]
> Even though on first run the option is provided to customize the page, hiding "tiles" and "cards" does not work Issue 1192882: After disabling tiles and cards they still appear on chrome://newtab https://bugs.chromium.org/p/chromium/issues/detail?id=1192882 is marked as 'WontFix'
> 
> > In general, NTPs are considered an integral part of Chrome's UI. Turning off JS will break the experience and so we don't allow this. You can also not set an arbitrary page as your NTP. This is currently by design. Closing this bug as WAI.
> 
> The workaround I use is a Chrome extension, see
> Simplest extension (unpacked, non-CWS) to disable JavaScript on new tab page https://groups.google.com/a/chromium.org/g/chromium-extensions/c/aH4kwzUqGXk/m/V2b5Af_MBAAJ.
> 
> ```
> {
>   "name": "tab",
>   "version": "1.0",
>   "manifest_version": 3,
>   "chrome_url_overrides" : {
>     "newtab": "./blank.html"
>   }
> }
> ```
> 
> blank.html
> 
> `<!doctype html><html><body></body></html>`

its appear it wont override this new one `chrome://new-tab-page-third-party`

**Comment by guest271314** [comment]
What is the source of that URL? The user would need to type out that URL in the address bar to not navigate to the new tab page the extension sets?

**Comment by jacob755** [comment]
> user would need to type out that URL in the addre
its seems load something in background.the above extension load correct but this new address load something for sure 



from [here](https://superuser.com/questions/1652797/what-is-a-new-tab-page-third-party-in-chrome)

https://github.com/chromium/chromium/blob/52c4e0d606a975dc5c1315422fb31db9e4406782/chrome/common/webui_url_constants.cc#L130-L132
https://github.com/chromium/chromium/commit/dc334612cb78fa2233eb34c1355b6ee905f57cdc

**Comment by PF4Public** [comment]
Is this still an issue?

**Comment by jacob755** [comment]
waiting for x86 version then test its solved or not
thanks

**Comment by jacob755** [comment]
seems working thanks

**Comment by jacob755** [comment]
it was working good until i have low history cache and its back
but extension method still better work
