### ISSUE TITLE
No option to enable encrypted DNS & no option to disable icons on the new tab

### ISSUE THREAD

**Issue by methane4** [Eloston/ungoogled-chromium#1515]
**Describe the bug**
No option to enable encrypted DNS on chrome://settings/security.
No option to disable icons on the new tab.

**Expected behavior**
The ability to enable dns and disable icons on the new tab

**Screenshots**
![Screenshot from 2021-05-09 20-02-14](https://user-images.githubusercontent.com/46012160/117583872-83d83380-b101-11eb-9a94-42b564b66f4d.png)

![Screenshot from 2021-05-09 20-03-14](https://user-images.githubusercontent.com/46012160/117583983-33ada100-b102-11eb-9c9b-35be13e6816a.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Fedora Linux with Gnome 40
 - ungoogled-chromium version: Version 90.0.4430.93 (Official Build, ungoogled-chromium) (64-bit) (flatpak)

**Comment by wittytweezers** [comment]
About the encrypted DNS issue, it's likely because it uses google's DNS servers. I'm not quite sure though. 
Anyway, I think you'd be better off setting up encrypted DNS system wide, with something like [stubby](https://www.linuxbabe.com/ubuntu/ubuntu-stubby-dns-over-tls), that allows you to select which servers to use.

**Comment by methane4** [comment]
@wittytweezers im not sure, what i read was that it would check what dns your system is using and just give it a go for encryption to be used if the dns server supports it. maybe someone has documentation about it

**Comment by Ahrotahn** [comment]
For some reason linux is excluded from enabling DoH in upstream Chromium:  https://source.chromium.org/chromium/chromium/src/+/refs/tags/94.0.4606.81:chrome/common/chrome_features.cc;l=311

Is that image from Chrome on linux?  I'm surprised they would change that option in Chrome but not Chromium.  

---

I have a couple patches that I'll submit sometime after 94.0.4606.81 is merged that should help with the icons on the new tab page.  One adds a flag for the existing switch `--disable-top-sites` which removes them, the other will allow the new tab page to be replaced entirely.

**Comment by PF4Public** [comment]
> I have a couple patches

@Ahrotahn By any chance have you played with the number of ntp links displayed? I once wanted to increase the number of suggested top sites, but couldn't make it display more. :(

**Comment by gothmog123** [comment]
brave on linux has the secure dns option

**Comment by methane4** [comment]
> brave on linux has the secure dns option, somehow

Yes, i confirm.
![Screenshot from 2021-10-19 05-23-41](https://user-images.githubusercontent.com/46012160/137843625-20e8e073-2bcf-4c35-8d6e-7cfa648b0151.png)
