### ISSUE TITLE
Update windows binary

### ISSUE THREAD

**Issue by lenincritus** [Eloston/ungoogled-chromium#1519]
It's been three weeks since the v90 update and there's still no windows binary for that. Can anyone please upload a windows v90 binary .exe ?

**Comment by jacob755** [comment]
@tangalbert919 please update

**Comment by intox25** [comment]
From what i understood there an error that is hard to fix : https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/84
People that knows more than me might be able to help tangalbert919

**Comment by nullpenguinexception** [comment]
Try downloading "Ungoogled" one on [here](https://chromium.woolyss.com/#windows-64-bit). It's always up to dated and they apply patches from Eloston's releases.

**Comment by jlanzarotta** [comment]
> Try downloading "Ungoogled" one on [here](https://chromium.woolyss.com/#windows-64-bit). It's always up to dated and they apply patches from Eloston's releases.

I tried several of those alternatives; however, they did not work for me...  Any idea if the original repo will have an updated Windows version soon?

**Comment by nullpenguinexception** [comment]
> > Try downloading "Ungoogled" one on [here](https://chromium.woolyss.com/#windows-64-bit). It's always up to dated and they apply patches from Eloston's releases.
> 
> I tried several of those alternatives; however, they did not work for me... Any idea if the original repo will have an updated Windows version soon?

I don't know much about the [issue](https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/84) but it looks like it's about resource compiler error mentioned [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/7ba8eb72-12e9-4c78-af68-7f50c170040f/warning-rc4011-and-error-rc2188?forum=vclanguage), [can be useful](https://stackoverflow.com/questions/1738640/visual-studio-2008-preprocessor-wierdness). I guess tangalbert got an error because of a experimental dependency that Eloston uses after version 90. He tries to fix it in PR but I don't know much, Woolyss version is enough to me for now.

**Comment by tomasz1986** [comment]
> Try downloading "Ungoogled" one on [here](https://chromium.woolyss.com/#windows-64-bit). It's always up to dated and they apply patches from Eloston's releases.

Those are x64 builds only though. The builds by @tangalbert919 are both x64 and x86, which are a bless for those like myself that need the latter for their 32-bit machines 🙂.

**Comment by jlanzarotta** [comment]
> > Try downloading "Ungoogled" one on [here](https://chromium.woolyss.com/#windows-64-bit). It's always up to dated and they apply patches from Eloston's releases.
> 
> Those are x64 builds only though. The builds by @tangalbert919 are both x64 and x86, which are a bless for those like myself that need the latter for their 32-bit machines 🙂.

I am not able to use those since they are not signed 😞

**Comment by jacob755** [comment]
there is an 32 bit build  thanks to @macchrome but 1 version behind in his release feel free to check
https://github.com/macchrome/winchrome/releases
ungoogled-chromium-91.0.4472.101-1_Win32.7z (32-bit legacy SSE2 instruction set)
https://github.com/macchrome/winchrome/releases/download/v91.0.4472.101-r870763-Win64/ungoogled-chromium-91.0.4472.101-1_Win32.7z

**Comment by neox91x** [comment]
> It's been three weeks since the v90 update and there's still no windows binary for that. Can anyone please upload a windows v90 binary .exe ?

yes is very old
