### ISSUE TITLE
Static Linux binary in deb package format

### ISSUE THREAD

**Issue by nyancat18** [Eloston/ungoogled-chromium#152]
How could you switch to a full deb?

like google-chrome ?

**Comment by Eloston** [comment]
What do you mean?

**Comment by triceratops1** [comment]
@eloston  
release an universal debian file (for debian, ubuntu, mint)  

like google chrome

**Comment by 9Morello** [comment]
Perhaps wrapping the static build in a `.deb` package could solve this.

**Comment by triceratops1** [comment]
@9Morello YES

**Comment by Eloston** [comment]
Closing this because it's almost done in #293.
