### ISSUE TITLE
Control freeze after computer waking up from suspension

### ISSUE THREAD

**Issue by teathinker** [Eloston/ungoogled-chromium#1520]
**Describe the bug**
Control freeze after computer waking up from suspension

**To Reproduce**
  1. Have browser window open
  2. Wait for computer to go to suspension
  3. Wake up the computer
  4. Browser window not responsive for 5~15 seconds, for example: no response when click tab or resize
  5. While other windows such as terminal, calculator are responsive.
  
Note: This issue is not reproducable every time.

**Environment (please complete the following information):**
 - OS/Platform and version: Debian 10 / 5.10.0-0.bpo.5-amd64
 - ungoogled-chromium version: 90.0.4430.212

** more info:
The responses are actually delayed somewhere. so after the window is back to responsive, all actions delayed such as clicking "add tab" 10 times will suddenly show 10 new tabs.

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-debian](https://github.com/ungoogled-software/ungoogled-chromium-debian)
