### ISSUE TITLE
Updating to Chromium 91  

### ISSUE THREAD

**Issue by Area51Kacz** [Eloston/ungoogled-chromium#1522]
De facto  ... Google might jump to Chromium 91 on May 25  (2 days)  

https://www.chromestatus.com/features/schedule

Thats why i post this
Sorry for being annoying

**Comment by Ahrotahn** [comment]
I'll start working on the beta to have most of the changes ready for the stable update.

**Comment by Area51Kacz** [comment]
@Ahrotahn i will try it  - thanks https://build.opensuse.org/project/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing
