### ISSUE TITLE
Google search engine not listed in default search engine on latest extension version

### ISSUE THREAD

**Issue by SushyDev** [Eloston/ungoogled-chromium#1523]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version:
 - ungoogled-chromium version:

**Additional context**

**Comment by networkException** [comment]
Could you please fill out the issue template? Just the title doesn't help with fixing your problem.

**Comment by jrdnrch** [comment]
Not to be too snarky but _is_  _un_ googled chromium. ( I thought the omission was on purpose and I dig it for sure.) 


However I totally understand if other search engines are failing in quality of queries using the big G us necessary. You may totally already know this but just in case for anyone who doesn't, One can add google and any other search by going to `chrome://settings/searchEngines` > Add . The for instance Google use `https://www.google.com/search?q=%s` as the URL and something like g for the key word. That way you can simply type g `space` [your query] in the address bar and search away.
