### ISSUE TITLE
[BUG] Use secure DNS cant be enabled because its "disabled on managed browsers"

### ISSUE THREAD

**Issue by TheSilencedOne** [Eloston/ungoogled-chromium#1527]
**Describe the bug**
Use secure DNS cant be enabled because it is "disabled on managed browsers"

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Privacy'
3. Click on 'Use secure DNS'

**Screenshots**
![NoFileName_0](https://user-images.githubusercontent.com/78061111/119775257-5b865e00-be91-11eb-933b-10599f08f1b7.jpg)

**Environment (please complete the following information):**
 - OS/Platform and version: Android 7.1.2
 - ungoogled-chromium version: 90.0.4430.212

**Additional context**

**Comment by wchen342** [comment]
I accidentally removed the part fixing the issue when updating patches. Will fix in next version.

**Comment by wchen342** [comment]
New version is available now.

**Comment by TheSilencedOne** [comment]
Fixed in v91.0.4472.77-1
