### ISSUE TITLE
"This site can’t be reached" error when visiting https://ads.google.com/ - [ERR_NAME_NOT_RESOLVED]

### ISSUE THREAD

**Issue by mark-franz** [Eloston/ungoogled-chromium#1528]
When I try to open the https://ads.google.com/ website, I get the "This site can’t be reached" error [ERR_NAME_NOT_RESOLVED]

**To Reproduce**
1. Go to address bar
2. Enter https://ads.google.com/
3. Click Enter
4. See error: 
> This site can’t be reached
> ads.google.com’s server IP address could not be found.
> Try:
> Checking the connection
> Checking the proxy, firewall, and DNS configuration
> Running Windows Network Diagnostics
> ERR_NAME_NOT_RESOLVED

**Expected behavior**
The https://ads.google.com/ web site opens

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 Pro
 - ungoogled-chromium version: 89.0.4389.114 (Developer Build, ungoogled-chromium) (64-bit)

**Additional context**
I also experience the following behaviour: 
1. Go to https://www.google.com/
2. On the cookie banner click **Customize**
3. On all options click **Off** and **Confirm**.
4. You get directed to: https://googleads.g.doubleclick.net/ads/preferences/cu/optout
5. See error:

> This site can’t be reached
> googleads.g.doubleclick.net’s server IP address could not be found.
> Try:
> 
> Checking the connection
> Checking the proxy, firewall, and DNS configuration
> Running Windows Network Diagnostics
> ERR_NAME_NOT_RESOLVED   

**Expected behavior**
The https://www.google.com/ website opens

**Notes**
- Other google.com URLs get opened as expected, e.g. google.com, accounts.google.com, support.google.com/
- Other domains (not on google.com) get opened as expected. 
- Could this have to do with the blocking of google.com URLs in Ungoogled Chromium UI etc. ?

**Comment by networkException** [comment]
Are you sure that you are not using something like pihole which blocks certain blacklisted domains? I can't reproduce the issue on 90.0.4430.212 Arch Linux and I wouldn't see why it would be any different on an older version. Also usually `ERR_BLOCKED_BY_CLIENT` would be the correct error for blocked domains that were patched out in the source code

**Comment by mark-franz** [comment]
thank you @networkException ! 
Indeed, it looks like it had to do with my DNS settings. 

Sorry for blaming Ungoogled-Chromium! 
(I'm new on it and experienced [another issue](https://github.com/NeverDecaf/chromium-web-store/issues/70) which indeed is related to - delibarately - broken google.com links. So I assumed, it could have the same root cause ... )

**Comment by networkException** [comment]
No problem, glad I could help
