### ISSUE TITLE
[feature request] add ccache support

### ISSUE THREAD

**Issue by Bogdan107** [Eloston/ungoogled-chromium#1533]
**Is your feature request related to a problem? Please describe.**
Each release need much time for rebuild package from the source.
I want to use ccache to speed up compilation of new releases.

Ccache may be configured ([in Gentoo](https://wiki.gentoo.org/wiki/Ccache)):
1) **globally for system environment**:
by setting environment variables in terminal;
2) **globally for portage building system**:
by configuring environment variables in /etc/portage/make.conf file;
3) **personally per package**:
for packages, that explicitly support ccache - by setting /etc/portage/package.use file;
for packages, that may support ccache - by setting /etc/portage/package.use in conjunction with /etc/portage/env/* files.

Ccache statistics may be viewed by ```ccache -s``` command.

In my case, ccache configured globally for portage system and works fine (ccache statistics changes) with other packages.

Neither global nor personal settings take effect if the package explicitly ignores ccache settings or does not support ccache.
The Cmake system, used to build the ungoogled-chromium package, can use ccache, but not in a trivial way.

I modified the ebuild to add support for switching ccache during build ungoogled-chromium: [ungoogled-chromium-90.0.4430.212-r1.ebuild.patch.txt](https://github.com/Eloston/ungoogled-chromium/files/6600185/ungoogled-chromium-90.0.4430.212-r1.ebuild.patch.txt)
But this patch is not sufficient to use ccache in package building process (```USE=ccache emerge -1 ungoogled-chromium```), since ccache usage statistics are not updated.

**Describe the solution you'd like**
I want to modify the ebuild to provide ccache support when building a package.

**Some interested links:**
- [Chrome: Using CCache on Mac](https://github.com/woweijingjing/chromium-1/blob/master/docs/ccache_mac.md)
- [CCACHE in Chromium Build](https://groups.google.com/a/chromium.org/g/chromium-dev/c/0S5OrREWHsc)
- [https://github.com/TheLartians/Ccache.cmake](https://github.com/TheLartians/Ccache.cmake)

**Comment by PF4Public** [comment]
What issue are you trying to solve? I see no issues with ccache presently.
![image](https://user-images.githubusercontent.com/10319700/121502980-51b03f00-c9e9-11eb-8329-3cea20995f0b.png)
One can see, that the first call is the call to ccache-wrapper, which in turn invokes the compiler
![image](https://user-images.githubusercontent.com/10319700/121503068-655ba580-c9e9-11eb-84c0-c1e75d3ecbe5.png)
Here are the corresponding misses highlighted

Either ccache is misconfigured on your system, or not enabled for ungoogled-chromium.
