### ISSUE TITLE
Cannot access to all files on Android 11

### ISSUE THREAD

**Issue by angelog0** [Eloston/ungoogled-chromium#1535]
A few day go there was the upgrade from an older version of Android to the version 11. After this, the [ungoogled](https://github.com/macchrome/droidchrome/releases/tag/v90.0.4430.91-r857950-Ungoogled-And64) Chromium I use on that device can access only to multimedia files. Usually I use it to browse my local files. I have a local site I used to open loading the `file:///sdcard/mysite/index.html`. After the upgrade, the `index.html` file is no more visible and typing that URL does not resolve because that _file is not accessible_. All this is very annoying because for years I used the browser that way.

It seems that the Android developers did so for security reasons.. it's like saying: don't eat otherwise you'll get diabetes, heart disease and so on...

**Comment by networkException** [comment]
I might be wrong but this seems like an issue regarding some random chromium build that just mentions "ungoogled" in the title. If that means the patches in this repository or some other is unclear.

As mentioned in the readme, android packaging for ungoogled chromium can be found [in the ungoogled-software organization](https://github.com/ungoogled-software/ungoogled-chromium-android)

**Comment by PF4Public** [comment]
macchrome releases are distributed separately from ungoogled-chromium, therefore we cannot provide support for them.
