### ISSUE TITLE
How to download themes in ungoogled?

### ISSUE THREAD

**Issue by Area51Kacz** [Eloston/ungoogled-chromium#1541]
How could i download themes for ungoogled _(if a theme its cute and u wannaenjoy it)_

https://www.themebeta.com/chrome/theme/1444532

**Comment by rany2** [comment]
If you install [Chromium Web Store](https://github.com/NeverDecaf/chromium-web-store) then clicking "Apply theme" would automatically install the extension for you.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.

**Comment by OAKO-UCONN** [comment]
Does not work anymore.

**Comment by maxfridbe** [comment]
Doesnt work for me either
