### ISSUE TITLE
Always open tabs in Incognito mode on Android

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [Eloston/ungoogled-chromium#1546]
**Is your feature request related to a problem? Please describe.**

Having the same feature like in Bromite to always be in incognito mode thus never retaining history is a good idea in my opinion. It increases privacy.

**Describe the solution you'd like**

The same as in Bromite.

**Describe alternatives you've considered**

**Additional context**

**Comment by networkException** [comment]
You can enable the deletion of all data after closing a session in the settings or just add `--incognito` to the launch arguments

**Comment by IHateTheProgrammingClass** [comment]
@networkException I should've specified (although it's kind of obvious) I'm talking about the Android version.

**Comment by networkException** [comment]
Oh yea I should have noticed you said Bromite. Well I'm unaware of a solution in that case

**Comment by IHateTheProgrammingClass** [comment]
I use both browsers (one without JS) I personally would prefer both of them to forget everything. And since I have yet to come across a solution to duplicate Bromite and it would probably benefit this project as well, wouldn't it be an option to copy the parts from Bromite?

**Comment by wchen342** [comment]
I am genuinely curious though in that case won't it be better just using Bromite? I want to avoid including too many things from Bromite because otherwise the android version is going to be just a bloated Bromite copy.

**Comment by IHateTheProgrammingClass** [comment]
I managaged to find a half baked solution. Chromium in this case is bad since as far as I'm concerned there are no native way of purging a whole browser when closing like in Firefox except running it in Incognito the whole time.
