### ISSUE TITLE
Disable upgrade detector

### ISSUE THREAD

**Issue by ujaroe** [Eloston/ungoogled-chromium#155]
Hi,

is there any chance you would consider removing upgrade detection:
master/chrome/browser/upgrade_detector_impl.cc
This would be most useful for a kiosk application, which is not connected to the web at all.

Or did I miss this feature?

Thanks!

**Comment by Eloston** [comment]
Is this for the browser itself? In that case, it isn't even enabled in Chromium if my memory serves me correctly (since Chromium's usually built by developers, so there's no point in checking Google for updates). ungoogled-chromium definitely does not have this enabld.
