### ISSUE TITLE
Unable to use my location in any website

### ISSUE THREAD

**Issue by Va1a** [Eloston/ungoogled-chromium#1551]
Disclaimer: I am quite sure this issue probably has a very simple solution, I am sorry if it does and I am just wasting time, however I spent a good while searching for answers and found nothing.

**Describe the bug**
I am unable to use location services with chrome. I have allowed chrome access to my location, but whenever I try to use it on a website which views my location, [the following error pop up occurs](https://i.imgur.com/c9V9mN6.png):  `Geolocation error: Network location provider at 'https://www.9oo91eapis.qjz9zk/' : No response received..` I am using ungoogled-chromium on mac (and have already allowed chromium to use location services) installed with homebrew cask.

**To Reproduce**
1. Go to https://openstreetmap.org
2. Click on show my location
3. Tell chromium to allow openstreetmap to see your location.

**Expected behavior**
No error, should be able to see my location.

**Screenshots**
https://i.imgur.com/c9V9mN6.png 

**Environment (please complete the following information):**
 - OS/Platform and version: macOS 11.2.3
 - ungoogled-chromium version: 91.0.4472.114

**Additional context**
Location services for chromium have been enabled.

**Comment by wchen342** [comment]
From the message it seems chromium send data to google servers to decide your location, which is thus unavailable in ungoogled-chromium because of domain substitution. I don't know whether it is possible to switch location provider though.

**Comment by Va1a** [comment]
This is what I figured, but Im sure others have managed to use location in ungoogled chromium. I can't possibly be the first one.

**Comment by ShadowTheC** [comment]
Are you using a proxy?

**Comment by networkException** [comment]
This has nothing to do wiith proxies, this is due to the way ungoogled-chromium patches source code

**Comment by PF4Public** [comment]
Unfortunately, this is how it is supposed to work with ungoogled-chromium patches applied.

**Comment by tomasz1986** [comment]
> Is there a way to fix this issue? Like there is a way to make the chrome extension store work again for example.

Not really unless you compile your own version of the browser without applying the related patch. The store is a completely different matter though, and it can be used with https://github.com/NeverDecaf/chromium-web-store. There should be a specific issue related to the store somewhere though, as this one is only about the location services.

**Comment by DevPrestigious** [comment]
Gotcha, just making sure. So the patch was to keep true to the ungoogled chromium way. Thanks for the understanding.

**Comment by thcrt** [comment]
Just as a tip for anyone who came across this as I did: you can enable location spoofing with Dev Tools (Console > Meatball menu > Sensors). This lets you choose a location to send to websites, which you can set to any value you like.

**Comment by TheFireCircle** [comment]
I came across [MLS](https://location.services.mozilla.com/api) today. Would it be possible to replace the google geolocation api with the Mozillas one?

**Comment by PF4Public** [comment]
> Would it be possible to replace the google geolocation api with the Mozillas one?

Apart from the need for implementing this, someone should also investigate how it could affact privacy of end-users and whether it would align with project goals.
