### ISSUE TITLE
Remove the "Not From Chrome Web Store badge in the extensions page

### ISSUE THREAD

**Issue by Va1a** [Eloston/ungoogled-chromium#1552]
**Is your feature request related to a problem? Please describe.**
It is very ugly seeing the "not from chrome web store" badge in chrome://extensions considering that no extensions can be added directly from the chrome web store.

**Describe the solution you'd like**
The removal of the badge

**Screenshots**
The badge: https://i.ibb.co/jbjxyDH/image.png

**Comment by kramred** [comment]
You can use this patch to hide the badges entirely: [hide-source-indicator-for-extensions.patch](https://github.com/kramred/ungoogled-chromium/blob/hide-source-indicator-for-extensions.patch/patches/extra/ungoogled-chromium/hide-source-indicator-for-extensions.patch)

Or, alternatively, use this patch for a subtler version of the badges: [subtle-source-indicator-for-extensions.patch](https://github.com/kramred/ungoogled-chromium/blob/subtle-source-indicator-for-extensions.patch/patches/extra/ungoogled-chromium/subtle-source-indicator-for-extensions.patch)

The subtler version will look something like on the following screen shot:
![subtle_extension_source_indicators](https://user-images.githubusercontent.com/16719551/122941476-553eb100-d36d-11eb-8c93-038aa6b60099.png)

If there is a broader interest in this visual modification I can open a pull request.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
