### ISSUE TITLE
Issue including XpathGrammar.h

### ISSUE THREAD

**Issue by DeadSix27** [Eloston/ungoogled-chromium#156]
Tried compiling target=64bit of master

EDIT: should probably mention, I am on windows 64 and this is targeted to windows 64. Followed the guide on BUILDING.md except ....

I changed `target_cpu` in windows.py, rather than build.py as the CPUArch include is missing in build.py so "CPUArch" is undefined, figured it wouldn't matter. (Unless it does and causes this issue ... )

Either way, I guess `from buildlib.common import CPUArch` should be added by default or mentioned in the README? 

Compile error:
```
[17193/24289] CXX obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj
FAILED: obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj.rsp /c ../../third_party/WebKit/Source/core/xml/XPathParser.cpp /Foobj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj /Fd"obj/third_party/WebKit/Source/core/xml/xml_cc.pdb"
g:\chromium\ungoogled-chromium\build\sandbox\third_party\webkit\source\core\xml\xpathparser.cpp(31): fatal error C1083: Cannot open include file: 'core/XPathGrammar.h': No such file or directory
[17201/24289] CXX obj/third_party/WebKit/Source/core/workers/workers/WorkerThread.obj
```

Is this a known issue or did I do something wrong?
Ask if you need any more information.

**Comment by Eloston** [comment]
> I changed target_cpu in windows.py, rather than build.py as the CPUArch include is missing in build.py so "CPUArch" is undefined, figured it wouldn't matter. (Unless it does and causes this issue ... )

It really doesn't matter, but users are supposed to import `CPUArch` from `buildilb.common`. Terrible design is terrible. I can just add the import to `build.py` by default I guess.

> Is this a known issue or did I do something wrong?

I built the Windows x64 build on Windows 10 Pro x64, but I don't think that's related to the issue. This is a weird error, since I don't know why the includes are wrong (for a file within the Chromium source tree, nonetheless).

Do your versions of Visual Studio and its components match **exactly** to what's listed in BUILDING? Do you have any other versions of Visual Studio installed?

**Comment by DeadSix27** [comment]
I installed all the requirements correctly.
Visual studio has all the required things selected and I added all the needed binaries to the Path.
I now set builder.target_cpu = CPUArch.x64 and imported CPUarch in build.py
And I ran:

```
G:\chromium>git clone https://github.com/Eloston/ungoogled-chromium.git
G:\chromium>cd ungoogled-chromium
G:\chromium\ungoogled-chromium>C:\Python35\python.exe build.py
```
I did not change anything beside adding the target_cpu in build.py rather than windows.py, which you yourself said wouldn't matter.

And now I get this error:
```
DEBUG:root:Running: mc.exe -r c:\users\*\appdata\local\temp\tmp0abet4\gen\base/trace_event/etw_manifest -h c:\users\*\appdata\local\temp\tmp0abet4\gen\base/trace_event/etw_manifest -u -um G:\chromium\ungoogled-chromium\build\sandbox\base/trace_event/etw_manifest/chrome_events_win.man
Traceback (most recent call last):
  File "tools\gn\bootstrap\bootstrap.py", line 754, in <module>
    sys.exit(main(sys.argv[1:]))
  File "tools\gn\bootstrap\bootstrap.py", line 121, in main
    return run_build(tempdir, options)
  File "tools\gn\bootstrap\bootstrap.py", line 71, in run_build
    build_gn_with_ninja_manually(tempdir, options)
  File "tools\gn\bootstrap\bootstrap.py", line 183, in build_gn_with_ninja_manually
    'base/trace_event/etw_manifest/chrome_events_win.man')
  File "tools\gn\bootstrap\bootstrap.py", line 134, in write_compiled_message
    os.path.join(SRC_ROOT, source),
  File "tools\gn\bootstrap\bootstrap.py", line 44, in check_call
    subprocess.check_call(cmd, cwd=GN_ROOT, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
2016-12-21 11:24:54,721 - ERROR: GN bootstrap command returned non-zero exit code: 1

G:\chromium\ungoogled-chromium>
```

**Comment by Eloston** [comment]
The older 55.x.x.x tags don't build on Windows. Only the latest one works (`55.0.2883.87-1` as of now). The master branch should also work at the time of this comment (but there are no significant changes for Windows between the tag and the branch right now)

> I figured, you only had to run "vcvarsall" in the "VS2015 x64 Native Tools Command Prompt"

Actually if you launch one of those command prompts, you don't need to run vcvarsall. The only reason I need to run in this command prompt is because the bootstrap build script for the GN tool won't build without the correct `PATH` containing the compilers.

However, this shouldn't affect the main build because Google already does the detection of the compilers during the GN build step separately from the currently executing terminal environment.

Did you install Visual Studio to the default location? I installed it to a custom location without spaces in it. Though I doubt this is the cause of the problems.

**Comment by DeadSix27** [comment]
Its in the default folder. Tried Official chromium, builds fine. Still getting the include issue

**Comment by DeadSix27** [comment]
Let's sum up: I can not start the build without using the Native Tools CMD Prompt, otherwise it errors
as seen in post3: https://github.com/Eloston/ungoogled-chromium/issues/156#issuecomment-268489583

As to your EDIT, I use "Default" and I checked `out/Default/gen/` there is no gen/blink at all
nor is there a build.gn in `third_party/WebKit/Source/core/` only has `core_event_interfaces_file_list.tmp`

Just in case, this time, here is the full output log:
https://paste.ubuntu.com/23667883/

![image](https://cloud.githubusercontent.com/assets/1492505/21422290/4a2ec142-c837-11e6-8a6a-4cba3e3ecae2.png)
![image](https://cloud.githubusercontent.com/assets/1492505/21420943/a8981834-c830-11e6-876b-34fc556e14e4.png)

**Comment by Eloston** [comment]
> And "vcvarsall" is not existing outside that cmd promt.
I figure you could prob just run it directly by specifying the full path in any cmd.exe process, but .. if you can just open the native tools cmd.. it doesnt matter.

Oh I misunderstood what you meant. I got some concepts screwed up. Yeah that's fine.

> nor is there a build.gn in third_party/WebKit/Source/core/ only has core_event_interfaces_file_list.tmp

*Sees image...*

*Corrects ambiguity*

> Bison is supposed to be generating this file according to ~~`third_party/WebKit/Source/core/BUILD.gn`~~ `build/sandbox/third_party/WebKit/Source/core/BUILD.gn` in `make_core_generated_bison`

[That file should have this section in it](https://chromium.googlesource.com/chromium/src/+/55.0.2883.87/third_party/WebKit/Source/core/BUILD.gn#795)

**Comment by DeadSix27** [comment]
> Sees image...
> Corrects ambiguity
heh, ye I pre-written the entire text expecting that folder to not be there, but it eventually got created, but without the file "out/Default/gen/blink/core/XPathGrammar.h" which the image shows you as well.


But Now I'm lost, am I supposed to look for BUILD.gn in `build/sandbox/third_party/WebKit/Source/core/`
now? In which case, that file does not exist.

**Comment by Eloston** [comment]
Then your build sandbox is broken, because [it's still there in 55.0.2883.95](https://chromium.googlesource.com/chromium/src/+/55.0.2883.95/third_party/WebKit/Source/core/BUILD.gn#795)

**Comment by DeadSix27** [comment]
Which is odd because I seriously just followed the guide.. I mean I can't do much wrong beside that..
Considering official chromium compiles just fine without any issues.
And they use almost the same setup. Meaning, my compiler works fine. My python works fine.
Do you think it could be an issue with one of the binaries you have to install? (patch,bison,etc. see below)

Otherwise I really can't think of what I could have done wrong...

```
2016-12-22 10:14:27,869 - INFO: Checking Python 2 command...
2016-12-22 10:14:27,895 - DEBUG: Using Python version '2.7.6'
2016-12-22 10:14:27,895 - INFO: Checking ninja command...
2016-12-22 10:14:27,903 - DEBUG: Using ninja version '1.7.2'
2016-12-22 10:14:27,903 - INFO: Checking patch command...
2016-12-22 10:14:27,917 - DEBUG: Using patch command 'GNU patch 2.7.5'
2016-12-22 10:14:27,917 - INFO: Checking bison command...
2016-12-22 10:14:27,929 - DEBUG: Using bison command 'bison (GNU Bison) 2.4.1'
2016-12-22 10:14:27,929 - INFO: Checking gperf command...
2016-12-22 10:14:27,938 - DEBUG: Using gperf command 'GNU gperf 3.0.1'
```

**Comment by Eloston** [comment]
(Going to repost edit so you don't have to keep checking messages you already read)

I'm still having a hard time believing that the file isn't there if the GN step was successful. What else is in that directory?

**Comment by DeadSix27** [comment]
Think you can see that on the images.
I unfortunately do not have the full output anymore as I tested the official chromium build to see if that fails too. (Which takes a big chunk of my SSD, leaving no space for ungoogled) 
But as I previously mentioned, I will re-run everything from scratch and report back again, only this way I can re-assure I did everything according to the guide (which I'm very very sure I did.)
Maybe you can read over the guide once too, see if really everything is correct, but then again no one else reported this issue, or barely anyone compiles this on/for Windows 64..

**Comment by Eloston** [comment]
> Think you can see that on the images.

Nope, those files are generated during the build. The path I'm talking about is part of the source code tree, not in the `out` directory.

> I unfortunately do not have the full output anymore as I tested the official chromium build to see if that fails too. (Which takes a big chunk of my SSD, leaving no space for ungoogled)

Ah ok. ~50 GB of files is large indeed.

> Maybe you can read over the guide once too, see if really everything is correct, but then again no one else reported this issue, or barely anyone compiles this on/for Windows 64..

nopjmp (who fixed Windows support for version 55) was able to get both 32-bit and 64-bit to build.

I'm starting to think that this could be a file writing/filesystem problem. From experiences I heard and had, I no longer find Windows a reliable OS for storing data. Do you have an antivirus enabled (including Windows Defender)? Do you know of any background service that could be affecting your data? I know of some PCs that come pre-installed with some special software for their SSDs that end up making things worse.

FYI, I run a fresh install of Windows 10 Pro inside a VirtualBox VM and with a lot of things turned off/tweaked. It's possible there's some external factor to your issue here.

**Comment by DeadSix27** [comment]
Sorry about the closing, ignore that :)

But ye Defender is not installed/disabled, I have nothing running that could interfere, I run Windows 10 Pro too, actually a fresh install as well.

**Comment by Eloston** [comment]
*The plot thickens...*

Maybe you could comment out the following in `build.py` so all of the build steps aren't executed:
```
        builder.setup_build_utilities()
        builder.generate_build_configuration()
        builder.build()
        builder.generate_package()
```

and see if `build/sandbox/third_party/WebKit/Source/core/BUILD.gn` is there at the end of it.

**Comment by DeadSix27** [comment]
Alright, ran through, it has the above file, and the file also contains:

```
action_foreach("make_core_generated_bison") {
  script = "../build/scripts/rule_bison.py"
  sources = [
    "xml/XPathGrammar.y",
  ]
  outputs = [
    "$blink_core_output_dir/{{source_name_part}}.cpp",
    "$blink_core_output_dir/{{source_name_part}}.h",
  ]
  args = [
    "{{source}}",
    rel_blink_core_gen_dir,
    bison_exe,
  ]
  if (!use_system_xcode) {
    args += [ hermetic_xcode_path ]
  }

  deps = make_core_generated_deps
}
```
I assume now I should run the rest?

      ```
  #builder.setup_build_utilities()
        #builder.generate_build_configuration()
        #builder.build()
        #builder.generate_package()
```

**Comment by Eloston** [comment]
Sure.

**Comment by DeadSix27** [comment]
Alright, finished, was kinda hoping to see it work now
Steps I took:
```
G:\chromium>git clone https://github.com/Eloston/ungoogled-chromium.git
Cloning into 'ungoogled-chromium'...
remote: Counting objects: 2517, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 2517 (delta 6), reused 0 (delta 0), pack-reused 2476
Receiving objects: 100% (2517/2517), 1.28 MiB | 326.00 KiB/s, done.
Resolving deltas: 100% (1446/1446), done.

G:\chromium>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
G:\chromium>cd ungoogled-chromium
G:\chromium\ungoogled-chromium>C:\Python35\python.exe build.py
```

Error:
```
[16906/24289] CXX obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj
FAILED: obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj.rsp /c ../../third_party/WebKit/Source/core/xml/XPathParser.cpp /Foobj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj /Fd"obj/third_party/WebKit/Source/core/xml/xml_cc.pdb"
g:\chromium\ungoogled-chromium\build\sandbox\third_party\webkit\source\core\xml\xpathparser.cpp(31): fatal error C1083: Cannot open include file: 'core/XPathGrammar.h': No such file or directory
[16914/24289] CXX obj/third_party/WebKit/Source/core/xml/xml/DocumentXSLT.obj
```

**Comment by Eloston** [comment]
> EDIT: btw, is there an easy way to re-run this without having to do all the patches again and getting errors about "already patched" etc? So that I can test theories ?
> EDIT2: ^above indeed re-runs it just fine, tested whether something in the back interferes, and nope, nothing is now running, and it still produces the same error

Yay you figured out how to use `buildlib` the way it's intended to. Apparently not many people read through the entire BUILDING document...

> EDIT3: btw there is this file, not sure if that helps in any way, it just stood out between all the headers and source files:

As you can see from the GN file I referenced a few times, that is the input file to Bison. Bison produces the header file and a corresponding C++ source file. The fact that the file is there is good, but Bison doesn't seem to be running for some reason.

> EDIT4: is there any way we can make the build more verbose?

I'm assuming you want to increase verbosity of Ninja. In that case, pass in `-v`. You can add it in [on this line of common.py](https://github.com/Eloston/ungoogled-chromium/blob/master/buildlib/common.py#L224)

**Comment by DeadSix27** [comment]
with -v:
Nothing new I that could help me, but maybe you.
```
[16954/24289] ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj.rsp /c ../../third_party/WebKit/Source/core/xml/XPathParser.cpp /Foobj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj /Fd"obj/third_party/WebKit/Source/core/xml/xml_cc.pdb"
FAILED: obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj.rsp /c ../../third_party/WebKit/Source/core/xml/XPathParser.cpp /Foobj/third_party/WebKit/Source/core/xml/xml/XPathParser.obj /Fd"obj/third_party/WebKit/Source/core/xml/xml_cc.pdb"
g:\chromium\ungoogled-chromium\build\sandbox\third_party\webkit\source\core\xml\xpathparser.cpp(31): fatal error C1083: Cannot open include file: 'core/XPathGrammar.h': No such file or directory
```

**Comment by Eloston** [comment]
> Is there a way to debug bison / the bison command lines?

You can modify the Python script that they use to run bison. GN can't run executables directly; the only thing it can run are Python scripts.

> Nothing new that could help me, but maybe it helps you.

Nope, sorry.

**Comment by DeadSix27** [comment]
Interesting stuff:
`BUILD.gn` calls `rule_bison.py` here using `bison_exe`
```
action_foreach("make_core_generated_bison") {
  script = "../build/scripts/rule_bison.py"
  sources = [
    "xml/XPathGrammar.y",
  ]
  outputs = [
    "$blink_core_output_dir/{{source_name_part}}.cpp",
    "$blink_core_output_dir/{{source_name_part}}.h",
  ]
  args = [
    "{{source}}",
    rel_blink_core_gen_dir,
    bison_exe,
  ]
  if (!use_system_xcode) {
    args += [ hermetic_xcode_path ]
  }

  deps = make_core_generated_deps
}
```
in here we see that it just runs bison
third_party/WebKit/Source/build/script/rule_bison.py
```
prefix = {'XPathGrammar.y': 'xpathyy'}[inputName]

(inputRoot, inputExt) = os.path.splitext(inputName)

# The generated .h will be in a different location depending on the bison "`bisonExe = sys.argv[3]`"

# version.
outputHTries = [
    os.path.join(outputDir, inputRoot + '.cpp.h'),
    os.path.join(outputDir, inputRoot + '.hpp'),
]
```

Now the problem here is, where is bisonExe defined... as in the root of it, I can't see any other usage of bisonExe in the GN file

**Comment by Eloston** [comment]
> Now the problem here is, where is bisonExe defined... as in the root of it, I can't see any other usage of bisonExe in the GN file

`bisonExe` is defined at the top of the Python script. GN runs the Python script with a Python subprocess given the arguments as defined in the GN file.

**Comment by DeadSix27** [comment]
I just checked the folders, rule_bison.py is never called (hence the lack of a pyc file and others having a pyc file, for example "make_style_builder.py" is being called by:
```
css_properties("make_core_generated_style_builder") {
  script = "../build/scripts/make_style_builder.py"
```
in the very same BUILD.gn file, do you have any clue what makes it call that but not

```
action_foreach("make_core_generated_bison") {
  script = "../build/scripts/rule_bison.py"
  sources = [
    "xml/XPathGrammar.y",
```
in fact make_core_generated_bison
appears in:
```
target(core_link_small_target_type, "core_generated") {
  sources = bindings_core_v8_files

  # Targets from above that generate outputs that need to be compiled.
  # All sources declared as outputs from these targets will be compiled into this
  # target.
  targets_generating_sources = [
    ":make_core_generated_bison",
```
and core_generated
appears in:
```
source_set("generated") {
  deps = [
    ":core_generated",
```

And thats as far as my guessing goes any other ideas?

**Comment by Eloston** [comment]
[More confusingly, `make_core_generated_style_builder` is in the same `targets_generating_sources` list as `make_core_generated_bison` of the `core_generated` target.](https://chromium.googlesource.com/chromium/src/+/55.0.2883.95/third_party/WebKit/Source/core/BUILD.gn#844)

Why `make_style_builder.py` is invoked but not `rule_bison.py` makes no sense to me either.

Maybe we should try investigating ninja files. Does `rule_bison.py` show up in `out/Default/toolchain.ninja`?

**Comment by DeadSix27** [comment]
yep, toolchain.ninja has::
```
rule __third_party_WebKit_Source_core_make_core_generated_bison___build_toolchain_win_x64__rule
  command = C$:/Python27/python.exe ../../third_party/WebKit/Source/build/scripts/rule_bison.py ${in} gen/blink/core bison.exe
  description = ACTION //third_party/WebKit/Source/core:make_core_generated_bison(//build/toolchain/win:x64)
  restat = 1
build obj/third_party/WebKit/Source/core/make_core_generated_bison.inputdeps.stamp: stamp ../../third_party/WebKit/Source/build/scripts/rule_bison.py obj/third_party/WebKit/Source/core/core_event_interfaces.stamp obj/third_party/WebKit/Source/core/generated_settings_macros.stamp obj/third_party/WebKit/Source/core/generated_testing_idls.stamp obj/third_party/WebKit/Source/core/generated_testing_idls_internal_runtime_flags.stamp obj/third_party/WebKit/Source/core/generated_testing_idls_settings.stamp

build gen/blink/core/XPathGrammar.cpp gen/blink/core/XPathGrammar.h: __third_party_WebKit_Source_core_make_core_generated_bison___build_toolchain_win_x64__rule ../../third_party/WebKit/Source/core/xml/XPathGrammar.y | obj/third_party/WebKit/Source/core/make_core_generated_bison.inputdeps.stamp

build obj/third_party/WebKit/Source/core/make_core_generated_bison.stamp: stamp gen/blink/core/XPathGrammar.cpp gen/blink/core/XPathGrammar.h
```

also:
.ninja.log
```
221313	221531	0	gen/blink/core/testing/InternalSettingsGenerated.idl	513b877cc043a3cd
221313	221531	0	gen/blink/core/testing/InternalSettingsGenerated.cpp	513b877cc043a3cd
221313	221531	0	gen/blink/core/testing/InternalSettingsGenerated.h	513b877cc043a3cd
```
After this, it should do xpathgrammar, but, no output

**Comment by Eloston** [comment]
> After this, it should do xpathgrammar, but, no output

Maybe the commands are out-of-order. The misordering should be reflected in the ninja files. Even if we figure out how ninja is doing it wrong, I'm not sure how this is going to help us figure out what GN is doing wrong.

> EDIT2: I also just compared both BUILD.gn (official LKGR and ungoogled)
Some interesting differences are:

I don't think that's related. [If you compare it to what we're working with](https://chromium.googlesource.com/chromium/src/+/55.0.2883.95/third_party/WebKit/Source/core/BUILD.gn#858), it looks like they just moved it out for better formatting/structuring.

@nopjmp Do you have any ideas why this issue is happening?

**Comment by DeadSix27** [comment]
Have you read my big edit?

**Comment by Eloston** [comment]
Do you mean EDIT2 and Before EDIT2 from [here](https://github.com/Eloston/ungoogled-chromium/issues/156#issuecomment-269111446)? Then yes. I replied to EDIT2 in the comment before this one.

**Comment by DeadSix27** [comment]
Nope, big fat bold header # EDIT (be sure to read this first)

**Comment by Eloston** [comment]
Ah. Apparently I needed to refresh the webpage in order to see edits. But if you stay on the page, new comments will show up. Going to add the new info to BUILDING.

@nopjmp Sorry for pinging you. It's all sorted out now.

**Comment by DeadSix27** [comment]
That's a short reply .. heh.. hoped you'd say a little more.

**Comment by Eloston** [comment]
> That's a short reply .. heh.. hoped you'd say a little more.

*shrugs*

Well here's more then

> Fun fact, this is the first time I've ever opened ungoogled chrome, since I've never got it to compile before.. be it due to this issue or the non-existent 64bit support before.

Could've ran the 32-bit version but I guess you like more bits and some more security.

> just wonder why it doesn't show this in the build output at all.....

I think `bison` runs `m4` (IIRC from the comment in the Python script), so even if the Python script were to redirect `bison`'s standard I/O to its own, that error would only show up if `bison` spat out the error.

> (And also wonder how to fix this, a work-around for now is using a less... spacy .. location, but that seems stupid.. should be fixed with quotation...)

There's not really much we can do, unless we patch the tools and build it. But what really bugs me is why `bison` doesn't throw an error if `m4` doesn't exit successfuly.

I'm wondering how Google deals with this space issue. Maybe they patched their versions of the utilities? Or somehow used relative paths? Or they don't?

**Comment by DeadSix27** [comment]
> I'm wondering how Google deals with this space issue. Maybe they patched their versions of the utilities? Or somehow used relative paths? Or they don't?
Patches I guess? official source comes with its own bison.

Btw..offtopic issue I now face:
![image](https://cloud.githubusercontent.com/assets/1492505/21470464/ebf9bd6a-ca8a-11e6-882c-f6c6d6849f73.png)
Every single page is grayed out and shows the error icon, even internal ones, any idea? (I can post this in a new issue if you want)

**Comment by Eloston** [comment]
You need to run it on the C: drive because the sandboxing technologies used by Chromium aren't happy with executables running on non C: drives.

**Comment by DeadSix27** [comment]
wow that sounds very sad (it was in C:/Pr..Files/Chromium-ungoogled/ actually)... 



(now i just need ungoogled chromium for android...)

**Comment by Eloston** [comment]
Oh saw your edit. Nevermind then.

> (now i just need ungoogled chromium for android...)

Yep, would like this too. Too bad extensions aren't supported yet though.

**Comment by DeadSix27** [comment]
chrome extensions on android are my dream

**Comment by nopjmp** [comment]
I'm just going to chime in some closing thoughts just in case someone else stumbles across this issue.

Spaces cause problems in a lot of ported tools on Windows. I always suggest used the `VS2015 x86 Native Tools Command Prompt` and `VS2015 x64 Native Tools Command Prompt` and then changing directories just because it prevents less knowledgeable users from making a mistake.

The grey page can also be caused by moving the ungoogled-chromium directory to a different path which is really dumb and needs to be fixed, but i'll open another issue when I get time (it's a holiday weekend for me).

I was actually going to work on getting Ungoogled Chromium on Android. It's going to take a lot more fiddling, but it's completely possible. CopperheadOS builds Chromium as part of their build process.

**Comment by DeadSix27** [comment]
> The grey page can also be caused by moving the ungoogled-chromium directory to a different path which is really dumb and needs to be fixed, but i'll open another issue when I get time (it's a holiday weekend for me).

Meaning its fixable from your side and not chromium?
(By patching chromium itself rather than making the chromium team fix it?)

**Comment by nopjmp** [comment]
If you extra that zip again then move it before running it works just fine. I think it's saving the sandbox binary location somewhere. I can upstream it later after its fixed. I'm a hobbyist c++ programmer so I should be able to fix it.

Sent from my android device.

-----Original Message-----

**Comment by DeadSix27** [comment]
Well, so am I, altho all other languages more than c++, but does it really have to do where it saves the zip, does the entire build process remember "i saved my zip to G:\test""lets fail everywhere else except G:"

But ye I need more information to fully understand this, since if it saves the sandbox binary somewhere, shouldn't all we have to do be, moving said binary as well?

**Comment by nopjmp** [comment]
I'm just mentioning the behavior I noticed I haven't looked into it too much since made the pull request. I will look into it later. It takes way too long for me to build chromium on my machine. I'm waiting for my new machine to come in.

Sent from my android device.

-----Original Message-----

**Comment by DeadSix27** [comment]
No problem, was just curious (ye even on my 6700k it takes a long while, def needs more than 8 threads, more like 24 :p)

Be sure to quote me or reply here or so when you get more Information.

**Comment by Eloston** [comment]
What "sandbox binary" are we talking about here? And zip file? I thought Chromium just made system API calls to get sandboxing to work

**Comment by nopjmp** [comment]
I think it's the sandbox process but it could be something else. I'm going to make a new issue or just submit a pull request to fix it. Most likely it only is a problem on Windows since macOS and Linux use different methods. macOS stores everything in the app and Linux uses a wrapper script.

Sent from my android device.

-----Original Message-----

**Comment by DeadSix27** [comment]
By the way, it does still work just fine, no matter which drive I put it on, after you mentioned it, I just took it for granted (that it won't work) but it does.

**Comment by Eloston** [comment]
Huh, I remember that it wouldn't run on my secondary HDD attached to the VM, but it would run just fine on the C: drive. Maybe they changed it now?

**Comment by nopjmp** [comment]
They probably fixed it upstream. Windows filesystem can be crazy. UTF16 file names if I remember correctly.

Sent from my android device.

-----Original Message-----

**Comment by Eloston** [comment]
[I created a Gitter room](https://gitter.im/ungoogled-software/Lobby). We should discuss more there instead of taking this issue off-track.
