### ISSUE TITLE
Updating to Chromium  92

### ISSUE THREAD

**Issue by Area51Kacz** [Eloston/ungoogled-chromium#1561]
Chromium 92 will came in 1-2 weeks (maybe jul 20th)  

So ... could we   prepare for chromium 92  
taking the actual 92.0.4515.80   as base

**Comment by YukikoTakashiro** [comment]
This project seems dead.. anyone know another ungoogled chromium project which gets updates ?

**Comment by networkException** [comment]
In what way does this project seem dead?

**Comment by YukikoTakashiro** [comment]
no i mean because the last version is 89.0.4389.114 from 6. april this year.

**Comment by networkException** [comment]
The lastest version is 91.0.4472.114-1 as can be seen [here](https://github.com/Eloston/ungoogled-chromium/releases/tag/91.0.4472.114-1)

**Comment by YukikoTakashiro** [comment]
and how is one supposed to install that ?

**Comment by networkException** [comment]
There are install instructions in the readme

**Comment by wchen342** [comment]
The windows version is not getting updated for some time because the person who maintained that version previously hasn't shown up for some time. All the linux/android versions are up to date.
If you are on a linux distribution, you can look for instructions in one of the repos under [ungoogled-software](https://github.com/ungoogled-software). I cannot help on windows version though.

**Comment by Ahrotahn** [comment]
Usually it's a good idea to wait until the stable cut to start working on the major updates so you don't have to do extra work.  That is normally the week before the release.  You can see the schedule here:  https://chromiumdash.appspot.com/schedule

I'll start working on this later in the week if no one else has picked it up before then.

**Comment by YukikoTakashiro** [comment]
> There are install instructions in the readme
> 
> If you need further help maybe its better to join the matrix channel instead of using github issues

where can i find this matrix channel ? couldnt make anything up with the readmes since im no programmer or anything besides a normal user...

**Comment by networkException** [comment]
The matrix channel is `ungoogled-software/lobby` (from [SUPPORT.md](https://github.com/Eloston/ungoogled-chromium/blob/master/SUPPORT.md))

**Comment by YukikoTakashiro** [comment]
> The matrix channel is `ungoogled-software/lobby` (from [SUPPORT.md](https://github.com/Eloston/ungoogled-chromium/blob/master/SUPPORT.md))

thanks alot

**Comment by jackloomen** [comment]
> There are install instructions in the readme
> 
> If you need further help maybe its better to join the matrix channel instead of using github issues

where is the matrix channel referenced? what is it?

**Comment by Area51Kacz** [comment]
Just remember than Arch had some surprises in chromium 92  _(replace old patches - add new **surprise** patches)_
https://github.com/archlinux/svntogit-packages/commit/78c86ecddcd707d7c90c4c03b26d736e0e9610fb
https://github.com/archlinux/svntogit-packages/commit/042a79d94343afffbc9bccfde2bda6f8735401d5

**Comment by brodybits** [comment]
https://www.bleepingcomputer.com/news/security/google-chrome-now-comes-with-up-to-50x-faster-phishing-detection/ - this statement kinda concerns me:

> "Starting with M92, Chrome now executes image-based phishing classification up to 50 times faster at the 50th percentile and 2.5 times faster at the 99th percentile," Chrome developer Olivier Li Shing Tat-Dupuis [said](https://blog.chromium.org/2021/07/m92-faster-and-more-efficient-phishing-detection.html)

https://blog.chromium.org/2021/07/m92-faster-and-more-efficient-phishing-detection.html

It looks to me and some others like we may want to be able to turn this off.

**Comment by Ahrotahn** [comment]
Luckily the phishing detection is part of SafeBrowsing which we build without!
