### ISSUE TITLE
Cant login to Pandora.com

### ISSUE THREAD

**Issue by isaac82419** [Eloston/ungoogled-chromium#1562]
**Describe the bug**
Using version 91 of ungoogled chromium I am unable to login to pandora.com, I have checked username and password that is not the issues. I am not using any extensions when testing this. I am using the portable build from here https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/91.0.4472.114-1.1

**To Reproduce**
1. Go to pandora.com
2. try to login
3. get error saying username/password incorrect

**Expected behavior**
I should be able to login. I havent found other sites that fail this way yet. 

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version: Ubuntu 20.04
 - ungoogled-chromium version: 91.0.4472.114-1.1

**Comment by networkException** [comment]
This doesn't sound like an issue of chromium really, are there any errors in the devtools console maybe?

**Comment by isaac82419** [comment]
It shows a 400 error when returning from the API but I can see in the request in the network tab that username/password are correct. I have noticed that godaddy does not allow logins either when using this browser. Im wondering if there is a library or some functionality thats been removed that these vendors are noticing and blocking logins now.

**Comment by networkException** [comment]
Perhaps the sites require more permissive cookie settings or similar?

**Comment by wchen342** [comment]
Check whether you have any anti-fingerprinting flags enabled.
