### ISSUE TITLE
Remove old window borders on linux

### ISSUE THREAD

**Issue by simulationguest** [Eloston/ungoogled-chromium#1567]
Chromium still has 4px window borders on linux that make it look outdated. There's also an official bug report about this and a few suggested patches. 
https://bugs.chromium.org/p/chromium/issues/detail?id=920768

The only alternative is
1. Showing a titlebar instead
2. Then removing the titlebar via the window manager
but that looks terrible

**Comment by Ahrotahn** [comment]
I had looked into the issue not too long after you made it.  I'm sorry for not responding then, I kind of lost track of it until it hit the closed list.  

Google is working on fixing this upstream:  [2901661](https://chromium-review.googlesource.com/c/chromium/src/+/2901661).  The changes were initially merged for v93, but it looks like there were issues with the shadows and it has been reverted.  Most likely it will land in v94 now.  There's a different bug report that they seem to be using:  [811515](https://bugs.chromium.org/p/chromium/issues/detail?id=811515)

If you're using a tiling window manager and want the border removed entirely while using chromium's CSD, all you need is this change:

```diff
--- a/chrome/browser/ui/views/frame/browser_non_client_frame_view.cc
+++ b/chrome/browser/ui/views/frame/browser_non_client_frame_view.cc
@@ -99,7 +99,7 @@
 }
 
 bool BrowserNonClientFrameView::IsFrameCondensed() const {
-  return frame_->IsMaximized() || frame_->IsFullscreen();
+  return true;
 }
 
 bool BrowserNonClientFrameView::HasVisibleBackgroundTabShapes(
```

**Comment by simulationguest** [comment]
Thank you very very much for your help :D
