### ISSUE TITLE
Widevine installed but not working.

### ISSUE THREAD

**Issue by RaphaelNeubert** [Eloston/ungoogled-chromium#1568]
I compiled chromium using pf4publics ebuild. I did enable the widevine useflag. After it was done I downloaded the chromium .deb package and extracted the WideVine folder and copied it to /usr/lib64/chromium-brower where all the other files are.

When going to chrome://components it shows `Widevine Content Decryption Module - Version: 4.10.2209.0` so I think it installed successfully.

Unfortunately, sites like amazon prime and spotify can't detect it. https://bitmovin.com/demos/drm doesn't detect it either. It just gives "NO DRM".  chrome://settings/content/protectedContent is enabled too.

The installed version is www-client/ungoogled-chromium-91.0.4472.114-r1::pf4public.

I'm not sure what I'm doing wrong. I appreciate any help.

**Comment by wchen342** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/1566#issuecomment-879056903.

**Comment by RaphaelNeubert** [comment]
Interesting. When I opened the issue, wine wasn't getting detected at all. Now it is getting detected but as described in the issue you linked, HD is not available.

So I guess right now there is no way to stream HD contents from companies certified with widevine. I know that brave is able to stream HD contents. Is it possible to extract the Widevine folder out of brave? I know they handle widevine differently than chromium so probably not. 

I understand that using a proprietary plugin like widevine on a privacy-focused browser doesn't make much sense. I was using brave before but got annoyed buy all the crypto stuff and them keep adding stuff I don't want/need. I really like the idea behind ungoogled chromium. I myself don't even really use prime but sometimes I have people coming over and they want to watch something. I guess the two choices I have are to either keep using brave or to have brave and ungoogled-chromium installed.

Let me know if there is anything else i can try out. If not then i will close this issue. Thank you very much.

**Comment by wchen342** [comment]
> Is it possible to extract the Widevine folder out of brave?

Interesting idea, but I don't know whether it is possible. I have never tried desktop Brave so I cannot tell, but maybe you can search its installation path and see whether there are anything related to widevine.

Other than that, the options are either use Brave/Vivaldi/Firefox. There is no real solution to this unfortunately.

**Comment by RaphaelNeubert** [comment]
I found brave's Widevine directory. It looks exactly like chromiums one but when I move it into ungoogled chromiums directory the version number of Widevine stays 0.0.0.0. Maybe there is some sort of version check between the plugin and the browser. Could using a different brave version do the trick? The brave browser is version 87.1.18.75 and chromium 91.0.4472.114.  I guess I will try using a newer brave version.

**Comment by RaphaelNeubert** [comment]
It turns out it's not possible to get HD on Prime Video on Linux. I'm not sure why but Amazon simply doesn't support it on Linux as statet [here](https://www.primevideo.com/help/ref=atv_hp_nd_cnt?nodeId=GUX9FYHU5D8LC9EJ).  I thought brave was able to stream HD because i knew it worked on Windows. I thought this was Browser dependent not OS dependent.

To get the HD only Wine back after my experiments i used this [this](https://github.com/proprietary/chromium-widevine) script. I manually set the chromium path because that part of the script didn't work. It might be a good idea to add this script to the FAQ (install Widevine section)
