### ISSUE TITLE
Block local IP address

### ISSUE THREAD

**Issue by Rademenes16** [Eloston/ungoogled-chromium#1569]
I noticed that ungoogled chromium **does not** block local IP address, this could be a potential privacy issue. I used whatismybrowser.com website to check both browsers I use - brave and chromium and I see that brave blocks local IP unlike chromium. Could this be updated or it's impossible?

**Comment by wchen342** [comment]
Are you looking for `chrome://flags/#block-insecure-private-network-requests`?

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
