### ISSUE TITLE
(Add to FAQ) Is the Flash player bundled and/or enabled by default like in Chrome?

### ISSUE THREAD

**Issue by magicgoose** [Eloston/ungoogled-chromium#158]
Maybe I'm dumb today, but I think that the answer to this question would be helpful in FAQ:  
Is the Flash player bundled and/or enabled by default like in Chrome?

I think, most users who are interested in this project would like to be sure that there's no surprise about this.

**Comment by Eloston** [comment]
I don't see how this is necessary if [there is a question in the FAQ that answers the question of how to install Flash player](https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#how-do-i-install-flash-player). Seems like simple deductive reasoning to me. Maybe I'm dumb today; let me know.
