### ISSUE TITLE
prune failed

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1581]
## Env
ungoogled-chromium: 91.0.4472.164-1
chromium: https://github.com/chromium/chromium/archive/refs/tags/91.0.4472.164.zip

## Reproduce

all manually, download chromium with the url above, extract to `ungoogled-chromium\build\src` without the leading folder (i.e. no root folder `chromium-91.0.4472.164`)

```shell
λ py ./utils/prune_binaries.py build/src pruning.list
ERROR: 15018 files could not be pruned.
```

**Comment by Area51Kacz** [comment]
@Eloston this bug its still happening in chromium 92

**Comment by Ahrotahn** [comment]
There are differences in the release sources compared to the github source archive.  
Try instead:  https://commondatastorage.googleapis.com/chromium-browser-official/chromium-91.0.4472.164.tar.xz

**Comment by playgithub** [comment]
@Ahrotahn 
Thanks, I think it is true.
