### ISSUE TITLE
Pruning binaries error: 1 files could not be pruned.

### ISSUE THREAD

**Issue by Area51Kacz** [Eloston/ungoogled-chromium#1584]
Version  92.0.4515.131
Command: python "$_utils/prune_binaries.py" ./ "$_ungoogled_repo/pruning.list"

Log error
```
 Pruning binaries
ERROR: 1 files could not be pruned.  
```

Ungoggled goes broken   at 92.0.4515.131

**Comment by Area51Kacz** [comment]
@PF4Public @Ahrotahn @networkException 
Im actually more on  trying to  compile-update  it by myself

But if the build process its broken    i've problems

**Comment by PF4Public** [comment]
Cannot confirm: [fine by me](https://github.com/PF4Public/gentoo-overlay/actions/runs/1094998068)

**Comment by Area51Kacz** [comment]
Its working **with** chromium-92.0.4515.131    or just with chromium-92.0.4515.107 (as me)  
_on opensuse build service + archlinux_

**Comment by PF4Public** [comment]
I've used a8033105b76b614598df33469b717aa75d4586f3
https://github.com/PF4Public/gentoo-overlay/blob/9492594d295bfcaa24134019508a9b34fb6bbcdc/www-client/ungoogled-chromium/ungoogled-chromium-92.0.4515.131-r1.ebuild#L17

**Comment by Area51Kacz** [comment]
And @PF4Public what could im actually doing wrong  (or its an upstream bug...)

_it crashes with 92.0.4515.131  / but works with chromium-92.0.4515.107_

my pkgbuild
https://build.opensuse.org/package/view_file/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch/PKGBUILD?expand=1 

my ungoogled 
https://build.opensuse.org/source/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch/ungoogled-chromium-92.0.4515.131-1.tar.gz?rev=9012b68dd3d3b2cba4827eeb2b78a82c
[ungoogled-chromium-92.0.4515.131-1.tar.gz](https://github.com/Eloston/ungoogled-chromium/files/6927234/ungoogled-chromium-92.0.4515.131-1.tar.gz)

**Comment by Area51Kacz** [comment]
@PF4Public actually this fixed my problem   (i think) 
https://github.com/Eloston/ungoogled-chromium/pull/1573/commits/a8033105b76b614598df33469b717aa75d4586f3

https://build.opensuse.org/package/live_build_log/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch222/Arch/x86_64

**Comment by PF4Public** [comment]
Looks like there's nothing left to do regarding this issue — closing.
