### ISSUE TITLE
Containers à la Firefox

### ISSUE THREAD

**Issue by akasaka99** [Eloston/ungoogled-chromium#1593]
Hello,
Is there some extension which would allow to filter urls and put them in dedicated containers such as Multi-Containers in Firefox.
SessionBox on Chrome is half way there, but does not allow to do an automatic sorting?
Many thanks !

**Comment by PierreAmide** [comment]
Hello, unfortunately this is not a feature supported by chromium. You won't find an extension similar to "Multi-containers account" on chromium.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
