### ISSUE TITLE
Can't locate on OpenStreetMap

### ISSUE THREAD

**Issue by MattRGX** [Eloston/ungoogled-chromium#1594]
**Describe the bug**
When i go to https://www.openstreetmap.org/ or https://wego.here.com/ i'm unable to locate myself on the map.

**To Reproduce**
1. Go to 'https://www.openstreetmap.org/'
2. Click on 'Show my location'
3. See error

**Expected behavior**
Show my location on the map

**Screenshots**

![image_2021-08-06_16-29-20](https://user-images.githubusercontent.com/58740578/128532897-1c9d7e7a-1ed3-47d5-8865-e83d3d04afb7.jpg)

**Environment (please complete the following information):**
 - OS/Platform and version: Windwos 10
 - ungoogled-chromium version: 89.0.4389.114

**Comment by networkException** [comment]
This is a duplicate of #1551

**Comment by PF4Public** [comment]
Closing this issue in favour of #1551
