### ISSUE TITLE
Is there a way to remove those requests rather than redirecting them?

### ISSUE THREAD

**Issue by navaneethkm004** [Eloston/ungoogled-chromium#1597]
Everytime ungoogled-chromium just redirects those request like chrome webstore(https://chrome.9oo91e.qjz9zk/) and google services(https://support.9oo91e.qjz9zk/chrome?p=syncgoogleservices).

Is there a way to remove them rather than redirecting them to qjz9zk domain?

**Comment by networkException** [comment]
Replacing the urls with that domain is basically removing them, the domain will no be resolved as it doesn't exist. Removing all functionally related to every google url in the source would be impossible to maintain, replacing the urls with something other than valid urls might cause undefined behavior.

**Comment by PF4Public** [comment]
> doesn't exist

Unless Google registers it :D

**Comment by PF4Public** [comment]
> 1. Can you completely remove these, cus its no use as it is of now, so why not remove it

The only reason I can think of not to do this is the added maintenance burden for no significant benefit.

**Comment by navaneethkm004** [comment]
Well, I can't deny that. Umm, can you help me with the second part?

**Comment by PF4Public** [comment]
> can you help me with the second part?

Unfortunately, not, not me at least.

**Comment by Ahrotahn** [comment]
I can dig into this a bit and see if it's something that can be added to `remove-uneeded-ui.patch`.  There's no reason to remove every instance of substituted links in the ui, but it's nice to remove the more egregious areas.  The passwords section is something I've been aware of and put off for too long.

**Comment by navaneethkm004** [comment]
> I can dig into this a bit and see if it's something that can be added to `remove-uneeded-ui.patch`. There's no reason to remove every instance of substituted links in the ui, but it's nice to remove the more egregious areas. The passwords section is something I've been aware of and put off for too long.

:) nice bro

**Comment by navaneethkm004** [comment]
@Ahrotahn Hey, I need a small help. I downloaded chromium using depot_tools earlier. But when i checked the modification readme, i saw that i have no option to use this downloaded one. I'm not that experienced, so can you help me with using the downloaded one. #

**Comment by Ahrotahn** [comment]
I'd recommend checking out the instructions on the repo for your platform:  https://github.com/Eloston/ungoogled-chromium/blob/master/docs/platforms.md

There's usually a writeup on the build process that's easier than attempting to set up your own.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
