### ISSUE TITLE
speed up unpacking

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1599]
To save SSD, I run the command
```
./utils/downloads.py unpack -c build/download_cache -i downloads.ini -- build/src
```
on an external disk with USB 3.0.

It is very slow, 2MB/s or so.

What about using memory as cache when extracting?

BTW, better if it shows progress.

**Comment by PF4Public** [comment]
Unpacking is mostly a CPU-bound operation. So in order to speed it up you will need a faster CPU.

**Comment by playgithub** [comment]
> Unpacking is mostly a CPU-bound operation. So in order to speed it up you will need a faster CPU.

AMD R7 now

**Comment by wchen342** [comment]
Is your external disk a mechanical disk?

My guess is because the chromium source has a huge amount of files, constantly read/write on a mechanical disk will be quite slow because the disk needs to constantly search non-continuous positions, and CPU/USB3 will not help in this case.

**Comment by playgithub** [comment]
> Is your external disk a mechanical disk?

Yes, because it writes a lot and I want to save SSD.
