### ISSUE TITLE
TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1601]
## Env
* OS: Windows 10
* Python: 3.9.6
* Chromium: 92.0.4515.131
* Project: https://github.com/Nifury/ungoogled-chromium-windows

## Log
```
...
Traceback (most recent call last):
  File "../../tools/grit/preprocess_if_expr.py", line 112, in <module>
    main(sys.argv[1:])
  File "../../tools/grit/preprocess_if_expr.py", line 107, in main
    json.dump(manifest_data, manifest_file)
  File "Path\To\Python27\lib\json\__init__.py", line 190, in dump
    fp.write(chunk)
TypeError: write() argument 1 must be unicode, not str
...
```

**Comment by Nifury** [comment]
I have `python.exe` and `python2.exe` for Python 2, and `python3.exe` for Python 3. 
Maybe that can help you.

**Comment by playgithub** [comment]
> I have `python.exe` and `python2.exe` for Python 2, and `python3.exe` for Python 3.
> Maybe that can help you.

Thanks very much, it works with a little different naming tricks

* For python2
  * path\to\pthon27\python.exe
  * path\to\pthon27\python2.exe
* For python3
  * path\to\pthon39\python.exe
  * path\to\pthon39\python3.exe

**Comment by playgithub** [comment]
@Nifury 
BTW, do you have the warning when building: `clang-cl: warning: unknown argument ignored in clang-cl: '-fno-ident' [-Wunknown-argument]`
https://github.com/Eloston/ungoogled-chromium/issues/1603

**Comment by Nifury** [comment]
> @Nifury
> BTW, do you have the warning when building: `clang-cl: warning: unknown argument ignored in clang-cl: '-fno-ident' [-Wunknown-argument]`
> #1603

Well yes, but I don't think it matters. You'll also find unused variable warnings here and there, but chromium still compiles and runs without any issue. 
You're welcome to submit PR to fix this issue.

**Comment by playgithub** [comment]
> > @Nifury
> > BTW, do you have the warning when building: `clang-cl: warning: unknown argument ignored in clang-cl: '-fno-ident' [-Wunknown-argument]`
> > #1603
> 
> Well yes, but I don't think it matters. You'll also find unused variable warnings here and there, but chromium still compiles and runs without any issue.

It doesn't matter much to compiler id. Though some it's a hint for hacking.

> You're welcome to submit PR to fix this issue.

I will if I find a solution.

Thanks

**Comment by playgithub** [comment]
As a note, it has been built successfully, and runs successfully.

**Comment by playgithub** [comment]
@Nifury
I've built using your repo, when the download windows has a little problem as below, do you have the same problem?
![Capture](https://user-images.githubusercontent.com/3665590/129477576-400b6a85-0830-47a3-9561-a86024d23571.PNG)

**Comment by Nifury** [comment]
> @Nifury
> It has been built successfully using your repo, when the download windows has a little problem as below, do you have the same problem?
> ![Capture](https://user-images.githubusercontent.com/3665590/129477576-400b6a85-0830-47a3-9561-a86024d23571.PNG)

Ah no. Is there a way to reproduce it?

**Comment by playgithub** [comment]
> > @Nifury
> > It has been built successfully using your repo, when the download windows has a little problem as below, do you have the same problem?
> > ![Capture](https://user-images.githubusercontent.com/3665590/129477576-400b6a85-0830-47a3-9561-a86024d23571.PNG)
> 
> Ah no. Is there a way to reproduce it?

I have tested it on 4 different machines, all have the same problem.
only `flags.windows.gn` is modified as below:
```
blink_symbol_level=0
build_with_tflite_lib=false
chrome_pgo_phase=0
clang_use_chrome_plugins=false
dcheck_always_on=false
enable_hangout_services_extension=false
enable_js_type_check=false
enable_mdns=false
enable_mse_mpeg2ts_stream_parser=true
enable_nacl=false
enable_nacl_nonsfi=false
enable_one_click_signin=false
enable_reading_list=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_swiftshader=false
enable_widevine=true
exclude_unwind_tables=true
ffmpeg_branding="Chrome"
fieldtrial_testing_like_official_build=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
is_chrome_branded=false
is_clang=true
is_component_build=false
is_debug=false
is_official_build=false
proprietary_codecs=true
safe_browsing_mode=0
symbol_level=0
target_cpu="x64"
treat_warnings_as_errors=false
use_gnome_keyring=false
use_official_google_api_keys=false
use_sysroot=false
use_unofficial_version_number=false
```

## Env
* OS: Windows 10 21H1 19043.1165
* cl.exe: 19.29.30133 for x64
* Windows SDK: 10.0.19041.0 (Installed by `Visual Studio Installer`)
* Debugging Tools for Windows: 10.0.19041.685 (What `winsdksetup.exe` shows)

**Comment by Nifury** [comment]
@playgithub Hmmm I don't have a clue. Works fine for me with the default `flags.windows.gn`.

**Comment by playgithub** [comment]
@Nifury I've tried the default flags for windows as below
`flags.windows.gn`
```
chrome_pgo_phase=0
enable_swiftshader=false
ffmpeg_branding="Chrome"
is_clang=true
is_component_build=false
is_debug=false
proprietary_codecs=true
target_cpu="x64"
use_gnome_keyring=false
use_sysroot=false
```

And I aslo tried other combinations of flags, the problem can not fix.
It took me almost one day.

As a note, I've applied `https://github.com/undergroundwires/privacy.sexy` before building chromium. As far as I can see, this chould be the reason. Anyway I have decided to use Linux now, though the GUI is much slower, but developer friendly.

**Comment by Nifury** [comment]
> @Nifury
> It has been built successfully using your repo, when the download windows has a little problem as below, do you have the same problem?
> ![Capture](https://user-images.githubusercontent.com/3665590/129477576-400b6a85-0830-47a3-9561-a86024d23571.PNG)

@playgithub I finally have time to look into this issue. 
```diff
--- a/chrome/browser/ui/webui/downloads/downloads_ui.cc
+++ b/chrome/browser/ui/webui/downloads/downloads_ui.cc
@@ -62,12 +60,6 @@ content::WebUIDataSource* CreateDownload
       source, base::make_span(kDownloadsResources, kDownloadsResourcesSize),
       IDR_DOWNLOADS_DOWNLOADS_HTML);
 
-  bool requests_ap_verdicts =
-      safe_browsing::AdvancedProtectionStatusManagerFactory::GetForProfile(
-          profile)
-          ->IsUnderAdvancedProtection();
-  source->AddBoolean("requestsApVerdicts", requests_ap_verdicts);
+ source->AddBoolean("requestsApVerdicts", false);

   static constexpr webui::LocalizedString kStrings[] = {
       {"title", IDS_DOWNLOAD_TITLE},
       {"searchResultsPlural", IDS_SEARCH_RESULTS_PLURAL},
```

**Comment by playgithub** [comment]
Thank you so much
