### ISSUE TITLE
How can I exclude the patch which blocks installation of extension from chrome/chromium webstore?

### ISSUE THREAD

**Issue by navaneethkm004** [Eloston/ungoogled-chromium#1602]
I would like to exclude the patch which blocks installation of extension from chrome/chromium webstore. Is there a way to do it?

**Comment by networkException** [comment]
I'm pretty sure there's no singular patch to remove and domain substitution will disable support as well. See [the faq](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore) for extension install instructions

**Comment by navaneethkm004** [comment]
So some extension forbid to run if theyre not installed from webstore, is there a way to prevent that.

**Comment by FieryMewtwo** [comment]
Yeah. There's an extension you can manually install called Chromium Web Store. Try that, it takes extensions straight from Google
