### ISSUE TITLE
clang-cl: warning: unknown argument ignored in clang-cl: '-fno-ident' [-Wunknown-argument]

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1603]
## Env
* OS: Windows 10
* Python: 3.9.6
* Chromium: 92.0.4515.131
* Project: https://github.com/Nifury/ungoogled-chromium-windows

## Problem
clang-cl: warning: unknown argument ignored in clang-cl: '-fno-ident' [-Wunknown-argument]

## More Info
https://releases.llvm.org/12.0.0/tools/clang/docs/ClangCommandLineReference.html#cmdoption-clang-qn
The option is supported by clang, however `clang-cl` is different from `clang`.
How to get rid of the warning while keeping the function?

**Comment by playgithub** [comment]
found taht `clang-cl` is different from `clang`, patch needed.

**Comment by wchen342** [comment]
It is simply because of your llvm version. This option is introduced in llvm 13, you probably have clang 11 or 12 on your machine.

**Comment by playgithub** [comment]
> It is simply because of your llvm version. This option is introduced in llvm 13, you probably have clang 11 or 12 on your machine.

`-fno-ident` can be found at https://releases.llvm.org/12.0.0/tools/clang/docs/genindex.html

Do you mean `clang-cl` in `llvm 13`?
