### ISSUE TITLE
Found the issue, the extension was unable to get some headers from chromium for video downloader online use extension

### ISSUE THREAD

**Issue by candrapersada** [Eloston/ungoogled-chromium#1606]
Found the issue, the extension was unable to get some headers from chrome, fixed and check in the code. but will take some time to update and publish the extension in chrome web store. in issue occurred due to api changes in chromium 72.
for video downloader online use extension

**Comment by trimechee** [comment]
Great ! Thank you for making this great extenion ti donwload video ! Uget donwlod manger is amazing but there no more often updates and we hope it will be kept up to date in sha Allah .
So if i understood correctly, there is a problem to download videos using this extension with ungooled chromium ? is there the same problem using other chromium browsers ?

**Comment by candrapersada** [comment]
> So if i understood correctly, there is a problem to download videos using this extension with ungooled chromium?

yes

> is there the same problem using other chromium browsers ?

yes

**Comment by trimechee** [comment]
Thank you :)

**Comment by candrapersada** [comment]
and the problem also occurs in Xtreme Download Manager

**Comment by trimechee** [comment]
Oh thank you for these informations :) we hope there will be a fix !

**Comment by PF4Public** [comment]
Is this still an issue?

**Comment by trimechee** [comment]
No, there is no issue when i used ungoogled chromium
