### ISSUE TITLE
Yet another chrome.9oo91e.qjz9zk problem

### ISSUE THREAD

**Issue by AgoodFriendOfSatan** [Eloston/ungoogled-chromium#1610]
It looks like you had this problem before and fixed it, but the Chrome Web Store is not allowing me in. Is there a good work around for this?

**Comment by AgoodFriendOfSatan** [comment]
For the record, I have enabled "Handling of extension MIME type requests"

**Comment by wchen342** [comment]
You mean the links in NTP/settings? They don't work, you need to search web store and get the right link.
