### ISSUE TITLE
Please create VM appliance for easy one-click Windows compiling!

### ISSUE THREAD

**Issue by AscendChina** [Eloston/ungoogled-chromium#1611]
This has to be said, but someone needs to create and upload a VM machine/appliance be it windows or linux based or whatever that already has pre-configured where it is one-click and we can compile the windows version binary of ungoogled chromium browser to the latest version 92 or whatever is newer at the time, OR just use bandicam or whatever screenrecording and show us step by step how to reproduce the VM compile environment ourselves so that we can easily compile this for Windows....

As of now, the latests downloadable binary is still like back in version 89 which is not acceptable

**Comment by wittytweezers** [comment]
You can find windows builds for more recent versions in [this repo](https://www.github.com/macchrome/winchrome/releases). 
As for building it yourself, it would take several hours (at least the first time) and hundreds of gigabytes. That holds even if you have a VM built especially for that purpose  (see [this](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_build_instructions.md) for details).

**Comment by PF4Public** [comment]
Closing this issue in favour of #1589
