### ISSUE TITLE
PGO support

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1614]
PGO = Profile Guided Optimization
I think it can achieve decent optimizaitons.
Is it possible to be supported?

now, `flags.gn`
```
chrome_pgo_phase=0
```

**Comment by PF4Public** [comment]
> PGO = Profile Guided Optimization
> I think it can achieve decent optimizaitons.

It does indeed make a little bit of a difference, but arguably increases the compilation time. I use it for a long time now.

> Is it possible to be supported?
> 
> now, `flags.gn`
> 
> ```
> chrome_pgo_phase=0
> ```

Apart from setting [chrome_pgo_phase=2](https://github.com/PF4Public/gentoo-overlay/blob/0037e3f513d8172663cdf7bc13ba17301515381b/www-client/ungoogled-chromium/ungoogled-chromium-92.0.4515.159-r1.ebuild#L737-L741) you also need [to keep prof data from pruning](https://github.com/PF4Public/gentoo-overlay/blob/0037e3f513d8172663cdf7bc13ba17301515381b/www-client/ungoogled-chromium/ungoogled-chromium-92.0.4515.159-r1.ebuild#L327-L330).


As a side note, I would also suggest [using PartitionAlloc explicitly](https://github.com/PF4Public/gentoo-overlay/blob/0037e3f513d8172663cdf7bc13ba17301515381b/www-client/ungoogled-chromium/ungoogled-chromium-92.0.4515.159-r1.ebuild#L668-L670) as it also does some improvements unless it is already enabled by default (IIRC they toggled it for some reasons recently).
