### ISSUE TITLE
Alt desktop/taskbar icon colors (for accessibility)

### ISSUE THREAD

**Issue by account123123123** [Eloston/ungoogled-chromium#1617]
**Is your feature request related to a problem? Please describe.**
Sort of. The blue monotone color of the icon looks too similar to Discord and it can be hard for me to tell the difference due to my eyesight. 

**Describe the solution you'd like**
Alternative color icons, by a setting in the application or just different executables. Another thread (#1193) suggested a new style of icon, but this suggestion would be to add several variants of the icon, simply a different recolor or with more contrast. 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/18605150/130716793-31abedfe-102c-4bed-88bd-915176fec8ff.png)

**Comment by PF4Public** [comment]
Have you considered replacing the icon locally while building yourself?
