### ISSUE TITLE
Error building on OS X

### ISSUE THREAD

**Issue by furetosan** [Eloston/ungoogled-chromium#162]
Hi,

Got an error trying to build. 

> Applying patch ../patches/ungoogled-macos/fix-widevine-macos.patch
> patching file third_party/widevine/cdm/BUILD.gn
> Hunk #1 FAILED at 92.
> 1 out of 1 hunk FAILED -- rejects in file third_party/widevine/cdm/BUILD.gn
> Patch ../patches/ungoogled-macos/fix-widevine-macos.patch does not apply (enforce with -f)
> 2016-12-30 09:00:50,526 - ERROR: Quilt returned non-zero exit code: 1

Am willing to help support the OS X build branch.

Cheers

**Comment by 9Morello** [comment]
The patch is applying fine here. Did you install `quilt` beforehand?
After applying it, you're going to run into the first problem of [this post](https://github.com/Eloston/ungoogled-chromium/issues/161). Using the same solution provided by him (but using OSX's `cleaning_list` instead) should fix it.

**Comment by nopjmp** [comment]
I got the same thing. I have the patch updated in my local tree and I'll submit a pull request when I get home this evening.

I'm currently discussing with @Eloston what to do about the icu data. It's just a lookup table as far as I can tell. While it is a binary blob, it can be regenerated which files under the acceptable binary blobs in my book.

**Comment by 9Morello** [comment]
@nopjmp Oh. Thats strange. I just tested it from scratch and its working normally here.
About the icu data file, maybe buildlib can download and compile it. I had to manually compile it on Ubuntu 14.04.

**Comment by nopjmp** [comment]
@9Morello build instructions are in the third_party/icu/README.chromium macOS and Linux will probably not have problems, but Windows it would be a nightmare since it's a bash script.

**Comment by nopjmp** [comment]
@Eloston not sure, but this can probably be closed now since the build fix commit got merged. we can discuss icu in another issue if needed

**Comment by Eloston** [comment]
Alright.
