### ISSUE TITLE
Please make the ungoggled chromium executables be available directly in GitHub releases page or the website.

### ISSUE THREAD

**Issue by clicky6** [Eloston/ungoogled-chromium#1623]
Please make the ungoggled chromium executables be available directly in releases page or the website.
It is somewhat hard for normal user to figure out where to download Ungoggled-Chromium executables from & If they figure out then also the executable is from someone else not the official Ungoggled-Chromium GitHub releases page or website so there exists some fear of getting something wrong so Please give the executables in above two places instead of giving it through random persons.

Why you have to give this message on Ungoggled-Chromium download page:-
IMPORTANT: These binaries are provided by anyone who are willing to build and submit them. Because these binaries are not necessarily reproducible, authenticity cannot be guaranteed. For your consideration, each download page lists the GitHub user that submitted those binaries.

If you can build the binaries yourself and give it in the releases section or on the download page website that would be amazing and we will not have any fear of the above warning because we are getting official binaries only from official trusted sources.

Please consider this opinion ,It would help Ungoggled-Chromium reach more users who are afraid to download executables from other persons it would be much better.

Regards

**Comment by wchen342** [comment]
The reason there is no official binaries is largely because the cost of building chromium requires additional servers and other maintenance. For Linux versions we have some automatic builds running on OpenSUSE's build service, but for Win/Mac that is not an option and we don't have extra servers/infrastructures to support builds ourselves.

Maybe this needs to be added to the download section of README too? Also I think @Eloston is not considering anything financial if I remember correctly?

**Comment by brodybits** [comment]
Shouldn't it be possible to use GitHub actions to build releases for Linux, mac, and Windows, considering that they do support running actions on all of these systems? Or am I mistaken somehow?

**Comment by wchen342** [comment]
The free tier of Github Actions without your own self-runners has a hardware limitation of 4 cores and running time upper limit of 6 hours, so in the past I and some others tried make the building into multiple parts but that is very difficult and has several bugs/caveats. You can still found those if you go through the historical commits in the Arch repo. In the end I found that unmaintainable.

**Comment by networkException** [comment]
GitHub Actions can be used in the free tier with a lot of effort. A workflow is limited to 72 hours and a job to 6 hours, effectively forcing the build process to be paused after 6 hours, its progress to be saved and then a new job to be started using the old process. Besides that builds also take extremely long, we are talking 24 - 27 hours. (as wchen342 already mentioned this was an issue for the Arch Linux repository, I would say the current solution I came up with is quite sophisticated but also not perfect as I am naturally only able to solve the logistics issues related to pausing the build process <https://github.com/ungoogled-software/ungoogled-chromium-archlinux/tree/master/.github>)

This still leaves the question what can be considered official binaries in the first place and when those are trustworty (see #1549). I myself am in favor of using the ungoogled-software organisation on GitHub as the only "source of truth" (besides maybe the location of this repository on Elostons account which has historical reasons, see https://github.com/Eloston/ungoogled-chromium/discussions/1305#discussioncomment-256140) and base build scripts and ci off those. This of course gets influenced by me being part of this organisation which allows me to verify the arch builds I maintain as legitimate, other users will have different opinions about the trustworthyness of this approach.

**Comment by clicky6** [comment]
What is the conclusion?

**Comment by Eloston** [comment]
>  Also I think @Eloston is not considering anything financial if I remember correctly?

I am open to this, but I don't want to be responsible for managing the finances. My time is more limited than I'd like for this project, so I'd rather focus my time on technical and leadership challenges.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
