### ISSUE TITLE
abnormal download window

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1628]
## Problem
![image](https://user-images.githubusercontent.com/3665590/131638693-da379b14-ed42-4fc4-a1a7-f5f5762b2388.png)

## Env
OS: Windows 10
SDK: Windows 10 SDK 10.0.19041.685
Chromium: 92.0.4515.159 & 92.0.4515.131

## Project
https://github.com/playgithub/ungoogled-chromium-windows

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

**Comment by playgithub** [comment]
solved at https://github.com/Eloston/ungoogled-chromium/issues/1601#issuecomment-925499796
