### ISSUE TITLE
Fail to use ExtensionSettings policy in ungoogled-chromium.

### ISSUE THREAD

**Issue by lessload** [Eloston/ungoogled-chromium#1629]
Ref : https://support.google.com/chrome/a/answer/9867568
Try to config something like this code to auto install extensions.
```
{
    "*": {
        "installation_mode": "allowed"
    },
    "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
        "installation_mode": "force_installed",
        "update_url": "https://clients2.google.com/service/update2/crx"
    }
}
```
but fail with policy error
```
Key "cjpalhdlnbpafiamejdnhcphjbkeiagm": This computer is not detected as enterprise managed so policy can only automatically install extensions hosted on the Chrome Webstore. 
The Chrome Webstore update URL is "trk:05:https://clients2.9oo91e.qjz9zk/service/update2/crx".
```
As i understand you prevent browser from leak to "clients2.google.com"
Is it posible to allow user to use it ? like flag setting?
For easy deploy in company.

**Comment by networkException** [comment]
By design domains get replaced after any custom modifications to the source code have been done. Excluding a file from domain substitution is therefore something that can not really be done by flag, you would have to manually compile a binary after exluding the file.

**Comment by squid-f** [comment]
Hi. 
I have also been trying to use the policy feature and failed. 
However, I have been able to load an extension using the master_preference file. I am still not able though to get it updated at start and fully functioning. 
Have you tried that way and succeeded?
Or am I stuck because of the same limitations? I don’t have any error displayed though.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
