### ISSUE TITLE
How does `brave` compare to `ungoogled-chromium` considering privacy?

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1630]

**Comment by networkException** [comment]
I've came across [this blog post](https://ebin.city/~werwolf/posts/brave-is-shit/) a while ago, its a bit over exaggerated but still should give a good idea on how brave behaves. There is also [another blog post](https://qua3k.github.io/ungoogled/) about ungoogled-chromium which I will include for completeness. To me only user submitted binaries and lacking behind official releases is an actual problem, the rest I'd say is just not understanding what the patchset mainly targets to do - remove google integration from chromium

**Comment by playgithub** [comment]
I'll not use `brave`, thanks.
