### ISSUE TITLE
Are Security Fixes for Chromium Backported to Ungoogled Chromium?

### ISSUE THREAD

**Issue by Anish-M-code** [Eloston/ungoogled-chromium#1633]
Currently Ungoogled chromium uses chromium 92.0.4515.159 but latest chromium release is 93.0.4577.63 , i heard that there are many security issues in older version of chromium as stated in https://chromereleases.googleblog.com/2021/08/stable-channel-update-for-desktop_31.html , just curious on whether  security fixes are  backported  ( Like Debian ) to current ungoogled chromium release or we have to wait for new release to get security fixes.

**Comment by networkException** [comment]
There are no backports, ungoogled-chromium releases are based on upstream releases with our patched and modifications applied. Updating the patchset can take a while as it's a community effort (see #1624)
