### ISSUE TITLE
Impossible to Restore a Previous Backed-up Folder 

### ISSUE THREAD

**Issue by kin-patsu** [Eloston/ungoogled-chromium#1634]
**Describe the bug**
After formatting my OS, I reinstalled ungoogled chromium and restored every folder to its place. The previous size and position of the window was successfully restored, however everything else (bookmarks, history, saved passwords and so on) weren't and opening chromium settings gives an error, saying that it wasn't possible to restore the previous settings.

**To Reproduce**
1. Format the OS
2. Try to put the profile folder to the proper place

**Expected behavior**
Previous open tabs, history and favorites should be restored

**Environment (please complete the following information):**
 - OS/Platform and version: Windows
 - ungoogled-chromium version: doesn't matter

**Comment by networkException** [comment]
I've moved my directory from macOS to different Linux distros over multiple harddrives without any issues. Chromium showing an error instead of just giving you default settings sounds like corrupted data

**Comment by wchen342** [comment]
If it's windows it can also be [this](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/36).

**Comment by kin-patsu** [comment]
> If it's windows it can also be [this](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/36).

It's most likely that error. I just had to reinstall Windows, and importing the old chromium folder only partially restored my data

**Comment by PF4Public** [comment]
Closing this issue in favour of ungoogled-software/ungoogled-chromium-windows#36
