### ISSUE TITLE
Video playback in udemy is not working

### ISSUE THREAD

**Issue by altBatman** [Eloston/ungoogled-chromium#1638]
I am not sure whether it is a problem with Udemy developers or my Ungoogled chromium is missing some plugin.

I have tried the latest versions from bot mac and windows versions. Both didn't work

**Comment by networkException** [comment]
Some Udemy courses use DRM, you could try [instructions from the faq](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-install-widevine-cdm)

**Comment by altBatman** [comment]
> Some Udemy courses use DRM, you could try [instructions from the faq](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-install-widevine-cdm)

Still Not working. I installed the widevine module

**Comment by PF4Public** [comment]
Please provide more information on the issue, so that someone could help you further. That is some console logs / developer tools logs, etc.

**Comment by altBatman** [comment]
`{
    "code": 4,
    "message": "No compatible source was found for this media.",
    "responseStatus": 200,
    "responseURL": "https://www.udemy.com/assets/18888406/encrypted-files/out/v1/00c939e3794c44d89d0e0ccd005d5459/f1a19e30df3f4529939385f046863720/6045af0b578e4f29b9b0594ae6d0eaca/index.m3u8?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzM3MDk0MDMsInBhdGgiOiJvdXQvdjEvMDBjOTM5ZTM3OTRjNDRkODlkMGUwY2NkMDA1ZDU0NTkvZjFhMTllMzBkZjNmNDUyOTkzOTM4NWYwNDY4NjM3MjAvNjA0NWFmMGI1NzhlNGYyOWI5YjA1OTRhZTZkMGVhY2EvIn0.21f7qw9rBspoGlk2S-Wx9uB74Tz7zCR1ksaZ6ZETM8Q&provider=cloudfront&v=1",
    "responseContentType": "application/x-mpegURL"
}`

Also a VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.
