### ISSUE TITLE
Impossible to increase the cache size beyond the 2Gb limit

### ISSUE THREAD

**Issue by trimechee** [Eloston/ungoogled-chromium#1649]
Hi, Ungoogled Chromium is amazing and wonderful!
Thank you very much!
Please I have an important vital request: I watch movies and tv series in streaming and also sports events in live streaming and the quality is in high definition and sometimes my wifi internet connection or data plan has become weak and it stutters, so it is important for me to increase the size of the Ungooled Chromium cache folder to avoid jerks and to have a sufficient buffer, I set a size of 10 Gb but it failed, I changed the default location of the folder cache but when I check the size of the cache folder of Ungoogled Chromium, it never exceeds 2Gb, I tried with firefox and I was able to increase the cache size to 10 Gb by changing some settings and playing the videos on firefox is much smoother than other chormium based browsers I have installed, it will be great if our beloved Ungooled Chromium which gives us so much freedom, it will be great if Ungoogled Chromium gives us an option to increase the cache beyond 2Gb because I could not increase the size of the cache beyond 2 Gb on Ungooled Chromium and it poses a big problem for me to play the live streaming video of a soccer match and view the videos in very high definition, 
on firefox I pause the video for two or three minutes and I can watch the videos without jerks unlike other Chromium based web browsers but I like Ungoogled Chromium so much and I would like it to be my browser by default and that will be great if Mr Eleston and and the Ungoogled Chromium team can invent an ingenious and brilliant idea that allows us to increase the size of the cache located in C: \ Users \ Asus \ AppData \ Local \ Chromium \ User Data \ Default \ Cache on windows 10 and it will be an incredible exclusivity of Ungoogled Chromium!

Thank you very much for this wonderful browser :)

**Comment by Ahrotahn** [comment]
The max size for the cache is stored in a 32-bit integer which is why the limit is ~2GB (2,147,483,647 bytes).  There were some changes a few years ago that updated some parts to in64_t's but individual entries are still limited to int32_t size.  It might be better in your situation to download the video you want to watch rather than streaming.

**Comment by trimechee** [comment]
Thanks a lot for your help !
Yes ! that's what I did, but sometimes the videos are hyper protected on streaming sites and it's complicated to download them  (i'm not talking about DRM) so i use FireDM downloader and there were videos I could not download from my.mail.ru and I had to contact the developer to help me resolve this issue ....

So it's not very easy to to download somes videos especially since sometimes the download speed is low and even if I activate the "chrome: // flags / # enable-parallel-downloading" flag, I fear that my IP address will be blacklisted .....

In addition I watch episodes of a TV series and I skip a lot of passages and parts so it's not very practical and fast to download everything if I am going to skip a lot of parts of the tv episode so usually I do not watch whole video , it may end up with bandwidth overuse since a lot of downloaded data eventually will be not watched.

I solved this problem by putting a specific web browser for streaming and regularly clearing the cache, but it's a bit boring lol, it 's it's surprising that we have 1TB HDDs, and even maybe hard drives more than 1000 Gb, Chromium does not allow to increase the cache, I increased the cache in Frefrox to 10Gb and Firefox remained lightning fast and no bugs .....

We hope that the developers of Chromium will add an option to modify this parameter which seems essential to me in sha Allah and I thank you very much for your help and we thank you very much for making releases of Ungoogled-Chromium :)

 please I have a question, on the Woolyss page:
https://chromium.woolyss.com/

there is a sync version of Ungoogled Chromium, so the sync version activates all google APIs eg gmail and youtube or just activates only one API, sync?
and if the google APIs are enabled, sites like gmail, google docs, youtube .... work better?

Another question please, there are many  torrent audiobook and videos and tv programs on "archive.org" and torrent audiobook site free public domain audiobooks 
 https://librivox.org/ ,  

is it possible that Ungoogled Chromum and browsers based on Ungoogled Chromoum add natively this important torrent protocol  "webtorrent" which allows to instantly play torrent video and audio ?

https://webtorrent.io/

**Comment by tomasz1986** [comment]
> please I have a question, on the Woolyss page:
> [chromium.woolyss.com](https://chromium.woolyss.com/)
> 
> there is a sync version of Ungoogled Chromium

From what I can see, the "sync" version is just the standard Chromium, not the Ungoogled one. Which link there do you have in mind specifically?

**Comment by trimechee** [comment]
On the official download page of Ungoogled Chromium, there is only Ungoogled Chromium 89 for windows 10 64bits, I stayed with this version for a long time because I love Ungoogled Choromium but there is no more updates so I decided to search on Github for fork of Ungogoled Chromium, I found this version and in the description, it says:                                                                           "Builds with sync
Widevine support
Sync enabled using Google API keys
H.264 in WebRTC enabled
Builds without sync
No Widevine support
No Google API keys (set to "no")
H.264 in WebRTC disabled "

https://github.com/Hibbiki/chromium-win64

so I was wondering if in the Woolys site, is there a version where the different google APIs are enabled in Ungooled Chromium?

**Comment by trimechee** [comment]
Excuse me, off topic, I discovered with surprise this post on Ungoogled Chromium, what do you think please ? is that true or false?

https://github.com/privacytools/privacytools.io/issues/274#:~:text=There%20is%20no%20privacy%20with%20ungoogled%20chromium%2C%20all%20the%20stuff%20that%20you%20can % 20easily% 20fingerprint% 20with% 20Chromium% 20 (fonts% 2C% 20canvas% 2C% 20 ...)% 20is% 20fairly% 20sufficient% 2C% 20and% 20when% 20coupled% 20with% 20the% 20lack% 20of% 20any% 20first % 20party% 20isolated% 2C% 20shows% 20that% 20one% 20can% 27t% 20expect% 20to% 20be% 20safe% 20from% 20browser% 20fingeprinting% 20and% 20tracking% 20with% 20it.

**Comment by trimechee** [comment]
Please another question, in the description of this software, it sayes : "Chromium for 64-bit Windows - All Codecs: MS Visual Studio 2020", that means we should install MS Visual Studio 2020 for this software to work?

https://github.com/macchrome/winchrome

**Comment by PF4Public** [comment]
> https://github.com/macchrome/winchrome

Those binaries are distributed separately from ungoogled-chromium by @macchrome

**Comment by trimechee** [comment]
It's good to know, thank you !

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.

**Comment by trimechee** [comment]
No, my questions were not all answered, I wanted to know if the ungooled chromium version of wolyss contains the different google APIs, like that of youtube, gamil ....

**Comment by networkException** [comment]
This project is not affiliated to woolyss binaries, the issue tracker is only meant for questions directly related to the ungoogled-chromium patchset.

**Comment by trimechee** [comment]
Yes I know but in the official page of Unggoled Chromium,

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

  there is no MORE the updated version for windows 64bits for a long time and so it is legitimate that ungooled chromium lovers are looking for a reliable updated version, woolyss said that Eleston knows that the wolyss site compiles ungoogld chromium, so  we are looking for where to download ungooeld chromium with sync with the different google APIs enabled, can you help us please ? where we can find a trusted version of unggoled chromium 64bits for windows 10 ?
