### ISSUE TITLE
#global-media-controls flag gone.

### ISSUE THREAD

**Issue by egg4096** [Eloston/ungoogled-chromium#1656]
Despite being reffered to by other flags on the `chrome://flags` page, the `#global-media-controls` flag, which can be used to disable this button (shows up in the top right next to the "Extensions" button while playing YouTube videos & other media):
![Screenshot from 2021-09-21 23-21-43](https://user-images.githubusercontent.com/72076491/134242022-cadfddd6-e78f-4e54-8651-7dcbc47b467b.png)
...is either hidden or removed from `chrome://flags`.
###### _I hope I'm not being an annoyance by missing something obvious._

**Comment by networkException** [comment]
As far as I can tell the flag has not been present since 85: <https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/flag-metadata.json;drc=0ff877a2651bf0e328ef53620a1f01dcbb09b8f9;l=3331>

**Comment by Ahrotahn** [comment]
It can still be disabled by adding `--disable-features=GlobalMediaControls` to your launch switches.  

The code for the flag still exists, so another option if you're compiling your own build would be to edit the file @networkException pointed out and set the expiry to a later version or remove the entry.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
