### ISSUE TITLE
Harfbuzz 3.0 breaks startup

### ISSUE THREAD

**Issue by seanluse41** [Eloston/ungoogled-chromium#1658]
Version 92.0.4515.159 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

Harfbuzz and harfbuzz-icu 3.0 and trying to run gives

`undefined symbol  hb_subset_input_set_retain_gids`
Downgrading to harfbuzz / harfbuzz-icu 2.9.1-1 allows startup as normal.

**Comment by git-bruh** [comment]
Already reported here https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/147. Also, issues relating to distro-specific packages should be raised on their corresponding repo.

**Comment by networkException** [comment]
The referenced issue will be used for tracking
