### ISSUE TITLE
ungoogled Chromium won't start on MX Linux

### ISSUE THREAD

**Issue by mochipancakes** [Eloston/ungoogled-chromium#1660]
I am running MX Linux 19.4 ahs on a virtual machine and just installed ungoogled Chromium as a flatpak. Unfortunately, whenever I try to open it, I always get this error
![Chromium_Wont_Open](https://user-images.githubusercontent.com/57260257/134571560-13986196-349c-4121-99e5-f6d2735b541c.png)

Here is the flatpak version I am using, updated from a Debian backport.
![Flatpak_Version](https://user-images.githubusercontent.com/57260257/134571610-4cab3c83-00c1-44f8-b59b-ecd609b782d9.png)

I followed the instructions from the error message and here's what happened.
![dpkg-statoverride_Not_Working](https://user-images.githubusercontent.com/57260257/134571652-691f17b9-9cb4-4a02-a890-3887c2fd44a4.png)

In case it helps, here are my settings on my /etc/sysctl.conf file
```
kernel.core_pattern=|/bin/false
fs.suid_dumpable=0
vm.swappiness=0
kernel.kptr_restrict=2
kernel.dmesg_restrict=1
kernel.printk = 3 3 3 3
kernel.unprivileged_bpf_disabled=1
kernel.kexec_load_disabled=1
kernel.sysrq=4
kernel.unprivileged_userns_clone=0

kernel.perf_event_paranoid=3

net.core.bpf_hit_harden=2
dev.tty.ldisc_autoload=0
vm.unprivileged_userfaultfd=0

net.ipv4.tcp_syncookies=1
net.ipv4.tcp_rfc1337=1
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1

net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.default.secure_redirects=0
net.ipv6.conf.all.accept_redirects=0
net.ipv6.conf.default.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.default.send_redirects=0

net.ipv4.icmp_echo_ignore_all=1

net.ipv4.conf.all.accept_source_route=0
net.ipv4.conf.default.accept_source_route=0
net.ipv6.conf.all.accept_source_route=0
net.ipv6.conf.default.accept_source_route=0

net.ipv6.conf.all.accept_ra=0
net.ipv6.conf.default.accept_ra=0

net.ipv4.tcp_sack=0
net.ipv4.tcp_dsack=0
net.ipv4.tcp_fack=0

kernel.yama.ptrace_scope=3

vm.mmap_rnd_bits=32
vm.mmap_rnd_compat_bits=16

fs.protected_symlinks=1
fs.protected_hardlinks=1
fs.protected_fifos=2
fs.protected_regular=2
```
(**Note:** I switched _kernel.unprivileged_userns_clone_ to 1 and I still got the same error from trying to open ungoogled Chromium)._

.Please reply back as soon as possible.
Thank you.

**Comment by mochipancakes** [comment]
Just to double check if its my settings causing this problem, I started a brand new virtual machine with the MX Linux ahs ISO without installing the OS. Upgraded flatpak and installed ungoogled Chromium. Running it still fetched me the same error as before
![Same_as_Before](https://user-images.githubusercontent.com/57260257/134574541-903e6eec-bb32-4557-b8d9-cab483964055.png)
.

**Comment by wchen342** [comment]
Flatpak related issues shall go to [flathub/com.github.Eloston.UngoogledChromium](https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues).

**Comment by mochipancakes** [comment]
Thank you. I just reposted my issue there.
Sorry about that.

**Comment by PF4Public** [comment]
Which means, we may close this issue here, right?
