### ISSUE TITLE
Screen Sharing not working in Google Meet 

### ISSUE THREAD

**Issue by pagenstedt** [Eloston/ungoogled-chromium#1663]
**Describe the bug**
Screen Sharing not working, when using Google Meet
**To Reproduce**
1. Opened new Google Meet Session
2. Click on Screen Share Button
3. See error: Screensharing not possible in browser

**Expected behavior**
Screen Sharing should work.

**Environment (please complete the following information):**
 - OS/Platform and version: Fedora 35, Gnome 41 with Wayland
 - ungoogled-chromium version: Version 93.0.4577.82 (Official Build, ungoogled-chromium) (64-Bit)

**Additional context**
 I enabled chrome://flags/#enable-webrtc-pipewire-capturer

**Comment by Ahrotahn** [comment]
Screensharing on Google Meet requires the browser to be built with the `enable_hangout_services_extension` GN flag set to true.  It's left up to each of the platforms to include it or not, but I'm not aware of any that do.  You would likely have to create your own build with the flag enabled.

**Comment by pagenstedt** [comment]
OK, thanks a lot. Will use Chromium for this special purpose then.
