### ISSUE TITLE
Microphone and webcam not working

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#1664]
Hi, when I try to allow the access to the microphone to discord but it don't detect a microphone or webcam at all even though my mic/webcam is plugged in and work on firefox,chromium and all other app except ungoogled-chromium

Step To Reproduce:

Go to discord.com.
Login.
Allow discord.com to have access to the microphone/webcam.
Try to call someone.
And the mic won't be detected.
Expected Behavior:

The mic/webcam should be detected/working
OS/Platform and version:

Kubuntu 21.04 Linux
ungoogled-chromium Version 91.0.4472.77 (Official Build, ungoogled-chromium) custom (64-bit)
Additional Information:
Downloaded from snap
I tried "audio_capture_enabled": false and "audio_capture_enabled": true to /home/user/.config/chromium/Default/Preferences as in the FAQ

Thanks in advance and if you need more details to ask them ! :)

EDIT: Work in the portable build but still not in the snap version maybe because of the version:
snap version : 91.0.4472.77
protable build version : 91.0.4472.164
Is this bug because of the version difference ?

**Comment by Ahrotahn** [comment]
Snap's isolation prevents microphone usage by default.  You should be able to enable it by going to the software center, going into ungoogled-chromium's details, then in the permissions there should be a toggle to allow recording audio.
