### ISSUE TITLE
Need a bit of help with building 94.0.4606.54 on Void linux

### ISSUE THREAD

**Issue by DAINRA** [Eloston/ungoogled-chromium#1666]
I'm trying to get a testing build going on Void Linux, so I've been basing my test branch ([link](https://github.com/DAINRA/ungoogled-chromium-void/tree/testing-94.0.4606.54)) on the v93 template that builds and patching what errors I encountered. My latest test fail seems to be related with the ungoogled-chromium patch set.

The build fails in:
`components/signin/internal/identity_manager/primary_account_manager.cc`
at the following code:
```
#if DCHECK_IS_ON()
  {
    std::string pref_account_id;
    bool consented_to_sync =
        client_->GetPrefs()->GetBoolean(prefs::kGoogleServicesConsentedToSync);

    DCHECK(pref_account_id.empty() || !consented_to_sync ||
           pref_account_id == account_info.account_id.ToString())
        << "account_id=" << account_info.account_id
        << " pref_account_id=" << pref_account_id;
  }
#endif  // DCHECK_IS_ON()
```
with `kGoogleServicesConsentedToSync` being undefined.

The only reference to that file that I found is in ungoogled-chromium's patches:
`patches/core/ungoogled-chromium/remove-unused-preferences-fields.patch`

For now I patched the build with `bool consented_to_sync = false;` and I'm waiting to see if it still fails (ccache is a bit useless this days >_<), but in the mean time if someone more knowledgeable could help me understand why this is happening or if there is a better fix, I would be grateful.

Edit: well just saw that void-packages updated chromium template to 94.0.4606.61 so I'm going to rebase on that, but my question still stands :)

**Comment by Ahrotahn** [comment]
Generally most builds are made with `is_official_build=true` or `is_debug=false` which would skip that section entirely.

**Comment by DAINRA** [comment]
Ah i see, the old template from v93 had `is_debug=false` and that was enough, and the void team added the `is_official_build=true` to the v94 template. I'm thinking the changes to `fieldtrial_testing_like_official_build` might be the root cause of the problem.
Thanks a lot for the reply :).
