### ISSUE TITLE
[Flatpak Wayland] "support.9oo91e.qjz9zk" blocked on Stadia when using --ozone-platform=wayland

### ISSUE THREAD

**Issue by gegoxaren** [Eloston/ungoogled-chromium#1667]
**Describe the bug**
When I force the use of Ozone platform for native wayland support, the browser blocks requests to support.9oo91e.qjz9zk, but net when I do not force Ozone Platform.

Google Chat, GMail and YouTube works fine.

**To Reproduce**
1) start ungoogled-chromium with the flags `--enable-features=UseOzonePlatform --ozone-platform=wayland`
2) go to stadia.com (and log in).
3) get error message.

**Expected behavior**
It showing the stadia games page.

**Environment (please complete the following information):**
 - OS/Platform and version: Flatpak under Ubuntu 21.04
 - ungoogled-chromium version: 94.0.4606.54

**Comment by wchen342** [comment]
Normally this shall go [flathub/com.github.Eloston.UngoogledChromium](https://github.com/flathub/com.github.Eloston.UngoogledChromium) but this one is probably not flatpak specific. What do you think @rany2?

**Comment by rany2** [comment]
@wchen342 I doubt this is Flatpak specific. I'm not doing anything that should cause this to happen on Flatpak only.

**Comment by TimB87** [comment]
This is not flatpak specific, I get that redirect on youtube videos when I try `--ozone-platform=wayland` with sway.

**Comment by Ahrotahn** [comment]
That link is normally displayed on crashed tabs.  Is the actual issue that the tab is crashing and you were just following that link afterwards?  

I guess I should add that link to the ui removal patch...

**Comment by PF4Public** [comment]
What is the status of this issue?

**Comment by TimB87** [comment]
I can only speek for my issue which wasn't the same as OPs and this is resolved a few releases back already.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
