### ISSUE TITLE
Install chromium and ungoogled chromium at the same time without conflict

### ISSUE THREAD

**Issue by trimechee** [Eloston/ungoogled-chromium#1668]
Hello, Linchrome is wonderful and amazing, thank you very much !
Please I have a problem: I installed Chromium 94 with sync for windows 10  from woolyss website (made by Hibbiki) then I installed Ungooled Chromium 94 because I want to have these two distinct browsers for different uses but after the installation of ungooled chromium , Unggoled chromium made  replaced my chromium with sync  and took the place of my chromium browser, please can you fix this problem by changing the name of chrome processes to unggoled chromium or change the default folder location of ungoogled chromium so that I can use these two browsers at the same time ?
Thank you so much !

**Comment by PF4Public** [comment]
Have you tried [--user-data-dir=](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/user_data_dir.md)?

**Comment by trimechee** [comment]
No ! what should I do  exactly please ? because when I installed Ungoogled chromium after installing chromium, ungoogled chromium took the place of my chromium because I no longer have my usual search engine because ungoogled chromium has disabled my search engine .....

**Comment by PF4Public** [comment]
Please read the documentation I linked.

**Comment by trimechee** [comment]
Ahh I did not realize that it is a link ! Great ! Thank you very much for your precious help :)

**Comment by PF4Public** [comment]
Feel free to close this issue if it solves it for you.

**Comment by trimechee** [comment]
Yes of course :)
