### ISSUE TITLE
Yubikey logins broken on Google accounts?

### ISSUE THREAD

**Issue by rolodato** [Eloston/ungoogled-chromium#167]
When trying to use a Yubikey to log in to a Google account, I always get "An unexpected error occurred":

![image](https://cloud.githubusercontent.com/assets/829698/21807263/adcd87d0-d71c-11e6-8e35-c6d02b8bc864.png)

Clicking on Retry just reloads the page and shows the error again. This works just fine on Chrome out of the box, no extensions or configuration needed. It also works on Firefox by installing a U2F extension.

Strangely enough I am able to log in to GitHub using a Yubikey, but not Google. I don't see any failed requests or JS errors in devtools, so not really sure what could be causing this. Thanks!

**Comment by Eloston** [comment]
[Have you tried this?](https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#fido-u2f-security-keys-are-not-working-in-google-sign-in)

**Comment by rolodato** [comment]
Sorry, I'm blind and need to RTFM better. Thanks!
