### ISSUE TITLE
White line bug after update

### ISSUE THREAD

**Issue by methane4** [Eloston/ungoogled-chromium#1672]
**Describe the bug**
A white line now appears after update. (see screenshots)

**To Reproduce**
1. open ungoogled-chromium

**Expected behavior**
The line not be visible like past versions

**Screenshots**

![Screenshot from 2021-09-28 15-15-51](https://user-images.githubusercontent.com/46012160/135105877-558a8273-a0fa-4a19-b7ea-9a5f7015e812.png)

![Screenshot from 2021-09-28 15-15-59](https://user-images.githubusercontent.com/46012160/135105914-2de5de10-64cc-464c-9478-5522d2a3326e.png)

![Screenshot from 2021-09-28 15-19-04](https://user-images.githubusercontent.com/46012160/135105933-f809ed8b-8a0b-4b4c-b8cd-cc198bf2620a.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Linux(Fedora) - Flatpak
 - ungoogled-chromium version: flatpak 94.0.4606.61

**Comment by networkException** [comment]
This is an upstream design change

**Comment by methane4** [comment]
ugh, looks horrible and out of place. thank you i will close it if there is no need further neeed

**Comment by networkException** [comment]
This might be a good fit for https://github.com/ungoogled-software/contrib but for the main patchset its out of scope.

**Comment by methane4** [comment]
> This is an upstream design change

btw do you have a source for it? maybe it will be useful for someone too

**Comment by Ahrotahn** [comment]
I have a patch that fixes this that I intend to submit to the contrib repo.  I'll try to get that PR up sometime soon.
