### ISSUE TITLE
Ability to Disable shortcuts on the new tab page

### ISSUE THREAD

**Issue by nesper8** [Eloston/ungoogled-chromium#1675]
As explained as above
It would be really appreciated if this could be done
Really tired having to manually remove the shortcuts one by one

**Comment by Ahrotahn** [comment]
Those can be removed by launching with `--disable-top-sites`.  There isn't an entry in chrome://flags for that, but I have two separate patches in the works that would solve the problem in different ways that I will make PRs for later.

**Comment by danilokleber** [comment]
Can I achieve this on macOS?

**Comment by networkException** [comment]
You'd have to do something like [creating a script and make it look like an application](https://superuser.com/questions/16750/how-can-i-run-an-application-with-command-line-arguments-in-mac-os). Alternatively you could also use the Custom New Tab Page flag `--custom-ntp` which is also available on chrome://flags/#custom-ntp

**Comment by m-jishnu** [comment]
is there any new update on this

**Comment by aral** [comment]
Just tried with the latest Ungoogled Chromium on macOS and this still seems to be an issue. Cannot find a way to not have the shortcuts created. Any chance we could reopen this?

**Comment by aral** [comment]
For anyone else who might want the default new tab page to be an empty one that nevertheless conforms to the system’s light and dark settings (nothing worse than a flash of white when opening a new tab in dark mode):

1. Make a custom new tab page somewhere (e.g., in _~/.config/ungoogled-chromium/new-tab-page.html_):

    ```html
    <html lang='en'>
      <head>
        <meta charset='utf-8'>
        <title>New tab</title>
        <style>
          body {
            /* Use light/dark background colours from the blue theme. */
            background-color: rgb(249, 249, 255);

            @media (prefers-color-scheme: dark) {
              background-color: rgb(51, 60, 77);
            }
          }
        </style>
      </head>
      <body></body>
    </html>
   ```

2. Go to chrome://flags/#custom-ntp

3. Set the absolute file path to your page as the value of that key. e.g., for me, it’s:

    ```
    file:///Users/aral/.config/ungoogled-chromium/new-tab-page.html
    ```

Restart the browser and you should have a lovely, minimal new tab page.

Enjoy!

**Comment by Ahrotahn** [comment]
We did eventually add flags for some existing switches to chrome://flags last year, so `chrome://flags/#disable-top-sites` is available for anyone that would rather not use a launch switch.  

If you've ever opened the dev tools on a new tab then you'll know that page is rather heavy for what it does, so I find using a custom page to still be the better option.  
Granted, I've added enough things to mine that it's becoming nearly as heavy anyways...
