### ISSUE TITLE
Storing history for more than 90 days

### ISSUE THREAD

**Issue by Bittyby** [Eloston/ungoogled-chromium#1676]
I think many are faced with the problem of storing history for more than 90 days. This is just as important to me.
There is an extension to solve this problem https://chrome.google.com/webstore/detail/history-trends-unlimited/pnmchffiealhkdloeffcdnbgdnedheme, but it says **2) this extension will not preserve the color of links you have already visited**. That important to me.

How can this problem be solved?

**Comment by networkException** [comment]
You are in luck, this is already implemented in ungoogled-chromium as a flag called `--keep-old-history`. I just checked and it showed a link as visited that I last viewed in April.
