### ISSUE TITLE
Support for HLS playback 

### ISSUE THREAD

**Issue by rkfox** [Eloston/ungoogled-chromium#1678]
I cannot get HLS playback working on Fedora 34. I have vlc, ffmpeg, and @Multimedia packages installed. Video playback works fine in Firefox and Brave (and Chromium Freeworld). I am looking at building from source ([suggested here](https://github.com/Eloston/ungoogled-chromium/issues/1446)), but there does not appear to be any option to enable freeworld spec.

**Comment by wchen342** [comment]
Did you encounter any error if you change `%global freeworld 0` to `%global freeworld 1`? Although I didn't test it, the `spec` file is modified from the chromium package of Fedora so freeworld shall build in theory.

The way you enable freeworld is just change the line I mentioned in the `spec` file and use the tar source file from `Source0` in the spec file.

**Comment by rkfox** [comment]
I installed from the Fedora repository. Videos playback fine on Youtube and the hls.js demo that @networkException linked is also working. Twitch playback does not work. It fails with error code 4000. I  thought I might be able to get shared ffmpeg libraries working like in other browsers?

@wchen342 I am not sure as I cannot get ungoogled-chromium or ungoogled-chromium-fedora to build. I can't find any "%global freeworld" lines in the ungoogled-chromium spec files so I am trying to get ungoogled-chromium-fedora to build. However, it can't find a file to patch when building so I'm not sure if it works or not.

**Comment by PF4Public** [comment]
I will close this issue. If at a later time it turns to be ungoogled-chromium issue, feel free to reopen.
