### ISSUE TITLE
javascript 30%-50% slower Chromium vs Chrome

### ISSUE THREAD

**Issue by leeoniya** [Eloston/ungoogled-chromium#168]
Hello,

This is not specific to ungoogled-chromium but does affect it like all other Chromium builds i've tried. For some reason javascript runs 30-50% slower than official Chrome builds of the same version. I find this difficult to understand since everything (including V8) is compiled from 95% the same sources, right? Are there some V8 optimizations or GC aggressiveness flags that are set differently in all Chromium builds?

😕

**Comment by Eloston** [comment]
Have you tried builds from [Woolyss](http://chromium.woolyss.com/)? They customize their build flags beyond what most Chromium projects do, like Whole Program Optimization.

If those builds have comparable performace to that of Chrome, then we could try implementing their changes in our builds.

**Comment by leeoniya** [comment]
Ok, i tried to carefully reproduce the exact thing in all versions using this bench [1]. Turns out this difference is due to x32 (mean settles @1.00ms) vs x64 (mean settles at 1.50ms).

Quite the per hit for x64. Sorry for the noise.

[1] https://rawgit.com/leeoniya/domvm/2.x-dev/demos/bench/dbmonster/index.html

**Comment by Eloston** [comment]
Hm, so there is quite a bit of a performance benefit using x32. Interesting. Thanks for the info.

**Comment by leeoniya** [comment]
i re-tested on my Thinkpad T440S Win10 x64. the x64 overhead is ~8% in all builds. think it depends on what V8's JIT can cobble together for any given CPU's features. i've seen exactly the same code perform differently on different CPUs and platforms using the same V8 version.

**Comment by gcarq** [comment]
It is also possible that some [fieldtrial](https://blog.chromium.org/2012/05/changes-to-field-trials-infrastructure.html) testing code is active in one built but not in the other, which would explain the performance differences.

You can see the active fieldtrial modifications in `chrome://version` as Variations.
More info on this: http://superuser.com/questions/541466/what-is-the-variations-section-in-the-output-of-aboutversion-or-chrome-v

**Comment by Eloston** [comment]
@gcarq I've set `fieldtrial_testing_like_official_build=true`, which I think disables all of the fieldtrial testing.
