### ISSUE TITLE
Add flag to disable tab hover cards

### ISSUE THREAD

**Issue by DarkFlame57** [Eloston/ungoogled-chromium#1683]
Hello! Please reimpliment tab-hover-cards flag that was removed from mainstream chromium, so it's possible to disable this. This is by far the most annoying feature that can't be disabled. Of course this is something that should be done in mainstream chromium, but there is no chance they'll do it.
<img width="350" alt="Tab Hover Cards2" src="https://user-images.githubusercontent.com/49563183/136701256-7d451c8c-6703-4750-a624-b5b7a236023f.png">

**Comment by Ahrotahn** [comment]
I set up a simple patch for a flag that allows removing the tab hover cards or changing them to tooltips.  I'll submit a PR after I get a few other things off my plate.
