### ISSUE TITLE
ld step fails with undefined reference to 'safe_browsing::****'

### ISSUE THREAD

**Issue by squid-f** [Eloston/ungoogled-chromium#1685]
**Describe the bug**
I am trying to package ungoogled-chromium for the Mageia rpm Linux distribution. I am using their spec file of Chromium as a base, same version. I have paid attention to include the ng args provided (otherwise, the build step fails with 'tab_strip_model.cc:1781:62: error: comparison of integer expressions of different signedness'). 
I then succeeded to almost complete the build step, but it fails at the last operation:
```
[49006/49006] LINK ./chrome
FAILED: chrome 
python3 "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome" -- x86_64-mageia-linux-gnu-g++ -Wl,--version-script=../../build/linux/chrome.map -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--disable-new-dtags  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -fno-use-linker-plugin -o "./chrome" -Wl,--start-group @"./chrome.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -lsmime3 -lnss3 -lsoftokn3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -latk-1.0 -latk-bridge-2.0 -lgio-2.0 -lcups -ldrm -lfontconfig -ldbus-1 -lz -ljsoncpp -lresolv -lpng16 -lwebpdemux -lwebpmux -lwebp -lfreetype -ljpeg -lexpat -lxcb -lX11-xcb -lm -lopus -lavcodec -lavformat -lavutil -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lxkbcommon -lgbm -lwayland-client -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lcairo -ludev -lre2 -lXi -lpci -lasound -lsnappy -ldav1d -latspi -lxml2 -lspeechd -lFLAC -lminizip -lgtk-3 -lgdk-3 -lcairo-gobject -lgdk_pixbuf-2.0 -lxshmfence -lxslt -lopenjp2 -lpng -ltiff
/usr/bin/ld: obj/chrome/browser/browser/download_target_determiner.o: in function `DownloadTargetDeterminer::GetLastDownloadBypassTimestamp() const':
download_target_determiner.cc:(.text+0x2030): undefined reference to `safe_browsing::SafeBrowsingMetricsCollectorFactory::GetForProfile(Profile*)'
/usr/bin/ld: obj/chrome/browser/browser/download_target_determiner.o: in function `DownloadTargetDeterminer::CheckVisitedReferrerBeforeDone(bool)':
download_target_determiner.cc:(.text+0x2aae): undefined reference to `safe_browsing::SafeBrowsingMetricsCollectorFactory::GetForProfile(Profile*)'
/usr/bin/ld: download_target_determiner.cc:(.text+0x2afa): undefined reference to `safe_browsing::FileTypePolicies::GetInstance()'
/usr/bin/ld: download_target_determiner.cc:(.text+0x2b15): undefined reference to `safe_browsing::FileTypePolicies::GetFileDangerLevel(base::FilePath const&) const'
/usr/bin/ld: download_target_determiner.cc:(.text+0x2b2a): undefined reference to `safe_browsing::RecordDownloadFileTypeAttributes(safe_browsing::DownloadFileType_DangerLevel, bool, bool, std::optional<base::Time>)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**To Reproduce**
1. Adjustments of Chromium rpm spec file based on build recommendations. 
2. Prune, patch, domain substitution and build GN steps are successfully passed. 
3. Set build options: 
```
LDFLAGS=' -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -fno-use-linker-plugin'
CXXFLAGS='-O2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -faligned-new -Wno-attributes -Wno-ignored-attributes -Wno-error=class-memaccess -Wno-error=unknown-pragmas -Wno-error=array-bounds -Wno-return-type -Wno-error=nonnull -Wno-error=free-nonheap-object -Wno-error=unused -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=maybe-uninitialized -Wno-error=uninitialized -Wno-error=invalid-offsetof -Wno-error=stringop-overflow -std=gnu++17 -fpermissive -w -Wno-error=format-truncation'
CFLAGS='-O2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -w' 
```
4. Fails at the end of 
``
python2 tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles '--gn-gen-args=use_sysroot=false 
                  system_libdir="lib64" 
                  icu_use_data_file=true 
                  enable_nacl=false 
                  is_nacl_glibc=false 
                  linux_use_bundled_binutils=false 
                  custom_toolchain="//build/toolchain/linux/unbundle:default" 
                  host_toolchain="//build/toolchain/linux/unbundle:default" 
                  proprietary_codecs=true 
                  linux_link_libudev = true 
                  linux_link_libspeechd = true 
                  linux_link_libbrlapi = true 
                  linux_link_xlib = true 
                  enable_platform_ac3_eac3_audio = true 
                  enable_mse_mpeg2ts_stream_parser=true 
                  enable_platform_hevc=true 
                  use_system_libjpeg=true 
                  use_system_libopenjpeg2=true 
                  use_libjpeg_turbo=false 
                  enable_widevine=true 
                  pdf_enable_xfa=true 
                  gtk_version=3 
                  fatal_linker_warnings=false 
                  use_libpci = true 
                  use_pulseaudio=true 
                  use_allocator="none" 
                  is_debug=false 
                  is_clang=false 
                  clang_use_chrome_plugins=false 
                  use_lld=false 
                  use_gold=false 
                  use_system_freetype=true 
                  use_system_harfbuzz=false 
                  use_system_libpng=true 
                  enable_dav1d_decoder=true enable_libaom=false 
                  use_custom_libcxx=false 
                  enable_mojom_closure_compile=false 
                  enable_js_type_check=false 
                  dcheck_always_on=false 
                  google_api_key="" 
                  build_with_tflite_lib=false 
                  chrome_pgo_phase=0 
                  clang_use_chrome_plugins=false 
                  disable_fieldtrial_testing_config=true 
                  enable_hangout_services_extension=false 
                  enable_js_type_check=false 
                  enable_mdns=false 
                  enable_mse_mpeg2ts_stream_parser=true 
                  enable_nacl=false 
                  enable_nacl_nonsfi=false 
                  enable_one_click_signin=false 
                  enable_reading_list=false 
                  enable_remoting=false 
                  enable_reporting=false 
                  enable_service_discovery=false 
                  enable_widevine=true 
                  exclude_unwind_tables=true 
                  google_default_client_id="" 
                  google_default_client_secret="" 
                  safe_browsing_mode=0 
                  treat_warnings_as_errors=false 
                  use_official_google_api_keys=false 
                  use_unofficial_version_number=false' 
``

**Expected behavior**
Complete the build and the package

**Environment (please complete the following information):**
 - OS/Platform and version: Magiea 8 x86_64
 - ungoogled-chromium version: 94.0.4606.61

Would you need more info, just let me know.

Thanks.

**Comment by PF4Public** [comment]
I've received the same bug report: PF4Public/gentoo-overlay#106
It is clear an issue if building with gcc.

@Ahrotahn @git-bruh What is causing this? Are ungoogled patches causing this? Could we solve it somehow?
