### ISSUE TITLE
Updating to Chromium [94.0.4606.85]

### ISSUE THREAD

**Issue by handokota** [Eloston/ungoogled-chromium#1688]
## Notes for the developer

Once you claim it, it is advisable that you create a [Draft Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) for increased visibility:

![GitHub Interface for creating Draft Pull Requests](https://help.github.com/assets/images/help/pull_requests/pullrequest-send.png)

Finally, make sure to reference this issue in your PR.

Feel free to ask questions and discuss issues here along the way. Thanks!

## Notes for others

Feel free to raise issues or questions throughout the process. However, please refrain from asking ETAs unless no visible progress has been made here or on the developer's PR for a while (e.g. 2 weeks).

**Comment by PF4Public** [comment]
94.0.4606.85 Is released only for Android. @Ahrotahn @Zoraver @wchen342 @Eloston Do we bump ungoogled-chromium in such a case?

**Comment by PF4Public** [comment]
@wchen342 @Ahrotahn Thanks for your inputs!

In the light of oncoming 95, I suggest not to take any action then.
