### ISSUE TITLE
Some privacy-focused addons

### ISSUE THREAD

**Issue by nyancat18** [Eloston/ungoogled-chromium#169]
you could add scriptsafe as an autoinstalled addon (like google makes with their adware), or put it at readme.md

we should clone their sourcecode and compile as addon

protects against:
referer watching
canvas
webgl
webaudio
webvr
spoof referer

https://github.com/andryou/scriptsafe
Or download from http://uploadboy.me/ad4ud8c8i6w5/scriptsafe.zip.html it has the best settings for inox

My ua spoofer addon
https://github.com/triceratops1/ua-change

http://uploadboy.me/eq1td092wqwv/0.1.6_0.crx.html

**Comment by Eloston** [comment]
If there is no benefit of building it into the source code, then it should be just linked from the FAQ.

**Comment by triceratops1** [comment]
@eloston you could add
the first uploadboy link has the ScriptSafe crx + the best setting for it

the second its my addon

**Comment by triceratops1** [comment]
Scriptsafe has an official build


https://github.com/andryou/scriptsafe/releases/download/v1.0.9.0_beta/ScriptSafe_v1.0.9.0_BETA.zip

**Comment by robotme** [comment]
How do I install extentions in ungoogled chromium (mac os 12.2.2)?

**Comment by triceratops1** [comment]
@robotme  
please check https://github.com/SethDusek/extension-downloader/blob/master/downloader.py

replace inox with your ungoogled path (afik, that works at linux)

**Comment by Eloston** [comment]
@robotme You can follow the instructions for installing extensions from the Chrome Webstore in the FAQ.

**Comment by macandchief** [comment]
Besides blocking scripts and spoofing user agent I'd like to add two add-ons that are important for Ungoogled Chromium v62 (as it has WebRTC now and on default WebGL is enabled):
- WebRTC Protect
- Disable WebGL
uBlock Origin has a Prevent WebRTC... setting too. To install an extension protecting from canvas fingerprinting is also a good idea.

**Comment by Eloston** [comment]
This issue is stale. If someone wants to submit a PR to include this in the FAQ, feel free to do so.
