### ISSUE TITLE
Bookmarks and extensions are broken

### ISSUE THREAD

**Issue by tnaftali** [Eloston/ungoogled-chromium#1694]
**Describe the bug**
When I open `chrome://bookmarks` and `chrome://extensions` I can't see anything despite having both many bookmarks and extensions.

**To Reproduce**
1. Go to `chrome://bookmarks` or `chrome://extensions`

**Screenshots**
![image](https://user-images.githubusercontent.com/8753873/137190389-2d1ce031-42f3-4eca-8d76-8f26050624db.png)

![image](https://user-images.githubusercontent.com/8753873/137190412-03b5c065-9d63-4ae6-a5c0-a1d26e9ed52e.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Debian 11 Bullseye
 - ungoogled-chromium version: Version 93.0.4577.82 (Developer Build, ungoogled-chromium) built on Debian bullseye/11, running on Debian bullseye/11 (64-bit)

Issue also reported on ungoogled-chromium-debian: https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/245

**Comment by markozajc** [comment]
This is a problem with Debian's upstream: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994888

**Comment by networkException** [comment]
Closing in favor of https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/245
