### ISSUE TITLE
Fonts are jagged.

### ISSUE THREAD

**Issue by JUserLittleEnglish** [Eloston/ungoogled-chromium#170]
Hi, I'm japanese. My english is very little.
I understand only short sentences. sorry.

On my ungoogled-chromium_55.0.2883.87-1_windows_x64 fonts are jagged.

![b](https://cloud.githubusercontent.com/assets/25126092/21958818/122277e6-dafa-11e6-8de4-f72ccea87286.jpg)

Font customization is ignored.
I want to change and designation to another font.

Do you have plans to add "font specification function" ?

or,

Is there a way to install "Advanced Font Settings" or "Change Font Family Style" ?

Advanced Font Settings
https://chrome.google.com/webstore/detail/advanced-font-settings/caclkomlalccbpcdllchkeecicepbmbm
Change Font Family Style
https://chrome.google.com/webstore/detail/change-font-family-style/aabledekpjmoghdjnpnhfkfpmjifklpb

**Comment by Eloston** [comment]
I don't know how font customization works. Does it work on Chrome?

You can install extensions from the Chrome Web Store if you [follow these instructions](https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#can-i-install-extensions-from-the-chrome-webstore).

**Comment by JUserLittleEnglish** [comment]
I installed "Change Font Family Style"!
I changed the font and it became very easy to see.

![aaa](https://cloud.githubusercontent.com/assets/25126092/21960743/12397dd6-db38-11e6-9c16-098d872aba9c.jpg)

Thank you very much!
