### ISSUE TITLE
with latest update any enabled ad blocker extension causes any url/page to fail to load.

### ISSUE THREAD

**Issue by dkebler** [Eloston/ungoogled-chromium#1703]
**Describe the bug**
INstall of latest ubuntu build Version 94.0.4606.81 (Official Build, ungoogled-chromium) Ubuntu (64-bit) has bug where any ad blocking software does not run correctly and hangs loading of ALL pages

**To Reproduce**
update to latest release.  Version 94.0.4606.81 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

**Expected behavior**
extensions (ad blockers) should work and not caues pages to fail to load.

**Environment (please complete the following information):**
 - OS/Platform and version:  ubuntu focal
 - ungoogled-chromium version:  Version 94.0.4606.81 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

**Additional context**

I am going to attempt to downgrade and see if issue resolves

**Comment by networkException** [comment]
Duplicate of #1698

**Comment by dkebler** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/249

yup can't regress  foobared for the moment.
