### ISSUE TITLE
Not properly maximizing window

### ISSUE THREAD

**Issue by Fallast** [Eloston/ungoogled-chromium#1710]
this is what the window should look like maximized Not using the system title bar and borders option.
![image](https://user-images.githubusercontent.com/61057195/138890486-de1fbaf8-6aea-487b-a44c-b13b92b5bc5a.png)
now this is what happens when move the window around and maximize it back again:
![image](https://user-images.githubusercontent.com/61057195/138890599-07fe84c2-c940-46f2-8e6a-de9a1323f086.png)

this wasn't happening in the previous version, i'm on debian bullseye

**Comment by Fallast** [comment]
this isn't happening on chromium for but it does for ungoogled chromium

**Comment by PF4Public** [comment]
Which version of ungoogled-chromium are you referring to? This issue was fixed several minor versions ago.
