### ISSUE TITLE
How do I keep this browser up to date?

### ISSUE THREAD

**Issue by alekrudolph** [Eloston/ungoogled-chromium#1711]
It's amazing how much ~googling~ duckduckgoing I did and still not being able to find a clear answer about how I am expected to keep this browser up to date. There is a question [here](https://github.com/Eloston/ungoogled-chromium/discussions/1511) asked by another person all the way back in **may** that is still unanswered. I simply cannot use a browser that does not update, for obvious security reasons. Therefore I am opening an issue because it seems like discussions do not get looked at.

Am I supposed to update by:

1. Checking the releases page periodically, and manually re-installing? (Full manual)
2. Waiting for the browser to notify me that there is an update, and restarting (Full automatic)
3. Waiting for the browser to notify me that there is an update, and downloading the new release from the releases page (Semi automatic)

I appreciate an answer soonish (less than a month) because I consider letting users know how to keep their browsers secure to be 100% necessary, full stop.

**Comment by tomasz1986** [comment]
> Yeah I can surely submit the binaries to ungoogled-software/ungoogled-chromium-binaries, but is it necessary since we can get the binaries from [macchrome/winchrome/releases](https://github.com/macchrome/winchrome/releases)?

I'd also add that binaries from that link are usually only 64-bit (x64). They do include 32-bit (x86) sometimes, but not regularly.

On the other hand, the binaries listed at https://ungoogled-software.github.io/ungoogled-chromium-binaries were always available for both x86, x64, and also even ARM64.

**Comment by PF4Public** [comment]
Closing this issue in favour of #174
