### ISSUE TITLE
[Feature request] Add a flag allowing to hide tab close buttons

### ISSUE THREAD

**Issue by tomasz1986** [Eloston/ungoogled-chromium#1712]
**Is your feature request related to a problem? Please describe.**

I use the browser on an 8" touch screen tablet. Since the screen size is rather small, opening just a dozen tabs makes each of them very narrow. If you press them with your fingers, it is very easy to mistap, resulting in accidentaly closing either the current tab or any of its adjacent ones.

**Describe the solution you'd like**

I think it would be nice to have a possibility to hide the close buttons. Closing tabs will still be possible with other methods, such as right click -> close, middle click, or using the keyboard shortcut. With the close buttons hidden, there will be no risk of mistapping them on a touch screen.

**Describe alternatives you've considered**

The alternative is to use the tab search button and switch tabs from there. Another alternative is to use a completely different browser like Firefox that supports custom CSS, which can be used to hide or remove tab close buttons completely.

**Additional context**

This is how the browser looks like on a 1280x800 resolution screen with DPI bumped up to 150% in Windows. As you can see, the tabs are very narrow and difficult to operate with a finger, especially with the big close button sitting right in the middle of them.

![image](https://user-images.githubusercontent.com/5626656/139244998-73310db2-51d4-46f3-9cba-683b63d17f4e.png)

**Comment by Ahrotahn** [comment]
I'll include a patch for this in a PR along with another related one after the refresh.  It's a simple change and would also help on small linux devices that use the desktop build like the pinephone.

**Comment by tomasz1986** [comment]
Thanks a lot for showing interest in this.

I think the main problem with this right now is that right after closing a tab (on purpose), there is a small delay after which the other tabs reposition. If you try to tap on a different tab while this happens, you're basically bound to mistap resulting in closing another tab.

This doesn't happen with a mouse, because the browser waits until you stop hovering over the tab panel before doing any reposition, while on a touch screen, there is no hover, hence the repositioning takes place immediately.
