### ISSUE TITLE
How to add username:password to flag --proxy-server ???

### ISSUE THREAD

**Issue by nttrung9x** [Eloston/ungoogled-chromium#1713]
Hello friends !

I want to add the username:password confirmation code to the flag ---proxy-server with the form ip:port:username:password, which file should I learn the code in?

Thank you very much !

**Comment by jacob755** [comment]
read this https://superuser.com/questions/902620/google-chrome-proxy-settings-with-username-and-password
or make your issue as request feature

**Comment by nttrung9x** [comment]
> read this https://superuser.com/questions/902620/google-chrome-proxy-settings-with-username-and-password or make your issue as request feature

Thank you, if I used an extension to solve it, I would have done it a long time ago !
