### ISSUE TITLE
chromium-flags.conf is ignored

### ISSUE THREAD

**Issue by h4ckee** [Eloston/ungoogled-chromium#1717]
When ungoogled-chromium is being started it desn't read file ~/.config/chromium-flags.conf
Linux 64bit
Version 95.0.4638.54

**Comment by mortezadadgar** [comment]
so there's no way to makes chromium-flags works outside archlinux? I'm not going to add my long lists of flags to desktop entry...

**Comment by mdedonno1337** [comment]
this is not a chromium feature, hence not supported.
I think editing the `.desktop` file is not unreasonable.

**Comment by mortezadadgar** [comment]
Ok by reading chromium-browser which is a script that start chromium, this can be done this way as well without modifying or adding a new desktop entry
export CHROMIUM_USER_FLAGS=$(< $HOME/.config/chromium-flags.conf)

**Comment by adduc** [comment]
For those who stumble on this issue in the future, this is the solution I used:

```sh
cat ~/.config/chromium/chromium-flags.conf | grep '^\(#.*\)\?$' -v | xargs chromium
```

It takes a flags file, prunes comments and empty lines, and passes the arguments to chromium.

**Comment by KataFF** [comment]
I know this is closed, but:
a) This is not a forum, so it's not like necroposting
b) This may benefit people searching for the issue online in the future

I found some relevant websites in the upstream chromium project:
https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_paths_linux.cc;l=63?q=CHROME_CONFIG_HOME&ss=chromium
https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md#Linux

Quoting:
```
// This returns <config-home>/<product>, where
//   <config-home> is:
//     $CHROME_CONFIG_HOME if set
//     otherwise $XDG_CONFIG_HOME if set
//     otherwise ~/.config
//   and <product> is:
//     "chromium" for Chromium
//     "google-chrome" for stable channel official build
//     "google-chrome-beta" for beta channel official build
//     "google-chrome-unstable" for dev channel official build
//
// (Note that ChromeMainDelegate will override the value returned by this
// function if $CHROME_USER_DATA_DIR or --user-data-dir is set.)
//
// See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
// for a spec on where config files go.  Using ~/.config also helps us sidestep
// issues with other apps grabbing ~/.chromium .
```
