### ISSUE TITLE
How can I automate configuration?

### ISSUE THREAD

**Issue by metov** [Eloston/ungoogled-chromium#1719]
I often need to install ungoogled-chromium on new machines, and configuring it every time through `chrome://settings/` is tedious. I'm guessing that simply adding the profile directory to my dotfiles repo won't work well (or will it?).

Is there a way to somehow automatically apply configurations that are available at `chrome://settings/`, eg. with a shell script? Is there a way to dump these settings from the browser?

**Comment by tomasz1986** [comment]
> I'm guessing that simply adding the profile directory to my dotfiles repo won't work well (or will it?).

Why wouldn't it work well? :wink:

You need the following from the userdata folder if you want to preserve the whole configuration (with extensions, etc.).

```
Default/Bookmarks
Default/Extensions
Default/IndexedDB/chrome-extension_*
Default/Local Extension Settings
Default/Local Storage
Default/Managed Extension Settings
Default/Preferences
Default/Secure Preferences
Default/Sessions
Default/Sync Extension Settings
Local State
```

This is for the default profile. If you have others, they will be called `Profile 1`, `Profile 2`, etc. instead of `Default`.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
