### ISSUE TITLE
Is XP unsupported?

### ISSUE THREAD

**Issue by antontriola** [Eloston/ungoogled-chromium#172]
Attempting to run from Win XP-sp3 using:
ungoogled-chromium_55.0.2883.87-1_windowsx86.zip

Results in the following when clicking on "chrome.exe":
"The procedure entry point Release SWRLock Exclusive could not be located in the dynamic link library KERNEL32.dll"

Is XP unsupported?

**Comment by Eloston** [comment]
Duplicate of #75.
