### ISSUE TITLE
Rollback to release 90

### ISSUE THREAD

**Issue by macbeto** [Eloston/ungoogled-chromium#1722]
Hi,
Is there a way to install back release 90 in Linux Mint?
After release 95 my uBlock Origin plugin stopped working, I uninstalled ungoogled-chromium waiting for a solution to this.
But in the meantime I would like to install release 90 again, but I don't know how to do it. 
I have installed release 90 in another Linux Mint, so if it is just a matter to move the files/folder from one computer to another is not a problem, but I don't know if it is just enough.
Besides I don't feel confortable compiling the release 90 tar files, I don't find a documentation right enough showing how to do it.
Thank you.

**Comment by PF4Public** [comment]
> After release 95 my uBlock Origin plugin stopped working

This doesn't answer your original question, but as a temporary workaround you may try my [Gentoo binaries](https://github.com/PF4Public/ungoogled-chromium-bin/releases) until the Debian binaries are fixed.

**Comment by macbeto** [comment]
Thanks for the reply PF4Public.
The binaries of your link are only release 95, not 90.
Nevertheless in the releases section exits a source code for the release 90.0.4430.212-1. 
I would like to install it. Is there a documentation (step-by-step will be great) to install it?
Everything I found is not very clear at this point.
Regards

**Comment by PF4Public** [comment]
> The binaries of your link are only release 95

I should probbaly made it clear from the beginning, that I experience no issues with uBlock on my binaries, that's why I suggested them.

**Comment by macbeto** [comment]
Thank you PF4Public. I will give it a try.
