### ISSUE TITLE
Can't play videos from google drive generated from meet 

### ISSUE THREAD

**Issue by Danielgb23** [Eloston/ungoogled-chromium#1729]
**Describe the bug**
I have (college) classes to watch hosted on google drive generated through google meet that won't play. They get stuck on time 0:00 with that spinning circle.

**Screenshots**
![image](https://user-images.githubusercontent.com/33136385/140627838-f4345b5d-2831-4193-b47f-c5be70e0f9f0.png)

**Environment (please complete the following information):**
 - OS/Platform and version:
 - 5.14.16-arch1-1
 - ungoogled-chromium version:
Version         : 95.0.4638.54-1

**Comment by theocassar** [comment]
Open the eye at the top left and disable cross-site cookie blocking.

![140627838-f4345b5d-2831-4193-b47f-c5be70e0f9f0](https://user-images.githubusercontent.com/59197790/140795079-d42c9e85-170f-4e43-94c4-c7927c169398.png)

**Comment by Danielgb23** [comment]
It worked. Thanks!
