### ISSUE TITLE
question: how I can build for Ubuntu

### ISSUE THREAD

**Issue by Kwaskoff** [Eloston/ungoogled-chromium#1730]
I find your build https://github.com/Eloston/ungoogled-chromium-binaries/releases/tag/95.0.4638.69-1.unportable1
But can't understand where is source code of this one.
Help me, please. I want to build like yours but with flag -march=tigerlake  - for my processor
Thx!

**Comment by networkException** [comment]
It links the commit that got built (ungoogled-software/ungoogled-chromium-debian@94a098d) in the release notes

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
