### ISSUE TITLE
Last clang-llvm updates  gives build errors  

### ISSUE THREAD

**Issue by a51kt** [Eloston/ungoogled-chromium#1734]
error

 ERROR at //build/config/freetype/BUILD.gn:8:1: Dependency not allowed.
[  300s] group("freetype") {
[  300s] ^------------------
[  300s] The item //build/config/freetype:freetype
[  300s] can not depend on //build/linux:freetype_from_pkgconfig
[  300s] because it is not in //build/linux:freetype_from_pkgconfig's visibility list: [
[  300s]   //third_party:freetype_harfbuzz
[  300s]   //third_party/harfbuzz-ng:harfbuzz_source
[  300s] ]

build setup https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium-arch

os  arch

**Comment by a51kt** [comment]
@Ahrotahn @PF4Public

**Comment by PF4Public** [comment]
I've also got similar report: PF4Public/gentoo-overlay#109. I'm hoping to have some time this week to look into it.

**Comment by networkException** [comment]
See https://github.com/archlinux/svntogit-packages/blob/6eb891b3597aa9a6a22a96eac3c7e1b3c001869e/repos/extra-x86_64/unbundle-fix-visibility-of-build-config-freetype.patch

**Comment by PF4Public** [comment]
Yeah, exactly the one I found in Gentoo: https://gitweb.gentoo.org/repo/gentoo.git/plain/www-client/chromium/files/chromium-96-freetype-unbundle.patch
