### ISSUE TITLE
How can I make this version run on USB Drive?

### ISSUE THREAD

**Issue by rock2rap** [Eloston/ungoogled-chromium#1738]
First. I've download portable version and install directly to USB Drive
2. now I'm running Ungoogled Chromium direct on USB Drive, All data/Cache/Extention/History it's saving on usb drive normally, and I've running again on same PC same Drive. All saving data load proprably
3. I've eject my usbdrive and put it on another PC (my laptop), All data (Loging on website/Cache/Cookies/Ectentions) it's not loaded, except History
How can I using as Portable Version?

**Comment by jacob755** [comment]
have you tested this flags Disable encryption
,Disable machine ID
