### ISSUE TITLE
Laggy browser on Wayland

### ISSUE THREAD

**Issue by Motor-head** [Eloston/ungoogled-chromium#1740]
Steps to reproduce:
1. Use Wayland on GNOME.
2. Install Ungoogled-Chromium 96.0.4664.45.
3. Flag `--use-gl=egl` is mandatory to get Hardware accelerated video decoding.
4. Open some other website on other tab.
5. Expectations: Everything must work smoothly.
6. Result: Video lags and stutters. Other tabs also suffer lags. Frames are dropped in the video playback.
I'm using Intel i5-8250U with integrated graphics, tried on Ubuntu 21.10 and Fedora 35. Terminal shows error:
`ERROR: sync_control_vsync_provider.cc(139) Calculated bogus refresh intervals=0.499152 s, last_timebase=5244286241 bogo-microseconds, timebase=5244785393 bogo-microseconds, last_media-stream_counter_=33, media_stream_counter=34`

**Comment by PF4Public** [comment]
This is unlikely to be ungoogled-chromium issue.

PS: Sorry @Zoraver miss-clicked.

**Comment by networkException** [comment]
Please check if the issue is reproducible using vanilla chromium and the same configuration

**Comment by Motor-head** [comment]
I can't find any install-able vanilla chromium on Ubuntu, and none of the portables are able to use hardware acceleration. I did install snap version of Chromium, that made the system freeze so bad, I had to force shutdown the system.

**Comment by wchen342** [comment]
Ubuntu [removed the chromium package and turned that to the snap version](https://packages.ubuntu.com/search?keywords=chromium). Fedora 35 has `chromium` package but that one was on v94 still.
By `portable` did you try [this](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/929513/)?

**Comment by Motor-head** [comment]
> Ubuntu [removed the chromium package and turned that to the snap version](https://packages.ubuntu.com/search?keywords=chromium). Fedora 35 has `chromium` package but that one was on v94 still. By `portable` did you try [this](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/929513/)?

Yes. I downloaded the `chrome-linux.zip`, unzipped it, ran `./chrome --enable-features=VaapiVideoDecoder` from terminal, enabled all the flags but `Video Acceleration Information` section is empty even on X11, where I can successfully run flatpak ungoogled-chromium with hardware acceleration, let alone running on Wayland.
![Screenshot from 2021-11-23 22-58-00](https://user-images.githubusercontent.com/93347209/143074658-cac59213-b6c7-4d33-808a-732b14a9fa91.png)
 Here's the screenshot of flatpak ungoogled chromium on X11 listing decoding capabilities:
![Screenshot from 2021-11-23 23-02-24](https://user-images.githubusercontent.com/93347209/143075092-d0e50cee-70ea-4e17-af88-6962025460f3.png)

**Comment by wchen342** [comment]
GPU problems are quite tricky and it has always been kind of buggy on Linux..

vaapi on Intel needs a patch, I suspect the snapshot version from Google doesn't have that. If you have Fedora, can you try [this](https://download.opensuse.org/repositories/home:/ungoogled_chromium/Fedora_35/x86_64/ungoogled-chromium-96.0.4664.45-1.1.x86_64.rpm) and post `chrome://gpu`? Additional flags can be added to `~/.config/chromium-flags.conf` for that version, see [Arch wiki](https://wiki.archlinux.org/title/chromium#Making_flags_persistent).

I am not very sure about the flatpak version, @rany2 may have more insights.

Generally speaking v96 seems to have some strange problems with graphics. I recently ran into a Vulkan+optimus problem and the GPU process kept crashing when using nvidia GPU, and your post solved my problem actually (`--use-gl=egl` solved my problem). I suspect there are other graphics bugs and this may related to one of them.

**Comment by Motor-head** [comment]
I somehow managed to mess up Fedora by trying to change `libc` and `glibstdc++6` a few days ago and thus reverted back to Ubuntu 20.04 (that's the reason I was late to follow up on this thread). So, now I can only run deb packages.

**Comment by Motor-head** [comment]
Installed Fedora 35 on Intel 8250U laptop, installed `libva-intel-driver`, `intel-media-driver.x86_64`, `libva-intel-hybrid-driver`, and ran a FHD video on Ungoogled Chromium version 96.0.4664.110. Opened another tab, and video started to drop frames. Hardware acceleration is working, but video is choppy.

**Comment by Motor-head** [comment]
The vanilla chromium in Fedora RPM repo is v94.0.4606.81. Where can I find the v95?

**Comment by wchen342** [comment]
They haven't been updating the package for a while. You can try `chromium-freeworld` from RPMFusion instead.

**Comment by wchen342** [comment]
Btw I can observe frame drop on 1080p60 under Wayland even without switching tab. I think it is an ANGLE problem but cannot confirm.

**Comment by Motor-head** [comment]
Installed `chromium-freeworld` v96.0.4664.93, enabled flags: `ignore-gpu-blocklist, enable-gpu-rasterization, enable-zero-copy, canvas-oop-rasterization, enable-features=VaapiVideodecoder`. Browser is smooth, but video is software decoded. on using `use-gl=egl`, the browser itself, videos included, is lagging, but video is hardware decoded.

**Comment by wchen342** [comment]
Then it is most likely an upstream problem. I don't think there is anything we can do to fix the problem here. The only suggestion I can give is using X11 instead.

**Comment by Motor-head** [comment]
I'm wondering when most of the people are using Wayland, then why has this problem not faced by anyone thus far?

**Comment by PF4Public** [comment]
> most of the people are using Wayland

Questionable statement

**Comment by wchen342** [comment]
I won't be so sure about "most of the people are using Wayland" and "not faced by anyone". Only a small portion of users will ever report a bug. Also it is probably dependent on video card vendor or DE:
- I am on KDE and its wayland support is not very mature, but Gnome probably have better support.
- The problem can be specific to Intel/Mesa, and I suspect this is the most likely cause. I cannot test nVIDIA here because Optimus switching doesn't work under Wayland.
- It can also be dependent on system OpenGL/kernel, but since you said Ubuntu also has this problem I think that possibility is small.

**Comment by Motor-head** [comment]
This is still an issue on Wayland. Even after setting following flags:

`--enable-features=VaapiVideoDecoder
--disable-features=UseChromeOSDirectVideoDecoder
--disable-gpu-memory-buffer-compositor-resources
--disable-gpu-memory-buffer-video-frames
--enable-hardware-overlays
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--canvas-oop-rasterization
--ozone-platform=wayland`

The Hardware acceleration doesn't seem to be working (v. 103.0.5060.53 Flatpak).

Running on Ubuntu 22.04, AMDGPU

**Comment by alejandro097** [comment]
> 

because chromium doesn't natively run under wayland by default, you have to force it, and when you do, browser becomes slow af, laggy and choppy.

**Comment by alejandro097** [comment]
> I'm wondering when most of the people are using Wayland, then why has this problem not faced by anyone thus far?

Because chromium doesn't natively run under wayland by default, you have to force it **(-ozone-platform=wayland --use-gl=egl --enable-features=VaapiVideoDecoder)**, and when you do, browser becomes slow af, laggy and choppy.

**Comment by qdrop17** [comment]
Chromium with Wayland and accelerated decoding was not able for a longer time, but maybe this helps: https://fostips.com/chromium-ubuntu-hardware-acceleration/

When will this be available as a Flatpak to test?
