### ISSUE TITLE
Please add search engine support for Google

### ISSUE THREAD

**Issue by Raj2032** [Eloston/ungoogled-chromium#1741]
I know Google is hated for a reason and I understand why this project is called _ungoogled_-chromium. But sometimes Google is needed for searching and I would like to have this as my defaut search engine at times.

I was wondering if it could be added into the browser?

**Comment by PF4Public** [comment]
Absolutely! You probably need to enable the collection of search engines or manually add google search.

**Comment by networkException** [comment]
Duplicate of https://github.com/Eloston/ungoogled-chromium/discussions/1488#discussioncomment-619116

**Comment by Raj2032** [comment]
Thanks guys :)
