### ISSUE TITLE
New tab webpage configuration option and left-right bookmarks menu button option

### ISSUE THREAD

**Issue by avidichard** [Eloston/ungoogled-chromium#1742]
I'm not asking for much. Just adding the possibility of choosing which web page to display when opening a new tab page

AND

The possibility to change the position of the bookmarks menu button which I always put on the far left before the back and forward buttons. That would just be a perfect web browser. NON-Google, open source and 2 annoyances cleared and taken car of! These will not change anything from the engine but just add the possibility of not using useless extensions for such small needs. And I am sure that everyone will love to have these slight options.

Oh, and having the option of removing that user profile button in the button bar.

**Comment by networkException** [comment]
I would recommend to look at docs/flags.md, I'm not sure about the bookmark bar things you talked about but new pages can be set using --custom-ntp and the avatar can be disabled using --show-avatar-button

**Comment by avidichard** [comment]
Basically, the only way to have a kind of bookmarks menu is to enable the bookmarks bar. It would be nice to have a bookmarks button that we can choose where to display in the toolbar.

**Comment by Ahrotahn** [comment]
Lazy link for the flags @networkException mentioned:  [docs/flags.md](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md)

I have a patch that adds the bookmarkbar into the toolbar to the right of the locationbar (which could be edited to be added the left), but that's not something that would make it into the core repo.  I'll submit it to [the contrib repo](https://github.com/ungoogled-software/contrib) later this weekend once I get some time.  I've been meaning to update my PR there anyways.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
