### ISSUE TITLE
Is there a binary version available in the AUR?

### ISSUE THREAD

**Issue by Raj2032** [Eloston/ungoogled-chromium#1743]
It kinda takes forever to build a browser in my PC and I was wondering if there was a binary version available in the AUR?

If so what would be the package name?

**Comment by networkException** [comment]
See https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/143, the code is technically there but I still require feedback from Eloston on some internal things before that can get pushed

**Comment by Raj2032** [comment]
I hope to see it soon then mate =D
