### ISSUE TITLE
Left over Google junk in ungoogled-chromium

### ISSUE THREAD

**Issue by avidichard** [Eloston/ungoogled-chromium#1744]
User icon automatically get's my Google Connection as soon as I connect on my google account on a webpage. I expect this user profile to NEVER use my Google account.

Also, when asking to save passwords, offers the possibility to save in my unwanted connected Google Account. If I remove my user account from the chromium settings, I get disconnected from all Google web pages. VERY inconvenient and does not fall un the "ungoogled" term completely for me.

Passwords should automatically be saved locally and NOT using my google account which I never asked to connect.

**Comment by wchen342** [comment]
Doesn't happen on my machine. What OS are you on? How did you install ungoogled-chromium (binary, package manager, flatpak)?

**Comment by avidichard** [comment]
Binary Windows downloaded 64 bit version here: [https://ungoogled-software.github.io/ungoogled-chromium-binaries/](url)

. Installed on Windows 11 Enterprise.

**Comment by wchen342** [comment]
@Nifury Do you have Win 11 to test? I only have Windows 10.

**Comment by Ahrotahn** [comment]
Yeah, this doesn't happen for me either.  Does that also happen on a new profile?

**Comment by Nifury** [comment]
@wchen342 No, I only have Windows 10 as well. 

Yeah, I think running Chromium with a clean profile is a good idea.

**Comment by wchen342** [comment]
This is likely something Google did changed the way sign-in is handled, probably related to profile migration. Brave is [having users reporting](https://www.reddit.com/r/brave_browser/comments/r1a7zj) something [very similar](https://community.brave.com/t/google-accounts-signs-out-of-brave-pc-after-closing-the-browser/301793/22).
