### ISSUE TITLE
Ungoogled Chromium connected to someonewhocares.org

### ISSUE THREAD

**Issue by TontyTon** [Eloston/ungoogled-chromium#1746]
Ungoogled Chromium connected to someonewhocares.org, after I left the browser started without opening anything. I never visited that website.
Search results told me that it publishes malware domains list. Is this list added by ungoogled chromium patches or is part of chromium base? or should I be suspicious?

**Comment by PF4Public** [comment]
Do you have extensions?

**Comment by Ahrotahn** [comment]
That domain doesn't exist in the patches if you give them a search.  
If you're using an adblock extension like uBlock Origin then you probably have Dan Pollock’s hosts file checked in the filter lists.

**Comment by TontyTon** [comment]
As far as I remember I was using profile without extensions, but now I don't remember if other profile was open on other desktop (Windows 10) or not.
Sorry for reporting without considering this.
