### ISSUE TITLE
Cross compare functionalities with `iridium-browser`

### ISSUE THREAD

**Issue by lenormf** [Eloston/ungoogled-chromium#175]
Hi,

What are the things that could be ported over to this project from [the iridium browser](https://github.com/iridium-browser/tracker/wiki/Differences-between-Iridium-and-Chromium), if any?

**Comment by Eloston** [comment]
I've ported over pretty much everthing except the redundant patches (that were already in other patchsets) and those that redirected traffic to Iridium servers. I did mention in the README that I used Iridium patches, but I was not very clear as to what I included.

Does this answer your question?

**Comment by lenormf** [comment]
Nothing in particular, this browser has gotten some exposure recently, I wanted to make sure we're not missing anything. If that's the case, then I'm closing this.
