### ISSUE TITLE
Fake vga name for webgl ?

### ISSUE THREAD

**Issue by nttrung9x** [Eloston/ungoogled-chromium#1751]
Hello!
Please guide me!
Current default chromium returns null => return WebGLAny(script_state,String(""));
Now I want it to return the name of a certain vga and I put the vga name in the json of the Preferences file, what should I do?
[ profiledir/Default/Preferences ]

Thank you!

**Comment by networkException** [comment]
How does this relate to ungoogled-chromium exactly?

**Comment by nttrung9x** [comment]
> 

I just want to fake more parameters for more profiles.

**Comment by networkException** [comment]
Does this yield any benefit for other users? Currently my understanding is that you want a custom feature in chromium that does not relate to the objectives of this project.

**Comment by PF4Public** [comment]
Same as #1713

**Comment by nttrung9x** [comment]
The goal of the project is to remove google and hide fingerprints right?
The purpose of fake vga and proxy is also within this goal
And I see that many of you also mentioned fingerprint?
