### ISSUE TITLE
On launch always tries to navigate to http://u/

### ISSUE THREAD

**Issue by jixbo** [Eloston/ungoogled-chromium#1752]
On launch, ungoogled-chromium always tries to navigate to "http://u/". If my start-up option is "Open new tab" or "Open a specific page or set of pages", I get just one tab, even when having several pages set, with "http://u/" and the "The site can't be reached" message. When I choose to start-up with "Continue where you left off"  I get the tabs I expect, plus a new tab with "http://u/".

Everything else works as expected after launch.

My system:
Ubuntu 21.10 and wayland, ungoogled-chromium version 96.0.4664.45 from the ubuntu store (flatpack)

Thanks!

**Comment by networkException** [comment]
Please check if the `custom-ntp` flag is set in `chrome://flags`, I can't reproduce this after installing the flatpak

**Comment by jixbo** [comment]
Thank you.

I's disabled.

**Comment by jixbo** [comment]
I tried changing the flags, and it asked to restart, and the issue was not there. So I suspected it had to do with the graphical launcher... and it is. 
What should be the command to start the program? I had a bunch of % and Us, probably my fault, and it was taking "U" as parameter.

**Comment by jixbo** [comment]
Fixed it, it was my mistake, sorry.
