### ISSUE TITLE
portable windows version request

### ISSUE THREAD

**Issue by n0k1a** [Eloston/ungoogled-chromium#1753]
i am requesting a completely portable version for windows.

will donate 50 euro in btc.

**Comment by n0k1a** [comment]
> What do you mean "completely portable"? There are [binary releases, Windows included](https://ungoogled-software.github.io/ungoogled-chromium-binaries/).

i mean saving user data in a local folder and not in appdata.

**Comment by PF4Public** [comment]
Have you tried [--user-data-dir=](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/user_data_dir.md)?

**Comment by n0k1a** [comment]
worked, thanks. didnt know its that easy to make it portable. leave your btc adress if you want. :-)

**Comment by PF4Public** [comment]
No problem.

**Comment by n0k1a** [comment]
is it possible to run multiple instances with different profiles?

**Comment by networkException** [comment]
should be, yes

**Comment by n0k1a** [comment]
nope, tried it. only 1 instance is possble. if i change the user data directory for an second instance too, it deletes for the old instance.

**Comment by n0k1a** [comment]
so its not completely portable.

**Comment by tomasz1986** [comment]
I have just done a test on my system here. It works fine with multiple instances, each of them using a different profile folder.

I'm achieving this with

```
chrome.exe --user-data-dir=profile1
chrome.exe --user-data-dir=profile2
```

etc.

**Comment by n0k1a** [comment]
yes it works, but i restarted my pc now and it didnt save. i had to do the command again. otherwise it writes into appdata again.

**Comment by tomasz1986** [comment]
Yes, this is how Chromium works in general. You always need to start the browser with the `--user-data-dir` flag if you want to use a custom profile path.
