### ISSUE TITLE
Install YouTube notification

### ISSUE THREAD

**Issue by calhix** [Eloston/ungoogled-chromium#1758]
When on youtube, it suggests within the URL bar on the right to install the youtube extension, it also comes up in the settings menu all the way on the right (the three dots), anyway to get rid of this? I feel like this should be an opt-in setting.

**Comment by PF4Public** [comment]
You have the possibility **not** to install anything simply by ignoring this icon. What is the problem with it?

**Comment by calhix** [comment]
No problem, just something I wanted to mention but sure one can just ignore it.

**Comment by plashenkov** [comment]
We would like to have a cleaner interface by removing all the clogging stuff.

**Comment by PF4Public** [comment]
> We would like to have a cleaner interface by removing all the clogging stuff.

Please by all means submit a PR with improvements.
