### ISSUE TITLE
portable version

### ISSUE THREAD

**Issue by elec7rum** [Eloston/ungoogled-chromium#1767]
hello, i am requesting a portable version for windows. i am not searching for something like the command --user-data-dir=

example: https://portapps.io/app/ungoogled-chromium-portable/

but official.

**Comment by PF4Public** [comment]
Please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
