### ISSUE TITLE
Corrupted drop-down menu in Linux

### ISSUE THREAD

**Issue by diogodiogo2** [Eloston/ungoogled-chromium#1772]
Some menus appear broken on Manjaro Linux XFCE. 
![image](https://user-images.githubusercontent.com/74558056/146112056-6ff749a9-b195-46d0-9714-4398aef71746.png)

I tried the precompiled Arch Linux version and the flatpak found on pamac.
Some menus aren't affected. For example, right clicking the website shows it normally. Pressing the 3 dots at the corner also works properly.
Version: 96.0.4664.93
Linux Kernel: 5.10.83-1
The issue only happens with hardware acceleration

**Comment by networkException** [comment]
Which menus exactly are affected? I've never seen this type of behavior on my system. Does this persist after a reboot? Is this related to a specific gpu driver version or something?

**Comment by diogodiogo2** [comment]
Yes, it does persist after rebooting. However, when I reactivated hardware acceleration, some of the problems disappear, but some remained happening.

The menus affected are:
Right click on a tab (solved)
Three points in a site opened as a window (solved)
Menus in settings (such as the search provider one)

Other problem I found is that, when you select and drag a text, it appears corrupted like the menus.

My GPU is a Radeon Vega 8 (included in the Ryzen 3 2200g processor)  and I am using the driver version 21.2.5 (which was included with manjaro)

**Comment by networkException** [comment]
Are there any error message in your gpu driver and or chromium logs?

**Comment by diogodiogo2** [comment]
Where can I find those?

**Comment by networkException** [comment]
sudo journalctl -f for system logs and for chromium see [the documentation](https://www.chromium.org/for-testers/enable-logging/)

**Comment by wchen342** [comment]
I'm seeing something similar but slightly different on `96.0.4664.110` today with Mesa driver and Intel UHD. I don't know whether it is the same problem though. It doesn't happen if switched to nvidia GPU so I suspect it can be mesa related.
![001](https://user-images.githubusercontent.com/6406743/146590575-7b22d3ae-e20b-4156-8d10-a233af227376.gif)

**Comment by diogodiogo2** [comment]
> I'm seeing something similar but slightly different on `96.0.4664.110` today with Mesa driver and Intel UHD. I don't know whether it is the same problem though. It doesn't happen if switched to nvidia GPU so I suspect it can be mesa related. ![001](https://user-images.githubusercontent.com/6406743/146590575-7b22d3ae-e20b-4156-8d10-a233af227376.gif)

For me it happens on AMD integrated graphics using MESA as well

**Comment by PF4Public** [comment]
Which version of mesa do you all have?
I have no such issues with Intel builtin video and mesa-21.2.5.

**Comment by diogodiogo2** [comment]
> Which version of mesa do you all have? I have no such issues with Intel builtin video and mesa-21.2.5.

I also use 21.2.5

**Comment by wchen342** [comment]
Mine is Mesa 21.3.1 and
```
Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.7-200.fc35.x86_64 (64-bit)
Graphics Platform: X11
```
. I should mention I have Vulkan turned on in `chrome://flags`.

**Comment by wchen342** [comment]
The problem kind of fixed itself to some extent, now I only see flickering, but the black artifacts are gone. Not sure what triggered the change.

**Comment by PF4Public** [comment]
@diogodiogo2 Do you also have Vulkan enabled? I remember disabling Vulkan as VA-API doesn't work well with it.

**Comment by diogodiogo2** [comment]
@PF4Public I don't know, but it's on the default, I didn't change it.

**Comment by PF4Public** [comment]
@diogodiogo2 Have you tried plain Chromium? I doubt this issue could be due to ungoogled-chromium patches. Highly likely it is upstream issue.

**Comment by git-bruh** [comment]
![f](https://user-images.githubusercontent.com/67585967/146780706-cafb9302-5bca-467b-b8d1-0f7fe6482c07.png)

It's a chromium issue, my friend had it on an electron app

**Comment by wchen342** [comment]
Yeah I think it is chromium, cr96 seems to have a bunch of GPU problems. I had a look at crbug but couldn't find a bug report related to this though.

**Comment by PF4Public** [comment]
I think, I'll mark it with `need info` for better visibility. In case someone finds a crbug for it that'd be great. With this label it'll also close automatically :)

I think we need a special label, like `upstream` for similar cases. To acknowledge that the issue does indeed exist, but we cannot do much about it.

@git-bruh That's element-desktop right? Which version of electron does it use. AFAIK element-desktop depends on electron-13, which is based on chromium 91. Unless it is a custom build of element with higher electron.

**Comment by PF4Public** [comment]
@diogodiogo2 @wchen342 Do you experience this issue with 97?

**Comment by wchen342** [comment]
Haven't had time do the upgrade to v97 yet. Maybe in a few days I can try it.

**Comment by diogodiogo2** [comment]
@wchen342 Apparently, it was fixed with v97. Sorry by the late reply.

**Comment by PF4Public** [comment]
@diogodiogo2 Thanks for letting us know!
