### ISSUE TITLE
How do I restore backup via AppData?

### ISSUE THREAD

**Issue by Sneffel** [Eloston/ungoogled-chromium#1773]
I copied the AppData folder on w10, performed a factory reset and then updated to w11
Now I moved the AppData folder to it's place but it's not recognised anymore by w11 (my guess)
So how should I do it?
I have lots of data I don't want to be lost

**Comment by networkException** [comment]
As documented [here](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/user_data_dir.md#Windows) user data should be located in appdata, make sure your installation points to the correct directory
