### ISSUE TITLE
`--enable-features=WebUIDarkMode` flag doesn't work with `--enable-features=VaapiVideoDecoder`

### ISSUE THREAD

**Issue by mizzunet** [Eloston/ungoogled-chromium#1778]
**Describe the bug**
If `chromium` opened with `--force-dark-mode` `--enable-features=WebUIDarkMode` `--enable-features=VaapiVideoDecoder`, dark mode at Settings, Extensions do not work. Opening merely with `--force-dark-mode`  and `--enable-features=WebUIDarkMode` works though

**To Reproduce**
1. Execute `chromium --force-dark-mode --enable-features=VaapiVideoDecoder --enable-features=WebUIDarkMode`
2. Go to any site, ex, chrome://settings/

**Expected behavior**
Dark mode at Chrome URLS

**Screenshots**
![image](https://user-images.githubusercontent.com/10193999/147069775-f6153f63-342c-49ff-b6e3-afe463482db2.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Arch Linux 
 - ungoogled-chromium version: 96.0.4664.110-1

Additional context:

 `--enable-features=VaapiVideoDecoder` is not useful to me anyway as HW does not work on mine https://github.com/Eloston/ungoogled-chromium/issues/1736#issuecomment-998672503

**Comment by PF4Public** [comment]
Please rephrase your issue, I have difficulties making sense of this:

>Extensions do not work
>Opening […] works though
>Expected behavior: Dark mode at Chrome URLS

**Comment by mizzunet** [comment]
`chromium --force-dark-mode --enable-features=WebUIDarkMode`

They are dark
![image](https://user-images.githubusercontent.com/10193999/147120266-1bcadd69-413c-4169-b44b-099c003df6b1.png)
![image](https://user-images.githubusercontent.com/10193999/147120287-0b0ad5f0-893a-4899-8b62-8784c1005f5a.png)

![image](https://user-images.githubusercontent.com/10193999/147120233-dd6b3d8f-08d4-49d9-beeb-a06983332e13.png)



`chromium --force-dark-mode --enable-features=WebUIDarkMode --enable-features=VaapiVideoDecoder
`
These aren't dark though it's flags were passed

![image](https://user-images.githubusercontent.com/10193999/147119963-f477155f-f6d9-4bdc-a6ca-1c6b39be950e.png)
![image](https://user-images.githubusercontent.com/10193999/147119987-e6b2403a-3177-4426-bd22-4842e1031cd6.png)
![image](https://user-images.githubusercontent.com/10193999/147120023-c8a56062-b337-478b-838d-30bd23af8238.png)

You got it?

**Comment by PF4Public** [comment]
> You got it?

Much better!

@networkException Have you had anything like this?

**Comment by networkException** [comment]
Reversing the order of those arguments brings back dark mode but I'm not very familiar with the whole VAAPI stuff so that might not work after doing so? I checked the media dev tools pannel and it showed FfmpegVideoDecoder both times.

**Comment by mizzunet** [comment]
> Reversing the order of those arguments brings back dark mode 

Oh yeah, that's right. Thanks. In that case, I think this issue can be closed.

**Comment by PF4Public** [comment]
> I checked the media dev tools pannel and it showed FfmpegVideoDecoder

I think Youtube tries to provide video in the best quality available, which could be using a codec, that is not supported by your GPU, which results in using CPU instead of VAAPI.

**Comment by mizzunet** [comment]
I too actually have FfmpegVideoDecoder for YouTube, Invidious and all

**Comment by PF4Public** [comment]
You could use h264ify extension to force videos to be h264 to ascertain VAAPI works.
