### ISSUE TITLE
Extension installation: page unresponsive

### ISSUE THREAD

**Issue by anishmittal2020** [Eloston/ungoogled-chromium#1780]
**Describe the bug**
> You must change the flag chrome://flags/#extension-mime-request-handling to Always prompt for install if you are using ungoogled-chromium. The majority of issues reported by users are solved by setting this flag.

> From: https://github.com/NeverDecaf/chromium-web-store

But when I do this my ungoogled-chromium just hangs! See screenshots below. After some time I get a pop up stating that the page is unresponsive.

**Screenshots**

![image](https://user-images.githubusercontent.com/42092626/147361957-5c2adb2d-575b-4eb8-860f-f7c51d5c1be5.png)

![image](https://user-images.githubusercontent.com/42092626/147362044-d545ad08-788b-4580-86db-b275c2fb08a6.png)

**Environment (please complete the following information):**
 - OS/Platform and version:Ubuntu 20.04.3
 - ungoogled-chromium version: Version 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

**Comment by networkException** [comment]
Are you using the OBS version?

**Comment by anishmittal2020** [comment]
@networkException I am not sure but  this is how I installed:

```bash
deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/ /" | sudo tee /etc/apt/sources.list.d/home-ungoogled_chromium.list > /dev/null; curl -s "https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/Release.key" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home-ungoogled_chromium.gpg > /dev/null;  sudo apt update; sudo apt install -y ungoogled-chromium
```

Does this answer your question?

**Comment by networkException** [comment]
Yes. Sadly those versions currently have various issues, see https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/247#issuecomment-950481610

**Comment by PF4Public** [comment]
I suppose we cannot do anything about it, right?

**Comment by networkException** [comment]
It would be helpful to at least have some kind of note in the readme but I don't have write access or anything

**Comment by wchen342** [comment]
I have been wondering why Ubuntu version has these problems. I saw someone mentioned in the thread that he had problems on Focal, but that shall come with pretty recent libraries unlike Debian. Maybe the Debian-based build has some special build time parameters?

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
