### ISSUE TITLE
Create a .AppImage version of latest ungoogled-chromium please! 

### ISSUE THREAD

**Issue by ExpertMen** [Eloston/ungoogled-chromium#1790]
I'm on Debian Linux guys, and.....it's really easy to me to install and open softwares by extracting tar.gz file and opening it and finding a button which can i click to open software, or by using .AppImage format (downloading first, then going to properties and click "Allow excute this file as a program."). So... i'm using 91.0.4472.164 version of ungoogled-chromium. Yes, i know, that this is old version, not the latest, but can somebody tell me where can i download latest version of ungoogled-chromium in .AppImage format? 
 **You may say:**
 **1**. Bruh, go to Realeases tab here on GitHub and download zip/tar.gz file.
**My Answer:** I can't understand how to open this files as a program. I downloaded both, but i have no idea how to make them run as a programs.
**2.** Well, there's version of ungoogled-chromium for debian on GitHub!
**My answer:** Really? I did not found .deb file! Even .AppImage version i did not found!

**_Please, help me to get .AppImage version of ungoogled-chromium, it will much easier for me to install!_**

**Comment by Noryub** [comment]
**I can't understand how to open this files as a program.** 
 Just open a terminal inside the folder and execute "./chrome"
 
 **Really? I did not found .deb file!**
Check https://github.com/ungoogled-software/ungoogled-chromium-debian (it's a bit buggy)

And just for the record, I'd also like the AppImage updated.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.

**Comment by gsantner** [comment]
> @PF4Public 
> I hope your question has been answered, otherwise please let us know.

Not answered properly, not fixed.

AppImage still has not been updated. That's what the topic is about. There is no recent release there.

![image](https://user-images.githubusercontent.com/6735650/150309742-42c5b5fd-7b85-4a78-88bb-1c5e16901ca1.png)

**Comment by PF4Public** [comment]
> AppImage still has not been updated.

Those binaries are submitted by volunteers. We have very limited responsibility about them (as it is stated on the webpage!). And of-course I _cannot_ force anyone to prepare and submit your requested binary. If anyone is willing to submit AppImage, it is without this issue apparent that the latest binary that is available is very old.

That being said, we try keeping open those issues, which we have to deal with in some regard.

**Comment by gsantner** [comment]
So are really the binaries themself by strangers as built by strangers, or only the buildscripts (and executed on CI) by strangers?

**Comment by gsantner** [comment]
So are really the binaries themself built on strangers machines and uploaded, or only the buildscripts defined by strangers (and executed on CI)?

**Comment by networkException** [comment]
The binaries themself

**Comment by gsantner** [comment]
Oh, I hipes for the second :D. Than I stay away from these.

**Comment by mpaunovic** [comment]
Here you go, the latest & greatest appimages:

https://github.com/macchrome/linchrome/releases

The guy making them is the same guy behind https://chromium.woolyss.com, so he is very trustworthy.

**Comment by PF4Public** [comment]
> https://github.com/macchrome/linchrome/releases
> 
> The guy making them is the same guy behind https://chromium.woolyss.com, so he is very trustworthy.

Please note though, that we cannot provide support for those binaries.

**Comment by gsantner** [comment]
thanks for posting this one, it's working well on all machines. Now I just automatically download the github release one device, automatic sync, and have a very recent browser version on all Linux (old & new distro) hosts. It's really hard nowadays to get a maintained and always-quite-uptodate browser without investing time, thats a bit of sad state^^.

**Comment by gsantner** [comment]
thanks for posting this one, it's working well on all machines. Now I just automatically download the github release on one device, it gets automatic synced, and I have a very recent browser version on all Linux (old & new distro) hosts. It's really hard nowadays to get a maintained and always-quite-uptodate browser without investing time, thats a bit of sad state^^. 

Btw, where can I find the info of the person/service relation -- `woolyss == linchrome`?

**Comment by gsantner** [comment]
thanks for posting this one, it's working well on all machines.  
Btw, where can I find the info of the person/service relation -- `woolyss == linchrome`?

**Comment by expertmanofficial** [comment]
ummm, if anyone interested, I am the same guy known as "Expert Men", just abandoned the previous account.

@mpaunovic has said the right thing, this what helped to get my issue fixed.....

Sorry for not responding for over a year now, @PF4Public :))))
