### ISSUE TITLE
Crash when about:support is draged to tab

### ISSUE THREAD

**Issue by Rexadev** [Eloston/ungoogled-chromium#1791]
**Describe the bug**
https://bugs.chromium.org/p/chromium/issues/detail?id=1274990

**To Reproduce**
1. Type "about:support" anywhere (for example in google search)
2. Drag "about:support" into a new tab or existing tab in tabs bar

**Expected behavior**
Open chrome:support

**Screenshots**
Crashes

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 21H1
 - ungoogled-chromium version: 96

**Additional context**

**Comment by networkException** [comment]
Does this happen in vanilla chromium as well?
