### ISSUE TITLE
how to get egl working under xwayland

### ISSUE THREAD

**Issue by D0nnieD4rk0** [Eloston/ungoogled-chromium#1794]
it worked fine on fedora install so its probably just a case of a few missimg dependencies on arch
the --use-gl=egl flag just tells you to it doesn't work
firefox which is a lot better supported on linux has egl by default
thanks in advance

**Comment by wchen342** [comment]
@networkException Arch specific problem?

**Comment by networkException** [comment]
I can't reproduce this, vanilla chromium and ungoogled-chromium behave the same with the flag on `plasma-wayland-session`

**Comment by D0nnieD4rk0** [comment]
well im not on plasma rn im on cinnamon which has generally poor support for wayland tho it doesnt matter cuz an app told to run wayland will do it no problem
in this case it tells u it cant do it
i didnt have this issue in cinnamon on fedora and so it has to be some missing deps

**Comment by networkException** [comment]
When installing `plasma-wayland-session` and `wayland`, `xorg-xwayland` was also installed. Thats the only real dependency I can see, everything else was just part of a base manjaro kde install (I doubt that includes many wayland specific dependencies)

**Comment by D0nnieD4rk0** [comment]
> When installing `plasma-wayland-session` and `wayland`, `xorg-xwayland` was also installed. Thats the only real dependency I can see, everything else was just part of a base manjaro kde install (I doubt that includes many wayland specific dependencies)

damn kde rly does have it ezier
i already have the `plasma-wayland-session` dependencies (besides the kde stuff) installed
so what can i do besides moving to kde to get the thing working ?

**Comment by networkException** [comment]
what exact error message does it report?

**Comment by D0nnieD4rk0** [comment]
`[24681:24681:0111/205716.837847:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is
[24681:24681:0111/205716.851790:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
[24649:24675:0111/205719.462979:ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0
[24649:24675:0111/205720.180886:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.`
