### ISSUE TITLE
No prebuilt mac version

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [Eloston/ungoogled-chromium#180]
I'm able to successfully build a Mac dmg – is something keeping you from including the Mac version with the latest release?

**Comment by Eloston** [comment]
[They're still on the downloads page](https://ungoogled-software.github.io/ungoogled-chromium-binaries/). I don't know what you mean...

**Comment by WIZARDISHUNGRY** [comment]
@Eloston the "Downloads for the latest release" link in README.md points to https://github.com/Eloston/ungoogled-chromium/releases/tag/55.0.2883.87-1

**Comment by Eloston** [comment]
Yes, and that points to the page to download binaries for other platforms.

The link will be changed once the new downloads system is finalized.
