### ISSUE TITLE
Addblocker blocks internet connection

### ISSUE THREAD

**Issue by Jd7Kz8o** [Eloston/ungoogled-chromium#1802]
When an addblocker is enabled, the browser cannot connect to the Internet and the addblocker gets stuck.
When I disable the extension everything works, as soon as I enable the extension, the browser cannot connect to the internet.
Everything worked fine until I updated the browser and the whole system. With the old version everything worked (apt update && apt full-upgrade && apt autoremove && apt autoclean).
I`ve installed the browser via the Reopsetory: http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/

Tested Add Blockers:
uBlock Origin: 1.40.8
AdGuard AdBlocker 3.6.17
uBlock Pro - #1 Adblocker 2.1.6

Browser: Version 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.11.5-custom
OS Type: 64-bit
Processors: 8 × AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
Memory: 13.7 GiB of RAM

**Comment by networkException** [comment]
Chromium 95 is an outdated version is no longer maintained. Please use [an up to date release](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/255)

**Comment by Jd7Kz8o** [comment]
The repository on OpenSUSE.org is out of dated, I have no other RePo. Can someone update the RePo? Please.

**Comment by networkException** [comment]
I know, thats why the string "an up to date release" is a link to - an up to date release.

**Comment by Jd7Kz8o** [comment]
Then I always have to update the browser manually, why no RePo?
I hate images, they never work properly and have to be saved in the home folder, messing up my folder structure.

**Comment by networkException** [comment]
Because this is a project maintained by people in their free time and as of now the problems described in the issue I linked have not been resolved.

**Comment by PF4Public** [comment]
Closing this issue in favour of ungoogled-software/ungoogled-chromium-debian#255

**Comment by manuelschneider** [comment]
Hi, fwiw - and because I had the same problem: Ublock works with the linked chromium 97 release. Thank you for this great work! :)
