### ISSUE TITLE
Moving tabs opens a new window in newer version

### ISSUE THREAD

**Issue by Yakui420** [Eloston/ungoogled-chromium#1803]
I'm using debian and version 97.0.4692.71 (flatpak)

Everytime I try to move a tab it just opens another window for me. 
Is there a way to fix that?

**Comment by networkException** [comment]
This is an upstream bug in chromium ([bugs.chromium.org](https://bugs.chromium.org/p/chromium/issues/detail?id=1279532)), there are patches for [KWin](https://chromium-review.googlesource.com/c/chromium/src/+/3355376) and [Mutter](https://chromium-review.googlesource.com/c/chromium/src/+/3355470/1) but those are not included in the current release. I would recommend opening an issue in the [flatpak repository](https://github.com/flathub/com.github.Eloston.UngoogledChromium) to get this fixed on their end ([other distributions](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/0a3d47330bec2ff48ddf13bccb322ff3aa5a5a8e) of ungoogled-chromium have fixed this issue downstream as well)

**Comment by Yakui420** [comment]
Thanks.
