### ISSUE TITLE
No Google's web page should be special

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Eloston/ungoogled-chromium#1807]
**Is your feature request related to a problem? Please describe.**
Chrome extensions are not allowed to modify some Google's web pages. For example, I've installed an extension called "Dark reader", which make all web pages dark. However, on the Chrome webstore page it simply doesn't work, and it tells us why.
![image](https://user-images.githubusercontent.com/39968/150661021-3b6869d9-80ca-4417-a42e-baa278f3136a.png)

**Describe the solution you'd like**
I think it's controlled by some source file of Chromium, but I can't find it. Hope I can get some help here.

**Comment by kramred** [comment]
That seems to be an issue with that extension:
It seems it [disables itself](https://github.com/darkreader/darkreader/blob/master/src/background/utils/extension-api.ts#L34) if the url starts with e.g. `https://chrome.google.com/webstore`
https://github.com/darkreader/darkreader/blob/master/src/background/utils/extension-api.ts#L34

```ts
    return (url
        && !url.startsWith('chrome')
        && !url.startsWith('https://chrome.google.com/webstore')
        && !url.startsWith('data')
        && !url.startsWith('devtools')
        && !url.startsWith('view-source')
    );
```

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Interesting. I didn't expect this to be the case. Thanks for the help!

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I commended the corresponding line and did some testing. It's true that Chrome doesn't allow extensions to modify the webstore page. I got this error when trying to do so:

![image](https://user-images.githubusercontent.com/39968/150677541-4eef9353-20e0-4feb-a59c-8b08d9364486.png)

The extension author has that code in it, it's just to avoid the error. But I can't find the error message `The extensions gallery cannot be scripted` in Chromium's source. Where do you think this comes from?

**Comment by kramred** [comment]
Cannot reproduce, see below. Also you write "Chrome" - is this about Goole Chrome or ungoogled chromium?
Please paste your output of the page `chrome://version/` here.
Mine is:
```
Chromium	97.0.4692.99 (Official Build, ungoogled-chromium) (x86_64)
Revision	d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS	macOS Version 10.15.7 (Build 19H1615)
JavaScript	V8 9.7.106.19
User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Command Line	/Applications/Chromium.app/Contents/MacOS/Chromium --flag-switches-begin --fingerprinting-canvas-image-data-noise --fingerprinting-canvas-measuretext-noise --fingerprinting-client-rects-noise --force-punycode-hostnames --keep-old-history --max-connections-per-host=15 --popups-to-tabs --flag-switches-end
Executable Path	/Applications/C
![ext_chromium](https://user-images.githubusercontent.com/16719551/150682107-cfc03f88-3eeb-4d65-bce9-72d6fa1bb29a.png)
hromium.app/Contents/MacOS/Chromium
Profile Path	/Users/$user/Library/Application Support/Chromium/Default
Linker	lld
Variations	19ebe09a-4542122
```

For me both "uBlock origin" and "User JavaScript and CSS" work on `https://chrome.google.com/webstore`:

![ext_chromium](https://user-images.githubusercontent.com/16719551/150682122-07af66c1-c1d7-4369-8c99-d749f20b757e.png)
