### ISSUE TITLE
Segfault after launch

### ISSUE THREAD

**Issue by Spaceface16518** [Eloston/ungoogled-chromium#1808]
I am using ungoogled chromium from [ungoogled-software/ungoogled-chromium-archlinux](https://github.com/ungoogled-software/ungoogled-chromium-archlinux) on Manjaro.

```
CPU: 8-core AMD Ryzen 7 4700U with Radeon Graphics (-MCP-)
Kernel: 5.15.16-1-MANJARO x86_64
```

Downloaded and compiled ungoogled-chromium

```
Chromium 97.0.4692.99 Manjaro Linux
```

However, when I try to start the browser, it crashes after a couple seconds. Starting from the terminal shows a segfault.

```
$ time chromium
[142067:142067:0125/190007.631315:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
Segmentation fault (core dumped)

real	0m4.531s
user	0m0.479s
sys	0m0.625s
```

This made me think it has something to do with sandboxing. Tried to disable sandboxing with `--no-sandbox` but this also segfaults and warns me that `--no-sandbox` is an "unsupported command line flag".

I couldn't find this issue elsewhere, but maybe I'm just not looking hard enough. Is this a known issue? Any help is appreciated. Thank you!

**Comment by networkException** [comment]
Please open an issue in that repository.

**Comment by Spaceface16518** [comment]
Oh okay, will do.
