### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ENTERspaceAspaceUSERNAME** [Eloston/ungoogled-chromium#1811]
1. I would like to know if
"Always use secure connections
Upgrade navigations to HTTPS and warn you before loading sites that do not support it"
calls Google's servers.

2. I would also like to know if saving passwords calls Google's servers or if it is completely local.

3. I would also like to know if
"Live Caption
automatically creates subtitles for English audio and video files. The audio and subtitles never leave your device."
calls Google's servers.

**Comment by networkException** [comment]
1. No
2. No
3. I don't know, is that even available in ungoogled-chromium?

This project not only removes code that would normally send requests to Google servers, it also forcefully removes all Google urls from the source code.

Still please be aware that the code is provided "AS IS", if your requirements are to be safe against targeted tracking by an intelligence agency or something you should probably not only rely on this project to stop connections to Google.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
3. Yes, in the settings. It is in _Advanced_ > _Accessibility_ > _Live Caption_
It basically gives yous subtitles which is nice.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Moreover, it does that in real-time. So that is why I wanted to know if it was something wholly local or constantly made calls to Google.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
4. I also wanted to know if "Autocomplete searches and URLs
Sends some cookies and searches from the address bar and search box to your default search engine." contacts Google because out of the description, it does not seem to. Nevertheless, I wanted to make sure that it doesn't because usually, in other browsers, it does.

**Comment by networkException** [comment]
ungoogled-chromium does not have that setting or functionality as it requires google servers.

**Comment by networkException** [comment]
I will close this for now. For this type of questions please consider asking on matrix in the future.
