### ISSUE TITLE
My settings just got reset.

### ISSUE THREAD

**Issue by ENTERspaceAspaceUSERNAME** [Eloston/ungoogled-chromium#1812]
I got this message: Some settings have been reset
Chrome has detected that some of your settings have been corrupted by another program and has reset them to their original default values. Read more.
What I did before this was set a flag that was enabled to default and put it back on to enabled, then I restarted the browser and got this message. Everything got removed aside from bookmarks. My extensions are all gone. My settings also got reset.

**Comment by networkException** [comment]
What flag have you modified?

**Comment by ENTERspaceAspaceUSERNAME** [comment]
The IPV6 one.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
It was enabled. I just clicked on default and then clicked on enabled. Straight after that, I relaunched and I got that message.

**Comment by PF4Public** [comment]
This might be an issue with the Windows binary as this does not happen on Linux or MacOS.
Please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
