### ISSUE TITLE
error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by BOY0038v2** [Eloston/ungoogled-chromium#1815]
upgrading ffmpeg  (2:4.4.1-1 => 2:5.0-3) on my artix linux install broke ungoogled chromium and i get this error when i try to run it. 
"error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory". Is there any fix for this?
for now i just downgraded back to ffmpeg version 2:4.4.1-1

**Comment by networkException** [comment]
`ffmpeg` is currently in `Staging` in the official Arch repository, if I were to push an update with the patches required for `2:5.0-3` it would break existing installations running `2:4.4.1-1`. I've pushed the required changes to a seperate branch called [staging](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/tree/staging) for now

**Comment by PF4Public** [comment]
So… Is it solved? Maybe it belongs to Arch platform repo?

**Comment by networkException** [comment]
Yea, if there are further questions please open an issue in https://github.com/ungoogled-software/ungoogled-chromium-archlinux
