### ISSUE TITLE
build error under Jessie

### ISSUE THREAD

**Issue by kairaven** [Eloston/ungoogled-chromium#182]
I have tried to compile ungoogled-chromium-55.0.2883.87-1 under Jessie, so i installed the mentioned dependencies and the missing libffi-dev libgconf2-dev libgnome-keyring-dev libnss3-dev libcups2-dev packages. But at this point it ends:

Done. Made 4959 targets from 1116 files in 5931ms
2017-02-01 15:43:28,311 - INFO: Running build command...
ninja: Entering directory `out/Default'
ninja: error: '../../third_party/icu/common/icudtl.dat', needed by 'obj/third_party/icu/make_data_assembly.inputdeps.stamp', missing and no known rule to make it
2017-02-01 15:43:29,129 - ERROR: ninja returned non-zero exit code: 1

**Comment by wimh** [comment]
I have also noticed that tag does not build. As a workaround you can remove `resources/linux_static/cleaning_list` before building. (remove `build\sandbox` if it still exists).

Note that you will also need python 3.5 or 3.6. Jessie includes python 3.4, will will cause an error at the end of the build (`AttributeError: 'PosixPath' object has no attribute 'write_bytes'`).

(I am working on a docker image which is currently able to build the master branch and some tags: https://github.com/wimh/build-ungoogled-chromium/blob/master/debian-8/Dockerfile)

**Comment by Eloston** [comment]
This is already fixed in `master`, but I haven't released a new tag with it. I'll close this when the next version comes out.
