### ISSUE TITLE
Running adblock or ublock on ubuntu ungoogled-chromium 95 completely stops all website traffic.

### ISSUE THREAD

**Issue by stubkan** [Eloston/ungoogled-chromium#1824]
**Describe the bug**
Due to newer extensions not working, I decided to upgrade from 87 to whatever the latest ubuntu maintained version was - which is 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

Installed via normal apt-get.  The first thing I notice is no websites will load.  After investigation, discover it is two extensions that are completely blocking all website traffic.  The two extensions are uBlock origin and AdBlock plus and were about a year old.  I updated them to the latest versions with no effect.

I found this other guy having a similar issue, at 
https://askubuntu.com/questions/1386811/after-update-ungoogled-chromium-web-browser-is-not-connecting-to-the-internet
which helped me to pinpoint the issue for me.  Which seems to indicate this is potentially a more widespread issue.

It seems this is likely not an issue with the extensions but rather an issue with the browser, since it is two separate extensions killing the traffic.  Also, the same extensions were working properly before the upgrade from 87 to 95, pointing to chromium code potentially being the problem.

Those extensions are absolutely essential for most security conscious web users, I hope the issue can be found and resolved soon.

**To Reproduce**
Be on ubuntu 20.04
Install latest maintained ungoogled chromium
Add either ublock or adblock
Try visiting google.com

**Expected behavior**
The ability for the web to be browsed safely with common extensions adblock/ublock running.  The extensions not completely blocking all web traffic.

**Environment (please complete the following information):**
 - OS/Platform and version: Linux Mint 20.1 - Based on Ubuntu 20.04 - Intel Nvidia
 - ungoogled-chromium version:  95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

**Additional context**
I will attempt to find other extensions that do similar jobs to ublock/adblock and try to run them, to keep my browsing safe.  I will report any other extensions that work / do not work in here as I find them.

**Comment by networkException** [comment]
This is a duplicate of #1802

**Comment by stubkan** [comment]
Ah, I did a search for issues, found none.  That is a closed issue though, why is it closed?  This issue came up following installation instructions off this github.

**Comment by networkException** [comment]
It's closed because it is in itself a duplicate of an issue in a different repository. OBS releases for Debian are currently broken, alternative builds are available (see https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/255)

**Comment by stubkan** [comment]
I realise this is probably not the right place for it, but I cant post on that thread you linked and starting a new issue seems redundant at this point.  To get a working system again, I tried getting ungoogled-chromium_97.0.4692.99-1.unportable1_amd64.deb off the latest build they released there.  

It just said dependency is not satisfied.   Okay, get the listed file 

- failed due to common_97.0.4692.99-1.unportable1_amd64.deb (--install):  conflicting packages - not installing ungoogled-chromium-common

Do I have to completely uninstall chromium in order to install this new version?  What about all my bookmarks, extensions, settings?  How do I downgrade or install a different version?  There is very little documentation I can find, so I have no idea what to do at this point.

**Comment by flrns** [comment]
You have to install the dependency, which can be found as one of the files listed at https://github.com/Eloston/ungoogled-chromium-binaries/releases (ungoogled-chromium-common_97.0.4692.99-1.unportable1_amd64.deb for the current version).

Configuration should be kept when installing the .deb over an old version (or even when uninstalling the old version first with `apt remove`), but if you want to be sure you can just make a backup copy of the config-directory.

**Comment by stubkan** [comment]
Yes, ok maybe I did not write it very well, sorry.

I did follow that step, I downloaded that file and it stopped me from installing it, the error message it told me was this

- failed due to common_97.0.4692.99-1.unportable1_amd64.deb (--install): conflicting packages - not installing ungoogled-chromium-common

Which I assume the conflicting package is the ungoogled chromium version 95 .... So I don't know how to proceed, because I don't know how to remove the block to that dependency...

**Comment by flrns** [comment]
Sorry, I did not read carefully enough.
Just encountered the same problem (or rather, a similar one I must now say) and solved it that way.

Can you remove ungoogled-chromium-common via `apt`?

**Comment by stubkan** [comment]
I did not try, as it specified the conflicting package was ungoogled-chromium, will try when I get back on the system

**Comment by ruamegatrader** [comment]
I had this problem with mine, the solution I found was to remove the apt, and use the portable version. 
Download it, extract it into ~/apps or ~/ whichever is your preferred method.
Fire it up, cd ~/ungoog....etc.../ and run ./chrome --process-per-site  (until you get an entry in menu editor)
Make sure your extensions are empty (settings->extensions).
If they're not, remove them and see if you can open web sites etc.
When you can, go back into the extensions, enable developer mode, drag and drop the extension folder into the page (you might need to enable one of the options to load unpacked).
it should work. post back here on success or failure, kindly give as much info as possible if it fails, or if you succeed, perhaps others need step-by-step to achieve the good outcome. cheers.
