### ISSUE TITLE
Fullscreened Videos Stutter

### ISSUE THREAD

**Issue by bctv12345** [Eloston/ungoogled-chromium#1826]
In the Ungoogled-Chromium Flatpak, whenever I play any video in fullscreen mode (whether it's in YouTube or Reddit or anywhere else that has a video), it stutters just above half of my screen, making it look slightly cut of or distorted. I've tried playing fullscreened videos in a different browser, but they don't stutter.  I've heard of other people saying thier videos stuttered as well with the Flatpak version, but they solved their problems by updating the browser, even though my browser is updated. I am running on Linux Mint 20.3 and I am running Ungoogled-Chromium 97.0.4692.99 Flatpak.

**Comment by ruamegatrader** [comment]
Did this work in previous versions? Previous UGChromiums or earlier Mint versions? Are you running Mesa or NVidia drivers? ie/ are your videos playing via CPU or GPU? 

What's your GPU? What's your CPU? Maybe jump into IRC and ask for help, make sure your Mint system is working properly when playing videos. Hope this helps a bit. Post back if you have success or it still fails, give as much info as possible for future people following your steps.

**Comment by bctv12345** [comment]
> Does this happen with [ungoogled-software/ungoogled-chromium-portablelinux](https://github.com/ungoogled-software/ungoogled-chromium-portablelinux)?

Sorry for the late response. No, It does not seem to be stuttering with the portable Linux version.

**Comment by PF4Public** [comment]
This could be a Flatpak issue then 🤷

**Comment by bctv12345** [comment]
> Did this work in previous versions? Previous UGChromiums or earlier Mint versions? Are you running Mesa or NVidia drivers? ie/ are your videos playing via CPU or GPU?
> 
> What's your GPU? What's your CPU? Maybe jump into IRC and ask for help, make sure your Mint system is working properly when playing videos. Hope this helps a bit. Post back if you have success or it still fails, give as much info as possible for future people following your steps.

I started using UGC since version 97.0.4692.99, and right now I am using version 99.0.4844.51, but the issues still persists. I started using UGC since Mint version 20.3, which is still the stable version right now. I am very sure that I am running Mesa drivers, but I do not know if the videos load through my CPU or my GPU. 

My GPU is Intel Corporation HD Graphics 620, and my CPU is Intel© Core™ i7-7500U and it's a dual processor.  In Mint, any offline video seems to load just fine, even in Firefox. I've checked my drivers but they all seem to be up-to-date. Still, nothing seems to be working.

**Comment by bctv12345** [comment]
> This could be a Flatpak issue then 🤷

Yeah, tt could be, considering how the Debian and Ubuntu OBS worked just fine as well.

**Comment by bctv12345** [comment]
UPDATE

After a while, I realized that I don't have this issue anymore, but as to why it's fixed, I can only speculate. Maybe it's fixed because I added other Mesa drivers, or because I reinstalled Linux Mint and upgraded it due to an issue unrelated to UGC, but an interesting change that I noticed is that YouTube videos now load with the VP9 codec instead of AVC1, though I do not know how or why that happened.
