### ISSUE TITLE
Removing bundled search engines

### ISSUE THREAD

**Issue by avrutg** [Eloston/ungoogled-chromium#1828]
Chromium 98 introduced unremovable and non-editable bundled search engines. As far as I know, there is no ungoogled chromium patch to reverse this anti-feature now. Is anybody among ungoogled chromium developers working on this or is it considered not an issue?
![image](https://user-images.githubusercontent.com/59525837/152651831-a38c7087-3c41-4591-95fc-487692c9fb48.png)
![image](https://user-images.githubusercontent.com/59525837/152651852-f09282b8-6959-4c7f-9d4f-5ced40738d69.png)

**Comment by networkException** [comment]
That should probably get removed. I haven't noticed that personally because it only really applies to the default settings

**Comment by kramred** [comment]
The list seems to be populated by [components/search_engines/prepopulated_engines.json](https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.80:components/search_engines/prepopulated_engines.json)

But the inability to edit the entry is just an `disabled` attribute in the HTML code.

You can open developer tools on the settings page and remove that `disabled` attribute from `<cr-input>` and edit the text in the input field or edit it directly in the shadow root in developer tools; see screen-shots below.

It seems that the `disabled` attribute is set in [chrome/browser/resources/settings/search_engines_page/search_engine_dialog.html](https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.80:chrome/browser/resources/settings/search_engines_page/search_engine_dialog.html) and the `urlLocked` bool defined in [chrome/browser/ui/webui/settings/search_engines_handler.cc](https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.80:chrome/browser/ui/webui/settings/search_engines_handler.cc;l=215)

![cr_input_disabled](https://user-images.githubusercontent.com/16719551/152656062-3feb18b9-79d6-44c4-9242-ec9213cc3cff.png)

![cr_input](https://user-images.githubusercontent.com/16719551/152656065-31a6c40b-2333-4c71-8e4f-6fa900a2da31.png)
]

**Comment by PF4Public** [comment]
Given the workarounds @kramred found, I think it is not a big issue, thus closing.
