### ISSUE TITLE
Broken "Remove Tabsearch Button"

### ISSUE THREAD

**Issue by avrutg** [Eloston/ungoogled-chromium#1829]
I don't know if it's ungoogled or upstream chromium bug, but the the above-mentioned flag seems now to work in Ungoogled Chromium 98 anymore

**Comment by networkException** [comment]
I can't reproduce an issue with the flag, perhaps is a platform specific problem?

**Comment by PF4Public** [comment]
Also cannot reproduce this issue:
![image](https://user-images.githubusercontent.com/10319700/152677170-77274952-86a6-4d73-b144-66843533e71a.png)
![image](https://user-images.githubusercontent.com/10319700/152677180-b56902d0-1c7f-4f67-87c6-a0678357c2e3.png)

**Comment by avrutg** [comment]
![image](https://user-images.githubusercontent.com/59525837/152677771-d3e1b73a-1351-4317-ad99-f9b23642af17.png)
Maybe it is a windows thing then? 
I use https://github.com/macchrome/winchrome builds, who builds Nifury's fork

**Comment by networkException** [comment]
Likely Windows specific, I guess you can open an issue in Nifurys fork... The current situation with Windows repositories being all over the place really isn't great

**Comment by tomasz1986** [comment]
> Likely Windows specific, I guess you can open an issue in Nifurys fork...

Wouldn't it be a little inappropriate, at least right now, as the Nifury's latest build is still at [97.0.4692.71](https://github.com/Nifury/ungoogled-chromium-binaries/releases/tag/97.0.4692.71-1)?

The issue may as well be specific to https://github.com/macchrome/winchrome builds, which has happened before with other issues, e.g. https://github.com/Eloston/ungoogled-chromium/issues/1714.

**Comment by PF4Public** [comment]
Agreed with @tomasz1986. We cannot support all the binaries available around.

**Comment by avrutg** [comment]
Maybe someone who builds ungoogled chromium themself or uses another build can confirm if the issue is specific to Windows or/and to winchrome build?

**Comment by PF4Public** [comment]
I'll leave it open with `need-info` then in case someone would build from source and could reproduce this issue.

**Comment by networkException** [comment]
Weird, I can't find any code changes from Nifury regarding windows chromium 98 even though macchrome wrote that they are using Nifurys sources.

> We cannot support all the binaries available around.

I assumed that Nifury updated their repository already and just didn't open a pull request to ungoogled-software/ungoogled-chromium-windows yet (I'd get a notification), so opening an issue there would have been logical as it would have been the most up to date

**Comment by avrutg** [comment]
I think they just apply ungoogled chromium 98 patches to Nifury's source code

**Comment by networkException** [comment]
Could be, in that case I'd at least open a pull request.. ah well

**Comment by Nifury** [comment]
I think winchrome's build is cross compiled. It's not built upon my code. 

I've been quite occupied recently - I'll update the code to 98 once I get some time to spare.

**Comment by avrutg** [comment]
@macchrome can you elaborate? Can you confirm the issue and whether or not the latest build is based off Nifury's code?

**Comment by macchrome** [comment]
I build Linux and (cross-compile) Windows x64 from a common source tree to which the (required) ungoogled Windows patches have been applied. Thus eliminating the about://safe-browsing screen in Linux; instead of the usual ungraceful failure.

Under Linux the "add-flag-for-tabsearch-button.patch" and the "Customise profile - Pick a theme colour" function correctly, but not so under Windows x64; I think that this is due to the cross-compilation process: native Windows x86 compilations function correctly.

In future Windows x64 cross-compilations I will omit the "add-flag-for-tabsearch-button.patch". The Chromium Authors can figure out the "Customise profile - Pick a theme colour" problem whilst they are contemplating why  Windows x86 cross-compilation does not work.

   
Nifury's V97 "windows-fix-building-without-safebrowsing.patch" has been amended to be compliant with V98: win.sb.fix.patch

[win.sb.fix.patch.txt](https://github.com/Eloston/ungoogled-chromium/files/8011285/win.sb.fix.patch.txt)

**Comment by avrutg** [comment]
> Under Linux the "add-flag-for-tabsearch-button.patch" and the "Customise profile - Pick a theme colour" function correctly, but not so under Windows x64; I think that this is due to the cross-compilation process: native Windows x86 compilations function correctly.

But the flag did used to work fine in previous builds by you, ever since it was added by ungoogled chromium developers, just like expected? It is only v98 that is the problem. Have you tested it with previous versions?

**Comment by PF4Public** [comment]
This is exactly the reason we do not provide support for third-party binaries.

**Comment by Nifury** [comment]
Windows 10 Tab Search Caption Button (chrome://flags/#win-10-tab-search-caption-button) needs to be disabled to remove tab search button on Windows.

**Comment by Nt3nMoIncwJHgBoHGLmWE** [comment]
Hi again, guys! Yesterday I asked to remove my issues and I don't know who did it, as I didn't get a notification, but it seems like they've been removed, except this one. Could you remove this one too? Thank you again! Sorry for bothering you.

@Ahrotahn @Nifury @networkException @rany2 @Eloston @Cubik65536
