### ISSUE TITLE
Request: Fix many vulns

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#183]
https://security.archlinux.org/AVG-156

sorry for disturb

best regards

**Comment by Eloston** [comment]
I appreciate your support and enthusiasm for a new version of ungoogled-chromium, but please do not post content that does not directly contribute to development.

Thank you.

**Comment by Hillside502** [comment]
@Eloston duplicate of what?

**Comment by Eloston** [comment]
#176
