### ISSUE TITLE
License homepage URLs not substituted. 

### ISSUE THREAD

**Issue by avrutg** [Eloston/ungoogled-chromium#1830]
Doesn't anybody else find it weird that the link to Chromium Open Source Project(which one could argue is harmless) is substituted, while links to license homepages are not and many of them lead to google sites?
![image](https://user-images.githubusercontent.com/59525837/152685788-4e1391de-4806-4b73-980f-dbbfaf03278c.png)
Maybe it makes sense to keep license texts, but remove the links? Just to be consistent? Because elsewhere in the browser they are

**Comment by avrutg** [comment]
If a malicious doer takes control of one of the many sites there, person clicking on the links might get in trouble

**Comment by networkException** [comment]
First of all if an attacker gets access to any chromium internal site you *are* in trouble.

For an url to get substituted it needs to match against a regex in this file:  https://github.com/Eloston/ungoogled-chromium/blob/master/domain_regex.list
There are 10 substituted urls in the credits, this is intended behavior
