### ISSUE TITLE
I can't update components and widevine not working

### ISSUE THREAD

**Issue by RomDlg** [Eloston/ungoogled-chromium#1836]
I just installed ungoogled chromium and i can't update any components in chrome://components. I got this screen
<img width="334" alt="Capture d’écran 2022-02-11 à 09 33 01" src="https://user-images.githubusercontent.com/41866268/153560114-c8c3b756-98fc-4c3c-91d8-5a4cb7e639f6.png">

Is there any way to fix this isssue ?

**Comment by kutsan** [comment]
You have to manually install Widevine, check [this](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-install-widevine-cdm) out.

**Comment by networkException** [comment]
I couldn't find the underlying code that updates components from a quick search but its likely either patched out or the update url is substituted. Anyways that page not working is expected behavior.

**Comment by reduakt** [comment]
There's a mistake in the FAQ: @maljaroudi
"How to install the Widevine CDM plugin?" [https://chromium.woolyss.com/#widevine](url)

There must be an additional subfolder called win_x64 (in case Windows is your OS)
```
98.0.4758.102/WidevineCdm/
├── LICENSE.txt
├── manifest.json
└── _platform_specific
    └── win_x64
        ├── widevinecdm.dll
        ├── widevinecdm.dll.lib
        └── widevinecdm.dll.sig
```
The screenshot lists the information, but three screenshots cropped into one image is visually cumbersome.

**Comment by networkException** [comment]
Like this?

![image](https://user-images.githubusercontent.com/42888162/155614227-2e164050-c4fb-4b11-a080-186deace992d.png)

**Comment by reduakt** [comment]
I was referring to @RomDlg , "Widevine not working"
His screenshot lists Widevine Version 0.0.0.0. It is not installed properly.

I didn't test the build in upgrade function.

**Comment by networkException** [comment]
Yes but adjusting for the mistake you pointed out didn't make it work either, so I was wondering if I maybe got the file path wrong
