### ISSUE TITLE
Version 57 - PLEASE Do Not Implement the new Permanently-Enabled DRM

### ISSUE THREAD

**Issue by WackyModder84** [Eloston/ungoogled-chromium#184]
This is apparently a new feature that Version 57 is going to have.

http://www.tomshardware.com/news/chrome-57-permanently-enabled-drm,33527.html

**Comment by Eloston** [comment]
By "not implementing", what do you mean exactly? Widevine support in Chromium doesn't work without the actual module.

**Comment by maciozo** [comment]
> Widevine support in Chromium doesn't work without the actual module.

Good. Proprietary DRM has no place on the open web.

**Comment by altblitz** [comment]
DRM is the future of the web.
Too late for You, Leddit smartfoners.

Say Sieg Heil!

**Comment by Eloston** [comment]
This is a warning to stay on topic. This is not the place for projecting opinions that do not contribute to development.

**Comment by Eloston** [comment]
Closing this because this isn't a bug.
