### ISSUE TITLE
Google reference in settings 

### ISSUE THREAD

**Issue by kross-italk** [Eloston/ungoogled-chromium#1842]
**Describe the bug**
Opening the settings panel shows a menu item named "You and Google". 

**To Reproduce**
1. Go to Chromium settings 
2. Click on the first menu item on the left, "You and Google"

**Expected behavior**
A ungoogled-chromium to have no Google references (Legality?)

**Screenshots**
![image](https://user-images.githubusercontent.com/50964932/154559363-a8c66e3d-c373-4554-aab2-5c39cc6c763d.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10
 - ungoogled-chromium version: 97.0.4692.71-1.1_windows

**Additional context**
Very cool project, I will be using this!

**Comment by PF4Public** [comment]
And the exact issue is…?
Quote from the README:
[Objectives](https://github.com/Eloston/ungoogled-chromium#objectives)
1. ungoogled-chromium is Google Chromium, sans dependency on Google web services.
2. ungoogled-chromium retains the default Chromium experience as closely as possible. Unlike other Chromium forks that have their own visions of a web browser, ungoogled-chromium is essentially a drop-in replacement for Chromium.
3. ungoogled-chromium features tweaks to enhance privacy, control, and transparency. However, almost all of these features must be manually activated or enabled. For more details, see [Feature Overview](https://github.com/Eloston/ungoogled-chromium#feature-overview).

If that string is bothering you, you could modify the sources to your heart's content before building.

**Comment by tomasz1986** [comment]
It is a little ironic that something called "ungoogled" has its very first settings entry named "You and Google" though, isn't it? 😛

**Comment by PF4Public** [comment]
> first settings entry named "You and Google"

I imagine a good 1. April prank adding a patch, that replaces that with "You've been unGoogled!" :D

**Comment by kross-italk** [comment]
Good to know, thanks! I'm using it now.
