### ISSUE TITLE
Can't build because debian_sid_amd64-sysroot is missing

### ISSUE THREAD

**Issue by olodar** [Eloston/ungoogled-chromium#1846]
Hello! I trying to build ungoogled chromium on ubuntu 20.04 following [this intruction](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md) 
But on './out/Default/gn gen out/Default --fail-on-unused-args' step I'm getting error:
```
ERROR at //build/config/sysroot.gni:64:7: Assertion failed.
      assert(
      ^-----
Missing sysroot (//build/linux/debian_sid_amd64-sysroot). To fix, run: build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
See //build/config/sysroot.gni:65:11: 
          exec_script("//build/dir_exists.py",
          ^-----------------------------------
This is where it was set.
See //chrome/installer/BUILD.gn:8:1: whence it was imported.
import("//build/config/sysroot.gni")
^----------------------------------
See //BUILD.gn:82:5: which caused the file to be included.
    "//chrome/installer",
    ^-------------------
```
triend run build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
and it cannot download:
```
Installing Debian sid amd64 root image: /home/build/ungoogled-chromium/build/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.9oo91eapis.qjz9zk/chrome-linux-sysroot/toolchain/95051d95804a77144986255f534acb920cee375b/debian_sid_amd64_sysroot.tar.xz
Failed to download https://commondatastorage.9oo91eapis.qjz9zk/chrome-linux-sysroot/toolchain/95051d95804a77144986255f534acb920cee375b/debian_sid_amd64_sysroot.tar.xz

```

**Comment by ruamegatrader** [comment]
You need to change the URL from commondatastorage.9oo91eapis.qjz9zk to commondatastorage.googleapis.com for that to work

**Comment by olodar** [comment]
> You need to change the URL from commondatastorage.9oo91eapis.qjz9zk to commondatastorage.googleapis.com for that to work

Thanks! But now I'm getting another errror:

`/bin/sh: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: not found`

clang is installed on system.
