### ISSUE TITLE
[request] Enable installation on macOS using `brew cask`

### ISSUE THREAD

**Issue by sg-s** [Eloston/ungoogled-chromium#185]
Hi, 

installation on macOS would be much easier if I could

`brew cask install ungoogled-chromium`

Thanks!

**Comment by altblitz** [comment]
kys is much more simple for mac untermensch.

**Comment by altblitz** [comment]
Srinivas Gorur-Shandilya - poo in the loo now

**Comment by gplessis** [comment]
AFAIK, it's already available as `eloston-chromium`

**Comment by Eloston** [comment]
Huh, I wonder why they called it `eloston-chromium`. I only wrote less than half of the patches.

**Comment by sg-s** [comment]
> But you can't find the package by typing in ungoogled which sort of bugs me.

yes, my problem precisely.

**Comment by hovancik** [comment]
I guess small PR can change it (rename it). I can do it, or anyone, really.

**Comment by Eitot** [comment]
The Caskroom maintainers decided against that name when the cask was added, per https://github.com/caskroom/homebrew-cask/pull/24969#issuecomment-250848695.

**Comment by Eloston** [comment]
vitorgalvao has made fair points. In that case, I will just add a section to the README about it.

**Comment by dieideeistgut** [comment]
Sorry for replying on a closed issue but i found this is where it suits best. I somehow wonder why there's no way to build the 57 version on the mac. Maybe cask is the way to go here but many users don't have homebrew in favour of a different pkg-manager. I'd be really keen to know why currently there's no mac 57-option willing to spend some time on building this if possible without a strict requirement for homebrew (so free to chose brew, macports or nixpkg).

**Comment by lenormf** [comment]
You could try setting up an environment with [udocker](https://github.com/indigo-dc/udocker), and compile from there.

**Comment by Eloston** [comment]
@dieideeistgut There's no version 57 support for macOS yet because it hasn't been updated yet.

**Comment by dieideeistgut** [comment]
@Eloston is this why i can't generate matching buildfiles targetting `macos` as the process changed since the 55? Maybe i can help @9Morello out if he needs some helping hands doing the dirty-work?

**Comment by Eloston** [comment]
@dieideeistgut macOS support haven't been implemented in the build files generator yet, nor has any of the macOS-specific patches been updated yet.

I don't know if 9Morello needs help or not. You can ask by sending a One-to-One message on Gitter.

**Comment by 9Morello** [comment]
I would appreciate some help as I'm not going to have free time until after the next week.

@dieideeistgut If you want to make a personal build, you can use the scripts to build the source, apply the patches and domain substitution and build everything manually.

**Comment by dieideeistgut** [comment]
@9Morello i'll give it a shot during next week, let's see how far i'll come
