### ISSUE TITLE
Make systemd optional? 

### ISSUE THREAD

**Issue by Wastelander72** [Eloston/ungoogled-chromium#1852]
Hi, I apologize for kind of cross posting but I don't know which is the proper place to ask for this. I'm using an Arch-based distro without systemd, so I can't install the browser unless I use the "--assume-installed=systemd" option every time or download the binary and manually remove the dependancy from the list. Would it be possible to remove the dependancy or make it optional? The browser seems to work without issues even if systemd is not available, so it happens with Gentoo. Thanks in advance.

**Comment by networkException** [comment]
Closing in favor of https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/171
