### ISSUE TITLE
chrome://settings/content/cookies doesn't exist

### ISSUE THREAD

**Issue by rubenfonseca** [Eloston/ungoogled-chromium#1858]
**Describe the bug**
While following the FAQ, I want to disable the setting to "Clear cookies and site data when you quit Chromium". However, the `chrome://settings/content/cookies` setting doesn't exist on my Chromium.

**To Reproduce**
1. Go to `chrome://settings/content/cookies`
2. Got redirected to `chrome://settings`, with no option to set cookies

**Expected behavior**
I expected a screen where I could disable the setting to clear cookies when I quit Chromium.

**Environment (please complete the following information):**
 - OS/Platform and version: macOS Monterey 12.3
 - ungoogled-chromium version: Version 99.0.4844.51 (Official Build, ungoogled-chromium) (arm64)

**Comment by networkException** [comment]
The setting has moved to `chrome://settings/cookies` and is now called "Clear cookies and site data when you close all windows"

**Comment by networkException** [comment]
See https://github.com/ungoogled-software/ungoogled-chromium-wiki/pull/20

**Comment by rubenfonseca** [comment]
Found it! Thank you very much!
