### ISSUE TITLE
no install button in chrome web store

### ISSUE THREAD

**Issue by ebartaus** [Eloston/ungoogled-chromium#1866]
i have ungoogled chromium 97.0.4692.71 on x64 windows.
i google «deepl translate extension» and go to the [first link](https://chrome.google.com/webstore/detail/deepl-translate-beta-vers/cofdbpoegempjloogbagkncekinflcnj). this page should have an «install» button, but there is none:
![image](https://user-images.githubusercontent.com/72306717/159183586-1c0688de-162c-488b-bf2a-45c04facaec8.png)
this button is not on any page. (sorry for bad english)

**Comment by networkException** [comment]
See https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore
