### ISSUE TITLE
Built binary and libraries have the debug symbols unrequired

### ISSUE THREAD

**Issue by TCH68k** [Eloston/ungoogled-chromium#1869]
Are the debugging symbols enabled by default? How can i tell the process to build the binary and libraries without the debugging symbols? It takes up almost 80 GB of space to build it.

**Comment by TCH68k** [comment]
Hello? Anybody? It is really not possible to build without the debugging symbols?

**Comment by networkException** [comment]
What platform are you building on?

**Comment by networkException** [comment]
You might want to try setting `is_official_build` or `symbol_level` as in https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/3007ce01280d929ef60cd5d9e3262f2a39efbbc3/PKGBUILD#L171-L172.

Please note that supporting outdated versions of chromium is not a goal of this project and its highly recommended to always use the latest version as security vulnerabilities get discovered basically every release.

**Comment by networkException** [comment]
Those are the values the Arch Linux packages get built with. As the GitHub Actions runner doesn't run out of space at least something in the build instructions will result in debug symbols not getting included. `is_official_build` is my best at the moment, you would need to try

**Comment by networkException** [comment]
As it's currently set to `false` I would try `true` to see if it makes a difference

**Comment by PF4Public** [comment]
I usually build with `is_official_build=true`

**Comment by TCH68k** [comment]
All right guys, i'll try it with `is_official_build=true` and `symbol_level=0`. Thanks for the help.

**Comment by TCH68k** [comment]
Successfully built UGC 83 without debug symbols and the binary works perfectly too. Thanks again.
