### ISSUE TITLE
Are anti fingerprinting addons necessary with ungoogled?

### ISSUE THREAD

**Issue by aeon3** [Eloston/ungoogled-chromium#1871]
Coming from Chrome, I just wondering if thats something I need to worry about.

**Comment by networkException** [comment]
Depends on your threat model...

The patchset adds flags to mitigate fingerprinting somewhat, it doesn't come anywhere near something like tor browser for example though

**Comment by aeon3** [comment]
No, I mean comparing to regular chrome with fingerpriting addons, like these:

https://chrome.google.com/webstore/detail/canvas-fingerprint-defend/lanfdkkpgfjfdikkncbnojekcppdebfp
https://chrome.google.com/webstore/detail/webgl-fingerprint-defende/olnbjpaejebpnokblkepbphhembdicik
https://chrome.google.com/webstore/detail/audiocontext-fingerprint/pcbjiidheaempljdefbdplebgdgpjcbe

**Comment by networkException** [comment]
By default ungoogled-chromium does not have fingerprint prevention, it behaves more or less just like vanilla chromium

**Comment by aeon3** [comment]
Thank you! I'll proceed to install those addons then.

Hey do you know if there is a way or an addon to sync ungoogled bookmarks with mobile browsers?

**Comment by networkException** [comment]
Not that I know of at the moment, see #667
