### ISSUE TITLE
Secure DNS does not work with "use current provider"

### ISSUE THREAD

**Issue by g-k-m** [Eloston/ungoogled-chromium#1880]
- Works on Edge Version 99.0.1150.55 (Official build) (64-bit) (latest as of right now)
![image](https://user-images.githubusercontent.com/37273303/160874770-6ab77e2f-ae81-45a2-af32-be23916a3942.png)

- Works on Google Chrome Version 100.0.4896.60 (Official Build) (64-bit) (latest on Stable branch)
![image](https://user-images.githubusercontent.com/37273303/160875492-20c7c604-bf4f-4031-86ec-00cb0d54287f.png)

![image](https://user-images.githubusercontent.com/37273303/160875535-d82e0e3d-35de-4999-93b7-db93792a7201.png)

- Does not work on Ungoogled Chromium for Windows
![image](https://user-images.githubusercontent.com/37273303/160875598-66088eba-1f2b-484f-a544-dfdcb55ec09c.png) (latest version)

![image](https://user-images.githubusercontent.com/37273303/160875985-79c5af09-5b48-4bdd-b06d-c71dc19d82b2.png)
![image](https://user-images.githubusercontent.com/37273303/160876062-b2c874f7-d7ff-4664-aea7-7a382a8155af.png)

Test link - https://www.cloudflare.com/ssl/encrypted-sni/
another link to test - https://1.1.1.1/help

Only works if you manually set the Secure DNS provider to Cloudflare like this 
![image](https://user-images.githubusercontent.com/37273303/160876159-a58bdace-d39c-4ed5-8d91-5106e15a618c.png)

Does not work when using "With your current service provider" like it does in Edge or Chrome

It is thus a problem with ungoogled chromium

I also have both of these enabled and yet it does not work
![image](https://user-images.githubusercontent.com/37273303/160876925-8a85bcbc-91ec-431f-a59d-548aa7fe50f9.png)

I am not using ungoogled-chromium-windows build, which is why i post here

**Comment by g-k-m** [comment]
Forgot to mention, i am using this build https://github.com/macchrome/winchrome/releases (shouldn't matter tho?)

**Comment by tomasz1986** [comment]
This isn't working for me on vanilla Chromium as well, so I'd guess the problem itself may not be related to the "ungoogled" variant at all.

**Comment by PF4Public** [comment]
> Forgot to mention, i am using this build https://github.com/macchrome/winchrome/releases (shouldn't matter tho?)

We cannot provide support for third-party binaries. Sorry. File the issue there.
