### ISSUE TITLE
Unable to connect to any site

### ISSUE THREAD

**Issue by Flashwalker** [Eloston/ungoogled-chromium#1881]
**Describe the bug**
After update from version 90.0.4430.212 to version 95.0.4638.54 from OBS PPA, browser is unable to connect to any site. Just nothing happens during infinite loading progress.
I noticed the removal of these packages during the update: 
ungoogled-chromium-common_90.0.4430.212-1.focal1_amd64.deb  
ungoogled-chromium-driver_90.0.4430.212-1.focal1_amd64.deb  
ungoogled-chromium-l10n_90.0.4430.212-1.focal1_all.deb  
ungoogled-chromium-sandbox_90.0.4430.212-1.focal1_amd64.deb  
ungoogled-chromium-shell_90.0.4430.212-1.focal1_amd64.deb  

But there is no builds of them in version 95.

**To Reproduce**
1. Update to version 95 from OBS PPA
2. Run browser
3. Try to open any site

**Expected behavior**
Load site

**Screenshots**
white-screen.jpg

**Environment (please complete the following information):**
 - OS: Ubuntu Focal 20.04 x64
 - ungoogled-chromium version: 95

**Comment by networkException** [comment]
See https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/255

**Comment by Flashwalker** [comment]
Thanks
