### ISSUE TITLE
Disable ungoogled-chromium address bar search autocomplete

### ISSUE THREAD

**Issue by zeronegithub** [Eloston/ungoogled-chromium#1885]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when searching in the address bar

**Describe the solution you'd like**
Disable ungoogled-chromium address bar search autocomplete and suggestion.

**Describe alternatives you've considered**
Brave Browser (_Show autocomplete in address bar_)
`brave://settings/appearance`

**Additional context**
[https://i.imgur.com/kIKcRAc.png](https://i.imgur.com/kIKcRAc.png)

**Comment by Nifury** [comment]
And probably this option:
`chrome://settings/syncSetup`

**Comment by zeronegithub** [comment]
> Try setting chrome://flags/#omnibox-autocomplete-filtering to `Search suggestions only`

Oh, great! Glad that worked. Thank you
