### ISSUE TITLE
password : no proposition to record

### ISSUE THREAD

**Issue by Quetzaal** [Eloston/ungoogled-chromium#1889]
windows10 and windows7
ungoogled  100.0.4896.60

**Describe the bug**
- proposition to record password do not appears(fail) on win10
- but appears(works) on win7 (same version of ungoogled)

**To Reproduce**
difficult to reproduce... caus', simply it do not propose to record passwords

**Expected behavior**
expected ungoogled to propose to save password on win10 as it do with win7

**Screenshots**
nothing happened, then no screeenshot

**Environment (please complete the following information):**
 - **OS/Platform and version:** win10 & win7
 - **ungoogled-chromium version:**  100.0.4896.60

**Additional context**
nothing particuliar, the extension context is quite the same on win10 and win7

**Comment by Quetzaal** [comment]
... vanilla chromium ? no... just have dowload th e last feature of ungoogled, it was working before, but i have reinstalled this version from scratch. i've get off my precedent config in app/data... 

saying that, may i should comme back to an older version before to re-implement this one... 

thanks a lot for your help

**Comment by PF4Public** [comment]
> * and upgrade 85 with ungoogled 100
> * and the password utility is present again and works perfectly

Does it work or not?

**Comment by Quetzaal** [comment]
... "and works perfectly" ? 
- this sentence is insuffisant to describe the behaviour of this new ungoogled 100 ? 
- may my first installation of 100 been "difficult" and provocate this weird behaviour, who knows

**Comment by PF4Public** [comment]
I assume this is a no-issue then.
Closing this issue for now.
