### ISSUE TITLE
Target OS X 10.8 and lower

### ISSUE THREAD

**Issue by 1-61803** [Eloston/ungoogled-chromium#189]
There's still people out there using older versions of OS X that need a usable browser that doesn't call home, but cannot / don't want to upgrade their whole system and break their workflows, or for whatever reason.

Or, at least, please provide some instructions or hints to compile it.

**Comment by Eloston** [comment]
It might work because version 55 (and 56 I believe) are building on an old macOS version I think. Do the binaries that are published work on those versions?

**Comment by 1-61803** [comment]
`55.0.2883-75-1` doesn't launch, even with `Info.plist` set to `10.8`
`53.0.2785.116-1.2` launches with `Info.plist` set to `10.8`, UI quirky
`51.0.2704.106-3` launches with `Info.plist` set to `10.8`, UI somewhat quirky

I've seen this with other applications, mostly due to new UI assets since 10.9. It should compile if targeted to 10.8 or lower.

**Comment by nopjmp** [comment]
Targeting anything before 10.8 is bad. Chrome doesn't support it anymore and there are no security updates for those operating systems.

I highly suggest those users get a new PC, if they want to use a computer for multiple years without worrying, they should stick with non-Apple devices. I don't feel like we should be bending over backwards for users of "EOL" operating systems.

**Comment by Eloston** [comment]
[I hadn't realized Google no longer supports 10.8 and lower](https://support.google.com/chrome/answer/95346).

In that case, I will not personally support this. I do not know how much work is involved in figuring any of this out, and there are other more important tasks to attend to. However, as usual, I will allow contributions of instructions or code to make this work.

**Comment by 1-61803** [comment]
That Google doesn't support ≤10.8 (is this still `ungoogled-chromium`, right?) and that Apple also dropped it, doesn't mean you also have to jump in the same bandwagon.

You are already building it for 10.9. If you target 10.8 I'll be happy to test it.

**Comment by nopjmp** [comment]
Google is upstream. They are now using APIs that are not in 10.8 (at least sanely). I don’t know what they are off the top of my head, but I build cef for another project which is where my experience comes from.


On February 26, 2017 at 2:18:04 PM, 1-61803 (notifications@github.com) wrote:

That Google doesn't support ≤10.8 (is this still ungoogled-chromium, right?) and that Apple also dropped it, doesn't mean you also have to jump in the same bandwagon.

You are already building it for 10.9. If you target 10.8 I'll be happy to test it.

**Comment by Eloston** [comment]
> That Google doesn't support ≤10.8 (is this still `ungoogled-chromium`, right?)

Yes. Generally, the set of all versions that Google Chrome supports is equal to that of Chromium.

> You are already building it for 10.9. If you target 10.8

One reason that Google dropped support for Windows XP was becauase it lacked system-provided security features that newer Windows versions have. There could be a similar- nevermind, @nojmp beat me to it.

Also, I'm not sure if there's a simple switch to target 10.8 or older. Even if it was easy, you may run into issues that @nojmp described.

**Comment by 1-61803** [comment]
@nopjmp, in my experience problems arose between 10.8 and 10.9 with new UI assets in such generic applications, no special APIs — after all, it's just a browser.

**Comment by 1-61803** [comment]
@Eloston, could you ask @9Morello to target 10.8? The switch is a couple of clicks away, build and wait.

**Comment by Eloston** [comment]
> after all, it's just a browser.

That's what I thought at first too. But, the modern web browser isn't some simple file-rendering application like the old days. It's essentially an application runner. Just consider the new technologies like WebRTC, WebAssembly, WebGL, WebUSB, Web Bluetooth, WebVR, HTML5, CSS3, APIs to access speakers, play video, use the microphone, use your webcam, and all of the new ECMAScript features coming out. And those are just the developing web standards that all modern web browsers are supposed to support; I haven't considered non-standard technologies like Native Client or Widevine.

Also, I believe Chromium takes as long (or longer) to compile than the Linux kernel.

> could you ask @9Morello to target 10.8? The switch is a couple of clicks away, build and wait.

I will let @9Morello or anyone else make that choice on their own. Plus, I'm not sure how this would be done; could you elaborate?

**Comment by nopjmp** [comment]
They mainly changed the compiler flags and used clang instead of GCC in 10.9.

Sent from my android device.

-----Original Message-----

**Comment by Eloston** [comment]
> They mainly changed the compiler flags and used clang instead of GCC in 10.9.

Are the flags backwards-compatible? Does clang work in pre-10.9 systems?

**Comment by nopjmp** [comment]
There is a flag to switch the target. I forget where it is.

Sent from my android device.

-----Original Message-----

**Comment by nopjmp** [comment]
The flags I'm speaking of are just the default Apple compiler flags.

Sent from my android device.

-----Original Message-----

**Comment by 1-61803** [comment]
@Eloston, change `MACOSX_DEPLOYMENT_TARGET` to 10.8, build and wait. I would ask @9Morello myself, had I a means to contact him. **If** no new APIs or other new shiny standards **were** in the way, why not target lower systems? And in any case, why not give it a shot, even as unsupported build?

**Comment by nopjmp** [comment]
Because this would have to change the target over to clang instead of GCC manually. You can already modify the plist file to make it run on an older macOS version. The chromium build system is the one that changes the target and will override any environment flag you set.

You can find the appropriate GN config flag, install xcode and dependencies and build ungoogled-chromium yourself. No one is stopping someone else from making this work.

**Comment by Eloston** [comment]
> change MACOSX_DEPLOYMENT_TARGET to 10.8

~Unfortunately, I don't know the GN flag where global environment variables can be specified (that won't be overridden by other parts of the GN config). It would be better to have a GN-specific flag for this.~ Nevermind, see the post above.

> I would ask @9Morello myself, had I a means to contact him

I believe 9Morello has notifications enabled, so this should not be a problem.

**Comment by 1-61803** [comment]
> I believe 9Morello has notifications enabled, so this should not be a problem.

I don't know what you mean by that.

**Comment by Eloston** [comment]
Every time you use `@` followed by a username, an email notification and/or other forms of notification are sent to the corresponding person.

**Comment by 9Morello** [comment]
I could test if it builds targetting OS X 10.8, but for the reasons @nopjmp pointed out I doubt it will work just by changing a flag. I searched a bit and it seems some people hacked Chrome v52 to work on ML, while v54 doesn´t even launch.
I suggest upgrading to a newer OS X version if you can, as 10.8's support ended in 2015 and it won't receive security updates anymore.

**Comment by 1-61803** [comment]
@9Morello, thanks for that. I guess you mean [this post](http://apple.stackexchange.com/questions/237271/is-there-a-google-chrome-version-50-supporting-mac-os-10-8-5/). Let me know if you build it for 10.8 and I'll be more than happy to test it.

**Comment by 1-61803** [comment]
@9Morello, did you have a chance to compile it for `10.8` or lower?

Of all the Chromium variants I checked this is the only one, at least in the couple of hours I informally tested, that doesn't unilaterally start to chatter with Almighty Google or, for that matter, any other third party. [Iridium](https://iridiumbrowser.de/), [Iron](http://www.srware.net/software_srware_iron.php), [Epic](https://www.epicbrowser.com/index.html) — all of them leak.

This one (v51) is the best.

**Comment by 9Morello** [comment]
@1-61803 I decided not to do it. Feel free to test it yourself if it works.

**Comment by 1-61803** [comment]
@9Morello, could you provide instructions for your current build? The documentation hasn't been updated yet.
