### ISSUE TITLE
I can't use Spotify Web Player

### ISSUE THREAD

**Issue by mytsrgit** [Eloston/ungoogled-chromium#1890]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version:
 - ungoogled-chromium version:

**Additional context**

**Comment by PF4Public** [comment]
https://github.com/Eloston/ungoogled-chromium/issues?q=is%3Aissue+spotify
