### ISSUE TITLE
buggy patches  

### ISSUE THREAD

**Issue by Alvintrmp** [Eloston/ungoogled-chromium#19]
i am making some test and i found some bugs

1 clear-http-auth-cache-menu-item.patch         
http://gpaste.us/f82eedc5

2 disable-google-host-detection.patch 

http://gpaste.us/352fe25d

3 disable-profile-avatar-downloading.patch

issue:   edits a file modified by another patch,  for them quilt cancels the compilation,  i suggest merge its content at all-add-trk-prefixes-to-possibly-evil-connections.patch           

4  i found a very nice set of modifications "attempts to make compatible these patches for chromium  51"    is "crappy"  but renames patch_order to series   

https://up1.ca/#3GVxlmnNWEjzfLCsPNNYWQ

you could use this attempt  and test it

**Comment by perfect7gentleman** [comment]
what do you mean 'buggy' ? they can't be applied or the patches themselves are bad ?

**Comment by Eloston** [comment]
They applied just fine when I committed them for version 51.0.2704.81. Though some of them don't have the correct offsets and have some fuzz (which quilt could deal with just fine). I never had the issue you described with quilt. What Debian version are you using? I'm guessing you're using the debian directory provided by this project?

**Comment by Eloston** [comment]
New version is out. Please see the new README for building. Let me know if this doesn't fix the issue.
