### ISSUE TITLE
Ubuntu 16.04 .deb builds of 55.0.2883.95-1 failing to install

### ISSUE THREAD

**Issue by pr0ggy** [Eloston/ungoogled-chromium#191]
When attempting to install the 16.04 deb from [this page](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/ubuntu/xenial_amd64/55.0.2883.95-1), receiving the following dependency errors:

```
----@-----:~/Downloads$ sudo dpkg -i chromium_55.0.2883.95-1_amd64.deb
Selecting previously unselected package chromium.
(Reading database ... 210797 files and directories currently installed.)
Preparing to unpack chromium_55.0.2883.95-1_amd64.deb ...
Unpacking chromium (55.0.2883.95-1) ...
dpkg: dependency problems prevent configuration of chromium:
 chromium depends on libavcodec57 (>= 7:3.2.2) | libavcodec-extra57 (>= 7:3.2.2); however:
  Package libavcodec57 is not installed.
  Package libavcodec-extra57 is not installed.
 chromium depends on libavformat57 (>= 7:3.2.2); however:
  Package libavformat57 is not installed.
 chromium depends on libavutil55 (>= 7:3.2.2); however:
  Package libavutil55 is not installed.
 chromium depends on libminizip1 (>= 1.1); however:
  Package libminizip1 is not installed.
 chromium depends on libre2-1v5 (>= 20151101+dfsg); however:
  Package libre2-1v5 is not installed.
 chromium depends on libwebpdemux1 (>= 0.4.3); however:
  Package libwebpdemux1 is not installed.

dpkg: error processing package chromium (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 chromium
```

The following libs don't appear to be available in the standard Xenial repos:

- `libavcodec57` or `libavcodec-extra57`
- `libavformat57`
- `libavutil55`

Any thoughts?  Appreciate the assistance!

**Comment by 9Morello** [comment]
What is your ffmpeg version?

**Comment by pr0ggy** [comment]
`7:2.8.11-0ubuntu0.16.04.1`

**Comment by 9Morello** [comment]
Do this:

```
sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
sudo apt-get update

sudo apt-get install -y debhelper ninja-build python-jinja2 flex yasm xvfb wdiff gperf bison valgrind libglew-dev libgl1-mesa-dev libglu1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev mesa-common-dev libxt-dev libre2-dev libgbm-dev libpng-dev libxss-dev libelf-dev libvpx-dev libpci-dev libcap-dev libdrm-dev libicu-dev libffi-dev libkrb5-dev libexif-dev libflac-dev libudev-dev libopus-dev libwebp-dev libxtst-dev libsrtp-dev libjpeg-dev libxml2-dev libgtk2.0-dev libxslt1-dev libpulse-dev libpam0g-dev libsnappy-dev libgconf2-dev libavutil-dev libavcodec-dev libavformat-dev libglib2.0-dev libasound2-dev libsqlite3-dev libjsoncpp-dev libspeechd-dev libminizip-dev libhunspell-dev libharfbuzz-dev libusb-1.0-0-dev ffmpeg libmodpbase64-dev libgnome-keyring-dev libnss3-dev libnspr4-dev libcups2-dev libevent-dev libjs-excanvas libjs-jquery-flot libgcrypt20-dev quilt build-essential
```

then try to install again.

**Comment by pr0ggy** [comment]
After running the above commands, the package installs correctly, but any attempt to navigate results in [this error](https://i.imgur.com/YlfRsJ0.png)

**Comment by 9Morello** [comment]
Are you running the packages in a VM?

**Comment by pr0ggy** [comment]
Negative, native install

**Comment by 9Morello** [comment]
Then I'll have to investigate further. You're not the first one reporting this problem, and I don't know what is causing it.

The packages you downloaded are not the same packages I uploaded before (those are from a slighty newer version). I don't have the older versions anymore, so if this one is broken for you, unfortunately  you'll have to wait for v56 or build yourself (and see if it works).

**Comment by pr0ggy** [comment]
No problem at all...let me know if there's anything I can do to help, will do what I can

**Comment by 9Morello** [comment]
@pr0ggy Are you using a NVIDIA graphics card?

**Comment by pr0ggy** [comment]
Yes, GTX1060. Driver `367.57`

**Comment by 9Morello** [comment]
Ok, I've found the problem. The shipped version of `harfbuzz` in Ubuntu 16.04 is too old, and it produces broken Chromium packages. Building it with a >1.2 `harfbuzz` package solves the problem. I probably built the working packages in a VM which had a PPA with a newer harfbuzz packager.

I have new, working binaries, but I can't upload them now. If you don't mind waiting, you can build them yourself ([this PPA](https://launchpad.net/~jonathonf/+archive/ubuntu/font-rendering) has a harfbuzz package that is new enough).

**Comment by pr0ggy** [comment]
Awesome, I can just wait for the new binaries...thanks again!

**Comment by 9Morello** [comment]
[link](https://github.com/9Morello/ungoogled-chromium-binaries/releases/tag/55.0.2883.87)

**Comment by Eloston** [comment]
Closing since new binaries were posted. Let us know if there are still issues.
