### ISSUE TITLE
Widevine

### ISSUE THREAD

**Issue by 89z** [Eloston/ungoogled-chromium#1913]
If I go here:

https://integration.widevine.com/player

I get this:

~~~
Player Error
category: 6
code: 6001
data:
[]
~~~

**Comment by alienbob** [comment]
Works for me (ungoogled chromium 100.0.4896.127 on Slackware 64bit).

**Comment by networkException** [comment]
Please note that widevine does not work out of the box (see the FAQ). For further issues see #1831
