### ISSUE TITLE
Ubuntu 20.04: version 100.0.4896.127-1.1.AppImage

### ISSUE THREAD

**Issue by wapster** [Eloston/ungoogled-chromium#1914]
Hello.
This is my first appeal, so do not judge strictly :)
I run version 100.0.4896.127-1.1.App Image in the console, I get an error:
```
/tmp/.mount_ungoogE58Do5/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libxkbcommon.so.0: version `V_1.0.0' not found (required by /tmp/.mount_ungoogE58Do5/opt/google/chrome/chrome)
```

##### package version
```
`$ sudo apt show libxkbcommon0`
Package: libxkbcommon0
Version: 0.10.0-1
Priority: optional
Section: libs
Source: libxkbcommon
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 288 kB
Depends: xkb-data, libc6 (>= 2.17)
Homepage: http://www.xkbcommon.org/
Task: ubuntu-desktop-minimal, ubuntu-desktop, kubuntu-desktop, xubuntu-core, xubuntu-desktop, lubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop
Download-Size: 98,4 kB
APT-Manual-Installed: no
APT-Sources: http://ru.archive.ubuntu.com/ubuntu focal/main amd64 Packages
Description: library interface to the XKB compiler - shared library
 This package provides a library to handle keyboard descriptions, including
 loading them from disk, parsing them and handling their state. It's mainly
 meant for client toolkits, window systems, and other system applications;
 currently that includes Wayland, kmscon, GTK+, Clutter, and more.
 .
 More information about X.Org can be found at:
 <URL:http://www.X.org>
 .
 This module can be found at
 https://github.com/xkbcommon/libxkbcommon.git
```

Tell me what to do? How do I launch a new version?

**Comment by networkException** [comment]
@clickot Do you know anything about this?

**Comment by clickot** [comment]
Hello @wapster, i ran the image on an ubuntu 21.10 and 22.04 without problems. Have you tried to use the tar.xz version? What linux distro do you use?

**Comment by marek141017** [comment]
Hello
All versions since 100 have the same issue on 20.04. Even portable one, which supposed to work on any Linux distro.

**Comment by clickot** [comment]
Hello, since I only execute the existing build procedure from ungoogled-chromium-portable (more or less) , I do not know how to fix this issue.
Sorry
Clickot

**Comment by wapster** [comment]
Привет.
В новой версии 101.0.4951.41 данной проблемы нет.
Буду использовать ее.
Спасибо за обратную связь. 

Удачи в разработке и поддержке проекта!

**Comment by marek141017** [comment]
Yes, library issue was fixed
But at least 2 others appered: 1. they remove themes support for incognito. 2. Most important: dropdown menu width doesnt reflect css, as a result I found few web sites where dropdown width was 15px, instead of 60.
This vertion is unusable.
