### ISSUE TITLE
Windows 10: 100.0.4896.60-1.1 Installer x-64 Not Installing

### ISSUE THREAD

**Issue by branc-8** [Eloston/ungoogled-chromium#1915]
On windows 10, I download the installer for the recommended I run the installer and all it does is create a CR_(varying hex number).tmp folder that contains "setup.exe" and CHROME.PACKED in the same folder with no installation process occurring and the folder quickly disappears. I then read on the readme:
"NOTE: These binaries are provided by anyone who are willing to build and submit them. Because these binaries are not necessarily [reproducible](https://reproducible-builds.org/), authenticity cannot be guaranteed; In other words, there is always a non-zero probability that these binaries may have been tampered with. In the unlikely event that this has happened to you, please [report it in a new issue](https://github.com/Eloston/ungoogled-chromium#contributing-reporting-contacting)." 
So, after looking for a similar issue and not seeing it, along with concern I am posting this issue.

The result I expected was for an installer to run and install the program.

**Comment by networkException** [comment]
The installer works for me. @Nifury do you know anything about this?

**Comment by tomasz1986** [comment]
If you mean the installers from https://github.com/Nifury/ungoogled-chromium-binaries/releases, then I can confirm that they do work. The program should be installed to `%LOCALAPPDATA%\Chromium`. I would check first whether your antivirus solution (if you use any) hasn't blocked the installer in the middle of the extraction or something.

**Comment by networkException** [comment]
Nifury submitted the installer to https://ungoogled-software.github.io/ungoogled-chromium-binaries/, thats why I'm asking

**Comment by branc-8** [comment]
I can happily confirm after reading these responses that it was a problem on my end. I think the issue was a conflict with a previously installed version of vanilla chromium. As soon as I run the installer after uninstalling the browser immediately pops up. Thank you all for your feedback.

**Comment by networkException** [comment]
Alright great!
