### ISSUE TITLE
Hide extension button from toolbar

### ISSUE THREAD

**Issue by zeref-dragneel** [Eloston/ungoogled-chromium#1916]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is: 
- Extensions button

**Describe the solution you'd like**
- Extensions button > Never show

**Describe alternatives you've considered**
- Edge `edge://settings/appearance` > Extensions button > Never show

**Additional context**

**Comment by networkException** [comment]
What?

**Comment by zeref-dragneel** [comment]
> What?


![image](https://user-images.githubusercontent.com/95934994/163718494-7178801b-9226-46ea-b2d2-700807b07fe1.png)

**Comment by networkException** [comment]
Please provide a clear description of the feature request.

**Comment by zeref-dragneel** [comment]
> Please provide a clear description of the feature request.

Hide extension button from toolbar
![image](https://user-images.githubusercontent.com/95934994/163719787-114fda16-d2e1-463c-a3db-985aefbf7fd5.png)

**Comment by PF4Public** [comment]
Closing this issue in favour of #1336
