### ISSUE TITLE
Cannot launch chromium because it is doing something in the background.

### ISSUE THREAD

**Issue by Game-01** [Eloston/ungoogled-chromium#1917]
Platform - Win11 Pro v21H2 (x64)
ungoogled-chromium - Version 100.0.4896.60 (Developer Build, ungoogled-chromium) (64-bit)

# Cannot open chromium
--First time writing an issue so bare me--

After opening and closing chromium a few times (3-4 times) I was unable to launch it. I open task manager and find out
that chromium was running in the background even though I have no window opened. It it when I kill the task
from task manager I was able to launch it again.
I tried doing it multiple times to see if it would happen again and it happened every time.

### Cannot launch it because it is doing something in the background, I can launch it again only when the background processes ends or I manually kill the task.
![back_running](https://user-images.githubusercontent.com/85191430/163729067-d69bd02b-41c5-42ba-922e-834560518961.png)

**Comment by j-james** [comment]
I get this issue sometimes when manually closing a crashed session. I don't think it's an Ungoogled-Chromium bug, it's probably a Chromium bug (if a bug at all). You should be able to fix it by simply force quitting and relaunching.

For the future - try reproducing it in Chromium to make sure it's specifically an Ungoogled Chromium bug.

**Comment by networkException** [comment]
Yep please verify that this is in fact not an upstream issue, in which case the ungoogled-chromium-windows repository would be more fitting.

(as it's not possible to move the issue I think it's fine to keep it here for now even though this is quite evidently not a problem with the patchset)

**Comment by Nifury** [comment]
Can confirm that this issue has been around for quite some time (https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/101).
It's highly likely that the issue only exists in ungoogled-chromium-windows. I've never experienced this in vanilla Chromium.

**Comment by PF4Public** [comment]
Closing this issue in favour of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/101
