### ISSUE TITLE
Can't disable clear-data-on-exit

### ISSUE THREAD

**Issue by bluebad** [Eloston/ungoogled-chromium#1924]
First I open chrome://flags/#clear-data-on-exit, then disable the feature, browser relaunch. I login in some website, then close browser  and open it again, the account of the website not in login state. 
version: ungoogled-chromium_100.0.4896.60-1.1_installer-x64.exe
system: windows 10

**Comment by Ahrotahn** [comment]
Do you have "Clear cookies and site data when you close all windows" enabled in `chrome://settings/cookies`?

**Comment by bluebad** [comment]
> Do you have "Clear cookies and site data when you close all windows" enabled in `chrome://settings/cookies`?

Sorry, my mistake. After I do that setting above, things go on right way.
