### ISSUE TITLE
Can not login to wellsfargo.com

### ISSUE THREAD

**Issue by guido99** [Eloston/ungoogled-chromium#1927]
Eloston/ungoogled-chrome
Google-Chrome

Release 100.0.4836.127

Cannot login to wellsfargo.com

Enter username, password, & click submit button. Screen redraws. The username & password fields are cleared prompting for input again. No error messages. Perusal of the chrome_debug.log after starting with command line options --enable-logging --v=1 shows no obvious issue (novice speaking here).

Normal expected mode. Fill login data & click submit leads to 2factor-verification prompt screen.

Observed on Lenovo P15 with Fedora 35, Slackware linux 15.0 (separate partitions) and on a Lenovo X390 running Fedora 36 in Gnome 42 GUI. With this same hardware, Firefox 91.8 & 99.0 function flawlessly; Fedora 35 Chromium 93.0.4577.63 also behaves properly.

Curiously, no problem on my Motorola Android cell phone using this release!

All earlier releases prior to 100...127 worked fine.

**Comment by guido99** [comment]
Error: I meant rel 100.0.4896.127.

**Comment by networkException** [comment]
Note: It is very difficult to debug a problem on websites that require authorization, a payed subscription or similar, as its unlikely that a ungoogled-chromium maintainer has access to the service as well.

Can you check that vanilla chromium with the same version on the same system that you are experiencing the error on does not have the issue as well?

**Comment by tomasz1986** [comment]
From my experience, these kind of problems are usually caused by blocking of 3rd party cookies, which Ungoogled Chromium does by default, while vanilla Chromium does not.

Compare the default settings in Ungoogled Chromium:

![image](https://user-images.githubusercontent.com/5626656/164945684-f7a3496c-2657-4c28-a2fb-0d45248dac21.png)

versus the default settings in vanilla Chromium:

![image](https://user-images.githubusercontent.com/5626656/164945697-3a5cdd37-9b97-4701-a772-5d4ee4f58a7d.png)

Vanilla Chromium blocks 3rd party cookies in Incognito only, while Ungoogled Chromium does it universally. I've experienced problems myself, e.g. with banking or shopping sites, and the only solution was to allow all cookies.

**Comment by guido99** [comment]
"Vanilla Chromium blocks 3rd party cookies ..."

I always use Allow all cookies.

I have "fiddled" with numerous security & privacy site-settings; nothing works!

**Comment by guido99** [comment]
"Note: It is very difficult to debug a problem on websites that require authorization..."

I'm well aware of that. WFB is a big bank. Maybe a GitHub developer has an account.

"Can you check that vanilla chromium with the same version on the same system that you are experiencing the error on does not have the issue as well?"

The fault appears on vanilla chromium of same rel. Anything earlier is OK. This just appeared when 127 was available.

**Comment by PF4Public** [comment]
It could be helpful to investigate the Developer console.

**Comment by guido99** [comment]
![xss](https://user-images.githubusercontent.com/34629286/164947395-df5d11d2-933b-4bfe-a17f-e52a694c6c6e.jpg)

After failing login, this is screenshot from developer tools. dectector-dom-min.js. Something is not being authenticated.

**Comment by PF4Public** [comment]
Look into "Console". There might be some errors.

**Comment by guido99** [comment]
![xss](https://user-images.githubusercontent.com/34629286/164947760-6d072ae7-de0e-43e8-bbbd-b50452c7284f.jpg)

Console output. Click on sources gives screenshot I show previously.

**Comment by guido99** [comment]
![xss](https://user-images.githubusercontent.com/34629286/164947865-65c4b594-1e0e-4860-b607-7beb91fd5974.jpg)

More data of same as above on 4 issues.

**Comment by guido99** [comment]
Logged on to troubled URL with firefox. Disabled 2 factor auth. Logged in with ungoogled-chrome! Activated 2 factor auth. Tested. All is well! Why? (We'll likely never know.)
