### ISSUE TITLE
I can't set Ungoogled-Chromium as default browser

### ISSUE THREAD

**Issue by nettlebay** [Eloston/ungoogled-chromium#1929]
Hi,
I can't set Ungoogled-Chromium (Flatpack) as default browser in Linux Manjaro XFCE4.
The command :
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chromium --file-forwarding com.github.Eloston.UngoogledChromium @@u %U @@`
desn't work.

**Comment by mpaunovic** [comment]
Run the following in your terminal:

xdg-settings set default-web-browser com.github.Eloston.UngoogledChromium.desktop

**Comment by nettlebay** [comment]
Thank you. I have re-installed the AUR version witch works well. But there are other issues like Google translate apps not working.

Patrice Airiau
***@***.***

Envoyé avec la messagerie sécurisée [ProtonMail](https://protonmail.com/).

------- Original Message -------

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by mohammadmansour200** [comment]
if @mpaunovic  's command won't work try out this one:
```shell
xdg-settings get default-web-browser io.github.ungoogled_software.ungoogled_chromium.desktop
```
