### ISSUE TITLE
Icons do not work for application shortcuts

### ISSUE THREAD

**Issue by Tiger862000** [Eloston/ungoogled-chromium#1937]
**Describe the bug**
When I create a shortcut from a webpage for it to be treated as an app on my desktop the apps (PWAs) do not have icons. I only see a system system "gear" icon (See screenshot below). But when I go to chrome://apps/ I see all the apps created and the correct icon (see screenshot below). Seems the icon support on the desktop is broken in the flatpak version.

**To Reproduce**
1. Go to any specific webpage of your choise that you want to create a shortcut from. e.g. https://www.timeanddate.com/worldclock/converter.html
2. Click on the "three dots", then click on "more tools" and then click "create shortcut..."
3. Check mark the box "Open in new window"
4. Close the "new app"
5. Search for the just created app in your desktop apps menu

**Expected behavior**
Shortcut icons are shown correctly in the desktop app menu. They are created and stored from the embedded webpage icons, but somehow the browser does not point correctly to them. I located them here: /home/user/.local/share/icons/hicolor/128x128/apps

**Screenshots**
![image](https://user-images.githubusercontent.com/12417480/166421688-afa62795-bf23-49f1-91f6-3c8af4745314.png)
![image](https://user-images.githubusercontent.com/12417480/166423506-f18c7b1c-dc6f-42ec-9dfb-5019c1ac7702.png)

**Environment (please complete the following information):**
 - OS/Platform and version: ZorinOS 16
 - ungoogled-chromium version: Version 101.0.4951.41

**Additional context**
I thought I found a fix explained on these two pages, but they did not work for me: https://www.reddit.com/r/flatpak/comments/ju4wna/chrome_chromium_flatpak_apps_now_support_creating/
https://forum.zorin.com/t/how-to-make-shortcuts-to-websites-with-icons/16003

**Comment by Tiger862000** [comment]
@PF4Public is there something I can do apart from issuing the topic? Could you reproduce it?

**Comment by PF4Public** [comment]
Have you tried non-flatpak install? Have you tried vanilla Chromium?

**Comment by Tiger862000** [comment]
I just tried with DEB version from this repo (deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/).
It worked like a charm, icons are created as they should. Tried with two new different websites.
But you know what's fascinating, now the icons also work for the older shortcuts on flatpak version. 
What is happening here?

**Comment by PF4Public** [comment]
I suppose, nothing we can do about flatpak misbehaving 🤷

**Comment by Tiger862000** [comment]
What do you mean "WE" cannot do anything about it? The maintainer of the flatpak version may look into that. 

Back to my discovery: "when installing DEB version alsonside flatpak version the icons also work for the older shortcuts on flatpak version" I figured when I uninstall the DEB version again then the new shortcuts created do not have icons again. :-/

**Comment by networkException** [comment]
"We" as in the maintainers of the ungoogled-chromium patchset.

Please file an issue in https://github.com/flathub/com.github.Eloston.UngoogledChromium
