### ISSUE TITLE
i delete the post because of the lies and rudeness of one of the members who must be excluded

### ISSUE THREAD

**Issue by trimechee** [Eloston/ungoogled-chromium#1939]
certains sont très malpolis ici, j'efface mon post

**Comment by networkException** [comment]
Please do not spam our issue tracker.

**Comment by trimechee** [comment]
@networkException please be polite and respectful, you seriously insulted and disrespected me so i came up with some big sensational additions to chromium and came up with the means to do it, other than you liked my suggestions and c it's my right to offer suggestions, nothing prohibits it, so delete your vexing defamatory liar comment and apologize, lol i have wirteen million of post to call this spam? you're the spammer, you have nothing better to do than comment on my suggestions? I'm going to file a complaint against you, delete your tweet and apologize, lol i have wirteen million of post to call this spam?!!! you are a shame,  you're the spammer, you have nothing better to do than comment on my suggestions?!!! I will file a complaint against you, delete your tweet and preset your sincere excuse

**Comment by networkException** [comment]
![image](https://user-images.githubusercontent.com/42888162/166744098-5324a6bf-7c26-4d1b-8b2f-454074c005eb.png)

**Comment by trimechee** [comment]
I don't want to argue, there was a misunderstanding because I forgot to delete my original post, and noble PF4Public calmed things down and ended this misunderstanding, so @networkException if you delete your first comment , I also delete my comments where I am angry and we forget all that....

**Comment by trimechee** [comment]
@networkException , are you Eleston ?
