### ISSUE TITLE
Missing dependency as of latest update to libdav1d.so.5 going from .5 to .6

### ISSUE THREAD

**Issue by LethalManBoob** [Eloston/ungoogled-chromium#1948]
/usr/lib/chromium/chromium: error while loading shared libraries: libdav1d.so.5: cannot open shared object file: No such file or directory

**Comment by networkException** [comment]
What platform is this on?

**Comment by LethalManBoob** [comment]
Archlinux.

**Comment by networkException** [comment]
hm weird, my build launches fine even with `dav1d 1.0.0-1`. Maybe try installing from another source listed on https://github.com/ungoogled-software/ungoogled-chromium-archlinux for now.

**Comment by LethalManBoob** [comment]
Installing the latest tarball made no difference. Same error.

**Comment by networkException** [comment]
What version of chromium do you have installed? Both 101.0.4951.54 releases from GitHub Actions and the one from chaotic all link against `libdav1d.so.6`

**Comment by LethalManBoob** [comment]
I have solved this by removing ffmpeg-git from chaotic and force removing dav1d once again. Then installing basic ffmpeg. 

But I was using

**Comment by networkException** [comment]
Ok yea that sounds seriously broken
