### ISSUE TITLE
Image vibrate in slideshow (like Wikipedia) and Chromium crashes

### ISSUE THREAD

**Issue by nettlebay** [Eloston/ungoogled-chromium#1952]
Hello! Image begin to vibrate in slideshow (like Wikipedia) and Chromium crashes. Nothing to do to exit except using Xkill. Here in a recipes page. 
I add an animated gif: 
![Peek11-05-2022](https://user-images.githubusercontent.com/14986362/167945700-7b1ccc9a-a653-4adc-9d78-0cdef4ed866e.gif)
Version 100.0.4896.127 (Official Build, ungoogled-chromium) Arch Linux (64 bits)

**Comment by networkException** [comment]
Does this occur on vanilla chromium? Does the issue still persist on the current ungoogled-chromium version? Can you link a page on which the issue occurs?

**Comment by jstkdng** [comment]
I'd suggest you upgrade to the latest uc version an test if the issue persists.

**Comment by nettlebay** [comment]
Hi. I had this problem already with previous versions **but not with the Flatpack version**. Most often this happens in a Wikipedia slideshow. Example: https://en.wikipedia.org/wiki/Chromium_(web_browser)#/media/File:Chromium_about_page_22nd_April.png
During the recent issue, the recipe page was translated with Google Translate in French: https://www-thespruceeats-com.translate.goog/british-desserts-puddings-4162566?_x_tr_sl=en&_x_tr_tl=fr&_x_tr_hl=fr&_x_tr_pto=wapp
No, it's not Vanilla: Version 100.0.4896.127 (Official Build, ungoogled-chromium) Arch Linux (64 bits)
My computer is a Brix Gigabyte GB-BXBT-2807 with only 4 Gb ram (exactly 3,7 mb. The second ram is dead). My Linux is Manjaro.
PS: what is UC version ?
 Good evening.

**Comment by PF4Public** [comment]
I bet it is this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1301067
Should be fixed in 102.

**Comment by nettlebay** [comment]
OK. I tried to update it, but the compilation was interminable. After 6 hours it was at only 20%. I stopped. I will look for a pre-compiled package. I understood for the bug. Thank you for your help.

**Comment by PF4Public** [comment]
This issue is finally fixed in 102:

https://user-images.githubusercontent.com/10319700/169654954-6aded8d2-1481-4a15-a32b-b1f923d3c41d.mp4
