### ISSUE TITLE
Darkmode flags don't work anymore

### ISSUE THREAD

**Issue by DaanKorver** [Eloston/ungoogled-chromium#1953]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

101.0.4951.54

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

The flags --force-dark-mode --enable-features=WebUIDarkMode don't work anymore

### How to Reproduce?

1. Open terminal
2. Type: ``` chromium --force-dark-mode --enable-features=WebUIDarkMode```
3. No dark mode :(

### Actual behaviour

The browsers starts in lightmode

### Expected behaviour

The browser should open in dark mode like it used to do.

**Comment by jstkdng** [comment]
Work's on my machine™, are you perphaps using the gtk+ theme on chromium?

![image](https://user-images.githubusercontent.com/52050345/168130560-d64829b9-c614-4de3-8c92-104993bd3d3d.png)

**Comment by DaanKorver** [comment]
I am using Classic. It worked before but not since I updated.

**Comment by PF4Public** [comment]
No problems on GTK:
![Unbenannt](https://user-images.githubusercontent.com/10319700/168140314-c0881871-ce37-451f-98a9-000c9e2fbc17.png)

**Comment by DaanKorver** [comment]
Editing the flags in the browser worked for me. Thanks :+1:

**Comment by thecountrox** [comment]
the flags in the browser page (chrome://flags#enable-force-dark) inverts on all pages whereas the --force-dark-mode only inverted chromium's pages and made websites prefer dark mode

This makes it not suitable for using along with dark reader

**Comment by PF4Public** [comment]
Does it work in vanilla Chromium?
