### ISSUE TITLE
Add ability to set your own pages on "Home Page" 

### ISSUE THREAD

**Issue by Nonameguy2283** [Eloston/ungoogled-chromium#1955]
### Description

In Google Chrome you can choose a type of Home Page links: 1. based on search history 2. Set your own pages;

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

For me it's really important to have all needed links on Home Page

### Possible solutions

Just copy this function from chrome

**Comment by PF4Public** [comment]
[--custom-ntp](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md#available-only-on-desktop)

**Comment by Nonameguy2283** [comment]
Thanks for help!
