### ISSUE TITLE
Youtube serves me av1 codec instead of vp9

### ISSUE THREAD

**Issue by johnsmith652355** [Eloston/ungoogled-chromium#1966]
### OS/Platform

Windows

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

Version 101.0.4951.67 (Official Build, ungoogled-chromium) (64-bit)

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

On Google Chrome youtube serves me vp9 by default, but on chromium it is av1 for some reason. 

### How to Reproduce?

1. Go on youtube.com
2. Play any video
3. Right click -> Stats for nerds
4. Look at Codecs

### Actual behaviour

I tried different user agents. Vp9 appears only only with Android user agent.

### Expected behaviour

How to make vp9 a default codec on youtube, just like in Chrome?

**Comment by mpaunovic** [comment]
Maybe this extension will help you:

https://github.com/Shimmermare/NotYetAV1

**Comment by johnsmith652355** [comment]
Yeah, I can fix it with an extensions. Still curious how does youtube know that I am not using chrome... Also, it seems like youtube serves av1 in Edge, Firefox as well (so only google chrome users can enjoy dedicated cores for vp9 decoding).

**Comment by jstkdng** [comment]
Can you check if you get av1 with this video? https://www.youtube.com/watch?v=LXb3EKWsInQ

I'm under arch linux and vp9 is served without issues.

![image](https://user-images.githubusercontent.com/52050345/170848394-daebf4c5-2e6a-4312-b8a8-4f205b36d047.png)

**Comment by johnsmith652355** [comment]
Sorry guys, I don't know what happened. A couple of days ago, on fresh install, it was all av1 on chromium and vp9 on chrome. But now they behave the same, even after deleting userdata folder. The video you posted is vp9 for me as well now... (I am on windows 10)

**Comment by PF4Public** [comment]
So I suppose it is fixed on its own.
