### ISSUE TITLE
Pinned chromium weird behaviour

### ISSUE THREAD

**Issue by bonswouar** [Eloston/ungoogled-chromium#1968]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

101.0.4951.64

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Something's wrong when pinning ungoogled-chromium to pannel/taskbar (debian/cinnamon)

### How to Reproduce?

1. Launch ungoogled-chromium
2. Pin it to your pannel/taskbar
3. Clic on that new icon

### Actual behaviour

When pinned, it duplicates the icon instead of "using" the opened one.
And when this new icon is clicked it always opens a new window
![image](https://user-images.githubusercontent.com/615053/170489831-edfc869f-ec09-4008-9ed6-4d938ff58f45.png)

### Expected behaviour

Pinning it should only use the already visible icon, not create a new one.

### Additional context

- Using build from https://github.com/berkley4/ungoogled-chromium-debian
- Debian Bullseye
- Cinnamon as a desktop/window manager

I checked the command options but didn't find anything related (`--new-window` isn't used, and needs an URL anyway).

I don't really know how this debian (cinnamon ? not sure how specific this functionality is) works, but maybe there's something about the process not being recognized as "part of the link", ie ` /usr/lib/chromium/chrome` vs `/usr/bin/chromium`?

**Comment by PF4Public** [comment]
@berkley4 Have you had similar issues?

**Comment by berkley4** [comment]
I would imagine this is a system-specific bug, perhaps in cinnamon. Try launching from the command line with `/usr/bin/chromium` and see if anything interesting shows in the log messages.

It might also be worth looking in /etc/chromium.d to see if anything in there in causing an extra window to be opened; I'm thinking a previous chromium package might have left an old entry behind.

I've just uploaded 102.0.5005.61, so maybe see if that helps.

**Comment by bonswouar** [comment]
@berkley4 I've just tried your latest build, but same behavior.

And unfortunately I don't see any relevant output log, I only have:
```
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
```

**Comment by jstkdng** [comment]
ohhh this issue has been there for quite a while, you need to add/edit StartupWMClass=chromium-browser to the chromium .desktop file

**Comment by bonswouar** [comment]
@jstkdng it worked, thanks!!
I wonder why I didn't have the issue with apt package
