### ISSUE TITLE
Clarification: Is the profile shared with chromium?

### ISSUE THREAD

**Issue by hrj** [Eloston/ungoogled-chromium#197]
In other words, can a user install & use both chromium and ungoogled-chromium simultaneously, with different profiles? Or is the profile directory shared?

It would be great if this was clarified in the README.md itself.

Note: I don't mean to ask about packaging overlap, only runtime profile overlap.

**Comment by lehitoskin** [comment]
The default profile is shared between the two. Before I figured out how to install extensions in ungoogled-chromium what I would do is start regular chromium, install the extension, and then start ungoogled-chromium so that I could then use the extensions like how I want.

**Comment by Eloston** [comment]
Yes, the profile directories are shared by default. You can use a command-line argument to specify what directory you want to designate as the profile directory.

**Comment by Eloston** [comment]
d67d389329150a524319a0500fee8ef9aabc3f7b
