### ISSUE TITLE
How to visit "unsafe" https websites?

### ISSUE THREAD

**Issue by networkException** [Eloston/ungoogled-chromium#1974]
### Discussed in https://github.com/Eloston/ungoogled-chromium/discussions/1972

<div type='discussions-op-text'>

<sup>Originally posted by **cihe13375** May 30, 2022</sup>
Sometimes I need to visit websites with https incorrectly configured (expired certificates, wrong hostname, etc.). In the original Chrome there's a warning for such sites, but I can click Advanced and proceed to the website anyway. However in ungoogled-chromium they're blocked with the "This site can’t be reached" page, and I can't find an option to add exceptions for them. I'm wondering how can I visit them in ungoogled-chromium.

Example websites:
https://expired.badssl.com/
https://wrong.host.badssl.com/</div>

**Comment by PF4Public** [comment]
#1975 This seems to be another important issue with 102 version. I'm again in favour of bumping patch-version :)
