### ISSUE TITLE
Weird bugs on IGN.com affecting uBlock

### ISSUE THREAD

**Issue by nhantrn** [Eloston/ungoogled-chromium#201]
For current release v 55.x

There seem to be some weird bugs when loading www.ign.com that only happen in ungoogled-chromium but not in other chrome variants. If you go to IGN.com, it'll first connect to `www.example.com` and then redirect to `http://www.ign.com/g00/?i10c.referrer=` according to the network log. This does not happen in Chrome official. Nor in Firefox, IE, etc.

Also ads  are slip through on IGN with uBlock. However, if you open up the devtool (F12) the page will automatically reload and ubBock will block all ads correctly. This only happens when you first launch ungoogled chromium. After opening the devtool, uBlock will work fine for the rest of the session.

**Comment by Eloston** [comment]
Alright, thanks for creating the issue.

Your issue is pretty interesting. Are you saying you see `http://www.ign.com/g00/?i10c.referrer=` in the URL bar after the page finishes loading? Or do you only see this in the network log? I'm running an experimental version of 56 and I'm not seeing my URL bar change at all.

**Comment by nhantrn** [comment]
Yes, I can see it in the url bar. I've included a video showing it briefly appear in the urlbar. But you can also see it in the network log in the video.

The first video show you the devtool issue. When I open it, you can the see IGN getting refreshed. uBlock also show it blocking more addresses once the devtool is invoked.

The second video show you ads playing before opening the devtool and did not after.

onedrive videos: https://1drv.ms/f/s!AkqT8bVKK245pBZ-6flqd8KIahJH

**Comment by Eloston** [comment]
I did some research and it may be related to this: https://github.com/uBlockOrigin/uAssets/issues/227

**Comment by nhantrn** [comment]
I haven't seen any mention of why would opening the devtool fixes the problem though.

Also for my case, this only happen in ungoogled-chromium right now. Vivaldi and CentBrowser does not have this issue. They are both chromium v56.x right now.

**Comment by Eloston** [comment]
Are you just using uBlock Origin, or are you also using uBO-Extra? I can reproduce on experimental versions 56 and 57 (which I just updated to) with just uBlock Origin. However, the problem seems to be resolved after I installed the latest stable of uBO-Extra (at the time of writing, 2.13)

**Comment by nhantrn** [comment]
Yes, I only have uBO installed.

**Comment by Eloston** [comment]
Do Vivaldi and CentBrowser have WebRTC enabled? I'm not sure if this is related but it's another factor.

**Comment by nhantrn** [comment]
Actually I recheck Vivaldi and it has the same problem. There's no user option to disable webrtc on Vivaldi so can't test that without webrtc.

I have webrtc disabled on Cent Browser . I turned it back on, but ign loaded fine without the g00 redirect.

Vivaldi is chromium 56.0.2924.88
Centbrowser is chromium 56.0.2924.87

**Comment by Eloston** [comment]
The fact that you reported Vivaldi did not have the issue earlier means there are some other variables at play here. Also, I don't see any reason why CentBrowser is not susceptible to this problem. Therefore, tweaking various variables and performing more trials may bring out the issue on CentBrowser too.

I'm inclined to say that this is not a problem of ungoogled-chromium but a uBlock Origin issue affecting Chromium versions older than 58 (as mentoined in the bug report). I don't see any similarities between Vivaldi and this project other than the Chromium codebase it derives from.

Unless you or anyone else reading this is able to show concrete evidence that some change made by ungoogled-chromium is causing this behavior, I will say install uBO-Extra as that seems to fix the problem.
