### ISSUE TITLE
Can we donate to improve development speed?

### ISSUE THREAD

**Issue by T-vK** [Eloston/ungoogled-chromium#203]
I was wondering how we could improve the development speed. Maybe we could motivate you with monthly donations?

**Comment by Eloston** [comment]
I do not accept donations. We can improve development speed by having more people work on this project. As stated in the README, I always welcome contributors.

**Comment by T-vK** [comment]
People with the necessary skill set to do so, seem to be very rare though. May I ask why you don't want to accept donations?

**Comment by Eloston** [comment]
Because I want the freedom to choose how I spend my time.

**Comment by Eloston** [comment]
I don't know if you already knew, but [it seems that Inox accepts donations](https://github.com/gcarq/inox-patchset#donations). ungoogled-chromium uses most of Inox's patches (especially the Safe Browsing patch, which can take considerable time to update). Having Inox be up-to-date will speed up the updating process for ungoogled-chromium. Also, donating may encourage Inox to grow and include more patches that will reduce the work to update ungoogled-chromium.
