### ISSUE TITLE
request: Static bundle

### ISSUE THREAD

**Issue by nyancat18** [Eloston/ungoogled-chromium#204]
can  we return  the static bundle of @9Morello ?
just run
move to /opt
and  play

**Comment by Eloston** [comment]
No one is working on re-adding this support in version 57. The task is open to anyone who wants to do it. I will update #176 once someone has claimed it.

**Comment by triceratops1** [comment]
@Eloston i gonna try

**Comment by lenormf** [comment]
I'll be waiting for a PR!

**Comment by triceratops1** [comment]
@lenormf i've tried to use the deb 
but uses ancient libraries

or wait to ungoogled-chromium at aur (after iit i build online)

**Comment by Eloston** [comment]
This has been implemented in `develop`, but it needs some work to make the build process smooth.
