### ISSUE TITLE
How does this compare to Inox and Iridium?

### ISSUE THREAD

**Issue by r3muxd** [Eloston/ungoogled-chromium#207]
Sorry!

**Comment by Eloston** [comment]
What specifically do you need clarifications on that the README does not provide you?

**Comment by r3muxd** [comment]
Sorry to bother you, but here's the description of the inox-patchset:
"Inox patchset is applied on the chromium source code and tries to prevent data transmission to Google to get a minimal Chromium based browser. The patches are split up based on features, so it's easy to patch only a subset of them."
Snippet from the Iridium Browser page:
"Chromium (which Iridium is based on) is a very secure browser, yes. But it does call home to Google. And we did even more to enhance security to the maximum extent possible." 
And here's ungoogled-chromium's:
"Modifications to Google Chromium for removing Google integration and enhancing privacy, control, and transparency"
I support what you're doing, but I can't figure out what's different. Sorry!

(Also, is there a way to auto-update extensions that from the chrome web store? I know I can install them, but at the very least is there a way to tell if there's an update? Thanks!)

**Comment by Eloston** [comment]
As the README states, the listed features are specific to ungoogled-chromium. If you want to know the features borrowed from other projects, then you can browse through the patches that ungoogled-chromium uses [here](https://github.com/Eloston/ungoogled-chromium/tree/master/resources/patches).

**Comment by r3muxd** [comment]
I understand. Sorry!

**Comment by Eloston** [comment]
No problem.
