### ISSUE TITLE
Question about new build system

### ISSUE THREAD

**Issue by tectiv3** [Eloston/ungoogled-chromium#209]
Hi!
I'm trying to build on macOS and looking at debian instructions I can't seems to figure out how to apply patches.

> All build scripts follow the general pattern:
> - Setup some or all of the source tree (as necessary)
> - Apply patches
> - Build GN via tools/gn/bootstrap/bootstrap.py
> - Run gn gen with the GN flags
> - Build Chromium via ninja

In a previous build system there was `apply_patches` step which called quilt. I see that you are using dpkg to create debian package and I guess you are applying patches somewhere inside it, right? I would appreciate any help.

Thank you.

**Comment by Eloston** [comment]
> I see that you are using dpkg to create debian package and I guess you are applying patches somewhere inside it, right?

Yes, that's correct. The Debian build system uses quilt to apply patches. The build files generator just places the files in correct locations for Debian to use them.

To get the full set of patches that are domain-substituted, you will need to use `export_resources.py`. Then you can configure `quilt` to use the exported patch order file and patches directory, or apply the patches using any other tool you choose.

**Comment by tectiv3** [comment]
Got it, thank you!
I have a lot of ninja errors because of the missing files (those that were removed when cleaning sources) how do you run build without those files? I think they are mostly required by unittests, can we build without them?

**Comment by tectiv3** [comment]
Nevermind. Do you happen to know why it would fail on:
`FAILED SOLINK libtrknotify.dylib libtrknotify.dylib.TOC`

**Comment by tectiv3** [comment]
Disabled `"//iridium:trknotify",` and finally built Chromium 57 for macOS :)

**Comment by Eloston** [comment]
Interesting. Do you have the error message for linking that library?

**Comment by tectiv3** [comment]
I got this one too. The problem is with `is_component_build = true` that I set to speed up builds. Without it - no errors.
I put up my macOS instructions in my fork so if you want I can submit a pull request.

**Comment by Eloston** [comment]
> The problem was with is_component_build = true that I set to speed up builds

Ah ok. That makes sense

> I put up my macOS instructions in my fork so if you want I can submit a pull request.

Sure. I'm making some minor revisions to `utilikit` right now to reduce code duplication so once you submit your pull request I can make some additional changes.

**Comment by Eloston** [comment]
Closing since macOS support is in `develop`
