### ISSUE TITLE
Impossible to compile: debian 8

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#21]
at debian8  compilation is impossible

its a fresh install  "opensuse build service instance"  

32bit log   https://mega.nz/#!INZx2Yqa!YRzIPlrrmxnHCZZam4zeyDjL6jIDC2od8c34hr0MsTo     

64bit log https://mega.nz/#!9Qhmib4Q!RWF5ufPfqaFZiSCG7KK_BHCpnpyG5QIRJljbfZwHNC0

**Comment by Eloston** [comment]
I noticed in your logs that you're using an old version of the libav* libraries. [Have you seen the note for Debian Jessie users?](https://github.com/Eloston/ungoogled-chromium#debian-and-derivatives).

If you want to use Chromium's bundled FFmpeg, then don't apply `ffmpeg.patch` from `build_templates/debian/patches/system/`.

Let me know how it goes. I haven't actually tested the patches yet, so if it works that will be helpful for me.

**Comment by triceratops1** [comment]
and i've got a very disturbing bug of  ungoogled "a clean opensuse build service xenial vm"   


with this log Supervised users aren't enabled

and after the compilation has been aborted

**Comment by Eloston** [comment]
> "a clean opensuse build service xenial vm"

Are you saying that you're trying to build on a Ubuntu Xenial machine now? Are you not building on Debian 8 anymore?

> Supervised users aren't enabled

What are "supervised users"?

> and after the compilation has been aborted

What's the error? Is it related to the code? If so, do you have a log?

**Comment by Eloston** [comment]
New version is out. Please see the new README for info. Let me know if you still have the problem.
