### ISSUE TITLE
Latest release not working with Ubuntu 16.04 anymore

### ISSUE THREAD

**Issue by nzytkkunit** [Eloston/ungoogled-chromium#213]
Hi! I'm on Ubuntu 16.04 and I get these errors when I try to install your latest package:
None of these are available for Ubuntu 16.04 yet, what to do?
Dpkg: problems with dependencies prevent the configuration of chromium:
  Chromium depends on libavcodec57 (> = 7: 3.2.4) | Libavcodec-extra57 (> = 7: 3.2.4); However:
   Package libavcodec57 is not installed.
   Package libavcodec-extra57 is not installed.
  Chromium depends on libavformat57 (> = 7: 3.2.4); However:
   Package libavformat57 is not installed.
  Chromium depends on libavutil55 (> = 7: 3.2.4); However:
   Version of libavutil55: amd64 on the system is 7: 3.0.2-1ubuntu3.
  Chromium depends on libminizip1 (> = 1.1); However:
   Package libminizip1 is not installed.
  Chromium depends on free2-1v5 (> = 20151101 + dfsg); However:
   Package libre2-1v5 is not installed.
  Chromium depends on libwebpdemux1 (> = 0.4.3); However:
   Package libwebpdemux1 is not installed.

**Comment by Eloston** [comment]
Which package are you trying to install?

**Comment by tristan-k** [comment]
Same here. Package `57.0.2987.110-1`.

**Comment by nzytkkunit** [comment]
I'm trying to install 55.0.2883.87-1 Binaries for Ubuntu - 16.04 (xenial) amd64

**Comment by Eloston** [comment]
@nzytkkunit That build was made by @9Morello. I'm not sure why you're getting those errors.

@tristan-k There is no published build of version 57 for Ubuntu.

**Comment by tristan-k** [comment]
> NOTE: This version only supports Debian and Ubuntu

This is confusing.

**Comment by 9Morello** [comment]
@nzytkkunit Could you please try the following?
1. Add this PPA:
```
sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
sudo apt-get update
```
2. Try to install the dependencies and the packages again.

@tristan-k Theres still no binary release of v57 for Ubuntu 16.04, but the master branch should be working if you want to build it from source.

**Comment by Eloston** [comment]
@tristan-k It says the following at the bottom of the changes list:

> The downloads below are for Debian 9 (stretch) only. Visit the downloads page in the README for other platforms.

**Comment by nzytkkunit** [comment]
@Eloston the install worked after I added the PPA you recommended, but its impossible to browse, I get this error everytime I try to browse
![98778984654](https://cloud.githubusercontent.com/assets/27119072/24841587/27e172f2-1d5e-11e7-9f49-2e32854a5162.png)

**Comment by 9Morello** [comment]
@nzytkkunit Could you please link where you got your packages from?

**Comment by nzytkkunit** [comment]
@9Morello sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3 and https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/ubuntu/xenial_amd64/

**Comment by 9Morello** [comment]
@nzytkkunit Could you please tell me the version of `harfbuzz` installed in your computer? If its below 1.2, consider getting a newer version from this [PPA](https://launchpad.net/~jonathonf/+archive/ubuntu/font-rendering). I just tested it in a Virtual Machine and it should fix it for you.

**Comment by nzytkkunit** [comment]
@9Morello it works now thanks, just too many things to install :/
but thanks anyway!

**Comment by Eloston** [comment]
A version 58 build was just pushed. I don't think it requires PPA packages anymore. Let me know if you still have problems.
