### ISSUE TITLE
Install on Debian Stretch requires *sandbox*

### ISSUE THREAD

**Issue by MathiasRenner** [Eloston/ungoogled-chromium#216]
## Problem description

When I install the `chromium` package on Debian 9, the sandbox package (from the releases of this repo) is required as well. Otherwise, chromium does not start up.

## Steps to reproduce
1. When I start chromium (with the terminal running `chromium`) the terminal says:

   `
[29774:29774:0413/112452.391878:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! 
Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. 
If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox
`

2. As suggested by that output, I ran `chromium --no-sandbox`. That works, chromium started correctly. 

3.  I installed the sandbox package with

    `dpkg -i chromium-suid-sandbox_57.0.2987.110-1_amd64.deb`

    Now, I can start chromium without the terminal from my application menu.

## Suggestion
Could anyone else please reproduce it? In case it's not just on my machine, I suggest 
  - to docmument these steps or 
  - provide a "How To Install" somewhere or
  - include the sandbox package as dependency.

**Comment by Eloston** [comment]
What is the output of the `dpkg -i` command when it fails to install ungoogled-chromium? (i.e. you didn't purge the cache)

**Comment by MathiasRenner** [comment]
The `dpkg -i` command did not fail. The install finishes with exit code `0` (=all fine).

I tested it again and ran `apt clean` in advance to avoid issues through caching. Unfortunately, same thing...

**Comment by Eloston** [comment]
Sorry, what I mean is the stdout and stderr of the program. Is there anything different about this output compared to installing a package with a name not known to the system?

**Comment by MathiasRenner** [comment]
Ah, I see :-) This is the terminal of `sudo dpkg -i chromium_57.0.2987.110-1_amd64.deb`. It looks just fine to me.
```
Selecting previously unselected package chromium.
(Reading database ... 419282 files and directories currently installed.)
Preparing to unpack chromium_57.0.2987.110-1_amd64.deb ...
Unpacking chromium (57.0.2987.110-1) ...
Setting up chromium (57.0.2987.110-1) ...
Processing triggers for bamfdaemon (0.5.3-2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
```

**Comment by Eloston** [comment]
Wait, I overlooked something in your message. When you say "not replaced properly", do you mean that after you install it you just have that sandbox issue, or the package you specified in the `dpkg` command isn't even being used at all?

You bring up a good point that the sandboxing stuff isn't documented anywhere. I think I separated the sandbox package from the `chromium` package because I wanted users to have an option to use either the SUID Sandbox or the Namespace Sandbox. I'll need to check what sandbox takes priority when both namespace sandboxing capabilities are enabled in the kernel and the SUID sandbox binary is present.

**Comment by MathiasRenner** [comment]
@Eloston 
> Wait, I overlooked something in your message. When you say "not replaced properly", do you mean that after you install it you just have that sandbox issue, or the package you specified in the dpkg command isn't even being used at all?

I tried it again: The package you provide **does** replace an existing `chromium` package, so that's fine. Thus, regarding this issue only the `sandbox` issue exists. 
(I don't know why the behavior is now different, sorry. I just updated the issue title and my first post.)

**Comment by Eloston** [comment]
I tested it out and Chromium will default to the namespace sandbox when the SUID sandbox is available. f2c1cb079dce0558bcb71476819deeca4e75b0f7 uses this fact to simplify the packages.
