### ISSUE TITLE
upload binaries   

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#22]
could you upload binaries  of ungoogled 51?

**Comment by Eloston** [comment]
Not yet. I haven't [finished working on it](https://github.com/Eloston/ungoogled-chromium/milestones/51.x.x.x).

**Comment by triceratops1** [comment]
i have a very small questio for you   

how many time - resources   need for compile ?

**Comment by Eloston** [comment]
[Here's Google's recommendations](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md), but I've been able to go with less than that. I think you'll need about 30 GB of storage space. I have 4 GB of RAM on my build VM and two cores (with hyperthreading, for a total of 4 threads) on an Intel Xeon E5-2430L. It takes about 5-6 hours to build Chromium I believe.

**Comment by triceratops1** [comment]
what build vm reccomend=

**Comment by Eloston** [comment]
You don't need a VM. I just used one because the machine I used is a VM host. If you match the specs I gave that should be sufficient.

**Comment by triceratops1** [comment]
a vps?

**Comment by Eloston** [comment]
No I didn't use a VPS. You can use one if you want. It really doesn't matter what kind of machine you use.

**Comment by triceratops1** [comment]
are you using your computer "native"??

**Comment by Eloston** [comment]
I do work on a VM that sits on a dedicated VM hypervisor. I use it because it has quite a bit of read and write storage cache, but it really doesn't make that much difference while building.
