### ISSUE TITLE
Discord: Can't enable microphone

### ISSUE THREAD

**Issue by MilesFM** [Eloston/ungoogled-chromium#221]
I was using discord and even when I manually enabled my microphone it still didn't detect it. On normal chromium and chrome there is no issue.

**Comment by Eloston** [comment]
Discord uses WebRTC for voice chat, which isn't enabled yet. See #179.

I'll close this when that is resolved.

**Comment by Atavic** [comment]
This repository removes Google integration and enhances privacy.

Better safe than sorry.

**Comment by Eloston** [comment]
As #179 notes, WebRTC has been re-enabled for the upcoming 62 release.

**Comment by jackhill** [comment]
Perhaps related to #785 ?
