### ISSUE TITLE
Installing extensions simply

### ISSUE THREAD

**Issue by icecom64** [Eloston/ungoogled-chromium#226]
I have an idea how to download extensions from chrome web store easily without any scripts. In FAQ there's this link you can use:
`https://clients2.google.com/service/update2/crx?response=redirect&prodversion=48.0&x=id%3D[EXTENSION_ID]%26installsource%3Dondemand%26uc`

You can replace `[EXTENSION_ID]` with `%s` and add this link as search engine, using something like `ext` as keyword. Next time you want to install extension, find it in chrome web store,  replace everything before extension id with "ext ", press enter and extension will be downloaded.
![image](https://cloud.githubusercontent.com/assets/23084830/25774046/34c88936-3291-11e7-91d3-7bc087ab8b0c.png)
![image](https://cloud.githubusercontent.com/assets/23084830/25773976/f58d50b8-328f-11e7-8f8e-5631f838d3d2.png)
![image](https://cloud.githubusercontent.com/assets/23084830/25773982/0d9ec07e-3290-11e7-93d8-07280b8d1cc2.png)

**Comment by Eloston** [comment]
This is pretty clever. Would you be able to make a pull request? (you can use the `master` branch since this isn't changing any features)

**Comment by Unkn0wn-MDCLXIV** [comment]
I've also created a small script for that issue.
It reads a textfile containing all extension ids you want to use and downloads them if they don't exist or updates them if there is a newer version.
The CRX files then get stored in a subfolder called and extensions and can be dragged in chromium to install them.

If there is some demand for that, I would be glad to upload the code and the compiled release to github.
It's windows only unfortunately.

**Comment by sergeevabc** [comment]
@Unkn0wn-MDCLXIV, compiled Windows binary would be appreciated indeed.

**Comment by shak3800** [comment]
@iCeC0M Thanks for this great workaround. However i can't seem to install extensions. I keep getting this message : 

apps extensions and userscripts cannot be added from this website.

Of course dragging and dropping the extension works ok. Is this disabled by default?

**Comment by macandchief** [comment]
It seems that the method with this link `https://clients2.google.com/service/update2/crx?response=redirect&prodversion=48.0&x=id%3D[EXTENSION_ID]%26installsource%3Dondemand%26uc` does not work on Ungoogled Chromium v62.

**Comment by macandchief** [comment]
In the end I tried every method given on the readme page and somehow none of them worked for me (even tried maninex and it did not work because of python2). However there is  https://chrome-extension-downloader.com/  which simply downloads the .crx file, so drag & drop on the extensions page works that way.

**Comment by Eloston** [comment]
@macandchief That URL never worked to auto-install CWS extensions. But since 62, `chrome://flags/#extension-mime-request-handling` was added to change the behavior. You can set it to "Install always" to make it prompt the user to install.

**Comment by sergeevabc** [comment]
> If there is some demand for that, I would be glad to upload the code and the compiled release

Notably, @Unkn0wn-MDCLXIV offered a way for Windows twice ([here][1] and [there][2]), but never uploaded it.
A man is only as good as his word, [right][3]?

[1]: https://github.com/Eloston/ungoogled-chromium/issues/226#issuecomment-308950357
[2]: https://github.com/Eloston/ungoogled-chromium/issues/174#issuecomment-308950754
[3]: https://www.quora.com/A-man-is-only-as-good-as-his-word-How-true-is-this

**Comment by Unkn0wn-MDCLXIV** [comment]
@sergeevabc 
Haha, got me.
[Here you are](http://m.unkn0wn3d.com/2BX5T9m)

Fill the extensions.txt with the ids of the extensions you want to download and the run the exectuable.
If there is anything wrong, just contact me.

**Comment by tonowoe** [comment]
I'm not sure if this kind of script have already been shared here. I made this JavaScript code which I can run on my browser's console to download the crx file automatically. This can't be run via bookmark, unfortunately (for security reasons I think).

Script can be found [here](https://gist.github.com/tonowoe/178bdb4fee71fedeee8981b424bd0631) (minified [here](https://gist.github.com/tonowoe/7050c8371490d48899e7e296792aee40)).

So when you are at the extension page in Google Webstore, just press F12 and open up the console and paste the code there. It should download the .crx file for you. No need to add browser version and extension ID to the URL manually.

**Comment by tim-hub** [comment]
`CRX Header Invalid`
When I try to install an extension through the script, but I got this error and, it is not installed.

![extension header invalid](https://user-images.githubusercontent.com/2884320/56244748-378aa880-608d-11e9-8912-d5d466afa9b1.jpg)

**Comment by ipeacocks** [comment]
@tim-hub with latest 73 version on ubuntu I have the same problem. But you can still use previous 72 version.

**Comment by Peacock365** [comment]
@tonowoe 

Would it be possible to revise your script, to publish a new version of it? Up to and including Ungoogled Chromium 72 is worked fine, from version 73 onwards it only gives the error message CRX_HEADER_INVALID. Please fix, I rely on it.

**Comment by tim-hub** [comment]
> @tonowoe
> 
> Would it be possible to revise your script, to publish a new version of it? Up to and including Ungoogled Chromium 72 is worked fine, from version 73 onwards it only gives the error message CRX_HEADER_INVALID. Please fix, I rely on it.

Tries on new v 74, same as 73.

**Comment by immanacled** [comment]
@Peacock365 @tim-hub 
I think you need to add `&acceptformat=crx3` to `var final_url`, [here](https://pastebin.com/HYzp9zV0) is minified version with modified final_url. Works for me with 74.0.3729.108

**Comment by tim-hub** [comment]
> &acceptformat=crx3

Great, thanks.

I created a gist too.
https://gist.github.com/tim-hub/4ee32f671de0ee38684ef6754335bb38

**Comment by Peacock365** [comment]
@immanacled 

Thank your for the new script. Everything works without a hitch again. Well done!

**Comment by enolgor** [comment]
@tim-hub 

Thank you for the gist it works like a charm.
I created a very simple extension that adds a contextual menu in the chrome webstore webpage of an extension that executes your gist with a click of a button.

https://github.com/enolgor/ungoogled-chromium-extension-installer

I think something like this could be added by default in the browser maybe?

**Comment by jlj2** [comment]
Using the compiled version of @enolgor's _ungoogled-chromium-extension-installer_, mentioned directly above, somehow had the added usefulness - for those who prefer it - of making the Google Translate extension work at least on the [Portable Linux 64-bit binary version of ungoogled-chromium 75.0.3770.100-1.2](https://ungoogled-software.github.io/ungoogled-chromium-binaries/).  The Google Translate extension perhaps did not work [in another installation](https://github.com/Eloston/ungoogled-chromium/issues/781), nor for me at least when installing the Google Translate extension by renaming the .crx extension to .zip, extracting it and installing the unpacked version using the Extension webpage in Developer mode (after setting chrome://flags/#extension-mime-request-handling to 'Always prompt for install'). If I recall correctly, another extension that reported "package invalid: crx header is invalid" for me when attempting to be installed by unpacking was able to be installed correctly when using the _ungoogled-chromium-extension-installer_ method.
Proviso:  I haven't checked the integrity of that installer's code.

**Comment by jieggii** [comment]
Hi everyone. I have created [website](https://ungoogled-extension.github.io/), using one you can easily install extensions from Chrome Web Store. I hope it will help someone. Just paste addon's url from store into input and press install!

**Comment by SkyNinja** [comment]
@enolgor 
I can't get your extension to work on 76.0. It can't be installed as is because of the change to CRX3, and when loaded unpacked, it sometimes tries to install, producing a error about this site not being allowed to install addons, or does nothing at all.

**Comment by afterdelight** [comment]
There is already a working extension installer and updater on https://github.com/NeverDecaf/chromium-web-store

**Comment by afterdelight** [comment]
There is already a working extension installer and updater on https://github.com/NeverDecaf/chromium-web-store

**Comment by enolgor** [comment]
@afterdelight
Nice!

@SkyNinja
I recommend you to use that extension, mine was just a quick workaround :)
