### ISSUE TITLE
Access to keychain?

### ISSUE THREAD

**Issue by pcaswell909** [Eloston/ungoogled-chromium#227]
Why does this build need access to the keychain?

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
  Boot ROM Version:	MBP121.0167.B24
  SMC Version (system):	2.28f7

**Comment by Eloston** [comment]
I don't change anything related to that. Chromium uses the keychain to store passwords from websites. I don't know if there's any way to disable that, but your best bet is a GN flag.

Let me know if something I said doesn't make sense.
