### ISSUE TITLE
57.0.2987.110-1 GN build error

### ISSUE THREAD

**Issue by lehitoskin** [Eloston/ungoogled-chromium#229]
I followed the directions listed in the BUILD file, but when I get to step 7 (building GN), it errors with this:

```
...
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
[337/337] LINK gn
Building gn using itself to out/Release...
ERROR at //printing/BUILD.gn:147:22: Script returned non-zero exit code.
      cups_version = exec_script("cups_config_helper.py",
                     ^----------
Current dir: /home/lehi/Downloads/ungoogled-chromium-57.0.2987.110-1/build/sandbox/out/Release/
Command: python -- /home/lehi/Downloads/ungoogled-chromium-57.0.2987.110-1/build/sandbox/printing/cups_config_helper.py --api-version /home/lehi/Downloads/ungoogled-chromium-57.0.2987.110-1/build/sandbox/build/linux/debian_wheezy_amd64-sysroot
Returned 1 and printed out:

cups-config not found: /home/lehi/Downloads/ungoogled-chromium-57.0.2987.110-1/build/sandbox/build/linux/debian_wheezy_amd64-sysroot/usr/bin/cups-config

See //BUILD.gn:270:7: which caused the file to be included.
      "//printing:printing_unittests",
      ^------------------------------
Command '['/tmp/tmpXrhx8n/gn', 'gen', '/home/lehi/Downloads/ungoogled-chromium-57.0.2987.110-1/build/sandbox/out/Release', '--args= is_debug=false']' returned non-zero exit status 1
```

I looked inside `ungoogled-chromium-57.0.2987.110-1/build/sandbox/build/linux/debian_wheezy_amd64-sysroot`, but it was empty.

I'm running amd64 Gentoo with Python versions 2.7.13, 3.4.6, and 3.6.1-r1

**Comment by Eloston** [comment]
What specific instructions are you following? Are you using `Notes for other systems, platforms, and configurations`? Are you using `depot_tools`? `utilikit`? What are your GN flags?

**Comment by lehitoskin** [comment]
I'm just following the "General building instructions". I'm using `utilikit` with the `UTILIKIT_CONFIG_TYPE=linux_conservative` environment variable set. I don't know anything about the GN flags, so your guess is as better than mine.

**Comment by Eloston** [comment]
Based on your interpretation, I've reformatted BUILDING to make more sense. [It's currently available in the develop branch](https://github.com/Eloston/ungoogled-chromium/blob/develop/BUILDING.md).

It's not documented yet (since there are some problems with GCC vs Clang that need to be worked out), but you can try generating a build script using the `linux_simple` build type.

**Comment by lehitoskin** [comment]
Okay, I'll try it with `linux_simple`.

**Comment by Eloston** [comment]
Oh yeah, I forgot to mention where that build script is and how to use it. `linux_simple` can be used by running `ungoogled_linux_simple/build.sh` from within `build/sandbox` (or whatever you specified your build sandbox directory to be). It also uses `quilt` to apply patches. And it's only been tested in a fresh sandbox.

**Comment by lehitoskin** [comment]
Ah, hm, the `ungoogled_linux_simple` directory doesn't appear to exist.

**Comment by Eloston** [comment]
Are you sure you generated the build files correctly? I tested the code and it still works correctly.

**Comment by lehitoskin** [comment]
Probably not. I'm running the command `utilikit/generate_build_files.py debian --flavor standard --apply-domain-substitution`, but since that was taken from the Debian build section, maybe I don't want to run it?

**Comment by Eloston** [comment]
`debian` in that command is the build type. Pass in `--help` to that script and subcommands of it for more info.

**Comment by lehitoskin** [comment]
Ah-ha! There we go. `ungoogled_linux_simple` has now been generated.

**Comment by Eloston** [comment]
Closing to clean up the issue tracker. Let me know if you still have problems.
