### ISSUE TITLE
Domain substitution should ignore HSTS preload list

### ISSUE THREAD

**Issue by ajhaydock** [Eloston/ungoogled-chromium#23]
I know this feature is a work in progress, and you may have thought of this already, but the domain substitution scripts currently do not make any exception for [the HSTS preload list](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json), which contains entries for basically all of the URLs the script wants to replace. Some form of exception could be added to avoid compromising user security by stripping the sites of their HSTS preload status in the final build.

And thanks for your work on this great project!

**Comment by Eloston** [comment]
I did not know about this. Thanks for letting me know.
