### ISSUE TITLE
Why is it only compatible with Ubuntu/Debian?

### ISSUE THREAD

**Issue by T-vK** [Eloston/ungoogled-chromium#232]
The latest release is only compatible with Ubuntu/Debian according to the release notes. 
I'd like to know why that is. 
The reason is that Ubuntu/Debian both tend to come with very outdated kernels and I really want my kernel to always be up to date, so I prefer distros like Fedora (which uses rmp instead of deb packages).  
I read about this tool called `alien` which apparently converts .deb packages to .rpm packages.  
Is there a reason why this wouldn't work for ungoogled-chromium?

**Comment by funghetto** [comment]
I believe that they just lack manpower, anyways debian sid & ubuntu Zesty Zapus have new kernels.

**Comment by Eloston** [comment]
> The latest release is only compatible with Ubuntu/Debian according to the release notes.
> I'd like to know why that is.

Because I run Debian Stretch, and someone I know asked me for a new Ubuntu version too.

> Is there a reason why this wouldn't work for ungoogled-chromium?

You might run into issues with system libraries. I use patches from Debian to build against more system libraries.

**Comment by T-vK** [comment]
@funghetto Debian sid is unstable and [uses 4.9](https://packages.debian.org/search?suite=sid&arch=any&searchon=sourcenames&keywords=linux). Just to give you a perspective, this kernel  is 6 months old. Fedora is way on top of that with 4.11, which is the latest. 

@Eloston Okay, thank you.

**Comment by Eloston** [comment]
Going to close this since everything here seems resolved.

**Comment by funghetto** [comment]
sid is unstable like fedora, not meant for a server that requires years of uptime.
You can find this kernel on the [experimental ](https://packages.debian.org/experimental/kernel/)branch.

**Comment by T-vK** [comment]
@funghetto 
I don't know, Fedora feels quite stable. Personally, I would compare it more to Debian's testing branch.  
I've never actually tried running Debian's experimental or unstable branches, but I've heard some bad things and feel like it's too risky. But maybe I'm just lucky with my Fedora...
