### ISSUE TITLE
Flash plugin always crashes

### ISSUE THREAD

**Issue by pickx** [Eloston/ungoogled-chromium#233]
Using Ungoogled-Chromium 57 on 10.11.6
I've installed PPAPI 25 and it is detected in chrome://flash/.
However whenever I attempt to load any Flash content the tab crashes (with the "Aw, snap" message).
I've also tried installing PPAPI 26 prerelease. Also detected in chrome://flash/, also crashes.

Has anyone been able to get this to work?

**Comment by Eloston** [comment]
This is because WebRTC is disabled. Inox had the same problem, so gcarq enabled WebRTC.

I will leave this open until #179 is resolved.

**Comment by Eloston** [comment]
This should be fixed in 62, since WebRTC has been re-enabled.
