### ISSUE TITLE
Current .desktop file doesn't work well with GNOME 3; proposed suggestion follows

### ISSUE THREAD

**Issue by picsi** [Eloston/ungoogled-chromium#234]
First off, it tries to fetch an icon from /opt/, and there's nothing there, so no icon shows up. On my end, since I use Numix icons, I just directed the path to /usr/share/icons/Numix-Circle/48/apps/chromium.svg

Secondly, the .desktop file needs this additional field: `StartupWMClass=chromium-browser`. This makes it possible to favorite the browser into the GNOME dash.

**Comment by Eloston** [comment]
What build of ungoogled-chromium are you using?

The `.desktop` file generated by `chrome-wrapper` is from Google's own code. This project doesn't touch that at all.

The `.desktop` file that is part of the Debian and Ubuntu packages is from Debian and work fine on GNOME 3 for me.

**Comment by picsi** [comment]
I'm using this one: https://aur.archlinux.org/packages/ungoogled-chromium-bin/

**Comment by Eloston** [comment]
That package isn't maintained by me or affiliated with this project. You should post the issue on that page. 

I don't know what that maintainer did, but the `.desktop` file that is part of the Debian packaging scripts of this project works correctly with GNOME 3. Maybe that can be used as a reference.

**Comment by picsi** [comment]
Does this project maintain ainy binaries/PKGBUILDs for Arch-like distros?

**Comment by Eloston** [comment]
There is #44, which is to add a PKGBuild generator to `utilikit` (but it has not gotten anywhere). Otherwise, there is an archlinux configuration type in `utilikit` to produce GN flags and patches to use.
