### ISSUE TITLE
Please provide fresh windows builds

### ISSUE THREAD

**Issue by leedoyle** [Eloston/ungoogled-chromium#236]
The latest windows x64 build is half a year old (Chromium version 55 was released in December). That's a **lot** for a network software.

**Comment by leeoniya** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/235

**Comment by Eloston** [comment]
#215 is a prerequisite. Once that is done, uploading builds is trivial and straight-forward. Therefore, marking this as a duplicate.
