### ISSUE TITLE
Error "Signal 11" on Ubuntu

### ISSUE THREAD

**Issue by matbonucci** [Eloston/ungoogled-chromium#237]
The browser do not open and in the Terminal this is shown
`Received signal 11 SEGV_MAPERR 000000000000
#0 0x55662a564e45 <unknown>
#1 0x55662a5651f9 <unknown>
#2 0x7f591776a390 <unknown>
#3 0x55662dfae1fc <unknown>
#4 0x55662dfae625 <unknown>
#5 0x55662dfb22fa <unknown>
#6 0x55662dfad8b7 <unknown>
#7 0x55662dfec9b7 <unknown>
#8 0x55662dfe67c0 <unknown>
#9 0x55662dfef6a3 <unknown>
#10 0x55662a5f3029 <unknown>
#11 0x55662a584d00 <unknown>
#12 0x55662a58699d <unknown>
#13 0x55662a586e50 <unknown>
#14 0x55662a5881a0 <unknown>
#15 0x55662a583e15 <unknown>
#16 0x55662a5a97ca <unknown>
#17 0x5566292f7e78 <unknown>
#18 0x5566292f805b <unknown>
#19 0x55662a5c6bf0 <unknown>
#20 0x55662a5c2752 <unknown>
#21 0x7f59177606ba start_thread
#22 0x7f5910d6282d clone
  r8: 00000cd9e5eff100  r9: fffffffd54ceb801 r10: fffff324b12f1ba1 r11: 0000000000000001
 r12: 00007f5900168c40 r13: 0000000000000040 r14: 00000cd9e5e824b0 r15: 00000cd9e5eff180
  di: 0000000000000000  si: 4eb3278da065247a  bp: 00007f5900168c50  bx: 00000cd9e5d2d400
  dx: 5ad72e47fb2b7c7f  ax: 0000000000000000  cx: 0000000000000000  sp: 00007f5900168c20
  ip: 000055662dfae1fc efl: 0000000000010202 cgf: 0000000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
`
I'm on Lubuntu 16.04 x64 and I installed all 5 .deb installers

**Comment by Eloston** [comment]
Did you install the Ubuntu 16.04 version 58 packages?

**Comment by matbonucci** [comment]
> Did you install the Ubuntu 16.04 version 58 packages?

Yes

**Comment by Eloston** [comment]
Hmm. I've never had this kind of problem before.

@dubvulture It seems that @matbonucci is using your build. Do you have any ideas?

**Comment by dubvulture** [comment]
I just tested on a virtual machine with Lubuntu 16.04.2.
It worked for me but I got the following message (which I do not get on Ubuntu vanilla):

`[27106:27106:0614/084735.470713:ERROR:sandbox_linux.cc(343)] InitializeSandBox() called with multiple threads in process gpu-process`

It went away by launching `chromium --disable-gpu` (but again, chromium worked even without it) so if you could try this and let me know what happens that would be very helpful.
Anyway, `signal 11 SEGV_MAPERR 000000000000` looks like a segmentation fault so the abovementioned error could be something not even related.

In the meanwhile in the next 10 hours I will try to replicate this on a different physical machine.

**Comment by Eloston** [comment]
@dubvulture Does `chrome://sandbox` show different values on Lubuntu and regular Ubuntu?

**Comment by dubvulture** [comment]
@Eloston nope, they're all the same.

Anyway I tested on another machine with Lubuntu 16.04.2 and it worked perfectly (with no sign of the `InitializeSandbox()` error*)

* upon further inspection in `sandbox_linux.cc(343)` it seems that is not even a real error since it is stated that  `// The GPU process is allowed to call InitializeSandbox() with threads.`

**Comment by matbonucci** [comment]
`After publishing that build I made another one while testing some flags so you might try that out -> https://www.dropbox.com/s/lku4ed8hnebzl9t/build.tar.xz`

Try them and the same error

I solved the problem by deleting the config folder from an old chromium installed from apt, the folder was
/home/$USER/.config/chromium/

Thanks @Eloston @dubvulture  for your answers

**Comment by Eloston** [comment]
Hm, the regular Chromium config is probably crashing ungoogled-chromium somehow. Not sure what it could be though.

It's probably not a huge deal, so I'm closing this.
