### ISSUE TITLE
Enable native notifications for macOS dont working.

### ISSUE THREAD

**Issue by kfur** [Eloston/ungoogled-chromium#239]
When i toggle this option in `chrome://flags/#enable-native-notifications` chromium still show me old style notifications.

**Comment by nixballs** [comment]
@kfur  - from what I can see, the above applies to the 59 branch - [Native Notofications macOS](https://developers.google.com/web/updates/2017/04/native-mac-os-notifications). Ungoogled-Chromium is still at 58 branch.

Maybe @Eloston can further clarify.

**Comment by Eloston** [comment]
In 58 it could have been an experimental option. I don't believe any patch affects notifications, so it could be due to some macOS build flags or build environment.

We can test this again in the next update to ungoogled-chromium.

**Comment by kfur** [comment]
It seems that all working again in Chromium 60.
So i guess issue may be closed.
