### ISSUE TITLE
Debian 9 Error - "Chromium conflicts with libnettle4"

### ISSUE THREAD

**Issue by 38576010295** [Eloston/ungoogled-chromium#242]
Hello everyone. Great project you have going on here and all.

So my situation is that I've gone down the Linux rabbit-hole and now I'm running Qubes. Seeing that Eloston himself makes the Debian 9 distributions, I figured I'd make a Debian 9 VM for my browsing qube. Being that Qubes 3.2 comes with Debian 8, I first upgraded made a new Debian 9 template and fully updated it, then ran the qube. I downloaded Chromium 58 from here, but during installation the following occurred...

```
 user@browser:~$ cd /home/user/Downloads
 user@browser:~/Downloads$ sudo dpkg -i chromium_58.0.3029.110-1_amd64.deb
 dpkg: regarding chromium_58.0.3029.110-1_amd64.deb containing chromium:
  chromium conflicts with libnettle4
   libnettle4:amd64 (version 2.7.1-5+deb8u1) is present and installed.

 dpkg: error processing archive chromium_58.0.3029.110-1_amd64.deb (--install):
  conflicting packages - not installing chromium
 Errors were encountered while processing:
 chromium_58.0.3029.110-1_amd64.deb
 user@browser:~/Downloads$ 
```

What's this all about? Anything I can do to fix the issue? I came here to ask first because I assumed Libnettle is probably some system resource I shouldn't just start toying with.

Lastly, just figured I'd say that I WAS able to get Ungoogled Chromium running with no problems on Ubuntu and Kubuntu. In fact I found that you can download the Chrome 58 for Ubuntu 16.04 (xenial) package to Ubuntu 17.04 (zesty) and it'll run just fine (I did that because the packages available for latest Ubuntu is an outdated Chromium).

Anyway, that doesn't address the problem though as you can't make a convenient Ubuntu VM on Qubes. You CAN make a full HVM from an ISO of course, but not an easily Qubes-managed AppVM from it or anything. So that's not an option.

Figured I'd mention the issue here and see if Eloston may know anything about it, seeing as Debian seems to be his thing.

Thanks!

**Comment by Eloston** [comment]
I've seen someone else get this error over on Gitter chat not too long ago, and I'm not sure why it's happening. `libnettle4` isn't in Debian stretch repositories, and my system does not have it.

Perhaps there is some old package or third-party package that is depending on it. Can you check what packages depend on `libnettle4`?

**Comment by 38576010295** [comment]
I'm still learning Linux but I'll do what I can.

Using a few different methods:

```
user@browser:~$ apt-cache rdepends libnettle4
libnettle4
Reverse Depends:
  libgnutls-deb0-28
  libhogweed2
  chromium
```
```
user@browser:~$ aptitude -v why libnettle4
i   libgnutls-deb0-28 Depends libnettle4 (>= 2.7)

i   libhogweed2 Depends libnettle4 (= 2.7.1-5+deb8u1)
user@browser:~$ 
```

```
user@browser:~$ apt-cache showpkg libnettle4
Package: libnettle4
Versions: 
2.7.1-5+deb8u1 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 9dcb77a61a93b06eb5b005f9c8c509a4


Reverse Depends: 
  libgnutls-deb0-28,libnettle4 2.7
  libhogweed2,libnettle4 2.7.1-5+deb8u1
  chromium,libnettle4
Dependencies: 
2.7.1-5+deb8u1 - multiarch-support (0 (null)) libc6 (2 2.14) 
Provides: 
2.7.1-5+deb8u1 - 
Reverse Provides: 
user@browser:~$ 
```
Hope that's helpful, lemme know if there's a better method.

**Comment by Eloston** [comment]
Just one method is fine.

`libgnutls-deb0-28` and `libhogweed2` aren't in Stretch either. It might be easier to use the ncurses aptitude interface (the default when running `aptitude`) to see what packages are considered obsolete (i.e. not in any of the configured APT repos). Having obsolete packages in your system can cause issues with other packages.

**Comment by 38576010295** [comment]
Strange that this would happen since I fully updated Debian 9 and did the cleanup process too.

I'll try `aptitude purge ~o` and see if that fixes it.

**Comment by 38576010295** [comment]
Looks like it will...

```
user@browser:~$ su
root@browser:/home/user# aptitude purge ~o
The following packages will be REMOVED:  
  gcc-4.8-base{p} gcc-4.9-base{p} libapt-inst1.5{p} libapt-pkg4.12{p} 
  libboost-iostreams1.55.0{p} libdns-export100{p} libgnutls-deb0-28{p} 
  libhogweed2{p} libicu52{p} libirs-export91{p} libisc-export95{p} 
  libisccfg-export90{p} libjson-c2{p} liblognorm1{p} libnettle4{p} 
  libprocps3{p} libpsl0{p} libreadline6{p} libssl1.0.0{p} 
  libtxc-dxtn-s2tc0{p} libxtables10{p} python-debian{u} python-debianbts{u} 
  python-httplib2{u} python-pysimplesoap{u} python-reportbug{p} 
  python-support{p} 
0 packages upgraded, 0 newly installed, 27 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 42.0 MB will be freed.
```
Dunno why they were on the system to begin with, weird. Wonder if they have something to do with Qubes, I dunno. Ya see the update and cleanup I did in the TemplateVM, this the AppVM made from the Template. Not sure if these have anything to do with it.

**Comment by 38576010295** [comment]
Looks like I'll have to do a bit more...

```
user@browser:~$ cd /home/user/Downloads
user@browser:~/Downloads$ sudo dpkg -i chromium_58.0.3029.110-1_amd64.deb
Selecting previously unselected package chromium.
(Reading database ... 98145 files and directories currently installed.)
Preparing to unpack chromium_58.0.3029.110-1_amd64.deb ...
Unpacking chromium (58.0.3029.110-1) ...
dpkg: dependency problems prevent configuration of chromium:
 chromium depends on libatomic1 (>= 4.8); however:
  Package libatomic1 is not installed.
 chromium depends on libavformat57 (>= 7:3.2.4); however:
  Package libavformat57 is not installed.
 chromium depends on libminizip1 (>= 1.1); however:
  Package libminizip1 is not installed.
 chromium depends on libre2-3 (>= 20160901); however:
  Package libre2-3 is not installed.
 chromium depends on libwebpdemux2 (>= 0.5.1); however:
  Package libwebpdemux2 is not installed.

dpkg: error processing package chromium (--install):
 dependency problems - leaving unconfigured
Processing triggers for qubes-core-agent (3.2.18-1+deb9u1) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
```

Well, guess I'll just install these and stuff. I need to get out for a walk or something first though, been staring at a screen all day. I'll report with news in a little while probably.

**Comment by 92847586** [comment]
Ha, I just saw this while checking up on Ungoogled Chromium. Must have forgotten to update after getting it working.

In the end I was able to get it running. Involved uninstalling a few conflicting things iirc. This was a while ago now though.

Sorry to revive a dead thread, just thought I'd say that I did get it working in the end but it involved deleting quite a few things manually from Debian 9. Perhaps those things were in the Debian 9 because it was a Qubes VM as opposed to an actual fresh install of Debian 9. Also comes to mind is that I updated that Template VM from Debian 8 to Debian 9 at some point. Perhaps they were residual leftovers. No idea though.

You might notice I'm also the person that asked about building it on Windows. Looks like Iridium is going to update to Chromium 60 before long. I've been using it for Windows lately since UGC is kinda Windows-unsupported for now.  Hoping that Chromium 60 might be a change for that, or at least you'll keep up with Debian builds.

Thanks!

**Comment by Eloston** [comment]
Glad to hear you got it working. I recently upgraded a separate machine from Debian 8 to Debian 9 via switching `sources.list` and using `aptitude`, but there were some pretty cryptic conflicts until I selected to remove the "Obsolute and Locally Created Packages". It makes me wonder if the automated `apt-get dist-upgrade` command would be able to resolve this correctly.

Regarding the future, I plan on upgrading to Chromium 60 very soon. If I can, that might also include upgrading Windows support this time around.

**Comment by 92847586** [comment]
You can see the method I used to update the Debian 8 TemplateVM to Debian 9 here: https://www.qubes-os.org/doc/template/debian/upgrade-8-to-9/

It could've left behind the conflicting files assuming they're present in Debian 8 and aren't automatically cleaned out by the upgrade, I suppose.
