### ISSUE TITLE
mac osx build fail: OverrideForTesting symbol not found for architecture x86_64

### ISSUE THREAD

**Issue by temoto** [Eloston/ungoogled-chromium#243]
Thanks for your work.

Trying to build on mac results with this error. Do you know how to fix it?

Version: 58.0.3029.110-1

```
[351/351] c++  -o gn tools/gn/gn_main.o -framework AppKit -framework CoreFoundation -framework Foundation -framework Security libevent.a base.a gn_lib.a dynamic_annotations.a
FAILED: gn
c++  -o gn tools/gn/gn_main.o -framework AppKit -framework CoreFoundation -framework Foundation -framework Security libevent.a base.a gn_lib.a dynamic_annotations.a
Undefined symbols for architecture x86_64:
  "base::ScopedClosureRunner::ScopedClosureRunner(base::Callback<void (), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&)", referenced from:
      base::ThreadTaskRunnerHandle::OverrideForTesting(scoped_refptr<base::SingleThreadTaskRunner>) in base.a(thread_task_runner_handle.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by Eloston** [comment]
So you're trying to build GN?

I'm assuming you're following [the macOS building instructions](https://github.com/Eloston/ungoogled-chromium/blob/master/BUILDING.md#macos)?

What versions of macOS and Xcode are you running?

**Comment by temoto** [comment]
Sorry I don't know what is GN, but that word occurs in build output as target name.

I followed macos build instructions from BUILDING.md

OSX version was likely 10.10 or 10.11, I've just upgraded to 10.12 and will try again.
XCode 6.3

`ungoogled_macos/build.sh` was deleted.

It works now, so I guess you could state OSX 10.10 is not supported as build machine.

**Comment by tectiv3** [comment]
I've tested it on 10.9 and 10.11.

**Comment by Eloston** [comment]
I don't recall anyone ever testing on Xcode 6.3 before. All development so far has occured on Xcode 7 or 8 as stated in BUILDING.md

**Comment by Eloston** [comment]
Closing since the issue seems to be resolved.
