### ISSUE TITLE
Remove Google's arbitrary style for menu, recover Windows native style

### ISSUE THREAD

**Issue by zcyzcy88** [Eloston/ungoogled-chromium#244]
This is Windows:
<img width="226" alt="2017-07-23 16_48_57-new issue eloston_ungoogled-chromium" src="https://user-images.githubusercontent.com/15178410/28498017-49498a54-6fc7-11e7-8c46-db652f340b46.png">

This is Google on Windows:
<img width="244" alt="2017-07-23 16_49_59-google" src="https://user-images.githubusercontent.com/15178410/28498018-4a2ba240-6fc7-11e7-8854-28894ea970e6.png">

Google won't fix this.

**Comment by Eloston** [comment]
Could you clarify what you mean by "arbitrary"? Additionally, what specifically do you consider to be "Windows native style"?

For my curiosity, do you mind posting a source to your claim that Google won't change this?

**Comment by zcyzcy88** [comment]
You should obey the system's style guide.
**Use Windows's default style**, instead of implement your own.

Specification: https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392.aspx
The source of Google won't change this: https://superuser.com/a/630510

**Comment by Artur96** [comment]
@zcyzcy88 If you're looking for UI consistency, then Windows is not the operating system to go for, considering that Windows 10 UI alone has [several different context menus](https://www.reddit.com/r/Windows10/comments/6a6c0s/context_menu_consistency_in_windows_10/).

**Comment by Eloston** [comment]
My knowledge on this is limited, but I believe Chrome uses its own rendering engine for its UI. It also has a consistent UI across all of its desktop platforms. So changing the context menu style may not be trivial.

**Comment by zcyzcy88** [comment]
@Artur96 You are true, but it is even not consistency inside self.

<img width="595" alt="2017-07-26 04_28_24-new tab - chromium" src="https://user-images.githubusercontent.com/15178410/28592253-ffbac916-71ba-11e7-8a67-5b19da5f4846.png">
<img width="595" alt="2017-07-26 04_28_35-new tab - chromium" src="https://user-images.githubusercontent.com/15178410/28592264-07a108ac-71bb-11e7-81a1-112527111faf.png">

---

@Eloston Bad argument.

> Chrome uses its own rendering engine for its UI.

Gecko (Firefox engine) also, but Gecko did it.

> It also has a consistent UI across all of its desktop platforms.

False. Chrome obey the standard on Mac.

**Comment by Eloston** [comment]
@zcyzcy88 What I mean is [Aura](http://dev.chromium.org/developers/design-documents/aura), which is not the same thing as the **web** rendering engine Blink.

Apparently macOS doesn't use Aura, which is why the style is not the same there ([source](https://stackoverflow.com/a/23974934))

**Comment by Eloston** [comment]
@zcyzcy88 Regarding your images, it's possible the context menu in the top image is from the title bar. The title bar might be rendered by Windows, not Chrome, so the style wouldn't be different.

**Comment by Streetwalrus** [comment]
I just want to pitch in to say that this might be out of scope for this project, whose goal is to remove Google's spyware from Chromium. If you want to mess with the UI design, you should maintain a separate patchset for that.

Just my two cents.

**Comment by Eloston** [comment]
@Streetwalrus You are correct, but I would be fine with it if someone is able to continually maintain such patch and it doesn't interfere with main development (within reason). The motivations of this project describe the core changes I want in a Chromium browser, but I don't mind other changes if they don't deviate too far from how Chromium looks and behaves.

**Comment by fitzha** [comment]
This issue should be closed.
