### ISSUE TITLE
Error of: mkdir() got unexpected keyword argument 'exist_ok' while trying to build version 58.0.3029.110-1 on Gentoo Linux

### ISSUE THREAD

**Issue by bennyprofane** [Eloston/ungoogled-chromium#245]
Here's my steps:

    export UTILIKIT_CONFIG_TYPE=linux_simple
    mkdir build/
    mkdir build/sandbox
    mkdir build/downloads
    ./utilikit/prepare_sources.py
    ./utilikit/substitute_domains.py
    ./utilikit/generate_build_files.py linux_simple --apply-domain-substitution
    
And this give an error referring to line 42 in `utilikit/_build_files_generators/linux_simple.py`:

    line 42, in generate_build_files 
        linux_simple_dir.mkdir(exist_ok=True)

    TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

I'm running Gentoo Linux, python version 3.4.5, but I also tried it on another Gentoo computer running python 2.7.10

I tried just removing the `exist_ok=True` argument and then another similar error happens in another file so I removed that `exist_ok=True` argument too. And then there's some other errors. Basically I can rig it to kind of do something if I add some `Try...Except` clauses, but even after messing around with all of that I end up with another dead end where it's complaining about line 10 in the build.sh script where the error is `./out/Default/gn: No such file or Directory` 

But because I had to rig it up to even get to that point I'm not sure if that's what would have even happened if `exist_ok=True` could have remained as intended. 

Are there any build instructions for how 9Morello was able to generate the 55.0.2883-75-1 semi-statically linked 64-bit linux build? Because that one works on my machine. I am just looking to build a binary for the newer 58 version.

**Comment by Eloston** [comment]
`exist_ok` was introduced in Python 3.5. The other errors are probably due to features introduced in Python 3.5. `subprocess.run` was also introduced in Python 3.5. Does Gentoo not have Python 3.5?

**Comment by bennyprofane** [comment]
I didn't even think about the 3.4 vs 3.5 python differences. So here's where I'm at now:

I installed python 3.5 and gentoo lets you switch between python versions with the eselect command so I switch to python 3.5 and the following commands all appear to work. No more "exist_ok" errors:

    export UTILIKIT_CONFIG_TYPE=linux_simple
    mkdir build/
    mkdir build/sandbox
    mkdir build/downloads
    ./utilikit/prepare_sources.py
    ./utilikit/substitute_domains.py
    ./utilikit/generate_build_files.py linux_simple --apply-domain-substitution

Next I run the following:

    cd build/sandbox
    ./ungoogled_linux_simple/build.sh

But it complains about print statements so that makes me think that the bootstrap.py script needs to be run as python 2.7 so I switch to python 2.7 with eselect and I run this command again:

    ./ungoogled_linux_simple_build.sh

And it appears to do a bunch of c++ commands and it gets to [347/347] and then it says "FAILED: gn"

Here's the output from there:

    [347/347] c++ -pthread -o gn -Wl,--start-group tools/gn/gn_main.o libevent.a base.a xdg_user_dirs.a gn_lib.a dynamic_annotations.a -Wl,--end-group -lrt -latomic
    FAILED: gn 
    c++ -pthread -o gn -Wl,--start-group tools/gn/gn_main.o libevent.a base.a xdg_user_dirs.a gn_lib.a dynamic_annotations.a -Wl,--end-group -lrt -latomic
    base/threading/thread_task_runner_handle.o: In function `base::ThreadTaskRunnerHandle::OverrideForTesting(scoped_refptr<base::SingleThreadTaskRunner>)':
    thread_task_runner_handle.cc:(.text+0x832): undefined reference to `base::ScopedClosureRunner::ScopedClosureRunner(base::Callback<void (), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&)'
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
    Command '['ninja', '-C', '/tmp/tmpZT6cfl', '-v', 'gn']' returned non-zero exit status 1
    ./ungoogled_linux_simple/build.sh: line 10: ./out/Default/gn: No such file or directory
    ninja: Entering directory `out/Default'
    ninja: error: loading 'build.ninja': No such file or directory

Are there some other important preparation steps that I'm missing? 

I also just ran it again and redirected stderr to a separate file and this is what is says:

    No patches in series
    DEBUG:root:Running: /home/bennyprofane/ungoo/ungoogled-chromium-58.0.3029.110-1/build/sandbox/build/write_buildflag_header.py --output base/allocator/features.h --gen-dir /tmp/tmpztWtHE/gen --definitions /tmp/tmpztWtHE/gen/base/allocator/features.h.tmp
    DEBUG:root:Running: /home/bennyprofane/ungoo/ungoogled-chromium-58.0.3029.110-1/build/sandbox/build/write_buildflag_header.py --output base/debug/debugging_flags.h --gen-dir /tmp/tmpztWtHE/gen --definitions /tmp/tmpztWtHE/gen/base/debug/debugging_flags.h.tmp
    DEBUG:root:Running: /home/bennyprofane/ungoo/ungoogled-chromium-58.0.3029.110-1/build/sandbox/build/write_build_date_header.py /tmp/tmpztWtHE/gen/base/generated_build_date.h default
    DEBUG:root:Running: ninja -C /tmp/tmpztWtHE -v gn
    Command '['ninja', '-C', '/tmp/tmpztWtHE', '-v', 'gn']' returned non-zero exit status 1
    ./ungoogled_linux_simple/build.sh: line 10: ./out/Default/gn: No such file or directory
    ninja: error: loading 'build.ninja': No such file or directory

What does "No patches in series" mean? Am I supposed to manually load patches into that directory or file?

**Comment by Eloston** [comment]
Hm, that's strange. Is there a file named `series` in `ungoogled_linux_simple/patches`?

**Comment by bennyprofane** [comment]
Yes the series file is there but when I opened it in vim it's blank.

**Comment by Eloston** [comment]
Sorry for taking so long to respond. Got caught up in other things.

`linux_simple` is not a valid utilikit config type. That is only a packaging type. You probably want to specify `linux_conservative`, which has conservative settings.

Also, it took me too long to realize how incomprehensibly cryptic my documentation is. I'll be overhauling it for the next release, as well as utilikit (yet again).

**Comment by Eloston** [comment]
Closing due to activity.
