### ISSUE TITLE
Sites stopped working.

### ISSUE THREAD

**Issue by h4ckee** [Eloston/ungoogled-chromium#2459]
### OS/Platform

Portable Linux

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

116.0.5845.96

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Sites stopped working

### How to Reproduce?

1. Go to https://aliexpress.ru
Press Sign In button
Enter email/password
Slide the button to the right position

2. Go to https://lk.mts.ru

### Actual behaviour

When I try to login https://aliexpress.ru a window pops up saying: "Sorry, we have detected unusual traffic from your network. Please slide to verify." It doesn't matter how many times you slide the button it reappears again and again.

When I try to login https://lk.mts.ru, site says:
403 Error
Forbidden
Access to login.mts.ru is forbidden.
Try accessing the site login.mts.ru later or contact administration of the site.

### Expected behaviour

1. Go to https://aliexpress.ru
Press Sign In button
Enter email/password
Optionally: Slide the button to the right position
You're logged in
 

2. Go to https://lk.mts.ru
A login window should appear

I have tested them with other browsers (thorium and firefox) and there they work as expected.

### Additional context

https://github.com/clickot/ungoogled-chromium-binaries/releases/download/116.0.5845.96-1/ungoogled-chromium_116.0.5845.96-1.1_linux.tar.xz

**Comment by PF4Public** [comment]
@clickot Is something wrong with that binary?

**Comment by clickot** [comment]
it works for me. Don't think that the described behaviour is build-specific. h4ckee reported that this behaviour exists for some versions now..

**Comment by PF4Public** [comment]
@h4ckee Do you have JIT enabled or disabled in website settings panel?
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/10319700/4aa8a264-d360-4e25-b956-ccf38509d352)

**Comment by PF4Public** [comment]
> Javascript is enabled everywhere

The question was about JIT.

Also please try reproducing your issue with an empty profile using --user-data-dir command line argument.

**Comment by LingamYoni** [comment]
@h4ckee 
I am experiencing the same issue described in this issue. I can provide more information and logs if necessary. Would it be possible to reopen this issue so that the developers can look into it again? 

I have tried the suggestions in the comments but none of them have worked for me.

**Comment by touba-denrael** [comment]
@LingamYoni, one of the last [admittedly remote] possiblities might be checking your `chrome://settings/content/v8` optimizer settings [enabled or disallowed].

**Comment by PF4Public** [comment]
IIRC there was a problem with the protection mechanism of the website itself, which would make it nearly impossible to even attempt to fix.

**Comment by LingamYoni** [comment]
> @LingamYoni, one of the last [admittedly remote] possiblities might be checking your optimizer settings [enabled or disallowed].`chrome://settings/content/v8`

I've tried changing the optimizer settings as you suggested, but unfortunately that didn't resolve the issue. Any other suggestions would be greatly appreciated.

**Comment by LingamYoni** [comment]
It seems like you're right, @h4ckee . It's highly probable that these websites have implemented security measures that actively prevent logins or specific functionalities when they detect unusual behavior or are unable to track users effectively. This might involve blocking certain browser configurations, detecting the absence of specific JavaScript execution patterns, or other methods.

While it's frustrating that we haven't found a direct workaround within Ungoogled Chromium, perhaps we should focus on understanding these security mechanisms better. Investigating how these websites identify and block "unusual" activity might provide insights for potential solutions or workarounds.

Would you be open to exploring this further? We could start by analyzing network requests and responses during login attempts to identify any telltale signs or discrepancies.

**Comment by LingamYoni** [comment]
@h4ckee, you're absolutely right, every site likely has its own unique "browser check-in" mechanisms, and trying to find specific workarounds for each could be a tedious and endless endeavor. I understand the appeal of using a separate, less privacy-focused browser for those specific cases.

However, juggling multiple browsers just for compatibility feels cumbersome. Ideally, a single browser could strike a balance between privacy and functionality.  

I've reached out to the AliExpress development team, explaining the situation and hoping they might provide some insight into why Ungoogled Chromium triggers their security measures.  Perhaps they can offer suggestions or adjustments that wouldn't compromise user privacy. It's a long shot, but worth a try.

**Comment by AlexeiMezin** [comment]
Any progress with that issue?

**Comment by LingamYoni** [comment]
BTW, I'm happy to report that the issue seems to be completely resolved. We've had several AliExpress releases in a row now that have worked flawlessly. So it looks like whatever was causing the problem has been fixed on their end for good.

**Comment by h4ckee** [comment]
> BTW, I'm happy to report that the issue seems to be completely resolved. We've had several AliExpress releases in a row now that have worked flawlessly. So it looks like whatever was causing the problem has been fixed on their end for good.

You're absolutely right, LingamYoni!
Aliexpress forks just fine on my side too!
At last!
