### ISSUE TITLE
Chromium updated itself to 59.0.3071.104

### ISSUE THREAD

**Issue by ik9999** [Eloston/ungoogled-chromium#246]
I was using binaries from here 

https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/debian/stretch_amd64/58.0.3029.110-1

for v58.0.3029.110-1.
Today, chromium updated itself to 59.0.3071.104. Is this ok?

**Comment by Eloston** [comment]
The names of ungoogled-chromium's Debian packages match Debian's builds of Chromium. There is no v59 release of ungoogled-chromium.

I will probably change the package name next release because it's become a hassle for me to hold back the Chromium packages.
