### ISSUE TITLE
Issue creating a source package "SP"

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#25]
dpkg-source: fallo: no se puede construir con el formato de fuente «3.0 (quilt)»: no se ha encontrado ningún archivo tar de la fuente original en ../chromium-browser_51.0.2704.81.orig.tar{bz2,gz,lzma,xz}
   

i suggest you manage the download with wget   using -O option   for generate this chromium-browser_51.0.2704.81.orig.tar

**Comment by Eloston** [comment]
I'll implement a way of generating all of the required files with the new build system.
