### ISSUE TITLE
window source file compiling problem

### ISSUE THREAD

**Issue by nusicvvv** [Eloston/ungoogled-chromium#251]
I am grateful to you for the work and the idea, ungoogled chromium is really a must. And sadly I got problems in the very first place even extract the source from compressed tar file under windows 7 x64. I wonder what should set the env 'UTILIKIT_CONFIG_TYPE to under win7 x64. I set it to 'windows', and prepare_sources.py works fine when downloading .tar.xz file,(over 400mb) but it failed to extract it to the source folder, with an err message  and stopped. I found the xz file and tried to extract it manually and still got same error (complaining about symbolic link file was not supported, paths got too deep), I guess the utilikit might have downloaded wrong source file package that was made for linux os. can you give me some clue?

**Comment by Eloston** [comment]
I'd advise you not to build for Windows yet. See #235 and #215 for more details.

FYI, the source package and symbolic link issue you're having is normal. The Python scripts used for extraction either attempt to create a symlink or just ignore it completely.
