### ISSUE TITLE
add binary download to release

### ISSUE THREAD

**Issue by chantisnake** [Eloston/ungoogled-chromium#252]
Hi, I am the maintainer of ungoogled-chromium's chocolatey package: https://chocolatey.org/packages/ungoogled-chromium

My update scripts depends on a powershell module: (github2choco)[https://github.com/chantisnake/github2choco], which automatically converts GitHub release to chocolatey packages.

It would help me a great deal if you can add your binary download to your release.

I feel terribly sorry to disturb you, but there are people waiting to use the latest version of your app.

Best,
Cheng

**Comment by wimh** [comment]
Looks like the windows build has to be fixed first (#215).
In #235 I read it is easy to add the binary download to the release when it's available:
> Yeah. It takes little effort to publish binaries once support is there.

**Comment by Eloston** [comment]
@chantisnake 

> It would help me a great deal if you can add your binary download to your release.

Do you mean GitHub Releases, or the ungoogled-chromium contributor binary downloads page? Or are you asking for a Windows support update (i.e. how @wimh interpreted the message)?

**Comment by chantisnake** [comment]
just adding downloads to GitHub release.

**Comment by Eloston** [comment]
The GitHub Releases of this repository in particular or of any other contributor's repository?

**Comment by chantisnake** [comment]
This current repo would work. Thanks.

**Comment by Eloston** [comment]
I've stopped posting binaries to this repo. Binaries are now uploaded to forks of [ungoogled-chromium-binaries](//github.com/ungoogled-software/ungoogled-chromium-binaries), which are then referenced by the `.ini` files and generated HTML files in that repository.

**Comment by chantisnake** [comment]
The thing is I need the binary file in the `release` page for my script to find it.

Is it possible that you can add them to the release instead of in the git repo?

I am terribly sorry about the trouble I have caused.

Best,
Cheng

**Comment by Eloston** [comment]
Sorry, but the current binary publishing system doesn't allow for that. The system was designed to meet two requirements:

1) A group of people (currently me) manages what gets published.
2) The same group of people need not to do a lot of work to publish binaries.
3) It should be relatively straight-forward and simple for builders to submit binaries for publishing, but requirement no. 2 takes priority within reason.

You could try writing up a simple script to poll the GitHub Atom feed for recent commits, and then check for new `.ini` files in the [`windows` platform configuration directory](https://github.com/ungoogled-software/ungoogled-chromium-binaries/tree/master/config/platforms/windows). Then the `.ini` files can be parsed for direct download links to the binaries.

I also apologize for any inconveniences this system has caused you, but it's the best one I could think of so far. If you have a better method that meets my three requirements, then I would be happy to hear it.

**Comment by chantisnake** [comment]
I totally understand. Thank you.
