### ISSUE TITLE
Cannot build v60 from the develop branch on Ubuntu 16.04

### ISSUE THREAD

**Issue by dubvulture** [Eloston/ungoogled-chromium#254]
I tried to build the new release on Ubuntu 16.04 and I found some problems.
Note: linux_conservative uses the main compiler on the system so I assume gcc is a valid option.

1. g++ doesn't work, unknown argument  `-fsanitize=cfi-vcall` (and maybe others)
2. Switched to clang++ (version 3.8) another unknown argument, `-fwhole-program-vtables`
3. Switched to clang++ (version 3.9) which should have this argument. ~~**Currently building.**~~ EDIT: failed (see comments below)

I know almost nothing about the building process of chromium so let me know how it should be handled.

To fix this now the following lines have to be changed:

- `use_clang=true` [here](https://github.com/Eloston/ungoogled-chromium/blob/develop/resources/configs/linux_conservative/gn_flags)
- `clang (>= 3.9) [here](https://github.com/Eloston/ungoogled-chromium/blob/develop/resources/packaging/debian/conservative/control) unless that missing argument had another name in 3.8 (I checked quickly on the [manual](http://releases.llvm.org/3.8.0/tools/clang/docs/UsersManual.html) but it doesn't look like it)
- remove gcc/g++ dependencies in the abovementioned file

**Comment by Eloston** [comment]
In the latest commit (which is after the successful build I made), I enabled cfi for all platforms to follow xsmile's changes for Inox. I'll probably disable it for now since it will decrease performance a bit (unless cancelled out with LTO which I didn't enable due to the memory requirements, and Debian doesn't come with a new enough Clang to use ThinLTO).

**Comment by Eloston** [comment]
7f238719fa0a16e40559df36988aecf0082a8cf3 removes `is_cfi=true`. This might fix the problems you're having with GCC.

If Clang 3.9 is working for you, you could also try to follow the Debian 9 (stretch) instructions. It has more flags and uses more system libraries, but there may be some libraries in 16.04 that are too old. `linux_conservative` does not have these changes; it is intended to be a "lowest common denominator" build configuration that can build on a variety of system configurations.

**Comment by dubvulture** [comment]
Build failed throwing a lot of `error: member access into incomplete type 'AVCodecParameters'`, see [gist](https://gist.github.com/dubvulture/b644d80ea2f745c75a5f814c6d4ecec1)

Tomorrow I'll try again with gcc and the new commit.

**Comment by Eloston** [comment]
Those are some interesting errors. There shouldn't be any other changes to media-related flags other than `rtc_libvpx_build_vp9` which I think is WebRTC-specific (and your errors don't seem to be specific to WebRTC).

It could be possible that `is_component_ffmpeg=true` on its own is breaking the build... Ubuntu also sets `is_component_build=true`. However, Ubuntu's xenial build uses Clang 4.0 now.

You might have better luck if you use clang-4.0 by modifying `CLANG_BASE_PATH` in `debian/rules` and change the component GN flags.

FYI, ungoogled-chromium's configuration builds with proprietary codecs by default. You'll need to change the FFmpeg branding and proprietary codecs GN flags if you don't use the system's FFmpeg. `linux_dynamic` and its descendents are the only configurations that use the system's FFmpeg.

**Comment by dubvulture** [comment]
With 7f238719fa0a16e40559df36988aecf0082a8cf3 both clang 4.0 and gcc 5.4.0 finished building successfully. (tomorrow I'll check again clang 3.8 and 3.9)

However, both produced the following warnings:
```
dpkg-shlibdeps: warning: couldn't find library libffmpeg.so needed by debian/ungoogled-chromium/usr/lib/chromium/chromium (ELF format: 'elf64-x86-64'; RPATH: '')
        install -d debian/ungoogled-chromium-l10n/DEBIAN
        install -d debian/ungoogled-chromium-shell/DEBIAN
        dpkg-shlibdeps -Tdebian/ungoogled-chromium-shell.substvars debian/ungoogled-chromium-shell/usr/bin/chromium-shell
dpkg-shlibdeps: warning: couldn't find library libffmpeg.so needed by debian/ungoogled-chromium-shell/usr/bin/chromium-shell (ELF format: 'elf64-x86-64'; RPATH: '/usr/bin/.')
        dpkg-shlibdeps -Tdebian/ungoogled-chromium-widevine.substvars debian/ungoogled-chromium-widevine/usr/lib/chromium/libwidevinecdmadapter.so
dpkg-shlibdeps: warning: couldn't find library libwidevinecdm.so needed by debian/ungoogled-chromium-widevine/usr/lib/chromium/libwidevinecdmadapter.so (ELF format: 'elf64-x86-64'; RPATH: '/usr/lib/chromium/.')
```

**Comment by Eloston** [comment]
The libffmpeg.so warning can be fixed by splitting off a separate package just for libffmpeg.so like Ubuntu has it, so chromium-shell and regular Chromium can both depend on it. Or FFmpeg can be statically linked into the main executables.

The Widevine warning is fine, since that shared library is provided by the user when they want to use Widevine DRM.

Were you able to test the main browser by installing and running it?

**Comment by dubvulture** [comment]
>The libffmpeg.so warning can be fixed by splitting off a separate package just for libffmpeg.so like Ubuntu has it, so chromium-shell and regular Chromium can both depend on it. Or FFmpeg can be statically linked into the main executables.

Does this mean that it has to be included in the final release build or it's not necessary?

> Were you able to test the main browser by installing and running it?

Yes, both build ran fine. Note: the previous version had to be uninstalled manually. due to the package name change.

**Comment by dubvulture** [comment]
Anyway, just for the record, with the new commit:

- clang 3.8 - [**failed**](https://gist.github.com/dubvulture/c91ee7cd4017a30965163e9538d1f285) (compiler problem, maybe due to ubuntu patches? who knows)
- clang 3.9 - **successful**

**Comment by Eloston** [comment]
> Does this mean that it has to be included in the final release build or it's not necessary?

FFmpeg is required, but how it's included doesn't matter too much. I'll probably just change it to static linking since it's easier, since the problem with proprietary codecs remains with either option.

**Comment by Eloston** [comment]
baf81bb4b0c712bfbaf1ab5b5a6496b691e90a68
