### ISSUE TITLE
UG and tmpfs?   

### ISSUE THREAD

**Issue by nyancat18** [Eloston/ungoogled-chromium#257]
according to gentoo wiki  i need 13GB for build it at RAM *tmpfs*

how much ram i need for make it with   UG  *fx 8350 16 ram*

https://wiki.gentoo.org/wiki/Portage_TMPDIR_on_tmpfs

**Comment by Eloston** [comment]
It is impossible with 16 GB. IIRC, I've seen my build directory consume around 40 GB after the build finished. You will also need at least 8 GB for compiling and linking.

It may be possible to build with 64 GB of RAM (assuming you configure tmpfs to grow large enough. I think the default maximum is half the available RAM).

Also:

https://github.com/gcarq/inox-patchset/issues/93
https://github.com/gcarq/inox-patchset/pull/90#issuecomment-325148498

Are you in a hurry or something?

**Comment by perfect7gentleman** [comment]
I have 16gb RAM, 13gb tmpfs, 13gb zram, no swap file. Have no problem building Chromium.

**Comment by nyancat18** [comment]
@perfect7gentleman     with only 3  for work )16-13)
i may be safe?

**Comment by perfect7gentleman** [comment]
@nyancat18, not 3 for work, but 16, as tmpfs can be empty

**Comment by Eloston** [comment]
@perfect7gentleman How much does the whole build tree take at most?

**Comment by perfect7gentleman** [comment]
@Eloston, honestly don't know, never made any measurements.

**Comment by nyancat18** [comment]
@perfect7gentleman **BUT**

with just 16GB  (ram)

and a  Ryzen 5 1600  *the best, and more tested*

could i build *inox* at **tmpfs**?

of i need made it at hdd *80-90 mins more* / ssd *20-30 extra*

**Comment by Eloston** [comment]
@nyancat18 perfect7gentleman said that Chromium can build with just 16 GB of RAM and no swap file. The CPU used does not have an effect.

I would like to try it myself when I get the chance. It would definitely speed up compilation.

**Comment by Eloston** [comment]
Building entirely from `tmpfs` does work, and is noted in 417b43295b94354c4a269e2a6d0ef145cea029bb for Debian Stretch builds.
