### ISSUE TITLE
Is there a way to remove profile icon on next build?

### ISSUE THREAD

**Issue by shak3800** [Eloston/ungoogled-chromium#259]
First of all i really like the ungoogled chromium . It feels very light and fast and of course private .

Is it possible since we are not using the Sign In To Google services , to remove the profile button (avatar) ? I remember there was a patch for an older version but i don't know if this will work for the upcoming release.

Is there any temp workaround to hide it?

Thanks a lot!

**Comment by woolyss** [comment]
You talk about this patch https://github.com/hparadiz/chromium-disable-profile-button-patch
No, it doesn't work on new Chromium versions.

**Comment by Artur96** [comment]
It is possible to write a patch to disable the avatar button, but I'm not sure whether that would be desirable for people who use multiple profiles. I don't see any Google-specific sign in option on the latest build.

**Comment by xsmile** [comment]
You can use something like this patch https://raw.githubusercontent.com/xsmile/inox-patchset/e111eb8dadedbb9fa673f0a7bb129d10ab93fe2e/9003-disable-avatar-button.patch which disables the button unless it is enabled via chrome://flags.
Alternatively as mentioned by @Artur96 it might be better to keep it enabled by deault unless the user disables it.

**Comment by Eloston** [comment]
The reasoning from @Artur96 is correct. AFAIK privacy and security are still intact with that button, so I see no reason to make a cosmetic change that deviates from Chromium's behavior.
