### ISSUE TITLE
Broken domain reliability dependency on json file in baked_in_configs.cc

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#26]
make[1]: se sale del directorio '/home/meh/uchrome/build-sandbox'
   debian/rules override_dh_auto_build-arch
make[1]: se entra en el directorio '/home/meh/uchrome/build-sandbox'
ninja  -C out/Release chrome chrome_sandbox chromedriver
ninja: Entering directory `out/Release'
ninja: error: '../../components/domain_reliability/baked_in_configs/c_android_clients_google_com.json', needed by 'obj/components/domain_reliability.gen/domain_reliability/baked_in_configs.cc', missing and no known rule to make it
debian/rules:141: fallo en las instrucciones para el objetivo 'override_dh_auto_build-arch'
make[1]: *** [override_dh_auto_build-arch] Error 1
make[1]: se sale del directorio '/home/meh/uchrome/build-sandbox'
debian/rules:134: fallo en las instrucciones para el objetivo 'binary'
make: *** [binary] Error 2
dpkg-buildpackage: fallo: fakeroot debian/rules binary devolvió un estado de salida de error 2

xenial 64

**Comment by Eloston** [comment]
Thanks for this. I still haven't built Chromium yet (I'm working on the build system and converting to GN) so I recommend you don't use the patches yet. You should wait until I release a new tag.

**Comment by Eloston** [comment]
I haven't encountered this error in my build. I will release a new tag version soon (within a day or two) so you can try building with that.
