### ISSUE TITLE
Why when i close chromium , next time i open it i have to sign in again in sites?

### ISSUE THREAD

**Issue by shak3800** [Eloston/ungoogled-chromium#260]
Hi!

Don't know if this is an issue or not , but each time i close my session and the reopen the browser i need to sign in again to sites that i was logged in before i close the browser.

Is this default behavior for security reasons?

**Comment by Artur96** [comment]
By default, cookies are not saved after closing the browser.

**Comment by shak3800** [comment]
@Artur96  Thanks for the information!

**Comment by englishextra** [comment]
@arturkomoter

You have to uncheck in advanced options in settings - keep cookies until browser closes
