### ISSUE TITLE
What should I do to get the modified source file?

### ISSUE THREAD

**Issue by lenomirei** [Eloston/ungoogled-chromium#261]
What should I do to get the source code after the patch(the source code with out google)?
Sorry for my poor English......

**Comment by Eloston** [comment]
If you're following the build instructions, just ignore the `generate_build_files.py` step and everything afterwards.

FYI, domain substitution or source cleaning may break support for some platforms right now.

**Comment by lenomirei** [comment]
Thanks a lot!
