### ISSUE TITLE
Manifest v2 Support - Google will roll out Manifest v3 on June 2024

### ISSUE THREAD

**Issue by Keirnoth** [Eloston/ungoogled-chromium#2623]
I've seen issue #662 already and you guys said that you are going to do something about it when "Google says they're going to do it."

Well, now they are:

https://arstechnica.com/google/2023/12/chromes-next-weapon-in-the-war-on-ad-blockers-slower-extension-updates/
https://arstechnica.com/gadgets/2023/11/google-chrome-will-limit-ad-blockers-starting-june-2024/

https://developer.chrome.com/blog/resuming-the-transition-to-mv3/

The rollout will be "slow", and I'm praying that enough people yell at them to just call this stupidity off altogether, but it now sounds like they're hellbent on pushing this out since they're trying so hard to stop extensions like uBlockOrigin from working.

Do you guys have any ideas on whether you plan on preserving Manifest v2 in Chromium like Mozilla is or finding some sort of workaround to this?  Perhaps working with the UBO guys to permanently implement their ad blocker into your browser?

**Comment by Keirnoth** [comment]
> What is the reason for opening yet another issue instead of continuing the discussion in the existing one?

Apologies, I'm just an end user so I am still learning Github etiquette.  However, considering the last comment in the previous issue was from *last year*, I thought a new thread with brand new information bringing light to the issue would be ideal.  Once again that's my fault.

I will close this issue and move it to the other thread.  Thank you.

**Comment by Keirnoth** [comment]
Duplicate, see issue #662 for post.

**Comment by Maxxee** [comment]
> What is the reason for opening yet another issue instead of continuing the discussion in the existing one?

And what exactly is the reason to be such an irrelevant fracktard w/o providing a link to his claim!

**Comment by networkException** [comment]
Language, please.

**Comment by michalrus** [comment]
@Maxxee, the link is literally on the first line of the issue description, so @Keirnoth knew what he/she did:

> I've seen issue https://github.com/ungoogled-software/ungoogled-chromium/issues/662 already and you guys said that you are going to do something about it when "Google says they're going to do it."
