### ISSUE TITLE
studying code

### ISSUE THREAD

**Issue by nyancat18** [Eloston/ungoogled-chromium#264]
how can  i  convert   ungoogled-chromium  to a *standard+automatized* build process? 

* dpkg-build package

* pkgbuild  *just bash*

* ebuild  *bash with aliases...complex*

* slackbuild

* rpm **yeah, its a hell**

**Comment by xsmile** [comment]
That's an interesting question. [fpm](https://github.com/jordansissel/fpm) for instance can generate platform-specific packages for dpkg, RPM, pacman and some other package managers.

**Comment by Eloston** [comment]
I don't think I understand your question @nyancat18, but based on what @xsmile said, `utilikit` is supposed to be an extensible framework to build for multiple different platforms. But I haven't heard of fpm before; might be interesting to look into.

**Comment by nyancat18** [comment]
@eloston  i  talk  about  how translate utilkit's work  to bash (good for pkgbuild)

**Comment by Eloston** [comment]
@nyancat18 `utilikit` can already be scripted based on the build instructions if you want that. Otherwise, `utilikit` can generate a shell script for buliding on Linux.
