### ISSUE TITLE
UG/C-61  and some death flags

### ISSUE THREAD

**Issue by nyancat18** [Eloston/ungoogled-chromium#265]
death flags,   if you put it you cant compile it (builds until LIINK ./CHROME after...errors)

examples

* 'enable_service_discovery=false'

* 'enable_mdns=false'

idk why this gn flags didnt work with chromium 61 + your patches

**Comment by Eloston** [comment]
Fixed in 91a96717f6e5a2b1ee191c0c94dd8eb6aef8fe92
