### ISSUE TITLE
ungoogled-chromium-os

### ISSUE THREAD

**Issue by Quenz** [Eloston/ungoogled-chromium#270]
Any chance of a project like this at any point? I know it would take some time and effort, but I think it's a nice idea.

**Comment by Eloston** [comment]
In the forseeable future? Probably not. There's not enough activity for the project to keep up-to-date. If anything, only support for new platforms (mobile or desktop) will be added.

Of course, I'm not going to reject anyone that wants to add support for this themselves, but I don't think it would be a wise time investment for most at this stage.

**Comment by Eloston** [comment]
Closing for above reasons.

**Comment by cjbd** [comment]
sorry for digging up old ticket, it's been a while, any plan for ungoogled-chromium-os?
to build ungoogled chromium on chromium os, which repo to use, [ungoogled-chromium-portablelinux](https://github.com/ungoogled-software/ungoogled-chromium-portablelinux)?
thanks!
