### ISSUE TITLE
Widevine crash on Netflix

### ISSUE THREAD

**Issue by solinium** [Eloston/ungoogled-chromium#272]
I'm on the latest release (58.0.3029.110-1) on Debian 9.2 with kernel 4.9.0 and GNOME. I followed your instructions on the FAQ on getting Widevine and it works for the most part. The demo at demo.castlabs.com works fine. After watching Netflix for a few minutes playback will stop and you get a message saying something like 'Widevine Decryption Module has crashed. Please reload'. Reloading doesn't help, and restarting the browser works but It's only a few minutes before it happens again.

**Comment by Eloston** [comment]
The instructions should always download the latest stable version of Chrome (which is version 61 at the time of writing). This is three versions ahead of the current stable for ungoogled-chromium, so there may be some incompatibilities that are causing it to fail. You might have better luck if you get the Widevine module from Chrome 58.

**Comment by solinium** [comment]
Thanks for the reply, I'll try that. I'll also make a quick pull request to update the FAQ.
