### ISSUE TITLE
How to build chrome 49 for windows xp?

### ISSUE THREAD

**Issue by CBEPX** [Eloston/ungoogled-chromium#276]
Subj. Need build chromium without any telemetry services for win xp, But there were problems.  Is there a  configuration or instruction for building?

**Comment by Eloston** [comment]
49 came out so long ago that I don't even remember much from back then. I went to check and found out that was still when I only supported Debian.

So, no. There is no configuration or instructions for building version 49 on Windows XP. I don't think it is reasonable for me to support a browser that is 13 major versions old, so I'm afraid you'll need to go elsewhere for additional help.
