### ISSUE TITLE
[Deleted] Solved

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#2766]
deleted due to unnecessariness.

**Comment by touba-denrael** [comment]
in addition to the above, you might want to check if any flag with `cr23` and `gm3` in its description is enabled.

**Comment by brunnopleffken** [comment]
Remember that we do not know how long these flags will last.

I don't like this redesign either. I find the new tab bar extremely clunky — a terrible mix between the old tab bar and the "button tab bar" from Firefox. Some buttons and menu items are exaggeratedly large, while others remain small.

I initially thought this was still under development, but after a while, it seems like it's definitely here to stay.
