### ISSUE TITLE
Cannot build 62.0.3202.62 on macOS 10.13

### ISSUE THREAD

**Issue by sCreami** [Eloston/ungoogled-chromium#277]
Hi,

I tried to build chromium 62 on macOS 10.13 using the patch on the develop branch but I occurred many errors. As the log file is kind of long and disgusting, I'm pasting it there: http://sprunge.us/IBcD

I'll also highlight that a patch fails. Could someone help me on this please?

```
Extracting clang+llvm-4.0.0-x86_64-apple-darwin.tar.xz...
Applying patch ungoogled_macos/patches/debian/gn/parallel.patch
patching file tools/gn/bootstrap/bootstrap.py
Hunk #1 succeeded at 111 (offset 8 lines).
Hunk #2 succeeded at 208 (offset 7 lines).

Applying patch ungoogled_macos/patches/debian/gn/buildflags.patch
patching file build/toolchain/linux/BUILD.gn
Hunk #3 succeeded at 113 (offset 8 lines).
Hunk #4 succeeded at 170 (offset 16 lines).

Applying patch ungoogled_macos/patches/debian/gn/scheduler.patch
patching file tools/gn/bootstrap/bootstrap.py
Hunk #1 FAILED at 490.
1 out of 1 hunk FAILED -- rejects in file tools/gn/bootstrap/bootstrap.py

```

**Comment by Eloston** [comment]
62 isn't ready on my own platform, so it won't be ready to test on other platforms. I'll announce in #262 when it is ready for test building on other platforms (which I hope isn't too long from now).
