### ISSUE TITLE
import function does not name the Firefox profiles that it imports from

### ISSUE THREAD

**Issue by libBletchley** [Eloston/ungoogled-chromium#280]
When using the import function, Chromium bluntly proposes "Mozilla Firefox" as a source without mentioning any of the ~6 or so profiles created by Firefox.  It looks like this:
![chromium_import](https://user-images.githubusercontent.com/18015852/32220674-e38d2620-be32-11e7-86aa-a5f47ef8a2b5.png)

Which profile is it sourcing the data from?  I think it's bug that no profile is mentioned, but perhaps consider the feature request of finding all profiles and offering each of them as choices in the pull-down menu.

**workaround** Launch `firefox-esr -ProfileManager` and make the profile you want to import from the default one.  Launch Chromium and import from "Mozilla Firefox".  Then run `firefox-esr -ProfileManager` again to restore the original default profile.

**Comment by Eloston** [comment]
Sorry, but ungoogled-chromium doesn't have enough resources to handle feature requests like these. This should be reported upstream.

If anyone is willing to maintain a patch for this, then feel free to submit one.
