### ISSUE TITLE
userContent.css not imported from firefox, and it's not used after manual import

### ISSUE THREAD

**Issue by libBletchley** [Eloston/ungoogled-chromium#281]
According to the "best" answer to this issue:

https://askubuntu.com/questions/96816/customize-chromium-with-user-css-like-in-firefox

Chromium looks for a user stylesheet in:

`~/.config/chromium/Default/User StyleSheets/Custom.css`

but when importing from Firefox the `userContent.css` file was ignored.  After manually copying `userContent.css` to the file above, the styles have no effect.  The 2nd best answer on askubuntu 
 (from user25656) says the capability isn't expected to be there (be he seems to contradict himself).  So if Chromium is supposed to honor that CSS file then this is a _bug report_.  If not, please treat it as an _enhancement request_.

Also note that user25656 mentions the existence of chrome://settings/personal.  For me that does not exist, and redirects to chrome://settings, indicating that a configuration page may be missing.

**Comment by Eloston** [comment]
I'm closing this for the same reasons as #280. Again, anyone willing to maintain a patch is free to submit one.
