### ISSUE TITLE
switch the default search from DDG to one that actually respects privacy

### ISSUE THREAD

**Issue by libBletchley** [Eloston/ungoogled-chromium#282]
Ungoogled-Chromium replaces the default search from google to duckduckgo presumably to serve its privacy-consious users.  That's only a marginal improvement from a privacy standpoint.  DDG is yet another centralized service and it's also falsely positioned as a privacy-respecting option.  DDG does harm to privacy in [several ways](https://www.reddit.com/r/privacy/comments/4vgqrn/duckduckgo_illusion_of_privacy/d5y8tdw/), in partnership with bigger evils than google.

Consequently, I suggest a variety of relatively corporate-free options that are more suitable from a privacy standpoint:

 * searx.me ([FOSS](https://github.com/asciimoo/searx), decentralized, many [instances](https://github.com/asciimoo/searx/wiki/Searx-instances) [many of which offer onion URLs])
 * startpage.com (aka "ixquick.com"; results are largely google-influenced but users don't feed google)
 * deusu.de ([FOSS](https://github.com/MichaelSchoebel/DeuSu))
 * metager.de
 * gigablast.com
 * qwant.com
 * swisscows.com

I know I'm missing [some](http://searchenginearchive.com/open_closed.php), but I highly recommend searx.  Results are quite good, in fact better than duckduckgo b/c fewer cloudflare sites end up in the top results.  DDG's first page results are often polluted with cloudflare pages.  Startpage.com (my 2nd choice) would be interesting in the sense that results are close to Google's results without touching google, which may be in alignment with ungoogled-chromium apparent philosophy to be minimal and conservative in the ungoogling effort.

I propose populating the pre-configured "default" list of search engines with all of the above, using a searx instance as the default of the defaults, and removing the politically incorrect ones like Bing, Yahoo, and AOL, or at least tagging them as "[PRISM](https://en.wikipedia.org/wiki/PRISM_%28surveillance_program%29)" or "ill-advised". 

This will also help in light of this annoyance: users cannot control which search engines are short-listed  on the "default search settings" and which are in the "other search settings" list.

**Comment by avently** [comment]
@libBletchley
deusu.org:
403 - Verboten: Zugriff verweigert.

deusu.de:
One contributor for search engine...
Only for german
It Is really bad

searchx.me:
So good idea
So bad implementation
Results in russian are terrible. Even in english results are bad

startpage:
Slow
Doesn't have Google and duckduckgo features
Bad design
Is it FOSS? Is it corporate free? Why do you believe in it?

Anyway, my choice is duckduckgo. It's bad in queries related to programming but everything else contains a right answer in the top result or in the first page.

**Comment by libBletchley** [comment]
The Yahoo partner Duckduckgo is a poor choice for the reasons I mentioned.  Bad results, bad politics.  And worse, it's falsely positioned (it masquerades as privacy-respecting when it's proven to be privacy-hostile).  The only good thing about DDG is the _bang_ queries, but that's not good enough reason to make it a default choice in a browser that is meant to cater to a pro-privacy community.  It's a bad idea to continue to mislead privacy-respecting users into thinking DDG is aligned with their principles.

Startpage would be a reasonable choice because it's [privacy-focused](https://www.startpage.com/eng/protect-privacy.html#hmb), but with results similar to google's.  It's centralized by a Dutch company with no connection to PRISM.

Searx comes out ahead though because it's decentralized.  If you don't like the results one particular instance gives, you can change nodes.  Roughly 90% of the nodes I've tried give results that are better than DDG results.

**Comment by Eloston** [comment]
I must've forgotten to respond to this. Sorry about that.

I honestly don't care too much about what default search engine ungoogled-chromium uses; I have been just borrowing whatever Inox uses. If someone wants to write a patch to set the default or add new search engines, that's fine by me. More options won't hurt at this stage.

However, I'm not going to remove the other search engines. Based on my experience, not all users of this browser have the same privacy requirements, so there may be someone who would want to use one of these other search engines.

I don't believe tagging is worth the effort, because those kinds of choices are transparent enough for the user to understand the implications of choosing said choices. Plus, I don't see a nice way to tag search engines in the manner you want without changing the name, and I think that will ruin the cohesive appearance of the search engine list.

**Comment by macandchief** [comment]
I like Startpage. Often read about privacy concerns regarding DDG. I'd like to mention framabee.org, which is based on searx. Considering results I'd say these are the best choices: startpage or a searx instance like framabee.

**Comment by nsuchy** [comment]
Regarding DuckDuckGo:
* "DDG promotes CloudFlare sites, which compromises both privacy and anonymity:" Could you cite a source of this, I'd like to read more about this if this is indeed the case.
* "Anonymity: CloudFlare DoS attacks Tor users, causing substantial damage to the Tor network. (Torproject is not vocal about this because DDG paid $25k to the Tor project)" Cloudflare sending attacks to Tor users? Those are very serious accusations. I'd like to read more on this.
* "Privacy: All CloudFlare sites are MitM'd by design." It's up to the site owner whether to use Cloudflare or not, Cloudflare functions as a reverse proxy filtering out bad traffic, by its design it can see traffic flowing through its network, the only different is they also hold TLS Keys.
* As for the corporate sponsorships I cannot say as much as I'm not very informed on those types of issues.

**Comment by libBletchley** [comment]
> "DDG promotes CloudFlare sites, which compromises both privacy and anonymity:" Could you cite a source of this, I'd like to read more about this if this is indeed the case.

It's unclear if you need a citation for DDGs promotion of those sites, or if you're questioning CloudFlare's destruction of privacy and anonymity. If you're looking for a scientific study for the former, such a study would be a waste of money when it's trivially verified (faster than one could even read a study).  I just went to DDG and searched for "buffalo wings recipe".  CloudFlare sites appeared in the 6th, 8th, 11th, & 14th rankings, which are obviously unacceptably high.  (To confirm if you don't have Tor, run `curl --head ` &lt;URL&gt; `| grep CF-RAY`. If there is a match, it's a CF site)

> Cloudflare sending attacks to Tor users? Those are very serious accusations. I'd like to read more on this.

CloudFlare's DoS attack is easily verified if you have Tor installed.  Simply run `torsocks lynx 'https://www.simplyrecipes.com/recipes/buffalo_wings/'` and you'll be denied service; thus blocked from retrieving the target document.  CF also DoS attacks in per the _degradation of service_ meaning.  That is, if you use a GUI browser, you'll be forced to solve a CAPTCHA.  If the CAPTCHA is solvable, then it's degraded service as you've have to do a bit of manual labor.  If it's not solvable, you'll be denied just as `lynx` users are.  If you don't have Tor installed, a good read is this thread: https://trac.torproject.org/projects/tor/ticket/18361.

> It's up to the site owner whether to use Cloudflare or not, Cloudflare functions as a reverse proxy filtering out bad traffic, by its design it can see traffic flowing through its network, the only different is they also hold TLS Keys.

You've apparently answered your own question, if you had one. Whether you rationalize or accept the MitM (by design) or not is your choice.  Certainly any well-informed self-respecting privacy advocate does not accept CF holding the keys and having visibility on all that sensitive data that the general public (including some web admins) is deceived into believing they've secured.  BTW, when you say "CF functions as.. filtering out bad traffic", that's inaccurate.  CF filters out both malicious and non-malicious traffic.  You can say "bad traffic" is a subset of that, but it's misleading because it neglects collateral damage.

> As for the corporate sponsorships I cannot say as much as I'm not very informed on those types of issues.

I'm not sure why you would say something about them.  What's your objective?

DDG is apparently embarrassed about their partnerships.  Their main page used to proudly say "partnered with Yahoo", but now they've removed that.  Not only have they removed it from their front page, they seem to have scrubbed it from deeper parts of their site (as far as I can tell).

**Comment by nsuchy** [comment]
```
CloudFlare sites appeared in the 6th, 8th, 11th, & 14th rankings, which are obviously unacceptably high.
```
So if multiple relevant results have the same frontend hosting provider, in this case Cloudflare, they're not allowed to be ranked highly together? Perhaps they're ranked highly because they load faster than non-cloudflare websites.

```
You've apparently answered your own question, if you had one. Whether you rationalize or accept the MitM (by design) or not is your choice. Certainly any well-informed self-respecting privacy advocate does not accept CF holding the keys and having visibility on all that sensitive data that the general public (including some web admins) is deceived into believing they've secured. BTW, when you say "CF functions as.. filtering out bad traffic", that's inaccurate. CF filters out both malicious and non-malicious traffic. You can say "bad traffic" is a subset of that, but it's misleading because it neglects collateral damage.
```
Any solution that blocks traffic will have false-positives, that's not a cloudflare specific issue.

```
CloudFlare's DoS attack is easily verified if you have Tor installed. Simply run torsocks lynx 'https://www.simplyrecipes.com/recipes/buffalo_wings/' and you'll be denied service; thus blocked from retrieving the target document. CF also DoS attacks in per the degradation of service meaning. That is, if you use a GUI browser, you'll be forced to solve a CAPTCHA. If the CAPTCHA is solvable, then it's degraded service as you've have to do a bit of manual labor. If it's not solvable, you'll be denied just as lynx users are. If you don't have Tor installed, a good read is this thread: https://trac.torproject.org/projects/tor/ticket/18361.
```
That's not a DoS attack, a DoS attack attempts to deny users access to a service by sending it a flood of malicious traffic. Cloudflare isn't doing that, they are simply blocking you from accessing a website.

**Comment by libBletchley** [comment]
> So if multiple relevant results have the same frontend hosting provider, in this case Cloudflare, they're not allowed to be ranked highly together? Perhaps they're ranked highly because they load faster than non-cloudflare websites.

Search engines base rankings on lots of trivia, such as whether a website has a white background.  So "relevance" is generally perversely distorted and overloaded to start with.  DDG is (falsely) positioned as a pro-privacy search engine, and is thus targeted toward privacy enthusiasts.  With that user demographic, privacy-abusing search results are of little relevance.  And yet such results get high rankings on DDG.  The privacy-embracing demographic that DDG claims to serve is less interested in load speed than they are about privacy.  CF results would be relevant enough for 1st page hits to users who aren't concerned with privacy (e.g. Google and Yahoo users).

> Any solution that blocks traffic will have false-positives, that's not a cloudflare specific issue.

Only socially irresponsible solutions accept false-positives to the reckless extent that CF does.  CFs competitors (e.g. perimeterX) don't have this problem of mass collateral damage.  Also, you need not have false-positives.  A well-designed socially responsible solution would likely accept false-negatives in pursuit of ensuring that positives are true.

It's also a bit perverse to even say the variety of collateral damage CF does is a "false positive", when it's actually doing a crude pre-emptive strike for the purpose of avoiding a proper traffic analysis that could sensibly try to determine malice from non-malice.

> That's not a DoS attack, a DoS attack attempts to deny users access to a service by sending it a flood of malicious traffic. Cloudflare isn't doing that, they are simply blocking you from accessing a website.

Of course it's a DoS attack.  You're only describing one specific variety of DoS attack.

First of all, when we speak of "DoS" (note the omission of "attack"), it covers _all_ situations where service to users is denied or degraded.  That means someone accidentally tripping over a power cord and knocking a server offline is a DoS (one that security admins are also responsible to mitigate by not having power cords run across a walkway).  That's how broad it is.  Adding the word "attack" merely takes the subset of _intentional_ and malicious DoS.  This means you can cleverly write a trojan that knocks a server offline (for example).  It's still a DoS attack, even without the traffic flood.

What you describe is better known as a DDoS (distributed denial of service) attack.

**Comment by nsuchy** [comment]
> First of all, when we speak of "DoS" (note the omission of "attack"), it covers all situations where service to users is denied or degraded. That means someone accidentally tripping over a power cord and knocking a server offline is a DoS (one that security admins are also responsible to mitigate by not having power cords run across a walkway). That's how broad it is. Adding the word "attack" merely takes the subset of intentional and malicious DoS. This means you can cleverly write a trojan that knocks a server offline (for example). It's still a DoS attack, even without the traffic flood.

So next time I am banned or kicked from a chatroom or forum can I accuse them of DoSing me?

> Only socially irresponsible solutions accept false-positives to the reckless extent that CF does. CFs competitors (e.g. perimeterX) don't have this problem of mass collateral damage. Also, you need not have false-positives. A well-designed socially responsible solution would likely accept false-negatives in pursuit of ensuring that positives are true.

So pretty much any system that makes decisions for the site owner.

> Since this is about Ungoogled-Chromium, ungoogled chromium users are also largely a pro-privacy demographic. This is why DDG is a particularly poor choice as a default search engine. It keeps the lie going.

Well the only alternative I can think of is Startpage and they just proxy results from Google so you are still subject to the same bias as a not privacy friendly search engine. Do you have a better idea? The search engines I looked at in your list had bad results.

**Comment by libBletchley** [comment]
I think I neglected to mention another point about DDG as a U.C. default engine:

The primary mission of Ungoogled Chromium is to avoid Google.  Yet DDG directs all image searches (!images) to Google.
