### ISSUE TITLE
[Windows] Include h265 codec in new releases

### ISSUE THREAD

**Issue by vaguiners** [Eloston/ungoogled-chromium#284]
please

**Comment by Eloston** [comment]
I'm not sure how I missed this issue. Is H265 working for you?

**Comment by vaguiners** [comment]
Not on windows

**Comment by Eloston** [comment]
I don't know much about codec support on Windows. Help will be appreciated.

**Comment by vaguiners** [comment]
https://github.com/henrypp/chromium/blob/master/hevc_support.md
https://github.com/henrypp/chromium/blob/master/hevc_support_new.md

**Comment by Eloston** [comment]
Is this still applicable in 78? I don't see any mention of it on chromium.woolyss.com. If so, please open a new issue in ungoogled-software/ungoogled-chromium-windows.
