### ISSUE TITLE
Restore Task manager's "network" column

### ISSUE THREAD

**Issue by top-master** [Eloston/ungoogled-chromium#2844]
### Description

Restore Task manager "network" column's ability to show usage

### The problem

The Task manager's "network" column shows always zero.

I have different tools which show me total internet usage per .exe, but
seeing that Chrome's .exe uses most is not enough.

### Possible solutions

Restore Task manager "network" column's ability to show internet-usage.

### Additional context

Stopped working after 85 or so.

**Comment by Nifury** [comment]
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/7867461/07715803-1692-466d-8833-a63ae2a6482c)
