### ISSUE TITLE
New builds for Windows?

### ISSUE THREAD

**Issue by matthewd673** [Eloston/ungoogled-chromium#286]
I tried to go through the build process, but BUILDING.md is incomplete to say the least. Will there be prebuilt packages out for Windows at some point? I see that other platforms are already past 55...

**Comment by garoto** [comment]
See #235.

**Comment by Eloston** [comment]
@matthewd673 In addition, BUILDING.md states that Windows instructions are out-of-date. Currently, no one is working on re-adding support (but there is a small chance I might re-add it).

@garoto I'm having the same issue with #215 here too; consistently getting error 500. I just sent a support request to GitHub.

**Comment by ribatamu** [comment]
[https://github.com/Eloston/ungoogled-chromium/issues/215](url) is working for me.

**Comment by Eloston** [comment]
@ribatamu Yep, working here too.
