### ISSUE TITLE
[Feature] Global installation

### ISSUE THREAD

**Issue by DelofJ** [Eloston/ungoogled-chromium#2865]
### Description

Make an installer able to install Ungoogled Chromium for all users

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Currently, the installer installs itself only for the user installing the software
I think there should be a way to install it for all users
Even by using the following winget command `winget install --scope machine --id eloston.ungoogled-chromium`, it is installed only for the current user

### Possible solutions

The installer could be able to use the `Program Files` directory instead of the local one

**Comment by Nifury** [comment]
Cannot reproduce. 
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/7867461/0fe00262-90dc-453b-81fe-da93fb121345)

**Comment by meyverick** [comment]
Does `winget install -e --id eloston.ungoogled-chromium` install the latest version? I'm noob at using winget and would like ot make it easier to update Chromium. It seems that the version available using winget is `111.0.5563.65` but I don't know if it's an older version or not related to Ungoogle Chromium.

**Comment by networkException** [comment]
winget should have all packages up to M127, see https://github.com/microsoft/winget-pkgs/commits/master/manifests/e/eloston/ungoogled-chromium
