### ISSUE TITLE
Hungry for New Windows 64 bit Build

### ISSUE THREAD

**Issue by leboz** [Eloston/ungoogled-chromium#287]
I am seeing only 3 builds ungoogled-chromium for Windows.
That's 51.0.2704.106-3, 53.0.2785.116-1 and 55.0.2883.87-1, like only the last one have 64 bit.

The version 55.0.2883.87-1 suffer from some bugs(both 32 and 64bit), which I am not able to see them in the previous 2 builds. 

It's there any 51.0.2704.106-3 or 53.0.2785.116-1 64 bits which I can test them or is there any other builds for 64 bit Windows?

**Comment by Eloston** [comment]
Nope, there are no other Windows builds than what you've seen. There won't be any until #215 is done (at the time of writing, it seems to cause GitHub to consistently throw a 500 error.)
