### ISSUE TITLE
UnGoogled Chromium 58.0.3029.110 Build Error for Windows

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#288]
I tried to build UnGoogled Chromium 58.0.3029.110 for Windows.

What I am not doing correctly?

The last few lines, which I have are:

"D:\depot_tools\src>git pull https://github.com/Eloston/ungoogled-chromium.git
From https://github.com/Eloston/ungoogled-chromium
 * branch                      HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories

D:\depot_tools\src>git pull https://github.com/Eloston/ungoogled-chromium.git --allow-unrelated-histories
From https://github.com/Eloston/ungoogled-chromium
 * branch                      HEAD       -> FETCH_HEAD
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Auto-merging LICENSE
CONFLICT (add/add): Merge conflict in LICENSE
Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Automatic merge failed; fix conflicts and then commit the result."

Any help?

This builds for windows are pain in the a.. when you don't know how to do them :)

**Comment by Eloston** [comment]
> What I am not doing correctly?

BUILDING.md states the Windows instructions are out-of-date. Right now, I don't think you can get a Windows version to build without doing a lot of work manually.

I don't know what is going on with your repository, but you should probably just clone a fresh copy from a directory that's not in a git repository.

> This builds for windows are pain in the a.. when you don't know how to do them :)

Nope, it was always a pain to setup the build environment. The development was even more so, but it's nothing compared to what Google has to do.

**Comment by Eloston** [comment]
See issue #215 (whenever GitHub decides to fix its problem) and #235 for more details if you're interested.
