### ISSUE TITLE
Revert stacked tabs removal (Request)

### ISSUE THREAD

**Issue by chaoskagami** [Eloston/ungoogled-chromium#289]
I apologize if this is out of scope. Feel free to close it if so.

One of the things that really annoys me upstream is the inability to see tab titles once you open too many. This used to be available in the form of a preference to use stacked tabs, which means that tabs pile up to the side rather than shrink to nigh-invisible sizes. Combined with something like The Great Suspender, tab stacks allowed to have a rather firefox-like experience for tab-heavy users.

And then google removed the preference with the justification of "it's not intended for desktops" even though the GUI code can handle it perfectly fine and there was no reason to block it from use. There was quite a bit of outcry.

The relevant code changes: https://codereview.chromium.org/291093005

I've made a hacky patch to force stacked tabs, but I have no doubt that this is unacceptable for inclusion anywhere and really should be behind a preference like before the removal:
```
--- chromium-62.0.3202.89/chrome/browser/ui/views/tabs/browser_tab_strip_controller.cc
+++ chromium-62.0.3202.89/chrome/browser/ui/views/tabs/browser_tab_strip_controller.cc
@@ -80,12 +80,7 @@
 bool DetermineTabStripLayoutStacked(PrefService* prefs, bool* adjust_layout) {
   *adjust_layout = false;
   // For ash, always allow entering stacked mode.
-#if defined(USE_ASH)
-  *adjust_layout = true;
-  return prefs->GetBoolean(prefs::kTabStripStackedLayout);
-#else
-  return false;
-#endif
+  return true;
 }
 
 // Get the MIME type of the file pointed to by the url, based on the file's
```

Is there any possibility you guys would think about reverting (or reimplementing; you can't revert it cleanly, so it's likely one would have to redo the pref code) this change from upstream with a patch? It'd be a nice enhancement to the user experience.

**Comment by Eloston** [comment]
Sure, I can add this in. Even though it's not a high-priority feature, it looks pretty simple and straight-forward to patch. Plus, your post contains pretty much all the info I need to write the patch (thanks for the well-written post BTW). But, if Chromium significantly changes the code and breaks this patch, I won't go out of my way to rewrite it.

I haven't looked at the source tree for 62 yet, so if you already know the answers to these questions it'll speed things up a bit:
* Is `kTabStripStackedLayout` configurable by the user at all? I don't see any configuration UI changes in the Issue you linked. You mentioned the pref code would have to be redone?
* What does `adjust_layout` do?

**Comment by chaoskagami** [comment]
Hey, I'm fine with that. I agree effort is better spent removing tracking. :P

Before the removal, there was an option in chrome://flags that allowed to toggle it as well as a console argument - upstream removed both, so kTabStripStackedLayout is right now purely used internally to keep track of the state from what I can tell.

Don't quote me on this: I *think* adjust_layout is used on tablets/touchscreens. From reading the issue tracker for chromium, it seems tablets are normally in equal-width mode until one hovers/touches the tabs bar, which causes it to switch to stacked. I'm assuming adjust_layout triggers this, but I'm not sure.

**Comment by Eloston** [comment]
Hmm alright. I'll add options for both and see what happens.

**Comment by Eloston** [comment]
Added in that referencing commit. Closing.
