### ISSUE TITLE
Ungoogled chromium 51.0.2704.106-3

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#290]
I just tried the Ungoogled chromium 51.0.2704.106-3.

Do we have the ability to choose between search engines in the omnibox?

I don't see it  in this version. It's that just me?

I know is old version but if we don't have it, could you bring the search engines like is with other ungoogled chromium versions?

**Comment by Artur96** [comment]
Why are you using such an old version? Binaries for 58 are available.

**Comment by Eloston** [comment]
Sorry, I can't afford to spend time on old versions. If you can make builds, you can remove the patch that disables search engines in that version.

**Comment by ribatamu** [comment]
Eloston, please could you point me the correct patch name?

**Comment by Eloston** [comment]
https://github.com/Eloston/ungoogled-chromium/blob/cd992fb1804bf05e9b285f99a8137a3e742bdaee/resources/common/patches/ungoogled-chromium/disable-omnibox-searching.patch
