### ISSUE TITLE
Allow ANGLEImplementation::kVulkan when ozone platform is Wayland

### ISSUE THREAD

**Issue by lgjint** [Eloston/ungoogled-chromium#2921]
### Description

Allowing vulkan on wayland can allow AMDGPU to use VA-API

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

For a long time now, AMDGPU has not been able to use VA-API on Linux. A while ago this Mesa [PR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26165) allowed AMDGPU to use VA-API with vulkan on X11. 

After that, this chromium commit [9ca21ac](https://chromium-review.googlesource.com/c/chromium/src/+/5568860)  allows AMDGPU to use VA-API with vulkan when ozone platform is wayland.

### Possible solutions

Arch Linux create a patch [allow-ANGLEImplementation-kVulkan.patch](https://gitlab.archlinux.org/archlinux/packaging/packages/chromium/-/commit/07e8575a6f2151055d480a7578687704c72019f2#3a06fc637ee994d0440fdc06ad84356a3d345625) to solve this, I hope to add this patch to ungoogled-chromium as well.
```diff
diff --git a/ui/ozone/platform/wayland/gpu/wayland_surface_factory.cc b/ui/ozone/platform/wayland/gpu/wayland_surface_factory.cc
index b6e99324c02b..7602a6b8e693 100644
--- a/ui/ozone/platform/wayland/gpu/wayland_surface_factory.cc
+++ b/ui/ozone/platform/wayland/gpu/wayland_surface_factory.cc
@@ -214,6 +214,7 @@ WaylandSurfaceFactory::GetAllowedGLImplementations() {
     impls.emplace_back(gl::ANGLEImplementation::kOpenGL);
     impls.emplace_back(gl::ANGLEImplementation::kOpenGLES);
     impls.emplace_back(gl::ANGLEImplementation::kSwiftShader);
+    impls.emplace_back(gl::ANGLEImplementation::kVulkan);
     impls.emplace_back(gl::kGLImplementationEGLGLES2);
   }
   return impls;

```

Related PR: https://gitlab.archlinux.org/archlinux/packaging/packages/chromium/-/merge_requests/6

**Comment by networkException** [comment]
Upstream has reverted the patch, see also https://github.com/NixOS/nixpkgs/issues/320030

**Comment by k1gen** [comment]
this will be relanded in 129: https://chromium-review.googlesource.com/c/chromium/src/+/5740783
