### ISSUE TITLE
Iridium Privacy?

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#296]
Could somebody know what's that?? Some old information, bug or privacy leak...

[https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/commit/chrome/browser/history/web_history_service.cc?id=3bb27d9887bef87a41b56f2ec5ef62df81319a0a](url)

**Comment by Eloston** [comment]
If you're curious to know what ungoogled-chromium changes, then I highly recommend that you look only at code in ungoogled-chromium. Pointing out specific features or changes from a project that is used by ungoogled-chromium is **not** representative of ungoogled-chromium.

That being said, that kind of change you've referenced is one of the changes ungoogled-chromium did not borrow from Iridium. Unfortunately, I can't recall all of the other changes that weren't included off the top of my head.

**Comment by Eloston** [comment]
I've pushed 9855e1efa00b21aeb86bde0e265c0bae3d7fcb08 in an attempt to emphasize my point.
