### ISSUE TITLE
New Windows Build 62.0.3202.94?

### ISSUE THREAD

**Issue by PolioZp** [Eloston/ungoogled-chromium#298]
I like the ungoogled project but the builds for Windows are with bugs and I think that's because of the Chromium source code., with it's shame.

The 51 build is very very old.

The 53 build has some SSL certificate issues, when is connecting to a lot pages.

The 55 build has GPU hardware acceleration issues on video hosting pages, like youtube.

This is showing if the project has the idea to keep Windows users, it's time for new build...

Hopefully Eloston, will consider and there will be another Ungoogled Chromium build.

**Comment by Eloston** [comment]
#215
