### ISSUE TITLE
Add Mac OS X support

### ISSUE THREAD

**Issue by tristan-k** [Eloston/ungoogled-chromium#3]
Provide plattform specific instructions on how to build for Mac OS X.

**Comment by Eloston** [comment]
I don't have an OS X machine to work with, so I won't be able to do this.

The shell scripts may be compatible with OS X, so you could try these rough steps:

1. Run `download_source.sh -v 48.0.2564.109`
2. cd into `build-sandbox`
3. Run `source_cleaner.sh`
4. Run `domain_patcher.sh`
5. Apply the patches in `patches` with the order specified in `patches/patch_order`. I believe you can configure [quilt](http://savannah.nongnu.org/projects/quilt) to read that file and apply patches.
5. Run `python build/gyp_chromium` with arguments from [`build_templates/debian/rules`](/Eloston/ungoogled-chromium/tree/master/build_templates/debian/rules)
6. Run `ninja -C out/Release chrome`. The build output should appear in `out/Release`

Let me know how this goes. If you get it to work, I can add OS X building instructions to the README.

**Comment by tristan-k** [comment]
Thanks! Will report back later.

**Comment by tristan-k** [comment]
I'm running in some syntax issues.

```
$ ./download_source.sh -v 48.0.2564.109                                                                                                       (master) 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
```

**Comment by Eloston** [comment]
It appears the GNU version of readlink has more features than Mac OSX's (BSD) version of readlink. It'll probably be better if you installed GNU version of the utilities instead of working around the deficiencies; [here are some instructions I found to do this](http://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities).

**Comment by Eloston** [comment]
Done with c9597e447fbf348afa41e2d6770f231b35d16b68
