### ISSUE TITLE
Fresh install on Arch linux always opens with an annoying warning

### ISSUE THREAD

**Issue by d-packs** [Eloston/ungoogled-chromium#306]
On app launch a warning keeps showing up, stating: 

> You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer.

I have tried launching the app with flag --test-type, but to no avail.

Using Ungoogled Chromium Version 55.0.2883.75 (64-bit) on Arch Linux (Antergos), installed by package ungoogled-chromium-bin 

![image](https://user-images.githubusercontent.com/33980111/33806156-5091996e-ddcc-11e7-95a9-e4ad96b2c46d.png)

**Comment by rednithin** [comment]
```
➜ cat /usr/share/applications/firefox-developer.desktop
[Desktop Entry]
Name=Firefox Developer
GenericName=Web Browser
Icon=firefox-developer-icon
Type=Application
Categories=Application;Network;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;
Encoding=UTF-8
Exec=env GTK_THEME=Breeze firefox-developer --class=firefox-developer %u
Terminal=false
MultipleArgs=false
StartupNotify=true
```
Look for similar .desktop file and in the Exec line remove the flag causing the problem.

**Comment by d-packs** [comment]
there is no such flag set. it must be something hardcoded...

![image](https://user-images.githubusercontent.com/33980111/33846787-f8af258c-deb0-11e7-97b1-2fc714d87d98.png)

**Comment by Eloston** [comment]
That package isn't maintained by me; someone else is providing that. The only information I know about Arch Linux packages are in #44.

If I had to guess, the packager probably wasn't able to get sandboxing to work at all, so they might have set `--no-sandbox` in a wrapper script. This is all I can say based on what I know now.
