### ISSUE TITLE
Missing conservative flavour

### ISSUE THREAD

**Issue by darthrevan13** [Eloston/ungoogled-chromium#307]
Following the instuctions in BUILDING.md on Ubuntu 16.04 will not work at step:

[./utilikit/generate_build_files.py debian --flavor conservative --apply-domain-substitution](https://github.com/Eloston/ungoogled-chromium/blob/ad8ca2f60fa8e49a0bc7fc3f8f2db13fdd7892b8/BUILDING.md#L55)

This is because there is no conservative dir in resources/packaging/debian. "Standard" flavour does not work for distributions like Ubuntu 16.04.

**Comment by dubvulture** [comment]
See #293 
You have to manually apply the minimal patch and rename the directory.

**Comment by Eloston** [comment]
In this release, I have introduced [a page about platform support](https://github.com/Eloston/ungoogled-chromium/wiki/statuses). It is noted there that the Debian `conservative` packaging type is broken right now.
