### ISSUE TITLE
release 62 build failed on Windows, about safe_browsing

### ISSUE THREAD

**Issue by PonyPC** [Eloston/ungoogled-chromium#308]
ninja: Entering directory `out/ReleasePackage'
[1/5624] LIB obj/chrome/browser/safe_browsing/safe_browsing.lib
[2/5624] LINK(DLL) chrome.dll chrome.dll.lib
FAILED: chrome.dll chrome.dll.lib 
C:/depot_tools/python276_bin/python.exe ../../build/toolchain/win/tool_wrapper.py link-wrapper environment.x86 False link.exe /nologo /IMPLIB:./chrome.dll.lib /DLL /OUT:./chrome.dll /PDB:./chrome.dll.pdb @./chrome.dll.rsp
LINK : fatal error LNK1181: Can't open input file “obj/chrome/browser/safe_browsing/safe_browsing.lib”
ninja: build stopped: subcommand failed.

**Comment by tectiv3** [comment]
so, the same as macOS then... https://github.com/Eloston/ungoogled-chromium/issues/301

**Comment by PonyPC** [comment]
so how to fix it for 62

**Comment by Eloston** [comment]
No idea. If no one figures it out beforehand, I'll investigate after progress is made with version 63.

**Comment by PonyPC** [comment]
I has fixed it for windows. This is my patch:
`diff --git a/chrome/browser/chrome_browser_main_win.cc b/chrome/browser/chrome_browser_main_win.cc
index 8bef669..6a07a72 100644
--- a/chrome/browser/chrome_browser_main_win.cc
+++ b/chrome/browser/chrome_browser_main_win.cc
@@ -44,9 +44,6 @@
 #include "chrome/browser/install_verification/win/install_verification.h"
 #include "chrome/browser/profiles/profile_manager.h"
 #include "chrome/browser/profiles/profile_shortcut_manager.h"
-#include "chrome/browser/safe_browsing/chrome_cleaner/settings_resetter_win.h"
-#include "chrome/browser/safe_browsing/settings_reset_prompt/settings_reset_prompt_config.h"
-#include "chrome/browser/safe_browsing/settings_reset_prompt/settings_reset_prompt_util_win.h"
 #include "chrome/browser/ui/simple_message_box.h"
 #include "chrome/browser/ui/uninstall_browser_prompt.h"
 #include "chrome/browser/win/browser_util.h"
@@ -227,16 +224,6 @@ void ShowCloseBrowserFirstMessageBox() {
       l10n_util::GetStringUTF16(IDS_UNINSTALL_CLOSE_APP));
 }
 
-void MaybePostSettingsResetPrompt() {
-  if (base::FeatureList::IsEnabled(safe_browsing::kSettingsResetPrompt)) {
-    content::BrowserThread::PostAfterStartupTask(
-        FROM_HERE,
-        content::BrowserThread::GetTaskRunnerForThread(
-            content::BrowserThread::UI),
-        base::Bind(safe_browsing::MaybeShowSettingsResetPromptWithDelay));
-  }
-}
-
 }  // namespace
 
 int DoUninstallTasks(bool chrome_still_running) {
@@ -366,23 +353,6 @@ void ChromeBrowserMainPartsWin::PostBrowserStart() {
 
   InitializeChromeElf();
 
-  // Reset settings for the current profile if it's tagged to be reset after a
-  // complete run of the Chrome Cleanup tool. If post-cleanup settings reset is
-  // enabled, we delay checks for settings reset prompt until the scheduled
-  // reset is finished.
-  if (safe_browsing::PostCleanupSettingsResetter::IsEnabled()) {
-    // Using last opened profiles, because we want to find reset the profile
-    // that was open in the last Chrome run, which may not be open yet in
-    // the current run.
-    safe_browsing::PostCleanupSettingsResetter().ResetTaggedProfiles(
-        g_browser_process->profile_manager()->GetLastOpenedProfiles(),
-        base::BindOnce(&MaybePostSettingsResetPrompt),
-        base::MakeUnique<
-            safe_browsing::PostCleanupSettingsResetter::Delegate>());
-  } else {
-    MaybePostSettingsResetPrompt();
-  }
-
   // Record UMA data about whether the fault-tolerant heap is enabled.
   // Use a delayed task to minimize the impact on startup time.
   content::BrowserThread::PostDelayedTask(
diff --git a/chrome/browser/component_updater/sw_reporter_installer_win.cc b/chrome/browser/component_updater/sw_reporter_installer_win.cc
index 89c617c..074b55e 100644
--- a/chrome/browser/component_updater/sw_reporter_installer_win.cc
+++ b/chrome/browser/component_updater/sw_reporter_installer_win.cc
@@ -34,8 +34,6 @@
 #include "base/win/registry.h"
 #include "base/win/windows_version.h"
 #include "chrome/browser/browser_process.h"
-#include "chrome/browser/safe_browsing/chrome_cleaner/reporter_runner_win.h"
-#include "chrome/browser/safe_browsing/chrome_cleaner/srt_field_trial_win.h"
 #include "components/chrome_cleaner/public/constants/constants.h"
 #include "components/component_updater/component_updater_paths.h"
 #include "components/component_updater/component_updater_service.h"
@@ -51,8 +49,6 @@ namespace component_updater {
 
 namespace {
 
-using safe_browsing::SwReporterInvocation;
-
 // These values are used to send UMA information and are replicated in the
 // histograms.xml file, so the order MUST NOT CHANGE.
 enum SRTCompleted {
@@ -121,18 +117,6 @@ void ReportExperimentError(SwReporterExperimentError error) {
                             SW_REPORTER_EXPERIMENT_ERROR_MAX);
 }
 
-// Once the Software Reporter is downloaded, schedules it to run sometime after
-// the current browser startup is complete. (This is the default
-// |reporter_runner| function passed to the |SwReporterInstallerTraits|
-// constructor in |RegisterSwReporterComponent| below.)
-void RunSwReportersAfterStartup(
-    const safe_browsing::SwReporterQueue& invocations,
-    const base::Version& version) {
-  content::BrowserThread::PostAfterStartupTask(
-      FROM_HERE, base::ThreadTaskRunnerHandle::Get(),
-      base::Bind(&safe_browsing::RunSwReporters, invocations, version));
-}
-
 // Ensures |str| contains only alphanumeric characters and characters from
 // |extras|, and is not longer than |max_length|.
 bool ValidateString(const std::string& str,
@@ -152,137 +136,6 @@ std::string GenerateSessionId() {
   return session_id;
 }
 
-// Add |behaviour_flag| to |supported_behaviours| if |behaviour_name| is found
-// in the dictionary. Returns false on error.
-bool GetOptionalBehaviour(
-    const base::DictionaryValue* invocation_params,
-    base::StringPiece behaviour_name,
-    SwReporterInvocation::Behaviours behaviour_flag,
-    SwReporterInvocation::Behaviours* supported_behaviours) {
-  DCHECK(invocation_params);
-  DCHECK(supported_behaviours);
-
-  // Parameters enabling behaviours are optional, but if present must be
-  // boolean.
-  const base::Value* value = nullptr;
-  if (invocation_params->Get(behaviour_name, &value)) {
-    bool enable_behaviour = false;
-    if (!value->GetAsBoolean(&enable_behaviour)) {
-      ReportExperimentError(SW_REPORTER_EXPERIMENT_ERROR_BAD_PARAMS);
-      return false;
-    }
-    if (enable_behaviour)
-      *supported_behaviours |= behaviour_flag;
-  }
-  return true;
-}
-
-// Reads the command-line params and an UMA histogram suffix from the manifest,
-// and launch the SwReporter with those parameters. If anything goes wrong the
-// SwReporter should not be run at all.
-void RunExperimentalSwReporter(const base::FilePath& exe_path,
-                               const base::Version& version,
-                               std::unique_ptr<base::DictionaryValue> manifest,
-                               const SwReporterRunner& reporter_runner) {
-  // The experiment requires launch_params so if they aren't present just
-  // return. This isn't an error because the user could get into the experiment
-  // group before they've downloaded the experiment component.
-  base::Value* launch_params = nullptr;
-  if (!manifest->Get("launch_params", &launch_params))
-    return;
-
-  const base::ListValue* parameter_list = nullptr;
-  if (!launch_params->GetAsList(&parameter_list) || parameter_list->empty()) {
-    ReportExperimentError(SW_REPORTER_EXPERIMENT_ERROR_BAD_PARAMS);
-    return;
-  }
-
-  const std::string session_id = GenerateSessionId();
-
-  safe_browsing::SwReporterQueue invocations;
-  for (const auto& iter : *parameter_list) {
-    const base::DictionaryValue* invocation_params = nullptr;
-    if (!iter.GetAsDictionary(&invocation_params)) {
-      ReportExperimentError(SW_REPORTER_EXPERIMENT_ERROR_BAD_PARAMS);
-      return;
-    }
-
-    // Max length of the registry and histogram suffix. Fairly arbitrary: the
-    // Windows registry accepts much longer keys, but we need to display this
-    // string in histograms as well.
-    constexpr size_t kMaxSuffixLength = 80;
-
-    // The suffix must be an alphanumeric string. (Empty is fine as long as the
-    // "suffix" key is present.)
-    std::string suffix;
-    if (!invocation_params->GetString("suffix", &suffix) ||
-        !ValidateString(suffix, std::string(), kMaxSuffixLength)) {
-      ReportExperimentError(SW_REPORTER_EXPERIMENT_ERROR_BAD_PARAMS);
-      return;
-    }
-
-    // Build a command line for the reporter out of the executable path and the
-    // arguments from the manifest. (The "arguments" key must be present, but
-    // it's ok if it's an empty list or a list of empty strings.)
-    const base::ListValue* arguments = nullptr;
-    if (!invocation_params->GetList("arguments", &arguments)) {
-      ReportExperimentError(SW_REPORTER_EXPERIMENT_ERROR_BAD_PARAMS);
-      return;
-    }
-
-    std::vector<base::string16> argv = {exe_path.value()};
-    for (const auto& value : *arguments) {
-      base::string16 argument;
-      if (!value.GetAsString(&argument)) {
-        ReportExperimentError(SW_REPORTER_EXPERIMENT_ERROR_BAD_PARAMS);
-        return;
-      }
-      if (!argument.empty())
-        argv.push_back(argument);
-    }
-
-    base::CommandLine command_line(argv);
-
-    // Add a random session id to link experimental reporter runs together.
-    command_line.AppendSwitchASCII(chrome_cleaner::kSessionIdSwitch,
-                                   session_id);
-
-    const std::string experiment_group =
-        variations::GetVariationParamValueByFeature(
-            kExperimentalEngineFeature, "experiment_group_for_reporting");
-    command_line.AppendSwitchNative(
-        chrome_cleaner::kEngineExperimentGroupSwitch,
-        experiment_group.empty() ? L"missing_experiment_group"
-                                 : base::UTF8ToUTF16(experiment_group));
-
-    // Add the histogram suffix to the command-line as well, so that the
-    // reporter will add the same suffix to registry keys where it writes
-    // metrics.
-    if (!suffix.empty())
-      command_line.AppendSwitchASCII(chrome_cleaner::kRegistrySuffixSwitch,
-                                     suffix);
-
-    SwReporterInvocation::Behaviours supported_behaviours = 0;
-    if (!GetOptionalBehaviour(invocation_params, "prompt",
-                              SwReporterInvocation::BEHAVIOUR_TRIGGER_PROMPT,
-                              &supported_behaviours))
-      return;
-    if (!GetOptionalBehaviour(
-            invocation_params, "allow-reporter-logs",
-            SwReporterInvocation::BEHAVIOUR_ALLOW_SEND_REPORTER_LOGS,
-            &supported_behaviours))
-      return;
-
-    auto invocation = SwReporterInvocation::FromCommandLine(command_line);
-    invocation.suffix = suffix;
-    invocation.supported_behaviours = supported_behaviours;
-    invocations.push(invocation);
-  }
-
-  DCHECK(!invocations.empty());
-  reporter_runner.Run(invocations, version);
-}
-
 }  // namespace
 
 SwReporterInstallerTraits::SwReporterInstallerTraits(
@@ -318,25 +171,6 @@ void SwReporterInstallerTraits::ComponentReady(
     const base::Version& version,
     const base::FilePath& install_dir,
     std::unique_ptr<base::DictionaryValue> manifest) {
-  DCHECK_CURRENTLY_ON(content::BrowserThread::UI);
-  const base::FilePath exe_path(install_dir.Append(kSwReporterExeName));
-  if (IsExperimentalEngineEnabled()) {
-    RunExperimentalSwReporter(exe_path, version, std::move(manifest),
-                              reporter_runner_);
-  } else {
-    base::CommandLine command_line(exe_path);
-    command_line.AppendSwitchASCII(chrome_cleaner::kSessionIdSwitch,
-                                   GenerateSessionId());
-    auto invocation = SwReporterInvocation::FromCommandLine(command_line);
-    invocation.supported_behaviours =
-        SwReporterInvocation::BEHAVIOUR_LOG_EXIT_CODE_TO_PREFS |
-        SwReporterInvocation::BEHAVIOUR_TRIGGER_PROMPT |
-        SwReporterInvocation::BEHAVIOUR_ALLOW_SEND_REPORTER_LOGS;
-
-    safe_browsing::SwReporterQueue invocations;
-    invocations.push(invocation);
-    reporter_runner_.Run(invocations, version);
-  }
 }
 
 base::FilePath SwReporterInstallerTraits::GetRelativeInstallDir() const {
@@ -388,8 +222,7 @@ bool SwReporterInstallerTraits::IsExperimentalEngineEnabled() const {
 }
 
 void RegisterSwReporterComponent(ComponentUpdateService* cus) {
-  if (!safe_browsing::IsSwReporterEnabled())
-    return;
+  return;
 
   // Check if we have information from Cleaner and record UMA statistics.
   base::string16 cleaner_key_name(
@@ -473,15 +306,6 @@ void RegisterSwReporterComponent(ComponentUpdateService* cus) {
   const bool is_experimental_engine_supported =
       base::FeatureList::IsEnabled(kExperimentalEngineAllArchsFeature) ||
       is_x86_architecture;
-
-  // Install the component.
-  std::unique_ptr<ComponentInstallerTraits> traits(
-      new SwReporterInstallerTraits(base::Bind(&RunSwReportersAfterStartup),
-                                    is_experimental_engine_supported));
-  // |cus| will take ownership of |installer| during installer->Register(cus).
-  DefaultComponentInstaller* installer =
-      new DefaultComponentInstaller(std::move(traits));
-  installer->Register(cus, base::Closure());
 }
 
 void RegisterPrefsForSwReporter(PrefRegistrySimple* registry) {
diff --git a/chrome/browser/conflicts/module_info_util_win.cc b/chrome/browser/conflicts/module_info_util_win.cc
index e392417..e51f8d6 100644
--- a/chrome/browser/conflicts/module_info_util_win.cc
+++ b/chrome/browser/conflicts/module_info_util_win.cc
@@ -24,7 +24,6 @@
 #include "base/strings/string_util.h"
 #include "base/strings/utf_string_conversions.h"
 #include "base/win/scoped_handle.h"
-#include "chrome/common/safe_browsing/pe_image_reader_win.h"
 
 namespace {
 
@@ -297,6 +296,7 @@ void CollapseMatchingPrefixInPath(const StringMapping& prefix_mapping,
 bool GetModuleImageSizeAndTimeDateStamp(const base::FilePath& path,
                                         uint32_t* size_of_image,
                                         uint32_t* time_date_stamp) {
+  return false;
   base::File file(path, base::File::FLAG_OPEN | base::File::FLAG_READ);
   if (!file.IsValid())
     return false;
@@ -313,12 +313,5 @@ bool GetModuleImageSizeAndTimeDateStamp(const base::FilePath& path,
   if (bytes_read == -1)
     return false;
 
-  safe_browsing::PeImageReader pe_image_reader;
-  if (!pe_image_reader.Initialize(buffer.get(), bytes_read))
-    return false;
-
-  *size_of_image = pe_image_reader.GetSizeOfImage();
-  *time_date_stamp = pe_image_reader.GetCoffFileHeader()->TimeDateStamp;
-
   return true;
 }
diff --git a/chrome/browser/prefs/browser_prefs.cc b/chrome/browser/prefs/browser_prefs.cc
index 0531ff8..710a636 100644
--- a/chrome/browser/prefs/browser_prefs.cc
+++ b/chrome/browser/prefs/browser_prefs.cc
@@ -259,8 +259,6 @@
 #if defined(OS_WIN)
 #include "chrome/browser/apps/app_launch_for_metro_restart_win.h"
 #include "chrome/browser/component_updater/sw_reporter_installer_win.h"
-#include "chrome/browser/safe_browsing/chrome_cleaner/settings_resetter_win.h"
-#include "chrome/browser/safe_browsing/settings_reset_prompt/settings_reset_prompt_prefs_manager.h"
 #include "chrome/browser/ui/desktop_ios_promotion/desktop_ios_promotion_util.h"
 #endif
 
@@ -633,9 +631,6 @@ void RegisterProfilePrefs(user_prefs::PrefRegistrySyncable* registry) {
   component_updater::RegisterProfilePrefsForSwReporter(registry);
   desktop_ios_promotion::RegisterProfilePrefs(registry);
   NetworkProfileBubble::RegisterProfilePrefs(registry);
-  safe_browsing::SettingsResetPromptPrefsManager::RegisterProfilePrefs(
-      registry);
-  safe_browsing::PostCleanupSettingsResetter::RegisterProfilePrefs(registry);
 #endif
 
 #if defined(TOOLKIT_VIEWS)
diff --git a/chrome/browser/ui/webui/settings/md_settings_ui.cc b/chrome/browser/ui/webui/settings/md_settings_ui.cc
index 2da8861..3cca579 100644
--- a/chrome/browser/ui/webui/settings/md_settings_ui.cc
+++ b/chrome/browser/ui/webui/settings/md_settings_ui.cc
@@ -47,8 +47,6 @@
 #include "content/public/browser/web_ui_data_source.h"
 
 #if defined(OS_WIN)
-#include "chrome/browser/safe_browsing/chrome_cleaner/chrome_cleaner_controller_win.h"
-#include "chrome/browser/safe_browsing/chrome_cleaner/srt_field_trial_win.h"
 #include "chrome/browser/ui/webui/settings/chrome_cleanup_handler.h"
 #if defined(GOOGLE_CHROME_BUILD)
 #include "chrome/grit/chrome_unscaled_resources.h"
@@ -192,27 +190,6 @@ MdSettingsUI::MdSettingsUI(content::WebUI* web_ui)
   // this still needed now that there's only 1 host name?
   html_source->AddString("hostname", chrome::kChromeUISettingsHost);
 
-#if defined(OS_WIN)
-  if (base::FeatureList::IsEnabled(safe_browsing::kInBrowserCleanerUIFeature)) {
-    AddSettingsPageUIHandler(base::MakeUnique<ChromeCleanupHandler>(profile));
-
-    safe_browsing::ChromeCleanerController* cleaner_controller =
-        safe_browsing::ChromeCleanerController::GetInstance();
-    if (cleaner_controller->ShouldShowCleanupInSettingsUI())
-      html_source->AddBoolean("chromeCleanupEnabled", true);
-
-#if defined(GOOGLE_CHROME_BUILD)
-    if (cleaner_controller->IsPoweredByPartner())
-      html_source->AddBoolean("cleanupPoweredByPartner", true);
-
-    html_source->AddResourcePath("partner-logo.svg",
-                                 IDR_CHROME_CLEANUP_PARTNER);
-#if BUILDFLAG(USE_VULCANIZE)
-    exclude_from_gzip.insert("partner-logo.svg");
-#endif
-#endif  // defined(GOOGLE_CHROME_BUILD)
-  }
-#endif  // defined(OS_WIN)
 
 #if defined(SAFE_BROWSING_DB_LOCAL)
   AddSettingsPageUIHandler(base::MakeUnique<ChangePasswordHandler>(profile));
@@ -295,15 +272,6 @@ MdSettingsUI::MdSettingsUI(content::WebUI* web_ui)
   content::WebUIDataSource::Add(web_ui->GetWebContents()->GetBrowserContext(),
                                 html_source);
 
-#if defined(OS_WIN)
-  // This needs to be below content::WebUIDataSource::Add to make sure there
-  // is a WebUIDataSource to update if the observer is immediately notified.
-  if (base::FeatureList::IsEnabled(safe_browsing::kInBrowserCleanerUIFeature)) {
-    cleanup_observer_.reset(
-        new safe_browsing::ChromeCleanerStateChangeObserver(base::Bind(
-            &MdSettingsUI::UpdateCleanupDataSource, base::Unretained(this))));
-  }
-#endif  // defined(OS_WIN)
 }
 
 MdSettingsUI::~MdSettingsUI() {

-- 
2.10.0.windows.1

`

**Comment by tectiv3** [comment]
@PonyPC can you please recap what you did? So I could try to reproduce it for macOS.

**Comment by Eloston** [comment]
@PonyPC I, too, would like to know your method. Based on your patch, I only see removal of Safe Browsing code from various files.

1. How did you figure out that the remaining references to various Safe Browsing code was causing the linker to include the non-existant Safe Browsing static library? Is this some behavior of `build/toolchain/win/tool_wrapper.py` or `.ninja` files?
2. What did you use to find the references?

**Comment by PonyPC** [comment]
Well, you're right. I did missing add GN config to git and I'll upload the patch again include these, sorry for that.

[0000-fix-safebrowsing.txt](https://github.com/Eloston/ungoogled-chromium/files/1562175/0000-fix-safebrowsing.txt)

How do I know?
There isn't a safe_browsing.lib in "obj\chrome\browser\safe_browsing", I checked "chrome\browser\safe_browsing\BUILD.gn" and found that there is no source file so that the compiler can not generate library. I tried add some sources which build without errors, and found that corrupt references, fix it. Then try to remove the static_library("safe_browsing"), the compiler figure out which contains safe_browsing.
How do I do?
1. Firstly, remove "static_library("safe_browsing")" in "chrome\browser\safe_browsing\BUILD.gn"
2. Build as normal you will get error about which GN config include these library.
3. Remove those you got below.
4. Build as normal you will get error about the references in header and source.
5. Remove by context to not break whole function.
6. Build passed.

**Comment by ribatamu** [comment]
@PonyPC can you upload your version somewhere?

I would like to test some recent version of ungoogled chromium. The last one is very old.

**Comment by Eloston** [comment]
@PonyPC Ah, I see. GN was the missing link that made everything here "click" for me.

From what I understand, the `static_library` keyword in GN causes the linker to look for a corresponding static library file, hence your original error. So you removed the GN dependency, which removed the visibility of header and source files in `chrome/*/safe_browsing`. To fix it, you patched out those references (many of which are Windows-specific since the existing Safe Browsing patch removes the cross-platform references), which made the build work.

@tectiv3 you can remove the `//chrome/browser/safe_browsing` line that @PonyPC has done, and then try building. You will encounter errors about missing headers and such in `chrome/*/safe_browsing/` and related paths; just patch them out in the same manner that is done in the existing patches. If trial-and-error isn't your style (or is too sloppy), you could use some code analysis tool to find includes of the path `chrome/browser/safe_browsing` or `chrome/common/safe_browsing`, and patch those files.

@ribatamu FYI, because @PonyPC seems to be using Depot Tools, there is a high probability that domain substitution or source cleaning were *not* used. As a result, Google binaries were involved in the build and could be included, and there may be an occasional leak from the browser (e.g. #302).

**Comment by tectiv3** [comment]
@Eloston no it's exactly my style =)

**Comment by PonyPC** [comment]
@ribatamu sorry, my binary version contains custom modifies.

**Comment by PonyPC** [comment]
Actually, I patched my version without domain substitution. But if patch them all, you can still use depot tools. You can fetch build params from ungoogle script and parsing them to ninja

**Comment by PonyPC** [comment]
Only the windows version I have environment to build, those platform I can't fix it.

**Comment by tectiv3** [comment]
yep, I was able to build successfully. Just needed to remove a couple of entries from various Build.gn files, there was no need in fixing sources.
