### ISSUE TITLE
trying building on ubuntu 17.10 failed

### ISSUE THREAD

**Issue by brokoli-mate** [Eloston/ungoogled-chromium#310]
here are errors:
4 warnings and 3 errors generated.
[14/25062] CXX obj/breakpad/client/thread_info.o
warning: unknown warning option '-Wno-address-of-packed-member' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-unused-lambda-capture'; did you mean '-Wno-unused-parameter'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-user-defined-warnings'; did you mean '-Wno-user-defined-literals'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-enum-compare-switch'; did you mean '-Wno-enum-compare'? [-Wunknown-warning-option]
4 warnings generated.
ninja: build stopped: subcommand failed.

**Comment by Eloston** [comment]
Can you post the errors? I only see warnings.

**Comment by brokoli-mate** [comment]
dh_clean: mv debian/.debhelper/bucket/files/1d9048b0ac9d4d1dfce7aa4e3a0b59ccfd32db2f7693814aa6f4c778560f5669.tmp third_party/libxml/src/config.guess: No such file or directory
debian/rules:108: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2

**Comment by Eloston** [comment]
How are you trying to build? What happens if you try to apply this patch?: https://github.com/Eloston/ungoogled-chromium/blob/master/resources/patches/inox-patchset/breakpad-use-ucontext_t.patch

**Comment by brokoli-mate** [comment]
just following the instructions for debian 9. What should i do to use the patch?

**Comment by Eloston** [comment]
> does it means i'm already using it when building?

No, because it's not used in the Debian 9 patch order list. So, you'll need to apply it yourself.

**Comment by Eloston** [comment]
v63 no longer requires the breakpad patch. You can try building it and see how it goes.

**Comment by Eloston** [comment]
Building on 17.10 using the instructions in `develop` works for me. Let me know if you have issues.
