### ISSUE TITLE
Option to turn off autocomplete in Omnibox

### ISSUE THREAD

**Issue by svnpenn** [Eloston/ungoogled-chromium#314]
Google has refused to implement this, maybe this project will?

http://bugs.chromium.org/p/chromium/issues/detail?id=91378

**Comment by svnpenn** [comment]
https://github.com/brave/browser-laptop/issues/3631

**Comment by svnpenn** [comment]
https://github.com/iridium-browser/tracker/issues/190

**Comment by Eloston** [comment]
According to your linked bug report, [it isn't trivial to add an option that disables autocompletion](https://bugs.chromium.org/p/chromium/issues/detail?id=91378#c6). So, it would require a significant amount of time to write something that isn't working towards ungoogled-chromium's main objectives.

Even though I have no issue with the Omnibox and agree with Google's decision in the bug report, I will allow a patch to add this option if someone's willing to maintain it.

(FYI, If Backspace didn't clear away inline autocompletion, I would also be a bit annoyed)
