### ISSUE TITLE
chromium 62.0.3202.94-1 prebuilt packages for other platforms

### ISSUE THREAD

**Issue by leso-kn** [Eloston/ungoogled-chromium#316]
Will there be any more prebuilt packages of ungoogled-chromium 62 for other platforms than debian stretch?
I'd need a build for Ubuntu 16.04 and i assume windows builds would also be appreciated by a lot of users.

**Comment by dubvulture** [comment]
For 16.04 look [here](https://github.com/dubvulture/ungoogled-chromium-binaries/releases).
As discussed in #293 I didn't request a pull on the main repo since the build is working but the path that lead to the success is obscure to say the least.

For windows, again #215

**Comment by Eloston** [comment]
What @dubvulture said is correct. Because my focus is on version 63, I can't support major development on 62.

**Comment by leso-kn** [comment]
Thanks a lot! :+1:
