### ISSUE TITLE
Idea, disable webrtc  

### ISSUE THREAD

**Issue by bn0785ac** [Eloston/ungoogled-chromium#317]
i've tried but i cant (gn flag its broken)

**Comment by Eloston** [comment]
Yes, the GN flag is broken because Google doesn't support it on desktop platforms. ungoogled-chromium is not going to disable WebRTC unless it causes a security risk or breaches privacy; see #179 for a more detailed explanation.

Unless shown otherwise, I am closing this as invalid.
