### ISSUE TITLE
webrtc mitigation

### ISSUE THREAD

**Issue by bn0785ac** [Eloston/ungoogled-chromium#319]
with this

you can use webrtc "safely", because  if you use a vpn doesnt leak your ip

https://github.com/bn0785ac/inox-hardened/commit/71c8d4b6403b63740635d8e6954585cdc144d5f3

**Comment by Eloston** [comment]
I've heard that changing these settings will break some websites like Google Hangouts or Discord. Plus, these settings can be configured via the extension API; uBlock Origin has an option for this.

As a result, I won't include these changes unless you have another reason for doing so.

**Comment by csagan5** [comment]
@HotelBellaMuerte those are not sufficient for custom tabs, see https://github.com/bromite/bromite/issues/553
