### ISSUE TITLE
Ungoogled Chromium for Windows Extension Bug Patch?

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#324]
I installed a few extensions in the ungoogled chromium for windows. A few of them are visible and a few are hide in the chromium menu.
When I am at chrome://extensions/ and refresh the the page using the refresh button all extensions are hiding?
I tried all official ungoogled builds for windows and is doing the same thing.
I don't have this behavior in the last official chromium build for instance.

Maybe that's due to some patch, relation to extension or maybe is just me...

**Comment by Eloston** [comment]
I've never seen that kind of behavior before. What do you mean by "hiding"? What do you see instead?

**Comment by ribatamu** [comment]
When I am at chrome://extensions/ and refresh the the page all extension are hiding in the chromium menu.

**Comment by Eloston** [comment]
I don't know why this happens. Does this happen on regular Chromium?

**Comment by ribatamu** [comment]
This is not happening with the regular Chromium.

It's happening only with the Ungoogled Chromium and with the Iridium browser. So this bug it's something to do with the patches from Iridium.

**Comment by Eloston** [comment]
In that case, there might be something in the Inox or Iridium patches that I've included (Inox includes some changes from Iridium, and Inox patches are applied first, so I've left those Iridium patches out).

**Comment by Eloston** [comment]
Windows support is back in 65, so closing this as invalid unless it re-occurs in a Windows build.
