### ISSUE TITLE
How to search in ungoogled chromium?

### ISSUE THREAD

**Issue by castor-troy** [Eloston/ungoogled-chromium#33]
As the title suggests, is there a way to search in ungoogled chromium without visiting the search engine website?

**Comment by Eloston** [comment]
No, there isn't a way to do that. You'll have to remove [`disable-signin.patch`](https://github.com/Eloston/ungoogled-chromium/blob/master/resources/common/patches/ungoogled-chromium/disable-signin.patch) and recompile if you want that functionality.

In the future, I will probably add options somewhere to re-enable searching in the omnibox and the automated adding of search engines.
