### ISSUE TITLE
Webcam/mic not working via flash plugin

### ISSUE THREAD

**Issue by szatan667** [Eloston/ungoogled-chromium#331]
Chromium Version 55.0.2883.87 (64-bit Windows)
Flash version 28.0.0.161

Flash plugin is working very well in playback mode. But I can't access built-in camera nor the microphone. 
Tried out a couple of different flash versions but with no luck -- same issue, no webcam detected.
Other (googled) chromium builds work well with flash, AV devices are detected and working.
Any ideas what might be the problem here?

**Comment by Eloston** [comment]
I think this is because WebRTC is disabled in that version. There's not much that can be done except rebuild it with WebRTC, or wait for a new Windows build.

**Comment by szatan667** [comment]
It's a wait then, thanks!
