### ISSUE TITLE
A website?

### ISSUE THREAD

**Issue by mtimofiiv** [Eloston/ungoogled-chromium#335]
I love this project, and have been using this build of Chromium for a while now. Only thing is, it would be great to raise awareness of its existence a bit. That might help with not only long term growth but also with finding new contributors.

This doesn't have to be too complex, but could start with a simple website landing page that lays out the project. And maybe an in-depth listing of what's been included.

Thoughts?

**Comment by stfnhrrs** [comment]
If there's support for this, I'd love to help.

**Comment by Eloston** [comment]
Right now, I use the README to accomplish what a website does. I usually just expect users to scroll down on the main repository page to see it.

But if that isn't clear enough, I could add a simple GitHub Pages website for ungoogled-chromium that just has the contents of README with a link to the GitHub repository. Is this what you're looking for?

**Comment by mtimofiiv** [comment]
Could do that. If you want someone else to take care of this as well, I wouldn't mind helping out, and @stfnhrrs seems also eager!

**Comment by Eloston** [comment]
If you have some ideas you want to implement, by all means go ahead and do so. I don't have much opinion on this matter.

Perhaps we could start with a prototype and work from there.

**Comment by Artur96** [comment]
GitHub Pages has page templates, might be worth checking them out

**Comment by macandchief** [comment]
I think this is a good idea. I suspect in the OP it wasn't meant to be a separate github page, but more like an own site. Something like www.ungoogledchromium.io   

Though I think simply "Eloston Browser" sounds much better (and as a slogan: Ungoogled Chromium). I know the files just got a new name (not like before with Chromium), so you might not even consider this, which is of course all right, but it's just sort of "uneasy" to write every time "Eloston/Ungoogled Chromium".

www.elostonbrowser.io
Ungoogled Chromium

This just looks and sounds too good.  :)

**Comment by Eloston** [comment]
@macandchief Eloston Browser is not a bad name in itself, but it's not without its disadvantages:
* ungoogled-chromium is a unique name that clearly states the main objective of this project
* If I decide to pass on responsibility of ungoogled-chromium to someone or some group in the future, having my name in it wouldn't make much sense (I would probably move it to github.com/ungoogled-software)
* Lastly, using my name in my own project is too egotistical for my taste ;)

Also, why are you writing "Eloston/Ungoogled Chromium"? Are you using that to tell others about the project, or do you just mean the URL on GitHub?

**Comment by macandchief** [comment]
@Eloston Well, I think it's not just me, but many users call it (write about it as) "Eloston/Ungoogled Chromium". This seems to be sort of the "official" name for the browser, showing e.g. right now on the window border. 

I do understand your points, especially the last one about being too egoistic, but the truth is though, that you put so much work in the project, that the browser even deserves to be called "Eloston Browser".If the responsibility is passed, nobody in his right mind would question the brilliant idea of starting the project and the amount of work to build it up step by step.

Ungoogled Chromium states the objective of the project, but with "Chromium" in the name it's not as unique as "Eloston Browser" - as mentioned, it just sounds good, easy to pronounce (and ungoogled chromium is a perfect slogan). Let's take Vivaldi as an example - it was surely better for that project in comparison to "Pre-tuned Chromium". Just my 0,02$.

**Comment by Eloston** [comment]
> This seems to be sort of the "official" name for the browser, showing e.g. right now on the window border.

If you're referring to the GitHub webpage title, by extension of your logic, I should call uBlock Origin "gorhill/uBlock" and Inox "gcarq/inox-patchset". Doesn't make a whole lot of sense, but maybe I'm just missing some context here.

> Let's take Vivaldi as an example - it was surely better for that project in comparison to "Pre-tuned Chromium"

[According to Wikipedia](https://en.wikipedia.org/wiki/Vivaldi_(web_browser)), Vivalid's main goal is to restore popular features lost in Opera post version 12. In that case, a name like "Opera Origin" probably would've worked well (disregarding any legal issues with the name).

> Ungoogled Chromium states the objective of the project, but with "Chromium" in the name it's not as unique as "Eloston Browser" 

I question the emphasis for a unique name. Maybe it's because I'm biased towards an engineering perspective, but I prefer clarity over aesthetics. "ungoogled-chromium" is clunky, but it conveys the main idea right from the start. I can't say the same for Vivaldi, even if the name does sound nice.

An ideal name would be something like uBlock (where "u" is supposed to be the Greek *mu*, the SI unit prefix), which is unique, and concise and accurate in meaning.

**Comment by tonowoe** [comment]
Me and my friends are using "ungoogled-chromium". I think it's good.

There are also news about this browser and in those articles they are calling it "ungoogled chromium".

https://lifehacker.com/ungoogled-chromium-strips-away-the-privacy-invading-fea-1787139870
https://betanews.com/2016/10/05/ungoogled-chromium-is-a-completely-google-free-browser/

and in Finnish
https://www.tivi.fi/Kaikki_uutiset/nain-saat-chrome-selaimen-ilman-googlen-vakoilutoimintoja-6586115
https://www.mikrobitti.fi/2016/09/tassa-on-todellisen-foliohatun-chrome-selain/
(tivi and mikrobitti are the largest tech newsmagazine in Finland)

**Comment by mtimofiiv** [comment]
Does the name "Ungoogled Chromium" impose some kind of trademark violations however? I'm not an expert but if I open a greasy burger joint and call it "Not McDonalds" I feel like that I'd have a nice letter in my mailbox within a couple days.

**Comment by Eloston** [comment]
@mtimofiiv I never really thought about that, but it's possible. If Google has a problem with it, I'll be open to changing it.

**Comment by 0vermind** [comment]
May I suggest "UnG" Chrome/Browser as a name?
To spread the awareness of the project and get the advantage of the Word of mouth you need a site and a community around the project.

my two cents

**Comment by intika** [comment]
- A website even with just the readme and link to github is good for the image of the project, also this would make the project look like a solid long life application not just a git project (this is just my opinion)

- In my personal install i rename it to **UGChrome** the original name is kind a phrase... 

Thanks a lot for your project and work

**Comment by Eloston** [comment]
@0vermind @intika Thanks for your suggestions, but please keep discussion focused on creating a website. Acronyms should be discussed elsewhere.

**Comment by intika** [comment]
Some practical question and suggestions : 

**1. Git page :** 
- Git page is a very good initiative ! (https://ungoogled-software.github.io/ungoogled-chromium-binaries/) to avoid a paying server... 
- We could just edit that page to make it more modern with a theme from https://themeforest.net/ or https://www.codegrape.com/ i think just the first page is enough (@Eloston i could personally do that)   
- Then adding a .org domain linking to that site and that's it (the domain indeed should be owned by @Eloston )

**The name :** 
Before picking a site the project should definitely have its own name even if we stick with ungoogled-chromium but in the purpose of growth i think this browser is unique and should have its own name and identity... all this in the hypothesis that this browser scope will grow beyond privacy any way this should be decided before the project become too big... names examples (Uchrome/UGChrome/Copper/Krypton/Oxygen/Oxium/Oxiweb/Oxfree/Chrodom/Atom/Earth/Sky/Star/Orion/Photon/Electron/...) loool but i kind a like Orion-Browser 

**A Team :** what about creating a team or just listing tasks of what should be done and any one involved could choose what to do.

**Comment by DonaldTsang** [comment]
@intika The name should be a metal that works similar to Chromium, like Nickel, Cobalt or Silver.

**Comment by f4most** [comment]
@DonaldTsang 

like _vanadium_?  something good mad from something undesirable?

**Comment by Eloston** [comment]
https://ungoogled-software.github.io

If someone wants to maintain this, feel free to send PRs here: https://github.com/ungoogled-software/ungoogled-software.github.io

**Comment by DonaldTsang** [comment]
@f4most if we are going by that logic, Thorium?
