### ISSUE TITLE
crash on clearing browsing data

### ISSUE THREAD

**Issue by murqach** [Eloston/ungoogled-chromium#337]
Version 64.0.3282.168 (Developer Build) built on Ubuntu artful/17.10, running on Ubuntu artful/17.10 (64-bit)

after restart data isn't cleared

**Comment by Eloston** [comment]
I'm having troubles grasping the situation. What happens exactly when you clear the browsing data? Does the browser crash or not? When are you restarting it?

**Comment by Eloston** [comment]
> I click "clear data" button (no matter "advanced" or "basic" tab), browser window closing

You mean the browser window closes itself?

**Comment by murqach** [comment]
yep

**Comment by Eloston** [comment]
I'm not able to reproduce this on my Debian 9 build. Does this happen every time you try to clear data on that profile? Do you get this with a fresh profile, or after doing certain actions with a fresh profile?

Also, would you be able to run a debugger and get a stack trace or crash dump?

To anyone else with this issue, feedback will be appreciated.

**Comment by murqach** [comment]
every time. on fresh profile too.

also I mentioned that there is a crash only if I choose time range: "all time"

I run chromium from terminal and get this on crash:

```
[16240:16240:0225/145659.531633:ERROR:vaapi_wrapper.cc(252)] vaInitialize failed: unknown libva error
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[16171:16171:0225/145712.636543:FATAL:memory_linux.cc(35)] Out of memory.
#0 0x55811edaa753 <unknown>

Received signal 6
#0 0x55811edabb63 <unknown>
  r8: 0000000000000000  r9: 00007ffcb01067d0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fe822ace080 r13: 00007ffcb0106ee0 r14: 0000000000000049 r15: 00007ffcb0106ed8
  di: 0000000000000002  si: 00007ffcb01067d0  bp: 00007ffcb0106a20  bx: 00007ffcb0106a70
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fe8221890bb  sp: 00007ffcb01067d0
  ip: 00007fe8221890bb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by murqach** [comment]
my build - https://transfer.sh/WLe0A/ungoogled-chromium.zip

**Comment by Eloston** [comment]
That stack trace isn't useful to me without symbols. Are you able to get symbols?

**Comment by Eloston** [comment]
Please re-test with 64.0.3282.186-1 and report back if the problem still occurs.

**Comment by murqach** [comment]
fixed, thanks!
