### ISSUE TITLE
Improve Mac OS dmg GUI

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#34]
Spinoff from #30 

Improve the Mac OS dmg GUI so it looks prettier by adding a `.DS_Store`, a volume icon, and a background image.

@9Morello has taken up the task in #30.

**Comment by 9Morello** [comment]
So, I've made a simple background image we can use with the .dmg.
I believe we can add some scripts from here to build the .dmg with the background and the correct icon sizes to fit: https://asmaloney.com/2013/07/howto/packaging-a-mac-os-x-application-using-a-dmg/
![background](https://cloud.githubusercontent.com/assets/16482463/18605254/17f7eb06-7c63-11e6-9e10-3f1966b1cddc.png)

As for a volume icon, I'll see if I can mock up something... its definitively harder to make something passable. hehe

**Comment by Eloston** [comment]
Looks good so far. You don't have to work so hard to create a nice volume icon; you can even grab the Chromium logo and use that. The Windows and Debian builds aren't getting anything nearly as fancy as this. Something simple, understandable, and functional will do.

Minor nitpick: Could you change the text to "ungoogled-chromium"? It looks weird to me when the "u" is capitalized and the hyphen is removed, haha.

**Comment by 9Morello** [comment]
You're the boss.

![ungoogled-chromium](https://cloud.githubusercontent.com/assets/16482463/18610820/d83054be-7cfc-11e6-8811-947e3ea75d0b.png)

**Comment by Eloston** [comment]
If someone wants to submit a PR for this, feel free to do so.
