### ISSUE TITLE
quarantine mitigations are dead

### ISSUE THREAD

**Issue by bn0785ac** [Eloston/ungoogled-chromium#343]
https://chromium.googlesource.com/chromium/src/+/d103f115ce35377345d6fe415aa8f97142148c33%5E%21/#F23

**Comment by Eloston** [comment]
I'm not sure what you mean by "dead". It's just being moved.

If [803135](https://bugs.chromium.org/p/chromium/issues/detail?id=803135) indicates anything, it'll be moved again anyway. So we'll deal with this when the changes come down to stable.
