### ISSUE TITLE
Win7 - No webcam/mic allow prompts, policies cant be set

### ISSUE THREAD

**Issue by stubkan** [Eloston/ungoogled-chromium#346]
I've been trying to get my webcam and mic to work on skype/discord/html5  

When the browser is supposed to pop up with an allow/deny webcam popup, nothing occurs.

I tried forcing Videowebcam to be allowed in policies in the registry.  Downloaded the chrome policy templates to make 100% sure I had the right ones, but it says that policies are "not set" when I check in about:policy 

webcam and mic does work - i can use them outside chromium.

**Comment by stubkan** [comment]
I see now, that it is WebRTC that is disabled, causing this.. I'm using version 55.

WebRTC enabled from 62 on, apparently.  Going to try to find a version 62+

**Comment by Eloston** [comment]
> Will an updated version for windows ever be made?

No idea. No one is working on it AFAIK.
