### ISSUE TITLE
adding binaries

### ISSUE THREAD

**Issue by brokoli-mate** [Eloston/ungoogled-chromium#347]
I still can not understand  how to reproduce this steps 
4. Use utilities/platform_ini_generator.py to generate an INI file with the correct URLs to binaries. Redirect the standard output to an .ini file in the config/platforms directory with the corresponding version as the name. Pass in --help for usage information.
5. If necessary, update config/valid_versions.
6. Run utilities/site_generator.py to generate the new HTML files. There are no arguments. It must be run from the root of the repository.
a have uploaded binaries for ubuntu [17.10 here](https://github.com/brokoli-mate/ungoogled-chromium-binaries/releases/tag/64.0.3282.186)

**Comment by Eloston** [comment]
Could you tell me what exactly is hard to understand?

**Comment by Eloston** [comment]
I made a few tweaks to the README. Let me know if you still need help.

**Comment by brokoli-mate** [comment]
**I run in terminal:** ./platform_ini_generator.py [tag_name [64.0.3282.186]]
**and get this:**
['[tag_name', '[64.0.3282.186]]']
[_metadata]
publication_time = 2018-03-10T20:18:04.694945
github_author = [64.0.3282.186]]
# Add a `note` field here for additional information. Markdown is supported
