### ISSUE TITLE
error while loading shared libraries: libre2.so.3

### ISSUE THREAD

**Issue by picsi** [Eloston/ungoogled-chromium#348]
I've installed the recently updated bin at AUR: https://aur.archlinux.org/packages/ungoogled-chromium-bin/ and I get this message when trying to load chromium

>/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.3: cannot open shared object file: No such file or directory

**Comment by Eloston** [comment]
`ungoogled-chromium-bin` is a third-party package. We do not provide support for packaging issues with third-party packages. Please contact the maintainer for that package, or switch to the officially supported `ungoogled-chromium` AUR package.
