### ISSUE TITLE
Desktop Android port of UngoogledChromium

### ISSUE THREAD

**Issue by D0ve** [Eloston/ungoogled-chromium#365]
This quite different from asking usual android native ui version.
My issue is about possibility of compilling Desktop Ungoogled-Chromium to android.

The goals:
full desktop ui will be using on android,  no usual poor native android ui
using the same code that already exist
it will be first one and only full browser for android, because usual android chromium code is different of desktop version that using poor android ui
workable extensions support  (android chromium code has not extensions support yet, and will not has it in near future, but anyway yandex did it somehow... )

So is it possible just compile existent Desktop UngoogledChromium code for android?
But maybe one thing, it will need implementation of scaling ui size , because of various screen sizes. But  it may be done thrue one extension for zooming browser ui imho.
Many thanks in advance!

**Comment by Eloston** [comment]
The desktop interface is highly dependant on the system's userland rendering facilities (e.g. there's always been X11 on Linux, but Wayland support is coming). Android has a unique rendering stack that is completely incompatible, so I don't expect there to be anyone that would want to do this.

This isn't even mentioning the non-rendering userland components, which may also require some modification to work with the desktop UI.

If you're running Wayland or X11 with a regular Linux distro on your Android phone however, then that might work already without any modification (just do a native or cross-compilation for that distro's architecture and run it). But I'm guessing you mean the former.
