### ISSUE TITLE
Remove unused toggles for Google services from the UI

### ISSUE THREAD

**Issue by irlcatgirl** [Eloston/ungoogled-chromium#369]
Certain settings toggles are displayed which could harm privacy if turned on by mistake. It might be better if they are patched out. Thoughts?
<img width="690" alt="screen shot 2018-03-25 at 6 21 56 pm" src="https://user-images.githubusercontent.com/8227641/37880612-70253260-3059-11e8-97fd-837ad120b59a.png">

**Comment by Eloston** [comment]
It's fine if someone wants to patch it out for aesthetics, but they won't do anything if switched on.

**Comment by Eloston** [comment]
It should be enough to add the hidden attribute to the entries that should be removed. You can submit a PR if you want.
