### ISSUE TITLE
Mitigate homograph attacks

### ISSUE THREAD

**Issue by xsmile** [Eloston/ungoogled-chromium#370]
Internationalized Domain Names (IDNs) were introduced to display non-latin characters in hostnames. While this can be useful, such domains can be abused for phishing purposes. A character in a hostname can be exchanged with a unicode character that has no visible difference to its ASCII counterpart.

Chromium uses an [algorithm](https://www.chromium.org/developers/design-documents/idn-in-google-chrome) to detect bad IDNs and converts them to punycode (ASCII representation of Unicode). This doesn't always work and In contrast to Firefox it has no option to force punycode hostnames.

Bad URL examples leading to real phishing sites: myẹtḣerwallet.com, ẹos.com. The second URL is not converted by Chromium.

I only encountered such URLs in the cryptocurrency area but I'm sure they are not limited to it.

If there is interest, I can create a PR for an option to force punycode hostnames (by default?).

**Comment by Eloston** [comment]
I wouldn't mind showing puny codes by default, but I'm not sure how much this could bother users that visit legitimate sites using puny code. Maybe adding it as a `chrome://flag` option will be safer (and it would be documented in the README).

**Comment by Eloston** [comment]
You can submit that PR whenever you're ready.
