### ISSUE TITLE
Cannot grab the "Trump Boycott" extension

### ISSUE THREAD

**Issue by libBletchley** [Eloston/ungoogled-chromium#374]
This is likely a documentation issue.

Following the faq, I go to https://chrome.google.com/webstore/detail/trump-boycott/oooganmdnecfpdgmmneaojopkhjljjbi?authuser=1 which shows the version as "0.2" and the id as "Doooganmdnecfpdgmmneaojopkhjljjbi", and so I ran this:
```
$ torsocks wget 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=0.2&x=id%3Doooganmdnecfpdgmmneaojopkhjljjbi%26installsource%3Dondemand%26uc'
--2018-03-29 11:20:28--  https://clients2.google.com/service/update2/crx?response=redirect&prodversion=0.2&x=id%3Doooganmdnecfpdgmmneaojopkhjljjbi%26installsource%3Dondemand%26uc
Resolving clients2.google.com (clients2.google.com)... 216.58.207.174
Connecting to clients2.google.com (clients2.google.com)|216.58.207.174|:443... connected.
HTTP request sent, awaiting response... 204 No Content
2018-03-29 11:20:29 (0.00 B/s) - ‘crx?response=redirect&prodversion=0.2&x=id%3Doooganmdnecfpdgmmneaojopkhjljjbi%26installsource%3Dondemand%26uc’ saved [0]
```
I suspect the API has changed and the doc needs an update.

**Comment by Eloston** [comment]
Please note from the FAQ (bolded for emphasis):

> To use the template, replace [EXTENSION_ID] with the extension-id from the Chrome Web Store, and [VERSION] with the **browser's version**.

With this issue corrected in your URL, it downloads the extension successfully.

Also, the extension ID is simply `oooganmdnecfpdgmmneaojopkhjljjbi`. I'm guessing the capital D in front of your ID is a typo by copy-pasting from your constructed URL.

**Comment by libBletchley** [comment]
Ah, sorry about that.  The D in "%3D" is a character code, but indeed I needed the browser's version.. Sloppy reading on my part.
