### ISSUE TITLE
"Re-add Windows support"

### ISSUE THREAD

**Issue by CardealRusso** [Eloston/ungoogled-chromium#376]
WHERE IS THE BUILD
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Eloston** [comment]
[WHY CAN'T YOU READ](https://github.com/Eloston/ungoogled-chromium/issues/352#issuecomment-376802048)
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

In all seriousness, you can build it yourself easily if you can't wait. No one's taken up the offer of providing a clean build yet.
