### ISSUE TITLE
Add configuration options

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#38]
Add an ability to customize features implemented by ungoogled-chromium.

Some features that will become toggleable:
- <strike>The search functionality of the Omnibox.</strike> EDIT: No longer necessary with 8d8fc4be586b00ad903817ff37a86f861e7e6bde
- ~Blocking `onbeforeunload` events~ Feature has been removed since 21651e39c7055149606a302db23132c9621009e6
- Forcing pop-ups into tabs

More may become toggleable or customizable in the future.

Options for a GUI and a storage method for these options will need to be investigated.

**Comment by Etheryte** [comment]
It would probably make for the easiest transition to new users if the default values are similar to the default Chrome build.

**Comment by mildfuzz** [comment]
I really do not think onbeforeunload should be blocked. That's like saying you should remove reminders to save work from a text editor, which is a pretty clear anti-pattern to me. Sure, people can abuse it, but it's usefulness in modern web applications is profound.

**Comment by Eloston** [comment]
@mildfuzz Well that's assuming the webpage author doesn't abuse it, or the webpage doesn't keep repeatedly prompting dialog boxes. Your text editor is an application that you have more control over, so you can choose one that has a good UI.

I get that you're trying to reduce some patching work, but I still find this a useful feature.

**Comment by Eloston** [comment]
@mildfuzz Well your wish came true. Chromium now has a feature to hide dialog boxes on certain webpages that keep showing up, so it seems redundant to block beforeunload JavaScript dialog boxes.

**Comment by Eloston** [comment]
It doesn't seem anyone cares about popups being forced into tabs, so I'm going to close this. If someone does care, let me know.

**Comment by achesnok** [comment]
> It doesn't seem anyone cares about popups being forced into tabs, so I'm going to close this. If someone does care, let me know.

@Eloston is there any chance of implementing this feature as toggleable? I would like to have it very much, even browser-wide setting will do.

**Comment by Eloston** [comment]
@achesnok Continuing discussion here: https://github.com/Eloston/ungoogled-chromium/discussions/1377
