### ISSUE TITLE
[Windows] Some sites crashing here

### ISSUE THREAD

**Issue by CardealRusso** [Eloston/ungoogled-chromium#382]
Is flash player?

**EDIT from Eloston: The following links are NSFW. Proceed with caution.**

http://tabooporns.com/
https://www.xnxx.com/video-dn1x3cd/groped_in_bus
https://www.xvideos.com/video9823072/girl_groped_on_bus

**Comment by Eloston** [comment]
What build are you using?

**Comment by CardealRusso** [comment]
https://github.com/squalus/ungoogled-chromium-winbuild/releases/tag/65.0.3325.181-1

this one

**Comment by Eloston** [comment]
Might be related to #380 or #381. We should re-check after fixing those first.

**Comment by CardealRusso** [comment]
https://pt.aliexpress.com/

**Comment by Eloston** [comment]
Fixed with #394.
