### ISSUE TITLE
[Windows] Profile icon Bug ?

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#383]
Mouse click on chromium profile icon and choose close all your windows. I am nor sure if that's a bug but Chromium is complaining like is not shutdown correctly at start up.

**Comment by Eloston** [comment]
Do you see the same window as clicking on "Manage people" (titled "Chromium") after you click "Close all your windows"? If I use "Close all your windows" then close the new window that shows up, I get no errors after starting Chromium again.

(I am running my Debian 9 amd64 65.0.3325.181-1 build)

**Comment by ribatamu** [comment]
Actually, when I click on "Manage People", Chromium is closing again and at start up is not complaining about shutdown error.

But If I click on "Guest" or "Close all your Windows", Chromium is closing and complaining like is not shutdown correctly at start up.

**Comment by Eloston** [comment]
Sounds like a Windows-specific bug. I'm not gettig it on my Linux system.

@squalus Do you get this error in the build that you fixed incognito?

**Comment by Eloston** [comment]
@squalus Awesome. I'll close this when I release a new version.

**Comment by Eloston** [comment]
It's a bit of a hassle to keep this open for no good reason, so closing.
