### ISSUE TITLE
Investigate using GN setting is_official_build=true for several base bundles

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#390]
Enabling `is_official_build=true` has several benefits as summarized in https://github.com/Eloston/ungoogled-chromium/pull/388#discussion_r179862682. So, I think it would be nice to enable this for configurations that don't link against system libraries, like:
* Portable Linux
* Windows
* macOS

Also, what is the minimum LLVM toolchain version required for this? This is only really a problem for Portable Linux, since some distributions don't ship with a new enough LLVM toolchain. One option is to have `is_official_build=true` by default, and then create another base bundle with `is_official_build=false` if demand is high enough. Thoughts?

Once development on 66 has started, I welcome testers to try building with this flag enabled.

**Comment by xsmile** [comment]
The minimum should be LLVM 5.0 as e.g. `build/config/compiler/BUILD.gn` uses linker options not available in previous versions like `--thinlto-cache-dir`. Still a [patch](https://git.archlinux.org/svntogit/packages.git/commit/trunk/PKGBUILD?h=packages/chromium&id=0196070bd6c86093b299ed6aaaf829613adba331) is required.
LLVM 6.0 is fully supported.

**Comment by csagan5** [comment]
I use this for Bromite, no specific issues to report. You can mention me in case you see something weird during the build and perhaps I can remember if I already met the problem context.

From the top of my head, a note about Google services integration: it checks if a header file with API keys is present, if not it just keeps going. The file obviously is not there in your case as you would get this file only in the internal Google network.

**Comment by Eloston** [comment]
It seems to be working on all platforms so far. Closing.
