### ISSUE TITLE
SWF files are downloaded instead of invoked with Flash player

### ISSUE THREAD

**Issue by phaoost** [Eloston/ungoogled-chromium#391]
Hi.

How to make browser not to offer download on pages with swf files? Is there any way to use flash plugin for them?

**Comment by antonin-lebrard** [comment]
I think the FAQ section on Flash player should answer your request :
https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#how-do-i-install-flash-player

**Comment by phaoost** [comment]
Hi,

I have plugin installed:

~# update-pepperflashplugin-nonfree --status
Flash Player version installed on this system  : 29.0.0.113
Flash Player version available on upstream site: 29.0.0.113

However it doesn't appear listed in chromium extensions.

**Comment by antonin-lebrard** [comment]
There is some supplementary installations instructions on the debian wiki: https://wiki.debian.org/PepperFlashPlayer/Installing
Maybe by trying to fiddle with the chromium installation and the libpepflashplayer.so file you will find a solution ? 
And there is the chrome url : chrome://flash/ that might ease your test scenario

**Comment by phaoost** [comment]
I had no any troubles with chromium installation.
Here is what chrome://flash showing (GL_EXTENSIONS omitted)
About Flash
Chromium	65.0.3325.181 (built on Debian stretch/9.4, running on Devuan ceres/unstable)
OS	Linux
Flash plugin	29.0.0.113 /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
--- Crash data ---
Crash Reporting	Enable crash reporting to see crash IDs
For more details	https://support.9oo91e.qjz9zk/chrome/?p=ui_usagestat
--- GPU information ---
--- GPU driver, more information ---
Vendor Id	0x8086
Device Id	0x1916
Driver vendor	Mesa
Driver version	17.3.3
Driver date	
Pixel shader version	1.30
Vertex shader version	1.30
GL_VENDOR	Intel Open Source Technology Center
GL_RENDERER	Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
GL_VERSION	3.0 Mesa 17.3.3

**Comment by antonin-lebrard** [comment]
I didn't managed myself to make it work, but I'm in ubuntu so I'm using the build of dubvulture https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/ubuntu/xenial_amd64/65.0.3325.181-1 
So I might not be able to help you

**Comment by Eloston** [comment]
Closing since multiple versions have been released since version 65. If this is still an issue, please let us know.
