### ISSUE TITLE
omnibar with different search engine

### ISSUE THREAD

**Issue by tristan-k** [Eloston/ungoogled-chromium#4]
Is there a way to use the omnibar with a different search engine like [duckduckgo](https://duckduckgo.com/), [yacy](http://search.yacy.de/) or [searx](https://searx.me/) or is this impossible because of the dependencies to google? In the inox-patchset there is a patch called [add-duckduckgo-seaarch-engine.patch](https://github.com/gcarq/inox-patchset/blob/master/add-duckduckgo-search-engine.patch).

**Comment by Eloston** [comment]
[The lack of searching is a feature](https://github.com/Eloston/ungoogled-chromium#features). I do this for two reasons:
* Mistyping or miscopying a URL will lead to a search, which I find annoying
* Certain custom domain names (whether they are defined in /etc/hosts or a local DNS server) will also end up causing a search (at least historically).

If you want searching in the omnibox, don't apply the patch `patches/ungoogled-chromium/disable-omnibox-searching.patch`

**Comment by tristan-k** [comment]
Thanks! Should have read the readme more carefully.
