### ISSUE TITLE
Allowing media (microphone) permission per site won't "stick" (WebRTC issue?)

### ISSUE THREAD

**Issue by TRSx80** [Eloston/ungoogled-chromium#412]
Greetings! Awesome work you have done here! You have allowed me to now consider using Chromium where I never would have before.

I was trying to do some free-form speech to text conversion (dictation), my understanding is Chrome(ium) plug-ins are best for this. And your awesome project brought this into my realm of possibility, without needing to give up privacy! But I seem to have hit a snag along the way...

I installed the latest pre-built Debian version (ungoogled-chromium_66.0.3359.139-1.stretch_amd64) with all other needed components (common, driver, shell, widevine) using gdebi. Then I figured out how to get plug-ins installed from the Chrome Webstore, following your instructions and the create a search provider method. I am on Debian unstable btw, also amd64.

I then installed 2 different speech to text plug-ins ([VoiceNote II](https://chrome.google.com/webstore/detail/voicenote-ii-speech-to-te/hfknjgplnkgjihghcidajejfmldhibfm) and [Online Speech Recognition](https://chrome.google.com/webstore/detail/online-speech-recognition/pehlbpmpoabkgenppepoaihkacolpdcf)) but could not get either to work, with roughly the same problem, namely: When I go to use these, a media permission icon appears in the right side of the URL bar. I click on this and allow the site access to my microphone. However it does not keep the setting, and I cannot get it to work.

I started thinking this might be due to something u-c is blocking, so some searches for "u-c microphone" & etc. led me to #221 which in turn led me to #179.

Well then I started looking at WebRTC stuff in settings. I searched chrome://flags for anything to do with "rtc" and enabled all of the following, to no avail:
- Negotiation with GCM cipher suites for SRTP in WebRTC
- Negotiation with encrypted header extensions for SRTP in WebRTC
- WebRTC Stun origin header

I also tried testing via https://test.webrtc.org/ with same steps (allow media/mic permission for site, which didn't "stick") and therefore that didn't work either.

Only other plug-ins I have installed so far are Dark Reader and uBlock Origin, the latter I thought might also be blocking something maybe. Note I have not checked the setting in uBO about "Prevent WebRTC from leaking local IP addresses". Also, I turned uBO completely off and still couldn't get the mic/WebRTC to work.

Only other thing is, I am using a VPN. But that shouldn't make a difference, should it? Not sure I am willing to get on the internet at all without VPN and so hope that's not the problem. I don't think it's an "extension based" VPN (read something somewhere about that) as I am connecting using the OpenVPN client in Debian.

So with that, I'm out of ideas at the moment, so I thought I would go ahead and post my predicament to marinate while I go on and get caught up on homework. :) Any thoughts would be appreciated.

**Comment by Eloston** [comment]
Do you have any entries for the site(s) in question in `chrome://settings/content/microphone` and/or `chrome://settings/content/camera`?

**Comment by TRSx80** [comment]
Wow! Thanks for quick reply!

Yes under chrome://settings/content/microphone it looks like this:

Microphone

G533 Wireless Headset Dongle
Ask before accessing (recommended)       [toggle ON]

Block
No Sites Added

Allow
https://voicenotebook.com:443
https://voicenote.in:443
https://test.webrtc.org:443

**Comment by Eloston** [comment]
Do you have the same problem with the Portable Linux build?

**Comment by TRSx80** [comment]
Just tried that. It took me a few minutes to remove old version, install (extract, really) the portable version, and then figure out the "allow user namespaces" thing.

But the answer is yes, still appear to be having same problem.

**Comment by Eloston** [comment]
Since Portable Linux is having the same problem, it's possible this is a bug in Chromium. Could you try out the new Debian binaries I published just to be sure?

> I am now thinking I should have done purge?

I don't think this is a problem with your browser profile. But if you want to test, you can just move or delete your configuration in `~/.config/chromium` and let the browser generate a new one to be certain.

Also, the purge scripts of the Debian packages don't clear out directories in your home directory (i.e. `~/.cache/chromium`, `~/.config/chromium`, etc)

**Comment by Eloston** [comment]
67 is out. If this is still a problem for you, let us know here.

**Comment by TRSx80** [comment]
Just for informational purposes, I got busy with other projects and never got back to working on this. But I expect to at some point, if/when I do, I will try and remember to report back, one way or the other.

Thank you very much for your time and keep up the great work! Cheers!

**Comment by jackhill** [comment]
As per https://github.com/Eloston/ungoogled-chromium/issues/785#issuecomment-515730982 in #785 I'm think I'm still experiencing this with Version 75.0.3770.142 (Developer Build) (64-bit)
