### ISSUE TITLE
66.0.3359.139-1: Binaries for Windows - 64-bit is NOT ungoogled!

### ISSUE THREAD

**Issue by micha06de** [Eloston/ungoogled-chromium#415]
The via crlauncher downloaded file is an official chromium build! It's goggled! What's going on?
![chromium](https://user-images.githubusercontent.com/36893745/40527912-069b59a8-5fef-11e8-94b6-2b94a9bd4e37.PNG)

https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/66.0.3359.139-1 its also googled!!

**Comment by ribatamu** [comment]
:)

**Comment by vivienney** [comment]
Will there be an update for the Windows binaries to 66.0.3359.181-1?

**Comment by BrianD91** [comment]
This seems to be true on Kubuntu as well

**Comment by Artur96** [comment]
It is ungoogled. The official build flag has been set to strip down on the binary size.
Try using any Google API service if you're skeptical :)

**Comment by Eloston** [comment]
It says Chromium because ungoogled-chromium does not change the branding. From the beginning of the README:

> **ungoogled-chromium should not be considered a fork of Chromium**. The main reason for this is that a fork is associated with more significant deviations from the Chromium, such as branding, configuration formats, file locations, and other interface changes. ungoogled-chromium will not modify the Chromium browser outside of the project's goals.
