### ISSUE TITLE
Feature Request -- Remove "Chromium didn't shut down correctly"

### ISSUE THREAD

**Issue by ryanmusante** [Eloston/ungoogled-chromium#419]
On starts frequently this message is bothersome because it requires manual intervention. Several methods through search do not remedy. Request removal.
```
Resore pages?
Chromium didn't shut down correctly.
```

**Comment by Eloston** [comment]
What are you doing to cause the message to appear? Do you make copies of profiles while in use or kill Chromium externally?

**Comment by ryanmusante** [comment]
I think it is when I reboot the machine without closing the window. That and killing  externally, I wish there was a way to force disable it.

**Comment by Eloston** [comment]
If someone wants to submit a patch to do this, feel free.

**Comment by Eloston** [comment]
@luckydonald All feature requests of this nature are opt-in by default, unless there is a good reason otherwise. I'm not one who wants to break workflows.
