### ISSUE TITLE
nasty little build error on macOS

### ISSUE THREAD

**Issue by pjv** [Eloston/ungoogled-chromium#425]
So here's a weird and nasty one.

Building on macOS, after the whole build was complete, the final packaging puked on me with the following rsync error:

`rsync: opendir "/var/empty/.anydesk/incoming" failed: Permission denied (13)`

...because apparently anydesk left an empty, root-owned directory under `/var/empty` on my mac.

I did a `sudo rm -rf /var/empty/*` and then tried various tricks to save the build but couldn't get anything to work so I had to get rid of the tree and do the whole build again. 

Frustrating.

It looks to me like the build is putting some stuff into `/var/empty` along the way and then copying it into the final package. I've no idea if that is peculiar to the mac build or common, but I wonder if it might be worthwhile to add a check at the beginning of the build for an empty `/var/empty` and abort and allow user to empty that directory if it's not.

**Comment by Eloston** [comment]
If it's the final packaging step that failed, then it might be an issue with `chrome/installer/mac/pkg-dmg` (which is written by the Chromium team). Do you know which command in `build.sh` failed?

If `pkg-dmg` is the issue, then we can check for any additional CLI options in the script before resorting to patching it.

> I had to get rid of the tree and do the whole build again.

Generally this shouldn't be necessary as packaging commands don't touch any files in the build output. In the event that they are missing or modified, you can rerun `ninja` to regenerate those missing files without rebuilding the entire browser.

**Comment by pjv** [comment]
from the error messages, I'm pretty sure it was the last command in `build.sh` that failed.

>>I had to get rid of the tree and do the whole build again.

>Generally this shouldn't be necessary as packaging commands don't touch any files in the build output. In the event that they are missing or modified, you can rerun ninja to regenerate those missing files without rebuilding the entire browser.

i thought that should be right, so after clearing out the `/var/empty` directory, i went into `build.sh` and commented out most of the stuff above that last command, but i think i botched what i did and didn't comment so that failed for me. I should have read through the script more carefully but i was doing too many things at the same time.

the second build went fine, so it was definitely having that errant root-owned directory in `/var/empty` that caused the problem. If i had `sudo'd` the build i think it would have worked, but then i also think that `pkg-dmg` would have potentially copied some random stuff that just happened to be in that directory into the package (though it says it is copying `*.so` so likely nothing would have gone anyway).

**Comment by Eloston** [comment]
I added a check to ensure `/var/empty` is actually empty before building (I'm assuming nothing will be adding files to `/var/empty` during that time).

During that change, I noticed that `pkg-dmg` is given `/var/empty` via the `--source` flag. If this directory is used only during the generation of the dmg and not in the dmg, then it may be better to just create and use a temporary directory instead.

**Comment by pjv** [comment]
>During that change, I noticed that pkg-dmg is given /var/empty via the --source flag. If this directory is used only during the generation of the dmg and not in the dmg, then it may be better to just create and use a temporary directory instead.

yeah, i think it would be better to make and use a temporary directory under `buildspace`. On a quick glance through `chrome/install/mac/pkg-dmg` and then again at `build.sh` it looks like passing `--source /var/empty` implies that nothing is actually going in there in the build and that using it as `--source` is really an attempt at a way to start with an empty directory to then copy stuff into in the `.dmg`. My guess is that creating and using an emtpy temp dir under buildspace would work fine.

i'll test that out when i have a chance and report back.

(i'll also suggest to the anydesk guys to stop using `/var/empty` as a `/tmp`)
