### ISSUE TITLE
Debian package missing dependency on gsettings-desktop-schemas

### ISSUE THREAD

**Issue by zaza42** [Eloston/ungoogled-chromium#432]
When i remove package `gsettings-desktop-schemas` then chromium doesn't start with a simple `Segmentation fault` message. Please include this dependency in `debian/control`.

**Comment by zaza42** [comment]
Not the `-dev` for compiling; the plain `gsettings-desktop-schemas` for Package: ungoogled-chromium for running the compiled binary.

**Comment by Eloston** [comment]
Well `gsettings-desktop-schemas-dev` basically only adds that dependency right now, so I think it's safer to do it this way just in case the dependencies change. If you can show me a source package that has `gsettings-desktop-schemas` explicitly as a runtime dependency, then it might be fine to change it.
