### ISSUE TITLE
Cannot install Extensions through drag/drop

### ISSUE THREAD

**Issue by waqas** [Eloston/ungoogled-chromium#434]
Using Chrome 67 on Windows.
When I drag a .crx file onto chrome://extensions there is no ovelay that says "Drag to install" like it used to in Chrome 66, and it simply downloads the crx file.

**Comment by xsmile** [comment]
See https://github.com/Eloston/ungoogled-chromium/issues/423#issuecomment-398940894.

**Comment by waqas** [comment]
That worked. Thanks.

**Comment by Eloston** [comment]
A note about this was also added into the [FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#installing-the-crx-file) following that issue.

Given Google's push for Material Design UI, I cannot guarentee that the "Enable Material Design extensions" switch will continue to last.
