### ISSUE TITLE
Is ungoogled-chromium supposed to delete history on exit?

### ISSUE THREAD

**Issue by leewdch** [Eloston/ungoogled-chromium#435]
I thought these settings kill cookies AND history on exit. Is this not the case anymore? do I need an extension for the job?

![image](https://user-images.githubusercontent.com/11262717/42543282-64ab66ce-84ab-11e8-886c-9cd2ffdb01a0.png)

![image](https://user-images.githubusercontent.com/11262717/42543302-87b82f12-84ab-11e8-90c6-313053feb4d6.png)

**Comment by Eloston** [comment]
To my knowledge, Chrome/Chromium never had a setting to clear history automatically on shutdown. Can someone else confirm this?

**Comment by antonin-lebrard** [comment]
I don't have access to my computer at the moment, but i have been using this parameter on both Chrome (last version) and Iridium browser (from last 2017

**Comment by leewdch** [comment]
From what I read online about the content deletion on exit it was supposed to delete ALL local content, history as well

**Comment by antonin-lebrard** [comment]
The chrome help page from google seems not to talks about history when talking of this parameter: https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&oco=1
And from the chrome help page about history itself, it seems only the incognito mode is mentioned as a way to not keep history
https://support.google.com/chrome/answer/95589?hl=en&co=GENIE.Platform%3DDesktop&oco=0

**Comment by leewdch** [comment]
Got it, guess I should not trust every single tech blog I find online. Thanks for the info
