### ISSUE TITLE
Problem inside vcxproj with xml validator, because of domain replacement 

### ISSUE THREAD

**Issue by Ti-R** [Eloston/ungoogled-chromium#437]
I just start to generate some days ago visual studio solution to modify chromium.

Like this:
~~~
call out\Default\gn.exe gen out\Default --ide=vs --filters="//chrome/*;//base/*" --sln=chrome --fail-on-unused-args --no-deps
~~~

But a bug occur.
Inside each vcxproj, 

It replace each xml validator xmlns="http://schemas.microsoft.com/developer/msbuild/2003" inside vcxproj by in invalid url validator "schemas.m1cr050ft.qjz9zk"

I think it is because of this script:
Could it be adapt ?
https://github.com/Eloston/ungoogled-chromium/search?utf8=%E2%9C%93&q=m1cr050ft&type=

Inside 
> resources/config_bundles/common/domain_regex.list

This code change the way the vcxproj are generated
 `microsoft(\\*?)\.com#m1cr050ft\g<1>.qjz9zk`

The detour is to replace each `schemas.m1cr050ft.qjz9zk` by `schemas.microsoft.com` in each vcxproj.

@Eloston Does it exist an easy way to filter out "vcxproj" from domain replacing ?

**Comment by Eloston** [comment]
There are no instances of vcxproj files in the binary pruning list, so one of the files in the pruning list must be involved with the schema URL. If the file does not contain any other domain names that should be substitued, then we can ignore it from the binary pruning list.

**Comment by Ti-R** [comment]
Hello @Eloston , I submit a pull request to fix the issue.
https://github.com/Eloston/ungoogled-chromium/pull/445
