### ISSUE TITLE
My findings about how Chromium disrespects privacy

### ISSUE THREAD

**Issue by anchev** [Eloston/ungoogled-chromium#438]
Hello,

I still haven't tried ungoogled-chromium but I wanted to share with you my findings about how Chromium connects to Google hosts regardless of all attempts to stop these connections.

I have [reported full details](https://bugs.chromium.org/p/chromium/issues/detail?id=795526) about that behavior to Chromium's bugzilla but the developers tend to merely admit it without considering privacy a priority.

Has that issue been fixed in ungoogled-chromium? Or is it something you may probably be interested to look into?

**Comment by Eloston** [comment]
I don't know. Those in the linked bug report are tweaking settings at a pretty high level (i.e. settings exposed by the UI), and a lot of our modifications are based on Wireshark traffic and digging around in the source code (mostly the latter).

If you do find a leak, please report it.

**Comment by anchev** [comment]
> tweaking settings at a pretty high level

Yes. That's why the bug report is titled "Privacy disrespected (by default)".

As you can see my test is also based on monitoring network connections. Not using wireshark but tcpdump.

> If you do find a leak, please report it.

I have already done this - not in ungoogled-chromium but in chromium itself. I thought you might be interested to test the same in your tweaked version and check if it is fixed. Considering you already have a compiled version it will be much easier than waiting for me to learn how to compile your version, then test it etc. Of course - I will, but it may take a long time and if it is an actual leak, it may still not be fixed while you wait for me. Hence the whole report here. I hope that clarifies.

**Comment by Eloston** [comment]
Domain substitution covers the domains that you reported in the bug report (1e100.net, google*.com, and many more not mentioned in the report. So any domain names hardcoded into the source code will not be able to function correctly unless obfuscated.

I also modified Chromium to log if the browser attempts to connect with the modified domains, so I can disable the unnecessary code and any other related services.

I am certainly *not* claiming to have blocked everything, but I believe that most, if not all unwarranted connections have been disabled.
