### ISSUE TITLE
domain substitution

### ISSUE THREAD

**Issue by aphextwins** [Eloston/ungoogled-chromium#439]
can't someone buy 9oo91e.qjz9zk for example, or cant google just make a DNS entry because they own 8.8.8.8. and redirect it to their own IP's anyway.

There hasnt been a new Windows version of Ungoogled-Chromium for a while, i saw a user called Wyse compiled one, but its not liked on this repo, so windows users wont be able to find it.

**Comment by Eloston** [comment]
Not only is it an invalid TLD, ungoogled-chromium will intercept and block all requests that go through Chromium's network stack (which includes URLRequest) that contain the qjz9zk domain name. So, the likelihood that Chromium will actually attempt any sort of connection with a URL with that domain name is very small.

However, services not using URLRequest theoretically could attempt a connection. Though I am not aware of any such cases.

**Comment by Eloston** [comment]
Regarding the Windows build not being linked, no one has submitted a PR to ungoogled-chromium-binaries for inclusion. I leave the responsibility of keeping contributor binaries up-to-date to the contributors that submit them.

If you have more questions regarding this issue's main topic, please respond here. If you have other questions, please create a separate issue for each separate topic. Thanks.
