### ISSUE TITLE
Documentation for Upgrade Process

### ISSUE THREAD

**Issue by ethanpil** [Eloston/ungoogled-chromium#441]
I just started with ungoogled-chromium v66 on Windows and all has been great - thanks for the excellent and diligent work. I am ready to try the v67 update recently released and am concerned about upgrade. Can I simply overwrite the install folder with the updated files without losing all of my bookmarks and data?

**Comment by Wyse-** [comment]
Yes, overwriting everything in the install directory is perfectly fine, on Windows ungoogled-chromium stores user data in the AppData folder (like Chromium does). See [this documentation](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md) for more info.

**Comment by Eloston** [comment]
ungoogled-chromium functions exactly like Chromium for profiles. You can even migrate an existing Chromium profile to ungoogled-chromium by simply running the browser.
