### ISSUE TITLE
How to update to latest version (windows)?

### ISSUE THREAD

**Issue by Kherby** [Eloston/ungoogled-chromium#443]
I'm using ungoogled chromium with win 10 x64 and i wonder what's the best way to update it to the lastest version without loosing my bookmarks and settings?
Imho an updateable installation would be more useful than a portable one...
Is there going to be a fully installed version for windows in the future so we can just update the version more easy via setup or even over a internet source?

Much love for this project, keep it up! <3

**Comment by xsmile** [comment]
See https://github.com/Eloston/ungoogled-chromium/issues/441.

I wonder about the installer, too. Currently Ungoogled Chromium cannot be registered as the default browser in Windows 10 without manually editing the registry but this is just a minor drawback.

**Comment by Kherby** [comment]
Thanks for the link!
Yes, a installer would be nice but as long as i don't lose my bookmarks i'm fine with the portable solution.
I'm using ungoogled chromium only for my GUI based network devices and for normal browsing i'm using Waterfox with some addons.
