### ISSUE TITLE
User switcher UI (upper right of titlebar) is missing

### ISSUE THREAD

**Issue by Noleli** [Eloston/ungoogled-chromium#45]
The user switcher, which lets you switch between Chromium users to silo cookies and other data between users, is missing from the right side of the titlebar. I see no other way to switch users.

**Comment by Eloston** [comment]
What platform are you using? I can see it on Windows 10, Debian, and Ubuntu.

**Comment by Noleli** [comment]
Sorry, I'm on OS X 10.11.x.

**Comment by Eloston** [comment]
Oh, okay. I don't actually have a Mac platform, so I can't test this out. @9Morello, can you confirm?

I think you can go to `chrome://settings/` under the People section to change users for now.

**Comment by 9Morello** [comment]
Yes, the button is not there. I also can't change user through the settings page. You only get a new session when you create a new user, and once you close it, you can't open a new session for that user anymore.

**Comment by Eloston** [comment]
That's interesting. I've never personally used multiple user profiles before.

@Noleli: if your intent is to separate cookies and other browsing data, I highly recommend that you use a separate browser profile instead via the `--user-data-dir` command-line argument. If that workflow doesn't work well for you, then we'll try to get this bug resolved.

Assuming this bug is to be solved: I did a little investigation and I might have an idea of what happened. @9Morello, would you mind making a build with `common/patches/inox-patchset/disable-new-avatar-menu.patch` modified such that `chrome/browser/profiles/avatar_menu.cc` isn't patched? I have a feeling the avatar menu plays a different role on Mac OS.

**Comment by Noleli** [comment]
Thanks for looking into it! Is there a reason using `--user-data-dir` is preferable to user profiles? I'd rather only have to run one instance of Chromium. Launching another one every time I want to use Facebook (which I isolate from everything else) sounds annoying (though probably good for my health).

**Comment by Eloston** [comment]
@Noleli: You'll have to specify a directory with `--user-data-dir`, which will be used to store all of the preferences and state information for a browser session. I'm not sure how user profiles are implemented, so I see this command-line switch as a "cleaner" and more certain way of accomplishing what you need. This still requires that you launch an instance with this flag, and you can't switch data directories in a session.

I did some testing of user profiles on Debian, and it seems that the user profiles are treated as separate windows (much like separate user data directories). The only benefit is that it's easy to launch or switch between them within Chromium.

By the way, there's also Incognito mode if you don't want cookies or other site data to persist. You'll also get to use your existing preferences.

**Comment by 9Morello** [comment]
@Eloston Just started building it, should be able to post my results tomorrow.
I think its good for @Noleli to run Facebook in a separate profile. It'll probably have different add-ons installed and most likely will have a different fingerprint.

**Comment by 9Morello** [comment]
Confirmed, thats the patch causing this bug. Building it without patching `avatar_menu.cc` brings the menu back.

This also fixed a bug I didn't know about. I can now right click Chromium's icon in the dock to select user - it wasn't showing anything before. I also didn't see any additional connection when messing with the users, this seems safe to enable.
Here is the resulting `.dmg`: https://my.mixtape.moe/srkvhc.dmg
