### ISSUE TITLE
Remove this forever

### ISSUE THREAD

**Issue by pzeups** [Eloston/ungoogled-chromium#458]
<img width="507" alt="capture d ecran 2018-08-17 a 05 28 19" src="https://user-images.githubusercontent.com/1773176/44246532-f335c880-a1de-11e8-833a-8f1366dcbd09.png">

**Comment by Zig-03** [comment]
No, just add a check box saying "Never ask me again". This functionality may be important for someone.

**Comment by Artur96** [comment]
It's storage for remembered passwords, I think.

**Comment by Eloston** [comment]
So if we disable this, credentials can't be saved, right?

There's a flag in Chromium to change the credentials storage type. Would changing it to another one disable this dialog box?

**Comment by Artur96** [comment]
Yeah, but if you choose the basic option, you'll be [storing your passwords plaintext](https://askubuntu.com/a/968149)

**Comment by Eloston** [comment]
Yes, but do we have any other option? Is there a way to automatically unlock it? What does Chrome do?

**Comment by antonin-lebrard** [comment]
The whole text could be roughly translated in english to :

<b>Chromium want to use your confidentials <br> informations kept in "Chromium Safe <br> Storage" of your key hold.</b>_(don't know for this one)_.
The authenticity of "Chromium" can't be verified. For<br>authorizing it, enter the password of your key hold<br> "session"
Password : [ Text Area ]

| Always Authorize  |  Refuse  |   Authorize  |

**Comment by Artur96** [comment]
In macOS, you can select 'Always allow' (like in OP) to make it automatically unlock.

Whereas for GNU/Linux, you can make the [keyring unlock automatically on startup](https://wiki.archlinux.org/index.php/GNOME/Keyring#Using_the_keyring_outside_GNOME).

**Comment by Artur96** [comment]
@Eloston I've just checked, it doesn't.

**Comment by Eloston** [comment]
68 is out. Closing stale bugs.

@pzeups If none of the above solutions are satisfactory, then please let us know what you want.

**Comment by MEPoss** [comment]
I have "Ask to save password" disabled but I still see this popup every time I launch ungoogled-chromium.
