### ISSUE TITLE
[Feature Request] Portable Windows build

### ISSUE THREAD

**Issue by rodneyrod** [Eloston/ungoogled-chromium#46]
If possible, it would be great to add this as an option to chrlauncher (https://github.com/henrypp/chrlauncher)

**Comment by Eloston** [comment]
I believe this is an issue for chrlauncher to take care of. Plus, chrlauncher already supports forks of Chromium. [See this](https://github.com/henrypp/chrlauncher#supported-browser).

I'm closing this for now unless I've been mistaken.
