### ISSUE TITLE
[Idea] Add Someone Features From Advance Chrome Fork

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [Eloston/ungoogled-chromium#460]
Advance Chrome is a Special Build Of Chromiun That add:

- Improved Download System.
- Allows to open, save or discard downloads.
- Downloads show realtime speed.
- Integrated Flash Player.
- Option to block javascript located on right click menu.
- Webpage read mode option located on right click menu.
- Browser address bar show full URLs.
- Enabled Password Autofill on self signed SSL sites.
- Disabled Blurry fonts created by DirectWrite and Skia.
- All Chrome stock features working.

and many others here: [http://browser.taokaizen.com/](Advance Chrome´s Page)
And of course the [http://browser.taokaizen.com/download/patch.txt](The Diff File)

**Comment by Eloston** [comment]
I've seen this before in #279. Closing this as a duplicate.
