### ISSUE TITLE
[Enhancement] Double click on tab to close it

### ISSUE THREAD

**Issue by intika** [Eloston/ungoogled-chromium#464]
First thank you for your amazing work 

Since NPAPI is no more used on browser, and the confinement of web-extensions it not possible anymore to make an extension to close tab on double click...

there for i am suggesting this feature  

Thanks

**Comment by Eloston** [comment]
I'm fine with this, as long as it lives behind a command-line flag (at most a setting behind `chrome://flags`). But, I can't guarentee that it will continue to be maintained in the event that the codebase changes significantly.

I'll see to adding this info into the README, since I think I've seen this come up often enough.

**Comment by intika** [comment]
i made a modified version with an ugly patch to "chrome/browser/ui/views/tabs/tab.cc" around line 1000 next to middle click close tab function... if i can made my patch clean i will pull request... 
i am just having trouble with libc version to make my compiled version work on my main machine which have older libc...

**Comment by intika** [comment]
Here is my ugly patch... it works but it need some additional work 
`--- tab.cc      2018-09-10 04:24:37.114899715 +0000
+++ chromnormal/ungoogled-chromium/build/src/chrome/browser/ui/views/tabs/tab.cc        2018-08-08 19:10:41.000000000 +0000
@@ -964,14 +964,10 @@
         }
       } else if (!IsSelected()) {
         controller_->SelectTab(this);
-        //intika
-        dblClick = 0;
         base::RecordAction(UserMetricsAction("SwitchTab_Click"));
       }
     } else if (!IsSelected()) {
       controller_->SelectTab(this);
-      //intika
-      dblClick = 0;
       base::RecordAction(UserMetricsAction("SwitchTab_Click"));
     }
     ui::MouseEvent cloned_event(event_in_parent, parent(),
@@ -986,9 +982,6 @@
   return true;
 }
 
-//Intika Fucking dblclick 
-int dblClick = 0;
-
 void Tab::OnMouseReleased(const ui::MouseEvent& event) {
   controller_->OnMouseEventInTab(this, event);
 
@@ -997,16 +990,13 @@
   // In some cases, ending the drag will schedule the tab for destruction; if
   // so, bail immediately, since our members are already dead and we shouldn't
   // do anything else except drop the tab where it is.
-  if (controller_->EndDrag(END_DRAG_COMPLETE)){
-        dblClick = 0;
-       return;
-    }
+  if (controller_->EndDrag(END_DRAG_COMPLETE))
+    return;
 
-  // Close tab on µmiddle click, but only if the button is released over the tab
+  // Close tab on middle click, but only if the button is released over the tab
   // (normal windows behavior is to discard presses of a UI element where the
   // releases happen off the element).
   if (event.IsMiddleMouseButton()) {
-    dblClick = 0;
     if (HitTestPoint(event.location())) {
       controller_->CloseTab(this, CLOSE_TAB_FROM_MOUSE);
     } else if (closing_) {
@@ -1023,28 +1013,11 @@
     // If the tab was already selected mouse pressed doesn't change the
     // selection. Reset it now to handle the case where multiple tabs were
     // selected.
-      
-    //--------------------------------------------------------INTIKA
-    if (!IsSelected()) {
-        dblClick = 0;
-    }
-      
-    if (dblClick > 1) {
-        dblClick = 0;
-        if (HitTestPoint(event.location())) {
-          controller_->CloseTab(this, CLOSE_TAB_FROM_MOUSE);
-        } else if (closing_) {
-          Tab* closest_tab = controller_->GetTabAt(this, event.location());
-          if (closest_tab)
-            controller_->CloseTab(closest_tab, CLOSE_TAB_FROM_MOUSE);
-        }
-    } else { //------------------------------------------------INTIKA
-        controller_->SelectTab(this);
-           dblClick++;
-        if (alert_indicator_button_ && alert_indicator_button_->visible() &&
-            alert_indicator_button_->bounds().Contains(event.location())) {
-          base::RecordAction(UserMetricsAction("TabAlertIndicator_Clicked"));
-        }
+    controller_->SelectTab(this);
+
+    if (alert_indicator_button_ && alert_indicator_button_->visible() &&
+        alert_indicator_button_->bounds().Contains(event.location())) {
+      base::RecordAction(UserMetricsAction("TabAlertIndicator_Clicked"));
     }
   }
 }
`

**Comment by intika** [comment]
I made my custom version available here https://github.com/intika/UGChrome/

**Comment by Eloston** [comment]
Do you still want a switch for this feature? If not, I'll close this.

**Comment by intika** [comment]
just close it, it's a little bit out of the scope of the project, i will maintain this patch on https://github.com/intika/UGChrome/ tho

**Comment by Eloston** [comment]
I don't have a use for this feature.

For anyone reading this, feel free to submit a PR if inclined.
