### ISSUE TITLE
[Windows] Installing WidevineCDM

### ISSUE THREAD

**Issue by vaguiners** [Eloston/ungoogled-chromium#465]

**Comment by vaguiners** [comment]
Using lastest x64 build for windows

**Comment by vaguiners** [comment]
i did not
im just using the lastest x64  unchromium

**Comment by Eloston** [comment]
ungoogled-chromium is the same as regular Chromium; you must install the Widevine CDM. No one has reported how to do this on Windows. If you figure it out, you may submit a PR against the Wiki to add it.

**Comment by vaguiners** [comment]
k i got this by simply downloading the widevide folder from chrome/chromium
looks like the chrome/chormium come without widevine, but it download from google servers when you frist starty your browser.

**Comment by Innomen** [comment]
Elo loves closing issues instead of dealing with them. Wow. What does closed mean to you guy? Because closed to me means, like case closed, problem solved.

**Comment by erm3nda** [comment]
I tried copying the Widevine folder as is from chrome and didn't work. By the way, ungoogled-chromium says "error on update" in every component at chrome://components.

**Comment by Eloston** [comment]
Weird, I don't see when the issue was closed. Going to re-open it.

@erm3nda Which ungoogled-chromium version are you using? And which Chrome did you get Widevine from? Are they both the same architecture? Where did you copy it to? What components do you see in `chrome://components`?

**Comment by LIINdd** [comment]
Installing WidewineCDM is pretty simple actually. 

On version 79.0.3945.88-1 of Ungoogled Chromium:

1. Download version 79.0.3945.88 (latest) of regular Google Chrome.

2. After it's installed, go to the Chrome folder, for this version, where you need to go is; "C:\Program Files (x86)\Google\Chrome\Application\79.0.3945.88", if you have another version of Chrome, that version will be the name of the folder.

3. Copy the folder "WidevineCdm" and Paste it into root of your Ungoogled Chromium (so where the .exe is, not inside the User Data folder) and that should be it. 

Worked for me so far with no issues. If you have a specific older version of Ungoogled Chromium that you really want to use, you just need to find the Chrome specific to that version and do the same thing.

**Comment by hariskar** [comment]
This didn't work for me in Windows 64 and in gentoo linux
Also in chrome://components/ all componets are Version: 0.0.0.0 and Status - Update error and can't be updated with Check for updated button (nothing happens)

Thank you for ungoogled chromium!

**Comment by Eloston** [comment]
This was added to the Wiki recently. Closing.
