### ISSUE TITLE
Widevine is not showing at chrome:components

### ISSUE THREAD

**Issue by glomeg132** [Eloston/ungoogled-chromium#466]
I tried to install Widevine after instructions in Wiki. Unfortunately without success. I was able to put libwidevinecdm.so in /usr/lib/chromium. After a restart, however, Widevine will not appear under chrome: components. I use ungoogled Chromium 67.0.3396.87 under Ubuntu.

**Comment by glomeg132** [comment]
Unfortunately, I do not know how to program ungoogled chromium.

**Comment by Eloston** [comment]
Yes, 67 is the current version for Ubuntu bionic. If you are willing to wait, usually someone will come around to submit binaries.

**Comment by Eloston** [comment]
Closing since 69 has come out. If Widevine still doesn't show in `chrome://components` **and** it doesn't work, then let us know.
