### ISSUE TITLE
System requirements for building

### ISSUE THREAD

**Issue by tonowoe** [Eloston/ungoogled-chromium#467]
I think it would be a good idea to add the information in to the [building page](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md) that [you need at least 8GB of RAM to be able to build chromium](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md), less than that and building will likely fail. I just tested building the ungoogled-chromium on 64-bit Intel 4 core CPU with 4GB RAM and it failed due to lack of RAM.

Also by the way, here's the list of all the needed packages for building in Debian 9 (stretch): 

clang-6.0 lld-6.0 llvm-6.0-dev packaging-dev python python3 ninja-build python-jinja2 gsettings-desktop-schemas-dev flex yasm xvfb gperf bison valgrind x11-apps xfonts-base libglew-dev libgl1-mesa-dev libglu1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev mesa-common-dev libxt-dev libre2-dev libgbm-dev libpng-dev libxss-dev libelf-dev libvpx-dev libpci-dev libcap-dev libkrb5-dev libexif-dev libflac-dev libudev-dev libopus-dev libwebp-dev libxtst-dev libsrtp-dev libjpeg-dev libxml2-dev libgtk-3-dev libxslt1-dev liblcms2-dev libpulse-dev libpam0g-dev libsnappy-dev libavutil-dev libavcodec-dev libavformat-dev libglib2.0-dev libasound2-dev libjsoncpp-dev libspeechd-dev libminizip-dev libhunspell-dev libharfbuzz-dev libusb-1.0-0-dev libopenjp2-7-dev libmodpbase64-dev libnss3-dev libnspr4-dev libcups2-dev libevent-dev libjs-jquery libjs-excanvas libjs-jquery-flot libgcrypt20-dev libva-dev

The building commands could be little bit clearer. Like in the information about adding backports, there could be something like:
_add this line to your sources.list (/etc/apt/sources.list):
`deb http://ftp.debian.org/debian stretch-backports main`_

and in the building commands before the "mkdir -p build/src" line:
```
git clone https://github.com/Eloston/ungoogled-chromium.git
cd ungoogled-chromium/
mkdir -p...
```

**Comment by Eloston** [comment]
> I think it would be a good idea to add the information in to the building page that you need at least 8GB of RAM to be able to build chromium, less than that and building will likely fail. I just tested building the ungoogled-chromium on 64-bit Intel 4 core CPU with 4GB RAM and it failed due to lack of RAM.

You are correct that it at least deserves a mention, especially since there are flags that can be tweaked which affect RAM consumption during building (e.g. GN flag `jumbo_file_merge_limit`).

> The building commands could be little bit clearer

Thanks for the feedback. I will see to clarifying them.

**Comment by Eloston** [comment]
Fixed in `master`
