### ISSUE TITLE
Option to disable javascript clipboard manipulation

### ISSUE THREAD

**Issue by yegor-alexeyev** [Eloston/ungoogled-chromium#47]
It would be nice to have configuration option that disables javascript clipboard API( https://www.w3.org/TR/clipboard-apis/ ). A feature like this is configurable in firefox using parameter dom.event.clipboardevents.enabled. Here are some rationale for the feature: http://superuser.com/questions/703744/how-do-i-prevent-read-more-www-site-com-from-being-injected-with-non-tynt-jav

**Comment by Eloston** [comment]
Sounds like a good idea if it's not implementable via an extension.

**Comment by macandchief** [comment]
In that superuser thread the Kill Evil extension https://chrome.google.com/webstore/detail/kill-evil/epieehnpcepgfiildhdklacomihpoldk was mentioned.
In Scriptsafe there is also "Options/Fingerprint Protection/Prevent Clipboard Interference" to check.

**Comment by Eloston** [comment]
Sounds like it's already been done, so I'm closing this.
