### ISSUE TITLE
docs/linux_build_instructions.md doesn't exist.

### ISSUE THREAD

**Issue by anchev** [Eloston/ungoogled-chromium#473]
[building.md](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md) says:

> For 64-bit systems, at least 8 GB of RAM is highly recommended (per the document in the Chromium source tree under docs/linux_build_instructions.md).

However there is no such file.

**Comment by Eloston** [comment]
Please, read your quoted text again and more carefully.

**Comment by anchev** [comment]
May I please ask what is "Chromium source tree"? Maybe I have misunderstood that part as I was looking at https://github.com/Eloston/ungoogled-chromium/tree/master/docs

**Comment by Eloston** [comment]
This repository contains the "ungoogled-chromium source tree" because it contains source code files for ungoogled-chromium. Therefore, the "Chromium source tree" contains source code files for Chromium. Google owns Chromium, so you can get the Chromium source tree from Google.

Hope this helps.
