### ISSUE TITLE
Cannot install extensions from Chrome webstore

### ISSUE THREAD

**Issue by vishaltelangre** [Eloston/ungoogled-chromium#48]
![Alt text](https://monosnap.com/file/0VJovivjRPDXIhi5cz9VZZtHajCgj8.png)

**Comment by mmoya** [comment]
Check [Can I install extensions from the Chrome Webstore?](https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#can-i-install-extensions-from-the-chrome-webstore) in the FAQ.

**Comment by Eloston** [comment]
Thanks @mmoya.
