### ISSUE TITLE
Generated PKGBUILD fails due to missing third_party/dom_distiller_js/protoc_plugins/*.py

### ISSUE THREAD

**Issue by Tank-Missile** [Eloston/ungoogled-chromium#483]
[error.log](https://github.com/Eloston/ungoogled-chromium/files/2355012/error.log)

**Comment by Eloston** [comment]
It seems like it fails on the sed command right after domain substitution, which is [line 80 of PKGBUILD.ungoogin](https://github.com/Eloston/ungoogled-chromium/blob/ef7354d05a1c591a18285fdcf7c9f68d2332921b/packaging/archlinux/PKGBUILD.ungoogin#L80).

@xsmile Have the file paths changed, or should the line be removed?

**Comment by xsmile** [comment]
This is fine, however `sed` and the following commands need to be run on the Chromium source. A `cd "$_tree"` is missing after the buildkit operations.

**Comment by Eloston** [comment]
@xsmile I see, didn't realize it was in the wrong directory. Thanks.
