### ISSUE TITLE
[Windows] Ungoogled and sites login

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#484]
Every time when I login to instagram, twitter.... and similar I am receiving e-mail from them like I used different device, but the device is the same whole the time.

I tested Ungoodled 55, 65 and 67 and all of them has this behavior in Windows.

**Comment by Eloston** [comment]
My guess would be cookie settings. By default, third-party cookies are disabled. There may be some other default settings in `chrome://settings` that are causing session identification information to be lost. Let me know if the settings can't be tweaked to fix your problem.

I believe kind of default behavior is desirable by privacy-conscious users. However, if this behavior can't be changed via settings, then it is a bug.

**Comment by ipeacocks** [comment]
It's was because of this option https://i.imgur.com/KZp0lqb.png
