### ISSUE TITLE
[Howto] Build it in 10 min with google cloud computing

### ISSUE THREAD

**Issue by intika** [Eloston/ungoogled-chromium#491]
**Note :**
Please close that issue... I did not made a pull request on building.md i wanted first to post here... also may be i can pull request building.md just to link here, as we can answer the post it's easier when we have an issue when building new versions instead of creating new issue...

**Infos :** 
Google provide a VM/Servers services with it's cloud computing service, also it offer more than 200 euros trial to new users, so why not use a powerfull machine to build this beast in a reasonable time and also may be have a kind of cli instruction to make it a little more easy for contributors 

**Where :** 
Just create an account at https://cloud.google.com/

**Infos II :** 
I managed to build v68 there against glibc v2.22 (for portability) i used an opensuse vm

 **How To :** 
After creating a new account or using your existing one 
install gcloud from here https://cloud.google.com/sdk/install or use a portable version or...

Create a virtual machine with opensuse (Note that opensuse vm can only be ceated with the gcloud command because opensuse image is a community image so its not listed on the web interface. also note that i am using a special config with 24 cpu cores etc. so update the command to your needs)
`./gcloud compute instances create osuse-leap-42-3-2018 --image-family opensuse-leap --image-project opensuse-cloud --zone europe-west4-b --boot-disk-type pd-ssd --boot-disk-device-name=bootssd --boot-disk-size=40GB --min-cpu-platform 'Intel Skylake' --custom-cpu 24 --custom-memory 64GB`

If you want to remote your VM directly with ssh and not with the web terminal you will need to add an ssh key (How to generate a key is explained here https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys)
`./gcloud compute config-ssh --ssh-key-file /home/path/to/your/ssh/key.key`

Connect to your vm 
`ssh 35.0.0.154 -i /home/path/to/your/ssh/key.key`
`sudo su `

You can then follow https://github.com/Eloston/ungoogled-chromium/issues/490 for building instructions

**Comment by Eloston** [comment]
Same as https://github.com/Eloston/ungoogled-chromium/issues/492#issuecomment-420129329
