### ISSUE TITLE
[Howto] Build portable v68 on fedora 

### ISSUE THREAD

**Issue by intika** [Eloston/ungoogled-chromium#492]
**Note :**
Please close that issue... I did not made a pull request on building.md i wanted first to post here... also may be i can pull request building.md just to link here, as we can answer the post it's easier when we have an issue when building new versions instead of creating new issue...

**Note II:**
Fedora is using a new version of glibc, so if you are planning to distribute the portable binary for distro other than fedora, it's not a good idea to build it with fedora

**Where did i build :**
I used Scaleway Cloud Services with a VM running Fedora v28

**Building Instructions For Fedora For Portable Version  :**
Update & install needed packages
```
dnf update 
dnf install wget git patch nano ninja-build python36
dnf builddep chromemium
dnf install perl-Switch dirac-devel hunspell-devel imlib2-devel libdc1394 libdc1394-devel libavcodec-devel yasm-devel libexif-devel libtheora-devel schroedinger-devel minizip-devel libvdpau-devel slang-devel libjack-devel libavformat-devel SDL-devel ninja binutils-gold bison cups-devel desktop-file-utils fdupes flex gperf hicolor-icon-theme libcap-devel libelf-devel libgcrypt-devel libgsm libgsm-devel libjpeg-devel libpng-devel libva-devel ncurses-devel pam-devel pkgconfig re2-devel snappy-devel update-desktop-files util-linux wdiff alsa Mesa-dri-devel cairo-devel libavutil-devel libavfilter-devel libdrm2 libdrm-devel libwebp-devel libxslt-devel libopus-devel rpm-build --skip-broken
yum install clang*
yum install llvm llvm-static llvm-devel ninja*
```
Clone sources
```
git clone https://github.com/Eloston/ungoogled-chromium.git
cd ungoogled-chromium
```
Prepare sources
```
mkdir -p build/src
./get_package.py linux_simple build/src/ungoogled_packaging
cd build/src
```
Edit `./ungoogled_packaging/build.sh ` and remove the last line starting with ninja

Prepare build 
`./ungoogled_packaging/build.sh`

Build (Note that `-j48` is for a cpu with 48 cores so update that number according to how many build thread you want to run at the same time)
`ninja -j48 -C out/Default chrome chrome_sandbox chromedriver`

Create the tar archive with the portable chromium
`./ungoogled_packaging/package.sh`

**Comment by Eloston** [comment]
Thanks for the instructions. If you could, please submit a PR with the information integrated into the Portable Linux building instructions.

Issues are not designed for long-term discussions. They are designed for short conversations that address specific concerns. If changes need to be made, they can be said in commit comments or new issues. This may not be what others are doing with issues, but it's a system that has been working well with this project (and long discussions definitely don't work on GitHub).

**Comment by intika** [comment]
@Eloston i just sent a pr ;)
