### ISSUE TITLE
Installer scripting for Linux 

### ISSUE THREAD

**Issue by tristan-k** [Eloston/ungoogled-chromium#5]
> The Pale Moon for Linux installer (also referred to as pminstaller) is a program that is meant to ease installation of the Pale Moon binaries on Linux, made available on http://linux.palemoon.org.

https://github.com/MoonchildProductions/PM4Linux-installer

Maybe adapt the installer for ungoogled-chromium? This way updating would be easier.

**Comment by Eloston** [comment]
I don't see the benefits in using this packaging system. I would rather create distribution-specific packages than use a third party system.

There are already scripts to create Debian and Ubuntu packages. If you need packages for another distribution, open a new issue report.

**Comment by tristan-k** [comment]
> I would rather create distribution-specific packages than use a third party system. 

That would be great. I'm just concerned about security updates which wont make it to the avaerage user because of the lack of a easy update system.

**Comment by Eloston** [comment]
I don't understand what you mean be "easy update system". At least on Debian, one can download packages and use `dpkg -i <package>.deb` to install them. This seems pretty straight-forward and simple. Unless you mean you want a way to install updates without root privilages.
