### ISSUE TITLE
crash MacOS 10.9.5

### ISSUE THREAD

**Issue by brighterness** [Eloston/ungoogled-chromium#501]
first: this older macbook pro cannot be updated to any newer version of the OS :'(   I see the dev version is abandoning me.  Am I entirely hosed for preventing privacy raping?

### describe

 download dmg, unpack to apps, waive quarantine, right click open, crash

`xattr -d com.apple.quarantine /Applications/Chromium.app`

crash

Process:         Chromium [504]
Path:            /Applications/Chromium.app/Contents/MacOS/Chromium
Identifier:      org.chromium.Chromium
Version:         67.0.3396.87 (3396.87)
Code Type:       X86-64 (Native)
Parent Process:  launchd [190]
Responsible:     Chromium [504]
User ID:         501

Date/Time:       2018-09-14 02:28:12.545 -0700
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8d59f866 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8751235c pthread_kill + 92
2   libsystem_c.dylib             	0x00007fff86069b26 abort + 125
3   org.chromium.Chromium         	0x000000010d989d94 main + 304
4   libdyld.dylib                 	0x00007fff843605fd start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fff72cc0310  rcx: 0x00007fff52276c98  rdx: 0x0000000000000000
  rdi: 0x0000000000000707  rsi: 0x0000000000000006  rbp: 0x00007fff52276cc0  rsp: 0x00007fff52276c98
   r8: 0x0000000000000040   r9: 0x00007fff52276b00  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fa100808e00  r13: 0x00006080000e5200  r14: 0x0000000000000006  r15: 0x0000000000000001
  rip: 0x00007fff8d59f866  rfl: 0x0000000000000206  cr2: 0x00007fa100402000
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Binary Images:
       0x10d989000 -        0x10d989fff +org.chromium.Chromium (67.0.3396.87 - 3396.87) <5037A471-7C9F-3E13-B855-AC2E158C396A> /Applications/Chromium.app/Contents/MacOS/Chromium
  
External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 483
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=160.5M resident=136.7M(85%) swapped_out_or_unallocated=23.8M(15%)
Writable regions: Total=30.7M written=172K(1%) resident=404K(1%) swapped_out=0K(0%) unallocated=30.3M(99%)
 
REGION TYPE                      VIRTUAL
===========                      =======
Kernel Alloc Once                     4K
MALLOC                             22.4M
MALLOC (admin)                       32K
STACK GUARD                        56.0M
Stack                              8192K
VM_ALLOCATE                           8K
__DATA                             20.9M
__IMAGE                             528K
__LINKEDIT                         63.5M
__TEXT                             96.9M
__UNICODE                           544K
shared memory                         4K
===========                      =======
TOTAL                             268.9M

Model: MacBookPro4,1, BootROM MBP41.00C1.B03, 2 processors, Intel Core 2 Duo, 2.6 GHz, 4 GB, SMC 1.28f3
Graphics: NVIDIA GeForce 8600M GT, GeForce 8600M GT, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR2 SDRAM, 667 MHz
Memory Module: BANK 1/DIMM1, 2 GB, DDR2 SDRAM, 667 MHz
Serial ATA Device: Samsung SSD 850 EVO 250GB

**Comment by Eloston** [comment]
I'm going to bet that your macOS is too old because:

```
Application Specific Information:
abort() called
```

so it's likely that Chromium decided to kill itself for some reason.

If the aged system isn't the issue, I'd be glad to reopen and have others investigate.

> Am I entirely hosed for preventing privacy raping?

Linux works well across a broader range of hardware, and software compatibility is better too. Given that you have an older Macbook Pro, it should work very well.
