### ISSUE TITLE
Installing Ungoohled Chromium Multiple Times On Linux

### ISSUE THREAD

**Issue by trymeouteh** [Eloston/ungoogled-chromium#509]
Is there a way to install this browser more than once on Linux. I know the windows version is a portable one so all you need to do is extract it into different folders and you can have many installments.

**Comment by Eloston** [comment]
I'm assuming this is the same problem as #510. Please correct me otherwise.

**Comment by trymeouteh** [comment]
This is for Linux, Not windows. I would like to install this browser multiple times on my Ubuntu machine but cannot figure out a way.

**Comment by Eloston** [comment]
You can use the Portable Linux version. It's essentially the Linux equivalent of the Windows build.
