### ISSUE TITLE
Multiple Installations On Windows

### ISSUE THREAD

**Issue by trymeouteh** [Eloston/ungoogled-chromium#510]
Chromiums is a portable installer but when I install it twice or more times all the settings are shared across each installment. Is it possible to make it each installment of Ungoogled Chromium is fully separate from eachother? I know Vivaldi browser allows this with its own portable installation.

**Comment by Eloston** [comment]
In Chromium, you can change the user data directory to a custom path via a command-line argument. This is a commonly-used feature you can search online for.

**Comment by trymeouteh** [comment]
Is it possible to create an installer that is an portable installer where you can select the user directory path for a more user friendly setup?

**Comment by Eloston** [comment]
> where you can select the user directory path

What do you mean by a "user directory path"?

**Comment by trymeouteh** [comment]
By choosing the user data directory custom path without a command line but instead use a installer to select the data directory

**Comment by Eloston** [comment]
Chromium's default installer does not support this. If you want this functionality, please develop it as a standalone wrapper around Chromium.
