### ISSUE TITLE
 fatal error: 'uuid/uuid.h' file not found

### ISSUE THREAD

**Issue by FabioNevesRezende** [Eloston/ungoogled-chromium#512]
### Problem description 

header file not found. I've followed the steps to build for debian based system. Building fail at `third_party/fontconfig/src/src/fccache.c` with error message:

>../../third_party/fontconfig/src/src/fccache.c:42:10: fatal error: 'uuid/uuid.h' file not found                                                                                                 
>#include <uuid/uuid.h>                                                                                                                                                                          
>        ^~~~~~~~~~~~~
>1 error generated.

**Comment by Eloston** [comment]
Both `debian_buster` and `debian_stretch` config bundles build against the system's fontconfig library. I've tested both and never had any problems related to fontconfig.

What is your build configuration? What config bundles and packaging scripts are you using?

**Comment by FabioNevesRezende** [comment]
`debian_minimal` and "Building locally". I'll try now "Building via source package" maybe it works

**Comment by FabioNevesRezende** [comment]
Also "building via source package" didn't work:

>dpkg-source: info: building ungoogled-chromium-browser in ungoogled-chromium-browser_69.0.3497.100-1~portable.dsc
>dpkg-genbuildinfo --build=source
>dpkg-genchanges -sa --build=source >../ungoogled-chromium->browser_69.0.3497.100-1~portable_source.changes
>dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build src
>dpkg-buildpackage: info: full upload (original source is included)
>Now running lintian...
>Could not find a profile matching "{VENDOR}/main" for vendor devuan at /usr/share/lintian/commands/lintian line 1561.
>Finished running lintian.
>Now signing changes and any dsc files...
>signfile dsc ungoogled-chromium-browser_69.0.3497.100-1~portable.dsc ungoogled-chromium Authors <maintainer@null>
>gpg: skipped "ungoogled-chromium Authors <maintainer@null>": No secret key
>gpg: /tmp/debsign.X3HmiE6M/ungoogled-chromium-browser_69.0.3497.100-1~portable.dsc: clear-sign failed: No secret key
>debsign: gpg error occurred!  Aborting....
>debuild: fatal error at line 1045:
>running debsign failed

**Comment by Eloston** [comment]
You can retry `debian_minimal` with the latest commit and see if that fixes this for you.
