### ISSUE TITLE
Prediction/Suggestions in omnibox for custom search engines/Google

### ISSUE THREAD

**Issue by oktvn** [Eloston/ungoogled-chromium#513]
### Problem description

Even with the suggestion/autocomplete setting enabled ("Use a prediction service to help complete searches and URLs typed in the address bar") there are still no suggestions/autocomplete for custom search engine URLs _(it appears to only work for DuckDuckGo)_. 

When adding the Google search string present in chrome (`{google:baseURL}search?q=%s&{google:RLZ}{google:acceptedSuggestion}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:searchClient}{google:sourceId}{google:instantExtendedEnabledParameter}ie={inputEncoding}`) it doesn't get processed as it does in Chrome, nor does it work by default, an issue which I suspect is closely related to this.

**Comment by xsmile** [comment]
The search engine template in the source code allows the specification of an additional autocomplete URL, otherwise the feature won't work. For Google it was removed, DuckDuckGo has it and it works well, Searx' autocomplete API doesn't seem to be compatible to Chromium on the other hand and no URL was inserted.

I can't say much about custom search engines which are added while visiting web sites. If that URL is not added automatically, the only way to change this is probably by adding that search engine to the source.

**Comment by oktvn** [comment]
> For Google it was removed

Too bad. I'd say Google's autocomplete is unrivaled, and it could've gone well with 3rd party search engines (like DuckDuckGo). Any chance for having a config switch flag for that?

**Comment by Eloston** [comment]
I think it would be better to have another autocomplete URL field for this.

**Comment by xsmile** [comment]
I'm not sure how this can be done without restoring Google search which is removed by [replace-google-search-engine-with-nosearch.patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/ungoogled-chromium/replace-google-search-engine-with-nosearch.patch).
Even if only the relevant `suggest_url` field is restored, I don't think it will be used when Google is added as a search engine during runtime.

**Comment by Eloston** [comment]
@xsmile Is extending the UI and config infrastructure to add the necessary fields not sufficient to fix this?

**Comment by xsmile** [comment]
@Eloston I'm not sure I follow.

The suggestion/autocomplete feature works as of now, see DuckDuckGo.

From my point of view there is no way to use this feature with Google - or apparently any other search engine - without hard-coding the full search engine template, as it is done in the original Chromium. I may be wrong though, I didn't check the source.

**Comment by Eloston** [comment]
> From my point of view there is no way to use this feature with Google - or apparently any other search engine - without hard-coding the full search engine template

Right. My idea is to add the infrastructure necessary to convert these hard-coded values into new text fields in the search engine editing UI, so users can freely set them.

I haven't looked at the code either, so I don't know how involved it will be. My guess is that it will at least require additions to HTML, JavaScript, and C++ in the browser (to implement both frontend and backend code for the settings)

**Comment by xsmile** [comment]
@Eloston This sounds doable, considering that a very similar text field already exist for editing the URL of a search engine.

The Preferences text file in the user data directory stores the currently selected search engine and contains a `suggestions_url` property. Editing it manually will probably work too, as long as the search engine settings are not changed.

**Comment by intika** [comment]
Good work :+1:  but DDG or Google it's the same issue at the end of the day it's almost impossible to have some services without loosing a little of privacy... (it's the price to pay for a free service) now when it come to DDG i personally prefer using Google at least they are clear in what they are doing... DDG is for sure somehow better for privacy at first look but they are not angels ether, DDG is not an exception to the rule when a service is free it mean that you are the product
