### ISSUE TITLE
Disable fetching of all field trials

### ISSUE THREAD

**Issue by csagan5** [Eloston/ungoogled-chromium#514]
Some time ago I made this patch: https://github.com/bromite/bromite/blob/master/patches/BRM067_Disable-fetching-of-all-field-trials.patch

Can you check if it is valid and/or useful? I guess on desktop OSes you can use a command-line option to disable them.

**Comment by Eloston** [comment]
I believe the last file modified might be useful, but I'll need to find some time if I am to investigate. It's a small patch, so if it doesn't break anything on desktop, then it should be fine.
