### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by grepwood** [Eloston/ungoogled-chromium#516]
Does it still take tens of GBs of memory in every aspect of interaction with this?

My grievances with Chromium were such:

- compiling the codebase takes 16GB RAM with just 1 compilation thread
- being an impatient person when it comes to compilation, I like to put the entire source and objects into a RAM disk, which can take another 16GB
- using the end result would still account for significant drains in available memory, and all that memory, where does it go if I can't tell the difference in performance with competing slimmer browsers? Is it going to Bitcoin mining?
- every time there's an update for Chromium and Widevine, they might not be keyworded in Portage which means I have to adjust the Chromium version to Widevine version or vice-versa, thus even wasting time to recompile Chromium if Netflix throws a baby tantrum when Widevine isn't the latest

I hope these issues are somehow addressed here by virtue of ungoogling the codebase.

**Comment by Eloston** [comment]
> compiling the codebase takes 16GB RAM with just 1 compilation thread

This is not true with the correct configuration; see the following response.

> I like to put the entire source and objects into a RAM disk, which can take another 16GB

It's possible to have the source tree fit entirely within 8-9 GB and still have enough to compile and link. I do this for my Debian builds on a machine with 16 GB of RAM.

But I do this to reduce wear on my storage devices, not for performance. I don't believe there is much of a performance improvement with RAM disks compared to non-volatile storage devices, but I have no data to back this up.

> using the end result would still account for significant drains in available memory, and all that memory, where does it go if I can't tell the difference in performance with competing slimmer browsers? Is it going to Bitcoin mining?

I don't know the Chromium code nearly well enough to tell you the breakdown of memory usage. You'd need people with the equivalent knowledge of core Chromium developers (for at least Blink and V8) to get a satisfactory answer. On a tangential note, DevTools has some profiling tools that might give you some insights on the HTML/CSS/JavaScript side.

> I hope these issues are somehow addressed here by virtue of ungoogling the codebase.

All of your concerns fall under secondary objectives of this project. I am open to anyone contributing features to resolve these problems.

**Comment by grepwood** [comment]
> But I do this to reduce wear on my storage devices, not for performance. I don't believe there is much of a performance improvement with RAM disks compared to non-volatile storage devices, but I have no data to back this up.

I beg to differ. Using LibreOffice as an example I testify that putting `/var/tmp` (default `$TMPDIR` for Portage) into a 23GB RAM disk allows me to emerge it in just 40 minutes compared to standard 440 minutes. This amount of space I found is optimal for that package - it fits the source code, the objects, it satisfied the ebuild's storage requirements, and on a machine with 32GB RAM it's enough to let 16 compilation threads go. All at once. But this is using very light libraries, contrast to Chromium where 1 compilation thread can take a lot more memory.

>I don't know the Chromium code nearly well enough to tell you the breakdown of memory usage. You'd need people with the equivalent knowledge of core Chromium developers (for at least Blink and V8) to get a satisfactory answer. On a tangential note, DevTools has some profiling tools that might give you some insights on the HTML/CSS/JavaScript side.
>All of your concerns fall under secondary objectives of this project. I am open to anyone contributing features to resolve these problems.

If time allows, I'll try. Thank you.

**Comment by Eloston** [comment]
> I beg to differ. Using LibreOffice as an example I testify that putting /var/tmp (default $TMPDIR for Portage) into a 23GB RAM disk allows me to emerge it in just 40 minutes compared to standard 440 minutes. 

I forgot to mention that I have a SATA III SSD, so I'm not sure if RAM disks yield a significant improvement. If you're using a HDD, then your numbers make more sense.

**Comment by grepwood** [comment]
>I forgot to mention that I have a SATA III SSD, so I'm not sure if RAM disks yield a significant improvement. If you're using a HDD, then your numbers make more sense.
I'm using mdadm RAID10, far2, consisting of 4 HDDs, rough performance is somewhere at 200-320MB/s.

**Comment by Eloston** [comment]
> rough performance is somewhere at 200-320MB/s

Is this for random or sequential reading/writing? I don't think RAID 10 will help either performance metric much beyond what the HDDs already give you.

**Comment by grepwood** [comment]
Random. It may be cached though, I'm using LVM cache on an encrypted M2 SSD.
