### ISSUE TITLE
Consider switch back to GPL v3?

### ISSUE THREAD

**Issue by rudolfolah** [Eloston/ungoogled-chromium#517]
I saw the project switched last year from GPL to BSD; what was the reasoning behind that since the browser is desktop-based and it's valuable for modifications to be shared?

**Comment by Eloston** [comment]
The reason for this change and a brief history of the licensing are all in #230.

Switching back to GPLv3 would break license compatibility with that project.

I also don't see any reason why I'd need to change the license to anything else. In terms of code sharing, BSD has *more* freedom than GPLv3 in that non-GPL products or projects can easily use and modify this code. If the risk is of a company profiting off these changes with a proprietary solution, I fail to see how that would affect the main audience this project is targeting.

However, if you have stronger reasons for changing, please let me know.

**Comment by rudolfolah** [comment]
Thanks @Eloston for responding with a pointer to the discussion and a nice explanation as to why the license is BSD rather than GPL. It's nice to help free/open source software developer neighbours but at the same time...GPL sends a stronger message, at least to me, that the project is motivated by free software ideals and practical ideals such as breaking vendor lock-in.

For my own project I would lean toward GPLv3. In this case, it's very cool to see a good dialogue on which license to use and the choice of BSD does make sense.
