### ISSUE TITLE
How to install extensions such as uBlock Origin?

### ISSUE THREAD

**Issue by hardhub** [Eloston/ungoogled-chromium#518]
There is not possibility to download it from Google store.  
Does it mean the single way to do it manually?

**Comment by antonin-lebrard** [comment]
In the FAQ, first question, first answer:
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-from-the-chrome-webstore

**Comment by mtimofiiv** [comment]
Instructions on installing extensions are here:
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-from-the-chrome-webstore

**Comment by hardhub** [comment]
@antonin-lebrard Thank you! But it is still not clear how to update automatically.

**Comment by antonin-lebrard** [comment]
@hardhub Unfortunatly I didn't find any way to auto update each extensions.
But in my experience it is actually a very good thing, as extensions may change of owner without notice or the owner might be malicious, and profit of autoupdate behavior of chrome to update its extensions with crypto-miner, adware, malware, anti-privacy features etc... 

I prefer to search for the code source of each extensions I wish to install/update.
It might be cumbersome, but I don't see better way to manage this automaticaly

**Comment by fractalf** [comment]
For reference, you can also install uBlock Origin manually like they describe here https://github.com/gorhill/uBlock/tree/master/dist#install

Easy pc
