### ISSUE TITLE
Are the builds automatically (or at least easily) reproducible?

### ISSUE THREAD

**Issue by d33tah** [Eloston/ungoogled-chromium#52]
I'd like to build ungoogled-chromium myself with h264 support. Is there any way to automate this process, e.g. using a Docker image?

**Comment by 9Morello** [comment]
What platform are you using? It should build just fine in Debian Jessie/Stretch, Ubuntu 16.04-based distros and OS X (with proprietary codecs support). Check the [build page](https://github.com/Eloston/ungoogled-chromium/blob/master/BUILDING.md).

After installing the dependencies, you just run `build.py` and it should build without more input from you.

**Comment by Eloston** [comment]
Yep, and Windows too (though you'll have to do a little more work).

Though to what degree do you want the automation to be? It's already pretty automated; you don't have to download the source code, run GYP, or invoke ninja yourself.

And like @9Morello said, all of these platforms have H.264 support enabled.

**Comment by RobinThrift** [comment]
It would be amazing to have automated builds with automated releases. So every time the repo ist updated with a new version, an automated system would build it and add it as a github release. This would greatly reduce setup cost for users and make in generally more accessible.

**Comment by RobinThrift** [comment]
something like https://www.appveyor.com/ could be used for windows builds and https://travis-ci.org for mac and linux builds.

**Comment by Eloston** [comment]
@RobinThrift: This is the wrong thread to post this information. Please head over to #17. Thanks!

I am closing this issue since the question here seems to be answered. If this is not the case, please comment.
