### ISSUE TITLE
use_gnome_keyring=false

### ISSUE THREAD

**Issue by anchev** [Eloston/ungoogled-chromium#523]
I noticed that `gn_flags.map` has this line:
```
use_gnome_keyring=false
```
but after building ungoogled-chromium I can start it with `--password-store=gnome` and it does use gnome keyring.

What is the reason for having the above line?

**Comment by Eloston** [comment]
I don't know. How is it used inside the GN files?

**Comment by anchev** [comment]
Considering [the reply](https://github.com/Eloston/ungoogled-chromium/issues/447#issuecomment-422963751) about what GN args are, I suppose you mean `args.gn`. (Please correct me if I am wrong) However I didn't keep the source code after building, just the final tar.xz. Do I need to rebuild again the whole thing in order to find the answer to your question or something else?

**Comment by Eloston** [comment]
No, I'm referring to the GN definition files, which consist of `BUILD.gn` and `*.gni` files throughout the Chromium source tree.

**Comment by anchev** [comment]
```
[/tmp/download]: grep -rln use_gnome_keyring . | grep -E "BUILD.gn|(.+\.gni)"
./ungoogled-chromium/build/src/components/os_crypt/features.gni
./ungoogled-chromium/build/src/components/os_crypt/BUILD.gn
./ungoogled-chromium/build/src/chrome/test/BUILD.gn
./ungoogled-chromium/build/src/chrome/browser/BUILD.gn
```
The first file seems to define the usage of gnome keyring itself.
The others contain conditions based on it.

**Comment by Eloston** [comment]
According to `components/os_crypt/features.gni`, the flag `use_gnome_keyring` is only useful for legacy systems without libsecret (which is the successor to an older gnome-keyring interface). That file references the following bug reports:

* https://bugs.chromium.org/p/chromium/issues/detail?id=355223
* https://bugs.chromium.org/p/chromium/issues/detail?id=466975

If I am to guess, libsecret is probably what implements the `--password-store=gnome` option.

On a related note, it seems that `use_glib` controls whether libsecret support is built or not. But I'm not sure if toggling it is a good idea, since other integration features with GNOME may be grouped under it.

**Comment by anchev** [comment]
Yes. [This comment](https://bugs.chromium.org/p/chromium/issues/detail?id=466975#c2) talks about it but it is still not clear how it should be set. If I am reading this correctly libsecret is still not ready.

**Comment by Eloston** [comment]
@anchev Based on [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=355223#c17), it should have been ready about 2-3 years ago; otherwise password storage wouldn't be secure for newer systems (they fallback to basic storage).

**Comment by anchev** [comment]
Thanks for this info.

Hm. But that still sounds contradictory. I also searched the web for more.

Based on [this](https://chromium.googlesource.com/chromium/src/+/lkgr/docs/linux_password_storage.md) and [this](https://dev.chromium.org/Home/chromium-security/security-faq#TOC-Does-the-Password-Manager-store-my-passwords-encrypted-on-disk-) info on Linux one still needs to specify explicitly `--password-store=gnome` or `--password-store=kwallet`, otherwise it would fallback to `basic` (unencrypted). Also according to [this bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=571003) the work on dropping KDE's and Gnome's backends is started but not finished.

What do you understand from all that? It sounds like a big mess to me.

**Comment by Eloston** [comment]
> Based on this and this info on Linux one still needs to specify explicitly --password-store=gnome or --password-store=kwallet, otherwise it would fallback to basic (unencrypted). Also according to this bug report the work on dropping KDE's and Gnome's backends is started but not finished.

It uses GNOME Keyring by default for Debian stretch builds. I personally use it. `use_gnome_keyring=false` is set for all builds by default.

**Comment by anchev** [comment]
> It uses GNOME Keyring by default for Debian stretch builds.

Even with `use_gnome_keyring=false`? How is this possible? Isn't that setting supposed to disable it?

I don't know what "Debian stretch builds" means. I build it from source (as we talked in other issues).

**Comment by Eloston** [comment]
> Even with use_gnome_keyring=false? How is this possible? Isn't that setting supposed to disable it?

No, that GN flag disables the legacy interface. Like the Chromium issues mention, `libsecret` is the current mechanism used to interface with GNOME Keyring in modern systems, and also KWallet it seems.

> I don't know what "Debian stretch builds" means. I build it from source (as we talked in other issues).

These are the builds for Debian stretch that I build and publish myself.

**Comment by anchev** [comment]
I see.
Thanks!
