### ISSUE TITLE
Question - is navigator.webdriver disabled in this version?

### ISSUE THREAD

**Issue by nadavhury** [Eloston/ungoogled-chromium#524]
Question - is navigator.webdriver disabled in this version?

Thanks!

**Comment by Eloston** [comment]
What is navigator.webdriver?

**Comment by nadavhury** [comment]
It's a property which is exposed when using chrome-driver\selenium for testing\scraping.
added by google since version 68 I think.

**Comment by Eloston** [comment]
@nadavhury I have very limited experience with `chromedriver`. Are you not able to try it yourself?

**Comment by Eloston** [comment]
I looked into it a bit more, and I don't see any code that should be affecting this. If it's not working, please open a new issue with the specific interfaces that aren't working.

**Comment by drzraf** [comment]
Would you mind reconsidering and allow users to not set this (readonly) Navigator property to true in CDP/debugging mode?
Context:
https://github.com/w3c/webdriver/issues/872
https://bugzilla.mozilla.org/show_bug.cgi?id=1696425
