### ISSUE TITLE
Unreadable Address Bar in macOS Mojave Dark Mode

### ISSUE THREAD

**Issue by HunterMeyer** [Eloston/ungoogled-chromium#525]
### ungoogled-chromium version:
68.0.3440.106 (Official Build) (64-bit)

### Configuration and/or platform(s):
MacBook Pro, macOS Mojave 10.14 (18A391)
- Appearance: Dark

### Problem description
When Mac's Dark Mode is enabled the address bar gets a black background and font color.
It becomes unreadable.

![light-to-dark-mode](https://user-images.githubusercontent.com/4690516/46029212-cbc8fa00-c0c0-11e8-95a3-6e0abded0f41.png)

**Comment by Eloston** [comment]
Does the development version 69 have the same issue?

**Comment by Artur96** [comment]
@Eloston nope

**Comment by Eloston** [comment]
@Artur96 Thanks.

@HunterMeyer If the problem still occurs for you after upgrading, let us know.
