### ISSUE TITLE
chrome 69 does not delete Google cookies

### ISSUE THREAD

**Issue by steven-omaha** [Eloston/ungoogled-chromium#526]
I just came across this on Twitter. Vanilla chrome does not delete Google cookies when cookies are deleted. Is ungoogled-chromium affected by this?

![dn4ic7pwsaa7ce9](https://user-images.githubusercontent.com/35634100/46030200-d3ef5c80-c0f5-11e8-92bc-69a609e0a0a1.jpg)

**Comment by xsmile** [comment]
This seems to be related to the "Sign-in to Chromium" function of the browser which is disabled.

Otherwise all Google cookies are deleted, at least the ones contained in the 'Cookies' file found in the browser profile.

**Comment by steven-omaha** [comment]
If this is really the case, this issue can be closed. Is there a way to check this?

**Comment by xsmile** [comment]
You run Chromium with a new temporary profile, login to various Google sites,
```rm -rf /tmp/chromium-profile && chromium --user-data-dir=/tmp/chromium-profile```

and inspect the cookie database with e.g. sqlitebrowser:
```sqlitebrowser ~/.config/chromium/Default/Cookies```

**Comment by steven-omaha** [comment]
Trying the method from @xsmile, I can confirm that deleting cookies actually deletes all cookies on ungoogled-chromium-69.
