### ISSUE TITLE
error: use of undeclared identifier 'VA_FOURCC_I420'; did you mean 'libyuv::FOURCC_I420'

### ISSUE THREAD

**Issue by FabioNevesRezende** [Eloston/ungoogled-chromium#528]
### Problem description
Building fails at `../../media/gpu/vaapi/vaapi_jpeg_decode_accelerator.cc:177:19` with error message:

>../../media/gpu/vaapi/vaapi_jpeg_decode_accelerator.cc:177:19: error: use of undeclared identifier 'VA_FOURCC_I420'; did you mean 'libyuv::FOURCC_I420'?
> format.fourcc = VA_FOURCC_I420;
>                 ^~~~~~~~~~~~~~
>                libyuv::FOURCC_I420
> ../../third_party/libyuv/include/libyuv/video_common.h:54:3: note: 'libyuv::FOURCC_I420' declared here
> FOURCC_I420 = FOURCC('I', '4', '2', '0'),
> ^

**Comment by Eloston** [comment]
I believe the patch `ungoogled-chromium/linux/fix-libva1-compatibility.patch` will fix the problem. You can use `debian_stretch` as a reference for when to apply the patch in the patch order.

**Comment by FabioNevesRezende** [comment]
you mean, this https://github.com/Eloston/ungoogled-chromium/blob/master/patches/ungoogled-chromium/linux/fix-libva1-compatibility.patch?

how to apply these patches?

**Comment by FabioNevesRezende** [comment]
So, I've changed to `debian_stretch` and applied the patch

>./get_package.py debian_stretch build/src/debian/
>cd build/src
>git apply ../../patches/ungoogled-chromium/linux/fix-libva1-compatibility.patch

I also had to install a new dependency

>sudo apt-get install gsettings-desktop-schemas-dev

But now fails with

>ERROR at //BUILD.gn:668:7: Can't load input file.
>      "//third_party/libjpeg_turbo:simd",
>      ^---------------------------------
>Unable to load:
> /home/fabio/src/ungoogled-chromium/build/src/third_party/libjpeg_turbo/BUILD.gn
>I also checked in the secondary tree for:
>  /home/fabio/src/ungoogled-chromium/build/src/build/secondary/third_party/libjpeg_turbo/BUILD.gn
>debian/rules:88: recipe for target 'override_dh_auto_build-arch' failed
>make[1]: *** [override_dh_auto_build-arch] Error 1
>make[1]: Leaving directory '/home/fabio/src/ungoogled-chromium/build/src'
>debian/rules:68: recipe for target 'binary' failed
>make: *** [binary] Error 2
>dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

**Comment by FabioNevesRezende** [comment]
So I've just deleted everything and restarted, this time using `debian_stretch` and it worked successfully
