### ISSUE TITLE
CRX downloading URL returns HTTP status 204

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#531]
See https://github.com/Eloston/ungoogled-chromium/issues/448#issuecomment-424595808

**Comment by intika** [comment]
i personally use http://crxextractor.com/ to install extensions

**Comment by csmk** [comment]
> i personally use http://crxextractor.com/ to install extensions

It doesn't work if you try to download the aforementioned extension. It gives a blank page, at least for me.

**Comment by intika** [comment]
you still need to set the flag #extension-mime-request-handling to "always prompt..." under "chrome://flags" then the site works... i like that site because it extract the real link it's not proxified or something...

**Comment by csmk** [comment]
Did you try to download the [aforementioned](https://github.com/Eloston/ungoogled-chromium/issues/448#issuecomment-424595808) extension?!

**Comment by intika** [comment]
> Did you try to download the [aforementioned](https://github.com/Eloston/ungoogled-chromium/issues/448#issuecomment-424595808) extension?!

indeed does not work https://stackoverflow.com/questions/7184793/how-to-download-a-crx-file-from-the-chrome-web-store-for-a-given-id i did try some different variable like "os" and "arch" also different chrome version but no it did not work... i will monitor chrome to see what link it's using...

**Comment by csmk** [comment]
I looked at the link you provided, and I ended up installing [Chrome extension source viewer](https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin), but it suffer from the same issues.

**Comment by csmk** [comment]
@Rob--W was kind enough to quick fix the ref. issue above, and update his documentation at https://stackoverflow.com/a/14099762

> _**(New in 2018)** `acceptformat=crx2,crx3` instructs the server to also respond with extensions in the [CRX3 format](https://github.com/Rob--W/crxviewer/issues/62) (instead of 204 No Content when the extension is not available as CRX2)._

**Comment by Eloston** [comment]
@csmk @Rob--W Thanks.
