### ISSUE TITLE
Google Secretly Logs Users Into Chrome Whenever They Log Into a Google Site

### ISSUE THREAD

**Issue by anchev** [Eloston/ungoogled-chromium#535]
Just saw this article and I thought I should share it:

https://tech.slashdot.org/story/18/09/24/1351251/google-secretly-logs-users-into-chrome-whenever-they-log-into-a-google-site

I suppose it is not the case with ungoogled-chromim but I wonder: if a user has locally saved login passwords for Google owned sites and visits such site - would that auto login the user? (i.e. would the clean-up which this project does have any effect)

**Comment by Eloston** [comment]
Sign-in functionality is disabled multiple ways via patches and domain substitution, so stored credentials shouldn't do anything to the browser itself. At most, it will affect webpage behavior if it sees it.

**Comment by anchev** [comment]
> At most, it will affect webpage behavior if it sees it.

That's what I was wondering: would the user be auto signed in the particular G owned site if there are stored credentials for that site. I suppose it won't happen since you have replaced all domain names and any check like "if (user is on site X) { login(); }" would fail. I haven't tested though.

**Comment by Eloston** [comment]
It seems the `chrome://flags//#account-consistency` is a flag that is tied into Sync, the mechanism in discussion. This flag could be a lead to understanding how Sync's inner workings, but that should be left for #520.

**Comment by anchev** [comment]
I see.

BTW: I see many flags which are set to "Default" but there is no indication what that default actually is. How do we know that?

**Comment by Eloston** [comment]
> BTW: I see many flags which are set to "Default" but there is no indication what that default actually is. How do we know that?

I think it's specified in `chrome/browser/about_flags.cc`.
