### ISSUE TITLE
Please disable auto-resetting of settings when migrating profiles

### ISSUE THREAD

**Issue by mehrdadn** [Eloston/ungoogled-chromium#538]
Hi there,

Chromium deliberately resets its profile when it detects an 'unauthorized' change to a profile, such as the migration of the profile to a different account, browser version, volume, etc. -- even when there would be no actual problem in doing so.

This makes it very difficult and painful to migrate to ungoogled-chromium. I was wondering if you might be able to disable the code that is responsible for doing so? I'm not entirely sure which part of the code is responsible for this, but I suspect it may be the `PrefHashStoreImpl::PrefHashStoreTransactionImpl::CheckValue` function inside `src/services/preferences/tracked/pref_hash_store_impl.cc`. Forcing it to always return `PrefHashCalculator::VALID` could potentially do the job.

(If this isn't desirable behavior by default, it would be great if it could be at least made an available option for users.)

Thank you!

**Comment by pellaeon** [comment]
Hi @mehrdadn , I'm trying to get this working, have you figured out a way to get this working? [My patch](https://gist.github.com/pellaeon/3ce99374507c6495dad5fd94da2bf624) according to your hints doesn't work. (I copied the entire content of profile folder from Chrome and the patched chromium deleted the copied extensions upon startup)

**Comment by mehrdadn** [comment]
Hi @pellaeon, yup I got it working. I just changed the last line of `PrefHashCalculator::Validate()` (in `services/preferences/tracked/pref_hash_calculator.cc`) from `return INVALID` to `return /*IN*/VALID`.

BTW, another helpful thing I did (completely unrelated to this issue, but maybe something else you'd also like to consider) is to avoid blocking extensions that aren't on the web store. You can do that by changing `return false` to `return true` in `ExtensionManagement::IsInstallationExplicitlyAllowed()` (`chrome/browser/extensions/extension_management.cc`).

**Comment by pellaeon** [comment]
Cool! Just built it and it works! Thanks!

**Comment by mehrdadn** [comment]
Yup!
