### ISSUE TITLE
Add Debian ARM CPU support

### ISSUE THREAD

**Issue by lwis** [Eloston/ungoogled-chromium#54]
Is this on the roadmap?

**Comment by Eloston** [comment]
No, this is the first time it's been suggested. What platform would you want an ARM build for?

**Comment by lwis** [comment]
@Eloston Raspberry Pi 3, if at all possible!

**Comment by Eloston** [comment]
Are you talking about a Debian arm64 or or armhf build? Or are you looking for a generic Linux ARM build?

**Comment by lwis** [comment]
Debian arm64 or armhf build would be brilliant!

**Comment by Eloston** [comment]
Alright. I don't have any experience with cross-compilation, so it'll have to be seen how this can be done.

**Comment by Eloston** [comment]
It might be possible to make arm64 and armhf builds with the current code, using the compilation methods that the package maintainers of `chromium` in Debian use. I don't know if this includes cross-compilation or not.

**Comment by TimestaticYT** [comment]
Currently on Asahi Linux and disappointed to see it not working
