### ISSUE TITLE
Strange url on extension page and unable to install extension from store

### ISSUE THREAD

**Issue by yuif37** [Eloston/ungoogled-chromium#545]
### Problem description

I found a pretty strange url on extension page. This link is unable to access. 
Meanwhile, I cannot install extensions from Chrome extension store.
(by the way, I install the chromium through brew cask)
<img width="427" alt="screen shot 2018-10-02 at 23 04 06" src="https://user-images.githubusercontent.com/3508411/46387973-92335880-c697-11e8-94aa-d9803117b722.png">

**Comment by csmk** [comment]
> _I found a pretty strange url on extension page.
> ...
> I cannot install extensions from Chrome extension store._

Please see https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq
