### ISSUE TITLE
ld.lld: error: undefined symbol: PR_ParseTimeString

### ISSUE THREAD

**Issue by perfect7gentleman** [Eloston/ungoogled-chromium#549]
```
[357/16250] python "../../build/toolchain/gcc_link_wrapper.py" --output="./top_domain_generator" -- clang++ -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -rdynamic -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,-O2 -Wl,--as-needed -Wl,--strip-debug -flto=thin -Wl,--thinlto-jobs=9 -fuse-ld=lld -o "./top_domain_generator" -Wl,--start-group @"./top_domain_generator.rsp"  -Wl,--end-group   -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -levent 
FAILED: top_domain_generator 
python "../../build/toolchain/gcc_link_wrapper.py" --output="./top_domain_generator" -- clang++ -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -rdynamic -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,-O2 -Wl,--as-needed -Wl,--strip-debug -flto=thin -Wl,--thinlto-jobs=9 -fuse-ld=lld -o "./top_domain_generator" -Wl,--start-group @"./top_domain_generator.rsp"  -Wl,--end-group   -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -levent 
ld.lld: error: undefined symbol: PR_ParseTimeString
>>> referenced by time.cc
>>>               base/time.o:(base::Time::FromStringInternal(char const*, bool, base::Time*)) in archive obj/base/libbase.a
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```
don't remember having this problem with Clang-6. Is it Clang-7 bug or just my problem?

**Comment by Eloston** [comment]
As it was asked in the issue template, what is your platform and configuration?

**Comment by perfect7gentleman** [comment]
Template - Archlinux
[ebuild   R    ] www-client/chromium-69.0.3497.100::pg_overlay  USE="cups custom-cflags (pic) proprietary-codecs pulseaudio suid system-ffmpeg system-icu system-libvpx tcmalloc vaapi -component-build -gnome-keyring -hangouts -jumbo-build -kerberos (-neon) (-selinux) -thin-lto -widevine" L10N="ru -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_7" 0 KiB

**Comment by intika** [comment]
We need more details about your config 

- What's your version of those application
-- lld
-- gcc 

- The output of uname -a 

- What version are you trying to build

- If possible indicate what steps are you doing

**Comment by perfect7gentleman** [comment]
bug is irrelevant as I took ebuild from chaos-overlay and it builds fine.
there was one bug https://gitlab.com/chaoslab/chaoslab-overlay/issues/47
```
x86_64-pc-linux-gnu-clang++: error: no such file or directory: '/usr/lib/llvm/7/bin/../../../../lib/clang/7.0.0/share/cfi_blacklist.txt'
```
solved with
EXTRA_GN="clang_use_default_sample_profile=false is_cfi=false"
