### ISSUE TITLE
thread_helpers.o ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Aquarian-Age** [Eloston/ungoogled-chromium#550]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: [openSUSE15.0]
 - ungoogled-chromium version: [69.0.3497.100]
 - If this is a custom build, please specify the following:
    - Configuration bundle: [ linux]
    - Packaging type: [linux_]
    - OS and version for building: [openSUSE15.0]
    - Compiler toolchain: [llvm-config --version6.0.1  gcc version 7.3.1, clang --version
clang version 6.0.1]

**[2860/20013] clang++ -MMD -MF obj/sandbox/linux/sandbox_services/thread_helpers.o.d -DSANDBOX_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -I../.. -Igen -fprofile-sample-use=../../chrome/android/profiles/afdo.prof -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -flto=thin -fwhole-program-vtables -m64 -march=x86-64 -Wall -Wextra -Wimplicit-fallthrough -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-address-of-packed-member -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -Wno-enum-compare-switch -Oz -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/blacklist.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem../../../../../../../usr/include/glib-2.0 -isystem../../../../../../../usr/lib64/glib-2.0/include -std=gnu++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../sandbox/linux/services/thread_helpers.cc -o obj/sandbox/linux/sandbox_services/thread_helpers.o
ninja: build stopped: subcommand failed.**

**Comment by Eloston** [comment]
* Please correct the configuration bundle and packaging types.
* Since you're compiling, you can use the development issue template.
* Please post more output of the error. Only the invocation command and the status message are in your snippet.

**Comment by Aquarian-Age** [comment]
@Eloston @intika  

Thanks Reply
I modified the compile option of the spec file to
Ninja -v -j2 -C out/Default chrome chrome_sandbox chromedriver
appear
Error: --thinlto-cache-policy: invalid cache policy: Unknown key: cache_size_files'

Reference: https://clang.llvm.org/docs/ThinLTO.html
Then modified BUILD/ungoogled-chromium-9.0.3497.100/build/config/compiler/BUILD.gn
Cache_policy =
          "cache_size=75%: cache_size_bytes=70g"

The problem is solved. Continue to compile.
FAILED: chrome_sandbox
Error: Invalid summary version 4, 1, 2 or 3 expected

The following is the error message
Done. Made 9329 targets from 1628 files in 8550ms
+ ninja -v -j2 -C out/Default chrome chrome_sandbox chromedriver
Ninja: Entering directory `out/Default'
[1/16703] python "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome_sandbox" -- clang++ -pie -Wl,--build-id=sha1 -fPIC -Wl, -z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -fuse-ld=lld -Wl,--icf=all - Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=2 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=75\ %:cache_size_bytes=75g -Wl,--lto-O0 -fwhole-program-vtables -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-rpath-link=. -Wl,-- Disable-new-dtags -o "./chrome_sandbox" -Wl,--start-group @"./chrome_sandbox.rsp" -Wl,--end-group -latomic -ldl -lpthread -lrt
FAILED: chrome_sandbox
Python "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome_sandbox" -- clang++ -pie -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack - Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color -diagnostics -flto=thin -Wl,--thinlto-jobs=2 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=75\%:cache_size_bytes=75g -Wl,--lto-O0 -fwhole-program-vtables -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-rpath-link=. -Wl,--disable-new-dtags -o "./chrome_sandbox" -Wl,--start-group @"./chrome_sandbox.rsp" -Wl,--end-group -latomic -ldl -lpthread -lrt
/usr/bin/ld.lld: error: Invalid summary version 4, 1, 2 or 3 expected
/usr/bin/ld.lld: error: Invalid summary version 4, 1, 2 or 3 expected
Clang-6.0.1: error: linker command failed with exit code 1 (use -v to see invocation)
[2/16703] python ../../tools/licenses.py --target-os=linux --depfile gen/components/resources/about_credits.d credits gen/components/resources/about_credits.html
Ninja: build stopped: subcommand failed.

The gongle search did not see the corresponding instructions. I don’t know what the value is. I can’t succeed after trying it.

My build environment is:
I am using openSUSE15.0
Clang --version
Clang version 6.0.1 (tags/RELEASE_601/final 335528)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Gcc --version
Gcc (SUSE Linux) 7.3.1 20180323 [gcc-7-branch revision 258812]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
Warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Llvm-config --version
6.0.1

**Comment by Eloston** [comment]
Please specify the configuration bundle and packaging type you are using, **or** the building steps you are taking.

If you are using `linux_portable` config bundle, you need to upgrade to at least LLVM 7 or 8 as stated in the build instructions.
