### ISSUE TITLE
Portable Linux is not statically-linked

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#556]
(This issue was reported by @tavlima in https://github.com/Eloston/ungoogled-chromium/issues/554#issuecomment-429896554)

`linux_portable` config bundle is supposed to be statically-linked, but that seems to not be the case.

If it is not feasible to make Chromium statically-linked, then we need to re-evaluate what exactly `linux_portable` should be (and thus how to build and use it).

Output from https://github.com/Eloston/ungoogled-chromium/issues/554#issuecomment-429896554:
```
# Looking into ungoogled-chromium_67.0.3396.87-1_linux.tar.gz ...
$ ldd chrome | grep "not found"
libatk-bridge-2.0.so.0 => not found
libgtk-3.so.0 => not found
libgdk-3.so.0 => not found
```

**Comment by intika** [comment]
What about including those library on the appimage ?

**Comment by Eloston** [comment]
My knowledge of this area of Chrome/Chromium is limited. Here are several questions I have:

* What are the shared library dependencies for Chrome? How about an official build of Chromium (with optimizations and `is_official_build=true` enabled like Chrome)?
* How are these dependencies being used?
* If there is no strong justification to use the shared library, how feasible is it to remove the dependency? What are the consequences of removing the dependency? What kind of issues can arise if the libraries are statically-linked instead?
* How does the use of shared libraries change over time? Is there a general policy or guideline for what Google does in regards to shared libraries?

In general, I just want to understand the whole situation regarding shared libraries in Chromium. If anyone could enlighten us, that would be much appreciated.

**Comment by Eloston** [comment]
After contemplating about this a bit more, I'm not really inclined to work on this (because I have no personal need) unless someone is willing to push for this. Additionally, it seems Google doesn't have fully statically linked libraries, which is why they [use a sysroot by default](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_sysroot.md).

For `linux_portable` bundle, I think it's best to disable shared library dependencies on a best-effort basis via GN flags and/or small patches. Each shared library should be considered individually (unless they are related in some manner), where we would need to consider

* the stability/compatibility of the ABI.
* features in Chromium dependent on the shared library.
* any maintenance work involved with patches we would need to add.

If anyone wants to request the removal of a shared library dependency, please do so in a new issue. Also, specify any knowledge you have of the above three considerations.

Finally, if anyone wants to work on static linking support, let us know here and this issue can be re-opened. I believe it should be done in new config bundle, like `linux_static`. `linux_portable` should maintain close compatibility with the Chromium "official" builds.

**Comment by jlj2** [comment]
> Thoughts?

Portable Linux builds by @intika are very valuable to me.  They are the ones being used by at least myself a considerable amount of time.

Gentoo overlays are not attractive as an alternative.

**Comment by Eloston** [comment]
@jlj2 I see. In that case, taking the route of creating and using sysroots may be the most reasonable here.

**Comment by intika** [comment]
i was a little busy with [Librefox](https://github.com/intika/Librefox) i will see what i can do ;)

**Comment by intika** [comment]
i am building portable with sysroots right now... the build script needs some adjustment... i will PR if everything went ok

**Comment by intika** [comment]
Done https://github.com/Eloston/ungoogled-chromium/pull/649/

**Comment by bill-mcgonigle** [comment]
If we can get to a statically linked output that will have value to people working on projects like kiosks where simple remote updates are really valuable.  They have the challenge of keeping their geographically diverse fleet of machines running securely without breakage from OS updates, etc.  The ability to run chromium-compatible platforms without Google code fiddling around inside their machines and a stable static binary would probably make some of these admins /very/ happy.  I might have an upcoming project that could use such a thing, and could help if that pans out.

**Comment by intika** [comment]
this is not a real issue, the problem we are facing is that sysroot is pre compiled (binary) we would need to maintain that as well if we want to build it from sources.

**Comment by intika** [comment]
sysroot is a little more complicated to be added while respecting this project rules... i added a full review about it here https://github.com/Eloston/ungoogled-chromium/pull/649... so wait and see what we decide...

**Comment by Eloston** [comment]
I don't think we need to worry about this since we have more packaging methods available now like AppImage and more distro support.
