### ISSUE TITLE
[User discussion] Linux and Ungoogled Chromium

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#559]
I see more people switching from Windows to Linux over the time with this constantly privacy issues...

I would like to open a topic and bring the question, what version of Linux the users of ungoogled chromium are using?

**Comment by jlj2** [comment]
Hi @ribatamu!

Using Calculate Linux, based on Gentoo.  Unlike Gentoo itself, the desktop environment is set up for you from the start, but still it might pose some challenges to newcomers to GNU/Linux.  For example, some might not realize that the `/etc/sudoers` file doesn't have the `# %wheel     ALL=(ALL)      ALL` line uncommented, and that `visudo` at a root prompt would be a way to change that, which would be an added challenge to newcomers.  Nevertheless, the base of Calculate Linux, Gentoo, gets considerable attention in some aspects.

Linux Lite takes you 'by the hand' in some respects and in my experience may be a good introductory system for newcomers to GNU/Linux.  It uses systemd, which is ubiquitous with many Linux installations but has its detractors.  

Moving to Linux is a good idea.  

Hopefully that helps.

**Comment by Artur96** [comment]
Arch Linux, the most modular It Just Werks™ distribution that doesn't require compiling from source. You can check out [Distrochooser](https://distrochooser.de/en/) to see which distro is right for you

**Comment by kabo** [comment]
Open source is important to me, so I use Debian Buster, and don't enable contrib or non-free, I just stick to main.
