### ISSUE TITLE
Let's have a bot build the binaries

### ISSUE THREAD

**Issue by raizam** [Eloston/ungoogled-chromium#562]
**Is your feature request related to a problem? Please describe.**
Building chromium is a heavy task, prebuilt binaries should be the way to go, but binaries provided by *users* can't be trusted. 

**Describe the solution you'd like**
A build bot that pulls the sources from the repository, and provide binaries on a weekly basis

**Comment by intika** [comment]
Yes this is a good idea... (and this was already requested) 
1- Please post here If you know example of any service that could provide that 
2- PR are open to any modification that would make such a thing possible
3- This is a small free non profit project (i personally pay 1~2 euros to build every release on a google cloud server and publish it back here) but in the case of a server/bot dedicated to that we would need something else or the project would bring in some financial aspect...  
4- I think @Eloston is welcome to any solution if you have one

**Comment by raizam** [comment]
[Travis](https://travis-ci.com/) is free for open source projects.
Supports all major platforms, it's the usual way to go.
(never used it though)

**Comment by Eloston** [comment]
@intika @ian-moone Thanks for responding here.

I have re-opened #17 to discuss this further.
