### ISSUE TITLE
[fixed]no luck w/ running on Arch Linux

### ISSUE THREAD

**Issue by s1nceri7y** [Eloston/ungoogled-chromium#567]
### Description

There are no easy way to run these patches on Arch linux at all.
e.g. Crash on launching latest .AppImage with suggestion to update the latest linux kernel to use sandbox.
also, i have crash on building/compiling ungoogled-chromium w/ failing write files.
i saw that u have no responsibility for installing ungoogled-chromium-bin from aur,but anyway: crash when trying to launch fresh-installed ungoogled-chromium-bin 
(fish: “chromium” terminated by signal SIGSEGV (Address boundary error))

### Console output and logs

`s1nceri7y@s1nceri7y ~/Downloads> 
./ungoogled-chromium_69.0.3497.100-2_linux.AppImage 
[9540:9540:1024/214814.525529:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
/tmp/.mount_ungoogJhm06p/AppRun: line 4:  9540 Trace/breakpoint trap   (core dumped) "${HERE}"/opt/google/chrome/chrome --password-store=basic $@
s1nceri7y@s1nceri7y ~/Downloads> uname -a
Linux s1nceri7y 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
`
`chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/lower_bound1.fail.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/count.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/lower_bound3.fail.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/find.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/count1.fail.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/count_transparent.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/equal_range3.fail.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/equal_range1.fail.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/count0.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/find1.fail.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.ops/lower_bound.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/compare.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/index_rv_key.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/index_tuple.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/at.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/empty.fail.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/index_key.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/size.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/iterator.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/max_size.pass.cpp: Write failed
chromium-69.0.3497.100/buildtools/third_party/libc++/trunk/test/std/containers/associative/map/map.access/empty.pass.cpp: Write failed
^C
`
### Environment details

* ungoogled-chromium version: latest available from site and aur (69.0.3497.100-2)
* OS and version for building: Linux s1nceri7y 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
* Compiler toolchain: dunno. most probably i have latest version of gcc.

**Comment by s1nceri7y** [comment]
i enabled users namespaces, but no luck
`> sudo sysctl kernel.unprivileged_userns_clone=1
kernel.unprivileged_userns_clone = 1
> ./chrome-wrapper 
fish: “./chrome-wrapper” terminated by signal SIGSEGV (Address boundary error)
> bash
[s1nceri7y@s1nceri7y ungoogled-chromium_69.0.3497.100-2_linux]$ ./chrome-wrapper 
Segmentation fault (core dumped)
`

**Comment by s1nceri7y** [comment]
after trying to launch from root w/ --no-sandbox option( which was failed too) and reassigment the unprivileged userns clone variable, i have another error (w/ delaying on ~0.5 sec before printing "Segmentation fault":
`[s1nceri7y@s1nceri7y ungoogled-chromium_69.0.3497.100-2_linux]$ ./chrome-wrapper 
[5145:5205:1025/184834.633308:ERROR:data_store_impl.cc(131)] Failed to open Data Reduction Proxy DB: 3
Segmentation fault (core dumped)
[s1nceri7y@s1nceri7y ungoogled-chromium_69.0.3497.100-2_linux]$ 
`

**Comment by Eloston** [comment]
@s1nceri7y In the first post, you were using an AppImage. Are you now using the Portable Linux build? What happens if you try the AppImage again?

**Comment by s1nceri7y** [comment]
at the beggining i was looking for easy ways, but then i downloaded portable build.
here's what i have for now  when trying to launch an appimage build
`s1nceri7y@s1nceri7y ~/Downloads> 
./ungoogled-chromium_69.0.3497.100-2_linux\(1\).AppImage 
[7203:7219:1025/190231.321316:ERROR:data_store_impl.cc(131)] Failed to open Data Reduction Proxy DB: 3
/tmp/.mount_ungoog2VYYdS/AppRun: line 4:  7203 Segmentation fault      (core dumped) "${HERE}"/opt/google/chrome/chrome --password-store=basic $@
s1nceri7y@s1nceri7y ~/Downloads> 
`

**Comment by intika** [comment]
Same error with both builds... stick with the portable version to debugging... 

1. Do you have the same issue with chromium ? 
2. Do you have same issue with v67 portable ?
3. How did you disable namespaces in the first place 
4. Are you using a custom kernel ? what's the output of "uname -a" ?
5. Try to run it with a different user or with a new profile

**Comment by s1nceri7y** [comment]
1. Only one of them, but i still able to run it.
2. I'm a little bit busy. i'll try later
3. They are disabled on Arch Linux by default.
4. I'm using original kernel (i mentioned my kernel in Enviroment info)
`Linux s1nceri7y 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
s1nceri7y@s1nceri7y ~> 
5. I'll try later, but i just noticed i haven't removed my profile from Chromium before uninstalling (i was logged in google account). i'll remove it and try.
Thanks for helping me!

**Comment by s1nceri7y** [comment]
yes, that was a deal: i wasn't able to launch ungoogled-chromium cause of remaining google acount i hadn't log out and disabled namespaces by default.
thanks.
i think it's a good idea to add removing existing cookies and etc before installing ungoogled-chromium

**Comment by intika** [comment]
Cool :) i am glad that helped, can you close the issue please

**Comment by Eloston** [comment]
Opened #568 to discuss crashing due to existing Google account.
