### ISSUE TITLE
Crash on startup with user data directory having an associated Google account

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#568]
Originated from https://github.com/Eloston/ungoogled-chromium/issues/567#issuecomment-433194097. The browser unconditionally crashed on startup when the Google account was still tied to the user data directory.

Ideally, the browser shouldn't crash and just ignore the Google account. The user would then have the freedom to launch regular Chromium and still have the Google account. However, I don't mind if the solution must strip the Google account to preserve settings from the profile.

**Comment by s1nceri7y** [comment]
i should mention that i logged in in chromium 70.
after cleaning cache, cookies and everything but boomarks, everything become right

**Comment by Eloston** [comment]
> UC will become very different in internals from chromium overtime...

Could you elaborate? What factors are contributing to this?

**Comment by intika** [comment]
@Eloston for me personally uc is a full replacement of chromium so it does not matter, but here is why it could be useful 

- First i think most classic users are considering uc as a complete different browser (even if technically its a patched chromium)
- What meant is the more features that come in the more the browser will be different from chromium... and uc is likely to be having growing features 

**In the case where both browser are used and or migration from chromium to uc :** 
- Flags : some flags are present here but not there and it could potentially lead to crash/loosing-settings i don't know exactly how chromium deal with unknown flags but it could be a source of problem 
- Out of the box experience (An old profile could lead to problems like https://github.com/Eloston/ungoogled-chromium/issues/567)
- Version mismatch : chromium does not like when a profile is used with a previous version and even show an error when we do so... (in case chromium/uc version mismatch)
- We could have a lot of arguments in each side but at the end of the day uc is not chromium 

Any way just developing what i was talking about... but for me its not something that i would put a lot of effort/energy in... nor bothering making the change... in the other hand the bug have to be fixed so...

**Comment by Eloston** [comment]
@intika 

> Flags : some flags are present here but not there and it could potentially lead to crash/loosing-settings i don't know exactly how chromium deal with unknown flags but it could be a source of problem

I believe `chrome://flags` come and go all the time, so unknown flags may be dropped.

> We could have a lot of arguments in each side but at the end of the day uc is not chromium

Sure, but trying to separate from Chromium violates the drop-in replacement goal of ungoogled-chromium.

If bi-directional compatibility with Chromium is not possible at some point in the future, I'd still like to support importing Chromium profiles.

**Comment by intika** [comment]
so may be cleaning the profile on first run as @s1nceri7y mentioned... but some users may not like being disconnected...

**Comment by Eloston** [comment]
If this can't be fixed practically with a code change, I would at least like some utility to strip out the Google account so ungoogled-chromium can read the profile data.

**Comment by renatolond** [comment]
Hi!
I'd like to leave a note that it seems to kinda work by logging out the profile and then removing "site settings", "passwords and other sign-in data", "autofill  form data" and "hosted app data". It allows ungoogled chromium to start without crashing (I did a backup of my profile folder and experimented removing some stuff to see where it would start working)

I say kinda work because even though ungoogled chromium starts, I'm still experimenting ocasional core dumps (It consistently happens when a website I'm logged asks for permission to send me notifications)

**Comment by Eloston** [comment]
Might be related: #631

**Comment by Eloston** [comment]
This should be solved with 6cc874cfc8a250224811584f2c293dc61ec4faeb.
