### ISSUE TITLE
Add "Open Developer Tools on page open" option

### ISSUE THREAD

**Issue by ezhokhova** [Eloston/ungoogled-chromium#57]
I use Chromium for web development and I need to open Developer Tools every time. Is it possible to make it automatically? Thank you

**Comment by Eloston** [comment]
It maybe possible to do this automatically, but I'm not sure how. Does pressing F12 not work for you?

**Comment by Dequim** [comment]
Ctrl+Shift+i 
works here

**Comment by Eloston** [comment]
Closing this since there seems to be no problems with the suggested solutions.
