### ISSUE TITLE
"remember me" / Remain Signed in functionality?

### ISSUE THREAD

**Issue by brianegan** [Eloston/ungoogled-chromium#575]
Hey hey -- really liking this browser, thanks for all your hard work :)

One question: I notice that after I restart the browser, I need to sign back in to all of my accounts. I use Two-factor auth a lot, which becomes pretty cumbersome (I tend to hop back and forth between OSX and Windows once or twice a day). It'd be great if the browser could "Remember me" if I choose to, and keep me logged in after a restart.

Is there a way to make this work?

**Comment by brianegan** [comment]
Wait! I found it. For those who are curious: You need to open the Settings and uncheck "Keep local data only until you quit your browser."

**Comment by intika** [comment]
yes its just about cookies

**Comment by milahu** [comment]
> You need to open the Settings and uncheck "Keep local data only until you quit your browser."

in chromium v79 it is

1. settings
2. site settings
3. cookies and site data
4. Clear cookies and site data when you quit Chromium

the last label is not searchable from the settings menu
i would call that a bug
