### ISSUE TITLE
Media previews on Google Drive don't work

### ISSUE THREAD

**Issue by FriendlyAI** [Eloston/ungoogled-chromium#576]
## Description
Audio (mp3, flac) media previews don't work on Google Drive. Not sure if this is intentional or not or if there's a workaround. Right clicking an audio file and choosing the `Preview` option gives a `Whoops! There was a problem playing this audio file.` error.

## Build
- Ungoogled-Chromium | 69.0.3497.100-1 (64-bit)
- Revision | 8920e690dd011895672947112477d10d5c8afb09-refs/branch-heads/3497@{#948}
OS | Mac OS X
- JavaScript | V8 6.9.427.23
- Flash | (Disabled)
- User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by Eloston** [comment]
Do they work in regular Chromium or Chrome?

**Comment by intika** [comment]
Also can you try v70

**Comment by FriendlyAI** [comment]
Previews work in both regular Chrome and in Vivaldi. Tried v70, but the issue persists. Previews for other file types work, however, including mp4's.

**Comment by Eloston** [comment]
We need more details to determine what is going on. Are there any errors in the DevTools console?

**Comment by FriendlyAI** [comment]
With some more testing, it looks like the previews are only broken when you are signed into an account and works when not signed in. 

Comparing the DevTools log from Chromium and a working Chrome, there is a failed media download from `https://doc-0k-2k-docs.googleusercontent.com/docs/securesc/...` initiated by `nonceSigner` with error `(failed) net::ERR_TOO_MANY_REDIRECTS` in Chromium but not in Chrome. 

There are a lot of requests to `https://docs.google.com/nonceSigner?nonce=...`, then to the `doc-0k-2k-docs.googleusercontent.com` url, then back and forth, creating a redirect loop and eventually failing.

**Comment by Eloston** [comment]
Does the behavior change if you change your user agent to a non-Chrome/Chromium one? e.g. Firefox

**Comment by FriendlyAI** [comment]
Nope. Same problem when on Firefox and Safari user agents.

**Comment by qvint** [comment]
I think the issue is not related to ungoogled-chromium. It seems Google Drive requires some third-party cookies. Adding `https://[*.]googleusercontent.com:443` to the cookie exceptions list (chrome://settings/content/cookies) resolves the issue. At least it did work for me. See [[1]](https://stackoverflow.com/questions/11602242/google-docs-redirect-301-error), [[2]](https://productforums.google.com/forum/?fromgroups=#!topic/drive/XgwZpN_0gz0).

**Comment by Eloston** [comment]
@qvint Thanks for the help.

@FriendlyAI If this doesn't resolve your issue, please let us know.

**Comment by FriendlyAI** [comment]
Worked, thank you.
