### ISSUE TITLE
Possibly switch from Windows x86 to x64

### ISSUE THREAD

**Issue by sHAsHiLx** [Eloston/ungoogled-chromium#58]
Yes it works under x86 and x64 but binaries only x86. Where is binaries for windows x64?

**Comment by Eloston** [comment]
I didn't realize that 64-bit Chromium was better than 32-bit. I'll consider deprecating the 32-bit build if no one uses them.

**Comment by Eloston** [comment]
I've decided to build both x86 and x64 binaries for now.
