### ISSUE TITLE
Question about how flags/features work (or not)

### ISSUE THREAD

**Issue by csagan5** [Eloston/ungoogled-chromium#580]
I have seen many times cases where upon my investigation on some flag, I conclude they are disabled by default, but then always have to disable them manually in `chrome://flags` to have them really disabled.

Two simple examples:

* `#passwords-keyboard-accessory`: https://cs.chromium.org/chromium/src/components/password_manager/core/common/password_manager_features.cc?type=cs&q=kPasswordsKeyboardAccessory&sq=package:chromium&g=0&l=55 (which causes this when enabled: https://imgur.com/a/YGTBwZA)
* `#enable-query-in-omnibox`: https://cs.chromium.org/chromium/src/components/omnibox/browser/omnibox_field_trial.cc?type=cs&sq=package:chromium&g=0&l=197 (also a flag specific to Android, although I have read in the code that there are plans to enable it on desktop some day)

@Eloston since I think you have more experience with flags and feature flags, could you please explain me why these (and similar) end up being actually enabled in the build and how you would disable them?

**Comment by Eloston** [comment]
Sorry for the late response; not sure if you have figured it out yet or not.

* `#passwords-keyboard-accessory`: Do you have `#experimental-ui` enabled? It looks like the passwords keyboard can be turned on when either flag is enabled:
    * https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/chrome/browser/password_manager/password_accessory_controller.cc#164
    * https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/chrome/android/java/src/org/chromium/chrome/browser/autofill/keyboard_accessory/ManualFillingMediator.java#414
* `#enable-query-in-omnibox`: The link you provided is to the wrong flag (`kUIExperimentMaxAutocompleteMatches`). Even after searching around with the correct flag, I'm not too sure why it is being enabled.

Alternatively, both flags are listed under `testing/variations/fieldtrial_testing_config.json` (in CamelCase). I believe this is a place where field trials are defined and set, so it may have been enabled randomly. You can disable fieldtrials with [a GN flag that is defined here](https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/build/config/features.gni#46). See [components/feature_engagement/README.md](https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/components/feature_engagement/README.md#adding-a-local-field-trial-testing-configuration) for more general info about field trials, and [testing/variations/README.md](https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/testing/variations/README.md) (also linked in the previous document) for the format of `fieldtrial_testing_config.json`.

I haven't looked at how you configured Bromite, nor do I know much about field trial tests, so I could be wrong. Let me know what you find.

**Comment by csagan5** [comment]
> Sorry for the late response; not sure if you have figured it out yet or not.

No worries, thanks for your reply. I have not figured it out yet.

> * `#passwords-keyboard-accessory`: Do you have `#experimental-ui` enabled?

They are both disabled by default according to the Chromium code.



> * `#enable-query-in-omnibox`: The link you provided is to the wrong flag (`kUIExperimentMaxAutocompleteMatches`). Even after searching around with the correct flag, I'm not too sure why it is being enabled.

Yes, the search results from that site are not pinned to a version. I am still puzzled as well about this one.



> Alternatively, both flags are listed under `testing/variations/fieldtrial_testing_config.json` (in CamelCase). I believe this is a place where field trials are defined and set, so it may have been enabled randomly. You can disable fieldtrials with [a GN flag that is defined here](https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/build/config/features.gni#46). See [components/feature_engagement/README.md](https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/components/feature_engagement/README.md#adding-a-local-field-trial-testing-configuration) for more general info about field trials, and [testing/variations/README.md](https://chromium.googlesource.com/chromium/src/+/70.0.3538.110/testing/variations/README.md) (also linked in the previous document) for the format of `fieldtrial_testing_config.json`.
> 

This is interesting, thanks for the pointers. I had read about this before but I was not aware of the role of that JSON file.

Would you say that the patch I use here https://github.com/bromite/bromite/blob/70.0.3538.95/patches/BRM071_Disable-fetching-of-all-field-trials.patch is ineffective to disable those?

> I haven't looked at how you configured Bromite, nor do I know much about field trial tests, so I could be wrong. Let me know what you find.

I use `is_official_build=true` but of course that does not set the branded flag, I will try a build with `fieldtrial_testing_like_official_build=true`, I think that might make the defaults I expect become effective.

I will report back, thanks again!

**Comment by Eloston** [comment]
> Would you say that the patch I use here https://github.com/bromite/bromite/blob/70.0.3538.95/patches/BRM071_Disable-fetching-of-all-field-trials.patch is ineffective to disable those?

That's a good question; I don't really know how this system works as a whole. If I have more time, I can look into it.

**Comment by csagan5** [comment]
I can confirm that `fieldtrial_testing_like_official_build=true` made the defaults in the code effective; thanks again!
