### ISSUE TITLE
Add flag to re-enable GCM (removed in https://github.com/Eloston/ungoogled-chromium/issues/7)

### ISSUE THREAD

**Issue by tvd9** [Eloston/ungoogled-chromium#581]
**Is your feature request related to a problem? Please describe.**

I'm using an extension called Join (https://chrome.google.com/webstore/detail/join/flejfacjooompmliegamfbpjjdlhokhj) to sync stuff between my phone and my computer. Join depends on some Google APIs/Services, such as Google Cloud Messaging, to function properly.

**Describe the solution you'd like**

I don't know if this is possible, but maybe add a chrome flag to re-enable it

**Describe alternatives you've considered**

I've thought about compiling from source, but unfortunately that's not feasible for me

**Additional context**

"GCM Issues" in Join's FAQ: https://joaoapps.com/join/faq/ (the first question), the solution provided there didn't help. Then I found this issue: https://github.com/Eloston/ungoogled-chromium/issues/7 (about removing GCM, etc.) and that's it.
I hope that there's a solution for this! :)

**Comment by saltama** [comment]
Instead of adding this back for everyone, adding an entry in the wiki on how to enable it back before compilation would be a better idea (albeit requiring some maintenance in future releases), in my opinion.
Was this working before #7? It was committed 2 years ago, hard to tell.

**Comment by tvd9** [comment]
All I know is that it was working with "stock" chromium. Also, I agree,  that this shouldn't be added for everyone.

**Comment by Eloston** [comment]
Adding this feature would go against the primary objective of this project. In addition, removing the patch for GCM isn't enough; we would need to modify domain substitution (which is risky, since other components may share some code).

If there exists an alternative implementation of GCM servers, then I'd allow an option to set the server to use for GCM.
