### ISSUE TITLE
args.gn doesnt contain default parameters.

### ISSUE THREAD

**Issue by nadavhury** [Eloston/ungoogled-chromium#583]
Platform Win 10 x64 - I7 32gb SSD drive - no indexing.
Version  : ungoogled-chromium-69.0.3497.100-2 

After running ungoogled_packaging\build.py, I get this error
K:\chrome69\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
ERROR at build arg file (use "gn args <out_dir>" to edit):2:1: Expecting assignment or function call.
clang_use_chrome_plugins
^-----------------------

When entering the file args.gn, in out\default, it's full of arguments with no definition, meaning no default values, for example,
clang_use_chrome_plugins
does not contain " = false" after it. 

Here are all the definitions as they apear,
blink_symbol_level
clang_use_chrome_plugins 
enable_ac3_eac3_audio_demuxing 
enable_google_now 
enable_hangout_services_extension 
enable_hevc_demuxing 
enable_iterator_debugging 
enable_mdns 
enable_mse_mpeg2ts_stream_parser
enable_nacl 
enable_nacl_nonsfi 
enable_one_click_signin 
enable_reading_list 
enable_remoting 
enable_reporting 
enable_service_discovery
enable_swiftshader
enable_widevine 
exclude_unwind_tables
fatal_linker_warnings 
ffmpeg_branding 
fieldtrial_testing_like_official_build 
google_api_key
google_default_client_id
google_default_client_secret
is_clang = false
is_debug
is_official_build
optimize_webui
proprietary_codecs
safe_browsing_mode 
symbol_level 
treat_warnings_as_errors
use_gnome_keyring 
use_jumbo_build
use_official_google_api_keys
use_ozone
use_sysroot
use_unofficial_version_number
chrome_pgo_phase
full_wpo_on_official
rtc_use_lto
target_cpu

At first, I have tried to remove all, left only those >
safe_browsing_mode = 0
symbol_level = 0
enable_nacl = true
enable_nacl_nonsfi = true

and I am receiving this error > 
ninja: error: '../../native_client/toolchain/win_x86/pnacl_newlib/bin/x86_64-nacl-objcopy.exe', needed by 'nacl_irt_x86_
64.nexe', missing and no known rule to make it

Tried running the code from vs 2017 developer console, no salvation.
If there is a place of all default values, it will be nice...

Please help

**Comment by Eloston** [comment]
The args.gn file is broken because I made a silly mistake.

However, Windows support is broken in other ways right now; see #475.
