### ISSUE TITLE
Cannot start the program after a successful build.

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#586]
### Description

Cannot start chrome after a successful build. Trying from console gives:
```
[~]: /opt/ungoogled-chromium/chrome
Illegal instruction (core dumped)
[~]: [6859:6859:1110/172120.926328:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Even deleting ~/.config/chromium` doesn't help.

### Environment details

* ungoogled-chromium version: 70.0.3538.77
* Configuration bundle: `linux_portable`
* OS and version for building: openSUSE Leap 15.0
* Compiler toolchain:

```
$ clang -v
clang version 8.0.0 (trunk 346584)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /<***>/llvm-build/bin
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

### Building and packaging steps

The same described in #447 which so far have worked fine (including for the same version of ungoogled-chromium).

### Additional info

I have been running this same version of UC till earlier today with zero issues. It was built several days ago. Today I decided to rebuild it because I saw that openssl got an update on the official openSUSE repos, so I thought it might be a good idea to rebuild chrome too. Unfortunately the new build cannot start at all (and sadly I deleted the old one, so now I have to use another browser).

**Comment by anchev** [comment]
Fortunately I found an older build (version `ungoogled-chromium_70.0.3538.67-1_linux.tar.xz` from 2018-10-25) which works. I tried running that one from console too and it also gives the `InitializeSandbox` error line but without the `Illegal instruction (core dumped)`.

**Comment by intika** [comment]
should we call the police because of the `Illegal instruction` ? hahahaha just kidding

**Comment by anchev** [comment]
It seems the culprit may be the LLVM version (which I also build from source code as usual). I found an older build on my machine:
```
clang -v
clang version 8.0.0 (trunk 346299)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /<***>/llvm-build/bin
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
and using it I rebuilt ungoogled-chromium and I ran `diff` to compare the `bad` build and the working one:
```
# diff -qr bad/ ungoogled-chromium/
Files bad/chrome and ungoogled-chromium/chrome differ
Files bad/chrome_sandbox and ungoogled-chromium/chrome_sandbox differ
Files bad/chromedriver and ungoogled-chromium/chromedriver differ
Files bad/libEGL.so and ungoogled-chromium/libEGL.so differ
Files bad/libGLESv2.so and ungoogled-chromium/libGLESv2.so differ
Files bad/v8_context_snapshot.bin and ungoogled-chromium/v8_context_snapshot.bin differ
```
Now I still get:
```
[23943:23943:1111/125039.974622:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
```
but UC works fine and there is no `Illegal instruction` message.

Unfortunately I have no idea how to report this to LLVM at all. So if anyone has - it seems that deserves attention as LLVM is essential to building UC.

**Comment by anchev** [comment]
*re-subscribing with new account

**Comment by Eloston** [comment]
`Illegal instruction` may arise because LLVM is compiling with an assembly instruction that your CPU doesn't support. I don't have a clue why LLVM would do this, though... it might have something to do with running development versions of LLVM.

I'm going to close this because it seems like a rare case due to an unstable compiler. We should stick either to stable versions or LLVM revisions that Google uses to compile; it will be difficult to support people otherwise.

**Comment by anchev** [comment]
> Illegal instruction may arise because LLVM is compiling with an assembly instruction that your CPU doesn't support.

I don't see why. I am building everything with `-march=native` and `-mtune=native` -- the way I have always done and which has always worked so far.

> We should stick either to stable versions or LLVM revisions that Google uses to compile

But the current stable version of LLVM is 7.0 ([released on 2018-09-19](https://lists.llvm.org/pipermail/llvm-announce/2018-September/000080.html)) and UC requires 8.0 to compile which as of this moment LLVM 8 is an "upcoming release" as per [their official page](https://llvm.org/docs/ReleaseNotes.html). I also remember [your words](https://github.com/Eloston/ungoogled-chromium/issues/447#issuecomment-422873787) about it:

> In addition, it seems likely that linux_portable actually requires at least LLVM 8;

**Comment by Eloston** [comment]
> I don't see why. I am building everything with -march=native and -mtune=native -- the way I have always done and which has always worked so far.

It's hard to say unless we get down to the specific changes that happened in trunk. I won't take much for granted for a complicated system (i.e. the LLVM toolchain, and any modern compiler for that matter) if I barely know how it works.

> I also remember your words about it:

Good catch. I forgot about this and confused myself with Debian. Maybe we could document the LLVM revision that works and/or Google uses?

**Comment by anchev** [comment]
> It's hard to say unless we get down to the specific changes that happened in trunk.

True. I already wrote in the LLVM user maling list but nobody has replied. I wish I knew how to properly report it as a bug but given the scarce info I wonder what to do.

> Maybe we could document the LLVM revision that works and/or Google uses?

Sounds good to me.
