### ISSUE TITLE
Facebook Push notification not working

### ISSUE THREAD

**Issue by aryanrajseo** [Eloston/ungoogled-chromium#589]
I am not able to turn On facebook Push Notification. The button is not working.

I am using Version 70.0.3538.77 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/34836534/48487336-ece9d380-e843-11e8-82e1-4ef206ffad12.png)

**Comment by aryanrajseo** [comment]
Hi,

I have already tried with Guest and new people profile in ungoogled chromium. I got the notification pop-up but it not activate from the facebook settings.

**Comment by Eloston** [comment]
I believe Push Notifications in Chrome/Chromium uses GCM (just like on Android), so it may be requiring code that has been disabled. Can anyone confirm?

**Comment by tvaleev** [comment]
Right! Push Notifications used GCM service for client notification.For example user get unique ID for future notifications.  In chrome/browser/push_messaging is located Push notifications implementation. Impossible to have client Push API notification without cloud services by Google (or Mozilla in case of Firefox browser).
By the way, currently they migrate to FCM.

**Comment by Eloston** [comment]
Alright, then I will close this as wontfix for now. The main concerns here are any privacy and security, especially if there is any proactive background communication with Google. If there is a way to implement Cloud Messaging while addressing these concerns, I'll be open to it.
