### ISSUE TITLE
[SOLVED] Portable Linux v70.0.3538.77-1 download points to v70.0.3538.110-1

### ISSUE THREAD

**Issue by jlj2** [Eloston/ungoogled-chromium#599]
**Describe the bug**
Clicking on [download link](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) for Portable Linux v70.0.3538.77-1 displays a [github page](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/70.0.3538.77-1) describing v70.0.3538.77-1 and its hash values, but the download link there points to a download page offering a [different version](https://www.opendesktop.org/p/1265177/), v70.0.3538.110-1, and its hash sums predictably fail.

**Expected behavior**
Up-to-date or matching version offered on original download link;  and hashes to succeed.

**Environment (please complete the following information):**
 - OS and version: Calculate Linux 18

**Comment by intika** [comment]
In the download page https://www.opendesktop.org/p/1265177/ 
Under `Files` tab you have "(7 archived)" when you click it it uncover all the previous versions... 
I am going to un-archive them

**Comment by intika** [comment]
Fixed... i un-archived them you don't need to click archived any more.
Can you please close the issue

**Comment by jlj2** [comment]
Excellent, thanks @intika.  I notice that the github page referred to above has also been updated to describe the latest version, v70.0.3538.110-1.  The hash sums match the ones for the tar.xz downloaded earlier for that version, so all matches up fine.  Thanks for all that, and for your willingness and dedication to compile and package these!  :)

**Comment by intika** [comment]
Oww that's too much kindness ^^ thanks you !

**Comment by jlj2** [comment]
@Eloston, thank you too for your attention, persistence and commits!
