### ISSUE TITLE
Release binaries for 48.0.2564.116

### ISSUE THREAD

**Issue by glitsj16** [Eloston/ungoogled-chromium#6]
First off, really appreciate your efforts to offer ungoogled-chromium to the public. I've been using the 48.0.2564.82 release offered here on Debian/Ubuntu for about a month now and am very happy with it, both performance-wise and especially on the security / privacy front. Noticing that there aren't any release binaries for 48.0.2564.116 (yet), I was just wondering if you plan on offering these in the future in the repo?

**Comment by Eloston** [comment]
I was holding off on releasing new binaries until I had time to fix #7, but that won't be in a while. I'll upload binaries for 48.0.2564.116 shortly.
