### ISSUE TITLE
Google, Mozilla working on letting web apps edit files despite warning it could be 'abused in terrible ways'

### ISSUE THREAD

**Issue by nchv** [Eloston/ungoogled-chromium#602]
Just seen and sharing it for future consideration:

https://www.techrepublic.com/article/google-mozilla-working-on-letting-web-apps-edit-files-despite-warning-it-could-be-abused-in-terrible/

A flag to block that (when the time comes) would be very welcome.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
