### ISSUE TITLE
Slow startup when launching in Debian Buster

### ISSUE THREAD

**Issue by taahamahdi** [Eloston/ungoogled-chromium#608]
**Describe the bug**
Launching UC via `chromium` in a terminal works, but it takes at least 3 seconds before the window actually shows up. I don't see any errors reported after issuing the command, and there aren't any issues with UC after startup.

*Update: Nevermind, I see the error `[21615:21615:1129/002153.242543:ERROR:vaapi_wrapper.cc(328)] vaInitialize failed: unknown libva error` when launching UC and no other Chromium windows are open.

I'm guessing there's some library incompatibility going on, but I'm not sure how to fix it.

**To Reproduce**
1. Start Ungoogled Chromium with no other browser tabs open. Wait.

**Expected behavior**
The window should show up in less than a second, as it does with a normal installation of Chromium. By contrast, clicking Ctrl+N opens a new window in UC instantly.

**Environment:**
 - OS and version: Debian Buster amd64
 - ungoogled-chromium version: ungoogled-chromium_70.0.3538.110-3 (though the bug has been present since I first started using version 70)
 - If this is a custom build, please specify the following:
    - Configuration bundle: debian_buster
    - Packaging type: debian_buster
    - OS and version for building: Debian Buster amd64
    - Compiler toolchain: clang version 7.0.0-6, gcc (Debian 8.2.0-9) 8.2.0

**Comment by taahamahdi** [comment]
After doing a bit of research, [this issue](https://github.com/saiarcot895/chromium-ubuntu-build/issues/26) seems somewhat related. Is the issue out of the scope of this project?

**Comment by Eloston** [comment]
So the 3 second waiting time issue is resolved now? Instead, does ungoogled-chromium not open because of the libva error?

**Comment by taahamahdi** [comment]
My bad, I was pointing out that there is actually an error message presented. The issue is still there, and ungoogled-chromium still opens, albeit with a delay.

**Comment by Eloston** [comment]
I'm not entirely sure what the delay may be, but I have set some flags in `/etc/chromium.d/default-flags` that may cause some slowdowns. You could try tweaking them to see if they change performance.

Regarding the libva issue, it may be because you just have `libva1` installed but not any of the runtimes (e.g. `libva-drm1`, `libva-egl`, `libva-glx`, etc). You can safely ignore this error if you don't need VA-API acceleration. I don't think it should have any performance impacts.

**Comment by taahamahdi** [comment]
Sorry for taking so long to respond. I tried commenting out the flags and there was no change in startup time. It might just be an issue with Buster itself.

**Comment by Eloston** [comment]
Do you have background processes enabled in regular Chromium? (i.e. "Continue running background apps when Chromium is closed" under `chrome://settings`)

**Comment by taahamahdi** [comment]
Yup! I have it enabled in both regular Chromium and ungoogled-chromium

**Comment by taahamahdi** [comment]
I tried running `` ./chromium --show-component-extension-options --disk-cache-dir=/tmp/ungoogled-chromium-disk-cache --disable-component-update --ignore-gpu-blacklist --no-default-browser-check --media-router=0 --enable-remote-extensions --load-extension=`ls -dm /usr/share/chromium/extensions/* 2>/dev/null | tr -d '\n'` `` in the folder `/usr/lib/chromium`, and ungoogled-chromium launches as fast as regular Chromium now, but I'm not sure why. I guess I can alias the command in the meantime, but if I'm using the same launch options, I wonder why it's faster than just entering `chromium`.

One thing to note is I no longer get the libva warning I was getting earlier, even after opening multiple windows at the same time with `./chromium [same as before]`. Are there any other flags I might be missing?

**Comment by Eloston** [comment]
`/usr/bin/chromium` is a shell script that eventually runs `/usr/lib/chromium`. This shell script is essentially the same script that is used in Debian's `chromium` package. Perhaps you could try Debian's `chromium` and see if it is slow for you as well?

**Comment by taahamahdi** [comment]
Just tested it, ungoogled-chromium is still noticeably slower than Debian's chromium package. By the way, which `.deb` packages should I be installing after manually building? The following packages are in my `ungoogled-chromium/build` folder:

```
ungoogled-chromium_70.0.3538.110-3~buster_amd64.deb
ungoogled-chromium-common_70.0.3538.110-3~buster_amd64.deb
ungoogled-chromium-driver_70.0.3538.110-3~buster_amd64.deb
ungoogled-chromium-l10n_70.0.3538.110-3~buster_all.deb
ungoogled-chromium-sandbox_70.0.3538.110-3~buster_amd64.deb
ungoogled-chromium-shell_70.0.3538.110-3~buster_amd64.deb
```

**Comment by Eloston** [comment]
@taahamahdi At the very least, you need `ungoogled-chromium` and `ungoogled-chromium-common`.

**Comment by taahamahdi** [comment]
Cool, just checking. I have the issue either way unfortunately.

**Comment by Eloston** [comment]
One thing I forgot to mention is that the disk cache in 71 and earlier lived in `/tmp` (due to `/etc/chromium.d/default-flags`). If you did something with `/tmp`, that may cause a slowdown. Version 72 onward do not have this change.

Let me know if this is still a problem for you.

**Comment by hjri** [comment]
For me chrome is slow to start because of all the `lsb_release` calls also calling `apt-cache`, three times in a row, taking about 15 seconds before chromium can even boot. Replacing them with random strings helped
