### ISSUE TITLE
debian_buster attribute.patch causes windows build failure

### ISSUE THREAD

**Issue by azdps** [Eloston/ungoogled-chromium#611]
### Description

Windows 10 ungoogled-chromium master branch build failure

The debian_buster [attribute.patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/debian_buster/warnings/attribute.patch) removes math.h and includes cmath. Unfortunately, removing math.h causes Windows build failure. If you look at [s1angle.h](https://chromium.googlesource.com/chromium/src.git/+/master/third_party/s2cellid/src/s2/s1angle.h) file it clearly indicates in the notes that math.h is required.

quote from the s1angle.h file:

> Needed on Windows to get |M_PI| from math.h.

 I'm sure there is a means to code this to avoid the build failure. I added math.h to s1angle.h directly under cmath and the Windows build works fine. Seems to be an issue on how Windows Visual Studio handles precompiled header options.

**Comment by waqas** [comment]
Can you please share Windows binaries if build succeeds? Thanks.

**Comment by azdps** [comment]
I have yet to have a successful Windows build. I'm working my way much closer though. When I do I will be sure to share it here.
