### ISSUE TITLE
Segmentation Fault for Cosmic 71.0.3578.98-2

### ISSUE THREAD

**Issue by arutr** [Eloston/ungoogled-chromium#612]
**Describe the bug**
Running UC from Contributor Binaries fails with an error thrown by `sandbox_linux.cc`, followed by a segmentation fault.

**Screenshots**
```
[8110:8110:1130/174113.071502:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
Segmentation fault (core dumped)
```

**Environment (please complete the following information):**
 - OS and version: Ubuntu 18.10 Cosmic
 - ungoogled-chromium version: 70.0.3538.110-3

**Comment by ian-moone** [comment]
> ...fails with an error thrown by `sandbox_linux.cc`, followed by a segmentation fault.

That error is unrelated to the segfault. If you search around, you will see that's a common error, with no clear solution. See https://github.com/Eloston/ungoogled-chromium/issues/519#issuecomment-425247527

**Comment by Eloston** [comment]
@arturkomoter Are you able to build from source on that machine?

**Comment by arturkomoter** [comment]
> @arturkomoter Are you able to build from source on that machine?

Yes, but the same problem occurs.

**Comment by Eloston** [comment]
I see. Could anyone else with Ubuntu 18.10 cosmic confirm or deny this?

**Comment by Eloston** [comment]
@arturkomoter Have you tried using a new user data directory?

**Comment by arturkomoter** [comment]
@Eloston like which one? I have built in my user home directory.

**Comment by Eloston** [comment]
@arturkomoter I mean a new Chromium user data directory, via `--user-data-dir`

**Comment by arturkomoter** [comment]
I've fallen back to 18.04, and the latest v71 works fine.

**Comment by Eloston** [comment]
Good to hear. Closing.

**Comment by zchlm** [comment]
I'm running into the same error on Ubuntu Cosmic. Using the Contributor Binary 71.0.3578.98-2. I'll attempt building from source.

**Comment by Eloston** [comment]
@zchlm Thanks for letting me know. Reopening.

**Comment by Eloston** [comment]
Version 72 is out. Please let us know if you still get the same issue.

**Comment by ratatouyee** [comment]
I also get the same issue, including with version 72.

**Comment by Eloston** [comment]
@ratatouyee Do you still get a segmentation fault if you let the browser create a new profile directory?

**Comment by ratatouyee** [comment]
That was it, I deleted .config/chromium and it worked. Thank you.

**Comment by Eloston** [comment]
For future reference, I'm guessing this is somewhat related to #631 in that some pre-existing settings in the profile directory are causing ungoogled-chromium to segfault. We can use that issue as a starting point to eliminate these kinds of bugs.
