### ISSUE TITLE
Channel IDs on Ungoogled Chromium

### ISSUE THREAD

**Issue by wiredrunner** [Eloston/ungoogled-chromium#615]
Since Google deprecated support for Token Binding recently Channel IDs amount to nothing more than unblockable cookies which can only be removed manually.  No API supports removing them selectively.

How does Ungoogled Chromium deal with these?  Vivaldi hides them but they are still being loaded.

Thanks

**Comment by Eloston** [comment]
I'm not familiar with them. Do you have any recommended readings?

**Comment by wiredrunner** [comment]
At the same time apparently chromium plans to deprecate them they are showing up from websites (on Chrome) I never even visit. pippio.com, superfastcdn.com breitbart.com and endless google properties all it says under cookies is Channel ID and the name of the website.  I could block all cookies and they still show up.  

https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/AjFQjBmaEQE

https://github.com/EFForg/privacybadger/issues/1135

https://bugs.chromium.org/p/chromium/issues/detail?id=467312#c23

https://bugs.chromium.org/p/chromium/issues/detail?id=875046

**Comment by wiredrunner** [comment]
If you look at the Channel ID they all say -

Domain 
*.*

Certificate Type
ecdsa_sign

Maybe they aren't really cookies?

**Comment by Eloston** [comment]
No problem. Thanks for letting me know anyway.
