### ISSUE TITLE
Build failure on Ubuntu 18.04, bootstrap option mismatch

### ISSUE THREAD

**Issue by yl3dy** [Eloston/ungoogled-chromium#617]
### Description

Build fails on Ubuntu 18.04 with an argument error when calling tools/gn/bootstrap/bootstrap.py. The same issue persists both with current master and with 70.0.3538.110-3 release.

### Console output and logs

```
...
make[1]: Entering directory '/home/yl3dy/ungoogled-chromium/build/src'
mkdir -p out/Release || true
cp base/numerics/safe_conversions_arm_impl.h base/numerics/safe_math_arm_impl.h tools/gn/base/numerics
./tools/gn/bootstrap/bootstrap.py -o out/Release/gn -j8
Usage: bootstrap.py [options]

bootstrap.py: error: no such option: -j
debian/rules:78: recipe for target 'out/Release/gn' failed
make[1]: *** [out/Release/gn] Error 2
make[1]: Leaving directory '/home/yl3dy/ungoogled-chromium/build/src'
debian/rules:75: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

### Environment details

* ungoogled-chromium version: 70.0.3538.110-3
* Configuration bundle: ubuntu_bionic
* Packaging type (if applicable): [e.g. `linux_simple`, `debian_stretch`, `macos`]
* OS and version for building: Ubuntu Bionic 18.04 amd64
* Compiler toolchain: LLVM 7.0.1 from apt.llvm.org

### Building and packaging steps

Standard build instructions for a local package.

**Comment by Eloston** [comment]
Do you have the text file `build/src/debian/patches/series`? Does it have any content?

**Comment by yl3dy** [comment]
Yes, it does: https://pastebin.com/ympcgrcC

**Comment by Eloston** [comment]
That's strange. The `-j` flag is added through `parallel.patch`, which is listed in the `series` file you gave me. The fact that you do not have the `-j` flag in your `bootstrap.py` means that something went wrong when applying patches; The patches *should* have been applied when you invoked the `dpkg-buildpackage` command.

In the output from `dpkg-buildpackage`, did you see output about applying patches for each entry in `build/src/debian/patches/series`?

**Comment by yl3dy** [comment]
At last I think I figured out the root of the problem: leftover hidden files in `build/src`. Looks like these somehow prevented patches from applying. Now the version from master builds successfully.

Probably it should be added to the docs that `build/src` directory should be cleared before every building attempt.
