### ISSUE TITLE
Windows: BrowserMetrics consuming large amount of space

### ISSUE THREAD

**Issue by black-ish** [Eloston/ungoogled-chromium#624]
First of hello there,
I've been using this version of chromium for a few weeks now and noticed that my disk space got lower and lower when it shouldn't, turn out that Chromium keeps filling the folder "BrowserMetrics" with 8MB .pma files and I see no option anywhere to disable that. In that time the folder grew already to about 1,2GB for nothing.

If that could be disabled through a command line switch or a flag that would be very helpful.

Also since there are a great many switches for the "startup command line" it would be very useful to get an option added to settings (I know not recommended) a la CentBrowser (startup command options are stored in an .ini file which is called at startup), in Windows you only get so many characters to add to the "Target" field (I believe 255?) before you run out, which in Chromiums case is very fast.

I'm not a dev so I hope that is not too unreasonable to ask.

**Comment by black-ish** [comment]
Forgot to add that I currently use these command line switches:
"\Chrome.exe --user-data-dir=".\Profile" --disable-breakpad --disable-logging --disable-sync --disable-speech-api --disable-voice-input --disable-domain-reliability"
Also forgot to say thank you for this nice edition of Chromium, thank you very much.
I don't seem to be able to edit my other post for some reason, so sorry for double posting.

**Comment by Eloston** [comment]
@englishextra As much as I would like to make every user happy, I just don't have enough interest or the time to do so. Even if I had a Windows development environment ready to go, it's not insignificant to fix Windows support.

If you know people that could fix Windows support, that would be great.
