### ISSUE TITLE
Will this ungoogled-chromium fix the v71 tabs, v71 muting and v71 disabling flash?

### ISSUE THREAD

**Issue by mickrussom** [Eloston/ungoogled-chromium#630]
Will this ungoogled-chromium fix the v71 tabs, v71 muting and v71 disabling flash?

My main need to get off of google's v71 browser is flash is basically gone, muting is broke now and the new tab system is beyond broken.

Will ungoogled-chromium be a sanctuary against google's radical and terrible design changes?

**Comment by Eloston** [comment]
Sorry, but that goes against this project's goals (stated in the beginning of the README). If you want something like that, you should propose the idea to a browser that makes its own design choices, like Brave browser. If you don't need something exclusive to Chrome/Chromium, there's always Firefox and its derivatives.

However, I will accept toggles to enable such customizations. That is, if anyone is inclined to implement them.
