### ISSUE TITLE
Investigating Google-specific code adding entries to Preferences

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#631]
On startup, the browser will add the following unnecessary fields to the Preferences file of a profile (of a user data directory) in version 71 (the following are paths of JSON keys in UNIX path format) if they are missing:

```
google/services/signin_scoped_device_id
protection/macs/google/services/{account_id,last_account_id,last_username,username}
protection/macs/safebrowsing/incidents_sent
```

The code that reads/writes these entries should be disabled, as it may help prevent the browser from crashing (e.g. segfaults) when an unclean profile is used (e.g. one from Chrome). I don't know if there are more of such keys that should be disabled, nor do I know the code that is writing these values. Any feedback here will be appreciated.

On a tangential thought, it may help to have an automated process to tell us about such changes (maybe even static analysis of the C++ code to catch all such values, regardless of the conditions?), or at least have a script that can test this out. Anyone have thoughts on this?

**Comment by csagan5** [comment]
Related: #520

**Comment by lipici** [comment]
still no progress on windows version? @Eloston

**Comment by r4sas** [comment]
@lipici have you done anything for that progress?
For now, we stuck in part of removing SafeBrowsing.

Please, dont create off-topic messages anywhere.

**Comment by lipici** [comment]
im also stuck at the removing of SafeBrowsing.
