### ISSUE TITLE
Project Name?

### ISSUE THREAD

**Issue by v00v** [Eloston/ungoogled-chromium#642]
Can we have a new project name for this? "ungoogled-chromium" really? I mean who uses google anymore when using privacy browser like this? LOL This project deserves a new name :-) I used to use "Inox" for example, but its no longer updated.

**Comment by Eloston** [comment]
Do you have any suggestions?

**Comment by Eloston** [comment]
Thanks for the suggestions @intika. I will discuss my decision in #640.

Closing this issue as invalid because it's not constructive.

**Comment by v00v** [comment]
How about simply **Libre** (https://www.wordnik.com/words/libre)
_adj. With very few limitations on distribution or improvement; including source code._
