### ISSUE TITLE
[question] list of substituted domains

### ISSUE THREAD

**Issue by wokawoka** [Eloston/ungoogled-chromium#654]
Not really a program issue, but s there a way to get a list of all the google domains that has been replaced by the dummy ones (other than going manually through the code, I suppose)?
I believe that It would be very useful to many.
Thanks again for this great project

**Comment by Eloston** [comment]
In https://github.com/Eloston/ungoogled-chromium/blob/47c6164c3b2c4a84ff54d90893ab5b650e9838cb/docs/design.md#source-file-processors

> The regular expressions to use are listed in domain_regex.list; the search and replacement expressions are delimited with a pound (#) symbol.

So the file mentioned would be here: https://github.com/Eloston/ungoogled-chromium/blob/47c6164c3b2c4a84ff54d90893ab5b650e9838cb/config_bundles/common/domain_regex.list

(FYI, this will be moved to the root of the repository in the refactor).

**Comment by wokawoka** [comment]
Great, many thanks for the information and (please) keep up with the great work!
