### ISSUE TITLE
Getting a CERTIFICATE_VERIFY_FAILED in setup-local-src

### ISSUE THREAD

**Issue by arichiardi** [Eloston/ungoogled-chromium#655]
### Description

I am launching: `./debian/rules setup-local-src` and I get an exception: 

```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
debian/rules:181: recipe for target 'setup-local-src' failed
```

It seems like a problem upstream really.

### Environment details

* ungoogled-chromium version: 71.0.3578.98-
* Configuration bundle: `linux`
* Packaging type (if applicable): `ubuntu_bionic`
* OS and version for building: Ubuntu 18.04
* Compiler toolchain: LLVM 7

### Building and packaging steps

```
./get_package.py ubuntu_bionic build/src/debian
cd build/src
./debian/rules setup-local-src
```

**Comment by Eloston** [comment]
Are you using Python 3 provided from Ubuntu? If you're not, it's possible it's not accessing all the root certificates on your system.

**Comment by arichiardi** [comment]
Well yes I should be using. Will double check but I thought for a moment the cert was expired for real, would that be possible?

**Comment by Eloston** [comment]
Could be possible, not very likely. Google probably refreshes their certs before they expire.

**Comment by arichiardi** [comment]
It looks like I have just discovered that I need this for `wget` in my ubuntu:

     wget --ca-directory /etc/ssl/certs ...

Can it be a difference in openssl configuration for Ubuntu?

**Comment by Eloston** [comment]
That doesn't sound like a normal Ubuntu setup if `wget` doesn't find your SSL certs by default. You may want to try a clean install; perhaps a VM or container (e.g. LXD or Docker).

If you still have issues with a clean setup, let me know.

**Comment by arichiardi** [comment]
@Eloston you have been very hasty in closing this - my Ubuntu is vanilla.

I am trying now in a VirtualBox VM. In the meantime please have a look at this: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/31915123#31915123

It seems similar to my error and has to do with `urllib`.

**Comment by Eloston** [comment]
I don't see how the error is related. Your link is regarding Windows, not Linux.

Still, if `wget` isn't working with HTTPS out-of-the-box, something in your environment is not normal. I've never seen anything happen like this on Ubuntu.

**Comment by arichiardi** [comment]
It seems like the VM downloads correctly the package. Definitely something is odd on my end. Thanks for now.

**Comment by arichiardi** [comment]
For posterity, when you compile `openssl` yourself, make sure you set `--openssldirs=/etc/ssl` in case of Ubuntu so that you reuse your distro certificates. This now works for me.

Thanks @Eloston for you patience and guidance.
