### ISSUE TITLE
Up to date windows compilation

### ISSUE THREAD

**Issue by caspertone2003** [Eloston/ungoogled-chromium#657]
@Wyse-

Could you generate an updated version please?
https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/

**Comment by caspertone2003** [comment]
@leo-liar 
Thanks very much, precious resource that link you gave!
@Eloston 
Perhaps would be good to add compilation to https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/ 
Thanks again
CT

**Comment by Eloston** [comment]
I can't accept that binary because it re-enables the Safe Browsing component. That weakens the removal of Google service integration in ungoogled-chromium.

**Comment by Eloston** [comment]
Also, Windows support has not been fully fixed yet, which is why no new binary has been published.

**Comment by caspertone2003** [comment]
@Eloston 
Thanks for the explanation. Difficult topics to understand for a layman...
So I will wait.
CT
