### ISSUE TITLE
Provide official binaries for Windows?

### ISSUE THREAD

**Issue by neilpanchal** [Eloston/ungoogled-chromium#658]
I just discovered this project and love the idea of vanilla chromium sans Google. If the manifesto of the project is to spearhead privacy, not providing official tamper-free binaries (for Windows) is absolutely crucial and not doing so is a huge hole in the vision of this project. Is there a reason why this project relies on contributor binaries? Perhaps lack of resources? I am not familiar with the build process but I am happy to volunteer as much as I can and at least raise this issue - I am sure it has been considered in the past. Thank you for listening.

**Comment by leo-liar** [comment]
You can grab an up-to-date one frome [here][1], **but please take a look at #657 beforehand!**
- [ungoogled-chromium-71.0.3578.98-1_windows.7z][2]

[1]: https://chromium.woolyss.com/#win64-stable-ungoogled "Download latest stable Chromium binaries (64-bit and 32-bit)"
[2]: https://github.com/macchrome/winchrome/releases/download/v71.0.3578.98-r599034-Win64/ungoogled-chromium-71.0.3578.98-1_windows.7z "v71.0.3578.98-r599034-Win64"

**Comment by Eloston** [comment]
>  providing official tamper-free binaries (for Windows) is absolutely crucial
> [...]
> Is there a reason why this project relies on contributor binaries?

What would you constitute to be "official"? Being "official" requires there to be an authorative and trustworthy source, which no one person or party here can provide. Trust is hard to establish when everyone here is generally anonymous and unknown.

The closest we can get to "official" binaries is reproducible builds; i.e. having anyone be able to produce the same exact binaries from a given source. This almost already seems to be a reality on Linux (#632), but I don't know what the state of reproducibility is on Windows.

Until reproducibility becomes a reality, contributor binaries is a solution for those who can't build ungoogled-chromium themselves *and* they trust other volunteers enough. If security/privacy is a significant enough concern for you, then don't use contributor binaries.
