### ISSUE TITLE
build.py: error: Could not detect Python 2 version from output:

### ISSUE THREAD

**Issue by twolf35** [Eloston/ungoogled-chromium#661]
### Description

I am trying to run build.py and run into the above issue.

### Console output and logs

Python 3.6.6
usage: build.py [-h] [--downloads-cache PATH] [--disable-ssl-verification]
                [--7z-path SEVENZ_PATH]
build.py: error: Could not detect Python 2 version from output:

### Environment details

* ungoogled-chromium version: 71.0.3578.98-2
Windows

*(If relevant, add other environment details here)*

### Building and packaging steps

(Specify which instructions you used from `docs/building.md`. If you used custom build steps, please describe them here.)

**Comment by TCB13** [comment]
@twolf35 you might want to take a look at my step by step guide on how to install the dependencies here: https://github.com/Eloston/ungoogled-chromium/issues/675#issuecomment-464741452

**Comment by Eloston** [comment]
I'm going to close this as a duplicate so we don't have too many Windows issues sitting around. Once the fragmentation refactor is done, I'm going to move all of them to the Windows repo.
