### ISSUE TITLE
Cannot build due to unmet dependencies (LLVM ERROR)

### ISSUE THREAD

**Issue by TylerWolfDev** [Eloston/ungoogled-chromium#663]
I am trying to build on Ubuntu LTS. I have done everything but need to install LLVM but get the following errors while attempting.

```
 clang-7 : Depends: libstdc++-4.9-dev but it is not installable
           Depends: libgcc-4.9-dev but it is not installable
           Depends: libobjc-4.9-dev but it is not installable
           Recommends: libomp-7-dev but it is not going to be installed

```

**Comment by Eloston** [comment]
I built bionic binaries for version 72, and you don't need to use apt.llvm.org to get LLVM 7. Please let me know if you still have issues.
