### ISSUE TITLE
/usr/bin/ld did not recognize --icf=all when building for ubuntu_bionic 72.0.3626.81

### ISSUE THREAD

**Issue by davidhuff2014** [Eloston/ungoogled-chromium#665]
Used the typical build process, when it died while running ninja. Remove the append from the BUILD.ng file and three short  named .py files which are not available after the compile completes. Sorry it was the last thing I did before going to bed. But the compile completed and I'm using it now. Thanks!

**Comment by psilocibin** [comment]
`
[175/175] LINK gn
FAILED: gn 
clang++-7 -Wl,--stats -Wl,--stats -O3 -fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-strip-all -Wl,--icf=all -Wl,--as-needed -o gn -Wl,--start-group tools/gn/gn_main.o base.a gn_lib.a -Wl,--end-group -ldl -lpthread -lnspr4 -levent
/usr/bin/ld: unrecognized option '--icf=all'
/usr/bin/ld: use the --help option for usage information
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./tools/gn/bootstrap/bootstrap.py", line 101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gn/bootstrap/bootstrap.py", line 84, in main
    ['ninja', '-C', gn_build_dir, 'gn', '-w', 'dupbuild=err', '-j'+str(options.jobs)])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/home/user/ungoogled-chromium/build/src/out/Release/gn_build', 'gn', '-w', 'dupbuild=err', '-j8']' returned non-zero exit status 1
make[1]: *** [debian/rules:80: out/Release/gn] Error 1
make[1]: Leaving directory '/home/user/ungoogled-chromium/build/src'
make: *** [debian/rules:75: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2`
ubuntu_cosmic
`clang-7 --version
clang version 7.0.0-3 (tags/RELEASE_700/final)
`

**Comment by davidhuff2014** [comment]
Unfortunately clang-8 gave the same initial response. But now, looking at it again it appears it is ld that is having the problem not clang?

`cp base/numerics/safe_conversions_arm_impl.h base/numerics/safe_math_arm_impl.h tools/gn/base/numerics
./tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles -j4 -o out/Release/gn
ninja: Entering directory `/tmp/src/ungoogled-chromium-master/build/src/out/Release/gn_build'
[175/175] LINK gn
FAILED: gn 
clang++-8 -Wl,--stats -Wl,--stats -O3 -fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-strip-all -Wl,--icf=all -Wl,--as-needed -o gn -Wl,--start-group tools/gn/gn_main.o base.a gn_lib.a -Wl,--end-group -ldl -lpthread -lnspr4 -levent
/usr/bin/ld: unrecognized option '--icf=all'
/usr/bin/ld: use the --help option for usage information
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./tools/gn/bootstrap/bootstrap.py", line 101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gn/bootstrap/bootstrap.py", line 84, in main
    ['ninja', '-C', gn_build_dir, 'gn', '-w', 'dupbuild=err', '-j'+str(options.jobs)])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/tmp/src/ungoogled-chromium-master/build/src/out/Release/gn_build', 'gn', '-w', 'dupbuild=err', '-j4']' returned non-zero exit status 1
debian/rules:78: recipe for target 'out/Release/gn' failed
`

**Comment by davidhuff2014** [comment]
Setting use_lld=true in the gn_flags.map for ubuntu_bionic did not work for me.
Moving ld out of the way and copying ld64.lld-7 as ld,  did work.

**Comment by psilocibin** [comment]
installed lldb-7 and it works now

**Comment by davidhuff2014** [comment]
I too added lldb-7 but it didn't change the outcome. I tried setting the gn_flags.map and it too had the same outcome. There may be somewhere else where the flags can be set that I am not aware of. I agree it  is calling the wrong linker, copying ld64.lld-7 as ld did allow it to build. I was also able to build by patching out the --icf=all appends everywhere I could find them, was just hoping to make a completely clean build.

**Comment by Eloston** [comment]
This may be related to GN flags. We are using the `unbundle` toolchain, which means we specify what tools to use for compiling. However, the `unbundle` toolchain [defers determination of the linker to the C++ compiler](https://chromium.googlesource.com/chromium/src/+/72.0.3626.96/build/toolchain/linux/unbundle/BUILD.gn#12), which means that Clang may not be selecting the right linker. We could try adding `-fuse-ld=lld` to LDFLAGS (in `debian/rules`) to see if that will force the use of LLD (also leave `use_lld=true` just in case).

**Comment by davidhuff2014** [comment]
Set both flags as you suggested and it got all the way into ninja but:
`[451/18196] ACTION //chrome/test/chromedriver:embed_version_in_cpp(//build/toolchain/linux/unbundle:default)
ERROR:root:Git error: rc=128, output=''
[2832/18196] LINK ./chrome_sandbox
FAILED: chrome_sandbox 
python "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome_sandbox" -- clang++-7 -pie -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O0 -fwhole-program-vtables -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -fsanitize=cfi-vcall -fsanitize=cfi-icall -pie -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,--stats,-fuse-ld=lld -Wl,--stats,-fuse-ld=lld -o "./chrome_sandbox" -Wl,--start-group @"./chrome_sandbox.rsp"  -Wl,--end-group   -latomic -ldl -lpthread -lrt 
ld.lld: error: unknown argument: -fuse-ld=lld
ld.lld: error: unknown argument: -fuse-ld=lld
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2835/18196] CXX obj/sandbox/linux/sandbox_services/syscall_wrappers.o
ninja: build stopped: subcommand failed.
debian/rules:100: recipe for target 'override_dh_auto_build-arch' failed
make[1]: *** [override_dh_auto_build-arch] Error 1
make[1]: Leaving directory '/tmp/src/ungoogled-chromium-master/build/src'
debian/rules:75: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
`

**Comment by davidhuff2014** [comment]
Something may have changed in the setup, this did build with only gn flag set this time. Won't have time until tonight to verify the video.

**Comment by davidhuff2014** [comment]
Adding only use_lld=true to gn_flags.map for ubuntu_bionic worked.

**Comment by tonowoe** [comment]
I was searching how to fix the error below while building, and I found this thread. Simply installing clang (apt-get install clang) fixed the problem.

Traceback (most recent call last):
  File "./tools/gn/bootstrap/bootstrap.py", line 142, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gn/bootstrap/bootstrap.py", line 125, in main
    ['ninja', '-C', gn_build_dir, 'gn', '-w', 'dupbuild=err', '-j'+str(options.jobs)])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/home/ville/ungoogled-chromium-master/build/src/out/Release/gn_build', 'gn', '-w', 'dupbuild=err', '-j4']' returned non-zero exit status 1

**Comment by tonowoe** [comment]
I was searching how to fix the error below while building, and I found this thread. Simply installing clang (apt-get install clang) fixed the problem.

Traceback (most recent call last):
File "./tools/gn/bootstrap/bootstrap.py", line 142, in
sys.exit(main(sys.argv[1:]))
File "./tools/gn/bootstrap/bootstrap.py", line 125, in main
['ninja', '-C', gn_build_dir, 'gn', '-w', 'dupbuild=err', '-j'+str(options.jobs)])
File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/home/tonowoe/ungoogled-chromium-master/build/src/out/Release/gn_build', 'gn', '-w', 'dupbuild=err', '-j4']' returned non-zero exit status 1
