### ISSUE TITLE
Problem with building in Mojave

### ISSUE THREAD

**Issue by gremilkar** [Eloston/ungoogled-chromium#666]
### Description
Error  occurred when I run:" ./get_package.py macos build/src/ungoogled_packaging"

### Environment details

* ungoogled-chromium version: [71.0.3578.98-2]
* Configuration bundle: [macos]
* Packaging type (if applicable): [macos]
* OS and version for building: [macOS Mojave 10.14.2]
* Compiler toolchain: [Xcode 10.1(10861)]

Python 2.7.13 
### Building and packaging steps
When I try to run:
-python get_package.py macos build/src/ungoogled_packaging
Get  this error message:
File "get package.py",line 131
yield from sorted (resolved_files.items())
^
SyntaxError: invalid syntax

**Comment by spotlightishere** [comment]
Cannot reproduce, but instead of your Python 2.7.13, Python 3 should work. The script seems to want such as well.
https://github.com/Eloston/ungoogled-chromium/blob/c68b9f4916d6a34dc6c843a565bfd1ca08b9fe4c/get_package.py#L1

**Comment by Eloston** [comment]
@spotlightishere is correct. It seems we didn't add this to the documentation for macOS. Python 3 is needed for `get_package.py`, and Python 2 is needed for Chromium build scripts. I will note this in the documentation.

**Comment by Eloston** [comment]
82b1194615a6542c28edfc5505d357c9dfca88c7
