### ISSUE TITLE
Pinch to zoom doesn't work in OS X Sierra

### ISSUE THREAD

**Issue by notDavid** [Eloston/ungoogled-chromium#67]
Hi, pinch to zoom doesn't seem to work (i'm using a Macbook with trackpad). Is this a known issue?

Thanks.

(Mac OS X 10.12 -16A323, Ungoogled-chromium 53.0.2785.116)

**Comment by Eloston** [comment]
ungoogled-chromium doesn't touch anything related to pinch-zoom, so it might be a Chromium problem. What website(s) are you trying to pinch-zoom on? Does it work on Chrome?

@9Morello: Do you know anything about this?

**Comment by notDavid** [comment]
Any website.
Yes, I just tried pinch to zoom in the exact same version (53.0.2785.116) from [Chromium FreeSmug](http://www.freesmug.org/chromium) and zooming works.

**Comment by Eloston** [comment]
Huh, that is strange. I'm not sure exactly what caused this to break.

**Comment by Eloston** [comment]
@9Morello: Do you have any ideas?

**Comment by 9Morello** [comment]
Unfortunately, I don't have a Macbook with a trackpad to test this.

**Comment by Eloston** [comment]
Oh ok. Well I'll try to investigate more after I get other issues out of the way first, though that may be a while later.

If anyone else knows more about this, please help out!

**Comment by piningforthefnords** [comment]
Confirming this is broken on El Capitan (2015 MBP Retina 15") as well. It does work with generic Chromium and Chrome, as well as other things (eg; Preview). Zoom using CMD+ works fine.

I'll be happy to help test in any way you like, but I have no idea what I'm doing with GUI apps.

**Comment by Eloston** [comment]
@piningforthefnords Thanks for the info

> I'll be happy to help test in any way you like, but I have no idea what I'm doing with GUI apps.

Well that makes four of us. :/

**Comment by notDavid** [comment]
> Unfortunately, I don't have a Macbook with a trackpad to test this.

I assume Linux/Windows can also do pinch to zoom, on a laptop? Maybe someone can test if they also have the same issue, on another OS..

**Comment by Eloston** [comment]
Possibly. I've seen pinch-to-zoom work on laptops with touchscreens, but I think those websites might have implemented it via JavaScript. Pinch-to-zoom on touchpads are a different interface.

**Comment by Eloston** [comment]
@piningforthefnords Does pinch to zoom still not work on 54?

**Comment by piningforthefnords** [comment]
@Eloston Correct, it's still not working, although CMD+/- does. This was why I was looking at arguments in the build thread, though the zoom option is present in both. There's no mention of zoom or pinch in any of the patches here, so I'm beginning to wonder if part of that takes place in a blob it fetches from Google.

I started Chromium, the latest build of ungoogled-chromium, and srware iron (another chromium variant) while wireshark was running, and saw the other two fetching blobs from Google, whereas this did not. Both of the other ones did have a working pinch to zoom.

I'll see about fetching all the blobs tomorrow and trying to find a reference to it in there.

**Comment by Eloston** [comment]
@piningforthefnords Wow there are blobs for this too? That's weird. I wonder what they are trying to hide...

**Comment by piningforthefnords** [comment]
@Eloston I'm not sure what's going on really. The [first blob](https://www.broken.com/tmp/crap.crx) (unzip works on it) I fetched was pretty innocent looking, but after that it was all SSL, and I don't currently have certs set up on this laptop to allow interception (though I'll get that set up tomorrow). Both of the other Chromium variants fetched quite a bit of data before I quit.

Just to clarify, ungoogled-chromium **was not** making any requests for blobs or anything else from Google.

**Comment by Eloston** [comment]
Huh, alright.

> Just to clarify, ungoogled-chromium **was not** making any requests for blobs or anything else from Google.

Just to clarify, I was wondering why pinch-to-zoom would require blobs at all since it doesn't seem like it would have any licensing restrictions that require it to be blobs.

**Comment by piningforthefnords** [comment]
@Eloston Does not appear to be a blob. Even with all cache and profile data wiped and network disconnected, zoom worked. I'll post if I figure out what it is.

**Comment by poiru** [comment]
@Eloston This is probably due to https://bugs.chromium.org/p/chromium/issues/detail?id=680927

**Comment by Eloston** [comment]
@poiru Thanks for the info. We could build against the 10.10 SDK, but it looks like the problem will be fixing itself soon since https://bugs.chromium.org/p/chromium/issues/detail?id=624049 says all of the compile bots will be updating. This could mean the problem will be fixed by the next stable version.

**Comment by ronakdev** [comment]
The problem actually also exists in standard Chrome (55) as well. :(

**Comment by tectiv3** [comment]
Wow, it works now!

**Comment by Eloston** [comment]
@tectiv3 Oh, neat.
