### ISSUE TITLE
Issues with video playback version 72.0.3626.81

### ISSUE THREAD

**Issue by davidhuff2014** [Eloston/ungoogled-chromium#673]
After a successful build I experienced sporadic issues with playing on-line videos. About half experienced tearing, the other half played well. Went back to the prior version 71 and retested the videos I had experience problems with and they worked fine. Ubuntu 18.04.1

**Comment by Eloston** [comment]
It may be related to VA-API decoding, since it changed in 72. What video driver are you using? What does `chrome://gpu` say about video decoding? Does toggling `chrome://flags/#disable-accelerated-video-decode` do anything?

**Comment by davidhuff2014** [comment]
Adding only use_lld=true to gn_flags.map for ubuntu_bionic worked. I tested several clickbait videos on youtube and one that previously failed all the time with the previous built and all were very good quality.

**Comment by davidhuff2014** [comment]
As an additional note, some days after the build I had some video issues of the same nature I'd experienced previously. Turning off hardware acceleration reduced those rare remaining occurrences to zero.
