### ISSUE TITLE
Additional VAAPI patches

### ISSUE THREAD

**Issue by Ranguvar** [Eloston/ungoogled-chromium#677]
Arch and Fedora are using the new mojo VAAPI patches also, and have two additional patches for the VAAPI version check:

https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=fb41953b188343acb8a4739d5f76427fdfbeed24

Can these be added to ungoogled-chromium?

**Comment by Eloston** [comment]
Sure. Since it's such a small change, it should probably go under `linux_rooted`.

Feel free to submit a PR.
