### ISSUE TITLE
Video Issues 72.0.3626.109-1 ubuntu_bionic

### ISSUE THREAD

**Issue by davidhuff2014** [Eloston/ungoogled-chromium#684]
This actually relates the last several builds. If you have hardware acceleration turned on you may encounter a really nasty looking playback. My AMD processor has 6 video processors and may even be the culprit. Just turn off hardware acceleration and restart ungoogled-chormium to get it sorted out. 
![video_issue](https://user-images.githubusercontent.com/7384846/53032686-511cc480-343d-11e9-9ec3-c78f378d2932.png)

**Comment by ian-moone** [comment]
It's a known issue. See https://bugs.freedesktop.org/show_bug.cgi?id=106490

TL;DR: Start with `allow_rgb10_configs=false` or add it to `/etc/environment` (or similar), then reboot.
