### ISSUE TITLE
Copying http URLs incorrectly converts them to https

### ISSUE THREAD

**Issue by k2l8m11n2** [Eloston/ungoogled-chromium#688]
**Describe the bug**
Copying a http URL from the address bar (e.g. by Ctrl+C) results in a (broken) https URL in the clipboard.

**To Reproduce**
1. Go to any http-only site (like http://neverssl.com)
2. Copy the URL from the address bar
3. Inspect clipboard contents
4. The URL is https and potentially invalid

**Expected behavior**
The URL should be the same as original.

**Environment (please complete the following information):**
 - OS and version: Fedora 29
 - ungoogled-chromium version: 72.0.3626.96

**Additional context**
This results in lots of frustration when copying URLs because the server is often not serving https pages at all or is misconfigured, leading to broken links when sending it to others.
Additionally, please consider reverting the https-as-default change, as it's really annoying in daily usage, I have to remember to add http: before the address. Alternatively, consider falling back to http when https doesn't connect or making this setting a flag. Thank you!

**Comment by qvint** [comment]
This const is somehow left unchanged.

https://github.com/Eloston/ungoogled-chromium/blob/a58db880c15e5077e881cad7b07d1a277ecd463a/patches/ungoogled-chromium/disable-formatting-in-omnibox.patch#L13
