### ISSUE TITLE
My ungoogle can not download extensons from the chrome store ??why

### ISSUE THREAD

**Issue by laokong911** [Eloston/ungoogled-chromium#690]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*

dont download plugins and extensions on google store . 
the google store's install button becomes an available on chrome
 
please help me ,thanks,god bless you .

**Comment by 23rd** [comment]
Please ensure you have read [FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore).

**Comment by laokong911** [comment]
I am so sorry! do not lookout it ! thank you...

**Comment by jieggii** [comment]
Hi everyone. I have created [website](https://ungoogled-extension.github.io/), using one you can easily install extensions from Chrome Web Store. I hope it will help someone. Just paste addon's url from store into input and press install!
