### ISSUE TITLE
Disable proxy controller

### ISSUE THREAD

**Issue by steemandlinux** [Eloston/ungoogled-chromium#697]
A patch, which turns off proxy controller, which in turn can lead to a data leak, because of proxy extension shutdown.

https://codereview.chromium.org/320633002/

```
diff -Npur chromium-72.0.3626.96.orig/chrome/browser/extensions/proxy_overridden_bubble_delegate.cc chromium-72.0.3626.96/chrome/browser/extensions/proxy_overridden_bubble_delegate.cc
--- chromium-72.0.3626.96.orig/chrome/browser/extensions/proxy_overridden_bubble_delegate.cc	2019-02-07 01:06:37.000000000 +0300
+++ chromium-72.0.3626.96/chrome/browser/extensions/proxy_overridden_bubble_delegate.cc	2019-03-02 17:57:12.119946332 +0300
@@ -62,7 +62,7 @@ bool ProxyOverriddenBubbleDelegate::Shou
   // Found the only extension; restrict to this one.
   extension_id_ = extension->id();
 
-  return true;
+  return false;
 }
 
 void ProxyOverriddenBubbleDelegate::AcknowledgeExtension(
```

**Comment by Eloston** [comment]
Could you clarify how this causes a data leak? I'm not familiar with this scenario.

**Comment by steemandlinux** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/Z3SZoKt"><a href="//imgur.com/Z3SZoKt"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by steemandlinux** [comment]
![Alt text](https://i.imgur.com/KGHTVW4.png?raw=true "")

**Comment by Eloston** [comment]
Sorry, I still don't understand. Could you point out and explain exactly what I should be looking for?

**Comment by steemandlinux** [comment]
Proxy controller blocks proxy extensions every 7 days and may cause data leakage through a direct connection. There is no possibility to disable it through the settings.

**Comment by Eloston** [comment]
I see, so when you apply the patch above:

1. What happens to the dialog box?
1. What does "Keep Changes" do now?
2. What does "Restore Settings" do now?
3. What happens to `extension_id_` above the return statement?

**Comment by mglwolf** [comment]
I found the proxy extension is not working on ungoogle chromium, is any idea to enable it

**Comment by r4sas** [comment]
SwitchyOmega works correctly on 89 version. Concretize where it is not works.

**Comment by mglwolf** [comment]
currently, I'm using 88.0.4324.182 (Official Build, ungoogled-chromium 64bit), so you mean this ver. not working, need to wait the latest right?

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
