### ISSUE TITLE
KeePassXC-Browser extension doesn't works

### ISSUE THREAD

**Issue by fujitsuDev** [Eloston/ungoogled-chromium#699]
KeePassXC-Browser doesn't launch properly and can't detect openned database KeePassXC.

**Steps to reproduce the behavior:**
1. Go to https://github.com/keepassxreboot/keepassxc-browser/releases
2. Download v1.3.2 archive and open it
3. Extract _keepassxc-browser_ folder (inside _keepassxc-browser-1.3.2_)...
4. ...and copy in ~_(Chromium location)_/extensions/_(HERE)_
5. Open Chromium and go to _chrome://extensions/_
6. Check if KeePassXC-Browser is activated

**Expected behavior:**

You can see error on KeePassXC-Browser extension card...

![](https://i.imgur.com/KqlYGLC.jpg)
![](https://i.imgur.com/1qg1Jij.jpg)

**Environment:**
 - Windows 7 SP1
 - ungoogled-chromium 72.0.3626.121 (64 bits)
 - KeePassXC-Browser 1.32 (as unpacked extension)

**Additional context:**

`ChromiumCommandLine=--user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad --disable-component-update --disable-gpu --disable-accelerated-video --disable-3d-apis`

This extension works with "stable-codecs-nosync" release, version 67.0.3396.99 (latest): https://github.com/henrypp/chromium/releases

Thanks.

**Comment by TCB13** [comment]
It works for me. At least under windows...

**Comment by Eloston** [comment]
I'm not sure if this is a Windows-specific issue, so I'm going to leave this open for now. If it is Windows-specific, I will close this since we don't support customized versions of ungoogled-chromium (because Windows support isn't updated yet).

**Comment by TCB13** [comment]
@fujitsuDev I'm running the extension on `71.0.3578.98-2` without issues.

**Comment by TCB13** [comment]
@fujitsuDev you can't download directly from the store, you need to follow this procedure: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore. I did that and I was able to use the extension.

**Comment by fujitsuDev** [comment]
@TCB13 I downloaded CRX file from Web Store by following the procedure, but impossible to install CRX within developer mod anyway under Windows 7 or 10: can't drag and drop file (see 2nd screenshot above).

**Comment by TCB13** [comment]
If youn change the flag, chrome://flags/#extension-mime-request-handling to Always prompt for install. You don’t even need to drag and drop. Opening the link of the file would ask you to install right away.

**Comment by fujitsuDev** [comment]
Ok, thats works now! Thanks!

Obviously KeePassXC-Browser don't allow unpacked installation, but only CRX from Web Store.
I don't understand why, but the most important thing, is that works.

**Comment by TCB13** [comment]
> Obviously KeePassXC-Browser don't allow unpacked installation

Did you experience this with other extensions? If not, this can be closed.

**Comment by fujitsuDev** [comment]
> > Obviously KeePassXC-Browser don't allow unpacked installation
> 
> Have you experienced this with other extensions? If not, I guess this can be closed. @Eloston

Only KeePassXC at this time. Works with others extensions tested.

**Comment by Eloston** [comment]
> Obviously KeePassXC-Browser don't allow unpacked installation, but only CRX from Web Store.

Interesting. Didn't know that extensions had the ability to determine that.

> If not, I guess this can be closed.
> Only KeePassXC at this time. Works with others extensions tested.

Sounds fine with me.
