### ISSUE TITLE
My native language somehow shoes on ungoogled-chromium

### ISSUE THREAD

**Issue by AlexIsNice** [Eloston/ungoogled-chromium#701]
So i have been enjoying ungoogled-chromium,i went to whoer.net and saw my local language i went to settings and languages and only saw english,as you may understand this is really not good  for fingerprinting.Is there any way to remove it?

**Comment by Eloston** [comment]
Which binary are you using?

**Comment by AlexIsNice** [comment]
https://chromium.woolyss.com/

The ungoogled one  72.0.3626.121

Link to download: https://chromium.woolyss.com/f/chrlauncher-win64-stable-ungoogled.zip

**Comment by Eloston** [comment]
You should ask whoever built that binary for support. There is no official Windows binary for version 72.
