### ISSUE TITLE
[Question] Is WebRTC currently disabled?

### ISSUE THREAD

**Issue by chazanov** [Eloston/ungoogled-chromium#702]
Is WebRTC currently disabled? https://github.com/Eloston/ungoogled-chromium/issues/319 looks like it's not.

Is there a patch publicly available? I would be very glad about such thing.

**Comment by Eloston** [comment]
WebRTC is not disabled. If it doesn't work, please let us know.

**Comment by chazanov** [comment]
@Eloston Actually I want to disable it.

**Comment by Eloston** [comment]
oh.

I don't know of any patch to disable WebRTC because we haven't found any security or privacy concerns with leaving it enabled (aside from the existing patches).
