### ISSUE TITLE
Push Notifications are not Working

### ISSUE THREAD

**Issue by rockingaryan** [Eloston/ungoogled-chromium#703]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*
Hi,

I love this ungoogled chromium because It is faster and private. I love Old UI and text weight. Chrome shows dark and bold text hurting my eyes.

I recently added an issue which is closed.
https://github.com/Eloston/ungoogled-chromium/issues/589

Is it possible to enable Push Notification Manually? I am not receiving any push notification from sites like Facebook, Twitter and Drift dot com.

I don't want to use Chrome. Could somebody help me to enable this feature?

Using MacOS mojave,
Chromium Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by Eloston** [comment]
As stated in #589, Push Notifications depends on GCM. I don't think it will be easy to re-enable GCM if you still want to maintain the features of ungoogled-chromium. You could try to switch to Chromium or another Chromium-based browser if this is really important to you.

**Comment by notpushkin** [comment]
Maybe using Mozilla's [push service](https://www.w3.org/TR/push-api/#push-service) (`wss://push.services.mozilla.com/`, [docs](https://mozilla-push-service.readthedocs.io/en/latest/#mozilla-push-service)) would be a possibility?

**Comment by Eloston** [comment]
@notpushkin We should be discussing that in a new issue. But does Chromium or a derivative implement the Push API? I'm not too familiar with it.
