### ISSUE TITLE
DevTools profiling broken in 72.0.3626.122 macOS

### ISSUE THREAD

**Issue by vovkasm** [Eloston/ungoogled-chromium#704]
**Describe the bug**
Profiling in DevTools broken in 72.0.3626.122 on macOS. After pressing "stop" button it loading results infinity.

**To Reproduce**
1. Go to 'https://popper.js.org/index.html'
2. Click on 'Cmd+I' (open DevTools)
3. Go to 'Performance' tab
4. Click 'Cmd+E' or Record button (start recording profile)
5. Do some activity on the page (scroll to bottom for ex)
6. Press stop button on performance collecting popup
7. Status will change to "Loading profile...", stop button will lock, but this state will never end...

**Expected behavior**
Step 7 from previous steps, should end with visible profile results.

**Screenshots**
![Step 7](http://vovkasm.skitch.vovkasm.org/chromium-bug_223BB7B1.png)

**Environment (please complete the following information):**
 - OS and version: macOS High Sierra 10.13.6
 - ungoogled-chromium version: 72.0.3626.122-1
 - If this is a custom build, please specify the following:
    This is build from brew cask https://github.com/Homebrew/homebrew-cask/blob/master/Casks/eloston-chromium.rb

**Comment by vovkasm** [comment]
Followup. When I open console for devtools itself (thanks https://stackoverflow.com/a/27661701)

I see this:
![devtools erros](http://vovkasm.skitch.vovkasm.org/devtools-errors_223BF20D.png)

Seems Tracing API removed?

**Comment by vovkasm** [comment]
I think it is because of this patch: https://github.com/Eloston/ungoogled-chromium/blob/master/patches/debian_buster/disable/tracing.patch

**Comment by vovkasm** [comment]
Refer to same bug report for debian folks https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922431

**Comment by Eloston** [comment]
Thanks for the well-constructed report.

I actually removed this patch while working on the `fragmentation` branch, but forgot to do it for `master`. I'll push a change later.

As for the reason why I dropped this patch, it really comes down to how strongly I want to adhere to FOSS principles. While Michael decided that it is important to break features, even large ones, to adhere to FOSS (as shown in the patch comment), I'm not sure if I want to do the same for ungoogled-chromium, at least not for all platforms. I think I'll limit it to Debian platforms only.

**Comment by qxzcode** [comment]
I'm running version 76.0.3809.100 from the Ubuntu PPA, and I'm having this same issue. Do I need to install a non-Debian version of ungoogled-chromium, or build it myself from source...?

**Comment by Eloston** [comment]
@qxzcode 76 is a very old version. It should be working in 79.

**Comment by qxzcode** [comment]
Updated to 79.0.3945.130 and it's now working 👍
