### ISSUE TITLE
Will Ungoogled Chromium move to declarativeNetRequest like official builds?

### ISSUE THREAD

**Issue by pipboy96** [Eloston/ungoogled-chromium#706]
Chromium devs are currently working on a change that will make extensions like HTTPS Everywhere unable to function, since handling each request programmatically will no longer be possible. Will Ungoogled Chromium include patches to reverse these changes?

**Comment by pipboy96** [comment]
Related: EFForg/https-everywhere#17268.

**Comment by Eloston** [comment]
There has been discussion about this in #662. I think it's best to move discussion over to that issue.

To briefly answer your question: Right now, there are no concrete plans related to this issue.

**Comment by pipboy96** [comment]
@Eloston Excuse me, I only skimmed over the first page of issues before asking.

**Comment by Eloston** [comment]
I'm sorry if I offended you in any way. I just want to consolidate the discussion.

You make a good point, so I will revise the title of that issue.

**Comment by pipboy96** [comment]
@Eloston No problem.
