### ISSUE TITLE
error: use of undeclared identifier 'PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_ALWAYS_ON'

### ISSUE THREAD

**Issue by mymortal** [Eloston/ungoogled-chromium#707]
Build fails on Windows 10 with error
` error: use of undeclared identifier 'PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_ALWAYS_ON`

Console output and logs
Full console output available [here.](https://pastebin.com/FwZ2g9bw)

Environment details
ungoogled-chromium version: 72.0.3626.122
Configuration bundle: windows
Packaging type: windows
OS and version for building: Windows 10 (64-bit)
Compiler toolchain: Visual Studio Community 2017 C++ tools
Installed sub-components:
Visual C++ core desktop features
Just-In-Time debugger
VC++ 2017 version 15.9 v14.16 latest v141 tools
C++ profiling tools
Windows 10 SDK (10.0.17763.0)
Visual C++ tools for CMake
Visual C++ ATL for x86 and x64
Test Adapter for Boost.Test
Test Adapter for Google Test
Visual C++ MFC for x86 and x64
Building and packaging steps
Install Visual Studio Community 2017 with the above sub-components

Enable Debugging Tools For Windows for Windows 10 SDK

Install Python 2.7.15, Python 3.7.1 and 7-Zip

Run the command pip install pypiwin32

Set PYTHON user environment variable pointing to Python 2.7.15

Run the commands below in ungoogled-chromium Git repository in cmd.exe as administrator:

mkdir build\src
py get_package.py windows build\src\ungoogled_packaging
cd build\src
py ungoogled_packaging\build.py

**Comment by TCB13** [comment]
@mymortal did you take a look at https://github.com/Eloston/ungoogled-chromium/issues/675 ?

**Comment by mymortal** [comment]
> @mymortal你看了[＃675](https://github.com/Eloston/ungoogled-chromium/issues/675)吗？

Yes, I have seen it, and reference
https://github.com/Eloston/ungoogled-chromium/issues/639#issuecomment-466478108
Methods

**Comment by TCB13** [comment]
@mymortal it only works up to 71.0.3578.98-2. You can't build anything newer than that.

**Comment by mymortal** [comment]
> @mymortal it only works up to 71.0.3578.98-2. You can't build anything newer than that.

thank you
