### ISSUE TITLE
x86_64-apple-darwin15.4.0-c++-4.9 is missing or does not exist!

### ISSUE THREAD

**Issue by stormxeron** [Eloston/ungoogled-chromium#71]
I am new to github, and new for terminal for building apps. When I use build.py, I get following error.

ERROR: Compiler '/usr/local/Cellar/gcc49/4.9.3/bin/x86_64-apple-darwin15.4.0-c++-4.9' does not exist or is not a file

I have installed gcc4.9 from home-brew and in the folder '/usr/local/Cellar/gcc49/4.9.3/bin/', the file isn't there. How do I fix it? Mac OS Sierra 10.12

**Comment by stormxeron** [comment]
Ok edited buildlib/macos.py and ungoogled-macos/fix-libcxx-archive-build-script.patch, working for now, see if any error comes!

**Comment by stormxeron** [comment]
Now I am having this problem:
![screen shot 2016-09-30 at 9 47 07 am](https://cloud.githubusercontent.com/assets/22469267/18980339/01f4e13e-86f3-11e6-9d57-b49b7566106e.png)

I think it is searching for PRESUBMIT.py for Archive do not have matching md5. How do I fix this?
Thanks

**Comment by Eloston** [comment]
If the `md5` doesn't match, that means the archive is corrupt. I'll modify it so the build script will halt if the hash check fails.

What exactly did you do to fix your initial problem?

**Comment by stormxeron** [comment]
Actually I edited the files macos.py and fix-libcxx-archive-build-script.patch. Changed the line (x86_64-apple-darwin15.4.0-c++-4.9 -> x86_64-apple-darwin16.0.0-c++-4.9)

**Comment by Eloston** [comment]
Oh ok. Thanks for that info. I might make the compiler detection a little smarter in the future.

You should probably try deleting your `build/` directory and re-running `build.py`

**Comment by stormxeron** [comment]
Ok, Thanks 👍

**Comment by stormxeron** [comment]
How large is chromium-53.0.2785.116.tar.xz....It is taking forever.

**Comment by Eloston** [comment]
Over 400 MB

**Comment by stormxeron** [comment]
Oh!

**Comment by hellodstyle** [comment]
mute the thread

2016年9月30日星期五，stormxeron <notifications@github.com> 写道：
