### ISSUE TITLE
Search in the address bar

### ISSUE THREAD

**Issue by leon0707** [Eloston/ungoogled-chromium#712]
**Describe the bug**
Input keywords in the address bar, then press enter. It will not direct to the default search engine page.

**To Reproduce**
1. input XXXX in the address bar
2. Press 'enter'

**Expected behavior**
When users press the enter key, it should open the search page.

**Environment (please complete the following information):**
 - Mac mojave
 - ungoogled-chromium version: 72.0.3626.122 - 1
 - installed through brew cask

**Comment by Eloston** [comment]
So what happens instead?

**Comment by leon0707** [comment]
Nothing happens after pressing 'enter', which is not right. In the previous versions, it directs to the search page. I notice another problem. The new version has a hard time distinguishing user's input in the address bar.

Eg.

![image](https://user-images.githubusercontent.com/523684/54779403-74c65c80-4bed-11e9-95fe-e25c2e5d9337.png)

"turin" is not a valid url, but browser will still try to visit 'turin'.

**Comment by Eloston** [comment]
This may be specific to the macOS version. I have a Debian buster build which isn't affected by this issue.

Can anyone else confirm this issue?

**Comment by davidhuff2014** [comment]
Have never had this issue using Ubuntu, I am a full time address bar searcher, It utilizes the default search engine for me.

**Comment by Eloston** [comment]
@leon0707 macOS has been on 73 for a while, and 74 is already out. If this is still an issue, please let us know.
