### ISSUE TITLE
Announcement: Updating all platform support

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#715]
Hi everyone,

I've decided to merge changes for #651, which is a massive refactor that splits code for platforms into separate repositories. Unfortunately, this has broken support for all of the supported platforms up until now.

Right now, I am in the process of updating most of the code for all the platforms. Once this is done, I'll be posting new issues to call for assistance in building/testing the new code. Please be on the lookout for new changes in the platform repositories that you are interested in.

Finally, if you need to build ungoogled-chromium for a platform that hasn't been updated yet, please use the code and instructions in the tag 72.0.3626.122-2 or earlier.

Thanks!

**Comment by DonaldTsang** [comment]
@Eloston mind if I ask, why aren't there any pre-compiled Windows, OSX and Linux binaries? Although people say compiled binaries are unsafe in some sense, it would make the ungoogled lifestyle more accessible to the technologically challenged.

**Comment by Eloston** [comment]
@DonaldTsang Links to binaries are available in the ungoogled-chromium README and the READMEs for all platform repos. I'm wondering if there is a way to make that more clear; would you have any suggestions?

**Comment by DonaldTsang** [comment]
@Eloston Having your own website would be the the clearest, but I don't think that you could spare the resource to do so. The next best thing would be to put the binary section on top, and change the repo's description that links directly to the releases page, where the binaries are shown.

**Comment by Eloston** [comment]
Hopefully it's better with d039263d70407f4c2eca92ccedf035db33e4c049.

**Comment by auqaspy** [comment]
Thanks!

**Comment by DonaldTsang** [comment]
Thanks!

**Comment by auqaspy** [comment]
if we create an official site for ungoogled chrome, in wordpress, I Think it would spread ungoogled chrome and make easier for non programmers @DonaldTsang  @Eloston

**Comment by DonaldTsang** [comment]
@aquaspy Even better

**Comment by auqaspy** [comment]
So can I start a project @Eloston  ? I will try to create a website and I can Host the files of ungoogled chrome in my pcloud since I have 500gb lifetime

**Comment by Eloston** [comment]
@DonaldTsang @aquaspy I think we should just have the website hosted on GitHub so it's easier for us to maintain. We should discuss this further in #335.

**Comment by DonaldTsang** [comment]
@Eloston sounds good

**Comment by Serkan-devel** [comment]
Maybe one can host the site on github pages, using a static site generator

**Comment by lipici** [comment]
> @DonaldTsang @aquaspy I think we should just have the website hosted on GitHub so it's easier for us to maintain. We should discuss this further in #335.

i think we should have the both, being only only on github it will look only like used by few people, an officila site where we can have a link with redirect to download from github will increase the audience, people will write about browser, will be more interested about him, people will contribuite more and will have faster fixes, new realases and so on. One thing leads to another. But this is just my opinion. Im no expert.

**Comment by DonaldTsang** [comment]
@lipici cross-linking would reduce the work. A titanium.com link (assuming it is called Titanium) would direct to a github.io link

**Comment by v00v** [comment]
@DonaldTsang https://ungoogled-software.github.io/ungoogled-chromium-binaries/

**Comment by DonaldTsang** [comment]
@v00v YES! Finally! but... can it be `https://ungoogled-software.github.io/binaries/` ?

**Comment by Eloston** [comment]
The migration is completed, and I think everyone has already adjusted to the new system. Thank you all who have helped in the transition.
