### ISSUE TITLE
Hardware-accelerated video decoding is really slow after upgrading 71 -> 72

### ISSUE THREAD

**Issue by tonowoe** [Eloston/ungoogled-chromium#719]
After upgrading from `71.0.3578.98-1~stretch` to `72.0.3626.122-3.stretch1` I experienced lots of lag (skipping frames and videos generally not playing properly) while playing HTML5 videos, especially 1080p. Then I disabled the hardware-accelerated video decoding and the problem went away. I just wanted to post this issue because other people might have the same problem right now after upgrading 71 to 72.

**Comment by Eloston** [comment]
Interesting. What graphics card and driver are you using?

**Comment by tonowoe** [comment]
AMD Radeon 6870. Open-source (Xorg) drivers.

**Comment by Eloston** [comment]
Strange, I don't think I'm having such issues on my Intel HD 620. Is anyone else having these issues?

**Comment by dackelblut** [comment]
@tonowoe can you provide a test case? I do have a system with a RX 480 at home and had no problems using booth browser versions playing the video in [1]. But if system load increases (e.g. kernel build) it starts dropping frames and later on it jumps. I get that with all chromium-based browsers though.

[1] https://www.twitch.tv/videos/408105082 (german streamer playing arma, max selectable size is 1080p60fps)

**Comment by tonowoe** [comment]
@dackelblut Open up a YouTube video, make sure it's 1080p, then just watch it. With Hardware-accelerated video decoding turned on, the video will drop frames. When the hw-accelerated video decoding is turned off, video will not drop frames. No other system load.

**Comment by Eloston** [comment]
VA-API acceleration has been buggy with recent Chromium, so I've disabled it until it gets fixed. It doesn't seem Stretch will be updated anytime soon (if at all), and I've already moved onto Buster a while ago. If VA-API acceleration gets re-enabled and you stil have a similar issue, please open a new issue.
