### ISSUE TITLE
Flash support on macOS

### ISSUE THREAD

**Issue by sanmarcos** [Eloston/ungoogled-chromium#72]
The only reason I have Chrome installed is for the built in Flash for sites that still need it (so I don't have to have a separate system installation of Flash). How do I get the built in flash in Ungoogled Chromium?

Is this even wise if there is no auto update mechanism to disable/update it when new 0days come out every week?

**Comment by Eloston** [comment]
[It seems that Adobe's version of Flash player has an auto-update mechanism for macOS and Windows](https://helpx.adobe.com/flash-player/kb/flash-player-background-updates.html)

To get it:
Go to https://get.adobe.com/flashplayer/otherversions/ and:
1. "Mac OS X 10.6-10.12"
2. "FP 23 Mac for Opera and Chromium - PPAPI"

**Comment by stfnhrrs** [comment]
The above instructions work perfectly, can I suggest marking this as closed?
