### ISSUE TITLE
Config option to disable push notifications completely and their permission popups

### ISSUE THREAD

**Issue by saltama** [Eloston/ungoogled-chromium#722]
They are annoying. Most of the people never enables them. They start becoming commonplace   on many sites. They are most of times utterly useless.

Firefox is introducing [a feature to limit them or disable them completely](https://blog.nightly.mozilla.org/2019/04/01/reducing-notification-permission-prompt-spam-in-firefox/). Will Chromium do something similar?

If someone wants to implement this while we wait, that would be **greatly** appreciated.

**Comment by xsmile** [comment]
This is not an issue. You can block notifications at `chrome://settings/content/notifications`.

**Comment by saltama** [comment]
Never noticed that option! Thanks @xsmile, closing this.
