### ISSUE TITLE
[Windows] build.py fails with ModuleNotFound for buildkit

### ISSUE THREAD

**Issue by aquaspy** [Eloston/ungoogled-chromium#723]
I am new at the world of proggraming. I set the python 2.7 as python, python 3.7 as py in cmd, and installed windows SDK (instead of I don't know if I did it right). I changed the limit of the path in regedit and I installed the git (and set it in the system to work in cmd), but when I go in cmd and try to build, this doesn't works. Here is the "log":

Microsoft Windows [versão 10.0.17763.379]
(c) 2018 Microsoft Corporation. Todos os direitos reservados.

C:\Users\aquasp>cd Desktop

C:\Users\aquasp\Desktop>cd ungoogled-chromium-windows

C:\Users\aquasp\Desktop\ungoogled-chromium-windows>py build.py
Traceback (most recent call last):
  File "build.py", line 24, in <module>
    import buildkit.config
ModuleNotFoundError: No module named 'buildkit'

C:\Users\aquasp\Desktop\ungoogled-chromium-windows>

What should I do or try? I want to help in this project because I found it amazing, so I waas trying to build the latest for windows. Can anyone help me?

**Comment by Eloston** [comment]
Those Windows scripts have not been updated since I migrated them to `ungoogled-chromium-windows`. Both `build.py` and `package.py` will need to be migrated from `buildkit` to utilities in `ungoogled-chromium/utils`. I'll try to find some time to do the migration.

**Comment by auqaspy** [comment]
oh, thanks @Eloston . I really would like to help, but I do not have experience yet :(

what should I study first to be able to help in ungoogled chrome as a whole?

**Comment by Eloston** [comment]
You should try building a version of ungoogled-chromium first. It will help you get an initial impression of how the build process works.

To understand how the build process works in more depth, you can read ungoogled-chromium's building and design documentation. Those documents have links for further reading.

Once you understand how building works, you can read through the patches and Google's design documentation on Chromium. That should give you a good understanding of how the source code is structured.
