### ISSUE TITLE
[Feature Request] Remove href hyperlink auditing/ping?

### ISSUE THREAD

**Issue by saltama** [Eloston/ungoogled-chromium#725]
From this [post](https://lapcatsoftware.com/articles/Safari-link-tracking.html) (see update at the bottom, with this [chromium commit](https://chromium.googlesource.com/chromium/src.git/+/80a809a3566fe87ecbf2d7255ff7af4a7ee2fcb8)) i've discovered that sooner or later (the next stable switch?) chromium will remove the flag to disable the feature "hyperlink auditing" that will remain permanently enabled.
~I have to admit that it's the first time that i hear about it~(i already had it disabled), but it's something that should be removed in my opinion.

I've searched through the patches and i couldn't find any reference to "hyperlink auditing" or "ping" ([this](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/core/inox-patchset/0015-disable-update-pings.patch) seems unrelated).

I we haven't removed the relevant code we should (in extra/?).

Edit: Or we could just enable back the option since for now the code checking for its value is still there (not future-proof?)?

**Comment by alphabug** [comment]
Extensions like uBlock Origin can still block pings by the chrome.privacy or chrome.webRequest API. Of course, it would be better to not require extensions.

**Comment by Eloston** [comment]
I'm failing to understand the value of a patch here. Is there any chance for hyperlink auditing pings to occur if they're disabled via `chrome.privacy` or `chrome.webRequest`? I'm also not convinced that the maintenance overhead of a patch is worth it over an extension that disabled hyperlink auditing. (However, if the APIs are to be removed eventually, then it would be a completely different story.)

**Comment by saltama** [comment]
I agree, this has to be carefully considered because the maintenance cost of this could become  substantial.
Right now this can still be controlled with `chrome.privacy.websites.hyperlinkAuditingEnabled` and that's what uBlock [is depending on](https://github.com/uBlockOrigin/uBlock-issues/issues/518), but they could completely remove it sooner or later.
Will keep an eye on this and report back is something changes/needs to be addressed here.

**Comment by forkoz** [comment]
I run ublock origin and hyperlink auditing was enabled in chrome:// flags. I had to go in and disable it separately. Maybe it was blocked anyway or maybe not. Either way its going away in the next chromium release. This shipped disabled in firefox by default, I don't understand why we can't have the same.

**Comment by Eloston** [comment]
@forkoz Two main reasons:

1. A patch isn't worth it if an extension can disable this feature (as discussed above)
2. I don't like disabling features (though in this particular case, it's arguable whether this feature is needed at all).

**Comment by forkoz** [comment]
I do get #2 but I thought the main use of ungoogled chromium was to have privacy enhancement. It seems  akin to leaving search autocomplete "off" by default. I did not mean purge pings completely from the code.

**Comment by chebourne** [comment]
This is extraordinary, surely Ungoogled chrome is all about stopping Google from tracking you. The Hyperlink Auditing (URL Ping) option is there precisely to enable Google (and others) to track you. I was surprised to discover that the option is not even disabled in the current release of Ungoogled Chrome - why is that?

Is it the case that the option to disable is being removed from Chromium itself or just Google's chrome? Or am I being naive thinking there is a difference?

If from Chromium itself then, unfortunately the maintenance hit has to taken if Ungoogled Chrome is to continue to be relevant.

**Comment by Eloston** [comment]
@chebourne As I have already discussed above, you can still disable hyperlink auditing via an extension. Therefore, we don't need to change any more code at this time. The lower the impact our code changes make, the faster we can keep up with newer versions of Chromium.
