### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by franc3** [Eloston/ungoogled-chromium#726]
I know you already covered this section but I want to ask again if you could do a flatpak package.
I think it would be one of the bets things to do because it is self contained you can push update and mostly every distro has Flatpak's support. Very easy to use. I am not a Developer but it seems not to difficult to build chromium flatpak.

**Comment by chazanov** [comment]
Who needs this? flatpak is totally useless.

**Comment by franc3** [comment]
It depends on your usage. On not so popular distros with not many packages it is very useful. You can instantly push updates and the bugs are the same on every distro so you don't have to make bugfxing for every binary. Nowadays many packages aren't even in normal repositorys and only distributed with flatpaks/snaps. Only because you don't use it it isn't useledd for others.

**Comment by Eloston** [comment]
I don't mind if a Flatpak version is made. Maybe we could add some scripts to ungoogled-chromium-portablelinux to create Flatpak packages.

To anyone that is interested, feel free to submit a PR (or an issue to discuss design decisions if necessary).

**Comment by trymeouteh** [comment]
I would prefer a flatpak over an appimage and be able to get updates through Linux Mint software manager.
