### ISSUE TITLE
[Guix] global/content/bindings/popup.xml breaks the build

### ISSUE THREAD

**Issue by znavko** [Eloston/ungoogled-chromium#730]
**Describe the bug**
Build process stops and freezes my system, and this message is displaying when I work in Icecat only:
"A script on this  page may be busy, or it have stopped responding...
Script:chrome://global/content/bindings/popup.xml:276"

**To Reproduce**
1. Install Guixsd, update to this commit
$ guix describe
Generation 94	Apr 11 2019 21:13:38	(current)
  guix a6de569
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: a6de569ea224a2f482c4d13c5f62240d1b1543a0

2. Install ungoogled-chromium package
$ guix package -i ungoogled-chromium

3. Run updates
$ guix pull && guix package -u

4. ungoogled-chromium build will reach 84% and stop.

**Screenshots**
http://0x0.st/zNo0.jpg

**Environment (please complete the following information):**
 - OS/Platform and version: GuixSD commit: a6de569ea224a2f482c4d13c5f62240d1b1543a0
 - ungoogled-chromium version: $ chromium --version
Chromium 73.0.3683.86

**Additional context**
I only use Icecat in that time while build process go. I have installed ugoogled-chromium. It rebuilds cause dependencies are updated.

**Comment by mbakke** [comment]
I believe the problem here is that the Chromium build processes ran out of memory.

It should be fixed by this unfortunate Guix commit:
https://git.savannah.gnu.org/cgit/guix.git/commit/gnu/packages/chromium.scm?id=9a2e5fe5fdcc6ea848ceeefa0f70147dfb360639

**Comment by Eloston** [comment]
@mbakke You could also try setting `jumbo_file_merge_limit` to a lower value. Debian uses `8`.

At this point, I might as well create a building FAQ...

**Comment by mbakke** [comment]
@Eloston `jumbo_merge_file_limit=8` succeeded with -j 8 on a 16GB RAM machine.  It will be in the Guix package soonish (to avoid needlessly rebuilding it).

Thanks for the tip, I think this can be closed now.

**Comment by mbakke** [comment]
For reference, here is the Guix commit:

https://git.savannah.gnu.org/cgit/guix.git/commit/?id=6a489839a8852dc3428c53b0d35ead32e06dc1ac

(I don't seem to have permissions to close this issue...)

**Comment by Eloston** [comment]
@znavko If you're still affected, let us know.
