### ISSUE TITLE
Getting logged out after some time

### ISSUE THREAD

**Issue by smcgit** [Eloston/ungoogled-chromium#732]
**Back Story**

Ungoogled Chromium was working fine until the day I had to reinstall Windows on my PC. Luckily I backed up my AppData folder. After copying `%Appdata%\Local\Chromium` to a fresh version of Windows and starting a fresh version of Ungoogled Chromium, almost everything was restored. The only thing missing were the login data and addons.

**Issue**

My only issue is, that I am getting logged out of every website, when the browser has been closed for some time, which never happened on my old OS. I have the correct settings in [chrome://settings/content/cookies](chrome://settings/content/cookies), where I say not to delete local files after closing the browser.

Anything else I can try?

**Steps to reproduce**

One way to reproduce this issue would be to run a fresh Windows with Ungoogled Chromium on VirtualBox and copy your Chromium folder from Appdata. But I did not try this yet.

**Comment by r4sas** [comment]
67.0.3396.87?

**Comment by smcgit** [comment]
Yes.

**Comment by smcgit** [comment]
I was getting logged out only from most of the sites. Some sites I was still logged in.

Deleting browser history, download history, cookies and cache fixed the problem.
