### ISSUE TITLE
Disable Hyperlink Auditing by Default

### ISSUE THREAD

**Issue by chebourne** [Eloston/ungoogled-chromium#733]
Shouldn't Hyperlink Auditing (URL Ping) be disabled by default in Ungoogled-Chromium?

**Comment by Eloston** [comment]
This is a duplicate of #725. See:

* https://github.com/Eloston/ungoogled-chromium/issues/725#issuecomment-481563319
* https://github.com/Eloston/ungoogled-chromium/issues/725#issuecomment-484178868
