### ISSUE TITLE
I made an extension to download extensions

### ISSUE THREAD

**Issue by TheDevKiller** [Eloston/ungoogled-chromium#734]
I have read some issues where people suggest scripts or ideas to download extensions and I have seen why they were refused. So my extension doesn't have the inconveniences of the other's propositions. https://github.com/TheDevKiller/extension-downloader
All the details in the README

**Comment by Eloston** [comment]
Thanks. If you would like, you can submit a PR against ungoogled-software/ungoogled-chromium-wiki in the FAQ section about installing extensions from the Web Store.
