### ISSUE TITLE
crx files invalid

### ISSUE THREAD

**Issue by 0lm** [Eloston/ungoogled-chromium#735]
hi there

first of all i am not sure what i am doing wrong.
i downloaded the crx files of the extensions and followed the instructuin on FAQ how to install extensions on chromoium ungoogled.
but chromoim always tells me "package invalid: crx header is invalid"
im not sure how to solve this.

EDIT: im sorry. i did something wrong. i found out my mistake now. it works now, i can install crx files.
bu before opening a new issue, i hope its okay to ask in the current one a new question: do i need to manually update the extensions or will auto updating still work on ungoogled chromum?

**Comment by Eloston** [comment]
No worries, glad you're able to figure it out.

> do i need to manually update the extensions or will auto updating still work on ungoogled chromum?

You'll need to manually update for now. For autoupdating, help is needed to implement #285.

**Comment by Gladuin** [comment]
Hi, 
I'm having the same issue, how did you fix it? I have found out that when you unpack the crx, then repack it and then install the repacked crx, it works fine. But that's a huge hassle...

**Comment by jeyeveey26** [comment]
> Hi,
> I'm having the same issue, how did you fix it? I have found out that when you unpack the crx, then repack it and then install the repacked crx, it works fine. But that's a huge hassle...

The FAQ is pretty straight forward on how to install

`chrome://flags/#extension-mime-request-handling` set to Always prompt.

`https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=[VERSION]&x=id%3D[EXTENSION_ID]%26installsource%3Dondemand%26uc`

https://chrome.google.com/webstore/detail/ublock-origin/**cjpalhdlnbpafiamejdnhcphjbkeiagm**?hl=en

Replace [VERSION] with your ungoogled chromium version. Replace extension with the letters similar to the ublock example.
[FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq)

**Comment by Gladuin** [comment]
Hey, sorry for the late answer, but that worked great!!
