### ISSUE TITLE
Ungoogled Chromium not listed in the FSF directory

### ISSUE THREAD

**Issue by libBletchley** [Eloston/ungoogled-chromium#736]
Is Ungoogled Chromium completely free software?  I thought it was, but I don't see it listed in the FSF Directory (https://directory.fsf.org/wiki/).  If there are no licensing issues, someone might want to get it listed (free publicity and it enables people to quickly check if it is free s/w).

**Comment by Eloston** [comment]
Yes, ungoogled-chromium is completely free software. If someone wants to get it published there, feel free to do so.
