### ISSUE TITLE
Rename the project to protect it legally

### ISSUE THREAD

**Issue by emanruse** [Eloston/ungoogled-chromium#738]
(Chromium's license](https://github.com/chromium/chromium/blob/master/LICENSE) says:

```
//    * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
```

The name "ungoogled" obviously does include the string "google". Renaming the project would be a good way to protect it from potential legal sanctions.

Also to protect the future of this excellent project I suggest that serious attention is paid to the legal side of things (licenses, ensuring that everything is fully FOSS etc).

**Comment by Eloston** [comment]
Everyone, [please vote here for a new name](https://linkto.run/p/4N2XRUGC)

**Comment by qvint** [comment]
Let's call it Ferrochrome.

> Ferrochrome, or Ferrochromium (FeCr) is a type of ferroalloy, that is, an alloy between chromium and iron, generally containing 50% to 70% chromium by weight.
> — https://en.wikipedia.org/wiki/Ferrochrome

**Comment by arutr** [comment]
Or Purifium

**Comment by SuperRobinHood** [comment]
To keep up with how the current name is - maybe Ungazed-chromium? Uneyed-chromium? Unglared-chromium? But if we're going with minerals, I like qvint's ferrochrome.

**Comment by emanruse** [comment]
I haven't researched if the names "chrome" or "chromium" may have legal implications too. Perhaps that should be checked by someone more experienced in licenses and other legal stuff.

**Comment by SuperRobinHood** [comment]
That would suck. It would mean ferrochrome is probably out too.

**Comment by Eloston** [comment]
Both Chromium and Chrome are trademarked according to Google: https://www.google.com/permissions/trademark/trademark-list/

So at the very least, names including those trademarks within them would put us in a grey area.

**Comment by lipici** [comment]
Escape /Retake / BackSpace / About

**Comment by emanruse** [comment]
> Both Chromium and Chrome are trademarked

Then the new name should be a word which has never been trademarked or reserved in other way and a proper license should make it impossible for anyone to "own" it in future. Only 100% FOSS.

**Comment by Qudix** [comment]
I went with Alphium

**Comment by v00v** [comment]
I requested for name change back in 2018 and it was ignored. https://github.com/Eloston/ungoogled-chromium/issues/642

My last comment and suggestion was to call it "**Libre**"

> How about simply Libre (https://www.wordnik.com/words/libre)
> adj. With very few limitations on distribution or improvement; including source code.

**Comment by garoto** [comment]
> Another new suggestion is calling it "**Phoenix**"

**Phoenix** was what Firefox was called on its 1st iteration, but it was dropped due to trademark issues.

https://en.wikipedia.org/wiki/History_of_Firefox#Naming

**Comment by SuperRobinHood** [comment]
Hey, I think I've got something good - gotta write it down before I inevitably forget it. ELUDIUM - as in, we ELUDE google's spying. What do you think?

**Comment by loongkylin** [comment]
Univesal is good name


 
---Original---

**Comment by v00v** [comment]
@garoto Didn't know that, thank you!

Looks like any name chosen will a trademark issue, because many businesses use same names. In that case, simply calling it "Secure Chromium" or "Chromium Inox" etc. will be good enough. Calling it some weird names like some people suggesting here, will make "Ungoogled Chromium" project hard to find. It has to be called something common sence that anyone thinking about secure chrome/chromium will know what to look for. Also make sure you that you be very clear about this name change in README somewhere. So anyone looking for new project name can still find it by typing "ungoogled chromium".

**Comment by iamfilipc** [comment]
I came up with these:
1. Chromite (as a mineral from which is pure chomium synthesized but unlike pure but synthetic chromium, chromite is naturally occuring in nature. So we can say Chromium is unnatural, and google stands against nature.)

2. Bromium ( It's similar to my favourite Android browser [](url)https://www.bromite.org which I think is good.)

And found some interesting names from greek mythology:
4. Chromion
5. Chromis
6. Chromius

And I would like an icon to have green color not default blue - almost all icons are blue.

**Comment by HandsomePixel** [comment]
I came up with these:
**Librium** or **Librite** (because open source)
**Cromo/Cromo Browser** (spanish/italian for the "Chromium" element, idk if it's legal to use the original name in a different language)
**Photon**

**Comment by bit-chemist** [comment]
Molybdenum. Same chemical group as Chromium, one period higher, so very similar chemical properties.

**Comment by lipici** [comment]
other option will be to try to fusionate\make a proposition to other developers like ntlite /hp /xda /and called ntlite browser/ hp browser/ xda browser and of course if they can help with development.

**Comment by PonyPC** [comment]
I'd like Inprivate-Chromium or Untracked-Chromium which is what the project to do

**Comment by r4sas** [comment]
> I'd like Inprivate-Chromium or Untracked-Chromium which is what the project to do

https://github.com/Eloston/ungoogled-chromium/issues/738#issuecomment-485485492

**Comment by PonyPC** [comment]
So, how about Inprivatium

**Comment by HandsomePixel** [comment]
I don't really like the suffix "In" for "Inprivatium", so how about "Privacium" instead?
And then in the project page, you could add something like "_Privacy and Chromium_"

**Comment by davidhuff2014** [comment]
I'd be proud to say I use the Elostonian Browser, because it rings like the Newtonian Telescope.
Works for me. ;)

**Comment by emanruse** [comment]
What is essential for this browser is not the fact that it is a fork of another browser (named after a chemical element) but that it creates zero unwanted connections. So why not simply call it "Zero"? Simple, short, easy to remember.

**Comment by 23rd** [comment]
@emanruse And hard to find it in Google (or whatever else).

**Comment by t00** [comment]
How about Barium? Short enough and implies it's bare nature without any strings attached while preserving Chromium morphology?

**Comment by emanruse** [comment]
> And hard to find it in Google (or whatever else).

A great number of existing dictionary words are already used for brand names (including chemical elements). That doesn't mean those brands cannot be found. It is just linguistic ambiguity (like Apple or Raspberry).

**Comment by Eloston** [comment]
Unfortunately, it appears that someone has manipulated the votes on the 5th of May, since the name "Pristine" has popped out of nowhere into the lead. As a result, I have decided to end the voting and announce my decision.

First, I would like to thank you all for voting. There have been a lot of interesting and creative suggestions, notably those derived from Chrome/Chromium. However, if we are to choose a name that is safe from legal repercussions, I do not think it is wise to choose names too similar to existing trademarks.

Based on the most popular result (which may be due to how I setup the poll to begin with), I have decided upon the name **uncloudium**. The name migration involves a lot of separate repos and systems to be updated, so I will be tracking progress in a new issue.

**Comment by nunbit** [comment]
As @v00v wrote
> Most other names I see suggested is not logical for such great project like this.
> Especially two default choices "uncloudium" and "detachium" in the poll are very dumb. _sorry_

Not logical indeed also legally likely very unfit. But "Hey let's rename the project every week just for fun" I am sure @Eloston has more important things to do than this wich is why it should be handled right once and carefully not in a hurry.

**Comment by yilmi** [comment]
@emanruse with all due respect, I'm not sure what you were thinking about when you opened this request.
Thanks for your contribution to killing a project by confusion

**Comment by emanruse** [comment]
@yilmi this is not a request but a suggestion aimed to protect the project, not to kill it.

**Comment by biziclop** [comment]
Dontbeevilium? :)

**Comment by derlaft** [comment]
`chlorine-unevilium`
