### ISSUE TITLE
Can't install extensions on macOS

### ISSUE THREAD

**Issue by agucova** [Eloston/ungoogled-chromium#74]
![2eca61abac6f0577fd0df16ad07c0661](https://cloud.githubusercontent.com/assets/4694408/19017759/8f641722-881c-11e6-9ef6-37c60d5ad6be.gif)

**Comment by Eloston** [comment]
Does that actually work on other platforms? Have you tried dragging from a file explorer?

@9Morello: Do you know anything about this?

**Comment by agucova** [comment]
Dragging from finder seems to work, but according to the inox-patchset documentation:

> Download the crx file with the browser, open chrome://extensions and drop the file from the download bar into the extensions tab.

**Comment by agucova** [comment]
Should I close the issue?

**Comment by Eloston** [comment]
This may be a Chromium issue. gcarq probably tested only on Linux, so it'll work differently.

I'm closing for now since it doesn't seem to be an ungoogled-chromium issue.
