### ISSUE TITLE
[73] VA-API with camera streaming freezes browser

### ISSUE THREAD

**Issue by kabo** [Eloston/ungoogled-chromium#740]
**Describe the bug**
Chromium crashes when trying to use the camera. Or maybe it's showing the video from the camera. I'm not sure.

**To Reproduce**
1. Go to https://meet.jit.si/SomeRandomTestRoom
2. Allow using the camera
3. Browser freezes

**Expected behavior**
The video chat to work normally, like it used to.

**Environment (please complete the following information):**
 - Debian Buster, X11
 - ungoogled-chromium version: 73.0.3683.103

**Additional context**
When starting chromium in the terminal and taking the above steps I see this in the terminal output:
```
[54:280:0422/235628.282301:ERROR:vaapi_utils.cc(90)] vaGetImage failed: the requested function is not implemented
```

I tried disabling video hardware acceleration, but it didn't make any difference.

**Comment by Eloston** [comment]
I tried this on my Buster system, and the video works fine regardless of the setting for `chrome://flags/#disable-accelerated-video-decode`. What GPU(s) do you have in your system?

**Comment by kabo** [comment]
```
$ sudo lspci
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 520 (rev 07)
```

**Comment by kabo** [comment]
Hmm, it doesn't seem to want to talk to my U2F key either (Solo key)...

**Comment by kabo** [comment]
I've tried rebooting my computer, didn't help. At first I only installed 
```
ungoogled-chromium_73.0.3683.103-1.buster1_amd64.deb
ungoogled-chromium-common_73.0.3683.103-1.buster1_amd64.deb
```
now I tried also installing 
```
ungoogled-chromium-driver_73.0.3683.103-1.buster1_amd64.deb
ungoogled-chromium-l10n_73.0.3683.103-1.buster1_all.deb
ungoogled-chromium-sandbox_73.0.3683.103-1.buster1_amd64.deb
ungoogled-chromium-shell_73.0.3683.103-1.buster1_amd64.deb
```
doesn't seem to make any difference.

**Comment by kabo** [comment]
I removed ungoogled-chromium 73 and reinstalled my old `.deb`'s:
```
ungoogled-chromium_72.0.3626.122-1~buster_amd64.deb
ungoogled-chromium-common_72.0.3626.122-1~buster_amd64.deb
ungoogled-chromium-sandbox_72.0.3626.122-1~buster_amd64.deb
```
Camera/video seems to be working normally again, not seeing that `vaGetImage` error anymore.

**Comment by kabo** [comment]
My solo key still won't work though.

https://update.solokeys.com/ works fine in Firefox, but not in chromium anymore. So that rules out any udev rules issues. I wonder if some setting got set in the update, and is now blocking the solo key even though I downgraded?

**Comment by Eloston** [comment]
Can you post the output of `vainfo`? Here's mine:

```
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Kaby Lake - 2.3.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

> My solo key still won't work though.

This is separate. Please open a new issue for that.

**Comment by kabo** [comment]
```
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.3.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointStats
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointStats
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointStats
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
```

**Comment by Eloston** [comment]
Hmm, I couldn't find anything particuarly useful from comparing the outputs.

It's possible that this issue is related to VA-API encoding, since the decoding flag doesn't change the outcome. However, I don't know much about VA-API to know how to further diagnose this problem.

@xsmile Would you happen to have any insights in this problem?

**Comment by xsmile** [comment]
meet.jit.si works here, however it uses VP8 which is not hardware accelerated on my machine. This might be related to WebRTC.

Chromium contains a series of flags responsible for toggling WebRTC hardware acceleration [1] which on Linux are neither exposed by default, nor influenced by the VA-API patch. Changing these settings could help avoiding the issue, if this is the case:
```
disable-webrtc-hw-decoding
disable-webrtc-hw-encoding
enable-webrtc-hw-h264-encoding
enable-webrtc-hw-vp8-encoding
```

Regardless of these settings, you can run Google's WebRTC test app [2] with different video codecs. Use the following URL to try H264, VP8 and VP9 as the preferred video send and receive codecs:
`https://appr.tc/?vsc=<CODEC>&vrc=<CODEC>`
You should be able to reproduce the same bug with at least one of these codecs. Make sure to join the same room twice to initialize the chat.

1: https://chromium.googlesource.com/chromium/src/+/refs/tags/74.0.3729.108/chrome/browser/about_flags.cc#1105
2: https://apprtc.appspot.com/params.html

**Comment by Eloston** [comment]
@kabo Also, an update for `intel-media-va-driver` was published not too long ago for version `18.4.1+dfsg1-1`. Could you try updating and see if that changes anything (particularly the `vaGetImage` error)?

**Comment by Eloston** [comment]
@kabo I just released binaries for 74. Could you check to see if this issue still occurs?

**Comment by kabo** [comment]
Hi, sorry for the slow reply, tested it now. Still get the same error.

Downgrading to 72 makes it work normally again.

**Comment by kabo** [comment]
And I'm running version `18.4.1+dfsg1-1` of `intel-media-va-driver`

**Comment by kabo** [comment]
I've tried:

- https://appr.tc/?vsc=VP8&vrc=VP8
- https://appr.tc/?vsc=VP9&vrc=VP9
- https://appr.tc/?vsc=H264&vrc=H264

They all give the exact same error and freeze up after the first frame comes on the screen.

**Comment by kabo** [comment]
I thought I'd build portable chromium from master to see if that works better (v73), but that gives me

```
INFO: * Applying mojo.patch (6/27)
DEBUG: /usr/local/bin/patch -p1 --ignore-whitespace -i /home/kabo/Downloads/ungoogled-chromium-portablelinux/patches/debian_buster/fixes/mojo.patch -d /home/kabo/Downloads/ungoogled-chromium-portablelinux/build/src --no-backup-if-mismatch --forward
patching file content/shell/BUILD.gn
Hunk #1 FAILED at 125.
Hunk #2 FAILED at 289.
2 out of 2 hunks FAILED -- saving rejects to file content/shell/BUILD.gn.rej
can't find file to patch at input line 27
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/content/shell/browser/layout_test/layout_test_content_browser_client.cc
|+++ b/content/shell/browser/layout_test/layout_test_content_browser_client.cc
--------------------------
File to patch:
```

**Comment by Eloston** [comment]
@kabo Debian still has some problems with VA-API decoding in 74.0.3729.108, so I'm wondering if it may be related to your issue. I'm waiting for Debian to publish a new version with these fixes.

> I thought I'd build portable chromium from master to see if that works better (v73)

Portable Linux's `master` branch is broken because the patches aren't updated yet. AFAIK, no one's working on it.

**Comment by Eloston** [comment]
Things have changed a bit since the last version. Portable Linux is now on the latest stable version 75, and Debian is not far behind. If this is still an issue, please let me know.

**Comment by kabo** [comment]
This seems to be resolved, 75 is working fine :)
