### ISSUE TITLE
Download links for Ubuntu 16.04 are 404 on Github (again?)

### ISSUE THREAD

**Issue by RainmakerRaw** [Eloston/ungoogled-chromium#744]
Since there is no contributor binary download available for Ubuntu 19.04 yet, and those for 18.10 don't work (on 19.04), I moved back to 16.04 for now. I had other unrelated reasons too of course (i.e. to not just go back to 18.04 or whatever). I've found 16.04 is very much noticeably faster on my hardware, even though said hardware is an 8700k at 5GHz all core and 32GB DDR4 4133MHz on an NVMe SSD; so I was hoping to keep it for a year or two, until support ends. 

Unfortunately the contributor binaries for 16.04 just lead to a Github 404 page. Can anyone please re-up them or point me in the right direction? I did check out similar issues reported here, but they're closed as the (at the time) version was re-uploaded. The binaries have obviously gone missing again since then.

Cheers.

**Comment by Eloston** [comment]
[19.04 binaries are published](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/ubuntu/disco_amd64/73.0.3683.103-1.disco1). I'm not inclined to get 16.04 binaries back up, since they're really old (and 16.04 is obsolete anyway). I'll remove the old links to prevent further issues.

**Comment by RainmakerRaw** [comment]
Cool, thanks. They weren't up last time I looked, sorry. I was under the impression 16.04 had support until April 2021, though?

**Comment by Eloston** [comment]
> Cool, thanks. They weren't up last time I looked, sorry.

I just published them. No worries :+1: 

> I was under the impression 16.04 had [support until April 2021](https://www.ubuntu.com/about/release-cycle), though?

I see, but what I mean is that the ungoogled-chromium binaries for that version are really old (65.x.x.x). Chromium has changed a lot since then.

**Comment by RainmakerRaw** [comment]
Again, no worries and thanks very much for your reply (and your work on the project). I wasn't referring to the binaries being old, I was referring to:
> (and 16.04 is obsolete anyway).
There's life in the old dog yet haha. No drama, I'll likely be going back to 19.04 anyway and I'm using Saiarcot897's Chromium + VAAPI PPA in the interim.
