### ISSUE TITLE
REQUEST: Version 74.0.3729.108-1 Binary for Arch Linux

### ISSUE THREAD

**Issue by v00v** [Eloston/ungoogled-chromium#745]
Can you please updated binary package for Arch Linux to 74.0.3729.108-1 in
https://ungoogled-software.github.io/ungoogled-chromium-binaries/
Right now newest is 72.0.3626.122-1 Thank You!

**Comment by Eloston** [comment]
The code for 74 was just merged into [ungoogled-chromium-archlinux](https://github.com/ungoogled-software/ungoogled-chromium-archlinux), so it shouldn't be too long from now.

Also, please post issues specifically regarding Arch Linux to ungoogled-chromium-archlinux. Thanks.
