### ISSUE TITLE
libicui18n.so.63: no such file

### ISSUE THREAD

**Issue by v00v** [Eloston/ungoogled-chromium#746]
**Describe the bug**
/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.63: cannot open shared object file: No such file or directory

**To Reproduce**
1. wget https://github.com/rtMis/ungoogled-chromium-binaries/releases/download/72.0.3626.122-1/ungoogled-chromium-72.0.3626.122-1-x86_64.pkg.tar.xz
2. sudo pacman -U ungoogled-chromium-72.0.3626.122-1-x86_64.pkg.tar.xz

**Environment (please complete the following information):**
 - OS/Platform and version: Arch Linux / XFCE
 - ungoogled-chromium version: 72.0.3626.122-1
 - related packages: harfbuzz-icu 2.4.0-2, icu 64.1-1, lib32-icu 60.1-1

**Comment by Eloston** [comment]
Binaries for 73 were just published, so closing this.
