### ISSUE TITLE
Get Ungoogled Chromium In The Official Ubuntu Repo

### ISSUE THREAD

**Issue by trymeouteh** [Eloston/ungoogled-chromium#748]
I do not mind downloading the AppImage but many browsers such as Firefox and Chrome are within the official Ubuntu repo and can be download with a simple few clicks.

But the main reason why I would like to see Ungoogled Chromium in the Ubuntu repo is for more visibility since users will discover this browser over the basic Chromium browser and updates will be automatic and be rolled out right away. Firefox and Chrome updates are frequent on Ubuntu also.

**Comment by Eloston** [comment]
I actually think getting ungoogled-chromium into Debian would be more beneficial, as that would further increase exposure to more distributions. However, both Debian and Ubuntu have the same problem: it requires a maintainer to keep the package up-to-date and ensure the package complies with all their packaging policies (currently, I know almost nothing about them).

I have discussed this in #27, and I think we should continue our discussion there.
