### ISSUE TITLE
Icon change ideas

### ISSUE THREAD

**Issue by nunbit** [Eloston/ungoogled-chromium#750]
I think chromium icon is just so old, ugly and outdated that it needs to be changed even if only in color. 
Lets have a look at browser's colors we have: chromium=blue,edge=blue,every v. of IE=blue, safari=blue, waterfox=blue, most of all icons? Blue. I also hate chrome's red-yellow-green-blue color combination since those are google colors. I think green purple red or black would be interesting.
I want to share with everyone this icon [](url)https://www.deviantart.com/nst-4/art/Google-chrome-icon-by-Nokia-Green-Team-530801044) I like it because it preserves the visual structure of chromium and with a small change in color it looks like a spinning fan. Maybe someone could make an icon like that. Hope I tickled someones pickle.

**Comment by lipici** [comment]
Just my opinion. Needs to reflect what it is in reality. Will be downloaded by kids and see they cant have themes, extensions, log on youtube or idk and will be dumped "that browser is broken and so on" and in same time will be avoided by mature people who will used for real. Needs to be changed but to reflect the real state of browser, not something that is not.

**Comment by Eloston** [comment]
Thanks for the suggestion, but I'm not really interested in rebranding the browser at this time. If ungoogled-chromium keeps growing in features and objectives, then maybe we can consider this more.
