### ISSUE TITLE
Can I compile with Chrome Web Store enabled?

### ISSUE THREAD

**Issue by hellotanuky** [Eloston/ungoogled-chromium#753]
I know this is a silly problem, but I'm tired of downloading crx and installing manually... I wrote a small script to download all extensions I need but I still run it manually. So I tried removing the `domain_substitution` in build.sh and removed the `disable-webstore-urls` but I got no luck. Can I just compile ungoogled-chromium with chrome web store enabled?

**Comment by Eloston** [comment]
If some of the [tips in the FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore) can't help you, then you could try unpacking crx files and installing them as unpacked extensions.

I don't know all of the changes that affect Web Store functionality, so it won't be trivial to re-enable it.
