### ISSUE TITLE
How do I update ungoogled chromnium?

### ISSUE THREAD

**Issue by StringMH** [Eloston/ungoogled-chromium#754]
I really don't now...

**Comment by Eloston** [comment]
It depends on which version you downloaded:

* If you download a Linux distribution package (e.g. `.deb`), then you will need to download new packages and use your distro's recommended way of installing new package files (e.g. `dpkg -i filename.deb` on Debian and derivatives).
* If you downloaded Portable Linux or Windows package, you can just delete the old files and unpack the new files in their place.
* If you downloaded a macOS dmg, it should be whatever standard procedure for installing new dmgs. I don't know much about them, so I can't help you here.
