### ISSUE TITLE
Can someone guide me trough this

### ISSUE THREAD

**Issue by StringMH** [Eloston/ungoogled-chromium#755]
I don't really  know how to install. I got this: https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/67.0.3396.87-3

But it shows up an old version of chrome. Can I update that to the latest version? 

Also, my passwords weren't saving. I mean, I couldn't just save my account for instant access on, let's say, Facebook. Everytime, I had to log in again and again, and that's sort of tidious.

Whan can I do?

**Comment by r4sas** [comment]
Dupe.
Help needed: https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2

**Comment by r4sas** [comment]
>Also, my passwords weren't saving. I mean, I couldn't just save my account for instant access on, let's say, Facebook. Everytime, I had to log in again and again, and that's sort of tidious.

Disable purging cookies at browser exit. See chrome://settings/content/cookies
