### ISSUE TITLE
How do I check for extension updates?

### ISSUE THREAD

**Issue by snakyjake1** [Eloston/ungoogled-chromium#760]
How do I check for extension updates?
How do I get notifications for extension updates?
Is there an easy option to pragmatically get the update and have it installed?

**Comment by hellotanuky** [comment]
If you use binaries from third-party contributors, you can't. You can only download crx files and install them manually.
If you compile by yourself, you can just remove two patches:
1. `core/inox-patchset/0005-disable-default-extensions.patch`
2. `core/iridium-browser/all-add-trk-prefixes-to-possibly-evil-connections.patch`

**Comment by Eloston** [comment]
Yeah, there isn't any mechansim for updates right now. The only fix for this would be #285
