### ISSUE TITLE
Can'd download dependancy to install deb 

### ISSUE THREAD

**Issue by anurag2361** [Eloston/ungoogled-chromium#764]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*

Cant download the file `ungoogled-chromium-common_74.0.3729.136-1.disco1_amd64.deb` from https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/ubuntu/disco_amd64/74.0.3729.136-1.disco1

Shows 'This XML file does not appear to have any style information associated with it.' error.

**Comment by Eloston** [comment]
@riyad It seems you're the author of those builds. Could you check it out?

**Comment by riyad** [comment]
Just found out that this one file was missing from the release: https://github.com/riyad/ungoogled-chromium-binaries/releases/tag/74.0.3729.136-1.disco1. I reuploaded it.

It's weird that the link didn't fail with a `404` instead it had this strange Amazon CDN error. 🤔

**Comment by Eloston** [comment]
Thanks for re-uploading. Closing.
