### ISSUE TITLE
goo.gl domain is not substituted

### ISSUE THREAD

**Issue by biziclop** [Eloston/ungoogled-chromium#765]
Hi, maybe it's a new domain introduced by Google into Chromium, but you might want to consider adding it to the domain substitutions list. I got this (otherwise unrelevant) error message on the console:

`[DOM] Found 2 elements with non-unique id #: (More info: https://goo.gl/9p2vKq)`

Thanks! :)

**Comment by Eloston** [comment]
`goo.gl` domains are for shortened URLs only, so they should pose little to no risk. But it shouldn't hurt to substitute it.

**Comment by qvint** [comment]
@Eloston There are another domains ending with `.google`. Should they be substituted as well?

```
$ grep -rh "\.google/" .
  item.URL = GURL("https://blog.google/products/chrome/");
              GURL("http://url.google/"),
              GURL("http://url.google/icon.png"),
              GURL("http://url.google/favicon.ico"),
      {"https://dns.google/dns-query{?dns}", false /* use_post */}};
              {"https://dns.google/dns-query{?dns}", false /* use_post */}),
      "https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/");
[borg]: https://ai.google/research/pubs/pub43438
```

**Comment by Eloston** [comment]
@qvint Yeah, we should probably add the domains within `.google` explicitly instead of just `.google`, because the latter would probably cause problems. Or, we could have an entry like `http(s?)://([A-Za-z\-]*?\\*?)\.google#http\g<1>://\g<2>.tld-9oo91e.qjz9zk` so that we match HTTP-only URLs.
