### ISSUE TITLE
Question: Easier way to install add-ons?

### ISSUE THREAD

**Issue by TobiasDev** [Eloston/ungoogled-chromium#767]
How does it currently work with add-ons and such. Do I need to update them manually every-time there is an update? Or do they update themself? 

And is there an easier way to add all my add-ons to a new PC? Eg. something like a script I can run on Windows and Linux? Because I will admit I miss chrome a bit, but I really do not want anything Google, so ungoogled chromium is my best bet. :D and the work you are doing here looks amazing, so I'm mostly curios if anyone has figured out a good way to deal with add-ons and updates.

**Comment by r4sas** [comment]
Have you even tried use search before creating issue?

**Comment by TobiasDev** [comment]
I did, all I found was someone praising this software and secondly one talking about syncing, which is not really what I am talking about.

**Comment by r4sas** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/734
https://github.com/Eloston/ungoogled-chromium/issues/735#issuecomment-490638860
https://github.com/Eloston/ungoogled-chromium/issues/760

**Comment by TobiasDev** [comment]
Thanks! I didn't find them when I searched.

**Comment by Eloston** [comment]
> How does it currently work with add-ons and such. Do I need to update them manually every-time there is an update? Or do they update themself?

I just added a section about this to the FAQ in the Wiki.

> And is there an easier way to add all my add-ons to a new PC? Eg. something like a script I can run on Windows and Linux? Because I will admit I miss chrome a bit, but I really do not want anything Google, so ungoogled chromium is my best bet. :D and the work you are doing here looks amazing, so I'm mostly curios if anyone has figured out a good way to deal with add-ons and updates.

No built-in functionality for that. I think most scripts install extensions one at a time.

**Comment by jieggii** [comment]
Hi everyone. I have created [website](https://ungoogled-extension.github.io/), using one you can easily install extensions from Chrome Web Store. I hope it will help someone.
