### ISSUE TITLE
clang: error while loading shared libraries: libLLVM-8.so: cannot open shared object file

### ISSUE THREAD

**Issue by act28** [Eloston/ungoogled-chromium#769]
**Describe the bug**
Fails to build on archlinux, with following error:
```
clang: error while loading shared libraries: libLLVM-8.so: cannot open shared object file: No such file or directory
[13/17710] ACTION //base:base__jumbo_merge(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.
```
**To Reproduce**
1. `yay ungoogled-chromium`

**Expected behavior**
Package installed successfully
**Screenshots**
Nil

**Environment (please complete the following information):**
 - OS/Platform and version: Linux 5.1.4-arch1-1-ARCH
 - ungoogled-chromium version: 72.0.3626.122-1

**Additional context**
Nil

**Comment by Eloston** [comment]
You're using quite an old version and and you seem to be using Arch, so you can try using the PKGBUILD from [ungoogled-chromium-archlinux](https://github.com/ungoogled-software/ungoogled-chromium-archlinux). There is also a temporary(?) ungoogled-chromium-archlinux package in the AUR.
