### ISSUE TITLE
W10 64bit love, finding the contributer

### ISSUE THREAD

**Issue by f4most** [Eloston/ungoogled-chromium#770]
Building is not something I am able.  W10 users are stuck back on v67.  How do I identify the binary contributer to politely request a less old build?

Is it these people? https://github.com/Eloston/ungoogled-chromium/issues/118

**Comment by r4sas** [comment]
Dupe.
Help needed: ungoogled-software/ungoogled-chromium-windows#2

**Comment by arutr** [comment]
You can get the latest Windows build [here](https://chromium.woolyss.com/#windows-64-bit), albeit it has Safe Browsing disabled.

**Comment by r4sas** [comment]
That's not ungoogled-chromium, please dont confuse people.

**Comment by arutr** [comment]
@r4sas the second build is Ungoogled Chromium

**Comment by r4sas** [comment]
> @r4sas the second build is Ungoogled Chromium

Thats why I said "mainly".
