### ISSUE TITLE
Add some easy way for user to tell/confirm they're using ungoogled-chromium

### ISSUE THREAD

**Issue by BillDietrich** [Eloston/ungoogled-chromium#771]
**Is your feature request related to a problem? Please describe.**
Can't be sure I'm running ungoogled-chromium instead of normal chromium.

**Describe the solution you'd like**
Title bar and Help/About box should say "ungoogled-chromium".

**Additional context**
Somewhat related: https://github.com/Eloston/ungoogled-chromium/issues/659

**Comment by Eloston** [comment]
Thanks for the suggestion, but I don't want to make it too visible. I'd rather keep the info contained to one page, otherwise we would need to rebrand the entire browser if we want to keep things consistent.
