### ISSUE TITLE
Install documentation should add a few items

### ISSUE THREAD

**Issue by BillDietrich** [Eloston/ungoogled-chromium#772]
Please add:

- Note somewhere that user must un-install Chromium before installing ungoogled-chromium.

- Note in Download page (at least for Linux) that typical user should install "common" then "browser".

- Note that Linux Mint 19 should use Ubuntu-bionic packages.

**Comment by Eloston** [comment]
I gather that you're referring to the Debian builds. In that case, I'll add the info to the README of ungoogled-chromium-debian.

> Note somewhere that user must un-install Chromium before installing ungoogled-chromium.

The package conflict should already make this clear, but I'll add a note so users will know in advance.

> Note in Download page (at least for Linux) that typical user should install "common" then "browser".

This is not necessary if the packages are installed simultaneously.

> Note that Linux Mint 19 should use Ubuntu-bionic packages.

Will note.
