### ISSUE TITLE
Cannot login on google sites

### ISSUE THREAD

**Issue by wchen342** [Eloston/ungoogled-chromium#773]
**Describe the bug**
When trying to login to google accounts, after typing in account name and hitting "Next" on the "Sign in" page, the page just refreshes itself and does nothing.
Console shows no error and there is no error if started from terminal.

**To Reproduce**
1. Go to 'https://accounts.google.com/ServiceLogin?hl=en'
2. Click on 'Next' or 'Forgot email?' or 'Create account'

**Expected behavior**
Next login page.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version: Arch Linux
 - ungoogled-chromium version: 74.0.3729.169-1

**Additional context**

**Comment by qvint** [comment]
This is caused by your ad blocker.

**Comment by wchen342** [comment]
You are right. I forgot about my ad blocker.
