### ISSUE TITLE
--fingerprinting-canvas-* flags - Enabled or Disabled?

### ISSUE THREAD

**Issue by emanruse** [Eloston/ungoogled-chromium#775]
[flags.md](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md) mentions three `--fingerprinting-canvas-*` flags. When I use them as command line options and then look at them in `chrome://flags` they all show as "Disabled" which implies that their functionality is off.

So it is not clear - should they be set to "Enabled" or "Disabled" in order to use these fingerprint deceptions? (perhaps clarify documentation?)

**Comment by Eloston** [comment]
Huh, never thought about doing that. If you add them to the command-line yourself, I don't think they will show up in `chrome://flags`. I believe the `chrome://flags` mechanism is blind to existing command-line options (which is further supported by the fact that there are `--flag-switches-begin` and `--flag-switches-end` in the complete command-line arguments shown in `chrome://version`). I'll add a note about this to the docs.

Your interpretation is correct about Enabled and Disabled.

**Comment by emanruse** [comment]
Thanks.

> Your interpretation is correct about Enabled and Disabled.

Just to double check I understand this:

So when used through a flag this means:

Enabled - to activate the fingerprint deception function
Disabled - to deactivate

Correct?

Also when used both as a command line argument AND as a flag - which one overrides the other (the argument or the flag)?

**Comment by Eloston** [comment]
> So when used through a flag this means:
> [...]
> Correct?

Yes, that is correct.

> Also when used both as a command line argument AND as a flag - which one overrides the other (the argument or the flag)?

I don't know. I'd assume the flag that appears last will have precedence, but I can't say for sure until we look at the code. You could try it out on a flag with multiple values (because it won't work with flags that are Enabled/Disabled because that just adds/removes it from the command-line arguments).

**Comment by emanruse** [comment]
Tried with another flag. It seems the flag has precedence.
Thanks!
