### ISSUE TITLE
Tab crashes with "Aw, snap!" on LinkedIn

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#778]
**Describe the bug**

The browser will consistently crash with an "Aw, snap!" when visiting LinkedIn. The following error appears in the console:

```
#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffec815b560#0 0x555c7378c1c9 <unknown>
```

I don't have debugging symbols on my browser, so I can't provide additional details at this time.

**To Reproduce**

1. Sign-in to LinkedIn and wait to be redirected
2. See the "Aw, snap!" page
3. At the same time, see the error logged to the console
4. Refresh the page and get the same results as Steps 2 and 3.

**Expected behavior**

**Screenshots**

N/A

**Environment (please complete the following information):**
 - OS/Platform and version: Debian buster amd64
 - ungoogled-chromium version: 75.0.3770.80-1.buster1

**Additional context**

If this turns out to be an issue with our patches, then I think it's finally time we start using automated testing. Otherwise, we will continue to have issues like this one as long as this project continues to grow and evolve.

**Comment by xsmile** [comment]
I can't reproduce the crash on Arch Linux.

**Comment by tonowoe** [comment]
I can reproduce this crash. Debian buster running version 75.

**Comment by Eloston** [comment]
Portable Linux 75.0.3770.80-1.2 is not affected. I'm wondering if Debian's chromium is affected...

I have not yet been able to make a debug build.

**Comment by Eloston** [comment]
Update: I think I've narrowed down the issue to ICU.

NodeJS v12.0.x had the same error as above, and they backported a bugfix from ICU which isn't available in Debian yet (or ICU 63, for that matter).

While their testcase using `new Date().toLocaleString()` for locale `ja` did not cause my browser to crash, the stacktrace from my debug build of an unreleased 75.0.3770.100 for Debian buster suggests that it is an ICU issue, due to the involvement of locales:

```
#0  0x000055555b53e522 in v8::base::OS::Abort() () at ../../v8/src/base/platform/platform-posix.cc:400
#1  0x000055555b53ba55 in V8_Fatal() () at ../../v8/src/base/logging.cc:171
#2  0x0000555558120b58 in ResolveLocale() () at ../../v8/include/v8.h:9016
#3  0x000055555813223c in Initialize() () at ./../../v8/src/objects/js-number-format.cc:261
#4  0x0000555557f61b8b in LegacyFormatConstructor<v8::internal::JSNumberFormat> ()
    at ./../../v8/src/builtins/builtins-intl.cc:286
#5  0x0000555557f61b8b in Builtin_Impl_NumberFormatConstructor() ()
    at ./../../v8/src/builtins/builtins-intl.cc:404
#6  0x0000555558743259 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h:155
#7  0x00005555586b3eda in Builtins_JSBuiltinsConstructStub ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h:155
#8  0x000014ec9265c599 in  ()
#9  0x000014ec9265c599 in  ()
#10 0x0000000700000000 in  ()
#11 0x000036eb5e8405b1 in  ()
#12 0x00002b8b137806a9 in  ()
#13 0x00002b8b137806f9 in  ()
#14 0x000036eb5e8405b1 in  ()
#15 0x0000000200000000 in  ()
#16 0x00003000bf2865b9 in  ()
#17 0x0000000000000022 in  ()
#18 0x00007fff3f7fa2b8 in  ()
#19 0x0000555558796f04 in Builtins_ConstructHandler ()
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h:155
```

This seems plausible from the perspective of other builds, since Arch Linux updates ICU very often, and Portable Linux uses a bundled ICU.

Currently building a new binary to confirm this hypothesis. At least it isn't an issue with our patches I suppose... but I still think we'd need to start using tests at some point in the future.

**Comment by jstkdng** [comment]
Unable to reproduce this bug.
Running Ungoogled Chromium version 75.0.3770.100.
btw i'm using arch

**Comment by tonowoe** [comment]
https://www.theguardian.com/environment/2015/dec/02/worlds-richest-10-produce-half-of-global-carbon-emissions-says-oxfam

This also crashes.

**Comment by Eloston** [comment]
@tonowoe Cannot reproduce on 75.0.3770.100-1.buster1. What version are you running?

**Comment by tonowoe** [comment]
I was running 75.0.3770.80. Now with 75.0.3770.100-1 its working. My bad, didn't notice the updated version.
