### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by zz1616611** [Eloston/ungoogled-chromium#781]
Thank you Please restore Google Translate，Translation function is very important to us

**Comment by Eloston** [comment]
That contradicts the purpose of this browser. If you want to use Google services like Translate, you should consider another browser like Chromium.

**Comment by darkralts** [comment]
what if you make it use yandex.translate.com or something instead? 
idk if thats possible but an idea at least

**Comment by darkralts** [comment]
an alternative would be pretty handy

**Comment by dm17** [comment]
@darkralts @zz1616611 I'm trying to look into a way of doing this - of course without violating the great efforts of ungoogled-chromium. And I'm not saying it should be part of this project, but I think this is a good place to find people who are serious about the functionality:
I'm currently trying to find out if there's an open source way of reading the offline Google Translate packs (some of which are under various OSS licenses). If so, then an extension would be possible. I don't like using Google or Yandex translate on web pages with passwords & credit card information anyway, which there's currently no alternative to that I can see.

**Comment by darkralts** [comment]
that would be very cool

**Comment by kangarko** [comment]
@Eloston maybe as a toggle-able feature? Considering the ease of access and one-click translations this should be allowed to be enabled at your own risk, despite the fact that it's against "ungoogled" principles ;)

**Comment by PF4Public** [comment]
> @Eloston maybe as a toggle-able feature?

A PR would be welcome.

**Comment by dm17** [comment]
I really think we could get offline translation working using the language paks that Google Translate has (on Android, for example). I don't mind if the translation quality is a bit below the quality of the Google API, which it supposedly is... But the added security of using translate at online shopping checkouts, for example, would be well worth it for many to use offline translation. There are a bunch of small groups with some knowledge and motivation for this - but the challenge is getting them collaborated.

@wchen342 - Brave might like something like this; perhaps you know someone we could ping who can look into this?

I realize that not every Google Translate language pak has a compatible license, but some of them do. And there are other offline language paks! :)

**Comment by darkralts** [comment]
offline translate is good

**Comment by dm17** [comment]
https://news.ycombinator.com/item?id=33792447 - some useful discussion for those researching how to implement offline translation

**Comment by trimechee** [comment]
@dm17 Wonderful fantastic ! Thank you very much :)

**Comment by darkralts** [comment]
thank you
