### ISSUE TITLE
SOLVED:  build fail in Arch/Manjaro without:  ninja -j 3 -l 3

### ISSUE THREAD

**Issue by dimyme** [Eloston/ungoogled-chromium#784]
- re-edit:  to build in Manjaro, just modify the ninja line in the PKGBUILD file. Else the build will probably break or even freeze your machine.

----
I understand that MASTER is meant to break during build but what do people have to download to actually successfully build ungoogldCHROM? 

the PKGBUILD did not build for months now... lets call it PKGBREAK....   :1st_place_medal:  lawl

**Comment by jstkdng** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-archlinux

Use that PKGBUILD

**Comment by dimyme** [comment]
no workie , dude !

**Comment by jstkdng** [comment]
you need at least 8gb of ram and a decent cpu in order to build ungoogled chromium. You should also have swap space in case ninja runs out of memory.

**Comment by dimyme** [comment]
have 12 GB ram and a 6-core   but no swap cuz 12G ought to be enuff

**Comment by jstkdng** [comment]
well, guess ninja runs out of memory for all of its workers.

Try editing the PKGBUILD in the part where it actually starts building chromium, in the last part of the build function
```
ninja -C out/Default chrome chrome_sandbox chromedriver
```
Edit that line like this
```
ninja -j (number of threads -1) -l (number of threads - 1) -C out/Default chrome chrome_sandbox chromedriver
```
You can get your number of threads executing nproc. Also, set up a swap file just in case, you can remove it after you are done compiling.

**Comment by dimyme** [comment]
OK I will try that.

**Comment by dimyme** [comment]
wow! that **ninja thread limiter** did the trick! it builds on a 6-core using , I used swap but it probablywasnt necess. now lets see whether my BTRfs SSD with enforced ZStd freezes still like without the thread limiter.

**ninja -j 3   -l 3    -C out/Default chrome chrome_sandbox chromedriver**

**Comment by dimyme** [comment]
the arch package maintainer ought to consider modding the PKGBUILD accordingly.

**Comment by Eloston** [comment]
Alternative suggestion with explanation: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/20#issuecomment-504626827
