### ISSUE TITLE
Microphone access is spotty - Permissions don't matter

### ISSUE THREAD

**Issue by ErictheSandvich** [Eloston/ungoogled-chromium#785]
**Describe the bug**
The Microphone access doesn't want to be friendly to me. I went to Duolingo to do my lessons, and getting to the voice lessons, the moment I clicked the microphone, it was counted incorrect. On the other hand, Vocaroo lets me use the mic no matter if I disable access to that site.

I have disabled all the extensions that I installed (Including uBlock Origin, uMatrix, Smart HTTPS, and TamperMonkey), re-plugged my mic, restarted the browser, made sure that the sites were actually or not getting the permissions, allowed cookies up to pop-ups to appear, and still nothing.

I've looked around here and it seems no one has actually been able to fix or get around this issue. Although, it should be noted that I'm using a USB headphones, and the settings say that it doesn't detect any USB devices. Specifically a Logitech USB Headset.

If I have to assume, ungoogled supresses the microphone by sending denial requests? I'm no coding expert or looked into the source code, I'm just an average joe who looked at this project and said "Ey, a browser! Me likey!"

**To Reproduce**
It doesn't seem anyone specifically has MY issue, so I can't reproduce it for everyone other than "Get a Logitech Headset and go to Duolingo"

**Environment**
 I am using Windows 10 Home edition, and have build 67.0.3396.87 64-bit

**Additional context**
If you want more information, such as what flags are enabled, just ask. I really don't want to hop between browsers just for one thing. I don't need it in Duolingo to survive, but it's preferable.

**Comment by jackhill** [comment]
> To Reproduce
It doesn't seem anyone specifically has MY issue, so I can't reproduce it for everyone other than "Get a Logitech Headset and go to Duolingo"

I'm using the GNU Guix (Linux) package of ungoogled chromium (Version 75.0.3770.142 (Developer Build) (64-bit)), and I can reproduce this issue with duolingo.  Specifically, setting to allow access to the microphone don't seem to stick. In both settings, and the video/microphone icon in the right of the address bar, I am unable to select anything other than blocked. Selecting allowed or ask is immediately changed back to blocked.

Even more specifically, in the site settings menu for https://www.duolingo.com,  the dropdown for the microphone permission says "Block". If I select it as though to change it, I see additional options of "Allow" and "Ask (default)". Selecting "Allow" changes nothing. However, if I select "Ask (default)" then  the options change to "Block (default)", "Allow", and "Block", with "Block (default)" the option in effect. This seems indicate a problem with the permission options for the microphone?

I also have microphone permission options with https://meet.jit.si.

**Comment by Eloston** [comment]
Hmm, must've missed this issue.

This doesn't seem like an ungoogled-chromium issue. Can you check if this affects regular Chromium?

**Comment by jackhill** [comment]
I've checked with chromium as packaged in Debian (Version 73.0.3683.75 (Developer Build) built on Debian buster/sid, running on Debian 10.0 (64-bit)), and the microphone permissions work as expected there.

**Comment by jackhill** [comment]
I just noticed that the Guix packages sets ["audio_capture_enabled": false](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/aux-files/chromium/master-preferences.json#n21). I don't know why this was done, I'll have to follow up to ask.

**Comment by jackhill** [comment]
It looks like my problem with the microphone was indeed related to `"audio_capture_enabled": false` Guix [fixed this setting in their package](https://issues.guix.gnu.org/issue/36961) and the microphone permissions work for me.

The microphone still doesn't work with Duolingo, but I think this is because it depends on a tracker. If I run ungoogled-chromium from the console, I see messages like

```
[11883:11886:0904/222052.856218:ERROR:trk_protocol_handler.cc(17)] Blocked URL in 
                 TrkProtocolHandler: 
trk:184:https://www.9oo91e.qjz9zk/speech-api/full-duplex/v1/down?key=dummytoken&pair=52970E410A529E6C&output=pb
```

As I understand it, that's not a problem with ungoogled-chromium, but a problem with how people are using the web.

**Comment by Eloston** [comment]
@jackhill Glad to hear you figured out the problem, and thanks for discovering the issue with Duolingo. This looks like something useful to add to the FAQ.

**Comment by PEPERSO** [comment]
Hi, I am sorry to reopen this issue, but I just want to add my experience, in case it is useful for somebody.

I had the same probem enabling microphone on meet.jit.si
In chrome://settings/content/microphone, under jitsi authorizations, enabling microphone didn-t do anything, it was reset to "Block" immediately.

To fix this, i had to :

1. Close Chromium
2. Open ./config/chromium/Default/Preferences
3. Set "audio_capture_enabled" to True

Hope it helps someone or corrects a bug for somebody, and thanks for your work !
