### ISSUE TITLE
Clear * data when ungoogled-chromium closes

### ISSUE THREAD

**Issue by maltfield** [Eloston/ungoogled-chromium#791]
**Is your feature request related to a problem? Please describe.**

One reason I don't use chromium is because I could never find a clear way to delete everything when I close the browser, like firefox has.

For example, in Firefox, I can go into the Firefox settings -> Privacy & Security -> History -> Check "Clear history when Firefox closes" -> Settings -> choose all of
  * "Browsing & Download History"
  * "Cookies", "Cache"
  * "Active Logins"
  * "Form & Search History"
  * "Site Preferences", and
  * "Offline Website Data"

AFAICT, there is no way to have Chromium delete all of this data (with the exception of cookies) when it closes. The best I've found is some plugin called "Click & Clean", but that requires the user to click -- I want the data to be deleted automatically when the browser is closed.

**Describe the solution you'd like**

An option should exist (maybe next to the Chromium settings -> Clear browsing data) to clean all data every time Chromium closes.

**Describe alternatives you've considered**

Using addons.

But I just use firefox ¯\(°_o)/¯

**Additional context**

**Comment by jstkdng** [comment]
Yeah, I've always wanted that functionality as well, a good workaround is to change the permissions of the folder where your history is stored and make it read-only.

**Comment by Eloston** [comment]
PRs welcome, but it might be more complicated to implement than it's worth.

**Comment by arutr** [comment]
Doesn't Private mode already do this?

**Comment by emanruse** [comment]
Just clean everything once and stick to using incognito mode only (run the program with `--incognito` command line option).

**Comment by Bt7fdbufffdk** [comment]
you can't open settings, history or bookmarks in an incognito window

**Comment by emanruse** [comment]
> you can't open settings, history or bookmarks in an incognito window

Any site specific settings are not remembered while browsing in incognito. Same applies for history.

Generally the important data needed to restore general and custom settings + profile bookmarks and logins is in:

~/.config/chromium/Default/Preferences
~/.config/chromium/Default/Bookmarks
~/.config/chromium/Default/Favicons
~/.config/chromium/Default/Login Data
~/.config/chromium/Local State

Those are the files I back up.

You can set up a generic empty profile with all your settings - no bookmarks, logins or site specific settings. It will only need

~/.config/chromium/Default/Preferences
~/.config/chromium/Local State

So you can copy those in a separate directory. Then with a simple script you can:

1. Delete ~/.config/chromium/* upon program exit
2. Copy "Default/Preferences" and "Local State" from your generic blank profile to ~/.config/chromium/ before program start.

**Comment by veloute** [comment]
as a workaround, you could use bleachbit to do something like

'chromium && bleachbit -c chromium.history chromium.cookies chromium.form_history chromium.session chromium.session chromium.vacuum`

chromium will run as normal, once exited, bleachbit will delete whatever you've told it to.

**Comment by afliw** [comment]
Couldn't this be achieved with an user script?

**Comment by do-at** [comment]
I think this is a very important feature and its absence keeps many people from using Ungoogled Chromium.

The ability to choose what data to delete upon closing the browser is a standard feature in all mainstream browsers (Google Chrome, Firefox, Edge, Brave, etc.) and for good reason. People want an automated way to stay logged in to the pages they regularly use while also not having the complete browsing history, cache, and whatnot being around somewhere in the background. 

There certainly is a demand for this and seeing that it has become a standard feature in modern browsers I wouldn't say that it is not worth the effort.

**Comment by grande-mephistopheles** [comment]
Is there any progress on this? Right now you can only clean cookies and site data on exit. But *History and Cached data and images* are still stored. I press Ctrl+Shift+Del from time to time but it's getting annoying. This is an essential feature in major browsers.

**Comment by pichongas** [comment]
Chromium has a policy called "SavingBrowserHistoryDisabled" (https://www.chromium.org/administrators/policy-list-3#SavingBrowserHistoryDisabled). Don't know if this can be implemented as a togglable option.

**Comment by Dyrimon** [comment]
So far only Brave browsers has this in all existing chromium browsers. Can this be done by tinkering around in `chrome://flags` ?

**Comment by nullpenguinexception** [comment]
I was just thinking about create a issue for this feature until I see here. It's useful on Brave and other Gecko based browsers. Brave's source code can be helpful to implement this feature.

![image](https://user-images.githubusercontent.com/83981524/120332543-850f1180-c2f7-11eb-9e13-2edcc3afcc59.png)

**Comment by maltfield** [comment]
Thanks @Ahrotahn & @Eloston for finally fixing this!

fwiw, my solution to this has been to wrap chromium in an "ephemeral" self-destructing `firejail`, which means you don't have to trust the browser at all. Details here (also only for linux):

 * https://tech.michaelaltfield.net/2019/03/03/ephemeral-firefox-in-ubuntu-01/

This is also the only way I browse some super-invasive sites (eg google, facebook), using site-specific "ephemeral" browsers:

 * https://tech.michaelaltfield.net/2019/03/26/ephemeral-firefox-as-a-site-specific-browser-03/
