### ISSUE TITLE
WidevineCdm, netflix, not working.

### ISSUE THREAD

**Issue by Innomen** [Eloston/ungoogled-chromium#794]
Portable Google chrome after running netflix once has a folder: GoogleChromePortable\App\Chrome-bin\75.0.3770.100\WidevineCdm

But ungoogled chromium has no directly anlogous folder apparently, though the bin folder looks very similar. Regardless, dropping the WidevineCdm folder in the bin folder does nothing. Dropping the dll/sig in also does nothing.

Under chrome://components/ we find:

Widevine Content Decryption Module - Version: 0.0.0.0
Status - Update error
Check for update

No idea where to go from here.

Yes I know it's a duplicate but since guy keeps closing things instead of addressing them, here we are.

**Comment by jstkdng** [comment]
It works, its just that the chrome and ungoogled chromium have to have the exact same version for the widevine dll to work. AFAIK, windows is still on version 75.0.3770.90 whilst chrome is in version 75.0.3770.100
Try to find a chrome package with that version, it should work, pic related, under linux
![image](https://user-images.githubusercontent.com/52050345/61086443-77e19480-a3f8-11e9-9987-6fd4aaa90331.png)

**Comment by Innomen** [comment]
Thanks, hmmm, I'll try that.

**Comment by Innomen** [comment]
~sigh~ and of course I can't find version "75.0.3770.90"

**Comment by jstkdng** [comment]
you could try to contact that Marmaduke guy to compile the new version, or just compile it yourself. Dunno the instructions for compiling under windows, probably a pain in the ass

**Comment by Innomen** [comment]
https://portableapps.com/downloading/?a=GoogleChromePortable&n=Google%20Chrome%20Portable&s=s&p=&d=pa&f=GoogleChromePortable_75.0.3770.90_online.paf.exe

Managed to get a link to the correct version from portable apps. It should have the correct version.

**Comment by Innomen** [comment]
Once upon a time guy cared about making this work, and apparently once upon a time it worked. I really don't wanna have to abandon the apparently only ungoogled version of chromium. /sigh

**Comment by jstkdng** [comment]
well, this widevine thing affects all chromiums, not just ungoogled chromium.
Literally just downloading chrome and copying dlls is the only way to solve this.

**Comment by Innomen** [comment]
> well, this widevine thing affects all chromiums, not just ungoogled chromium.
> Literally just downloading chrome and copying dlls is the only way to solve this.

Can you (or anyone) tell me what DLLs to copy and where? I have portable chrome that works.

**Comment by jstkdng** [comment]
copy libwidevinecmd.dll to the root of the chromium folder

**Comment by Innomen** [comment]
I don't have that file, I tried copying WidevineCdm.dll to the root dir with the launcher and the bin dir, still nothing. Where did you get that file name/file? Maybe it would work for me?

**Comment by jstkdng** [comment]
That dll has to be in the same directory as the chrome.exe file. Also, I'm currently under linux and I thought it was the same name for windows, apparently it isn't.
Keep in mind that I'm giving you the steps I had to do in linux in order to get widevine, It should be the same for windows, I'm trying to extrapolate since the folder structure for linux and windows are different, pic related.
![2019-07-13_18-37](https://user-images.githubusercontent.com/52050345/61177521-3e965980-a59d-11e9-8c07-27770c53ea1e.png)
So yeah, I just copied the .so file (in your case would be .dll) in the same directory as chromium (in your case chrome.exe). If that doesn't work, try to copy the directory where that dll was originally.

**Comment by Innomen** [comment]
I tried that, like I said above. Guess it's just not possible on windows. /sigh

**Comment by jstkdng** [comment]
Welp, I tried. Maybe someone with windows experience can help.

**Comment by Innomen** [comment]
True. Thanks.

**Comment by Eloston** [comment]
I don't think there's much we can help you with here. Windows support is still broken, and the last working version is really old. You can try asking at the bottom of https://chromium.woolyss.com, since there are probably more Windows users there.

**Comment by Innomen** [comment]
>  Eloston added help wanted  and removed help wanted  labels yesterday
>  Eloston closed this yesterday

Wow...

**Comment by 537** [comment]
Copying the entire WidevineCdm folder to \AppData\Local\Chromium\Application\* and then restarting made Netflix work for me.

**Comment by chaoscreater** [comment]
> ### Easy solution.
> 1. Download New Chromium Portable ([chromium.woolyss.com](https://chromium.woolyss.com))
> 2. Copy the version folder from inside the "**User Data\WidevineCdm**" directory.
> 3. Paste this folder into the Ungoogle-Chromium: "**AppData\Local\Chromium\User Data\WidevineCdm**"

Doesn't work. My Ungoogled Chromium shows widevine support and all codecs enabled, but Netflix still errors. The widevine website video tests all work fine, but Netflix just doesn't work. Works fine on Brave browser though.

https://chromium.woolyss.com/#widevine

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/18227319/8d5300c0-1017-4996-b912-df4e877ac635)
