### ISSUE TITLE
ungoogled-chromium left a "burning" mark in the screen - ArchLinux

### ISSUE THREAD

**Issue by ciciolina** [Eloston/ungoogled-chromium#799]
**Describe the bug**
I install the ungoogled-chromium  version: 75.0.3770.100-1 on Archlinux, all works perfect except for a burning-mark the browser left on my screen, the mark have the form of the address box, a white line rounded the address -box burn my screen and its more visible if i use the browser for a long time.

After go here i test anything, i left my test list:
- update and downgrade xorg and video drivers (reboot after any try)
- mod my screen options (change render, swappiness, buffer and other options)
- change to windows 10 after the burn (i confirm the burn appears here too, after change of OS)
- disable any window animation or option that force screen to render 
- if i shutdown the laptop and wait more than 10min and power up again, the burning disapears but if i use the laptop (using the browser) so much time (more than 4 hours), the mark appears and stay after the shutdown or change of OS.
- if the mark  disapears and i dont use chromium the mark dont apears again, for that reason i know its problem of the browser and not my screen or drivers.

After that i try one more thing, put the browser in "normal" window mode (not maximize the window), and Voila! the browser dont left burning-mark and i can work for 12 hours without any sign of the issue... if i use the full screen works perfect too, but if i use the maximize window option again the error apears.

**To Reproduce**
1. Open chromium
2. Put the window on maximize
3. Browse for 10min o more
4. Close or minimize the browser and see a mark on the screen with the form of the address box

**Expected behavior**
A mark (silouette) of the address box its in the screen (like a burning) and its persistence after reboot (and its visible if you change your OS)

**Screenshots**
- i solve the problem not maximize the window, i dont like put to run the error again because  dont like f#$%.. my screen,  in this moment its working perfect, sorry if i dont put screenshots

**Environment (please complete the following information):**
 - OS/Platform and version:  ArchLinux 5.2.1-arch1-1-ARCH and my DE its Deepin Rolling
 - ungoogled-chromium version: 75.0.3770.100-1 from AUR 

**Additional context**
If you have the same problem dont maximize your browser, put it in "normal" mode, rezise your window and enjoy.

**Comment by jstkdng** [comment]
If it is persisting after a reboot I'd say it is a problem with your display and not with chromium.

**Comment by ciciolina** [comment]
its back... i think its the display but its weird... the line only appears with the siluette of the address box, i put anothers windows and video players and the burn dont appears... but its the display i can confirm that.
