### ISSUE TITLE
Failed Patch: autofill-disable-autofill-download-manager.patch !

### ISSUE THREAD

**Issue by perfect7gentleman** [Eloston/ungoogled-chromium#8]
```
Failed Patch: autofill-disable-autofill-download-manager.patch !
 *  ( /home/user/local_overlay/www-client/chromium/files/ungoogled-chromium/iridium-browser/autofill-disable-autofill-download-manager.patch 
```
```
$ sudo cat /tmp/portage/www-client/chromium-49.0.2623.111/temp/autofill-disable-autofill-download-manager.patch.out
***** autofill-disable-autofill-download-manager.patch *****
PWD: /tmp/portage/www-client/chromium-49.0.2623.111/work/chromium-49.0.2623.111
PATCH TOOL: patch -> /usr/bin/patch
VERSION INFO:
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

============================================================

PATCH COMMAND:  patch -p0 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/home/perfect_gentleman_007/local_overlay/www-client/chromium/files/ungoogled-chromium/iridium-browser/autofill-disable-autofill-download-manager.patch'

============================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From e02b16d3c278d09d68c3d93723659e9e306e442c Mon Sep 17 00:00:00 2001
|From: Jan Engelhardt <jengelh@inai.de>
|Date: Thu, 11 Sep 2014 16:37:32 +0200
|Subject: [PATCH 09/57] autofill: disable autofill download manager
|
|Disables the autofill download manager (trk:158).
|---
| components/autofill/core/browser/autofill_download_manager.cc | 2 +-
| components/autofill/core/browser/autofill_manager.cc          | 2 ++
| 2 files changed, 3 insertions(+), 1 deletion(-)
|
|diff --git a/components/autofill/core/browser/autofill_download_manager.cc b/components/autofill/core/browser/autofill_download_manager.cc
|index 45f1e95..c99e8a7 100644
|--- a/components/autofill/core/browser/autofill_download_manager.cc
|+++ b/components/autofill/core/browser/autofill_download_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/components/autofill/core/browser/autofill_manager.cc b/components/autofill/core/browser/autofill_manager.cc
|index 4c346f6..40fd35c 100644
|--- a/components/autofill/core/browser/autofill_manager.cc
|+++ b/components/autofill/core/browser/autofill_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
============================================================

PATCH COMMAND:  patch -p1 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/home/perfect_gentleman_007/local_overlay/www-client/chromium/files/ungoogled-chromium/iridium-browser/autofill-disable-autofill-download-manager.patch'

============================================================
checking file components/autofill/core/browser/autofill_download_manager.cc
Hunk #1 FAILED at 87.
1 out of 1 hunk FAILED
checking file components/autofill/core/browser/autofill_manager.cc

patch program exited with status 1
============================================================

PATCH COMMAND:  patch -p2 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/home/perfect_gentleman_007/local_overlay/www-client/chromium/files/ungoogled-chromium/iridium-browser/autofill-disable-autofill-download-manager.patch'

============================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From e02b16d3c278d09d68c3d93723659e9e306e442c Mon Sep 17 00:00:00 2001
|From: Jan Engelhardt <jengelh@inai.de>
|Date: Thu, 11 Sep 2014 16:37:32 +0200
|Subject: [PATCH 09/57] autofill: disable autofill download manager
|
|Disables the autofill download manager (trk:158).
|---
| components/autofill/core/browser/autofill_download_manager.cc | 2 +-
| components/autofill/core/browser/autofill_manager.cc          | 2 ++
| 2 files changed, 3 insertions(+), 1 deletion(-)
|
|diff --git a/components/autofill/core/browser/autofill_download_manager.cc b/components/autofill/core/browser/autofill_download_manager.cc
|index 45f1e95..c99e8a7 100644
|--- a/components/autofill/core/browser/autofill_download_manager.cc
|+++ b/components/autofill/core/browser/autofill_download_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/components/autofill/core/browser/autofill_manager.cc b/components/autofill/core/browser/autofill_manager.cc
|index 4c346f6..40fd35c 100644
|--- a/components/autofill/core/browser/autofill_manager.cc
|+++ b/components/autofill/core/browser/autofill_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
============================================================

PATCH COMMAND:  patch -p3 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/home/perfect_gentleman_007/local_overlay/www-client/chromium/files/ungoogled-chromium/iridium-browser/autofill-disable-autofill-download-manager.patch'

============================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From e02b16d3c278d09d68c3d93723659e9e306e442c Mon Sep 17 00:00:00 2001
|From: Jan Engelhardt <jengelh@inai.de>
|Date: Thu, 11 Sep 2014 16:37:32 +0200
|Subject: [PATCH 09/57] autofill: disable autofill download manager
|
|Disables the autofill download manager (trk:158).
|---
| components/autofill/core/browser/autofill_download_manager.cc | 2 +-
| components/autofill/core/browser/autofill_manager.cc          | 2 ++
| 2 files changed, 3 insertions(+), 1 deletion(-)
|
|diff --git a/components/autofill/core/browser/autofill_download_manager.cc b/components/autofill/core/browser/autofill_download_manager.cc
|index 45f1e95..c99e8a7 100644
|--- a/components/autofill/core/browser/autofill_download_manager.cc
|+++ b/components/autofill/core/browser/autofill_download_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/components/autofill/core/browser/autofill_manager.cc b/components/autofill/core/browser/autofill_manager.cc
|index 4c346f6..40fd35c 100644
|--- a/components/autofill/core/browser/autofill_manager.cc
|+++ b/components/autofill/core/browser/autofill_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
============================================================

PATCH COMMAND:  patch -p4 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/home/perfect_gentleman_007/local_overlay/www-client/chromium/files/ungoogled-chromium/iridium-browser/autofill-disable-autofill-download-manager.patch'

============================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From e02b16d3c278d09d68c3d93723659e9e306e442c Mon Sep 17 00:00:00 2001
|From: Jan Engelhardt <jengelh@inai.de>
|Date: Thu, 11 Sep 2014 16:37:32 +0200
|Subject: [PATCH 09/57] autofill: disable autofill download manager
|
|Disables the autofill download manager (trk:158).
|---
| components/autofill/core/browser/autofill_download_manager.cc | 2 +-
| components/autofill/core/browser/autofill_manager.cc          | 2 ++
| 2 files changed, 3 insertions(+), 1 deletion(-)
|
|diff --git a/components/autofill/core/browser/autofill_download_manager.cc b/components/autofill/core/browser/autofill_download_manager.cc
|index 45f1e95..c99e8a7 100644
|--- a/components/autofill/core/browser/autofill_download_manager.cc
|+++ b/components/autofill/core/browser/autofill_download_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/components/autofill/core/browser/autofill_manager.cc b/components/autofill/core/browser/autofill_manager.cc
|index 4c346f6..40fd35c 100644
|--- a/components/autofill/core/browser/autofill_manager.cc
|+++ b/components/autofill/core/browser/autofill_manager.cc
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
```

**Comment by Eloston** [comment]
Are your patches applying relative to the root of the Chromium source tree? Did you remove any files beforehand? I just published 49.0.2623.111, so it should work.

**Comment by perfect7gentleman** [comment]
yes, of course

**Comment by Eloston** [comment]
From your build log with `-p1`:
```
checking file components/autofill/core/browser/autofill_download_manager.cc
Hunk #1 FAILED at 87.
1 out of 1 hunk FAILED
checking file components/autofill/core/browser/autofill_manager.cc
```
If you applied the Iridium patches against a clean source tree, it should apply cleanly.

**Comment by perfect7gentleman** [comment]
if orginal Iridium patches are applied, it's okay. But as i understood you sllightly modify Iridium and Inoc patches, and they cannot be applied in my case.

**Comment by perfect7gentleman** [comment]
i ran domain_patcher.sh, and patches were magically applied.

**Comment by Eloston** [comment]
Ah yeah I forgot about that. :P Glad you figured it out.

**Comment by perfect7gentleman** [comment]
also, it is needed to run source_cleaner.sh

**Comment by Eloston** [comment]
No, only `domain_patcher.sh` is needed. `source_cleaner.sh` only removes files.

**Comment by perfect7gentleman** [comment]
without source_cleaner.sh i get error at the very end of compilation

**Comment by Eloston** [comment]
Interesting. What kind of error?

**Comment by perfect7gentleman** [comment]
ninja: error: loading 'build.ninja'

**Comment by Eloston** [comment]
Is that all it says? At what point did you run `source_cleaner.sh`?

**Comment by perfect7gentleman** [comment]
yep, that's all
I ran it at the beginning before domain_patcher.sh and applying the patches

**Comment by Eloston** [comment]
Is that the only error shown during the build? Usually the actual error shows up before that line.

**Comment by perfect7gentleman** [comment]
it is the only one. no errors before that.

**Comment by perfect7gentleman** [comment]
there is ebuild modified. you can take a look.
https://github.com/perfect7gentleman/pg_overlay/blob/master/www-client/chromium/chromium-49.0.2623.111.ebuild

**Comment by perfect7gentleman** [comment]
-Dsafe_browsing=0
		-Dremoting=0
		-Denable_prod_wallet_service=0

**Comment by perfect7gentleman** [comment]
1. No source_cleaner.sh, but 
-Dsafe_browsing=0
-Dremoting=0
-Denable_prod_wallet_service=0

Compilation successful.

2. source_cleaner.sh, but no 
-Dsafe_browsing=0
-Dremoting=0
-Denable_prod_wallet_service=0

Compilation failed
`FAILED: x86_64-pc-linux-gnu-g++ -MMD -MF obj/chrome/browser/extensions/browser_extensions.blacklist.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D_FILE_OFFSET_BITS=64 -DDISABLE_NACL -DCHROMIUM_BUILD -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_TOPCHROME_MD=1 -DUSE_UDEV -DDONT_EMBED_BUILD_METADATA -DTRACING_IS_OFFICIAL_BUILD=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_HANGOUT_SERVICES_EXTENSION=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DGL_GLEXT_PROTOTYPES -DMOJO_USE_SYSTEM_IMPL -DUSE_SYSTEM_MINIZIP -DTOOLKIT_VIEWS=1 -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DSK_SUPPORT_GPU=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DU_USING_ICU_NAMESPACE=0 -DI18N_ADDRESSINPUT_USE_BASICTYPES_OVERRIDE=1 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_LINUX -DWEBRTC_POSIX -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen/shim_headers/libflac/target -Igen/shim_headers/snappy/target -Igen/shim_headers/libpng/target -Igen/shim_headers/harfbuzz-ng/target -Igen/shim_headers/zlib/target -Igen/shim_headers/icuuc/target -Igen/shim_headers/icui18n/target -Igen/shim_headers/libevent/target -Igen -I../.. -Iobj/chrome/browser_extensions.gen -Iobj/chrome/browser_extensions.gen/chrome -I../../third_party/khronos -I../../gpu -I../../skia/config -Igen/angle -I../../third_party/WebKit/Source -Igen/chrome -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../third_party/dom_distiller_js/dist/proto_gen -Igen/components/strings -Igen/content/app/resources/ -I../../third_party/WebKit -Igen/extensions -Igen/extensions/strings -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -I../../third_party/re2/src -I../../third_party/libaddressinput/chromium/override -I../../third_party/libaddressinput/src/cpp/include -Igen/third_party/libaddressinput/ -I../../third_party/webrtc_overrides -I../../third_party -Igen/ui/resources -Igen/ui/keyboard -Igen/ui/views/resources -Igen/policy -fstack-protector --param=ssp-buffer-size=4  -pthread -fno-strict-aliasing -Wall -Wno-extra -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -march=native -mtune=native -O3 -pipe -fomit-frame-pointer -fno-stack-protector -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-narrowing  -c ../../chrome/browser/extensions/blacklist.cc -o obj/chrome/browser/extensions/browser_extensions.blacklist.o
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
../../chrome/browser/extensions/blacklist.cc: In constructor ‘extensions::{anonymous}::LazySafeBrowsingDatabaseManager::LazySafeBrowsingDatabaseManager()’:
../../chrome/browser/extensions/blacklist.cc:42:49: error: ‘class BrowserProcess’ has no member named ‘safe_browsing_service’
     if (g_browser_process && g_browser_process->safe_browsing_service()) {
                                                 ^
../../chrome/browser/extensions/blacklist.cc:44:30: error: ‘class BrowserProcess’ has no member named ‘safe_browsing_service’
           g_browser_process->safe_browsing_service()->database_manager();
                              ^
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
ninja: build stopped: subcommand failed.`

**Comment by Eloston** [comment]
[This patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/ungoogled-chromium/fix-building-without-safebrowsing.patch) assumes that Chromium is built with `safe_browsing=0`. The fact that the built went fine with the proper GYP flags without `source_cleaner.sh` proves that `source_cleaner.sh` is not necessary to build ungoogled-chromium.

**Comment by perfect7gentleman** [comment]
I assumed that Inox-patchset uses safe_browsing=0. But I see safe_browsing_mode=0, and they are different options.
Do you recommend to use source_cleaner.sh for other distros or not ?

**Comment by Eloston** [comment]
`source_cleaner.sh` is for deleting binary files residing in the source tree. As long as your build flags do not depend on any of the binaries deleted by `source_cleaner.sh`, then it won't hurt to use it.

**Comment by perfect7gentleman** [comment]
according to https://chromium.googlesource.com/chromium/src.git/+/master/build/common.gypi, there is no such flag safe_browsing_mode=0

**Comment by Eloston** [comment]
`safe_browsing_mode` may have been the name of the flag before. Thanks for checking again to confirm that the `safe_browsing` flag still exists.
