### ISSUE TITLE
Please give definitions of the package types (common, driver, shell, etc)

### ISSUE THREAD

**Issue by BillDietrich** [Eloston/ungoogled-chromium#802]
On every "Download' page such as https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/ubuntu/bionic_amd64/72.0.3626.122-3.bionic1 , please give definitions of what the various packages mean.  I'm unsure if I should download common, driver, shell, or the one with no particular tags in the name (ungoogled-chromium_72.0.3626.122-3.bionic1_amd64.deb).  Thanks.

**Comment by Eloston** [comment]
Fixed with https://github.com/ungoogled-software/ungoogled-chromium-binaries/commit/ed3a222143cd047545ad841db11714c3e9f29cd1 and following commits.
