### ISSUE TITLE
Does not retain login?

### ISSUE THREAD

**Issue by Merith-TK** [Eloston/ungoogled-chromium#803]
Im using the windows build of ungoogled 
https://i.imgur.com/mnD7upj.png

the issue im having is, when i close chromeium, i am logged out of everything, and have to relog back in, I can save passwords, login info, extensions. pretty much everything else works, 

but when i hit that red X in the top right. i am logged out of EVERYTHING.

Any ideas?

**Comment by jstkdng** [comment]
ungoogled chromium clears all cookies on close.
Just change that option in the settings

**Comment by Merith-TK** [comment]
Yeah that fixed it, thanks
