### ISSUE TITLE
Installing and Launching Ungoogled-Chromium Portable Linux - Best Practice

### ISSUE THREAD

**Issue by jlj2** [Eloston/ungoogled-chromium#805]
1. In order to reduce the possibility of remote hacking in cases where no other user would be formally granted access on an installation, would it be more secure to install Ungoogled-Chromium Portable Linux:-

(a) in a root folder, say, `/opt/`, as following; 
`$ cd ~/Downloads`
`$ wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/75.0.3770.80-1.2/ungoogled-chromium_75.0.3770.80-1.2_linux.tar.xz`
	Check sums by comparing the outputs for the following with the sums at UC's download webpage:
	`$ md5sum ungoogled-chromium_75.0.3770.80-1.2_linux.tar.xz`
	`$ sha1sum ungoogled-chromium_75.0.3770.80-1.2_linux.tar.xz`
	`$ sha256sum ungoogled-chromium_75.0.3770.80-1.2_linux.tar.xz`
	Unpack it:
	`$ sudo tar -xvf ungoogled-chromium_75.0.3770.80-1.2_linux.tar.xz   -C /opt`

(b) in a user folder, say, `/home/yourusername/opt/` ?

SUGGESTION No. 1:  Instructions such as the above for newcomers to Linux and to UC Linux Portable might be useful, maybe in a new 'Installing binaries - Portable Linux' section in the Instructions [FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq) and in the [README.md](https://github.com/Eloston/ungoogled-chromium/blob/master/README.md).  I am not techie and am not currently planning on learning how to do request a PR...

2. Once installed, UC Portable Linux offers a _README_ file e.g. under `/opt/ungoogled-chromium_75.0.3770.100-1.2_linux/README` that assesses your sandboxing requirements:

"Before you run, you must setup your system so the browser's sandboxing will work. There are two options:
- Use the user namespace sandbox. This is the preferred option.
- Use the SUID sandbox. This should be used on systems that do not have support for user namespaces.
[...]"

SUGGESTION No. 2:  IMHO, it might be helpful for users if there could also be the following added guidance in that README file (and in the installation instructions webpage):

"To quickly determine a relevant aspect of your current sandboxing setup:
1. Launch UC temporarily from a terminal:
/opt/ungoogled-chromium_75.0.3770.80-1.1_linux/chrome   (??) 
2. Navigate to the following url:
chrome://sandbox/

Your screen may declare, in part:
"Sandbox Status
Layer 1 Sandbox           Namespace
PID namespaces           Yes
[...]
You are adequately sandboxed."

In that case, if I understood correctly, there would be a 'Namespace' sandbox already set up, and the following from the README file would apply:
"Once the sandbox is setup, the browser can be run by using the chrome-wrapper script."

The alternative scenario, mentioned above, is the use of SUID sandboxing whereby one has to _"Rename "chrome_sandbox" to "chrome-sandbox""_ and take other steps.  

Could launching UC as `/opt/ungoogled-chromium/chrome` be a relevant option for general use?  (A [screen recording](https://github.com/Eloston/ungoogled-chromium/issues/783#issuecomment-511238237) was very kindly offered for an unrelated issue where UC is apparently launched that way, and this is a more intuitive path than `.../chrome-wrapper` or `.../chrome-sandbox`.)

**Comment by jlj2** [comment]
SUGGESTION No. 3: Maybe the README file could be improved slightly, as currently the README might be interpreted to conclude that 'chrome-wrapper' is to be used in all cases:
	_"Running the browser:
	Once the sandbox is setup, the browser can be run by using the chrome-wrapper script."_

Perhaps the following wording could be used instead with added instructions on creating a simple link:
	_"Running the browser:
	Once the sandbox is setup, a handy link could be set up, depending on the sandbox chosen:"_
`	sudo mkdir /opt/ungoogled-chromium/`
`	sudo ln -s /opt/ungoogled-chromium_75.0.3770.100-1.2_linux/chrome-wrapper /opt/ungoogled-chromium/chrome-wrapper
`	_OR:_
	`sudo mkdir /opt/ungoogled-chromium/`
	`sudo ln -s /opt/ungoogled-chromium_75.0.3770.100-1.2_linux/chrome-sandbox /opt/ungoogled-chromium/chrome-sandbox`
	_As the case may be, UC could then be simply launched as_ `/opt/ungoogled-chromium/chrome-wrapper` _OR_ `/opt/ungoogled-chromium/chrome-sandbox`

Thank you for any help in advance!

**Comment by Eloston** [comment]
You might be able to edit the file without creating a PR manually. Does this link work for you?: https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/edit/master/README.md

Otherwise, I'd be open to others submitting PRs. I'm not sure if/when I can update the docs.

**Comment by jlj2** [comment]
The edit was done.  
Instructions on how to set up soft links may be out of place for that README page so were thought not to included, as currently there are so many instructions for other builds there already. 
I'm not sure whether _"PID namespaces Yes"_ needs to be displayed by _chrome://sandbox/_ to confirm a namespace sandbox;  I kept it in to be safer - anyone?
A PR request could perhaps be made for the README in the packaged version, but eventually I plan to figure out how to make that!  Thanks again, @Eloston!

**Comment by Eloston** [comment]
@jlj2 You can edit your PR and modify the file `tar_includes/README`. Also, there's a pencil icon on the top right of files you view, which is how I got that link above.

**Comment by jlj2** [comment]
Done, thank you!
