### ISSUE TITLE
Windows build is too old

### ISSUE THREAD

**Issue by WrongBit** [Eloston/ungoogled-chromium#808]
Guys, what's happen to windows builds? (esp. 64bit) Latest one is v.67, while actual is v.75; Is it hard procedure to build? Anything is broken in automated build? Please clarify should we expect new releases. It's highly desirable to have actual browser w/o google's hooks.

**Comment by leo-lb** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2

**Comment by Eloston** [comment]
Progress is being made to update, but it's not an easy problem.
