### ISSUE TITLE
HTTP Error 404 when fetching the Chromium 76.0.3809.100 source

### ISSUE THREAD

**Issue by Zoraver** [Eloston/ungoogled-chromium#809]
**Describe the bug**
As the first step toward updating ungoogled-chromium to Chromium 76.0.3809.100, I changed the contents of chromium_version.txt to 76.0.3809.100. When I tried to use `./utils/downloads.py` to retrieve the Chromium 76.0.3809.100 source, I get an HTTP Error 404.

**To Reproduce**
1. Change the contents of chromium_version.txt to 76.0.3809.100
2. Run `./utils/downloads.py retrieve -i downloads.ini -c build/download_cache/`

**Expected behavior**
A tarball of the source of Chromium 76.0.3809.100 is downloaded into the build/download_cache/ directory

**Environment (please complete the following information):**
 - OS/Platform and version: Fedora 30
 - ungoogled-chromium version: 76.0.3809.100 ;)

**Additional context**
There are two possibilities. Either Google just hasn't gotten around to posting the source, or the way that they distribute the source has changed. Typically, they post the source to `https://commondatastorage.googleapis.com/chromium-browser-official/` within a few hours, and it has been two days since the release of Chrome 76.0.3809.100.

**Comment by Eloston** [comment]
Interesting. The largest impact of this is on Linux distro packagers; I wonder if they've found anything. Maybe there's Google Groups thread about it?

**Comment by Zoraver** [comment]
This was apparently caused by issues with the chromium publish_tarball bot: https://bugs.chromium.org/p/chromium/issues/detail?id=990747. It seems that the source should be up soon; I will close this issue once it is posted.

**Comment by Zoraver** [comment]
The source has been posted, so I am closing this issue.
