### ISSUE TITLE
A way to hide recently visited pages?

### ISSUE THREAD

**Issue by sixtyfive** [Eloston/ungoogled-chromium#81]
Is there a way to hide the thumbnails of recently visited pages shown when opening a new tab? I suffer from ADDH and find these suggestions to disturb my workflow. Normally you'd use an extension for getting rid of them, but the ones I tried seem to be broken in ungoogled-chromium...

**Comment by stfnhrrs** [comment]
You could install this extension https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij follow these [instructions](https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#can-i-install-extensions-from-the-chrome-webstore) to install it.  I can confirm this extension is working on OS X.

**Comment by sixtyfive** [comment]
I didn't know that one, thank you! Here's the download command if anybody else wants to get it without first having to look up the download URL scheme: `wget -c https://clients2.google.com/service/update2/crx?response=redirect\&prodversion=48.0\&x=id%3Ddpjamkmjmigaoobjbekmfgabipmfilij%26installsource%3Dondemand%26uc -O emptynewtab.crx`.

**Comment by tossivahva** [comment]
According to the [doc](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#available-only-on-desktop), there is kind of a new flag that handle this behavior, so you don't need additional plugins anymore: 

`--disable-top-sites `  Disables the top sites and most visited entries on the new tab page.

- Go to chrome://flags/#disable-top-sites
- Enable `disable-top-sites` flag

<img width="1371" alt="Screenshot 2024-05-12 at 12 59 53 PM" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/50559009/781743a9-b8f2-45ad-8504-5f1ac5a5f562">
