### ISSUE TITLE
libevent-2.1.11-1 broke chromium

### ISSUE THREAD

**Issue by thegergo02** [Eloston/ungoogled-chromium#811]
The error is:
`/usr/lib/chromium/chromium: error while loading shared libraries: libevent-2.1.so.6: cannot open shared object file: No such file or directory`

Downgrading to libevent-2.1.10-1 fixes the issue.

Chromium version: 75.0.3770.100-1

**Comment by jstkdng** [comment]
in those cases you have to recompile chromium for the new version of libevent

**Comment by Eloston** [comment]
@thegergo02 We don't support running binaries outside of the environment they support. In this particular scenario, @jstkdng's advice will work, but it may not continue to work as the distro versions diverge. Another option is to use Portable Linux.
