### ISSUE TITLE
Google account logging out after I close the browser

### ISSUE THREAD

**Issue by dave-dm** [Eloston/ungoogled-chromium#812]
I'm not sure why but it appears with the ungoogled chromium version I get logged out of my google account very often after I close the browser. Anyone knows why that happens? In theory the cookies should still be in my profile folder and I shouldn't have to re-login all the time.

**Comment by jstkdng** [comment]
ungoogled chromium by default clears all cookies after you close the browser.

**Comment by dave-dm** [comment]
oh that makes sense, is there a way to keep them?

**Comment by jstkdng** [comment]
Change that option in the settings
![image](https://user-images.githubusercontent.com/52050345/63035981-cfed3a00-be81-11e9-8c6d-f265b2f8954f.png)

**Comment by dave-dm** [comment]
> Change that option in the settings
thanks but I'm actually trying to do it programmatically. I'm looking into preference files at the moment but I'm not sure what the setting is called or which preference file is the correct one https://www.forensicswiki.org/wiki/Google_Chrome

**Comment by Eloston** [comment]
@dave-dm It's probably stored in the `Preferences` file, which is just a serialized JSON text file. You could try pretty-formatting the JSON before and after changing the setting, and doing a text diff to see what JSON key(s) changed.

**Comment by dave-dm** [comment]
yes I did try `Preferences` and it was indeed working but in the end policies ended up a better option for me but if someone else needs to try the settings to add were:
```
{"profile":{"block_third_party_cookies":false,"default_content_setting_values":{"cookies":1}}}
```

**Comment by Eloston** [comment]
Closing because issue is solved.

**Comment by dhruvdewangupta** [comment]
What does this have to do with "ungoogling" Chromium? Can you please explain the logic behind this stupid setting?
