### ISSUE TITLE
Video playback broken

### ISSUE THREAD

**Issue by aksel** [Eloston/ungoogled-chromium#817]
**Describe the bug**
I am unsure if this is related to ungoogled-chromium directly, but it doesn't happen on regular chromium.

Video playback seems to be broken, and it seems to be a graphics driver issue. **Edit: Disabling hardware acceleration via --disable-gpu will let me play videos again. But that's not ideal, because all performance goes out the window.**

I have tried mp4s and webms, and YouTube. The videos do appear to buffer, but there's no playback.

The following error happens on launch, and sometimes when I open a video.
`
ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
`
**Edit: It should be noted, the error above also happens on regular Chromium, where videos still work.**

**To Reproduce**
1. Open any video _on my machine lol_
2. Nothing happens. 

**Expected behavior**
Playback.

**Environment (please complete the following information):**
 - OS/Platform and version: Arch Linux. Dell XPS 13 (9370), Intel UHD Graphics 620
 - WM: i3-gaps-next. No compositor.
 - ungoogled-chromium version: 76.0.3809.100 (Developer Build) Arch Linux (64-bit)
 - revision: ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}

**Additional context**
[Output from chrome://gpu](https://pastebin.com/raw/tvmScGnw)

I am unsure on how to debug and fix this, so any help is greatly appreciated.

**Comment by atelosotaar** [comment]
You could try running chromium with arg: `--v=99` but expect a ton of console output... or you could try `--v=1` for way less output... Just an idea :)

There's also `--log-level=2` and `--vmodule=device_event_log*=1` which I see in my `ps axuw` output, but I haven't tried to figure out how they work or lookup.

**Comment by Eloston** [comment]
I can also confirm @jstkdng's fork's VA-API changes works well. I've already included it in ungoogled-chromium-debian.

**Comment by aksel** [comment]
Fantastic, I will try your fork and report back tonight

**Comment by aksel** [comment]
It works! Thank you all ~~~

**Comment by loficat** [comment]
I'm here from the future to relay that the issue still exists.  After updating Ungoogled Chromium yesterday, I've been treading water until coming across this page.  Every video would stop at 19 seconds.  Turning off hardware acceleration resolved the issue, so now I have a place to start.  Out of curiosity, with hardware acceleration enabled, I attempted to play videos via other online methods and didn't encounter this issue.  YouTube video playback is the only context in which I've encountered this issue to date.

**Comment by PF4Public** [comment]
@loficat Your issue is this one: https://github.com/ungoogled-software/ungoogled-chromium/issues/3012

**Comment by loficat** [comment]
@PF4Public Thank you for your response.  Unfortunately (and unless I missed something), that wasn't the issue.  This typed, while the issue persists, after 4 years of Ungoogled Chromium tinkering, I've decided to evaluate other browsers (flavors of LibreWolf, Brave, etc.).

**Comment by aksel** [comment]
@loficat My issue was that videos refused to start playing, whereas this sounds like a different issue. It's always 19 seconds?

Shot in the dark here, but maybe that means it manages to buffer a chunk(?)or two or video. Like, it loads seconds 0 through 9, and then 10 through 19, and then fails on the third. Or 0 through 19, and then fails on the second.

Maybe it's a total red herring, but the specificity of it being 19 seconds was the first thing that stood out to me.
