### ISSUE TITLE
The inability to have a normal chromium with ungoogled-chromium on one system

### ISSUE THREAD

**Issue by Xasweil** [Eloston/ungoogled-chromium#82]
Has anyone found a way to have the usual **chromium** for a windows with **ungoogled-chromium** on the one system? When i start **ungoogled-chromium**, starts the usual **chromium**, which is installed in the system. I would like to have both browsers.

**Comment by Eloston** [comment]
Huh. I've never installed Chromium via the installer before, so I never knew about this behavior.

What happens if you launch ungoogled-chromium with a different path for the user data directory?

**Comment by Xasweil** [comment]
**Eloston**, it works, but when i launch browser opens "http://chromium/cache" page instead of the home page. I use _--user-data-dir=c:\users\vladimir\other\ungoogled chromium\cache_ in shortcut configuration

**Comment by Eloston** [comment]
You need to use quotes around the path, otherwise cmd will interpret the space as the end of an argument instead of being part of the path. Right now, your profile is located in `c:\users\vladimir\other\ungoogled`

**Comment by Xasweil** [comment]
**Eloston**, yes, now everything works as it should. Thank you!
