### ISSUE TITLE
Verbosity levels

### ISSUE THREAD

**Issue by PF4Public** [Eloston/ungoogled-chromium#820]
**Is your feature request related to a problem? Please describe.**
<s>I'm always frustrated when there is a lot of output from patching and substituting scripts.</s>
The logger starts with DEBUG by default. This provides a lot of output.

**Describe the solution you'd like**
It would be of most use, if by default the logger would print only INFO messages.

Also it would be great to have `-q, --quiet` for absolute quiet except for errors and `-v, --verbose` for INFO _and_ DEBUG messages.

**Comment by wchen342** [comment]
A related but slightly different problem: when I use `prune_binaries.py` in my android build, it always prints out a full list of files it cannot find, which is unformatted and extremely long. I just had a look at the code and it is logged at _ERROR_ level so that list will always be printed. It is probably better to only log number of files not found at _ERROR_ level and leave the whole list to _DEBUG_ level.

**Comment by Eloston** [comment]
@wchen342 Yeah, these are the kinds of design choices in logging levels that I'm looking for. Would you be able to submit a PR for this change?

I'm not too experienced in creating effective logging (i.e. high signal-to-noise ratio). At some point, we should find/develop some rough guidelines for logging levels so we can update all tools the same way.

**Comment by Eloston** [comment]
With #831, all that's left is to add a flag to change the log level. Perhaps we should add some function to `_common.py` to add common flags and callbacks in all utilities?

**Comment by wchen342** [comment]
For now it seems the only common flags will be the log level ones? It may still worth the abstraction for future use though. I can add a function say `add_common_flags(parser)` to `_common.py` and call it in other scripts. Does this sound good?

**Comment by Eloston** [comment]
@wchen342 Yep, that sounds good to me. Also yes, the log level ones should be the only common flags right now, but I don't think it will be the only flag that we will add. Perhaps we may want to add a log file path flag in the future, or even something not logging-related.

**Comment by Eloston** [comment]
This is fixed with #832. We should create new issues for any other tool that can have better logging.
