### ISSUE TITLE
Google's DNS-Over-HTTPS

### ISSUE THREAD

**Issue by emanruse** [Eloston/ungoogled-chromium#833]
https://soylentnews.org/article.pl?sid=19/09/12/1724222

https://tech.slashdot.org/story/19/09/29/2033247/googles-dns-over-tls-plans-scrutinized-by-us-congress

If DNS requests are forced through Google's DNS this is a serious privacy issue. AFAIK currently ungoogled-chromium does domain name based replacement to make connections to Google's hosts impossible. However this may need additional attention/flag.

*Personally I use Tor proxy and don't want to have my DNS requests forced through Google.

**Comment by pipboy96** [comment]
It would make sense keeping the feature but letting the user select the DoH endpoint they want to use.

**Comment by csagan5** [comment]
You could use this patch from Bromite: https://github.com/bromite/bromite/blob/764cf58/build/patches/Add-a-flag-for-DNS-over-HTTPS.patch

**Comment by travankor** [comment]
@eloston

Would it be possible for ungoogled-chromium to permanently unlock the flag #dns-over-https (currently, it's locked for linux on Chromium 78 :/ ... and there is no explanation why when it worked perfectly fine in the past)?

Note that enabling the flag only gives the user the freedom to choose his/her DoH provider and doesn't actually change DoH on its own (maybe Chrome can do something opaque here, but I'm not sure).
See: https://bugs.chromium.org/p/chromium/issues/detail?id=985589#c32

**Comment by jstkdng** [comment]
If we are talking about linux and DoH I'd just setup dnscrypt for it to be system wide.

**Comment by travankor** [comment]
DNSCrypt Proxy is cross-platform, like Chromium, so it should run on Mac/Windows/(maybe Android?)/BSD. 

I use DNSCrypt too, but I haven't had much luck with it when dealing with some custom firewall/VPN rules. Also dealing with systemd-networkd is just a hassle.

**Comment by csagan5** [comment]
@travankor the PR you created will still use the same DNS configured in the system, but over DoH if it is available. Chromium has a hard-coded list of providers which support DoH.

Just mentioning it in case not all parties are aware.

**Comment by travankor** [comment]
You should be able to set your own DoH provider via a command-line option -- unfortunately, the option is ignored if the chrome://flags DoH flag is turned off (or if you have an enterprise policy set).
https://bugs.chromium.org/p/chromium/issues/detail?id=985589#c32

I don't think there is anything harmful with the default behaviour, though. The default behaviour only "upgrades" the DNS of a supported/hard-coded DNS provider to an authenticated version. So no third parties can spy on or intercept your DNS queries, but you will have the same DNS provider that you use for your system.

If chromium changes this default behaviour, then this issue should be revisited.

@csagan5 Let me know if I made a mistake or misunderstood something.

**Comment by travankor** [comment]
Thank you Carl Sagan, I think I made a misunderstanding. The chrome://flags does not seem to override the CLI flags for DNS, for now.

However, to effectively use Chromium's DoH for a custom provider, `--force-fieldtrial-params` needs to set the `Fallback` option to false. Chromium's fallback does not seem to be the dictionary definition of fallback (ie: the resolver tried DoH, and if it is unavailable it falls back to unencrypted DNS), but instead will use unencrypted DNS if it is faster.

So, apologies for the noise.

**Comment by DutchPete** [comment]
Another workaround: use "HTTPS Everywhere" extension.

**Comment by csagan5** [comment]
There is already an UI available for this feature from upstream, so not sure if there is anything to be done anymore here.

**Comment by M86xKC** [comment]
Can you elaborate more on this, please?

When this was added? and is there anything extra needed to build ungoogled-chromium with it?

**Comment by csagan5** [comment]
See https://source.chromium.org/chromium/chromium/src/+/16e25a3ab375471e888c7c1e8b6a2ce3b4868bfe; Bromite already uses it: https://github.com/bromite/bromite/blob/86.0.4240.70/build/patches/Enable-DoH.patch

**Comment by Eloston** [comment]
Closing based on info from @csagan5.

**Comment by travankor** [comment]
Actually seems like it's not available on what upstream calls the Linux platform

https://bugs.chromium.org/p/chromium/issues/detail?id=1127671#c5

**Comment by M86xKC** [comment]
I noticed that too, when visiting `chrome://flags/#dns-over-https` on Linux it shows _**Not available on your platform.**_ Message. But apparently it is available on _Mac, Windows, Chrome OS, Android_
