### ISSUE TITLE
[Windows] Extensions don't install via drag-and-drop

### ISSUE THREAD

**Issue by xbeyond1** [Eloston/ungoogled-chromium#834]
**Describe the bug**
Extensions don't install when dropping the crx files to the extensions page. When dragging and dropping the crx file I don't get any error messages nor is there an installation prompt. The developer mode is turned on and "chrome://flags/#extension-mime-request-handling" has been set to "Always prompt for install".

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 Pro 1903 x64
 - ungoogled-chromium version: 77.0.3865.90-1 (Development binary)

**Comment by Eloston** [comment]
Not sure if this is related, but I'm guessing you are not affected by https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/16?

**Comment by lipici** [comment]
sorry for the spam but you know me. Good job for the windows version update. Kepp up the good work.

**Comment by xbeyond1** [comment]
> Not sure if this is related, but I'm guessing you are not affected by [ungoogled-software/ungoogled-chromium-windows#16](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/16)?

No, I'm not. I'm actually writing this from the browser.

I did find a temporary workaround for the extensions issue: I installed the older version, 67 alongside this one and simply dragged all the necessary extensions and themes there. They all showed up on this one and are working perfectly thus far.

**Comment by ydoiliv20** [comment]
I'm suffering from the same problem. I checked all hash values of zip file. And I changed the setting of 'flags' to 'always prompt for install'. And I turned on developer mode. And I drag-and-drop the crx file onto the Extensions page, but I could only see the installation circle goes round and round at the bottom of the screen.

**Comment by xbeyond1** [comment]
Yup, it behaves the exact same way for me.

**Comment by mikhaelkh** [comment]
The CRX installation prompt does not appear in [tinfoil build](https://github.com/macchrome/winchrome/releases/download/v77.0.3865.120-r681094-Win64/Ungoogled-Chromium-tinfoil-77.0.3865.120-win64.7z), but works fine in [w/o safebrowsing patch build](https://github.com/macchrome/winchrome/releases/download/v77.0.3865.120-r681094-Win64/ungoogled-chromium-77.0.3865.120-1_windows.7z), so the problem must be in safebrowsing patch.

**Comment by Ph0rkoz** [comment]
I am not able to drop CRX onto linux versions either. I had to unpack all extensions and load them that way.

**Comment by juanpablo-munoz** [comment]
Had the exact same problem on Win10: none of the two windows-compatible methods listed in the FAQ worked. As a workaround I extracted the crx file (using https://crxextractor.com/) and then installed the unpacked extension with developer mode activated in chrome://extensions/.

**Comment by lluke777** [comment]
Cannot install extension at Win 10 Enterprise. chromium installed through chocolatey installer.
Extension installation last forever after drop. Round timer is moving all the time, but cannot see the end of process.
Version 77.0.3865.120 (Developer Build) (64-bit)
Windows 10 Enterprise 1903

**Comment by gammacray** [comment]
> Had the exact same problem on Win10: none of the two windows-compatible methods listed in the FAQ worked. As a workaround I extracted the crx file (using https://crxextractor.com/) and then installed the unpacked extension with developer mode activated in chrome://extensions/.

I haven't even had luck with your technique. It's the only thing so far that's presented an error though. - When I try loading .crx from unpacked, i get 'missing manifest'? Not sure what I'm doing wrong. I DL .crx with crxextractor, point chromium (load unpacked) to it, and error. Am I missing something?

Anyone else solved this yet?

**Comment by Devocub** [comment]
same problem

**Comment by D3bby9** [comment]
i tried using this method and it works.
https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/

**Comment by Devocub** [comment]
@D3bby9 sure load unpacked zip works

**Comment by nam108** [comment]
Same. Win 8.1 32bit UChromium 78.0.3904.97
Unzipped worked tho also.

**Comment by Ph0rkoz** [comment]
I haven't verified on windows but the latest build on linux allowed me to drag CRX onto the extensions window and install.

**Comment by jstkdng** [comment]
Just giving my two cents here:
I can't drag and drop the extension but can install them by using the file:/// handle under linux, in windows the extension install popup never shows up.

**Comment by MrBananaxx** [comment]
>
> in windows the extension install popup never shows up.
Same happening here.

**Comment by naviracs** [comment]
I have the same problem on Manjaro linux with
ungoogled-chromium Version 79.0.3945.88-1 

So the dragging and dropping bookmarks in the bookmark manager doesnt work for me. Does the bookmark manager works for you guys?

**Comment by Eloston** [comment]
@naviracs I'm also on 79.0.3945.88 for Debian Buster, and I'm having troubles with drag-and-drop in general for this version. I think it's an unrelated bug due to Chromium's changes.

**Comment by LIINdd** [comment]
> 
> 
> Cannot install extension at Win 10 Enterprise.
> Extension installation last forever after drop. Round timer is moving all the time, but cannot see the end of process.
> Version 77.0.3865.120 (Developer Build) (64-bit)
> Windows 10 Enterprise 1903

Same issue here, on Windows 10 Home 1903, with both regular installed and the Portable version.  It's not just a problem with the latest version, the only version I've tried that installing extensions works properly is 67. So the work-around for me is to install extensions on 67, and then just copy that User Data over to latest version.

**Comment by flesti** [comment]
Same here. No drag and drop works, either extensions or links or text. Chrome-web-store extension doesn't work either. Both win7 and 10. 

I checked with Brave, Vivaldi, Opera and default Chromium and they work fine.

**Comment by sertraline** [comment]
.crx is just an archive, open it with your archive manager, unpack to some folder, go to chrome://extensions, switch developer mode on, load extension folder as unpacked, switch developer mode off. Works for me.

**Comment by bazir123** [comment]
i was able to install in this way
i had problem too with installing roboform extension
i try this opened chrome://extensions/ and draged icon(from roboform options) there
not working
then i try 
file:///C:\Program Files\Siber Systems\AI RoboForm\Chrome\rf-chrome.crx
it copy extension to download folder (not working)
then again i try installing without going to chrome://extensions/ tab
finally it shows prompt for installing it clicked add browser crashed
[0130/041153.825:WARNING:safe_terminate_process_broken.cc(27)] Don't use this! For cross builds only. See https://crbug.com/777924.(im not sure this log related to it because i opened this for awhile and may saved file so that cause change time of debug.log file )
reopend chromium goes to chrome://extensions/ tab and finally it worked and installed extension
prompt appeared and added it

**Comment by bennyhillthebest** [comment]
Installed 79.0.3945.117-1 via Chocolatey on W10 Pro. Drag-n-drop doesn't work. Installed 79.0.3945.130 from Marmaduke repo. Drag-n-drop works. So as a temporary solution one can probably swap to this other repo

**Comment by hariskar** [comment]
I managed to install ublock origin following this guide: https://github.com/gorhill/uBlock/tree/master/dist

**Comment by loadcorp** [comment]
The same problem with:
79.0.3945.117-1.buster1: Binaries for Debian 10 (buster) amd64

**Comment by Eloston** [comment]
I have a feeling this is the same problem as #923. Closing this as duplicate because the other issue is titled and tagged better.

**Comment by FrankSalmick** [comment]
I have this problem as well on a brand new install of windows (ungoogled chromium was the first thing I installed). I also can't install using unpacked extensions by dragging them, only by clicking "Load unpacked extension" - so I suspect the problem involves the drag-and-drop action, not nessicarily the extension loading itself.

**Comment by ehamawy** [comment]
Having the same problem. Sometimes it just does nothing, but sometimes it says "Adding to Chromium" at the bottom of the screen and loads forever.
