### ISSUE TITLE
[Windows] Crahes at sites login

### ISSUE THREAD

**Issue by lipici** [Eloston/ungoogled-chromium#835]
**Describe the bug**
Crashes everytime i log in a site with username and password and after i open again browser im still unlogged

**Environment (please complete the following information):**

OS/Platform and version: Windows 8.1 Pro x64
ungoogled-chromium version: 77.0.3865.90-1 (Development binary)

**Comment by r4sas** [comment]
Doesnt have same issue when running chrome from MVS17 debugger.
Environment is same.

**Comment by lipici** [comment]
https://www.dropbox.com/h?preview=Action+07-Oct-19+8-14-25+PM.mp4

Correct, now its working, 12 hours ago didnt worked when i amde the post.

Can be closed.

**Comment by lipici** [comment]
seems its something random

https://www.dropbox.com/s/89ppnb8q1pkb4ub/Action%2007-Oct-19%208-39-05%20PM.mp4?dl=0

**Comment by tangalbert919** [comment]
This is an absolutely bizarre issue. I am not able to reproduce this on my Win10 machine or my Windows 8.1 VM (Virtual Machine).

**Comment by howaboutsynergy** [comment]
What do you see on the terminal when it crashes, maybe when ran with `--v=2` (or `--v=99`)

**Comment by Mwni** [comment]
The crashs are caused by the "Do you want to save this password?" dialog. You can disable it in the settings for now. Autofill > Passwords > Offer to save passwords: off

**Comment by lipici** [comment]
> The crashs are caused by the "Do you want to save this password?" dialog. You can disable it in the settings for now. Autofill > Passwords > Offer to save passwords: off

correct. problem solved.

**Comment by Eloston** [comment]
Hmm, this might be related to the Safe Browsing patch. This needs to be investigated further.

**Comment by Ph0rkoz** [comment]
Yes, saving passwords does it for me too. :(

**Comment by c33s** [comment]
same problem here. crashing even if the password was stored before (old version where no crash occured). disabling save offer works.

from the `debug.log`
```
[1105/234320.152:ERROR:process_memory_win.cc(73)] ReadMemory at 0x30ffffb1 of 767 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[1105/234612.135:ERROR:process_info.cc(375)] NtQuerySystemInformation SystemExtendedHandleInformation: The specified information record length does not match the length required for the specified information class. (0xc0000004)
```

**Comment by Ph0rkoz** [comment]
I worked around this by using keepassxc since I don't think its being fixed any time soon.

**Comment by Eloston** [comment]
I'm guessing this is still an issue in version 80? If so, we should open another issue in ungoogled-chromium-windows so we can track this better.

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)
