### ISSUE TITLE
Help with Search Suggestions

### ISSUE THREAD

**Issue by flesti** [Eloston/ungoogled-chromium#837]
Can't seem to be able to make it work.
I am trying out whatever suggest URL I can gather from the web, like:

Ecosia: https://ac.ecosia.org/autocomplete?q=%s&type=list
DuckDuckGo: https://ac.duckduckgo.com/ac/?q=%s&type=list
Qwant: https://api.qwant.com/api/suggest/?q=%s&client=opensearch

I put the url in the appropriate input in the search engines edit, but nothing appears in the Omnibox when I try to search.

What am I doing wrong ?

**Comment by qvint** [comment]
Did you mark your search engine as default?

**Comment by Eloston** [comment]
Did you enable `Autocomplete searches and URLs` in `chrome://settings/syncSetup`?

**Comment by flesti** [comment]
That was the problem then.
Thanks you both.
