### ISSUE TITLE
any 77 version includes this or only latest 77 update after 17 october?

### ISSUE THREAD

**Issue by lipici** [Eloston/ungoogled-chromium#839]
https://blog.chromium.org/2019/10/recent-site-isolation-improvements.html

**Comment by jstkdng** [comment]
well, according to [#36](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/36), chromium 77.0.3865.119 gets error messages related to invalid isolated origins, it could be related to that post.

**Comment by Eloston** [comment]
78 is out, closing.
