### ISSUE TITLE
Is there Installation-ID?

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#844]
When checking [SRWare Iron](https://www.srware.net/iron/), it mentions `Installation-ID`.
Is it removed here?

PS: features of SRWare Iron:
* Installation-ID
A copy of Google Chrome includes a generated installation number which will be sent to Google after the installation and the first usage. It gets deleted when Chrome checks first time for updates.If Chrome is received as part of a promotional campaign, it may generate a unique promotion number which is sent to Google on the first run and first use of Google Chrome.
does not exist in Iron

* Suggest
Depending on the configuration, each time you put something in the address line,this information is sent to Google to provide suggestions.
does not exist in Iron

* Alternate Error Pages
Depending on the configuration, if you have typed a false address in the adress bar, this is sent to Google and you get an error message from Google's servers.
does not exist in Iron

* Error Reporting
Depending on the configuration, details about crashes or failures are sent Google's servers.
does not exist in Iron

* RLZ-Tracking
This Chrome-function transmits information in encoded form to Google, for example, when and where Chrome has been downloaded.
does not exist in Iron

* URL-Tracker
Calls depending on the configuration five seconds after launch the Google homepage opens in background
does not exist in Iron

**Comment by kramred** [comment]
Ungoogled Chromium strives to prevent all unintended communication with Google servers (see [key features](https://github.com/Eloston/ungoogled-chromium#key-features)). That should include all the points in your/SRWare Iron's list and many more. 

Furthermore, the whole source code and procedure of how Ungoogled Chromium is generated and compiled is available here and in the platform repos. 

SRWare Iron seems to be closed source, their versioning system is unclear, and the link to their privacy statement leads to a website only available in German, which seems very generic and makes no statement about their browser…

**Comment by playgithub** [comment]
Thank you

**Comment by Eloston** [comment]
Thanks @kramred. Question looks sufficiently answered, closing.
