### ISSUE TITLE
about PKGBUILD using mirrors

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#847]
Because Google is blocks by the government, I'd like to use mirror to download all the stuff that is blocked.
The problem is chromium use **depot_tools** to download what it needs, I don't known how deep **ungoogle-chromium** changed the way of building, is it replace url in PKGBUILD enough to solve the blocking problem?

Thanks

**Comment by Eloston** [comment]
> The problem is chromium use depot_tools to download what it needs

ungoogled-chromium and most Chromium builds in Linux distros use a single `.tar.xz` file instead of depot_tools. In ungoogled-chromium, the download URL is defined here: https://github.com/Eloston/ungoogled-chromium/blob/master/downloads.ini

> is it replace url in PKGBUILD enough to solve the blocking problem?

In the context of ungoogled-chromium-archlinux, that is sufficient.

**Comment by playgithub** [comment]
Thanks, I think it's time for me to buy a 2TB SSD harddisk for my notebook :)

**Comment by jstkdng** [comment]
if you want compile times to be fast get a cheap per hour vps. On ovh you can get a 16 core 60 gb ram vps for 0.55USD per hour, and with that speed it takes you less than an hour to compile chromium.
Really worth it if you ask me

**Comment by playgithub** [comment]
That is very good, marked, thanks.
However I may modify the code, e.g. to hard code all my password in.
I'm goting to buy Asus Cubi N5000, very cheap, TDP 6W, no fan, compiling when sleeping.

**Comment by jstkdng** [comment]
hardcode passwords? wtf
also, that laptop is going to take some time to compile chromium, probably 10 hours lmao, unless electricity is really cheap where you live, its not worth it.

**Comment by playgithub** [comment]
> hardcode passwords? wtf

e.g. hardcode the usernamea and password for github.com, so never need login manually.
If it is hard, I can make a shortcut or a button to fill username and password automatically according current URL.

> also, that laptop is going to take some time to compile chromium, probably 10 hours lmao, unless electricity is really cheap where you live, its not worth it.

The CPU TDP is only 6w, suppose 10w at all, for one year it is only 6w * 24h/day * 365 = 52.56kwh

**Comment by jstkdng** [comment]
>The CPU TDP is only 6w, suppose 10w at all, for one year it is only 6w * 24h/day * 365 = 52.56kwh

Check the values of the battery, not just the cpu tdp. My laptop has a 15w tdp but the battery requires 45w, so yeah, check that.

>e.g. hardcode the usernnam and password for github.com, so never need login manually.

you don't really need your password in order to clone from github. Or you could use ssh keys, more secure imo.
You do you.

**Comment by playgithub** [comment]
> Check the values of the battery, not just the cpu tdp. My laptop has a 15w tdp but the battery requires 45w, so yeah, check that.

Alright, I'll check when I receive it.

> you don't really need your password in order to clone from github. Or you could use ssh keys, more secure imo.
To login on the website,  for some webistes the passwords remembered in cookies expires daily.
