### ISSUE TITLE
ch40m1um.qjz9zk

### ISSUE THREAD

**Issue by adammenges** [Eloston/ungoogled-chromium#85]
possible security issue?

steps to repo

1.

open about chromium

2.

click chromium

<img width="609" alt="screenshot 2016-10-03 19 30 00" src="https://cloud.githubusercontent.com/assets/817438/19060773/caf212ce-899f-11e6-9374-e8900f7e7ac4.png">

3.

see this

<img width="438" alt="screenshot 2016-10-03 19 27 32" src="https://cloud.githubusercontent.com/assets/817438/19060784/d8d051e4-899f-11e6-9b84-8ab62e26bddb.png">

**Comment by Eloston** [comment]
No, there's no security issue here. That's just the result of domain substitution with the patch that intercepts all `qjz9zk` URLs. Is there a problem with this behavior?

**Comment by adammenges** [comment]
just seems a little weird that through the UI, in the about area, you can click on a URL that is blocked.

**Comment by Eloston** [comment]
Well these kinds of links are scattered throughout the UI, so I don't think it's too strange.

**Comment by shetakeyourmoneyleaveupoor** [comment]
Same Problem with Version 109.0.5414.74 (Official Build, ungoogled-chromium) (64-bit)

**Comment by funchan24** [comment]
> 好吧，这些类型的链接分散在整个UI中，所以我认为这并不太奇怪。

Is there any way to make it cleaner？
