### ISSUE TITLE
[Feature request] Old UI layout

### ISSUE THREAD

**Issue by seitokaichou** [Eloston/ungoogled-chromium#853]
It has been a while (version 71 iirc) since google removed the `chrome://flags/#top-chrome-md` flag to disable the new material UI - would bringing that back be feasible?

**Comment by qvint** [comment]
AFAIK the old UI code has been physically removed from the Chromium source tree, so there is no runtime/compiletime flag to bring it back. Here are examples of how Google removes "non-material" code: https://crrev.com/c/1285082, https://crrev.com/c/1244882, https://crrev.com/c/1287929

**Comment by Eloston** [comment]
Thanks @qvint. I don't think there's much we can do about this unless someone writes patches to revert those changes, and especially maintains them.
