### ISSUE TITLE
Close the other tabs is missing

### ISSUE THREAD

**Issue by lipici** [Eloston/ungoogled-chromium#858]
**Describe the bug**
Function "Close the other tabs" is missing

**Environment (please complete the following information):**
 - OS/Platform and version: windows 8.1
 - ungoogled-chromium version: Version 78.0.3904.87 (Developer Build) (64-bit)

**Comment by lipici** [comment]
sorry, should be added at features wanted because i just checked in chromium 78 and is missing there too, seems they remove it.

**Comment by Marek33** [comment]
Is it possible to restore it back? I know, that Ungoogled is mainly about privacy, but I would really love to have this feature, but I'm afraid that it's not possible, but it is very useful. Plus, these kinds of features should never be removed, even if they are used by a very few people.

**Comment by jstkdng** [comment]
Yes, it could be possible, but someone would have to maintain it and be sure it doesnt break after every update.
Maybe instead of restoring the functionality, recreate it but it should have the capability to be toggled during compile time and while using the browser(flags), that way, if that new functionality broke after an update it can be disabled easily until whoever maintains it fixes the problem.

**Comment by Marek33** [comment]
That's a pity to hear, since the current Windows release was quite a long time ago and that would slow it even more. However, if it would be possible to have it, as an extension, it would be a nice addition!

I understand, and thank you very much for the info!

**Comment by Eloston** [comment]
> Maybe instead of restoring the functionality, recreate it but it should have the capability to be toggled during compile time and while using the browser(flags),

I think we can make an exception for this case. Since we are just adding a single drop-down menu item, it won't change the UI significantly or cause any other features to change. This is assuming that the dropdown is like this feature: #761

**Comment by PF4Public** [comment]
Did anybody do a search for a commit, that removed it? If that is a simple commit, then it could be trivial to revert it, right?

**Comment by qvint** [comment]
> Did anybody do a search for a commit, that removed it? If that is a simple commit, then it could be trivial to revert it, right?

https://crbug.com/1020399,  https://crrev.com/c/1912620

**Comment by PF4Public** [comment]
Am I correct to understand, that they have reverted this change upstream?

**Comment by jstkdng** [comment]
it seems they are going to re add it, but probably not next release, (we are only 35 days before stable)

**Comment by qvint** [comment]
This can be closed. Fixed in 78.0.3904.108 (#865).

**Comment by Eloston** [comment]
Nice to see Google speedily re-add this feature. Thanks for keeping us posted @qvint.
