### ISSUE TITLE
Unable to install extensions in a conventional manor

### ISSUE THREAD

**Issue by Merith-TK** [Eloston/ungoogled-chromium#860]
**Describe the bug**
I am unable to add a extension to ungoogled chromium via `chrome://extensions` with developer mode

I beleive this is because un-chrome does not have a proper extension dir?

**To Reproduce**
https://i.imgur.com/a8rvQhQ.png
1. Download a CRX file from any source, 
2. go to [chrome://extensions](chrome://extensions)
3. enable dev mode
4. drag and drop teh CRX to the page

**Expected behavior**
I expected the plugin/extension to install normally like it does on actual chrome

**Screenshots**

**Environment (please complete the following information):**
 https://i.imgur.com/a8rvQhQ.png

**Additional context**
Currently, i have to extract the CRX with 7zip (turns out they are just standard zip files) 
And "Load Unpacked" every time i want to install a extension,

The attached GIF shows the issue in a side by side comparison

**My Thoughts?**
I think we could apply a patch to a but load of files to replace the string 
`clients2.google.com/service/update2/crx` with something of our choosing, so we dont have to worry about a chrome webstore, maybe allow CRX installs from github?

https://cdn.merith.tk/bandicam%202019-11-13%2017-28-04-002.gif < this may take a few seconds to load, i have slow internet

**Comment by qvint** [comment]
#834

**Comment by Eloston** [comment]
This is a duplicate. Thanks @qvint.
