### ISSUE TITLE
auto updates?

### ISSUE THREAD

**Issue by Chippel** [Eloston/ungoogled-chromium#861]
Thinking about switching to this Browser for my privacy but I'm not sure about the updates. Does this Browser updates itself or do I have to check everytime I go online for new versions? Plus how safe are the packages I can download in the download section?

**Comment by PF4Public** [comment]
First of all, we do not know the platform you're willing to run ungoogled-chromium on. That could make a huge difference.

**Comment by Chippel** [comment]
I'd like to use it on my Mac. Does it somehow offer auto update there?

PF4Public <notifications@github.com> schrieb am Sa., 16. Nov. 2019, 18:26:

**Comment by PF4Public** [comment]
Then you should probably have a look at [MacOS repo](https://github.com/ungoogled-software/ungoogled-chromium-macos) and probably ask there. But most likely you should build it yourself every time an update is available, although they have a convenient script for that.

**Comment by Chippel** [comment]
Thanks didn't know about that. Where did you find the repo? I haven't found
it myself.

PF4Public <notifications@github.com> schrieb am Sa., 16. Nov. 2019, 18:50:

**Comment by PF4Public** [comment]
The README.MD section [Source Code](https://github.com/Eloston/ungoogled-chromium#source-code) says:

> This repository only contains the common code for all platforms; it does not contain all the configuration and scripts necessary to build ungoogled-chromium. Most users will want to use platform-specific repos, where all the remaining configuration and scripts are provided for specific platforms:
> 
> Find the repo for a specific platform here.

And the last sentence is a link to [this document](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/platforms.md).

**Comment by Eloston** [comment]
Thanks @PF4Public for helping out. Closing as an answered question.

**Comment by Francewhoa** [comment]
## Flatpak

For those using Linux, the easiest option that I know of to get automated updates for Ungoogled-Chromium is to use Flatpak to install Ungoogle Chromium. I used this Flatpak for months now. It works really well. Very stable. And more importantly, more secure. Steps are in my comment at [ https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps](https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps) 

## Chromium Web Store

To get semi-automated updates for **extensions**, I suggest using this [Chromium Web Store](https://github.com/NeverDecaf/chromium-web-store#readme) extension. Yes, an extension which update other extensions. Chromium Web Store is available for Linux and Windows and other operating systems. Steps to install and use Chromium Web Store are in my same comment at [ https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps](https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps)

**Comment by claudiodekker** [comment]
Since this appears to be a common and recurring issue (arguably for good reason), I figured I'd try to partially address it by creating **a Chromium extension that automatically checks for new Chromium updates in-line with your preferences**.

Its functionality resembles that of NeverDecaf's "Chromium Web Store" extension: It displays a badge indicating available updates and, when interacted with, provides a concise overview of all available updates, allowing you to directly download newer build versions, jump to the release page, copy hashes and more. Essentially, it serves as the closest thing to an automated updater mechanism, without one being built-in.

You can find it here: https://github.com/claudiodekker/chromium-update-notifier
