### ISSUE TITLE
Disable Search Suggestions and Auto Comlete

### ISSUE THREAD

**Issue by jputting** [Eloston/ungoogled-chromium#867]
Hi, 

I would an option to disable Search Suggestions and Autocomplete when searching from the Omnibar.

At this point in time UnGoogled Chromium behaves  in the same way that Chrome behaves.

When you type in a website address or perform a Search Enquiry form the Omnibar you get Suggestions from your History, Bookmarks and the information that Google has retained about your previous browsing history etc.

A great many Chrome users of complained loud and strongly about this issue on the Google Chrome Forums.

However Google have made it abundantly clear that they will NOT EVER CHANGE THIS and give Chrome users a choice to disable Search Suggestions or Autocomplete completely

Vivaldi is a browser based upon Chrome and the producers of Vivaldi have given users the freedom to choose what they want in regards to Search Suggestions or Autocomplete in the Omnibar.

With Vivaldi if you don't like Search Suggestions or Autocomplete you have very clear Options in the Vivaldi Preferences to completely disable ALL of the Search Suggestions and they will NEVER EVER appear  if you have chosen to disable them. If you want those Suggestions and Autocomplete you can still choose to keep them.

However after using Vivaldi I found it has issues with playing of certain media types and there are other issues which have made Vivaldi inferior to Chrome.

As Vivaldi is a Chrome based browser, Ungoogled Chromium should be able to duplicate what Vivaldi has done and give us the option to disable Search Suggestions and Autocomplete entirely if we choose to do so.

This feature should have present from the begining when the whole concept of UnGoogled Chromium was concieved as Google keeps a mammoth database on its users web searches and their browsing history.

If the producers of UnGoogled Chromium are 100% dedicated and quite earnest about UnGoogling Chromium because of privacy concerns this is an issue which needs to be addressed urgently.

**Comment by xsmile** [comment]
Ungoogled Chromium does not connect to Google if you use the omnibar. Search data will only be sent to Google if you explicitly configure Google as your default search engine.

Furthermore, the option "Autocomplete searches and URLs" can be disabled (IIRC this is the default) at the settings page chrome://settings/syncSetup.

The remaining suggestions (history, bookmarks) are generated from your local browser profile which is not stored online.

**Comment by jputting** [comment]
I fully acknowledge your points mentioned.

However partial disabling of autocomplete and search suggestions is not enough.

A great many Chrome users have complained bitterly for a long time that Google will simply not provide users with a choice and give us an option for full disabling of ALL search suggestions, regardless of their origin.

I want what Vivaldi provides its users 100% full disabling of ALL search suggestions including those from my History and Bookmarks.

This is needed when you have more than one person with access to your mac and Chrome browser, this is a quite important issue because with a shared mac you may not want other users having access to browsing history and getting hints or suggestions sourced from visits to websites which deal with banking/financial, health/medical or personal reationships.

There are of course a great many other harmless but quite valid personal reasons why you may not others getting hints or indications or indeed any knowledge of your browsing history for personal reasons which may include: a spouses birthday is due soon and have chosen to purchase an expensive antique  for her and you certainly do not what the birthday surprise ruined because the websites you have visited are popping up in search suggestions based upon you browsing history or bookmarks.

I strongly feel you should have a look at the way Vivaldi has implemented this feature and given its users TOTAL CONTROL with regards to Search Suggestions and Autocomplete regardless of how they sourced.

People have complained loud and strongly to Google and told them very clearly this is an important issue to them and yet Google still chooses to bury its head in the sand and will not give people what they want.

If as a developer you value privacy then half measures are NOT ENOUGH.

**Comment by xsmile** [comment]
Indeed, Vavaldi has a lot of interesting customization options which are missing in Chromium. Nevertheless, I would argue that this has no benefit for privacy. If someone wants to access your browsing history, he can do it directly without relying on omnibar suggestions.

There may be other already working ways to do what you want. Chromium supports multiple user profiles to separate user data. Each Chromium user has his own settings, history and bookmarks. If you don't want to keep any browsing history at all, you can launch the browser in incognito mode. To make absolutely sure that others have no access to your data, create a new Mac user.

**Comment by jputting** [comment]
I am extremely dismayed and very disappointed that you are taking a stance very similar to Google and making countless excuses to NOT GIVE USERS WHAT THEY WANT.

I have tried repeatedly and at great length to explain why half measures in disabling search suggestions is SIMPLY NOT GOOD ENOUGH.

A great many users of Chrome want TOTAL 100% disabling of search suggestions and autocomplete and will NOT settle for half measures.

This all about giving Chrome browser users choice and empowering them by allow them to decide what level of privacy suits them and what features they choose NOT TO USE.

You are being extremely stubbornly in refusing to give us what we want and as such you have not lived up to your advertised claim of being an UnGoogled Chromium as you are still forcing users to accept extremely unpopular Google features that we DO NOT WANT.

You add further insult to injury because you still slavishly following Googles totalitarian dictator like authority and will not give us the choice as to decide what features we wish to use and disable. 

I once again repeat half measures are simply NOT GOOD ENOUGH.

I am now uninstalling UnGoogled Chromium

I'm reverting back to using Firefox as it give users far more control and has recently implemented a great many more privacy and security features.

I am now closing this issue because of your inability to understand people whom use internet browsers want the FREEDOM TO CHOOSE what features they wish to use and want they want disabled ENTIRELY.

**Comment by jpsoutlook** [comment]
What version does not have this Omnibox auto suggest from history stuff.   It's so annoying and distracting.  Thanks for your hard work but that really sucks.

When I click up there and start type this massive pull down comes and I can see wtf I am typing and I dont/never/want suggestions.  Why would you not make it optional?

**Comment by jpsoutlook** [comment]
I uncheck all 3 and it still persists
