### ISSUE TITLE
Linux FREETYPE_PROPERTIES seems to be ignored in portable version

### ISSUE THREAD

**Issue by marek141017** [Eloston/ungoogled-chromium#868]
Hello

I am trying to pass FREETYPE_PROPERTIES="truetype:interpreter-version=35" to portable version, but when I check font anti-aliasing it looks like type 40
I also do not see those variable in /proc/<pid>/environ
I also tried to put "export" into the wrapper - the result is the same.

How can I pass FREETYPE_PROPERTIES to ungoogled-chromium?

**To Reproduce**
1. FREETYPE_PROPERTIES="truetype:interpreter-version=35" /usr/local/share/chromium/chrome-wrapper
1. Or put FREETYPE_PROPERTIES="truetype:interpreter-version=35" to /etc/environment, then start chrome-wrapper as usual

2. check /proc/"pid chrome"/environ

**Expected behavior**
I would like to be able to pass FREETYPE_PROPERTIES="truetype:interpreter-version=35" to portable version of ungoogled-chromium

**Screenshots**

**Environment (please complete the following information):**
 Debian Buster
 - ungoogled-chromium version: Chromium 75.0.3770.100 custom

Thank you

**Comment by Eloston** [comment]
Maybe it's because FreeType is compiled into the browser for Portable Linux. If so, this should be common to all Chromium-based browsers that bundle FreeType. Does this work on the regular Debian buster version?

**Comment by marek141017** [comment]
I do not think they are compiled it into. I think they do not read FREETYPE_PROPERTIES environment variable at all. Therefore it doesn't go into /proc/<pid>/environ
But /proc/<pid>/environ does have some browser arguments.
Will you be able to check, if it is possible to pass FREETYPE_PROPERTIES to /proc/<pid>/environ?
Type 40 really needs to be changed to type 35. Type 40 has unreadable anti-aliasing.

Thank you

**Comment by Eloston** [comment]
I am running `78.0.3904.108-2.buster1` and I don't see any differences running `FREETYPE_PROPERTIES="truetype:interpreter-version=35"` with `FREETYPE_PROPERTIES="truetype:interpreter-version=40"`. The version I'm running should be using the system's FreeType library. Do you know if `chromium` in Debian supports this?

**Comment by marek141017** [comment]
It looks to that chromium doesn't read FREETYPE_PROPERTIES variable at all
Therefore it doesn't go to /proc/'pid of the cromium'/environ
And may be it doesn't render in accordance with freetype type.
Will you be able to check if chromium reads FREETYPE_PROPERTIES variable?

Thank you.

**Comment by Eloston** [comment]
This will not be convenient for me to test. I may take a look if I have some time.

**Comment by marek141017** [comment]
Thank you.
I can open a bug in chromium, but I am sure they won't do anything about it, because they relay on official chrome. But chrome dev team won't do anything about it for sure.

It would be a big advantage for ungoogled-chromium, if it will render text with type 35, because it looks much better.

One can add this FREETYPE_PROPERTIES into /etc/environment, then log-out/log-in and then open LibreOffice, fonts will be much better.

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo.
