### ISSUE TITLE
Bookmarklet to download extensions from Chrome Web Store

### ISSUE THREAD

**Issue by biziclop** [Eloston/ungoogled-chromium#869]
**Is your feature request related to a problem? Please describe.**
I needed a simple and clean solution to install extensions easier from the Store.

**Describe the solution you'd like**
Based on the [wiki instructions](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#downloading-the-crx-file) I made this:  
`javascript:location.href='https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion='+(navigator.appVersion.match(/Chrome\/(\S+)/)[1])+'&x=id%'+'3D'+(location.pathname.split('/').pop())+'%'+'26installsource%'+'3Dondemand%'+'26uc';`

So first I set the chrome://flags/#extension-mime-request-handling flag to "Always prompt for install", restarted UngooChromium, went to the webstore page, clicked on the bookmarklet, and [boom](https://www.youtube.com/watch?v=emI_u1sV0KI).

**Describe alternatives you've considered**
There is already a website and an extension, but my bookmarklet is simpler :)  
https://github.com/Eloston/ungoogled-chromium/issues/767#issuecomment-523059611 https://github.com/Eloston/ungoogled-chromium/issues/734

**Comment by Eloston** [comment]
I like this, except apparently it's possible to not have the app ID as the last path element. Most of the time this should be fine, so I'll add this. Thanks!

**Comment by biziclop** [comment]
Hi, thanks for adding it. :)

But do you happen to have an example url which is different than these? I haven't found other url schemes:  
https://chrome.google.com/webstore/detail/EXTENSIONID  
https://chrome.google.com/webstore/detail/EXTNAME/EXTENSIONID  
https://chrome.google.com/webstore/detail/EXTNAME/EXTENSIONID?hl=en

**Comment by Eloston** [comment]
@biziclop You won't get there by any normal means, but it's possible to add path elements yourself. These path elements won't be removed after you visit the CWS. If the extension is being linked from somewhere else, it's possible (but unlikely) that the URL may contain unwanted path elements.

**Comment by biziclop** [comment]
Thanks for your answer.

I found another solution, by finding the 'report' link, which is available even for Google's own cr*p:  
`document.querySelector('a[href^="https://chrome.google.com/webstore/report/"]').pathname.match(/[^\/]+\/*$/)[0]`

Full bookmarklet:  
`javascript:location.href='https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion='+(navigator.appVersion.match(/Chrome\/(\S+)/)[1])+'&x=id%'+'3D'+(document.querySelector('a[href^="https://chrome.google.com/webstore/report/"]').pathname.match(/[^\/]+\/*$/)[0])+'%'+'26installsource%'+'3Dondemand%'+'26uc';`

**Comment by Clebersonc** [comment]
A simple solution is to go to this site that extracts the source code from crx, for some reason on windows when I drag crx in the extensions tab nothing happens.

https://crxextractor.com/

**Comment by Oymate** [comment]
@Clebersonc you need to unpack it to get the source code, the unzip the folder somewhere.
Then load the unpacked extension in extension part.

**Comment by qpwo** [comment]
Old issue but just want to say I think it would help this project a lot if the bookmarklet came pre-installed

**Comment by PF4Public** [comment]
@qpwo There exist more convenient ways nowadays: https://github.com/NeverDecaf/chromium-web-store

**Comment by Testla** [comment]
The Chrome Web Store page changed sometime after mid-September, which broke the bookmarklet.

The report link element now looks like this:

```HTML
<a href="./detail/cjpalhdlnbpafiamejdnhcphjbkeiagm/report" target="_blank" class="X4yNFb">Report a concern</a>
```

One possible fix:

```JavaScript
document.querySelector('a[href$="/report"]').pathname.split('/')[2]
```

```JavaScript
javascript:location.href='https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion='+(navigator.appVersion.match(/Chrome\/(\S+)/)[1])+'&x=id%'+'3D'+(document.querySelector('a[href$="/report"]').pathname.split('/')[2])+'%'+'26installsource%'+'3Dondemand%'+'26uc';
```
