### ISSUE TITLE
'Unblockable' web trackers emerge

### ISSUE THREAD

**Issue by KonoromiHimaries** [Eloston/ungoogled-chromium#870]
https://www.theregister.co.uk/2019/11/21/ublock_origin_firefox_unblockable_tracker/

**Comment by Ph0rkoz** [comment]
Should make a list of the ips/cnames so they could be blocked in dnscrypt-proxy or the hosts. I don't think chrome has the api to fix this just yet.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, please continue the discussion in #1897.
