### ISSUE TITLE
Coincidence ?

### ISSUE THREAD

**Issue by lipici** [Eloston/ungoogled-chromium#871]
Im just asking because is the first time i get an email like this one and never used vpn or anything like this .
After i instaled last version 78.0.3904.108 i got this : 
![Polish_20191125_065438728](https://user-images.githubusercontent.com/46893370/69513663-31c54180-0f51-11ea-9620-b89400a6cd5f.jpg)

**Comment by Eloston** [comment]
I don't see any causal relationship here. It's more likely that your Yahoo account has been compromised, because they've had security issues in the past.
