### ISSUE TITLE
All my extensions got deleted, suddently, twice

### ISSUE THREAD

**Issue by erm3nda** [Eloston/ungoogled-chromium#873]
**Describe the bug**
All my extensions got deleted, suddently, twice.
-Adblocker
-Wappalizzer
-Video DownloadHelper

**To Reproduce**
1. Install extensions if you have the enough patience to unpack then install them from chrome://extensions
2. Use your browser and wait 
3. See some ad, and be aware that your adBlocker and all other extensions got DELETED
4. Enjoy

**Expected behavior**
All extensions working whole life :-)

**Screenshots**
Unneeded

**Environment (please complete the following information):**
 - Win10, original, no cracked software inside, so i do assume clean of viruses (google virus excluded)
 - ungoogled-chromium version: 78.0.3904.97

**Additional context**
I would love to stick to this browser, but i can't assume that i should reinstall those extensions everytime they got deleted.

Regards.

**Comment by Eloston** [comment]
Does this happen if you don't install all your extensions? How often does it happen?

We've been having a variety of strange bugs unique to Windows, including extensions, so it could be Windows-specific. Does anyone else experience this?

**Comment by erm3nda** [comment]
I remember that the first time only 2 extensions got deleted, the later got
deleted too after try again :-)
It may preserver extensions for 2 days, and delete them again. This
happened to me 3 times in a week.
Lucky me i am Linux user, so i think that I'm not gonna hit the same
problem never.

I would love to tell you what happened with Linux, but after 2h of compile,
i had a very strong problem with libva. I regret to a older version, but i
had then a problem with libicu.
I could then ... symlink it, but i got extremely bored about the process so
i im just testing other browsers.

I'll be back here if i decide to try again.

Best regards.
~~ Self signed ~~

**Comment by Eloston** [comment]
> I remember that the first time only 2 extensions got deleted, the later got
deleted too after try again :-)
It may preserver extensions for 2 days, and delete them again. This
happened to me 3 times in a week.

When the extension gets removed from the browser, are the extension files still in the filesystem? Also, do any other browser settings get reset?

> I would love to tell you what happened with Linux, but after 2h of compile,
i had a very strong problem with libva. I regret to a older version, but i
had then a problem with libicu.

You're probably trying to build a variant of ungoogled-chromium that isn't compatible with your distro. If none of the variants match your distro, you can build the Portable Linux version. There are more details in the documentation. Anyways, this is off topic.

**Comment by erm3nda** [comment]
When the extension gets removed from the browser, are the extension
files still in the filesystem?

- No, extensions got deleted on the filesystem.

Also, do any other browser settings get reset?

- Im unsure, i didn't look at.

You're probably trying to build a variant of ungoogled-chromium that
isn't compatible with your distro.

- Maybe, rolling release always have latest packages and sometimes this happens.

Kind regards.

2019-11-30 2:14 GMT+01:00, Eloston <notifications@github.com>:
>> I remember that the first time only 2 extensions got deleted, the later
>> got
> deleted too after try again :-)
> It may preserver extensions for 2 days, and delete them again. This
> happened to me 3 times in a week.
>
> When the extension gets removed from the browser, are the extension files
> still in the filesystem? Also, do any other browser settings get reset?
>
>> I would love to tell you what happened with Linux, but after 2h of
>> compile,
> i had a very strong problem with libva. I regret to a older version, but i
> had then a problem with libicu.
>
> You're probably trying to build a variant of ungoogled-chromium that isn't
> compatible with your distro. If none of the variants match your distro, you
> can build the Portable Linux version. There are more details in the
> documentation. Anyways, this is off topic.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Eloston/ungoogled-chromium/issues/873#issuecomment-559901836


-- 
~~ Self signed ~~

**Comment by Eloston** [comment]
> - No, extensions got deleted on the filesystem.

Then it is unlikely to be caused by ungoogled-chromium. AFAIK even regular Chrome/Chromium will not modify the unpacked extension files. If you have some evidence that this is caused by ungoogled-chromium, I'd like to know.

Usually whenever something else removes the unpacked extension files, Chromium will automatically remove the extension's entry from the extensions page.

> - Maybe, rolling release always have latest packages and sometimes this happens.

In this case, Portable Linux might be best for your use-case. It has very few dependencies on system libraries.

**Comment by erm3nda** [comment]
> Then it is unlikely to be caused by ungoogled-chromium. AFAIK even regular
> Chrome/Chromium will not modify the unpacked extension files. If you have
> some evidence that this is caused by ungoogled-chromium, I'd like to know.

- Haha. Maybe Windows Defender kill them? I really don't understand,
and happened twice.
- I have no evidences, not little idea about how and why. Also i have
no idea on how debug those things in Windows. Sorry.

> In this case, Portable Linux might be best for your use-case. It has very
> few dependencies on system libraries.

Thank you.

**Comment by Eloston** [comment]
> - Haha. Maybe Windows Defender kill them? I really don't understand,
and happened twice.

Depending where you put it, Windows may be automatically removing your files. It's quite annoying. Also, Windows Defender is quite a complicated piece of software...
