### ISSUE TITLE
How do I pass --extension-mime-request-handling=install-always under Windows?

### ISSUE THREAD

**Issue by drogga3** [Eloston/ungoogled-chromium#879]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*

Version 78.0.3904.108

Already tried to pass it to the binary, not having an effect except if set with chrome://flags/#extension-mime-request-handling

**Comment by leo-liar** [comment]
Took me some experimenting but I use it as command line parameter like this:
`[...]\chrome.exe --extension-mime-request-handling=always-prompt-for-install`

(I think I found the exact wording by looking at `chrome://version/` in the command line section and there within "--flag-switches-begin/end" after having it activated in `chrome://flags/` before.)

**Comment by drogga3** [comment]
therefore instruction in https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md is false.

**Comment by Eloston** [comment]
There are also some `chrome://flags` that don't even resemble the expected flag name, such as `chrome://flags/#enable-force-dark`.

> therefore instruction in https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md is false.

Technically not true, they just didn't specify how to use all the flags correctly.

It might be more worthwhile to add instructions that tell users to check `chrome://version` to figure out what CLI flags will enable certain `chrome://flags`.

**Comment by leo-liar** [comment]
> It might be more worthwhile to add instructions that tell users to check chrome://version to figure out what CLI flags will enable certain chrome://flags.

Are there that many flags that require some specific value for their funtion? After a quick glance at https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md and `chrome://flags/` I've only found these 4:

  * `--extension-mime-request-handling` with the following values (besides `default`)
    * `download-as-regular-file`
    * `always-prompt-for-install`
  * `--scroll-tabs` with the following values (besides `default`)
    * `always`
    * `never`
  * `--show-avatar-button` with the following values (besides `default`)
    * `never`
    * `always`
    * `incognito-and-guest`
  * `--max-connections-per-host`
    * `6` (default)
    * `15`

And for `--extension-mime-request-handling` and `--show-avatar-button` I can confirm that these values are correct.
