### ISSUE TITLE
building error, step 6: -bash: ./out/Default/gn: Is a directory

### ISSUE THREAD

**Issue by GildedHonour** [Eloston/ungoogled-chromium#882]
https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md, step 6.

I do this:

`./out/Default/gn gen out/Default --fail-on-unused-args`

Error:

`-bash: ./out/Default/gn: Is a directory`

**Comment by Eloston** [comment]
Huh, so is the path to the binary `out/Default/gn/gn`?

**Comment by GildedHonour** [comment]
@Eloston  yes

**Comment by GildedHonour** [comment]
```
# ./out/Default/gn/gn gen out/Default --fail-on-unused-args
ERROR at //build/config/sysroot.gni:57:5: Assertion failed.
    assert(
    ^-----
Missing sysroot (//build/linux/debian_sid_amd64-sysroot). To fix, run: build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
See //build/config/sysroot.gni:58:9: 
        exec_script("//build/dir_exists.py",
        ^-----------------------------------
This is where it was set.
See //chrome/installer/BUILD.gn:7:1: whence it was imported.
import("//build/config/sysroot.gni")
^----------------------------------
See //BUILD.gn:67:5: which caused the file to be included.
    "//base:base_perftests",
    ^----------------------
```

**Comment by GildedHonour** [comment]
Is there a hack for now to make it compile ?

**Comment by Eloston** [comment]
Sure, have another look at the building instructions above where you're reading:

> The recommended way to build ungoogled-chromium is by consulting [the repository for your supported platform (links here)](platforms.md).
> 
> * *Linux users*: If your distribution is not listed, you will need to use Portable Linux.

and also

> **NOTE: This example is intended only for users who want to learn how ungoogled-chromium's build process works.** If you are simply trying to build and run ungoogled-chromium, please consult the [repository for your supported platform](platforms.md).

Finally:

> The following example demonstrates a typical build process. Please note that these steps alone will probably not be sufficient to get a working build.

**Comment by GildedHonour** [comment]
@Eloston re-read the whole issue.

**Comment by Eloston** [comment]
Sorry, I'm not understanding your point. If you just want to build ungoogled-chromium, you should not be using the Rough Example as a guide.

If you don't understand why you're getting the sysroot error, then you will probably run into a lot more problems along the way. To save time for us both, I highly recommend you follow the recommendations in the build instructions and use a platform repository. At the very least, they serve as concrete examples for how to build ungoogled-chromium.

**Comment by GildedHonour** [comment]
> If you just want to build ungoogled-chromium, you should not be using the Rough Example as a guide.

* No, I don't just want to do that.

**Comment by Eloston** [comment]
Well since I don't understand what your situation is, I am trying to provide the best advice I can give given what you've said here. If you'd like better advice, please clarify what you're trying to do.

I've only labeled this as a bug because `bootstrap.py` has changed its behavior, and the example needs to be updated. The sysroot issue is not a bug in ungoogled-chromium.

My guess for your sysroot problem is you didn't set `use_sysroot=false` in GN, or you didn't download the sysroot for your platform. For your reference, all our platform repos set `use_sysroot=false`.

Also, now that I have read the section again, I'll revise it to more clearly state its intended purpose. Thanks for bringing this up.

**Comment by GildedHonour** [comment]
Ok

How to set `use_sysroot=false` in GN?

**Comment by Eloston** [comment]
You can set it in your GN args.gn file, usually `out/Default/args.gn`. You can also provide it as a specific argument of `gn gen`.

**Comment by GildedHonour** [comment]
> You can also provide it as a specific argument of gn gen.

How?

**Comment by Eloston** [comment]
Use `gn gen --help` to find out. I don't recall off the top of my head.
