### ISSUE TITLE
SSDP / mDNS / Casting packets on start-up even if Media Router flag is disabled

### ISSUE THREAD

**Issue by sunrez** [Eloston/ungoogled-chromium#884]
**Bug:  When ungoogled chromium is first started, it sends m/DNS/SSDP packets looking for castable devices**

**Debugging:  I have gone to chrome://flags and disabled the following**
1.  Load Media Router Component Extension
2.  Connect to Cast devices on all IP addresses
3.  Cast Media Route Provider
4.  DIAL Media Route Provider

And used Wireshark to capture the packets on start-up

**Expected behavior**
1.  By default I would NOT expect ungoogled-chromium to have SSDP enabled or send these packets
2.  With flags disabled I wouldn't expect to see any SSDP/mDNS traffic

**Screenshots**
(Sorry direct attaching screenshots seemed to fail)
https://imgur.com/a/knPLJ6o
https://imgur.com/VZgPqFy
https://imgur.com/ktK2Nkt

**Environment:**
 - Debian Buster Linux
 - ungoogled-chromium version: ungoogled-chromium_78.0.3904.108-2.buster1

**Comment by xsmile** [comment]
The only way to avoid this type of traffic is to use a managed policy, see https://ungoogled-software.github.io/ungoogled-chromium-wiki/user-resources#disable-media-router, #436.

**Comment by Eloston** [comment]
Thanks @xsmile. Closing.
