### ISSUE TITLE
[Windows] Chromium alongside Ungoogled-C. problematic, not working properly.

### ISSUE THREAD

**Issue by nam108** [Eloston/ungoogled-chromium#885]
I am not a programmer so I apologize if it's a stupid question or something, but when I installed ungoogled-chromium alongside chromium on windows, it's not working properly and windows can't distinguish between them so that they are using same plugins, and have some common files used I guess, so I was wondering whether it would be possible and reasonable to somehow specify that ungoogled chromium is ungoogled chromium and not just chromium?

**Comment by lipici** [comment]
ungoogled chromium is better, no sense in using both, 
if you'll use firefox and firefox beta is same profile.

**Comment by nam108** [comment]
@lipici
I know it's better that's why it's my main browser, but I am usually using it with advance setting for umatrix+ublock and some sites not work and I don't want to risk [reading my details/contaminating the browser] etc. by checking which script allowance or whatever will fix the site, so for riskier jobs I would like to have another browser and chromium is closest to the needs I have. 

Putting this aside I was just wondering what is the reason that ungoogled chromium is installed just as chromium and not as ungoogled chromium.

**Comment by jstkdng** [comment]
ungoogled chromium is still technically chromium so it uses the same profile as normal chromium would.
You could run regular chromium with the ```--user-data-dir``` flag, and make it point to another directory different as ungoogled chromium's.

**Comment by nam108** [comment]
Thanks @jstkdng it works.
Could we be sure tho that there is non crucial considering privacy file being shared now?
Or it doesn't share anything now?

**Comment by jstkdng** [comment]
It shouldn't share anything, cookies, history, settings, extensions, etc, are all stored in the profile directory.

**Comment by Eloston** [comment]
Question looks solved. Closing.
