### ISSUE TITLE
Build failing on Windows 8.1

### ISSUE THREAD

**Issue by maciozo** [Eloston/ungoogled-chromium#89]
I'm unable to build
Using VS Community 2015 with the options specified in BUILDING.md, except for the Windows 10 SDK.

```
[3756/20445] ACTION Copying D3D Compiler DLL...
FAILED: d3dcompiler_47.dll
C:\Python27\python.exe gyp-win-tool action-wrapper environment.x86 copy_compiler_dll_target_copy_dll_a30e198148542d4bce19a5c818c6884f..rsp ..\..\third_party\angle\src
[3763/20445] LINK_EMBED bro.exe
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
  OptRef: Total time = 0.000s
  OptIcf: Total time = 0.000s
Pass 1: Interval #1, time = 0.578s
  Wait PDB close: Total time = 0.156s
  Wait type merge: Total time = 0.063s
Pass 2: Interval #2, time = 0.266s
Final: Total time = 0.844s
[3765/20445] LINK_EMBED mksnapshot.exe
ninja: build stopped: subcommand failed.
2016-10-07 12:07:19,795 - ERROR: ninja returned non-zero exit code: 1
```

**Comment by Eloston** [comment]
You need the Windows 10 SDK to build. It includes libraries and header files such as the `d3dcompiler_47.dll` that you are missing.

It should still work on Windows 8.1 even though the name doesn't seem to imply that.

Let me know if you run into other problems. I'll re-open the issue if you do.

**Comment by maciozo** [comment]
Well, that fixed the d3d problem. But now I've run in to another one. Seems that Bison is unhappy with something.

```
FAILED: gen/blink/core/XPathGrammar.cpp gen/blink/core/XPathGrammar.h
C:\Python27\python.exe gyp-win-tool action-wrapper environment.x86 make_core_generated_target_bison_fe4dcbb12ad96ef4dade61a9dbd3691f.29be8c7a8e7e566255f37ac5795d1bd2.rsp ..\..\third_party\WebKit\Source\core
xml\xpathgrammar.y:58: unrecognized: %parse_param
xml\xpathgrammar.y:58:    Skipping to next %
Traceback (most recent call last):
  File "../build/scripts/rule_bison.py", line 83, in <module>
    assert returnCode == 0
AssertionError
[4128/20445] LINK_EMBED(DLL) libEGL.dll
```

**Comment by Eloston** [comment]
I'm not exactly sure what happened here. Did you make sure you download and extracted all of the bison components listed in the build instructions?

**Comment by maciozo** [comment]
I think I did. I extracted the three archives and merged them all in to one folder (bison-2.4.1)
Then I added `C:\Chromium\bison-2.4.1\bin;C:\Chromium\bison-2.4.1\lib;C:\Chromium\bison-2.4.1\include` to PATH.

**Comment by Eloston** [comment]
I'm not really sure what's causing your problem. I also don't have a Windows 8.1 machine to test what's going on. I'll probably build a new Windows version sometime (on Windows 10), so if I run into this issue I'll be able to investigate more in-depth.

BTW, what version of Chromium are you trying to build? Are you building a x86 or x64 binary?

**Comment by maciozo** [comment]
chromium-53.0.2785.143 and x86. I haven't messed with any of the build scripts.

**Comment by Eloston** [comment]
> chromium-53.0.2785.143

Could you try 116 instead of 143? There is a remote chance that 143 could have broken bison. If it did, it would be much easier to narrow down the problem.

**Comment by maciozo** [comment]
Deleted the `build` directory, changed the version in `version.ini` to `53.0.2785.116`

```
[4102/20445] RULE make_core_generated: bison_fe4dcbb12ad96ef4dade61a9dbd3691f xml\XPathGrammar.y
FAILED: gen/blink/core/XPathGrammar.cpp gen/blink/core/XPathGrammar.h
C:\Python27\python.exe gyp-win-tool action-wrapper environment.x86 make_core_generated_target_bison_fe4dcbb12ad96ef4dade61a9dbd3691f.29be8c7a8e7e566255f37ac5795d1bd2.rsp ..\..\third_party\WebKit\Source\core
xml\xpathgrammar.y:58: unrecognized: %parse_param
xml\xpathgrammar.y:58:    Skipping to next %
Traceback (most recent call last):
  File "../build/scripts/rule_bison.py", line 83, in <module>
    assert returnCode == 0
AssertionError
[4110/20445] LINK_EMBED(DLL) libGLESv2.dll
```

**Comment by Eloston** [comment]
I did some digging and I think you also need to download Sources as well. I wrote these instructions after I setup the build environment, so I probably missed this component.

You can switch back to 143 since it makes no difference.

**Comment by maciozo** [comment]
Alright, downloaded the sources, merged them all in to the same `bison-2.4.1` directory, recloned this repo, and now I'm getting patching errors.

```
patching file `components/domain_reliability/uploader.cc'
patching file `components/domain_reliability/bake_in_configs.py'
Hunk #1 FAILED at 21.
Hunk #2 FAILED at 32.
2 out of 2 hunks FAILED -- saving rejects to components/domain_reliability/bake_in_configs.py.rej
2016-10-09 16:08:43,619 - ERROR: 'patch -p1' returned non-zero exit code 1
```

I'm not familiar with how patching works, but to me it looks like it's trying to remove a line that doesn't exist in `/components/domain_reliability/BUILD.gn`?

**Comment by maciozo** [comment]
Still fails
```

[3743/20445] LIB obj\v8\src\v8_base_3.lib
LINK : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance

[4109/20445] RULE make_core_generated: bison_fe4dcbb12ad96ef4dade61a9dbd3691fxml\XPathGrammar.y
FAILED: gen/blink/core/XPathGrammar.cpp gen/blink/core/XPathGrammar.h
C:\Python27\python.exe gyp-win-tool action-wrapper environment.x86 make_core_generated_target_bison_fe4dcbb12ad96ef4dade61a9dbd3691f.29be8c7a8e7e56625
5f37ac5795d1bd2.rsp ..\..\third_party\WebKit\Source\core
xml\xpathgrammar.y:58: unrecognized: %parse_param
xml\xpathgrammar.y:58:    Skipping to next %
Traceback (most recent call last):
  File "../build/scripts/rule_bison.py", line 83, in <module>
    assert returnCode == 0
AssertionError
[4116/20445] LINK_EMBED(DLL) libGLESv2.dll
LibDef: Total time = 0.047s
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
  OptRef: Total time = 0.000s
  OptIcf: Total time = 0.078s
Pass 1: Interval #1, time = 1.391s
  Wait PDB close: Total time = 0.297s
  Wait type merge: Total time = 0.016s
Pass 2: Interval #2, time = 0.500s
Final: Total time = 1.891s
[4118/20445] LINK_EMBED mksnapshot.exe
ninja: build stopped: subcommand failed.
2016-10-10 14:21:05,844 - ERROR: ninja returned non-zero exit code: 1
```

**Comment by Eloston** [comment]
I'm out of ideas now. I will be trying to setup and build on Windows 10 when I get the time to, so there may be a possibility that I may figure out what's going on here.

**Comment by maciozo** [comment]
Alright, turns out the problem was that my system was using GNU Patch 2.5 from WinAVR, rather than 2.7.5 from MSYS. x86 builds successfully now.

**Comment by Eloston** [comment]
Oh cool. Glad to hear it works. Though I'm wondering why there's a difference between the two.
