### ISSUE TITLE
Message: Can't update Chromium to latest version.

### ISSUE THREAD

**Issue by emanruse** [Eloston/ungoogled-chromium#890]
I am using 77.0.3865.90 built from source on openSUSE Leap 15.1 (I haven't had the time to build a newer version). Today I noticed something weird which I haven't seen in any version so far. The browser shows a message:

"Can't update Chromium

Chromium couldn't update to the latest version, so you are missing out on new features and security fixes."

On one hand this seems logical: it is ungoogled, so it cannot connect to Google.

OTOH though: how could the browser possibly know that it is out of date without checking if new version exists at all (and if the current one is the latest)? Is it that Google assumed that there will be a new build forever, so it can show this message merely based on clock time/date?

IOW: is it that the browser has made a background connection to some remote host or just the nonsense assumption of Google?

**Comment by kramred** [comment]
Probably an assumption based on the build/install date (did you build it ~84 days ago?), see `kOutdatedBuildAge` in [chrome/browser/upgrade_detector/upgrade_detector_impl.cc](https://chromium.googlesource.com/chromium/src/+/refs/tags/77.0.3865.90/chrome/browser/upgrade_detector/upgrade_detector_impl.cc#72)

```cpp
// The number of days after which we identify a build/install as outdated.
constexpr base::TimeDelta kOutdatedBuildAge = base::TimeDelta::FromDays(12 * 7);
```

See also `UPGRADE_NEEDED_OUTDATED_INSTALL_NO_AU` in the files in [chrome/browser/upgrade_detector](https://chromium.googlesource.com/chromium/src/+/refs/tags/77.0.3865.90/chrome/browser/upgrade_detector)

The code for the update bubble is in [chrome/browser/ui/views/outdated_upgrade_bubble_view.cc](https://chromium.googlesource.com/chromium/src/+/refs/tags/77.0.3865.90/chrome/browser/ui/views/outdated_upgrade_bubble_view.cc)

**Comment by emanruse** [comment]
> did you build it ~84 days ago?

The build date is 2019-10-02 which means:

30 days from October
30 days from November
14 days from December

Total: 74 days

This is less than 84 days ago.

**Comment by Eloston** [comment]
Is #721 related at all?

**Comment by emanruse** [comment]
> Is #721 related at all?

I don't know. I don't see an "Update is available" message.

BTW today the "arrow up" icon related to the message doesn't show on top right.

**Comment by kramred** [comment]
Even though it was not the 84 days I guessed from looking at the code, I'm pretty sure its an automatism that works without contacting Google as I've also seen it in Google Chrome on an offline system some time ago. One would have to track down the date that is actually used for the comparison (`base::TimeDelta::FromDays`) in the code…

Not sure if/how this is related to issue https://github.com/Eloston/ungoogled-chromium/issues/721

**Comment by Eloston** [comment]
Alright. We can probably just strip out the entire `upgrade_detector` unless someone here thinks the notifications could be useful somehow.

**Comment by emanruse** [comment]
> Alright. We can probably just strip out the entire `upgrade_detector` unless someone here thinks the notifications could be useful somehow.

Sounds good. If there is no actual upgrade detection, there is nothing useful in having notifications related to that.

**Comment by Eloston** [comment]
Is this still an issue in version 81?

**Comment by emanruse** [comment]
> Is this still an issue in version 81?

I have not noticed in 80.
I have built 81 yesterday.
Perhaps it's too early to confirm.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
