### ISSUE TITLE
An issue with CreateExtraView

### ISSUE THREAD

**Issue by PF4Public** [Eloston/ungoogled-chromium#891]
There is an error while compiling:
```
./../../chrome/browser/ui/views/confirm_bubble_views.cc:30:30: error: redefinition of 'CreateExtraView'
std::unique_ptr<views::View> CreateExtraView(views::ButtonListener* listener) {
                             ^  
./../../chrome/browser/ui/views/accessibility/invert_bubble_view.cc:50:30: note: previous 
definition is here
std::unique_ptr<views::View> CreateExtraView(views::ButtonListener* listener) {
                             ^ 
1 error generated.
```
Which is very weird. I think I remember seeing some patches dealing with "bubble-something", but cannot find them. Not sure, what could be causing this :(

Any idea is welcome.

[Cross-linking](https://github.com/PF4Public/gentoo-overlay/issues/20) just in case.

**Comment by Zoraver** [comment]
It's my understanding that this is related to [Google removing support for the jumbo build](https://groups.google.com/a/chromium.org/forum/?_escaped_fragment_=topic/chromium-dev/DP9TQszzQLI). Jumbo can cause anonymous namespaces in different files to collide, causing this issue; if they were still interested in supporting jumbo, I don't think they would be using anonymous namespaces. I was able to get Ungoogled-chromium to compile with jumbo by wrapping the anonymous namespace in confirm_bubble_views.cc with a unique (named!) namespace.

**Comment by PF4Public** [comment]
@Zoraver You're right. I've also figured out, that this has something to do with jumbo.
Nonetheless, thank you very-very much for pointing out, that Google had removed support for jumbo. Now it all makes sense to me!
