### ISSUE TITLE
Google Talk No incomming sound on windows or linux

### ISSUE THREAD

**Issue by SteelChickens** [Eloston/ungoogled-chromium#895]
I used the latest 78 development version. If I place an audio call the other side can hear me but I can't hear them.

This has happened on windows and on linux. Other browsers that use the google plugin work. I tried with all extensions disabled to make sure it wasn't one of them.

Funny thing is video chats work both ways.

**Comment by Eloston** [comment]
Does this FAQ section help you?: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-is-my-microphone-not-working

**Comment by SteelChickens** [comment]
On windows there is a talk plugin for firefox and ie 11. I'm unable to install it on linux of course. chrome is supposed to just work on both platforms.

**Comment by Eloston** [comment]
Do you have any errors show up in Developer Tools? How about in the syslog or terminal?

**Comment by SteelChickens** [comment]
Nothing in the terminal. This shows up in the console:

VM1311:96 Uncaught (in promise) DOMException: The play method is not allowed by the user agent.

**Comment by SteelChickens** [comment]
I think it was autoplay blocking extension that stayed on until I fired up chrome with all extensions disable switch.
