### ISSUE TITLE
as-needed.patch might be unneeded?

### ISSUE THREAD

**Issue by berkley4** [Eloston/ungoogled-chromium#896]
The description in fixes/as-needed.patch states that "some libraries fail to link when --as-needed is set", and changes this option to '--no-as-needed' in build/config/compiler/BUILD.gn.

But the latest ungoogled-chromium (debian) seems to compile and run okay if this patch is removed (in other words compiling with -Wl,--as-needed).

Since the patch seems to originate from Debian, I would tend to think the original problem was specific to gcc or bfd/gold (with clang/lld unaffected), or else is obsolete.

Perhaps this patch can be considered for removal?

**Comment by Eloston** [comment]
Thanks for the suggestion!
