### ISSUE TITLE
[Patchwork] How do you handle patches in general and/or maintaining them up to date?

### ISSUE THREAD

**Issue by PF4Public** [Eloston/ungoogled-chromium#897]
This is not a bug, but mere a 'discussion'-kind of things.

Maintaing Gentoo ebuild of ungoogled-chromium I often face the need to edit or/and update patches (those, that are not maintained by ungoogled, or Gentoo, or Debian, or whatever they are). I handle this either by manually editing the patch file itself in an ordinary text editor or editing the needed files and running `diff`.

This is rather tedious and time consuming. I wonder, if there are any other (more automated or something) ways of dealing with all this? Given that ungoogled-chromium constantly deals with patches, those who maintain it and other paltform repos ( @Eloston in particular) might have some experience to share? How do you handle this?

**Comment by Eloston** [comment]
When I first started ungoogled-chromium, I used to modify them by hand. Then I discovered that Debian uses `quilt` to manage patches. Now, managing patches is almost as easy as managing changes in a modern VCS.

If you want to get started with quilt, there are some [instructions in the development notes](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/developing.md#updating-patches). Most platform repos also document their own processes, but it's usually the same as this one with some slight modifications.

Currently, ungoogled-chromium structures patches in a quilt-compatible format; i.e. there is one directory `patches` that contains all patches, and a `patches/series` file that defines the order to apply them. [There are more details about the format in the design doc](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/design.md#patches). This applies to all platform repos in `ungoogled-software` as well.

However, the current workflows are not without their problems. Most notably, I think the process for updating to a new Chromium version is a bit cumbersome; it's not possible to update a platform repo's patches and ungoogled-chromium's patches in one shot (i.e. you have to run some commands to change from ungoogled-chromium's patches to the platform repo's patches). Another related problem is it's tedious to copy updated patches back to the source repos (e.g. the platform repo or the main ungoogled-chromium repo) after a build error. Ideally, there should be one command to handle domain substitution and the copying of patches in this scenario.

I'd also like to know how you all manage patches, and if you have suggestions for alternative workflows (e.g. a git-based workflow).

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
