### ISSUE TITLE
[Extension] UC closes Abruptly

### ISSUE THREAD

**Issue by alivefromupstairs** [Eloston/ungoogled-chromium#902]
**Describe the bug**
[LastPass](https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd) when attempting to `save` settings in the extension's options, `ungoogled-chromium` closes. 

**To Reproduce**
1. Install [LastPass](https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd) (no need to login).
2. Open Options from the extension's context menu.
3. Hit `save`
4. `ungoogled chromium` closes

**Expected behavior**
`ungoogled chromium` not to close.

**Environment**
 - Manjaro Linux 
 - ungoogled-chromium version: 79.0.3945.88

**Comment by qvint** [comment]
When you click the 'Save' button, the extension closes its tab. And since there are no other tabs, the browser shuts down.

https://support.google.com/chrome/forum/AAAAP1KN0B0PKDJgfyWYmQ

**Comment by alivefromupstairs** [comment]
Oh yeah, and if it's the last tab, changes do not take place. Weird one.
