### ISSUE TITLE
Add option to build ungoogled-chromium without PDF reader

### ISSUE THREAD

**Issue by TotalCaesar659** [Eloston/ungoogled-chromium#906]
The integrated PDF reader based on PDFium (the library for opening PDF files in Chromium) is enabled by default and often contain [vulnerabilities](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2019-13721). Adding option to build ungoogled-chromium without it (and switching PDF files to download) may remove additional attack vector and reduce building time.

**Comment by wchen342** [comment]
There is a GN flag `enable_pdf`.  Set it to `false` will stop building PDFium with Chromium.

**Comment by TotalCaesar659** [comment]
Thank you very much, I guess it can be closed now.
