### ISSUE TITLE
ungoogled-chromium-ozone 79.0.3945.79-1 not launching

### ISSUE THREAD

**Issue by GraveDigger1** [Eloston/ungoogled-chromium#915]
i just installed ungoogled-chromium-ozone 79.3945.79-1 on manjaro kde 18.1.5 testing build via manjaro's update / software manager. from what i can see it looks like it installed without issue, but when i try to launch ungoogled-chromium it does nothing. i do not even get a error message to post. i;ve done a logoff and a reboot and neither fixed the issue. suggestions on how to fix this would be greatly appreciated. thanks

**Comment by jstkdng** [comment]
Oh boy, ungoogled-chromium-ozone isn't related to this repository at all. Please reopen this issue in [ungoogled-chromium-archlinux](https://github.com/jstkdng/ungoogled-chromium-archlinux)

**Comment by GraveDigger1** [comment]
ok thanks, much appreciated. might want to fix the info aur has for github.
