### ISSUE TITLE
[Not an Issue - Clarification] How do builds differ?

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [Eloston/ungoogled-chromium#919]
So there's a fresh _79.0.3945.130-1_ build on [_this repo_](https://github.com/macchrome/winchrome/releases/tag/v79.0.3945.130-r706915-Win64) linked from [_chromium.woolyss.com_](https://chromium.woolyss.com/#Windows), and then there's [_this_](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/79.0.3945.117-1) _79.0.3945.117-1_, a bit older build, linked from [_here_](https://github.com/Eloston/ungoogled-chromium). 

Disregarding the build version, other than the latter being _~93MB_ and the first one _~64MB_ (i assume due to the compression algorithms one being _.7z_ and the other _.zip_), what is generally the difference between the builds? As i can tell both have the same maintainer and both have all the latest patches applied. 

![Download latest stable Chromium binaries (64-bit and 32-bit)](https://user-images.githubusercontent.com/17363930/73006984-e245a980-3e0b-11ea-95e6-76875d96120d.png)

**Comment by Eloston** [comment]
> As i can tell both have the same maintainer and both have all the latest patches applied.

Well based on the image you posted, it seems they excluded the patches that remove Safe Browsing. I don't know anything else about those builds.

**Comment by Vulgaris-Viridis** [comment]
Hi @Eloston I was wondering if these two projects are in any way related. Thank you for clarifying this.
