### ISSUE TITLE
Global command switches 

### ISSUE THREAD

**Issue by ci70** [Eloston/ungoogled-chromium#92]
Consider implementing this.  Would be very usefull for those who use a lot of command line switches.
https://bugs.chromium.org/p/chromium/issues/detail?id=598168#c1

**Comment by Eloston** [comment]
Hmm it's not a bad idea. But if you want this feature now, you could implement it via a wrapper script.

**Comment by reclaimer** [comment]
Yeah, it's not very relevant vs. the amount of work to get it in. Right?

**Comment by Eloston** [comment]
@reclaimer: I could include a wrapper script, but I was thinking about implementing this feature in the Chromium code.

**Comment by PF4Public** [comment]
A lot has changed since the time of filling of this issue. Is it still of interest?

**Comment by PF4Public** [comment]
Looks like there's nothing left to do regarding this issue — closing.
