### ISSUE TITLE
how to install adblock plus and ublock and other extensions ?

### ISSUE THREAD

**Issue by hydrogenpi** [Eloston/ungoogled-chromium#921]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*

how to install adblock plus and ublock and other extensions ?

**Comment by flesti** [comment]
[get the crx for your extension](https://chrome-extension-downloader.com/)
[unzip it](https://www.7-zip.org/)
go to chrome://extensions
check "developer mode"
click "load unpacked"

same for manually updating

**Comment by Eloston** [comment]
Please the the FAQ linked from the README.
