### ISSUE TITLE
jumbo is no more

### ISSUE THREAD

**Issue by PF4Public** [Eloston/ungoogled-chromium#928]
Just to let you all know, that `jumbo` is now buried:

> ERROR at //build/config/jumbo.gni:16:1: Assertion failed.
> assert(!use_jumbo_build,
> ^-----
> The jumbo build is no longer supported. Please remove any uses of 'use_jumbo_build', 'jumbo_build_excluded', or 'jumbo_file_merge_limit' from your args.gn file and re-run GN.
> See //media/media_options.gni:8:1: whence it was imported.
> import("//build/config/jumbo.gni")
> ^--------------------------------
> See //BUILD.gn:21:1: whence it was imported.
> import("//media/media_options.gni")
> ^---------------------------------
>

**Comment by wchen342** [comment]
Yeah just realized that when testing v80. This will make automatic building and testing even more difficult to do.

**Comment by jstkdng** [comment]
jumbo was already removed some releases ago, maybe just now google removed the legacy support code.

**Comment by tangalbert919** [comment]
When I made #927, I was very clear on that. All distros will need to remove those jumbo GN flags now, which (unfortunately) does increase compile time.

**Comment by PF4Public** [comment]
… _sigfnificantly_ increase compile time :(

```
2019-09-01T00:25:51 >>> www-client/ungoogled-chromium-72.0.3626.122_p1: 1 hour, 50 minutes, 5 seconds
2019-09-11T23:59:01 >>> www-client/ungoogled-chromium-76.0.3809.132_p1: 1 hour, 56 minutes, 39 seconds
2019-09-20T01:12:30 >>> www-client/ungoogled-chromium-77.0.3865.90_p1: 2 hours, 41 minutes, 24 seconds
2019-09-25T19:37:27 >>> www-client/ungoogled-chromium-77.0.3865.90_p1: 2 hours, 9 minutes, 15 seconds
2019-10-15T18:58:33 >>> www-client/ungoogled-chromium-77.0.3865.120_p1: 2 hours, 12 minutes, 9 seconds
2019-11-02T21:09:47 >>> www-client/ungoogled-chromium-78.0.3904.70_p1: 2 hours, 16 minutes, 58 seconds
2019-11-03T23:59:10 >>> www-client/ungoogled-chromium-78.0.3904.87_p1: 2 hours, 17 minutes, 48 seconds
2019-11-10T16:32:11 >>> www-client/ungoogled-chromium-78.0.3904.97_p1: 2 hours, 15 minutes, 51 seconds
2019-12-01T01:20:57 >>> www-client/ungoogled-chromium-78.0.3904.108_p2: 2 hours, 1 minute, 52 seconds
2019-12-19T05:19:56 >>> www-client/ungoogled-chromium-79.0.3945.79_p1: 2 hours, 56 minutes, 42 seconds
2019-12-21T18:45:44 >>> www-client/ungoogled-chromium-79.0.3945.88_p1: 2 hours, 36 minutes, 2 seconds
2020-01-10T02:25:50 >>> www-client/ungoogled-chromium-79.0.3945.117_p1: 2 hours, 36 minutes, 57 seconds
2020-01-20T22:56:26 >>> www-client/ungoogled-chromium-79.0.3945.130_p2: 2 hours, 38 minutes, 26 seconds
2020-02-07T19:06:21 >>> www-client/ungoogled-chromium-80.0.3987.87_p1: 6 hours, 15 minutes, 11 seconds
```

**Comment by jstkdng** [comment]
yeah, same, it doubled my compile times
![2020-02-09-094418_1273x581_scrot](https://user-images.githubusercontent.com/52050345/74104247-c5ee8000-4b20-11ea-82dd-7a2134e5e9a6.png)

**Comment by PF4Public** [comment]
Did anybody try building completely in tmpfs? Theoretically this could speed up the process.

**Comment by wchen342** [comment]
When I build through github actions it's (almost) completely tmpfs (well except the whole thing runs in a docker). It still takes more than 6 hours. I can try again on my own machine but I don't think it will magically speed up things a lot.

By the way will `ccache` speed up things? I'm thinking if it does then maybe we can share the cache somehow?

**Comment by jstkdng** [comment]
@PF4Public 
I used to use a vps with enough resources with arch in order to build, and it took ~1 hour (when jumbo was still a thing).

@wchen342 
I think that is because in the PKGBUILD ninja is only using a single thread, maybe using the `-j $(nproc)` option could help. And afaik ccache only helps with subsequent builds, not initial ones. I think Github uses a clean env for every build.

**Comment by wchen342** [comment]
@jstkdng 

> I think that is because in the PKGBUILD ninja is only using a single thread

That is not true. `ninja` defaults to multi thread, unlike `make`. I just tested on my own machine and can confirm that is the case.

> ccache only helps with subsequent builds, not initial ones.

So my idea is, if each build doesn't differ too much (like between minor versions), then once we have an initial build with `ccache`, maybe we can put the cache from that inital build into a tarball and use it for all the builds afterwards?

**Comment by jstkdng** [comment]
That is a really crazy idea, and the tarball would be huge in size. I'm not sure if it would work tho, just go for it if you have the internet speed to upload the tarball somewhere.

**Comment by PF4Public** [comment]
tmpfs seems to be of no help unfortunately :(
One system:
```
2020-03-11T10:45:41 >>> www-client/ungoogled-chromium: 9 hours, 48 minutes, 24 seconds
2020-03-15T22:05:16 >>> www-client/ungoogled-chromium: 9 hours, 56 minutes, 22 seconds
```
Another one:
```
2020-03-11T13:02:02 >>> www-client/ungoogled-chromium: 6 hours, 16 minutes, 5 seconds
2020-03-16T03:41:29 >>> www-client/ungoogled-chromium: 6 hours, 16 minutes, 44 seconds
```
Last one is on the tmpfs

Comparing other packages:
```
2020-02-10T19:29:36 >>> app-office/libreoffice: 1 hour, 12 minutes, 43 seconds
2020-03-15T23:12:02 >>> app-office/libreoffice: 1 hour, 8 minutes, 55 seconds
```
```
2020-03-03T21:14:45 >>> dev-lang/rust: 48 minutes, 33 seconds
2020-03-15T21:58:30 >>> dev-lang/rust: 45 minutes, 30 seconds
```
```
2019-11-18T17:31:22 >>> app-emulation/wine-vanilla: 16 minutes, 22 seconds
2020-03-16T00:26:24 >>> app-emulation/wine-vanilla: 17 minutes, 41 seconds
```
```
2020-03-15T06:01:10 >>> www-client/firefox: 1 hour, 35 minutes, 1 second
2020-03-16T02:02:40 >>> www-client/firefox: 1 hour, 29 minutes, 42 seconds
```

**Comment by sinetek** [comment]
Would there be interest in a patch to put jumbo builds back in?
I think it can be done..

**Comment by PF4Public** [comment]
> I think it can be done..

True, but with Google removing more and more code, it could become more and more painful maintaining such a patch.

**Comment by Eloston** [comment]
@sinetek I have an idea kicking around but I don't know how feasible it is.

I believe main problem with Jumbo is that non-exported symbols can conflict when you combine translation units together. If this is the only problem with Jumbo builds, then it is possible to determine the translation units that can be combined. (Or inversely, the translation units that cannot belong together. I think the frequency of the collisions should determine which implementation is more efficient.) Once you have this information, then you'll need to do is make GN produce jumbo'd Ninja build files, and everything else is pretty straight-forward.

However, there are two problems we'd need to overcome:

1. I don't know how much work we'd need to make GN produce Jumbo builds.
2. I might be wrong and there may be more problems that make it difficult to automatically determine which translation units can be combined. It's entirely possible that after considering all the potential issues, there's not much of an advantage to this approach.

This is not a high-priority for me, so this might be all I want to contribute for now.

**Comment by sinetek** [comment]
@Eloston Yes, that is correct.

I went ahead and investigated this. The result is a patch that enables jumbo-build on Ungoogled Chromium. There are a few instances of conflicting symbols, currently there are three.

chromium-80-jumbo-builds.patch :
```
--- a/build/config/jumbo.gni  2020-04-11 19:11:51.979131201 +0200
+++ b/build/config/jumbo.gni  2020-04-11 19:17:26.472451060 +0200
@@ -6,18 +6,42 @@
 import("//build/toolchain/goma.gni")
 
 declare_args() {
+  # If true, use a jumbo build (files compiled together) to speed up
+  # compilation.
   use_jumbo_build = false
+
+  # A list of build targets to exclude from jumbo builds, for optimal
+  # round trip time when frequently changing a set of cpp files. The
+  # targets can be just the short name (in which case it matches any
+  # target with that name), a directory prefixed with the root
+  # specifier //, or a full build target label.
+  #
+  # Example:
+  # These would all exclude the "browser" target in a file
+  # content/browser/BUILD.gn, and potentially more.
+  #
+  # jumbo_build_excluded = [ "browser" ]
+  # jumbo_build_excluded = [ "//content/browser" ]
+  # jumbo_build_excluded = [ "//content/browser:browser" ]
   jumbo_build_excluded = []
+
+  # How many files to group on average. Smaller numbers give more
+  # parallellism, higher numbers give less total CPU usage. Higher
+  # numbers also give longer single-file recompilation times.
+  #
+  # Recommendations:
+  # Higher numbers than 100 does not reduce wall clock compile times
+  # even for 4 cores or less so no reason to go higher than 100.
+  # Going from 50 to 100 with a 4 core CPU saves about 3% CPU time and
+  # 3% wall clock time in a tree with blink, v8 and content
+  # jumbofied. At the same time it increases the compile time for the
+  # largest jumbo chunks by 10-20% and reduces the chance to use all
+  # available CPU cores. So set the default to 50 to balance between
+  # high and low-core build performance. -1 means do the default which
+  # varies depending on whether goma is enabled.
   jumbo_file_merge_limit = -1
 }
 
-# TODO(crbug.com/994387): Remove all uses of the jumbo_* templates from the
-# BUILD.gn files, and then remove this whole file.
-assert(!use_jumbo_build,
-       "The jumbo build is no longer supported. Please remove any uses of " +
-           "'use_jumbo_build', 'jumbo_build_excluded', or " +
-           "'jumbo_file_merge_limit' from your args.gn file and re-run GN.")
-
 # Normal builds benefit from lots of jumbification
 jumbo_file_merge_default = 50

--- a/v8/gni/v8.gni   2020-04-11 19:11:32.232465323 +0200
+++ b/v8/gni/v8.gni   2020-04-11 19:56:48.159023051 +0200
@@ -2,6 +2,7 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
+import("//build/config/jumbo.gni")
 import("//build/config/sanitizers/sanitizers.gni")
 import("//build/config/v8_target_cpu.gni")
 import("split_static_library.gni")
@@ -70,7 +71,7 @@
   # build configuration. This allows us to set v8_use_multi_snapshots=true on
   # all bots, and e.g. no-snapshot bots will automatically do the right thing.
   v8_use_multi_snapshots =
-      v8_use_external_startup_data && !build_with_chromium
+      v8_use_external_startup_data && !build_with_chromium && !use_jumbo_build
 }
 
 if (v8_enable_backtrace == "") {
@@ -139,9 +140,9 @@
       defined(v8_static_library) && v8_static_library && is_win) {
     link_target_type = "split_static_library"
   } else if (defined(v8_static_library) && v8_static_library) {
-    link_target_type = "static_library"
+    link_target_type = "jumbo_static_library"
   } else {
-    link_target_type = "source_set"
+    link_target_type = "jumbo_source_set"
   }
   target(link_target_type, target_name) {
     forward_variables_from(invoker,
@@ -160,7 +161,7 @@
 }
 
 template("v8_header_set") {
-  source_set(target_name) {
+  jumbo_source_set(target_name) {
     forward_variables_from(invoker, "*", [ "configs" ])
     configs -= v8_remove_configs
     configs += v8_add_configs
--- a/third_party/blink/renderer/platform/fonts/font_matching_metrics.cc 2020-04-11 19:11:33.505798604 +0200
+++ b/third_party/blink/renderer/platform/fonts/font_matching_metrics.cc 2020-04-11 20:31:54.822271813 +0200
@@ -15,7 +15,7 @@
 enum FontLoadContext { kTopLevel = 0, kSubFrame };

 template <typename T>
-HashSet<T> Intersection(const HashSet<T>& a, const HashSet<T>& b) {
+HashSet<T> HSIntersection(const HashSet<T>& a, const HashSet<T>& b) {
   HashSet<T> result;
   for (const T& a_value : a) {
     if (b.Contains(a_value))
@@ -52,16 +52,16 @@
   ukm::builders::FontMatchAttempts(source_id_)
       .SetLoadContext(top_level_ ? kTopLevel : kSubFrame)
       .SetSystemFontFamilySuccesses(ukm::GetExponentialBucketMin(
-          Intersection(successful_font_families_, system_font_families_).size(),
+          HSIntersection(successful_font_families_, system_font_families_).size(),
           kUkmFontLoadCountBucketSpacing))
       .SetSystemFontFamilyFailures(ukm::GetExponentialBucketMin(
-          Intersection(failed_font_families_, system_font_families_).size(),
+          HSIntersection(failed_font_families_, system_font_families_).size(),
           kUkmFontLoadCountBucketSpacing))
       .SetWebFontFamilySuccesses(ukm::GetExponentialBucketMin(
-          Intersection(successful_font_families_, web_font_families_).size(),
+          HSIntersection(successful_font_families_, web_font_families_).size(),
           kUkmFontLoadCountBucketSpacing))
       .SetWebFontFamilyFailures(ukm::GetExponentialBucketMin(
-          Intersection(failed_font_families_, web_font_families_).size(),
+          HSIntersection(failed_font_families_, web_font_families_).size(),
           kUkmFontLoadCountBucketSpacing))
       .Record(ukm_recorder_);
 }
--- a/storage/browser/quota/quota_settings.cc 2020-04-11 19:11:56.809131010 +0200
+++ b/storage/browser/quota/quota_settings.cc 2020-04-11 21:16:14.728831862 +0200
@@ -21,7 +21,7 @@
 
 namespace {
 
-const int64_t kMBytes = 1024 * 1024;
+const int64_t QSkMBytes = 1024 * 1024;
 const int kRandomizedPercentage = 10;
 
 // Skews |value| by +/- |percent|.
@@ -35,7 +35,7 @@
   // The incognito pool size is a fraction of the amount of system memory,
   // and the amount is capped to a hard limit.
   double incognito_pool_size_ratio = 0.1;  // 10%
-  int64_t max_incognito_pool_size = 300 * kMBytes;
+  int64_t max_incognito_pool_size = 300 * QSkMBytes;
   if (base::FeatureList::IsEnabled(features::kIncognitoDynamicQuota)) {
     const double lower_bound = features::kIncognitoQuotaRatioLowerBound.Get();
     const double upper_bound = features::kIncognitoQuotaRatioUpperBound.Get();
--- a/chrome/browser/performance_manager/decorators/process_priority_aggregator.cc       2020-04-11 19:11:54.455797767 +0200
+++ b/chrome/browser/performance_manager/decorators/process_priority_aggregator.cc    2020-04-11 21:39:36.945442260 +0200
@@ -22,15 +22,15 @@
 
 namespace {
 
-class DataImpl : public ProcessPriorityAggregator::Data,
-                 public NodeAttachedDataImpl<DataImpl> {
+class PPADataImpl : public ProcessPriorityAggregator::Data,
+                 public NodeAttachedPPADataImpl<PPADataImpl> {
  public:
   using StorageType = ProcessPriorityAggregatorAccess::StorageType;
 
   struct Traits : public NodeAttachedDataOwnedByNodeType<ProcessNodeImpl> {};
 
-  explicit DataImpl(const ProcessNode* process_node) {}
-  ~DataImpl() override {}
+  explicit PPADataImpl(const ProcessNode* process_node) {}
+  ~PPADataImpl() override {}
 
   static std::unique_ptr<NodeAttachedData>* GetUniquePtrStorage(
       ProcessNodeImpl* process_node) {
@@ -106,7 +106,7 @@
 // static
 ProcessPriorityAggregator::Data* ProcessPriorityAggregator::Data::GetForTesting(
     ProcessNodeImpl* process_node) {
-  return DataImpl::Get(process_node);
+  return PPADataImpl::Get(process_node);
 }
 
 ProcessPriorityAggregator::ProcessPriorityAggregator() = default;
@@ -114,7 +114,7 @@
 
 void ProcessPriorityAggregator::OnFrameNodeAdded(const FrameNode* frame_node) {
   auto* process_node = ProcessNodeImpl::FromNode(frame_node->GetProcessNode());
-  DataImpl* data = DataImpl::Get(process_node);
+  PPADataImpl* data = PPADataImpl::Get(process_node);
   data->Increment(frame_node->GetPriorityAndReason().priority());
   // This is a nop if the priority didn't actually change.
   process_node->set_priority(data->GetPriority());
@@ -123,7 +123,7 @@
 void ProcessPriorityAggregator::OnBeforeFrameNodeRemoved(
     const FrameNode* frame_node) {
   auto* process_node = ProcessNodeImpl::FromNode(frame_node->GetProcessNode());
-  DataImpl* data = DataImpl::Get(process_node);
+  PPADataImpl* data = PPADataImpl::Get(process_node);
   data->Decrement(frame_node->GetPriorityAndReason().priority());
   // This is a nop if the priority didn't actually change.
   process_node->set_priority(data->GetPriority());
@@ -140,7 +140,7 @@
   // Update the distinct frame priority counts, and set the process priority
   // accordingly.
   auto* process_node = ProcessNodeImpl::FromNode(frame_node->GetProcessNode());
-  DataImpl* data = DataImpl::Get(process_node);
+  PPADataImpl* data = PPADataImpl::Get(process_node);
   data->Decrement(previous_value.priority());
   data->Increment(new_value.priority());
   // This is a nop if the priority didn't actually change.
@@ -160,8 +160,8 @@
 void ProcessPriorityAggregator::OnProcessNodeAdded(
     const ProcessNode* process_node) {
   auto* process_node_impl = ProcessNodeImpl::FromNode(process_node);
-  DCHECK(!DataImpl::Get(process_node_impl));
-  DataImpl* data = DataImpl::GetOrCreate(process_node_impl);
+  DCHECK(!PPADataImpl::Get(process_node_impl));
+  PPADataImpl* data = PPADataImpl::GetOrCreate(process_node_impl);
   DCHECK(data->IsEmpty());
   DCHECK_EQ(base::TaskPriority::LOWEST, process_node_impl->priority());
   DCHECK_EQ(base::TaskPriority::LOWEST, data->GetPriority());
@@ -171,7 +171,7 @@
     const ProcessNode* process_node) {
 #if DCHECK_IS_ON()
   auto* process_node_impl = ProcessNodeImpl::FromNode(process_node);
-  DataImpl* data = DataImpl::Get(process_node_impl);
+  PPADataImpl* data = PPADataImpl::Get(process_node_impl);
   DCHECK(data->IsEmpty());
 #endif
 }
```

**Comment by sinetek** [comment]
Here is my work. It works for `ungoogled-chromium-80.0.3987.163_p1.ebuild`, but the -81 needs a few minor fixes.

https://github.com/sinetek/pf4-jumbo
https://github.com/sinetek/pf4-jumbo/commit/403b81ccf9c9af2ddb681b039d05b9b6dc745694

In my opinion this is easy enough to maintain for the gains it brings. It's at most 1-2 fixes per new revision.

**Comment by PF4Public** [comment]
@sinetek Have you tried removing `jumbo_file_merge_limit`? This makes it 50, which should make it even faster, but guarantees more namespace clashes.

**Comment by sinetek** [comment]
I haven't tried, there would be diminishing returns at one point. The old
behaviour in your ebuild is 8. That is easily tunable.

Regarding the commit, it seems I have a bit more work to do on it because a
few other conflicts have come up.

There is a way to simply add files to the ignore list instead of manually
patching every little compiler nit. A few exceptions will not extend the
build time by anything, that's what I will go back and do.


Help appreciated for integration, bug fixing or benching.

**Comment by PF4Public** [comment]
> The old behaviour in your ebuild is 8

I had to lover it from default 50 at some point, when namespace clashes started to occur.

>there would be diminishing returns at one point.

… at around 100 ;) But you will anyway need lots (of lots) of RAM then.

[Jumbo - bringing shorter compile times to you](https://docs.google.com/document/d/19jGsZxh7DX8jkAKbL1nYBa5rcByUL2EeidnYsoXfsYQ/edit#)
![image](https://user-images.githubusercontent.com/10319700/79057872-ca452f80-7c6e-11ea-9305-39a482df801a.png)

**Comment by sinetek** [comment]
Awesome that you have this information. This is an incredible speedup. For
the ebuild we should have it either ask for N or have it pulled out of an
environment variable.

All the conflicts can just go to the exception list.

Thoughts?

**Comment by sinetek** [comment]
One came up to mind just after posting. As you know the OOM response on
Linux is extremely poor, we should check RAM or at least make it hard to
load N=500 on a 8GB system... That would require a reboot, probably.

**Comment by Eloston** [comment]
> As you know the OOM response on
Linux is extremely poor, we should check RAM or at least make it hard to
load N=500 on a 8GB system... 

I agree, also there's no good way to communicate memory usage to the compiler. I think the best we can do is to use cgroups to limit the memory usage to some percentage of the total memory (or a fixed number). There are some nice examples on ArchWiki: https://wiki.archlinux.org/index.php/cgroups

**Comment by PF4Public** [comment]
>have it pulled out of an environment variable

`EXTRA_GN` is already available in Gentoo:
`set -- gn gen --args="${myconf_gn} ${EXTRA_GN}" out/Release`

>All the conflicts can just go to the exception list.

That's fine, several exceptions are fine, I suppose. But if this list grows bigger and bigger due to Google efforts…

>we should check RAM

>use cgroups

I'd suggest against overcomplicating things. It used to work fine with 50, cut almost half the compile time and nobody requested to lower it (on Gentoo and from my ebuild at least). I have never had a single OOM while compiling myself in a kvm-guest. Even RAM usage was never observed to be higher than 4-6 gigs. I admit, that compiling Chromium is a lengthy process and RAM usage might have peaked at some point, when I was not looking at it. I also admit, that I compile it in a kvm-guest with 16-19 GB of dedicated RAM, but still… The biggest issue here is to patch back jumbo support.

If @sinetek succeeds in making this patch, we will have some more things to discuss.
* Where does this patch belong? Options are: 
    * Here in this particular repo. If that's the case, @Eloston might have a say on the subject.
    * Platform repos. In this case, there would be a issue on how to syncronise this patch across all the repos. My Gentoo overlay for example does not use portable-linux repo, only this one.
* This patch needs to be maintained from version to version. Who's going to be doing this?

**Comment by Eloston** [comment]
I don't think the patch proposed in https://github.com/Eloston/ungoogled-chromium/issues/928#issuecomment-612523039 is sustainable in the long-term. Patching the source code to fix symbol conflicts can only become more difficult after each new version, especially as Google has stated that they will not guarantee Jumbo compatibility. Not to mention renaming symbols will probably break tests too. We don't want another patch that keeps growing in complexity like Safe Browsing patches.

My approach in https://github.com/Eloston/ungoogled-chromium/issues/928#issuecomment-612317405 does not require modifying the source code (aside from some GN changes), and instead statically analyzes all symbol conflicts before the build. However, this approach is also non-trivial; creating this tool, testing it, and optimizing its performance (I suspect it might be challenging in both runtime and memory usage) will take some time.

**Comment by PF4Public** [comment]
I think, I will close this issue, as there was not much of a discussion recently and re-implementing jumbo seems prohibitively complicated at the moment.

If at a later time something changes, one could continue the discussion and reopen the issue.

**Comment by benjamasu** [comment]
Perhaps [Clang modules](https://clang.llvm.org/docs/Modules.html) can do the thing? 

> The primary user-level feature of modules is the import operation, which provides access to the API of software libraries. However, today’s programs make extensive use of #include, and it is unrealistic to assume that all of this code will change overnight. Instead, modules automatically translate #include directives into the corresponding module import. For example, the include directive
> ```
> #include <stdio.h>
> ```
> will be automatically mapped to an import of the module std.io. Even with specific import syntax in the language, this particular feature is important for both adoption and backward compatibility: automatic translation of #include to import allows an application to get the benefits of modules (for all modules-enabled libraries) without any changes to the application itself. Thus, users can easily use modules with one compiler while falling back to the preprocessor-inclusion mechanism with other compilers.

**Comment by benjamasu** [comment]
I'm trying to build Chromium with `-fmodules` in cflags. It seems to work, as the directory I specified in `-fmodules-cache-path` is populated. I'll check out the size of the cache produced and whether this out of the box affects build speed.

**Comment by benjamasu** [comment]
Perhaps the [Clang modules](https://clang.llvm.org/docs/Modules.html) will do the trick? 

Maintaining the patch would probably be much easier than with jumbo build's one. 

> The primary user-level feature of modules is the import operation, which provides access to the API of software libraries. However, today’s programs make extensive use of #include, and it is unrealistic to assume that all of this code will change overnight. Instead, modules automatically translate #include directives into the corresponding module import. For example, the include directive
> ```
> #include <stdio.h>
> ```
> will be automatically mapped to an import of the module std.io. Even with specific import syntax in the language, this particular feature is important for both adoption and backward compatibility: automatic translation of #include to import allows an application to get the benefits of modules (for all modules-enabled libraries) without any changes to the application itself. Thus, users can easily use modules with one compiler while falling back to the preprocessor-inclusion mechanism with other compilers.

Just need to make a module map for all (or almost) header files that are used in-tree when building Chromium. 
Extra Clang utility [modularize](https://clang.llvm.org/extra/modularize.html) generates a module map based on the list of header files.

**Comment by PF4Public** [comment]
> Perhaps the [Clang modules](https://clang.llvm.org/docs/Modules.html) will do the trick?

Could you please elaborate on how clang's module system could help? I have an impression of it being orthogonal to the problem of long building time of Chromium.

**Comment by benjamasu** [comment]
> Could you please elaborate on how clang's module system could help?

Clang modules use PCH (Precompiled Headers) to automatically cache built modules. Because of this, each module only needs to be built once.

There's a problem with modules that header files have to conform to certain practices.

> Note that headers with dependents will be ignored with a warning, as the Clang module mechanism doesn’t support headers that rely on other headers being included first.

I wrote a script to generate a dependency tree of header files. According to rough calculations (just using `find`), out of ~120,000 header files, ~40,000 are being excluded by `modularize`.

While effective use of Clang modules does not require major changes to the build system, it will probably require code refactoring, which is why the Chromium development team rejected this option as an alternative to jumbo builds.

However, it should be possible to use PCH, which should not require changes in the code, but in the build system definitely. 

Cmake is supported natively by PCH. Libreoffice has been providing support for building with PCH for quite some time now

**Comment by PF4Public** [comment]
> @PF4Public, Clang modules use PCH (Precompiled Headers) to automatically cache built modules. Because of this, each module only needs to be built once.

You're not telling that among 50-60 thousand compile targets, that Chromium builds, most are duplicates, are you?

**Comment by benjamasu** [comment]
> You're not telling that among 50-60 thousand compile targets, that Chromium builds, most are duplicates, are you?
@PF4Public, when building C/C++ code dependencies are ‘included’, i.e. the compiler ends up processing one big ‘file’. In this case, headers are processed more times than necessary, because for each translation unit (target) the compiler needs to process all included dependencies. Doesn't it? That's why jumbo build helps, because it reduces the number of duplicate header processing.

**Comment by benjamasu** [comment]
By the way, there is already some support for precompiled headers in Chromium, but it was implemented long before LLVM 11 was released in 2020, in which PCHs were redesigned, and offers no real advantage, especially on Linux.

**Comment by benjamasu** [comment]
> While effective use of Clang modules does not require major changes to the build system, it will probably require code refactoring, which is why the Chromium development team rejected this option as an alternative to jumbo builds.

 The relevant discussion can be found [here](https://discourse.llvm.org/t/jumbosupport-making-unity-builds-easier-in-clang/48269).
 
 > As a data point: Inside Chromium the time to process headers is typically 80-95% of the total time processing a cc file. Maybe not surprising when the headers are around 240k lines, and the cc files themselves 50-500 lines.

**Comment by philmb3487** [comment]
I don’t think there is much we can do at this point. Perhaps Google will work on it.

**Comment by implicitfield** [comment]
Just saw that termux has a [patch set](https://github.com/termux-user-repository/tur/tree/master/tur/chromium-beta-host-tools/jumbo-patches) that reintroduces support for jumbo builds. It's very much non-trivial though:
```
wc -l tur/chromium-beta-host-tools/jumbo-patches/*
[snip]
   26350 total
```
