### ISSUE TITLE
How can I install ungoogled-chromium on my Debian Jessie?

### ISSUE THREAD

**Issue by tonowoe** [Eloston/ungoogled-chromium#93]
How can I install `ungoogled-chromium` on my Debian Jessie? I think I have to build it manually, there's no simple way (yet)? I tried to build it with the instructions found in "Building" page, but I'm not really sure what I should do.

This is what I've tried:

We need `Python 3` and `Python 2` and `Ninja` to use `buildlib`, which is used to install `ungoogled-chromium`:

```
user@debian:~$ python3 --version
Python 3.4.2

user@debian:~$ python2 --version
Python 2.7.9

user@debian:~$ apt-get install ninja-build
```

Because we are using Debian Jessie, we need to do extra steps:

_"Note for Debian Jessie users: ungoogled-chromium is configured to build against the system's FFmpeg (available in Stretch and onwards); Libav (used in Jessie) will not work. However, FFmpeg is available in jessie-backports. To install it, add jessie-backports to the apt sources, and then install libavutil-dev, libavcodec-dev, and libavformat-dev from it. Note that this will replace Libav."_

Okay, let's add jessie-backports to our sources.list:

- Open and edit `/etc/apt/sources.list`
- Add this to the file `deb http://httpredir.debian.org/debian jessie-backports main`
- Save and exit
- Update and upgrade: `sudo apt-get update && sudo apt-get upgrade`
- Now we need to install the `libavutil-dev`, `libavcodec-dev`, and `libavformat-dev` packages:

`sudo apt-get install libavutil-dev libavcodec-dev libavformat-dev`

Let's download the `ungoogled-chromium`:

```
wget https://github.com/Eloston/ungoogled-chromium/archive/master.zip
unzip master.zip
cd ungoogled-chromium-master
```

Okay, we have everything ready to go. Now we need to "invoke"(?) the `build.py` to install the `ungoogled-chromium`:

```
chmod +x build.py
./build.py
```

This is as far as I can go. `build.py` [throws me an error and the building will fail](http://pastebin.com/raw/p5mHDjR5).

**What am I doing wrong?**

**Comment by 9Morello** [comment]
Try to build [a tag release](https://github.com/Eloston/ungoogled-chromium/releases) instead of the master branch.

**Comment by Eloston** [comment]
[This looks like a feature introduced in Python 3.5](https://www.python.org/dev/peps/pep-0448/). Python 3.5 is the default Python 3 version on Debian Stretch, so I hadn't realized I've broken Python 3.4 support. I'll make a quick fix.

**Comment by tonowoe** [comment]
Thanks for the fix, but I still do get an error. Now when I'm trying to run the `build.py` [it will give me this error](http://pastebin.com/raw/nUCUqN1J). _AttributeError: 'module' object has no attribute 'run'_


I did some Googling [and I found this](https://github.com/winksaville/vendor-install-tools/issues/2). What should I do?

I really wouldn't want to manually update my python because in Debian Jessie the [latest python version](http://pastebin.com/raw/eAexB07Q) is 3.4.2.

Thank you.
