### ISSUE TITLE
GN flag optimize_webui in Chromium 80

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#932]
Now that it seems we need Node.js for Chromium 80, can we turn on `optimize_webui` without breaking the build or needing additional dependencies?

**Comment by PF4Public** [comment]
Shouldn't build tools be able to find node without 'optimize_webui'?

**Comment by Eloston** [comment]
@PF4Public Yes, but the reason why we disabled `optimize_webui` to begin with is because we didn't want to include a Node.js dependency. Now that Chromium 80 requires it, we might as well turn on some additional optimizations.

**Comment by jstkdng** [comment]
can flags be overriden from the distribution repositories themselves?

**Comment by PF4Public** [comment]
>can flags be overriden from the distribution repositories themselves?

Last flag in gn args wins. I use it, for example, to conditionally overthrow `use_lld=false`, which goes first in my ebuild.

>Now that Chromium 80 requires it, we might as well turn on some additional optimizations.

Could these optimisations do any harm if enabled by default?

**Comment by Eloston** [comment]
> can flags be overriden from the distribution repositories themselves?

If you mean override a value that is set in `flags.gn`, then technicall yes. But, I don't like overriding flags because it can become confusing. If there's a flag setting that needs to be overridden, we should consider moving it out of `flags.gn` and into the platform repos.

> Could these optimisations do any harm if enabled by default?

Considering `optimize_webui` is enabled by default in Chromium (i.e. it is set to true if we don't include it in `flags.gn`), it should not break anything. If it does, then we have a bug to fix.

**Comment by jstkdng** [comment]
>Could these optimisations do any harm if enabled by default?

If anything it could make debugging problems in the UI a bit harder, like #930 , since everything would be minified.

**Comment by jstkdng** [comment]
Ok, just tested the flag and it only reduced the binary size by ~1.5mb
