### ISSUE TITLE
[Question] It's legit? I mean the part with version 80

### ISSUE THREAD

**Issue by lipici** [Eloston/ungoogled-chromium#933]
https://www.techspot.com/downloads/7181-ungoogled-chromium.html

**Comment by braewoods** [comment]
They're still working out the issues with the new major release. There's no binary releases for it as of yet.

**Comment by braewoods** [comment]
@Eloston, I think this should be closed as the "issue" has been resolved.

**Comment by PF4Public** [comment]
Although this quote from readme is concerned with binaries from https://ungoogled-software.github.io/ungoogled-chromium-binaries/ , I think, it is also applicable here:

> NOTE: These binaries are provided by anyone who are willing to build and submit them. Because these binaries are not necessarily reproducible, authenticity cannot be guaranteed; In other words, there is always a non-zero probability that these binaries may have been tampered with. In the unlikely event that this has happened to you, please report it in a new issue.
