### ISSUE TITLE
[Question] Is it safe to download compiled binaries from this source ?

### ISSUE THREAD

**Issue by Lucifer879** [Eloston/ungoogled-chromium#936]
Website - https://chromium.woolyss.com

![Chromium](https://user-images.githubusercontent.com/48880976/74303619-832ae300-4d80-11ea-85df-2d06152f8d9d.png)

GitHub Release - https://github.com/macchrome/winchrome/releases

**Comment by PF4Public** [comment]
Although this quote from readme is concerned with binaries from https://ungoogled-software.github.io/ungoogled-chromium-binaries/ , I think, it is also applicable here:

> NOTE: These binaries are provided by anyone who are willing to build and submit them. Because these binaries are not necessarily reproducible, authenticity cannot be guaranteed; In other words, there is always a non-zero probability that these binaries may have been tampered with. In the unlikely event that this has happened to you, please report it in a new issue.

**Comment by Eloston** [comment]
Not sure. They are not affiliated with us. But, they have been making builds for a while.
