### ISSUE TITLE
Crashing with error "seccomp-bpf failure"

### ISSUE THREAD

**Issue by IamPARANOID** [Eloston/ungoogled-chromium#939]
**Describe the bug**
At random times after startup the browser will crash.
Sometimes extensions will crash as well.

**To Reproduce**
1. Open the browser (``chromium``)
2. Extensions may crash
3. Some or many sites may crash

**Expected behavior**
It not to crash.

**Environment:**
 - OS/Platform and version:
Artix Linux, kernel 5.5.3-zen1-1-zen
 - ungoogled-chromium version:
79.0.3945.130

**Log from terminal**
```
[17218:17255:0214/164054.043129:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[17218:17255:0214/164054.090748:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[17218:17255:0214/164054.090799:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[17257:17257:0214/164054.200780:ERROR:vaapi_wrapper.cc(420)] vaInitialize failed: unknown libva error
[17257:17257:0214/164054.395292:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
```
**Additional Notes**
Running local DNS server unbound for DNS-over-TLS.
Seemed like while running OpenVPN (RiseUp VPN) it did not crash, which does edit resolv.conf, but this could have been coincidental however.
I have several extensions installed:
Chromium Web Store, cVim, Dark Reader, Decentaleyes, HTTPS Everywhere, Play with MPV, Privacy Redirect, Redirector, uBlock Origin, uMatrix.
I have tried running the browser both as default ``chromium`` and with ``chromium --enable-features=WebUIDarkMode --force-dark-mode --process-per-site --disable-reading-from-canvas``.  On the latter it seems to crash not as often/fast, but again this could just be coincidental.

Any ideas?  This is a really annoying problem that renders the browser unusable.

**Comment by PF4Public** [comment]
Did it crash before? 78, for example.

**Comment by azastrael** [comment]
I am using the same ungoogled-chromium version and it started doing the same thing as you describe after upgrading my system. After looking around for a long while, I found this issue on Red Hat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1773289. This gave me the idea of checking whether glibc had been updated and yep, it went from 2.30-3 to 2.31-1, so I downgraded it back and chromium doesn't seem to crash my tabs anymore :).

**Comment by Eloston** [comment]
There's not much we can do about `glibc`, other than address it in platform repos. Closing as invalid here.

**Comment by ChALkeR** [comment]
This is fixed in Chromium 80, it's a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1025739, not a glibc bug.

 https://github.com/chromium/chromium/commit/54407b422a9cbf775a68c1d57603c0ecac8ce0d7 is the fix that can be backported.
