### ISSUE TITLE
Exporting/Importing Custom Search Engines Stored in the Profile "Web Data" SQL Store

### ISSUE THREAD

**Issue by CrafterLaughter** [Eloston/ungoogled-chromium#943]
Read through SUPPORT.md

Ungoogled Chromium Version 80.0.3987.116 (Official Build) (64-bit)

I have a 300+ custom search engines with special keyword assignments for productivity.  I'm trying to export the custom search engines from Chrome and Import them into Ungoogled Chromium.

I've tried two scripts without success.
https://superuser.com/a/1458616

https://ludovic.chabant.com/devblog/2011/01/18/poor-mans-search-engines-sync-for-google-chrome-version-2

For the second method I adjusted the restore path to the SQL file accordingly to match the appropriate Ungoogled Chromium path.

Each time I ran the scripts, I subsequently closed out of Ungoogled Chromium & relaunched it, yet the custom search engines were missing.  However, the file size of the "Web Data" SQL file was increased as expected.

"%HOMEDRIVE%%HOMEPATH%\AppData\Local\Google\Chrome\User Data\Default\Web Data"

When I ran either of the above scripts on Chrome Version 80.0.3987.116 they succeeded as expected.  I thought about just replacing Ungoogled Chromium's existing Web Data SQL file with the one from Chrome, but I'm convinced there is other data stored in the Web Data SQL file that's unrelated to search engine customizations and I don't want to risk corrupting anything or inadvertently introducing unwanted Google tracking.

I appreciate your guy's expertise to get me on the right track.

**Comment by flesti** [comment]
I am not sure but maybe try running the browser with a new profile along with the following arguments that disable the machine id that encrypts those files:
```
--disable-machine-id
 --disable-encryption
```
But I am pretty sure you will have to redo your search engines by hand at least this one more time, as the "web data" file is already encrypted and cannot be used by any other profile.

**Comment by CrafterLaughter** [comment]
@flesti   I just added the arguments to a \chrlauncher\64\bin\chrome.exe shortcut and it loaded successfully.  Then I created a test profile and attempted to import the search_engines.json.  No dice.  Chromium just closes (Chrome works and remains open).

Since you mentioned something about it not being able to be used with another profile I went ahead and tested it on Chrome on a different PC with an entirely new profile.  It imports fine there as well.  Is Ungoogled Chromium such that it encrypts the file in question, yet regular Chrome does not?

I'm using chrlauncher because it allows me to automatically keep Ungoogled Chromium up to date.  chrlauncher has Ungoogled Chromium work as a portable version, so I went ahead an tested the regular ungoogled-chromium_79.0.3945.130-2.1_installer-x64.exe but that also behaves the same with Ungoogled Chromium closing the instant I select "open" on importing the search_engines.json

**Comment by flesti** [comment]
I am not familiar with chrlauncher
All chrome versions encrypt profile data by default. Only ungoogled give us the option not to.
The data needs to be already from an un-crypted profile to be imported into another profile.

There maybe ways to batch export your search engines in to a json or something. I don't know.

**Comment by CrafterLaughter** [comment]
Woolyss does a great job explaining the loss of "secure preferences" well here:
https://github.com/henrypp/chrlauncher/issues/116#issuecomment-444426692

@flesti   I appreciate your efforts to help.  In the future I encourage you to warn folks ahead of time as to the consequences of those arguments wiping extensions as a function of secure preferences.  That can set people back a lot of time if they have many highly customized extensions.

Bummer it is 2020 and Chromium devs have still kept the profiles dependent on sync (dependent on Google) in order to be transferable to another computer. (Encryption is great, but at least make it transferable)

It is especially annoying that extensions have been deemed "encrypt by default," but not user's private bookmarks.

I was really hoping to switch from Firefox to Ungoogled Chromium for the security benefit of site isolation, but profiles not being transferable between computers is a deal breaker. I guess I'll just have to stick it out with Firefox until their project Fission site isolation goes stable.

As for exporting/importing custom search engines in Chromium...  I have every confidence that will get sorted out since it's a non-issue for Chrome.  Like bookmarks, the Web Data file is definitely not encrypted, because I can even read it's contents with Notepad++

**Comment by TheJags** [comment]
@CrafterLaughter if you do not want to replace the entire "Web Data" file from `Chrome` to `Ungoogled Chromium`, you can just export `Table: Keywords` using `DB Browser for SQLite`.

Here's a detailed answer on Stackoverflow:
`https://stackoverflow.com/a/57355395/11855487`

Using the same answer, I have exported custom search engines from `Ungoogled Chromium` in Ubuntu Focal to `Microsoft Edge` in Windows 10.

Though that answer is little confusing in few places, so if you need help, I can post the detailed steps that I have saved for myself.

**Comment by Eloston** [comment]
Let us know if @TheJags's answer does not help.
