### ISSUE TITLE
Web Data not retaining user-specified search engines/Selection Context Search Extension results not opening

### ISSUE THREAD

**Issue by jlj2** [Eloston/ungoogled-chromium#949]
Using Ungoogled-chromium Portable Linux 80.0.3987.106-1.1 binary today, a pop-up appeared: “Your profile could not be opened correctly.  Some features may be unavailable."  Indeed, only the default search engines were available.

A [webpage from 2015](http://simplifyitco.com/google-chrome-profile-could-not-be-opened-correctly-error/) suggested that `~/.config/google-chrome/Default/Web Data` may be corrupt in Chrome for a similar notification;  perhaps the corresponding location for UC v80 would be  `~/.config/chromium/Default/Web Data`.

According to a recent [post](https://github.com/Eloston/ungoogled-chromium/issues/943), the Web Data file seems to store search engines.  Is it not encrypted by default in Ungoogled Chromium, along with some other config files, contrarily to some in Chromium?

Apparently, it can be opened with **Notepad++** (perhaps also **notepadqq** in Linux, a _'Notepad++-like editor for Linux'_).  However, a quick `cat` displays some unexpected '_credit_cards_' term in the second paragraph.  Perhaps it is safer to do the following check while offline?  The bash prompt has been changed below for safety's sake to '`myprompt ~$`';  it appears twice below:

```
myprompt ~ $ cat .config/chromium/Default/Web\ Data
SQLite format @  !.;ñöûö                                                                                                                   YSearxsearx.mehttps://searx.me/favicon.icohttps://searx.me/?q={searchTerms}UTF-8ch{google:pathWildcard}?ei={inputEncoding}&fr=crmas&p={searchU^øckDuckGoduckduckgo.comhttps://duckduckgo.com/favicon.icohttps://duckduckgo.co485bf7d3-0215-45af-87dc-538868000012[]https://searx.me/archTer^¾gÏ­,òÐ¢,¾óBBkc5bf7d3-0215-45af-87dc-538868000092[]https://duckduckgo.com/chrome_newtabEO]about:blank}!)Q[[]https://www.bing.com/images/detai%%tablecredit_cardscreditø°kCHROMI#enterInsightsimageBin={google:imageThumbnailBase64}https://www.bing.com/chrome/newtab~#5	
%%tablecredit_cardscredit_cards
                               CREATE TABLE credit_cards ( guid VARCHAR PRIMARY KEY, name_on_card VARCHAR, expiration_month INTEGER, expiration_year INTEGER, card_number_encrypted BLOB, date_modified INTEGER NOT NULL DEFAULT 0, origin VARCHAR DEFAULT '', use_count INTEGER NOT NULL DEFAULT 0, use_date INTEGER NOT NULL DEFAULT 0, billing_address_id VARCHAR)t	?indexautofill_name_value_lowerautofill
CREATE INDEX autofill_name_value_lower ON autofill (name, value_lower)'gindexautofill_nameautofill	CREATE INDEX autofill_name ON autofill (name)[	tableautofillautofillCREATE TABLE autofill (name VARCHAR, value VARCHAR, value_lower VARCHAR, date_created INTEGER DEFAULT 0, date_last_used INTEGER DEFAULT 0, count INTEGER DEFAULT 1, PRIMARY KEY (name, value))/Cindexsqlite_autoindex_autofill_1autofil)%tablekeywordskeywordsCREATE TABLE keywords (id INTEGER PRIMARY KEY,short_name VARCHAR NOT NULL,keyword VARCHAR NOT NULL,favicon_url VARCHAR NOT NULL,url VARCHAR NOT NULL,safe_for_autoreplace INTEGER,originating_url VARCHAR,date_created INTEGER DEFAULT 0,usage_count INTEGER DEFAULT 0,input_encodings VARCHAR,suggest_url VARCHAR,prepopulate_id INTEGER DEFAULT 0,created_by_policy INTEGER DEFAULT 0,last_modified INTEGER DEFAULT 0,sync_guid VARCHAR,alternate_urls VARCHAR,image_url VARCHAR,search_url_post_params VARCHAR,suggest_url_post_params VARCHAR,image_url_post_params VARCHAR,new_tab_url VARCHAR,last_visited INTEGER DEFAULT 0, created_from_play_api INTEGER DEFAULT 0)}''9tabletoken_servicetoken_serviceCREATE TABLE token_service (service VARCHAR PRIMARY KEY NOT NULL,encrypted_token BLOB)9M'indexsqlite_autoindex_token_service_1token_servicef/tablemetaÌetaCREAün+mílüõû'óÌÕn;;utableautofill_profiles_trashautofill_profiles_trashCREATE TABLE autofill_profiles_trash ( guid VARCHAR);;tableautofill_profile_phonesautofill_profile_phonesCREATE TABLE autofill_profile_phones ( guid VARCHAR, number VARCHAR)~;;tableautofill_profile_emailsautofill_profile_emailsCREATE TABLE autofill_profile_emails ( guid VARCHAR, email VARCHAR);99tableautofill_profile_namesautofill_profile_namesU/indexsqlite_autoindex_autofill_profiles_1autofill_profiles"e VARCHAR, middle_name VARCHAR, last_name VARCHAR, full_name VARCHAR)A
CREATE TABLE autofill_profiles ( guid VARCHAR PRIMARY KEY, company_name VARCHAR, street_address VARCHAR, dependent_locality VARCHAR, city VARáHAR, state VARCHAR, zipcode VARCHAR, sorting_code VARCHAR, country_code VARCHAR, date_modified INTEGER NOT NULL DEFAULT 0, origin VARCHAR D^\&ÖéÆ(µ\*uáW--ctablepayments_upi_vpapayments_upi_vpaCREATE TABLE payments_upi_vpa (vpa VARCHAR)q99tablepayments_customer_datapayments_customer_dataCREATE TABLE payments_customer_data (customer_id VARCHAR)??Etableautofill_model_type_stateautofill_model_type_stateCREATE TABLE autofill_model_type_state (model_type INTEGER NOT NULL PRIMARY KEY, value BLOB)K991tableautofill_sync_metadataautofill_sync_metadataREATE TABLE autofill_sync_metadata (model_type INTEGER NOT NULL, storage_key VARCHAR NOT NULL, value BLOB, PRIMARY KEY (model_type, storage_key))K_9indexsqlite_autoindex_autofill_sync_metadata_1autofill_sync_metadataj;;ktableserver_address_metadataserver_address_metadataCREATE TABLE server_address_metadata (id VARCHAR NOT NULL,use_count INTEGER NOT NULL DEFAULT 0, use_date INTEGER NOT NULL DEFAULT 0, has_converted BOOL NOT NULL DEFAULT FALSE)M--Mtableserver_addressesserver_addressesCREATE TABLE server_addresses (id VARCHAR,company_name VARCHAR,street_address VARCHAR,addrec^[[?1;2cmyprompt ~ $ 1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2code VARCHAR,sorting_code VARCHAR,country_code VARCHAR,language_code VARCHAR, recipient_name VARCHAR, phone_number VARCHAR)R55Gtableserver_card_metadataserver_card_metadataCREATE TABLE server_card_metadata (id VARCHAR NOT NULL,use_count INTEGER NOT NULL DEFAULT 0, use_date INTEGER NOT NULL DEFAULT 0, billing_address_id VARCHAR)z2;;{tablepayment_method_manifestpayment_method_manifest!CREATE TABLE payment_method_manifest ( expire_date INTEGER NOT NULL DEFAULT 0, method_name VARCHAR, web_app_id VARCHAR)S==9tableweb_app_manifest_sectionweb_app_manifest_section CREATE TABLE web_app_manifest_section ( expire_date INTEGER NOT NULL DEFAULT 0, id VARCHAR, min_version INTEGER NOT NULL DEFAULT 0, fingerprints BLOB)
```

**NOTES:**
1.  When trying an engine search from the shortcut menu offered by the [Selection Context Search](https://chrome.google.com/webstore/detail/selection-context-search/kplgehmegmjifbhioeldcnphfkcfckjj) v5.18 extension, the search results tab doesn't appear, even when changing its settings option to open the result in a separate window. The extension worked ok with UC v78.
2.  The UC Portable Linux binary was extracted to `/opt` using sudo and demonstrated `username:username` ownership for some extracted files.  For this install, '`sudo chown root:root -R`' was used for that folder:  perhaps this would be an additional recommended security step?

**Comment by wchen342** [comment]
[https://chromium.googlesource.com/chromium/chromium/+/20f8aa123f98b2bcb0d346af0d78ad7a8ddea5d0/chrome/browser/webdata/web_database.cc](https://chromium.googlesource.com/chromium/chromium/+/20f8aa123f98b2bcb0d346af0d78ad7a8ddea5d0/chrome/browser/webdata/web_database.cc)

It is probably there for the autofill function? Though I don't know whether they put queries directly into the file. There should be an sql file somewhere in the folder that saves the actual data.

**Comment by jlj2** [comment]
Thanks @wchen342!  

Having searched further after the initial concern, the appearance of 'credit cards', etc. in `.config/chromium/Default/Web Data` doesn't seem to be specific to Ungoogled Chromium Portable Linux binary v80 but rather standard to Chromium/Chrome and appears in Vivaldi 2.11 (based on Chromium too):  you can choose to autofill your credit card information, and presumably that file helps to store it.  For example, [this website](https://www.askcybersecurity.com/view-chrome-saved-credit-cards/) suggests that this autofill setting can be modified at:

`chrome://settings/autofill 
`
...which leads to the search engine list and is therefore related to the `Web Data` file, presumably.

The title has been changed to _'Web Data not retaining user-specified search engines/Selection Context Search Extension results not opening'_, as there is no unusual _'Security alert'_ required about that file, presumably.

**Comment by Eloston** [comment]
Would you happen to have `chrome://flags/#disable-search-engine-collection` enabled? I'm not sure if that affects the issue here though.

**Comment by jlj2** [comment]
Thanks, @Eloston.

`chrome://flags/#disable-search-engine-collection` was not altered and is therefore disabled.  The only flag that I think has remained changed since either before or after this situation occurred is the flag to enable `#enable-reader-mode` (which distills webpages from clutter on request).  However, I would have also changed the MIME flag (`#extension-mime-request-handling`) occasionally when trying (unsuccessfully) to install extensions without needing to unpack them (using an extension to install them that was first unpacked), but afterwards the flag was reset to default.  

On closer inspection, not all of my added search engines are missing after all:  I have since noticed that the search engine which I added and then marked as default (https://www.yippy.com/search?v%3Aproject=clusty-new&query=%s) is the only one that is still listed among the added engines.  That engine works ok and remains the default in the location field.  It is marked as the default in `chrome://settings/searchEngines` and is listed in the 'Default Search Engines' section along with the out-of-the-box search engines.  It also appears towards the top of the Web Data file.  

However, in **Vivaldi 2.11.1811.38** (user agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/80.0.3987.107** Safari/537.36') on this Calculate Linux 20 (Gentoo) installation, my user-defined search engines and the Selection Context Search extension's context menus offering search engines all seem to open result tabs ok.  Maybe this bug has something to do with the new `ScrollToTextFragment` feature introduced in Chromium 80, 
 mentioned in a [link](https://www.theregister.co.uk/2020/02/20/chrome_deploys_deeplinking/) in an aforementioned post, or some related bug upstream with chromium 80, as the link seems to relate to search engines being enable to provide more information?

**Comment by jlj2** [comment]
This issue may now be closed, as the two artifacts reported do not recur at least in the current UC Portable Linux version (v85), which supersedes v80 on which this report applies.  The artifacts may not have recurred in v84 either, at least.  Specifically:-

- Web Data not retaining user-specified search engines
- Selection Context Search Extension results not opening in new tab

**Comment by Eloston** [comment]
Closing since #1444 is merged.
