### ISSUE TITLE
Difference Chrominium vs ungoogled-chrominium

### ISSUE THREAD

**Issue by the4anoni** [Eloston/ungoogled-chromium#95]
Afaik Chrominium don't have goooooogle spying ,but now i m confused....

**Comment by 9Morello** [comment]
I'm sorry, do you mean Chromium (as in, the vanilla Chromium browser by Google)?

Chromium, despite not having the Chrome brand, phones Google for a variety of functions (most of them having some trade-off with privacy). ungoogled-chromium is Chromium with many patches to modify/change these functions so the browser doesn't connect to Google at all.

**Comment by mimf** [comment]
What the hell is Chrominium? Googling that doesn't find anything. If your question is in regards with Chromium, then, you should've read the README: https://github.com/Eloston/ungoogled-chromium/blob/master/README.md

It has all your answers there. Noone is going to read it for you.

**Comment by the4anoni** [comment]
Ok ,got it thanks. Just thinked that chrominium is without google ,but now i'm on good way ;)
