### ISSUE TITLE
Hardware video acceleration in portable?

### ISSUE THREAD

**Issue by RainmakerRaw** [Eloston/ungoogled-chromium#952]
Is it possible to enable hardware video acceleration in the portable build? 

I normally install the binary release for whichever (Linux) distro is applicable (or build it on Arch), but I'm currently testing Ubuntu 20.04 LTS daily. As there's no ungoogled-chromium available for this yet, I snagged the latest testing portable (80.0.3987.106), copied over my profile from backup, and added WidevineCDM. So far, so great - even Netflix works. Unfortunately, chrome://flags shows that hardware-accelerated video decode and encode report they're not available for the platform. 

Is there a way to get this enabled, or is it just a hard block due to the build being 'portable'? Since it happily pulls Widevine from /usr/lib on launch I figured - apparently incorrectly - that it would be able to access the rest of the system and accelerate video playback too. Any help greatly appreciated. Thanks in advance.

Edit: I see from [this old issue](https://github.com/Eloston/ungoogled-chromium/issues/430) that you enabled VAAPI in portable. Is it just broken? I have the correct drivers installed on the OS and vainfo reports all is working.

**Comment by Eloston** [comment]
Portable doesn't have VA-API support anymore because it creates a dependency on VA-API shared libraries. You could try applying the patch and building with VA-API support, but YMMV.

You might have better luck building the Ubuntu eoan source on 20.04, but some patches or flags may need to be tweaked. Otherwise, I'm sure someone will come around to add support for 20.04.

**Comment by mbakke** [comment]
@RainmakerRaw You can install [GNU Guix](https://guix.gnu.org), a cross-platform package manager that only depends on the Linux kernel, and install ungoogled-chromium from there.  It has VAAPI acceleration enabled.

See [the manual](https://guix.gnu.org/manual/en/guix.html#Binary-Installation) for how to get started, in particular the shell installer script.  Once installed, you should be able to `guix pull` and `guix install ungoogled-chromium`.

Guix is designed not to conflict with the host distribution and is a great way to get the latest version of packages on top of a stable distribution such as Ubuntu.
