### ISSUE TITLE
Installed the stable and then installed the development version on Windows.

### ISSUE THREAD

**Issue by king-final-ecks** [Eloston/ungoogled-chromium#953]
Hi,
I have installed Ungoogled Chromium stable but I wanted the latest available so I installed the development version. Somehow I can access both versions and the user data is shared between them. Is this supposed to happen?

1. Get the binary for the latest stable version of ungoogled-chromium
2. Set the binary up.
3. Than get the installer for the latest available binary for the development version and install.
4. Repeat step 2.
5. Start up the stable version and install a few extensions. Close it.
6. Start up the development version, the extensions are still there as if it updated itself. Close it.
7. Start up the stable version and wait, there is the extensions we have installed earlier.

I was expecting for an error to pop up and also some data corruption.

 - Windows 10 Education1909 (19H2)
 - ungoogled-chromium version: 79.0.3945.130 (Dev) + 67.0.3396.87 (Stable)

**Comment by Eloston** [comment]
Yeah, this is expected. They aren't separate tracks of development, just different versions of Chromium basically. The distinction is actually pretty unnecessary right now so I've created https://github.com/ungoogled-software/ungoogled-chromium-binaries/issues/136 to remove the distinction.
