### ISSUE TITLE
Ota support

### ISSUE THREAD

**Issue by the4anoni** [Eloston/ungoogled-chromium#96]
Because why not :)
I think ota updates

**Comment by Eloston** [comment]
OTA support? What do you mean by OTA in this case?

**Comment by the4anoni** [comment]
Updates via browser ,not github

**Comment by Eloston** [comment]
Oh okay. I'm not very familiar with the browser's built-in update feature since I've never seen it on Chromium and I've never tried it on Chrome.

However, I don't really want to implement this since there are so many ways to setup ungoogled-chromium, and I don't want to write very complicated code to accomplish something that has little value. If you have a very good reason for implementing this, let me know.

**Comment by reclaimer** [comment]
FreeSMUG has [Chromium builds](http://www.freesmug.org/chromium). They don't auto-update, but there's [an extension](https://chrome.google.com/webstore/detail/chromium-updater/ccgjmadhdidfloacagcnnodbkedkjedg) that checks for newer builds. It then prompts you to download the updated version. It's not a perfect solution, but it's a good one.

**Comment by Eloston** [comment]
@reclaimer: It's not a bad idea, but I don't want that to be a part of this project. This project tries not to deviate too much from the user experience provided by vanilla Chromium. It would be fine if that extension if such extension was made into a separate project and then referenced from ungoogled-chromium's documentation (e.g. the README).

**Comment by reclaimer** [comment]
The extension is basically [checking Sourceforge for a newer build](https://github.com/p1g30n/chromium-updater/blob/master/js/background.js#L70). A Github-based approach might actually be more elegant.

**Comment by the4anoni** [comment]
If you have a very good reason for implementing this, let me know.

Because i don't want every day check for updates...

**Comment by Eloston** [comment]
@the4anoni You don't need the browser to self-update to know if there's an update. @reclaimer's solution will notify users when there's an update.
