### ISSUE TITLE
Undefined symbols of ungoogled switches

### ISSUE THREAD

**Issue by HarukaMa** [Eloston/ungoogled-chromium#963]
**Describe the bug**
Switches in the `switches` namespace are not exported.
```
Undefined symbols for architecture x86_64:
  "switches::kFingerprintingClientRectsNoise", referenced from:
      (anonymous namespace)::SetRuntimeFeaturesFromCommandLine(base::CommandLine const&)::switchToFeatureMapping in runtime_features.o
      content::RenderProcessHostImpl::PropagateBrowserCommandLineToRenderer(base::CommandLine const&, base::CommandLine*)::kSwitchNames in render_process_host_impl.o
  "switches::kFingerprintingCanvasImageDataNoise", referenced from:
      (anonymous namespace)::SetRuntimeFeaturesFromCommandLine(base::CommandLine const&)::switchToFeatureMapping in runtime_features.o
      content::RenderProcessHostImpl::PropagateBrowserCommandLineToRenderer(base::CommandLine const&, base::CommandLine*)::kSwitchNames in render_process_host_impl.o
  "switches::kFingerprintingCanvasMeasureTextNoise", referenced from:
      (anonymous namespace)::SetRuntimeFeaturesFromCommandLine(base::CommandLine const&)::switchToFeatureMapping in runtime_features.o
      content::RenderProcessHostImpl::PropagateBrowserCommandLineToRenderer(base::CommandLine const&, base::CommandLine*)::kSwitchNames in render_process_host_impl.o
ld: symbol(s) not found for architecture x86_64
```

**To Reproduce**
Build Chromium using own build process.

**Expected behavior**
Should not have such errors.

**Environment (please complete the following information):**
 - OS/Platform and version: macOS 10.15.3
 - ungoogled-chromium version: 80.0.3987.132
* Using self-compiled LLVM toolchain, not Xcode one.

**Additional context**
It seems that normal build process has build config `//build/config/gcc:symbol_visibility_hidden` which adds `-fvisibility=hidden` flags, causing all symbols to be unexported unless explicitly requested. I had to remove that build config in `BUILD.gn` to make it compile:

```patch
component("switches") {
  sources = [
    "ungoogled_switches.h",
    "ungoogled_switches.cc",
  ]
+  configs -= [ "//build/config/gcc:symbol_visibility_hidden" ]
}
```

**Comment by HarukaMa** [comment]
Related docs in `build/config/gcc/BUILD.gn`:

```
# This config causes functions not to be automatically exported from shared
# libraries. By default, all symbols are exported but this means there are
# lots of exports that slow everything down. In general we explicitly mark
# which functions we want to export from components.
#
# Some third_party code assumes all functions are exported so this is separated
# into its own config so such libraries can remove this config to make symbols
# public again.
#
# See http://gcc.gnu.org/wiki/Visibility
config("symbol_visibility_hidden") {
  cflags = [ "-fvisibility=hidden" ]

  # Visibility attribute is not supported on AIX.
  if (current_os != "aix") {
    cflags_cc = [ "-fvisibility-inlines-hidden" ]
    cflags_objcc = cflags_cc
  }
}
```

**Comment by Eloston** [comment]
Hmm I wonder why this issue doesn't occur in any of our Linux platforms?

**Comment by HarukaMa** [comment]
I'm also not sure and it seems other macOS builds are not encountering this issue, however from the doc it does seem that removing that flag should be needed as I'm not seeing ungoogled switches are explicitly exported...

**Comment by HarukaMa** [comment]
btw, I was checking `libswitches.dylib` when it happens and those switches were indeed not exported (`s` instead of `S` in `nm` output).

**Comment by Eloston** [comment]
In that case it's probably that different build configurations lead to different shared libraries. We should follow the Chromium convention here and fix the exports as you suggested.
