### ISSUE TITLE
Cant install Chromium.Web.Store.crx i got stucked

### ISSUE THREAD

**Issue by Ud4ba** [Eloston/ungoogled-chromium#964]
I cant install the Chromium.Web.Store.crx i got stucked .... and with no ublock origin this is useless ..

**Comment by PF4Public** [comment]
Please, kindly provide more information on the issue, so that we could help.

**Comment by Ud4ba** [comment]
Im really sorry for being rude .. I had the worst day in my life yesterday . Im really sorry . 

Now to the problem . When im trying to drop the chromiun.web.store.crx , on the extensions with Developer Mode on, im dropping it there and nothing happens .

**Comment by Ud4ba** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/923

seems like the same problem . any idea how i could add the store?

**Comment by Eloston** [comment]
You'll probably want to unpack the extension first or get the source code from GitHub, then load the unpacked extension in developer mode.

**Comment by perfect7gentleman** [comment]
open *.crx with UnGoogled-Chromiu,

**Comment by Ud4ba** [comment]
i tried both of them . nothing works :/
when i open crx with UnGoogle-Chromiun it stucks "Adding to chromiun" and stucks there for ever . the same happens every time i try to add or open crx file .

**Comment by perfect7gentleman** [comment]
Have you done that?

> If you wish to install extensions directly instead of just downloading the crx, you must change the flag chrome://flags/#extension-mime-request-handling to Always prompt for install.

**Comment by Ud4ba** [comment]
> 
> 
> Have you done that?
> 
> > If you wish to install extensions directly instead of just downloading the crx, you must change the flag chrome://flags/#extension-mime-request-handling to Always prompt for install.

yes of course .

**Comment by perfect7gentleman** [comment]
Clean profile?

**Comment by Ud4ba** [comment]
its clear yes . i havent done anything . im just trying to add ublock origin and some more addons so i can start browsing .

**Comment by Eloston** [comment]
Like I said, you need to unpack them by renaming them to zip first, then load them in developer mode.

Also if you're using Windows, I haven't been able to get CRX files to install at all, even with Chromium Web Store installed. We really need to get into better testing practices, and/or spend some time to fix these bugs.

**Comment by Ud4ba** [comment]
so this is unfix able ?

**Comment by Eloston** [comment]
No, it should be fixed with #923, and also #845. The workaround is to unpack the extension as I've described above.

**Comment by Ud4ba** [comment]
how i suppose to unpack the add on??
