### ISSUE TITLE
Can't grant Persmissions for microphone

### ISSUE THREAD

**Issue by allilengyi** [Eloston/ungoogled-chromium#965]
**Description of the bug**
I am on debian 10, and tried to use jisti meet video conferencing.
Unfortunately, I was not able to grant permissions to the microphone.

**To Reproduce**
1. Go to 'https://meet.jit.si'
2. Start a conference
3. Error occurs: No Permissions for microphone

**Expected behavior**
Jitsi should ask for Permissions to allow microphone

**Environment (please complete the following information):**
 - Debian Buster and version: 10.2
 - ungoogled-chromium version: 80.0.3987.132-1.buster1

**Additional context**
Everything goes fine when using Google Chrome, Firefox or Brave.
Same behavior for chromium as for ungoogled chromium

**Comment by Eloston** [comment]
In `chrome://settings/content/`, is your microphone set to "Ask before accessing"? I have used Jitsi on that particular build with no issues.

**Comment by allilengyi** [comment]
yep,  microphone is set to "Ask before accessing".

**Comment by mbakke** [comment]
@allilengyi Open `~/.config/chromium/Default/Preferences` and check if you have an `"audio_capture_enabled": false` entry.  If so, removing or inverting this setting should fix the problem.

See also the related [FAQ entry](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-is-my-microphone-not-working).

**Comment by allilengyi** [comment]
Thank you, this solved the issue.

**Comment by EchedeyLR** [comment]
This seems to be a default issue. I was having it too in a default installation of the last version (today) and the last one before using Debian prebuilt packages

Could a reference be added in the Readme or the Wiki for visibility?

**Comment by EchedeyLR** [comment]
Okay, nothing. It is already referenced in the wiki here: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-is-my-microphone-not-working

Thank you all for that.
