### ISSUE TITLE
Build fails with Python 3.4?

### ISSUE THREAD

**Issue by tonowoe** [Eloston/ungoogled-chromium#97]
When I'm trying to run the `build.py` [it will give me this error](http://pastebin.com/raw/nUCUqN1J). _AttributeError: 'module' object has no attribute 'run'_

I did some Googling [and I found this](https://github.com/winksaville/vendor-install-tools/issues/2). What should I do?

I really wouldn't want to manually update my python because in Debian Jessie the [latest python version](http://pastebin.com/raw/eAexB07Q) is 3.4.2.

Thank you.

**Comment by Eloston** [comment]
Oh wow the whole function isn't supported? That's annoying. I guess I can change the code to use a different function.
