### ISSUE TITLE
build error    ERROR: A failure occurred in build().

### ISSUE THREAD

**Issue by yasoomn** [Eloston/ungoogled-chromium#972]
makepkg -si exiting with error whent trying to build pkg

runnning on Manjaro 
output:
`==> Starting build()...                                                 [0/9528]
make: Entering directory '/home/yasoom/Downloads/ungoogled-chromium/src/chromium-launcher-6'
cc -o chromium -D_FORTIFY_SOURCE=2 -DLAUNCHER_VERSION=\"v6\" -DCHROMIUM_NAME=\"chromium\" -DCHROMIUM_BINARY=\"/usr/lib/chromium/chromium\" -DCHROMIUM_VENDOR="\"Manjaro Linux\"" -DPEPPER_FLASH_DIR=\"/usr/lib/PepperFlash\" -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/json-glib-1.0 -I/usr/lib/libffi-3.2.1/include -pthread -I/usr/include/libmount -I/usr/include/blkid  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now launcher.c -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
{standard input}: Assembler messages:
{standard input}: Fatal error: can't write 45 bytes to section .text of /tmp/ccKr6GWQ.o: 'No space left on device'
{standard input}: Fatal error: can't close /tmp/ccKr6GWQ.o: No space left on device
make: *** [Makefile:23: chromium] Error 1
make: Leaving directory '/home/yasoom/Downloads/ungoogled-chromium/src/chromium-launcher-6'
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by perfect7gentleman** [comment]
```
No space left on device
```

**Comment by yasoomn** [comment]
I assume this refers to my drives, but none of them are out of space

**Comment by PF4Public** [comment]
> Building Chromium requires quite a lot of memory.

IIRC, by the end of compilation sources + build artifacts occupy around 7G.

PS: writing just to clarify the "a lot" statement ;)

**Comment by Eloston** [comment]
This is getting a bit stale; closing.
