### ISSUE TITLE
Installer is caught by SmartScreen

### ISSUE THREAD

**Issue by FrankSalmick** [Eloston/ungoogled-chromium#975]
**Describe the bug**
When downloading the 64-bit windows client version 80.0.3987.132-1, Windows shows a smartscreen warning. This is odd as ungoogled chromium is a (relatively) widely-used browser, and smartscreen only shows on apps that are not on ["a list of files that are well known and downloaded by many Windows users"](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview), so the warning shouldn't be showing. The specifics of how an app becomes "downloaded by many users" isn't known, but as far as I know it should be much lower than the number of people that use this program.

**To Reproduce**
1. Go to https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/
2. Choose the latest version (in this case, 80.0.3987.132-1)
3. Download and open the file
4. Get SmartScreen warning.

**Expected behavior**
1. Go to https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/
2. Choose the latest version (in this case, 80.0.3987.132-1)
3. Download and open the file
4. No SmartScreen warning

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10
 - ungoogled-chromium version: None (80.0.3987.132-1)

**Additional context**

**Comment by FrankSalmick** [comment]
I just realized I forgot to include this, but this applies to the 64 and 32 bit installers and `chrome.exe` in the zip files

**Comment by Eloston** [comment]
I don't think ungoogled-chromium *on Windows* is that popular. Even then, some users may not use the installer and choose to use the zip package instead.

I'm guessing SmartScreen does not block users from using the installer, right? If so, then I don't think we need to do anything here. I'm assuming it isn't easy to get on SmartScreen's whitelist either, and that a number of other smaller applications have this same problem.

Closing as it's not really in our control.
