### ISSUE TITLE
What is the recommended way to update this Chromium with "brew"?

### ISSUE THREAD

**Issue by ianpan870102** [Eloston/ungoogled-chromium#977]
I'm using ungoogled-chromium on a macbook and installed it with `brew cask fetch eloston-chromium && brew cask install eloston-chromium`

I'd like to know the recommended way of updating Chromium when a new release is out (either through Autoupdate or the command-line, I don't mind). So far I've been completely reinstalling it whenever newer versions are out -- but certainly there's a better way?

**Comment by kramred** [comment]
Hi, I'm someone who is providing binaries for macOS and currently by build is referenced in the [cask code](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/eloston-chromium.rb).
As far as I can tell there is currently no Autoupdate from ungoogled chromium itself; see also https://github.com/Eloston/ungoogled-chromium/issues/861 and https://github.com/Eloston/ungoogled-chromium/issues/754 
I would say completely reinstalling it via command line would be one recommended way; see also https://github.com/Eloston/ungoogled-chromium/issues/876
As [tectiv3](https://github.com/tectiv3) commented there
> you can force an upgrade with `brew cask upgrade eloston-chromium`

I don't know if there are plans to include an automatic check for newer versions (maybe as an opt-in feature), or there might be an extension that does that...

**Comment by ianpan870102** [comment]
Thanks for your reply :) 
`brew cask upgrade eloston-chromium` sounds like a good-enough answer for me!

**Comment by james2406** [comment]
For anyone trying to do this in 2022, the command is `brew upgrade --cask eloston-chromium`
