### ISSUE TITLE
Extensions removed on browser restart.

### ISSUE THREAD

**Issue by asm20** [Eloston/ungoogled-chromium#979]
Hello,
I am currently running Ungoogled Chromium 80.0.3987.132 on Windows 10 and installed it with the 64-bit binary offered on this git. After installing an extension (the only way the installation works is by unpacking the crx and loading the unpacked extension) the extension is gone if I close and re-open the browser and has to be installed again. Is there are workaround for this? As an aside, none of the extensions I have tried to install (Chromium Web Store, uBlock Origin) seem to work properly, though I suspect that this is likely related to the above issue.

**Comment by asm20** [comment]
Fixed by using 32-bit version instead

**Comment by skbzk** [comment]
This bug still exists for me on Appimage version 91.0.4472.164-1.1

**Comment by networkException** [comment]
Does the issue persist on chromium 96 or newer? 91 is close to a year old and will not receive updates to the patches.

**Comment by skbzk** [comment]
> Does the issue persist on chromium 96 or newer? 91 is close to a year old and will not receive updates to the patches.

Sorry for disturbing, issue has resolved itself, chromium 91 loads the plugins just fine now. I don't think I did anything specific to fix this.

**Comment by networkException** [comment]
Just that you are aware, chromium 91 is extremely outdated and has a large number of critical security vulnerabilities that have only been fixed in newer releases. Please, if not strictly nessesarry do **NOT** use old versions like this.
