### ISSUE TITLE
Option to hide shortcuts on new tab?

### ISSUE THREAD

**Issue by ianpan870102** [Eloston/ungoogled-chromium#980]
As titled, is there a way to hide the 'most visited website' shortcuts in the new tab page?

**Comment by qvint** [comment]
https://chrome.google.com/webstore/search/empty%20new%20tab%20page

**Comment by ianpan870102** [comment]
Ideally I'd prefer to not have 3rd party plugins. But it works -- closing issue

**Comment by snow344** [comment]
> Ideally I'd prefer to not have 3rd party plugins.

I second this.
