### ISSUE TITLE
Incognito mode is detectable and can be blocked

### ISSUE THREAD

**Issue by karz1** [Eloston/ungoogled-chromium#981]
Incognito mode is detectable and can be blocked.
News articles from 2019 say it has been "Fixed" but they never really did.
Verify here:
[https://output.jsbin.com/tazuwif](url)

Gist for the code:
[https://gist.github.com/jherax/a81c8c132d09cc354a0e2cb911841ff1](url)

**Comment by PF4Public** [comment]
@karz1 Your link is for some reason leads to a different URL.

**Comment by Eloston** [comment]
This looks like a general Chromium problem. Is there a crbug for this issue? How have other Chromium forks dealt with this?

**Comment by keddad** [comment]
It is not even Chromium problem, the same thing happens in Firefox. I don't think this issue belongs here.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
