### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#983]
Its possible to a feature where we can change the keyboard shortcuts?

**Comment by PF4Public** [comment]
Why would you need this?

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.

**Comment by gerryhernandez** [comment]
I'd like to revisit this. I'm using a Mac keyboard on Arch Linux in the KDE desktop environment and I have the rest of my system following idiomatic macOS hotkeys, such as `Command+C` to copy, or `Command+F` to find. I've changed these in KDE and the bindings seem to work everywhere other than Ungoogled Chromium. The `Edit` menu still shows `Ctrl+C` and `Ctrl+F` for the key bindings.

I can live without it respecting the system defaults as long as I can manually change Chromium's keyboard shortcuts. Is it possible, at all? I'm aware of the "Shortcuts" extension, but it doesn't allow disabling or overrides of default shortcuts, such as cut/copy/paste.

**Comment by networkException** [comment]
I use the de-macintosh layout with a Windows keyboard (meaning the Windows key corresponds to Command) also on Arch KDE and it works fine in ungoogled-chromium
