### ISSUE TITLE
ungoogled chromium closes itself seconds after starting

### ISSUE THREAD

**Issue by dln949** [Eloston/ungoogled-chromium#986]
My machine is running Ubuntu 18.04.4.  

I installed version 80.0.3987.149-1.bionic1 of ungoogled-chromium from the Buren PPA.  

When I start ungoogled-chromium, the browser opens up, but within a few seconds it closes itself.  

When I start ungoogled-chromium from the terminal, here is the output I see (it means nothing to me, I am not a computer type person):  

> main1@system1:~$ dpkg -s ungoogled-chromium | grep -i version
Version: 80.0.3987.149-1.bionic1
main1@system1:~$ 
main1@system1:~$ 
main1@system1:~$ chromium
[31683:31683:0401/005704.444924:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
[31724:31724:0401/005704.556915:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[31726:31744:0401/005704.661076:ERROR:url_request.cc(586)] Block URL in URLRequest: https://update.9oo91eapis.qjz9zk/service/update2/json
[31726:31744:0401/005704.661226:ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://update.9oo91eapis.qjz9zk/service/update2/json
Received signal 11 SEGV_MAPERR 000000000000
#0 0x558b5fe6a6d9 <unknown>
  r8: 0000354a348e7050  r9: 00007f7fed1bf39c r10: 0000000000000001 r11: 0000000000000001
 r12: 0000000000000000 r13: 0000354a33f6bdb0 r14: 00007f7fed1bf450 r15: 0000354a33f58000
  di: 0000000000000000  si: 4533df6984f81d97  bp: 00007f7fed1bf410  bx: 0000354a347222d0
  dx: 0d6e17e2c4ca804c  ax: 002e99c60a7fb5d8  cx: 00007f7fed1bf500  sp: 00007f7fed1bf3d0
  ip: 0000558b61d14ee0 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
main1@system1:~$

**Comment by braewoods** [comment]
It's working fine with my amd64 build. Are you using a different architecture build? Only other thing I can think of is maybe you have an incompatible browser profile from regular chromium.

**Comment by dln949** [comment]
@braewoods , thanks for your response.  

My system's architecture is shown as x86_64.  

I *did* have the debian package of regular chromium installed, but I had removed it completely (I thought).  

Also, I currently have the snap package of debian chromium installed.  

And - due to work requirements - sadly, I also need to have google chrome installed.  

If the problem might be, as you thought, an "incompatible browser profile from regular chromium", how do I find that and delete it?  And, will deleting it affect the snap installation of chromium and the installation of google chrome?

**Comment by camgirls** [comment]
Recently had this issue while I was transferring my User Data from Iridium (another Chromium fork) to this. I'd suggest clearing your Default folder (in %localappdata%/Chromium/User Data/Default) or saving only the essential folders you need (cookies, login info, settings).

**Comment by dln949** [comment]
@camgirls , thank you.  

On my system I found these directories:  ~/.config/chromium , and ~/.cache/chromium .  I deleted both of them.  Now it seems (so far) that everything still works fine, and my original problem I wrote about in the first post for this issue has been solved.  

Thanks to everyone.
