### ISSUE TITLE
Version of chromium

### ISSUE THREAD

**Issue by adamabdulahi** [Eloston/ungoogled-chromium#989]
Hi, 

Really do like the project and what has been done to it. I'm just wondering if there is a special reason as to why the version of chromium used for this project is so old compared to the latest version of chromium.

**Comment by Eloston** [comment]
Right now we track stable releases of Chromium. We could additionally follow beta or canary versions of Chromium, but I don't know if anyone's interested in that.

Would like to hear some opinions.

**Comment by braewoods** [comment]
We should not be tracking non-stable releases in the main branch. If this is done it should be relegated to other branches. But I don't see the value myself. We're not behind the official stable which is what people should be using anyway outside of developers that have some reason to need early access to new upstream features.

**Comment by adamabdulahi** [comment]
Mistake from my part, didn't realize it was the latest stable version. 
Agree with @braewoods's comment

**Comment by lipici** [comment]
should be closed to avoid confusion

**Comment by Eloston** [comment]
Based on @braewoods's comment and the reactions to posts I'm closing.
