### ISSUE TITLE
Unable to see video call recipients on Cisco Webex

### ISSUE THREAD

**Issue by AryToNeX** [Eloston/ungoogled-chromium#990]
**Describe the bug**
During a videoconference, I am unable to see other people's webcams.

**To Reproduce**
- Have a conference on Webex
- Make the recipients show their webcam

**Expected behavior**
- Video streams should show

**Screenshots**
I can't show those because of __privacy__

**Environment (please complete the following information):**
 - OS/Platform and version: KDE neon 5.18.4
 - ungoogled-chromium version: 80.0.3987.149-1.bionic1 amd64

**Additional context**
I have an AMD GPU and Mesa 20.1-dev drivers from oibaf's PPA

**Comment by Ph0rk0z** [comment]
WebRTC is disabled?

**Comment by AryToNeX** [comment]
how do I check it ?

**Comment by Eloston** [comment]
I don't think WebRTC is the issue because I don't think you can disable it.

What does DevTools show while you are making the video call?

**Comment by AryToNeX** [comment]
DevTools doesn't show anything but a series of errors due to denied accesses to fonts (content security policy errors)

and a lot of private stuff

**Comment by AryToNeX** [comment]
I tried to make a call with the Vivaldi browser as a comparison and I looked at the console output: they're the same, same CSP errors and same output. It's just that ungoogled chromium somehow doesn't show webcams... idk

**Comment by Eloston** [comment]
I'm guesing chrome://settings/content/camera is configured correctly? Could you try a webcam tester or a service like Jitsi Meet?

**Comment by AryToNeX** [comment]
Well, the problem is not with my webcam but it's with other's video feed; that one doesn't load.

Sure I can try Jitsi asap

**Comment by Eloston** [comment]
Does this work in Chromium or a derivative?

**Comment by AryToNeX** [comment]
This works in stock Chromium!

**Comment by AryToNeX** [comment]
This now works on Ungoogled Chromium 81 from the newer openSUSE repos (for Ubuntu)
