### ISSUE TITLE
What's with hammering port 1900.

### ISSUE THREAD

**Issue by Ph0rk0z** [Eloston/ungoogled-chromium#991]
What is with ugC hammering port 1900. I have set the media router to disabled and turned off "hide local ip with mDNS". I still get literally hundreds of broadcasts a day while chrome is open.

**Comment by Eloston** [comment]
Port 1900 is SSDP, which underlies UPnP. I think they're separate from mDNS and Media Router, but we're going to need more info to know what's happening.

**Comment by Ph0rk0z** [comment]
What do you want to know? I have the latest dev build on ubuntu 18.0.4. I have set the flags to not load media router.... interestingly the "cast" menu still appears and this has been a common thing through the versions. I read it was supposed to go away if you set that flag.

I also disabled hide webrtc behind MDNs hostnames. Couldn't find any other relevant flags.

I have a firewall and blocked port 1900 but keep getting denials on it every few minutes when chromium is open. I do not see what it's doing on windows over time but I also blocked port 1900 as it tries to connect on open.

**Comment by Eloston** [comment]
Well the easiest way to know what's happening is to dig through the source code to see what's sending SSDP. The Cast menu behavior you described might be related.

**Comment by Ph0rk0z** [comment]
Maybe related to what's left of cloud print? I will try out https://www.vastorigins.com/2019/01/disable-mdns-and-ssdp-discovery-in.html and see if that helps.

The cast thing has been happening since at least 67. I don't know how this works on regular chrome since I've never installed it.

**Comment by kramred** [comment]
I've also observed this behavior starting from version 80.0.3987.100 on macOS, see also my comment in the respective PR https://github.com/Eloston/ungoogled-chromium/pull/934#issuecomment-586530728
Maybe something [introduced in that version](https://chromium.googlesource.com/chromium/src.git/+log/86f7c91cf23bceaaeebbd6a0d1d46626ac68d924..2629099321c1cc57846878fcca7f9983ca38401b?n=1000&pretty=fuller) or in the [changes of the patches](https://github.com/Eloston/ungoogled-chromium/pull/927/files#diff-e3139a31351fe3fac6a974c9f620f766L37) can give a hint what is causing it.

**Comment by Ph0rk0z** [comment]
Did some investigation. Set policies in /etc/chromium/policies/managed

enablemediarouter - turned off the cast button and warned "some settings are managed by your organization but the connections continued.

BTW, the requests happen twice every 2 minutes.

Then I disabled the cloud print proxy "cloudprintproxyenabled" and the requests have stopped. You can also select what types of printer cloud print uses... by default it shares your local printers with google! Just wow.

**Comment by PF4Public** [comment]
Could this cloudprintproxy be disabled any other way, like flags?

**Comment by Ph0rk0z** [comment]
I only see: #enable-cloud-printer-handler in flags, try it and see.

**Comment by PF4Public** [comment]
> I only see: #enable-cloud-printer-handler in flags, try it and see.

Given its description it is some other feature.

**Comment by Eloston** [comment]
> Then I disabled the cloud print proxy "cloudprintproxyenabled" and the requests have stopped.

So maybe this is Cloud Print related? That feature is entirely Google-dependent, so we should patch that out if this is the cause.

**Comment by Ph0rk0z** [comment]
100% the cause. I was surprised it never got patched out. Shouldn't the same go for sign in? Wouldn't the URLs to try be al asdfklj8sd.com?

**Comment by Eloston** [comment]
> I was surprised it never got patched out.

Usually it's easier to upgrade our existing code than scan through the commit log between major versions, so we're bound to miss changes like these. At the very least, domain substitution and our existing changes makes it very unlikely that it would share your data with Google.

> Shouldn't the same go for sign in? 

Sign-in has been patched out a while ago; could you clarify what you mean?

**Comment by Ph0rk0z** [comment]
Seeing the menus for it. I usually set the flag to hide avatar but I assumed it did something and failed when you tried.

**Comment by ObeseChicken** [comment]
I am still getting requests on port 1900 even with the printing disabled!

**Comment by Ph0rk0z** [comment]
Log has been empty here. I have propagated the policies across all my machines.

**Comment by Ahrotahn** [comment]
I think I figured this one out.  The DIAL registry has it's own timer set to send out SSDP broadcasts every two minutes.  It does this even if nothing else is using it to broadcast (like casting or cloud printing).  

I'll submit a PR in a bit that addresses this and has been working well for me.  Please give it shot and let me know if it clears up the network spam for you.  
I don't have anything I can cast to, so if you have one it would be a good idea to test that out and make sure it still functions properly.  There will still be an SSDP broadcast burst when clicking "Cast..." in the menu of course.
