### ISSUE TITLE
Google Speech API Question/Issue

### ISSUE THREAD

**Issue by UniqueActive** [Eloston/ungoogled-chromium#994]
Hello,

since Firefox currently has an issue in its WebRTC implementation, I am looking for an alternative temporary solution to use for Jitsi Meet. I would like to go with ungoogled chromium over chrome or chromium, but it appears that Jitsi uses the Google Speech API mentioned in the FAQ (the errors indicate as much).

Is there any more information on this or perhaps a way to work around it or force Jitsi to work differently? I would be happy if someone here could explain how this API works and how it is problematic because the FAQ is a bit sparse on details there and search engines return all sorts of confusing results. :)

Thanks in advance!

**Comment by Eloston** [comment]
I use Jitsi Meet just fine on ungoogled-chromium. There's probably an issue with your setup or your internet connection.

What errors are you getting?

**Comment by UniqueActive** [comment]
@Eloston I am getting errors as mentioned in the FAQ:
```
[4062:4067:0411/065220.883806:ERROR:url_request.cc(586)] Block URL in URLRequest: https://update.9oo91eapis.qjz9zk/service/update2/json?cup2key=9:2821697705&cup2hreq=81e68254af2276afbb5756e62f1caaf309ea1526d647602806029ef68791001e
[4062:4067:0411/065220.883896:ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://update.9oo91eapis.qjz9zk/service/update2/json?cup2key=9:2821697705&cup2hreq=81e68254af2276afbb5756e62f1caaf309ea1526d647602806029ef68791001e
```
I also found a workaround: When starting with the argument `--use-fake-ui-for-media-stream` it works fine. I also tested this in regular Chromium and ran into the same issue with the same solution, so it may well be an issue with my setup. I am just not sure what exactly it is, though for now the workaround works.

**Comment by Eloston** [comment]
> I also found a workaround: When starting with the argument --use-fake-ui-for-media-stream it works fine. I also tested this in regular Chromium and ran into the same issue with the same solution, so it may well be an issue with my setup. I am just not sure what exactly it is, though for now the workaround works.

That means you won't be streaming your video and/or audio to other users. But the fact that you get this in regular Chromium means it's an issue out of our control.

> I am getting errors as mentioned in the FAQ

Those errors are different than the ones for Google Speech API. I get those messages too, and I think it's because there's some background service that's trying (and failing) to check for component or browser updates; it's hard to tell without looking into the source code.
